-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."ACC_ACCT"
   (	"ACC_ACCT_NUM" NUMBER(18,0),
	"ACCT_NUMBER" VARCHAR2(20),
	"IS_DELETED" CHAR(1),
	"ACC_COST_CENTER_NUM" NUMBER(18,0),
	"ACC_ACCT_TYPE_NUM" NUMBER(18,0),
	"STATUS" CHAR(1),
	"ACC_BALANCE_NUM" NUMBER(18,0),
	"NAME" VARCHAR2(200),
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE,
	"STATUS_CHANGE_REASON" VARCHAR2(255),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
