-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."ACCOUNT_CREDIT_CARD"
   (	"ACCOUNT_CREDIT_CARD_NUM" NUMBER(18,0),
	"PATIENT_NUM" NUMBER(18,0),
	"CARD_TYPE_NUM" NUMBER(9,0),
	"EXPIRATION_DATE" DATE,
	"CHARGE_CARD_NUM" VARCHAR2(200),
	"KEY_ALIAS" VARCHAR2(20),
	"CARDHOLDER_NAME" VARCHAR2(61),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
