-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."ANCILLARY_ITEM"
   (	"ANCILLARY_ITEM_NUM" NUMBER(18,0),
	"INVENTORY_SKU_NUM" NUMBER(18,0),
	"EXPIRATION_DATE" DATE,
	"ORIGIN_DATE" DATE,
	"COST" NUMBER(17,6),
	"PRICE" NUMBER(17,6),
	"QUANTITY" NUMBER(16,8),
	"ORIGINAL_QUANTITY" NUMBER(16,8),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"RECOMMENDED_QTY" NUMBER(16,8),
	"NUM_UPDATES" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(18,0)
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("AUD_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
