-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."AUDIT_EXTRACT_T"
   (	"PATIENT_NUM" NUMBER,
	"FILL_STATE_KEY" NUMBER,
	"RX_NUMBER" VARCHAR2(20),
	"FACILITY_NUM" NUMBER,
	"TP_PATIENT_NUM" NUMBER,
	"PRESCRIBER_ADDRESS_NUM" NUMBER,
	"PRESCRIBER_NUM" NUMBER,
	"TP_MESSAGE_KEY" NUMBER,
	"RX_FILL_SEQ" NUMBER,
	"DISPENSED_PROD_NUM" NUMBER,
	"FILL_STATE_NUM" NUMBER,
	"TP_PROCESSOR_DEST_NUM" NUMBER,
	"TP_ITEM_CLAIM_KEY" NUMBER,
	"TP_ITEM_CLAIM_NUM" NUMBER,
	"FILL_STATE_PRICE_NUM" NUMBER,
	"SYSTEM_USER" NUMBER,
	"ORDER_KEY" NUMBER,
	"ITEM_KEY" NUMBER,
	"DISPENSED_DRUG_NUM" NUMBER,
	"WRITTEN_DRUG_NUM" NUMBER,
	"RX_RECORD_NUM" NUMBER(18,0)
   ) ;
-- ==========================================
