-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."AUDIT_EXTRACT_HISTORY"
   (	"EXTRACT_HISTORY_NUM" NUMBER,
	"RUN_DTSTMP" TIMESTAMP (6),
	"START_DTSTMP" TIMESTAMP (6),
	"END_DTSTMP" TIMESTAMP (6),
	"RUN_TYPE" CHAR(1),
	"RUN_STATUS" NUMBER,
	"START_SEQ" NUMBER,
	"END_SEQ" NUMBER,
	"RECORD_COUNT" NUMBER,
	 CONSTRAINT "PK_AUDIT_EXTRACT_HISTORY" PRIMARY KEY ("EXTRACT_HISTORY_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "CK_AUDIT_EXTRACT_HISTORY_01" CHECK (RUN_TYPE In ('A','M')) ENABLE,
	 CONSTRAINT "CK_AUDIT_EXTRACT_HISTORY_02" CHECK (RUN_STATUS in (0,1,2)) ENABLE
   ) ;
-- ==========================================
