-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."COUNSELING_NOTE"
   (	"COUNSELING_NOTE_SEQ" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"NOTE_TEXT" VARCHAR2(4000),
	"CREATE_USER" NUMBER(18,0),
	"CREATE_DATE" DATE,
	"PRIORITY_INDICATOR" CHAR(1),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"H_TYPE" CHAR(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("AUD_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
