-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."CP_PATIENT_STATUS"
   (	"CP_PATIENT_STATUS_NUM" NUMBER(18,0),
	"CLINICAL_PROGRAM_NUM" NUMBER(18,0),
	"PATIENT_ID" VARCHAR2(100),
	"LOCATION_ID" VARCHAR2(1000),
	"STATUS" VARCHAR2(30),
	"LAST_UPDATED" DATE,
	"UPDATED_BY" VARCHAR2(50),
	"PARTITION_DATE" DATE,
	"PMS_FACILITY_ID" VARCHAR2(100),
	"PMS_FACILITY_NUM" NUMBER(18,0),
	"PMS_PATIENT_NUM" NUMBER(18,0),
	"VENDOR_PATIENT_ID" VARCHAR2(100),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"H_TYPE" CHAR(1),
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("AUD_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
