-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."CPS_CLINICAL_PROGRAM"
   (	"CLINICAL_PROGRAM_NUM" NUMBER(18,0),
	"LOCATION_ID" VARCHAR2(100),
	"TAG" VARCHAR2(30),
	"NAME" VARCHAR2(60),
	"DESCRIPTION" VARCHAR2(600),
	"PROGRAM_TYPE" VARCHAR2(50),
	"STATUS" VARCHAR2(30),
	"LOGO_URL" VARCHAR2(1000),
	"ICON_URL" VARCHAR2(1000),
	"DISPLAY_MESSAGE_DAYS" NUMBER(3,0),
	"LAST_UPDATED" DATE,
	"UPDATED_BY" VARCHAR2(50),
	"ENROLLMENT_TYPE" VARCHAR2(30),
	"PARTITION_DATE" DATE,
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"H_TYPE" CHAR(1),
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"CHECKIN" CHAR(1)
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("AUD_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
