-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."CREDIT_CARD_TYPE_OLD"
   (	"CREDIT_CARD_TYPE_NUM" NUMBER(18,0),
	"CARD_TYPE_DESC" VARCHAR2(100),
	"CARD_NUMBER_LENGTH" NUMBER(9,0),
	"CVV_NUMBER_LENGTH" NUMBER(9,0),
	"CARD_TYPE_STATUS" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"CARD_TYPE_DESC_ABBREVIATION" VARCHAR2(10)
   )
  PARTITION BY RANGE ("DATESTAMP")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
