-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."DUR_CONFLICT_DRUG_FOOD"
   (	"DUR_CONFLICT_NUM" NUMBER(18,0),
	"MESSAGE" VARCHAR2(255),
	"DESCRIPTION" VARCHAR2(255),
	"DRUG_CUSTOM_ID" VARCHAR2(15),
	"DRUG_DESC" VARCHAR2(50),
	"DRUG_ID" VARCHAR2(15),
	"ID" VARCHAR2(15),
	"DRUG_TYPE" VARCHAR2(25),
	"MONOGRAPH_ID" VARCHAR2(15),
	"SCREEN_MESSAGE" VARCHAR2(4000),
	"SIGNIFICANCE" CHAR(5),
	"USER_DEFINED_CATEGORY" CHAR(5),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_KEY" NUMBER(18,0),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"MECHANISM_OF_ACTION" CLOB,
	"CLINICAL_EFFECTS" CLOB,
	"PATIENT_MANAGEMENT" CLOB,
	"MANAGEMENT_LEVEL_CODE" VARCHAR2(50),
	"AVOIDANCE_LEVEL" VARCHAR2(50),
	"ONSET_TEXT" VARCHAR2(50)
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
