-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."ELIGIBILITY_CLARIF_OLD"
   (	"ELIGIBILITY_CLARIF_NUM" NUMBER(18,0),
	"DESCRIPTION" VARCHAR2(30),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER,
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100)
   ) ;
-- ==========================================
