-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."EXTPAY_TRANS_XREF"
   (	"EXTPAY_ID" NUMBER(18,0),
	"CC_TRANS_REQUEST_NUM" NUMBER(18,0),
	"TX_ID" VARCHAR2(300),
	"STATUS_MESSAGE" VARCHAR2(4000),
	"STATUS_CODE" VARCHAR2(10),
	"ACCEPTED_RX" VARCHAR2(4000),
	"DECLINED_RX" VARCHAR2(4000),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"PARTITION_DATE" DATE,
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"RESP_PATIENT_NUM" NUMBER(18,0)
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("AUD_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2013-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
