-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."FF_CONFIG"
   (	"FF_CONFIG_NUM" NUMBER(18,0),
	"FEED_FORMAT" VARCHAR2(50),
	"RECORD_FORMAT" VARCHAR2(50),
	"FILE_LAYOUT" CLOB,
	"POSITIVE_FILL_STATE_CODE" NUMBER,
	"NEGATIVE_FILL_STATE_CODE" NUMBER,
	"EXCLUDE_TP_ONLINE" CHAR(1),
	"EXCLUDE_TP_MANUAL" CHAR(1),
	"EXCLUDE_CASH" CHAR(1),
	"EXCLUDE_100_COPAY" CHAR(1),
	"EXCLUDE_SAME_DAY_REVERSAL" CHAR(1),
	"DATESTAMP" DATE,
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"FF_ENABLE" CHAR(1),
	 CONSTRAINT "PK_FF_CONFIG" PRIMARY KEY ("FF_CONFIG_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
