-- ==========================================

  CREATE GLOBAL TEMPORARY TABLE "TREXONE_AUD_DATA"."FILL_FACT_T"
   (	"FILL_STATE_PRICE_NUM" NUMBER,
	"TP_ITEM_CLAIM_NUM" NUMBER,
	"FILL_STATE_CHG_TS" DATE,
	"TP_MESSAGE_NUM" NUMBER,
	"FILL_STATE_CODE" VARCHAR2(2),
	"PRESCRIBER_NUM" NUMBER,
	"PRESCRIBER_ADDRESS_NUM" NUMBER,
	"ORDER_NUM" NUMBER,
	"ITEM_SEQ" NUMBER,
	"FILL_STATE_NUM" NUMBER,
	"FILL_STATE_KEY" NUMBER,
	"DATESTAMP" DATE
   ) ON COMMIT DELETE ROWS ;
-- ==========================================
