-- ==========================================

  CREATE GLOBAL TEMPORARY TABLE "TREXONE_AUD_DATA"."GTT_RX_DIVEST_DATA"
   (	"PATIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_NUMBER" VARCHAR2(20) NOT NULL ENABLE,
	"RX_RX_RECORD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"IMAGE_GROUP_NUM" NUMBER(18,0),
	"RF_RX_RECORD_NUM" NUMBER(18,0),
	"REFILL_NUM" NUMBER(18,0),
	"RX_FILL_SEQ" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) NOT NULL ENABLE
   ) ON COMMIT PRESERVE ROWS ;
-- ==========================================
