-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."IMAGE"
   (	"IMAGE_NUM" NUMBER(18,0),
	"TYPE" VARCHAR2(30),
	"IS_ASSIGNED" CHAR(1),
	"IMAGE" BLOB,
	"NAME" VARCHAR2(70),
	"FILE_FORMAT" VARCHAR2(10),
	"SCAN_USER" NUMBER(18,0),
	"SCAN_DATE" DATE,
	"ASSIGN_USER" NUMBER(18,0),
	"ASSIGN_DATE" DATE,
	"BARCODE" VARCHAR2(255),
	"DATA_GROUP" NUMBER(18,0),
	"DEVICE_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(18,0),
	"PARTITION_KEY" NUMBER(18,0),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PREFERRED_BRIGHTNESS" NUMBER(4,0),
	"PREFERRED_CONTRAST" NUMBER(4,0),
	"PREFERRED_ROTATE_ANGLE" NUMBER(6,2),
	"PREFERRED_SCALE" NUMBER(6,2)
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
