-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."INBOUND_MSG_QUEUE"
   (	"INBOUND_MSG_QUEUE_NUM" NUMBER(18,0),
	"OUTBOUND_MSG_QUEUE_NUM" NUMBER(18,0),
	"HTTP_HEADERS" VARCHAR2(4000),
	"HTTP_METHOD" VARCHAR2(20),
	"REQUEST_CONTENT" CLOB,
	"HTTP_STATUS" NUMBER(18,0),
	"RESPONSE_CONTENT" CLOB,
	"PARTITION_DATE" DATE,
	"REQUEST_URI" VARCHAR2(4000),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"H_TYPE" CHAR(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("AUD_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2013-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
