-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."IVR_ORDER"
   (	"IVR_ORDER_NUM" NUMBER(18,0),
	"ELECTRONIC_ORDER_NUM" NUMBER(18,0),
	"PICKUP_DATE" DATE,
	"LANGUAGE_NUM" NUMBER(18,0),
	"IS_SUBMIT_HANGUP" CHAR(1),
	"SUBMIT_DATE" DATE,
	"PICKUP_DATE_SRC" VARCHAR2(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_KEY" NUMBER(18,0),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"FACILITY_NUM" NUMBER(18,0),
	"LOCALE_NUM" NUMBER(18,0),
	"IS_PROCESSED" CHAR(1),
	"TRANSFER_FACILITY_NUM" NUMBER(18,0),
	"DELIVERY_METHOD_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"MAIL_CC_LAST4" CHAR(4),
	"MAIL_CC_TYPE" VARCHAR2(10),
	"SHIPPING_ADDRESS_NUM" NUMBER(18,0),
	"SHIPPING_ADDR_USAGE" VARCHAR2(10),
	"MAIL_CC_EXP_DATE" VARCHAR2(7),
	"CLINICAL_PROGRAM_NUM" NUMBER(18,0),
	"ORDER_SOURCE_TYPE_NUM" NUMBER(18,0),
	"PAYMENT_METHOD" VARCHAR2(50)
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
