-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."LTC_PACKAGING_METHOD"
   (	"LTC_PACKAGING_METHOD_NUM" NUMBER(18,0),
	"LTC_FACILITY_NODE_NUM" NUMBER(18,0),
	"NAME" VARCHAR2(100),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"IS_DEFAULT" CHAR(1),
	"IS_IN_USE" CHAR(1),
	"NUMBER_OF_LABELS" NUMBER(9,0),
	"DOC_TYPE_NAME" VARCHAR2(30),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"SPECIAL_PACKAGING_CODE" CHAR(1)
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
