-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."LTC_RX_PRESCRIBER_ORDER"
   (	"LTC_RX_PRESCRIBER_ORDER_NUM" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"TYPE" VARCHAR2(30),
	"IS_ON_HOLD" CHAR(1),
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE,
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"PRESCRIBER_NUM" NUMBER(18,0),
	"LTC_HOA_NUM" NUMBER(18,0),
	"TEXT" VARCHAR2(1500),
	"EFFECTIVE_DATE" DATE,
	"TERMINATION_DATE" DATE,
	"PRINT_ORDER" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
