-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."PATIENT_ID_NCPDP"
   (	"PATIENT_ID_NCPDP_NUM" NUMBER(18,0),
	"PATIENT_NUM" NUMBER(18,0),
	"QUALIFIER" VARCHAR2(2),
	"IDENTIFIER" VARCHAR2(20),
	"ID_STATE" VARCHAR2(2),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"ID_EXPIRATION_DATE" DATE
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
