-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."PATIENT_PERM_RX"
   (	"PATIENT_PERM_RX_NUM" NUMBER(18,0),
	"PATIENT_NUM" NUMBER(18,0),
	"PRODUCT_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"FIRST_FILL_QTY" NUMBER(13,3),
	"TOTAL_DAILY_DOSE" NUMBER(13,3),
	"CREATE_DATE" DATE,
	"EXPIRY_DATE" DATE,
	"LATIN_FREQUENCY_CODE" VARCHAR2(10),
	"LATIN_FREQUENCY_QTY" NUMBER(9,0),
	"DAYS_SUPPLY" NUMBER(9,0),
	"USER_INSTRUCTIONS" VARCHAR2(2000),
	"UNEXPANDED_DIRECTIONS" VARCHAR2(2000),
	"IS_ACTIVE" CHAR(1),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PARTITION_DATE" DATE,
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"H_TYPE" CHAR(1),
	"H_LEVEL" NUMBER,
	"LTC_PRINT_ON_MAR_REPORT" CHAR(1),
	"LTC_PRINT_ON_POF_REPORT" CHAR(1),
	"DOSE" NUMBER(13,3)
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
