-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."PATIENT_QUESTIONNAIRE"
   (	"PATIENT_QUESTIONNAIRE_NUM" NUMBER(18,0),
	"PATIENT_ID" VARCHAR2(100),
	"CLINICAL_PROGRAM_NUM" NUMBER(18,0),
	"MESSAGE_NUM" NUMBER(18,0),
	"QUESTIONNAIRE_DATA" CLOB,
	"SUBMITTED_DATE" DATE,
	"LAST_UPDATED" DATE,
	"UPDATED_BY" VARCHAR2(100),
	"PMS_FACILITY_NUM" NUMBER(18,0),
	"SYSTEM_DUE_DATE" DATE,
	"DUE_DATE_OVERRIDE" DATE,
	"SILO_ID" VARCHAR2(50),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"DATESTAMP" DATE,
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"H_TYPE" CHAR(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("AUD_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
