-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."PAYMENT_GROUP_OLD"
   (	"PAYMENT_GROUP_NUM" NUMBER(18,0),
	"GROUP_HEALTH_CARD_TYPE" VARCHAR2(30),
	"PAYMENT_GROUP_AMOUNT_CALC" NUMBER(17,6),
	"PATIENT_PAY_AMOUNT_CALC" NUMBER(17,6),
	"CALCULATION_DTSTAMP" DATE,
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE DEFAULT sysdate,
	"PARTITION_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("DATESTAMP")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
