-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."PDMP_RESPONSE_ERROR"
   (	"PDMP_RESPONSE_ERROR_NUM" NUMBER(18,0),
	"PDMP_RESPONSE_NUM" NUMBER(18,0),
	"MESSAGE_TYPE" CHAR(1),
	"MESSAGE" VARCHAR2(2048),
	"DETAILS" CLOB,
	"SOURCE" VARCHAR2(100),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("AUD_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
