-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."POS_FINALIZATION"
   (	"POS_FINALIZATION_NUM" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"RX_FILL_SEQ" NUMBER(18,0),
	"TXN_TYPE" CHAR(1),
	"REGISTER_TXN" NUMBER(9,0),
	"REGISTER_TXN_SEQ" NUMBER(9,0),
	"POS_USERID" VARCHAR2(20),
	"POS_AMOUNT" NUMBER(17,6),
	"POS_DATESTAMP" DATE,
	"PATIENT_PAY_SRC" CHAR(1),
	"PRICE_OVERRIDE_RSN_CD" CHAR(2),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_KEY" NUMBER(18,0),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"POS_TAX_AMOUNT" NUMBER(17,6),
	"REGISTER_NUM" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTIAL_FILL_NUM" NUMBER(2,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
