-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."PRICE_LINK_RULE"
   (	"PRICE_LINK_RULE_NUM" NUMBER(18,0),
	"PRICE_LINK_RULE_SET_NUM" NUMBER(18,0),
	"MASTER_PRODUCT_NUM" NUMBER(18,0),
	"PROCESS_ORDER" NUMBER(9,0),
	"EXCLUDE_FROM_LINKING" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"DATA_FILTER" CLOB,
	"PARTITION_DATE" DATE,
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"H_TYPE" CHAR(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("AUD_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2013-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
