-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."PRINT_DEVICE_TYPE"
   (	"PRINT_DEVICE_TYPE_NUM" NUMBER(18,0),
	"NAME" VARCHAR2(30),
	"DESCRIPTION" VARCHAR2(256),
	"IS_COLOR_CAPABLE" CHAR(1),
	"IS_DUPLEX_CAPABLE" CHAR(1),
	"IS_DEFAULT" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"LANGUAGE" VARCHAR2(10),
	"FONTS" VARCHAR2(2048),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"DATA_GROUP" NUMBER(18,0)
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
