-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."PRODUCT_CHARACTERISTICS"
   (	"PRODUCT_CHARACTERISTICS_NUM" NUMBER(18,0),
	"PRODUCT_NUM" NUMBER(18,0),
	"IMAGE_SOURCE_CODE" VARCHAR2(20),
	"IS_DEFAULT" CHAR(1),
	"ORIGINAL_EFFECTIVE_DATE" DATE,
	"ORIGINAL_EXPIRATION_DATE" DATE,
	"EFFECTIVE_DATE" DATE,
	"EXPIRATION_DATE" DATE,
	"FLAVOR_CODE" VARCHAR2(30),
	"COLOR_CODE" VARCHAR2(25),
	"SHAPE_CODE" VARCHAR2(30),
	"IMPRINT1" VARCHAR2(45),
	"IMPRINT2" VARCHAR2(45),
	"MARKS_CODE" VARCHAR2(25),
	"IMAGE_NUM" NUMBER(18,0),
	"ORIGINAL_MANUFACTURER" VARCHAR2(30),
	"MANUFACTURER" VARCHAR2(30),
	"REPACKAGER_CODE" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"CLARITY_CODE" VARCHAR2(30),
	"COATING_CODE" VARCHAR2(30)
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
