-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."PRODUCT_STATE_OVERRIDE"
   (	"PRODUCT_STATE_OVERRIDE_NUM" NUMBER(18,0),
	"PRODUCT_NUM" NUMBER(18,0),
	"CTRY_CODE" VARCHAR2(8),
	"STATE_CODE" VARCHAR2(2),
	"DRUG_SCHEDULE" VARCHAR2(30),
	"IS_REPORTABLE" CHAR(1),
	"IS_SCHEDULED_RX_ID_REQ" CHAR(1),
	"IS_TAX_EXEMPT" CHAR(1),
	"IS_MANDATED" CHAR(1),
	"PRICE_BOARD_QUANTITY" NUMBER(16,8),
	"PRICE_BOARD_QUANTITY2" NUMBER(16,8),
	"PRICE_BOARD_QUANTITY3" NUMBER(16,8),
	"PRICE_BOARD_QUANTITY4" NUMBER(16,8),
	"PRICE_BOARD_QUANTITY5" NUMBER(16,8),
	"BILLING_UNITS" VARCHAR2(2),
	"FORMULARY_INDICATOR" VARCHAR2(1),
	"FORMULARY_IND_EFFECTIVE_DATE" DATE,
	"PACKAGE_SIZE_DIVISOR" NUMBER(11,3),
	"QUANTITY_BILL_UNITS" VARCHAR2(10),
	"BILLING_CODE" VARCHAR2(11),
	"BILLING_CODE_EFFECTIVE_DATE" DATE,
	"GENERIC_BILLING_CODE" VARCHAR2(11),
	"GENERIC_BC_EFFECTIVE_DATE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PRODUCT_FACILITY_NUM" NUMBER(18,0)
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
