-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."PURCHASE_ORDER_ACK"
   (	"PURCHASE_ORDER_ACK_NUM" NUMBER(18,0),
	"VENDOR_NUM" NUMBER(18,0),
	"PURCHASE_ORDER_NUM" NUMBER(18,0),
	"DATE_RECEIVED" DATE,
	"ACKNOWLEDGEMENT_TYPE_CODE" CHAR(2),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"TRANSACTION_SET_CTRL_NUMBER" VARCHAR2(9),
	"INTERCHANGE_CTRL_NUMBER" NUMBER(9,0)
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
