-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."PURGE_AUDIT_TABLE_LIST"
   (	"TABLE_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"RETENTION_YEARS" NUMBER(2,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(30),
	 CONSTRAINT "UC_PURGE_AUDIT_TABLE_LIST_01" UNIQUE ("TABLE_NAME")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
