-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."RX_FILL_INGREDIENT_INFO"
   (	"RX_FILL_ING_INFO_NUM" NUMBER(18,0),
	"RX_FILL_SEQ" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"PRODUCT_INGREDIENT_NUM" NUMBER(18,0),
	"INGREDIENT_LOT_NUMBER" VARCHAR2(20),
	"INGREDIENT_EXPIRATION_DATE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_DATE" DATE,
	"PARTITION_KEY" NUMBER(18,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
