-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."RX_FILL_DUR_CONFLICT"
   (	"RX_FILL_DUR_CONFLICT_NUM" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"RESPONSE_RECEIVED_TIME" DATE,
	"REQUEST_MADE_TIME" DATE,
	"ACKNOWLEDGING_USER_NUM" NUMBER(18,0),
	"COMMENTS_USER_DESC" VARCHAR2(255),
	"RESULT_USER_DESC" VARCHAR2(255),
	"CONSULTED_USER_DESC" VARCHAR2(255),
	"PROBLEM_USER_DESC" VARCHAR2(255),
	"RX_FILL_SEQ" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_KEY" NUMBER(18,0),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"IS_INT_DUR_WITH_CLAIM" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
