-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."TP_DUR_PPS"
   (	"TP_DUR_PPS_NUM" NUMBER(18,0),
	"TP_ITEM_CLAIM_NUM" NUMBER(18,0),
	"DISPLAY_SEQ" NUMBER(18,0),
	"REASON_FOR_SERVICE_CODE" VARCHAR2(2),
	"PROFESSIONAL_SERVICE_CODE" VARCHAR2(2),
	"RESULT_OF_SERVICE" VARCHAR2(2),
	"LEVEL_OF_EFFORT" VARCHAR2(2),
	"CO_AGENT_ID_QUALIFIER" VARCHAR2(100),
	"CO_AGENT_ID" VARCHAR2(100),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE,
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
