-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."TP_MESSAGE_EXCEPTION"
   (	"TP_MESSAGE_EXCEPTION_NUM" NUMBER,
	"TP_MESSAGE_KEY" NUMBER,
	"TP_MESSAGE_NUM" NUMBER,
	"TP_CASH_MESSAGE_NUM" NUMBER,
	"TP_ITEM_CLAIM_NUM" NUMBER,
	"TP_PROCESSOR_DESTINATION_SEQ" NUMBER,
	"TP_PROCESSOR_NUM" NUMBER,
	"SUBMISSION_DATE" DATE,
	"SUBMISSION_STATUS" VARCHAR2(20),
	"MESSAGE_CATEGORY" CHAR(1),
	"COMM_FAILURE" CHAR(1),
	"SYS_USER" NUMBER,
	"DATESTAMP" DATE,
	"EE_DT" DATE,
	"REQUEST_RESPONSE_MESSAGE" CLOB,
	"MESSAGE_TYPE" CHAR(2),
	"MESSAGE_EXCEPTION" VARCHAR2(2000),
	"CREATE_DATE" DATE,
	"UPDATE_DATE" DATE,
	"STATUS" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100)
   ) ;
-- ==========================================
