-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."ADS_ACCURACY_SCAN"
   (	"ACCURACY_SCAN_NUM" NUMBER(18,0),
	"ORDER_NUM" NUMBER(18,0),
	"ITEM_SEQ" NUMBER(18,0),
	"DISPENSING_EVENT_SEQ" NUMBER(18,0),
	"IMAGE_GROUP_NUM" NUMBER(18,0),
	"DISPENSED_ITEM_SERIAL_NUMBER" VARCHAR2(20),
	"DISPENSED_ITEM_GTIN_NUMBER" VARCHAR2(25),
	"DISPENSED_ITEM_LOT_NUMBER" VARCHAR2(20),
	"DISPENSED_ITEM_EXPIRATION_DATE" DATE,
	"DATESTAMP" DATE,
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
