-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."AUDIT_EXTRACT_STATUS"
   (	"EXTRACT_STATUS_NUM" NUMBER,
	"RUN_TYPE" CHAR(1),
	"DESCRIPTION" VARCHAR2(100),
	"RUN_DTSTMP" TIMESTAMP (6),
	"STATUS" NUMBER,
	 CONSTRAINT "PK_AUDIT_EXTRACT_STATUS" PRIMARY KEY ("EXTRACT_STATUS_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "CK_AUDIT_EXTRACT_STATUS_01" CHECK (RUN_TYPE in ('A','M')) ENABLE,
	 CONSTRAINT "CK_AUDIT_EXTRACT_STATUS_02" CHECK (STATUS in (0,1,2)) ENABLE
   ) ;
-- ==========================================
