-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."AUDIT_EXTRACT_ERROR"
   (	"EXTRACT_ERROR_NUM" NUMBER,
	"EXTRACT_HISTORY_NUM" NUMBER,
	"PROCEDURE_NAME" VARCHAR2(50),
	"ERROR_MSG" VARCHAR2(100),
	"ORA_ERROR_NUM" VARCHAR2(10),
	"ORA_ERROR_MSG" VARCHAR2(150),
	 CONSTRAINT "PK_AUDIT_EXTRACT_ERROR" PRIMARY KEY ("EXTRACT_ERROR_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_AUDIT_EXTRACT_ERROR" FOREIGN KEY ("EXTRACT_HISTORY_NUM")
	  REFERENCES "TREXONE_AUD_DATA"."AUDIT_EXTRACT_HISTORY" ("EXTRACT_HISTORY_NUM") ENABLE
   ) ;
-- ==========================================
