-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."AUDIT_EXTRACT_COMPOUND"
   (	"AUDIT_EXTRACT_NUM" NUMBER,
	"CMP_DOSAGE_FORM_DESC_CODE" VARCHAR2(2),
	"CMP_DISPENSING_UNIT_FORM_IND" VARCHAR2(10),
	"CMD_ROUTE_OF_ADMIN" VARCHAR2(25),
	"CMP_INGREDIENT_COMPONENT_COUNT" NUMBER,
	"CMD_REPEATING_FIELDS1" VARCHAR2(80),
	"CMD_REPEATING_FIELDS2" VARCHAR2(80),
	"CMD_REPEATING_FIELDS3" VARCHAR2(80),
	"CMD_REPEATING_FIELDS4" VARCHAR2(80),
	"CMD_REPEATING_FIELDS5" VARCHAR2(80),
	"CMD_REPEATING_FIELDS6" VARCHAR2(80),
	"CMD_REPEATING_FIELDS7" VARCHAR2(80),
	"CMD_REPEATING_FIELDS8" VARCHAR2(80),
	"CMD_REPEATING_FIELDS9" VARCHAR2(80),
	"CMD_REPEATING_FIELDS10" VARCHAR2(80),
	"CMD_REPEATING_FIELDS11" VARCHAR2(80),
	"CMD_REPEATING_FIELDS12" VARCHAR2(80),
	"CMD_REPEATING_FIELDS13" VARCHAR2(80),
	"CMD_REPEATING_FIELDS14" VARCHAR2(80),
	"CMD_REPEATING_FIELDS15" VARCHAR2(80),
	"CMD_REPEATING_FIELDS16" VARCHAR2(80),
	"CMD_REPEATING_FIELDS17" VARCHAR2(80),
	"CMD_REPEATING_FIELDS18" VARCHAR2(80),
	"CMD_REPEATING_FIELDS19" VARCHAR2(80),
	"CMD_REPEATING_FIELDS20" VARCHAR2(80),
	"CMD_REPEATING_FIELDS21" VARCHAR2(80),
	"CMD_REPEATING_FIELDS22" VARCHAR2(80),
	"CMD_REPEATING_FIELDS23" VARCHAR2(80),
	"CMD_REPEATING_FIELDS24" VARCHAR2(80),
	"CMD_REPEATING_FIELDS25" VARCHAR2(80),
	 CONSTRAINT "FK_AUDIT_EXTRACT_COMPOUND" FOREIGN KEY ("AUDIT_EXTRACT_NUM")
	  REFERENCES "TREXONE_AUD_DATA"."AUDIT_EXTRACT" ("AUDIT_EXTRACT_NUM") ENABLE
   ) ;
-- ==========================================
