-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."AUDIT_EXTRACT_HEADER"
   (	"EXTRACT_HISTORY_NUM" NUMBER,
	"START_DTSTMP" TIMESTAMP (6),
	"END_DTSTMP" TIMESTAMP (6),
	"CHAIN_ID" VARCHAR2(30),
	"STORE_NUMBER" VARCHAR2(10),
	"CLAIM_COUNT" NUMBER,
	"VERSION_NUM" NUMBER,
	"RUN_TYPE" CHAR(1),
	 CONSTRAINT "CK_AUDIT_EXTRACT_HEADER_01" CHECK (RUN_TYPE in ('A','M')) ENABLE,
	 CONSTRAINT "FK_AUDIT_EXTRACT_HEADER" FOREIGN KEY ("EXTRACT_HISTORY_NUM")
	  REFERENCES "TREXONE_AUD_DATA"."AUDIT_EXTRACT_HISTORY" ("EXTRACT_HISTORY_NUM") ENABLE
   ) ;
-- ==========================================
