-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."AUDIT_LAST_LOAD_SEQ"
   (	"TABLE_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"SEQ#" NUMBER,
	"LAST_LOAD_DATE" DATE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_AUD_DATA"."PK_AUDIT_LAST_LOAD_SEQ" ON "TREXONE_AUD_DATA"."AUDIT_LAST_LOAD_SEQ" ("TABLE_NAME")
  ;
ALTER TABLE "TREXONE_AUD_DATA"."AUDIT_LAST_LOAD_SEQ" ADD CONSTRAINT "PK_AUDIT_LAST_LOAD_SEQ" PRIMARY KEY ("TABLE_NAME")
  USING INDEX "TREXONE_AUD_DATA"."PK_AUDIT_LAST_LOAD_SEQ"  ENABLE;
-- ==========================================
