-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."CC_TRANS_RESPONSE_OLD"
   (	"CC_TRANS_RESPONSE_NUM" NUMBER(18,0),
	"CC_TRANS_REQUEST_NUM" NUMBER(18,0),
	"CC_TRANS_STATUS_MSG" VARCHAR2(300),
	"CC_TRANS_STATUS_CODE" VARCHAR2(10),
	"CC_TRANS_TERMINATION_MESSAGE" VARCHAR2(200),
	"CC_TRANS_RESPONSE_MESSAGE" VARCHAR2(300),
	"CC_TRANS_AUTHORIZATION_CODE" VARCHAR2(20),
	"CC_TRANS_ROUTING_ID" VARCHAR2(20),
	"CC_TRANS_PAYMENT_MEDIA" VARCHAR2(20),
	"CC_TRANS_PAYMENT_TYPE" VARCHAR2(20),
	"CC_TRANS_AVS_CODE" VARCHAR2(30),
	"CC_TRANS_CVV_VALIDATION_CODE" VARCHAR2(30),
	"CC_TRANS_COMMERCIAL_CARD_TYPE" VARCHAR2(30),
	"CC_TRANS_CC_AMOUNT" NUMBER(17,6),
	"CC_TRANS_PROCESSOR_TRANS_NUM" VARCHAR2(30),
	"CC_TRANS_PROCESSOR_TRANS_DATE" VARCHAR2(30),
	"CC_TRANS_PROCESSOR_TRANS_TIME" VARCHAR2(30),
	"CC_TRANS_REFERENCE_NUM" VARCHAR2(100),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"PARTITION_DATE" DATE
   )
  PARTITION BY RANGE ("DATESTAMP")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
