-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."CSR_RXFILL_TP_DETAIL"
   (	"CSR_RXFILL_EXTRACT_NUM" NUMBER(20,0),
	"TP_PLAN_NUM" NUMBER(18,0),
	"TP_PLAN_CODE" VARCHAR2(12),
	"TP_PLAN_NAME" VARCHAR2(45),
	"TP_PLAN_TYPE" VARCHAR2(10),
	"TP_PLAN_COVERAGE" VARCHAR2(2),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"NUM_UPDATES" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"BILLING_ORDER" NUMBER(2,0)
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2001-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
