-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."DUR_CONFLICT_DRUG_DISEASE"
   (	"DUR_CONFLICT_NUM" NUMBER(18,0),
	"CONDITION_CUSTOM_ID" VARCHAR2(35),
	"CONDITION_DESC" VARCHAR2(255),
	"CONDITION_ID" VARCHAR2(15),
	"DISEASE_DESC" VARCHAR2(255),
	"DETAIL_DRUG_DESC" VARCHAR2(255),
	"DRUG_CUSTOM_ID" VARCHAR2(15),
	"DRUG_DESC" VARCHAR2(50),
	"INTERNAL_DRUG_ID" VARCHAR2(15),
	"MEDICAL_CONDITION_DESC" VARCHAR2(255),
	"MEDICAL_CONDITION_ID" VARCHAR2(15),
	"SCREEN_MESSAGE" VARCHAR2(4000),
	"SEVERITY" VARCHAR2(20),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_KEY" NUMBER(18,0),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"COMMENTARY" CLOB
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
