-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."FACILITY_LOGIN"
   (	"FACILITY_LOGIN_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"SYSTEM_USER_NUM" NUMBER(18,0),
	"LOGIN_STATUS" CHAR(1),
	"LAST_ACTIVITY" DATE,
	"LAST_SERVICE_CALL" VARCHAR2(500),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
