-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."FACILITY_DAILY_HOURS_OLD"
   (	"FACILITY_DAILY_HOURS_NUM" NUMBER(18,0),
	"FACILITY_SCHEDULE_GROUP_NUM" NUMBER(18,0),
	"DAY_OF_WEEK_NUM" NUMBER(9,0),
	"OPEN_TIME" DATE,
	"CLOSE_TIME" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER,
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100)
   ) ;
-- ==========================================
