-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."FACILITY_LINK"
   (	"FACILITY_LINK_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"FACILITY_LINK_TYPE" CHAR(1),
	"LINKED_FACILITY_NUM" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"IS_ACTIVE" CHAR(1),
	"PRIORITY" NUMBER(3,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"FULFILLMENT_TYPE" CHAR(1)
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
