-- ==========================================

  CREATE GLOBAL TEMPORARY TABLE "TREXONE_AUD_DATA"."GTT_FACILITY_ADDRESS"
   (	"FACILITY_NUM" NUMBER,
	"ADDRESS1" VARCHAR2(100),
	"ADDRESS2" VARCHAR2(50),
	"ZIPCODE" VARCHAR2(20),
	"CTRY_CODE" VARCHAR2(8),
	"STATE_CODE" VARCHAR2(2),
	"COUNTY" VARCHAR2(30),
	"CITY" VARCHAR2(40),
	"POST_OFFICE" VARCHAR2(40)
   ) ON COMMIT PRESERVE ROWS ;
-- ==========================================
