-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."IMH_PATIENT_ALLERGY_SYMPT"
   (	"IMH_PATIENT_ALLERGY_SYMPT_NUM" NUMBER(18,0),
	"IMH_PATIENT_ALLERGY_NUM" NUMBER(18,0),
	"EXTERNAL_SYMPTOM_NUM" NUMBER(18,0),
	"DESCRIPTION" VARCHAR2(255),
	"STATUS" VARCHAR2(10),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
