-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."IMPORTED_PRESCRIBER_ERROR"
   (	"IMPORTED_PRESCRIBER_ERROR_NUM" NUMBER(18,0),
	"IMPORTED_PRESCRIBER_NUM" NUMBER(18,0),
	"ERROR_TEXT" VARCHAR2(255),
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE,
	"SYS_USER" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"ERROR_VALUE" VARCHAR2(256),
	"ERROR_TABLE" VARCHAR2(30),
	"ERROR_COLUMN" VARCHAR2(30),
	"ERROR_TABLE_PK" NUMBER(18,0),
	"ERROR_REASON" NUMBER(18,0),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
