-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."INVENTORY_LOT"
   (	"INVENTORY_LOT_NUM" NUMBER(18,0),
	"LOT_NUMBER" VARCHAR2(20),
	"SERIAL_NUMBER" VARCHAR2(20),
	"PURCHASE_DATE" DATE,
	"EXPIRATION_DATE" DATE,
	"QTY" NUMBER(16,8),
	"COST" NUMBER(17,6),
	"INVENTORY_ITEM_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("AUD_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
