-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."JOB_CONTROL"
   (	"BATCH#" NUMBER,
	"JOB_NAME" VARCHAR2(200),
	"START_DATE" DATE,
	"END_DATE" DATE,
	"STATUS" VARCHAR2(1)
   )
  PARTITION BY RANGE ("END_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
