-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."KEY_VALUE"
   (	"KEY_VALUE_NUM" NUMBER(18,0),
	"CLINICAL_PROGRAM_NUM" NUMBER(18,0),
	"PATIENT_ID" VARCHAR2(100),
	"CP_KEY" VARCHAR2(36),
	"CP_DESCRIPTION" VARCHAR2(1000),
	"CP_VALUE" VARCHAR2(4000),
	"UPDATED_BY" VARCHAR2(100),
	"ICON_URL" VARCHAR2(1000),
	"LAST_UPDATED" DATE,
	"KEY_TYPE" VARCHAR2(20),
	"VENDOR_PATIENT_ID" VARCHAR2(100),
	"PMS_PATIENT_NUM" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"H_TYPE" CHAR(1),
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PATIENT_QUESTIONNAIRE_NUM" NUMBER(18,0)
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("AUD_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
