-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."KEYSTORE_PROPERTY"
   (	"KEYSTORE_PROPERTY_NUM" NUMBER(18,0),
	"KEYSTORE_NUM" NUMBER(18,0),
	"KEYSTORE_PROPERTY_NAME" VARCHAR2(100),
	"KEYSTORE_PROPERTY_STRINGVALUE" VARCHAR2(4000),
	"KEYSTORE_ENTRY_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE DEFAULT sysdate,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID'),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
