-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."LTC_PATIENT"
   (	"LTC_PATIENT_NUM" NUMBER(18,0),
	"LTC_FACILITY_NODE_NUM" NUMBER(18,0),
	"PATIENT_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"STATUS" CHAR(1),
	"IS_FACILITY_LOCATION_INFO_USED" CHAR(1),
	"IS_ACTIVE" CHAR(1),
	"DISCHARGED_DATE" DATE,
	"STATUS_EFFECTIVE_DATE" DATE,
	"STATUS_TERMINATION_DATE" DATE,
	"ROOM" VARCHAR2(50),
	"BED" VARCHAR2(50),
	"ADMISSION_INFORMATION" VARCHAR2(255),
	"ADMITTED_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"LTC_PATIENT_ID" VARCHAR2(20),
	"STATUS_CHANGE_DATE" DATE
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
