-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."MAIL_DELIVERY_OPTIONS"
   (	"OPTIONS_NUM" NUMBER(18,0),
	"DATA_GROUP" NUMBER(18,0),
	"DELIVERY_METHOD_NUM" NUMBER(18,0),
	"SHIPPING_COURIER_NUM" NUMBER(18,0),
	"SHIPPING_METHOD_NUM" NUMBER(18,0),
	"COURIER_CHARGE" NUMBER(17,6),
	"SHIP_DAYS" NUMBER(3,0),
	"SHIPMENT_SIGNATURE_NUM" NUMBER(18,0),
	"HIGH_PRIORITY" CHAR(1),
	"PAYMENT_TYPE_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("AUD_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
