-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."MEDICAL_AUTHORIZATION"
   (	"MEDICAL_AUTHORIZATION_NUM" NUMBER(18,0),
	"PATIENT_NUM" NUMBER(18,0),
	"REPRESENTATIVE_NAME" VARCHAR2(30),
	"AUTHORIZED_PARTY" VARCHAR2(255),
	"EFFECTIVE_DATE" DATE,
	"TERMINATION_DATE" DATE,
	"SIGNATURE_IMAGE_NUM" NUMBER(18,0),
	"AUTH_FORM_IMAGE_NUM" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"COMMENT_TEXT" VARCHAR2(1000),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
