-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."PATIENT_ADDRESS"
   (	"PATIENT_NUM" NUMBER(18,0),
	"ADDRESS1" VARCHAR2(100),
	"ADDRESS2" VARCHAR2(50),
	"CITY" VARCHAR2(40),
	"STATE" VARCHAR2(2),
	"ZIP" VARCHAR2(20),
	"COUNTY" VARCHAR2(30),
	"CNTRY_CD" VARCHAR2(8),
	"POST_OFFICE" VARCHAR2(40),
	"PRIMARY_PATIENT_NUM" NUMBER(18,0),
	"LAST_NAME" VARCHAR2(50),
	"MIDDLE_NAME" VARCHAR2(50),
	"FIRST_NAME" VARCHAR2(50),
	"BIRTH_DATE" DATE,
	"GENDER" CHAR(1),
	"PHONE_NUM" VARCHAR2(30),
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "PK_PATIENT_ADDRESS" PRIMARY KEY ("PATIENT_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
