-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."PAYMENT_EXCEPTION_OLD"
   (	"PAYMENT_EXCEPTION_NUM" NUMBER(18,0),
	"CREDIT_CARD_PROCESSOR_NUM" NUMBER(18,0),
	"EXCEPTION_CODE" VARCHAR2(20),
	"EXCEPTION_CODE_DESCRIPTION" VARCHAR2(100),
	"EXCEPTION_TRANSACTION_TYPE" VARCHAR2(100),
	"EXCEPTION_TYPE" CHAR(1),
	"EXCEPTION_MESSAGE" VARCHAR2(200),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"EXCEPTION_TRANS_TYPE_FILTER" VARCHAR2(100),
	"EXCEPTION_MESSAGE_FILTER" VARCHAR2(200)
   )
  PARTITION BY RANGE ("DATESTAMP")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
