-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."PAYMENT_OLD"
   (	"PAYMENT_NUM" NUMBER(18,0),
	"ACCOUNT_MEMBER_CREDIT_CARD_NUM" NUMBER(18,0),
	"PAYMENT_TYPE_NUM" NUMBER(18,0),
	"PAYMENT_DATE" DATE,
	"PAYMENT_STATUS_NUM" NUMBER(18,0),
	"PAYMENT_SOURCE" CHAR(2),
	"PAYMENT_AMOUNT" NUMBER(17,6),
	"PAYMENT_REVERSAL_AMOUNT" NUMBER(17,6),
	"REVERSAL_PAYMENT_NUM" NUMBER(18,0),
	"CREDIT_AUTHORIZATION_NUMBER" VARCHAR2(100),
	"CHECK_NUMBER" VARCHAR2(100),
	"MONEY_ORDER_NUMBER" VARCHAR2(100),
	"OTHER_PAYMENT_ID" VARCHAR2(100),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"CREDIT_ROUTING_ID" VARCHAR2(100),
	"PRE_OR_VOICE_AUTH_ID" VARCHAR2(100),
	"SETTLEMENT_DATE" DATE,
	"FF_DATE" DATE,
	"AUTHORIZED_DATE" DATE,
	"COMPLETION_DATE" DATE,
	"CANCELLED_DATE" DATE,
	"ACC_AR_ACCT_NUM" NUMBER(18,0),
	"PAYMENT_ITEM_SEQ" NUMBER(18,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"PARTITION_DATE" DATE,
	"IS_RX_STATUS_CHANGE" CHAR(1),
	"HEALTH_CARD_DESIGNATION" VARCHAR2(20),
	"HEALTH_CARD_DESIGNATION_DATE" DATE
   )
  PARTITION BY RANGE ("DATESTAMP")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
