-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."PAYMENT_EXCEPTION_LINK_OLD"
   (	"PAYMENT_NUM" NUMBER(18,0),
	"PAYMENT_EXCEPTION_NUM" NUMBER(18,0),
	"CC_TRANS_REQUEST_NUM" NUMBER(18,0),
	"RESOLVED" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"AVS_VALIDATION_MESSAGE" VARCHAR2(100),
	"CVV_VALIDATION_MESSAGE" VARCHAR2(100),
	"ORDER_NUM" NUMBER(18,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"PARTITION_DATE" DATE
   )
  PARTITION BY RANGE ("DATESTAMP")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
