-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."PCS_PATIENT_COMM_PREF"
   (	"PCS_PATIENT_COMM_PREF_NUM" NUMBER(18,0),
	"PCS_PATIENT_COMM_SETTING_NUM" NUMBER(18,0),
	"PCS_COMM_METHOD_NUM" NUMBER(18,0),
	"CUSTOMER_ID" VARCHAR2(100),
	"LAST_UPDATED" DATE,
	"UPDATED_BY" VARCHAR2(50),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"DATESTAMP" DATE,
	"H_TYPE" CHAR(1),
	"H_LEVEL" NUMBER,
	"SILO_ID" VARCHAR2(50),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("AUD_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
