-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."PCS_PATIENT_PREFERENCE"
   (	"PCS_PATIENT_PREFERENCE_NUM" NUMBER(18,0),
	"PATIENT_NUM" NUMBER(18,0),
	"IS_MOBILE_APP_CUSTOMER" CHAR(1),
	"EVENTS_SUBSCRIBED" VARCHAR2(1000),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PARTITION_DATE" DATE,
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"H_TYPE" CHAR(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("AUD_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
