-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."POG_MEMBERSHIP_RULE"
   (	"POG_MEM_RULE_NUM" NUMBER(18,0),
	"PRODUCT_ORDERING_GROUP_NUM" NUMBER(18,0),
	"PRODUCT_NUM" NUMBER(18,0),
	"INCLUDE_EXCLUDE_FLAG" CHAR(1),
	"IS_DIRECT_INCLUSION" CHAR(1),
	"IS_PRIMARY_PRODUCT" CHAR(1),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"PARTITION_DATE" DATE,
	"H_TYPE" CHAR(1),
	"H_LEVEL" NUMBER(20,0),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"IS_ORDERING_PRODUCT" CHAR(1),
	"DATA_GROUP" NUMBER(18,0)
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
