-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."PPI_NETWORK"
   (	"PPI_NETWORK_NUM" NUMBER(18,0),
	"NETWORK_NAME" VARCHAR2(30),
	"PRIORITY" NUMBER(9,0),
	"STOP_IN_DATA_ENTRY_IND" CHAR(1),
	"AUTOPOPULATE_SIG_IND" CHAR(1),
	"USE_EXPECTED_DISCHARGE_IND" CHAR(1),
	"OUTBOUND_PPI_MSG_USER_ID" VARCHAR2(50),
	"OUTBOUND_PPI_MSG_PASSWORD" VARCHAR2(200),
	"OUTBOUND_PPI_MSG_URL" VARCHAR2(500),
	"NETWORK_DOMAIN" VARCHAR2(255),
	"PPI_DIRECTORY_URL" VARCHAR2(500),
	"PARTNER_ACCOUNT_ID" VARCHAR2(50),
	"DIRECTORY_LOGIN_ID" VARCHAR2(50),
	"DIRECTORY_PASSWORD" VARCHAR2(50),
	"DIRECTORY_VERSION" VARCHAR2(15),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"IS_SUPERSET_NETWORK" CHAR(1),
	"REFILL_QUANT_QUALIFIER_IND" CHAR(1),
	"IS_TEST_SYSTEM" CHAR(1),
	"INBOUND_PPI_MSG_USER_ID" VARCHAR2(50),
	"INBOUND_PPI_MSG_PASSWORD" VARCHAR2(200),
	"DIRECTORY_DOWNLOAD_BASE_URL" VARCHAR2(500),
	"PORTAL_ID" VARCHAR2(35),
	"DATA_PROVIDER_ID" VARCHAR2(35),
	"PARTITION_DATE" DATE,
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"H_TYPE" CHAR(1),
	"H_LEVEL" NUMBER,
	"OUTBOUND_AUTH_URL" VARCHAR2(255)
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("AUD_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
