-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."PRESCRIBER_ADDRESS_PHONE"
   (	"PRESCRIBER_ADDRESS_PHONE_NUM" NUMBER(18,0),
	"PRESCRIBER_PHONE_NUM" NUMBER(18,0),
	"PRESCRIBER_ADDRESS_NUM" NUMBER(18,0),
	"PHONE_ADDRESS_TYPE" VARCHAR2(4),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
