-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."PRICING_TABLE_CONFIG"
   (	"PRICING_TABLE_CONFIG_NUM" NUMBER(18,0),
	"PRICING_TABLE_NUM" NUMBER(18,0),
	"EFFECTIVE_DATE" DATE,
	"TERM_DATE" DATE,
	"MIN_VALUE" NUMBER(17,6),
	"MAX_VALUE" NUMBER(17,6),
	"EXTRACTION_METHOD" VARCHAR2(30),
	"BASIS_OF_COST" CHAR(2),
	"INDEX_VARIABLE" VARCHAR2(30),
	"PUBLISH_STATUS" CHAR(1),
	"PUBLISH_USER" NUMBER(18,0),
	"PUBLISH_DATE" DATE,
	"CALCULATION_TARGET" VARCHAR2(30),
	"COST_BASIS_NUM" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
