-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."PRICING_LIST_ITEM"
   (	"PRICING_LIST_ITEM_NUM" NUMBER(18,0),
	"PRICING_LIST_CONFIG_NUM" NUMBER(18,0),
	"PRICING_FORMULA_NUM" NUMBER(18,0),
	"PRICING_FORMULA_NAME" VARCHAR2(30),
	"PROCESS_ORDER" NUMBER(9,0),
	"EXCLUDE_FROM_PROCESSING" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"DATA_FILTER" CLOB,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
