-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."PRICE_LINK_RULE_SET"
   (	"PRICE_LINK_RULE_SET_NUM" NUMBER(18,0),
	"EFFECTIVE_DATE" DATE,
	"TERM_DATE" DATE,
	"CASH_TP_INDICATOR" CHAR(1),
	"PUBLISH_STATUS" CHAR(1),
	"PUBLISH_USER" NUMBER(18,0),
	"PUBLISH_DATE" DATE,
	"DATA_GROUP" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"PARTITION_DATE" DATE,
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"H_TYPE" CHAR(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("AUD_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2013-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
