-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."PRODUCT_INGREDIENT"
   (	"PRODUCT_INGREDIENT_NUM" NUMBER(18,0),
	"PRODUCT_COMPOUND_NUM" NUMBER(18,0),
	"PRODUCT_NUM" NUMBER(18,0),
	"QUANTITY" NUMBER(16,8),
	"BILLING_QUANTITY" NUMBER(16,8),
	"COST" NUMBER(17,6),
	"DRUG_FORM_CODE" VARCHAR2(30),
	"PRINT_NUTRITIONAL_INFO" CHAR(1),
	"PRINT_PATIENT_EDU_INFO" CHAR(1),
	"NCPDP_CODE" CHAR(2),
	"FREE_FORM_NAME" VARCHAR2(50),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PROCESS_FLAG" CHAR(1) DEFAULT 'P',
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"RANK" NUMBER(2,0),
	"IS_ACTIVE" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE,
	"IS_AVAILABLE_ON_LABEL" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
