-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."RX_STATUS_DETAIL"
   (	"RX_STATUS_SEQ" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"PREVIOUS_RX_STATUS_NUM" NUMBER(18,0),
	"RX_STATUS_REASON_NUM" NUMBER(18,0),
	"EFFECTIVE_DATE" DATE,
	"COMMENTARY" VARCHAR2(255),
	"CREATE_USER" NUMBER(18,0),
	"CREATE_DATE" DATE,
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_KEY" NUMBER(18,0),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
