-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."SHIPPING_COURIER_OLD"
   (	"SHIPPING_COURIER_NUM" NUMBER(18,0),
	"COURIER_NAME" VARCHAR2(50),
	"IS_DEFAULT_COURIER" CHAR(1),
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"SHIPPING_PROCESSOR_NUM" NUMBER(18,0)
   )
  PARTITION BY RANGE ("DATESTAMP")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
