-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."SPECIALTY_PROGRAM"
   (	"SPECIALTY_PROGRAM_NUM" NUMBER(18,0),
	"START_DATE" DATE,
	"END_DATE" DATE,
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"SPECIALTY_PROG_TYPE_NUM" NUMBER(18,0),
	"SPECIALTY_PROG_SUB_TYPE_NUM" NUMBER(18,0),
	"SPECIALTY_PROGRAM_GROUP_NUM" NUMBER(18,0),
	"CENTRAL_FILL" VARCHAR2(20),
	"PROGRAM_CODE" VARCHAR2(10)
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("AUD_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
