-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."SPECIALTY_PROG_ANC_ITEM_LIST"
   (	"SPECIALTY_PROG_ANC_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SPECIALTY_PROG_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ANCILLARY_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) NOT NULL ENABLE,
	"DATESTAMP" DATE,
	"ARCHIVE_LEVEL" VARCHAR2(100),
	"SYS_USER" VARCHAR2(100),
	"NUM_UPDATES" VARCHAR2(100),
	"H_TYPE" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("AUD_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
