-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."TP_ADJ_RETRY_QUEUE"
   (	"TP_ADJ_RETRY_QUEUE_NUM" NUMBER(18,0),
	"ORDER_NUM" NUMBER(18,0),
	"ITEM_SEQ" NUMBER(18,0),
	"RETRY_TIME" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"MAX_RETRY_TIME" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"RETRY_STATUS" CHAR(1),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"H_LEVEL" NUMBER,
	"H_TYPE" CHAR(1)
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("AUD_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2013-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
