-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."TP_CASH_MESSAGE"
   (	"TP_CASH_MESSAGE_NUM" NUMBER(18,0),
	"ORDER_NUM" NUMBER(18,0),
	"ITEM_SEQ" NUMBER(18,0),
	"TP_PROCESSOR_NUM" NUMBER(18,0),
	"TP_PROCESSOR_DESTINATION_SEQ" NUMBER(18,0),
	"TP_ADJ_DRIVER_CONFIG_NUM" NUMBER(18,0),
	"TP_BILLING_FORMAT_NUM" NUMBER(18,0),
	"SUBMISSION_DATE" DATE,
	"SUBMISSION_STATUS" CHAR(1),
	"MESSAGE_CATEGORY" CHAR(1),
	"REQUEST_MESSAGE" CLOB,
	"RESPONSE_MESSAGE" CLOB,
	"COMM_FAILURE" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_KEY" NUMBER(18,0),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"FINANCIAL_FEED_NUM" NUMBER(18,0),
	"IS_BAR_TRANSACTION" CHAR(1),
	"TRANSACTION_STATUS" VARCHAR2(50),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"ACTIVE_SUBMISSION_DATE" DATE GENERATED ALWAYS AS (CASE  WHEN ("EFF_END_DATE"=TO_DATE(' 2999-12-31 00:00:00', 'syyyy-mm-dd hh24:mi:ss') AND "SYS_USER"<>2 AND LENGTH("REQUEST_MESSAGE")>0 AND LENGTH("RESPONSE_MESSAGE")>0) THEN "SUBMISSION_DATE" ELSE NULL END) VIRTUAL ,
	"SUBMISSION_TIMESTAMP" TIMESTAMP (6)
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
