-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."TP_PLAN_GENERAL_INFO"
   (	"TP_PLAN_GENERAL_INFO_NUM" NUMBER(18,0),
	"CONTACT_NAME" VARCHAR2(40),
	"INACTIVITY_DEACTIVATION_PERIOD" NUMBER(9,0),
	"FACILITY_PLAN_NUM" VARCHAR2(20),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
