-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."TP_WORKERS_COMP_CLAIM"
   (	"TP_WORKERS_COMP_CLAIM_NUM" NUMBER(18,0),
	"PATIENT_NUM" NUMBER(18,0),
	"ACTIVE_STATUS" CHAR(1),
	"CLAIM_REFERENCE_ID" VARCHAR2(30),
	"INJURY_DESCRIPTION" VARCHAR2(60),
	"DATE_OF_INJURY" DATE,
	"CLAIM_TERMINATION_DATE" DATE,
	"CLAIM_AUTHORIZED_BY" VARCHAR2(60),
	"EMPLOYER_NAME" VARCHAR2(30),
	"EMPLOYER_CONTACT_NAME" VARCHAR2(30),
	"EMPLOYER_ID" VARCHAR2(15),
	"EMPLOYER_TAX_ID" VARCHAR2(15),
	"CARRIER_ID" VARCHAR2(10),
	"CARRIER_NAME" VARCHAR2(25),
	"CARRIER_INSURANCE_ID" VARCHAR2(15),
	"CARRIER_CONTACT_NAME" VARCHAR2(30),
	"APPROVAL_NUMBER" VARCHAR2(30),
	"REFILLS_AUTHORIZED" NUMBER(9,0),
	"DIAGNOSIS_CODE_SUBMITTED" VARCHAR2(15),
	"CLAIM_EFFECTIVE_DATE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"JURISDICTION_STATE" VARCHAR2(2),
	"PAYEE_QUALIFIER" VARCHAR2(2),
	"PAYEE_ID" VARCHAR2(15),
	"PAYEE_NAME" VARCHAR2(20),
	"PAYEE_CONTACT_NAME" VARCHAR2(30),
	"CLAIM_TYPE_CODE" VARCHAR2(2)
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
