-- ==========================================

  CREATE TABLE "TREXONE_AUD_DATA"."VACCINE_DATA_FILTER"
   (	"VACCINE_DATA_FILTER_NUM" NUMBER(18,0),
	"DATA_FILTER_VALUE" CLOB,
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID'),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("AUD_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
