-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."BATCH_LOG"
   (	"BATCH_LOG_NUM" NUMBER(18,0),
	"PROCESS_NAME" VARCHAR2(200) NOT NULL ENABLE,
	"RUN_STATUS" CHAR(1) NOT NULL ENABLE,
	"START_TIMESTAMP" TIMESTAMP (6) NOT NULL ENABLE,
	"LAST_TIMESTAMP" TIMESTAMP (6) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"BATCH_CTL_NUM" NUMBER(18,0),
	 CONSTRAINT "PK_BATCH_LOG" PRIMARY KEY ("BATCH_LOG_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_BATCH_CTL_01" FOREIGN KEY ("BATCH_CTL_NUM")
	  REFERENCES "TREXONE_ODS_DATA"."BATCH_CTL" ("BATCH_CTL_NUM") ENABLE
   ) ;
-- ==========================================
