-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ETL_RUN_ERROR"
   (	"ETL_RUN_ERROR_NUM" NUMBER(18,0),
	"ETL_RUN_PROC_NUM" NUMBER(18,0),
	"ETL_RUN_STEP_NUM" NUMBER(18,0),
	"ERROR_MSG" VARCHAR2(1000),
	"ORA_ERROR_MSG" VARCHAR2(1000),
	"STMT_ID" VARCHAR2(10),
	"STMT_VAR_VALUES" VARCHAR2(1000),
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "PK_ETL_RUN_ERROR" PRIMARY KEY ("ETL_RUN_ERROR_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_ETL_RUN_PROC_01" FOREIGN KEY ("ETL_RUN_PROC_NUM")
	  REFERENCES "TREXONE_ODS_DATA"."ETL_RUN_PROC" ("ETL_RUN_PROC_NUM") ENABLE,
	 CONSTRAINT "FK_ETL_RUN_STEP_02" FOREIGN KEY ("ETL_RUN_STEP_NUM")
	  REFERENCES "TREXONE_ODS_DATA"."ETL_RUN_STEP" ("ETL_RUN_STEP_NUM") ENABLE
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("ODS_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
