-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ETL_RUN"
   (	"ETL_RUN_NUM" NUMBER(18,0),
	"START_TIME" DATE NOT NULL ENABLE,
	"END_TIME" DATE,
	"STATUS" CHAR(1) NOT NULL ENABLE,
	"OLTP_UTC_CUTOFF_TIME" DATE NOT NULL ENABLE,
	"RUN_TYPE" CHAR(2),
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "PK_ETL_RUN" PRIMARY KEY ("ETL_RUN_NUM")
  USING INDEX  ENABLE
   )
  PARTITION BY RANGE ("START_TIME") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("ODS_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
