-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ETL_STEP"
   (	"ETL_STEP_NUM" NUMBER(18,0),
	"STEP_NAME" VARCHAR2(20) NOT NULL ENABLE,
	"STEP_DESC" VARCHAR2(200),
	"SCHEMA_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"IS_ACTIVE" CHAR(1) NOT NULL ENABLE,
	"MAX_PROCESS" NUMBER(4,0) NOT NULL ENABLE,
	"LOOP_HOURS" NUMBER(6,0) NOT NULL ENABLE,
	"PARENT_STEP_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"ETL_STEP_GROUP_NUM" NUMBER(18,0),
	 CONSTRAINT "PK_ETL_STEP" PRIMARY KEY ("ETL_STEP_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_ETL_STEP_01" FOREIGN KEY ("PARENT_STEP_NUM")
	  REFERENCES "TREXONE_ODS_DATA"."ETL_STEP" ("ETL_STEP_NUM") ENABLE,
	 CONSTRAINT "FK_ETL_STEP_GROUP_01" FOREIGN KEY ("ETL_STEP_GROUP_NUM")
	  REFERENCES "TREXONE_ODS_DATA"."ETL_STEP_GROUP" ("ETL_STEP_GROUP_NUM") ENABLE
   ) ;
-- ==========================================
