-- ==========================================

  CREATE GLOBAL TEMPORARY TABLE "TREXONE_ODS_DATA"."GTT_IOT_DISPENSE"
   (	"FILL_FACT_KEY" NUMBER(18,0),
	"FD_FACILITY_KEY" NUMBER(18,0),
	"CENTRAL_FILL_FD_FACILITY_KEY" NUMBER(18,0),
	"TRANSACTION_TYPE" CHAR(1),
	"RX_RECORD_NUM" NUMBER(18,0),
	"PARTIAL_FILL_SEQ" NUMBER(2,0),
	"RX_NUMBER" VARCHAR2(20),
	"RX_FILL_SEQ" NUMBER(18,0),
	"REFILL_NUM" NUMBER(18,0),
	"QTY_DISPENSED" NUMBER(13,3),
	"DAYS_SUPPLY" NUMBER(18,0),
	"TOTAL_REFILLS_ALLOWED" NUMBER,
	"TOTAL_REFILLS_REMAINING" NUMBER,
	"IS_340B" CHAR(1),
	"IS_CENTRAL_FILL" CHAR(1),
	"IS_ERP_OPPORTUNITY" CHAR(1),
	"FILL_INDICATOR_KEY" NUMBER(18,0),
	"EXPECTED_DUE_DATE" DATE,
	"ERP_TARGET_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"SOLD_DATE" DATE,
	"READY_DATE" DATE,
	"CANCEL_DATE" DATE,
	"DISPENSED_DRUG_KEY" NUMBER(18,0),
	"PD_PATIENT_KEY" NUMBER(18,0),
	"PRIMARY_TPLD_PLAN_KEY" NUMBER(18,0),
	"PRESCRIBER_KEY" NUMBER(18,0),
	"FOA_DATE" DATE
   ) ON COMMIT DELETE ROWS ;
-- ==========================================
