-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."INVENTORY_COST_STG"
   (	"INVENTORY_COST_STG_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0),
	"PRODUCT_NUM" NUMBER(18,0),
	"INVENTORY_ITEM_NUM" NUMBER(18,0),
	"FACILITY_ID" VARCHAR2(10),
	"NDC" VARCHAR2(11),
	"DRUG_PACKAGE_SIZE" NUMBER(19,8),
	"LAST_ACQ_UNIT_COST" NUMBER(17,6),
	"LAST_ACQ_PKG_COST" NUMBER(17,6),
	"EXPECTED_ACQ_UNIT_COST" NUMBER(17,6),
	"EXPECTED_ACQ_PKG_COST" NUMBER(17,6),
	"AWP_UNIT_COST" NUMBER(17,6),
	"AWP_PKG_COST" NUMBER(17,6),
	"DISPENSED_QTY" NUMBER(19,8),
	"RECEIVED_QTY" NUMBER(19,8),
	"ADJUSTMENT_QTY" NUMBER(19,8),
	"ON_HAND_QTY" NUMBER(19,8),
	"COMMITTED_QTY" NUMBER(19,8),
	"REORDER_POINT" NUMBER(12,3),
	"REORDER_POINT_QUALIFIER" CHAR(1),
	"AVG_COST" NUMBER(17,6),
	"AVG_COST_TYPE" VARCHAR2(10),
	"PURCHASE_PLAN_NUM" NUMBER(18,0),
	"PURCHASE_PLAN_ITEM_NUM" NUMBER(18,0),
	"PRIMARY_VENDOR_NUM" NUMBER(18,0),
	"PRIMARY_VENDOR_ITEM_NUM" NUMBER(18,0),
	"VENDOR_PACKAGE_SIZE" NUMBER(19,8),
	"VENDOR_PURCHASE_INCREMENT" NUMBER(9,0),
	"IS_QTY_CHANGED" CHAR(1),
	"PRD_IS_GENERIC" CHAR(1),
	"DRUG_PURCHASE_INCREMENT" NUMBER(19,8),
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"UNDISPENSED_QTY" NUMBER(19,8),
	"RETURN_SUPPLIER_QTY" NUMBER(19,8)
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("ODS_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
