-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_IMPORTED_PRESCRIBER"
   (	"IMPORTED_PRESCRIBER_NUM" NUMBER(18,0),
	"STATUS" CHAR(1),
	"PRESCRIBER_NUM" NUMBER(18,0),
	"STATUS_DATE" DATE,
	"SCRUB_ID" NUMBER(18,0),
	"IMPORT_DATE" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE,
	"SYS_USER" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"ESV_PRESCRIBER_ID" VARCHAR2(50),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
