-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_PDMP_RESPONSE_ERROR"
   (	"PDMP_RESPONSE_ERROR_NUM" NUMBER(18,0),
	"PDMP_RESPONSE_NUM" NUMBER(18,0),
	"MESSAGE_TYPE" CHAR(1),
	"MESSAGE" VARCHAR2(2048),
	"DETAILS" CLOB,
	"SOURCE" VARCHAR2(100),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE DEFAULT SYSDATE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0,
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1, 'DAY')) STORE IN ("ODS_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
