-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_PATIENT_TO_SPECIALTY_PROG"
   (	"PATIENT_TO_SPECIALTY_PROG_NUM" NUMBER(22,0),
	"SPECIALTY_PROGRAM_NUM" NUMBER(22,0),
	"PATIENT_NUM" NUMBER(22,0),
	"DATA_GROUP" NUMBER(22,0),
	"ELIGIBILITY_START_DATE" DATE,
	"ELIGIBILITY_END_DATE" DATE,
	"DEACTIVATED_DATE" DATE,
	"PARTITION_DATE" DATE,
	"DEACTIVATION_REASON" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1, 'DAY')) STORE IN ("ODS_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
