-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_HEALTH_CARD_BIN"
   (	"HEALTH_CARD_BIN_NUM" NUMBER(18,0),
	"HEALTH_CARD_BIN_CURRENT" CHAR(1),
	"HEALTH_CARD_BIN_DATE" DATE,
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE,
	"ERX_CLIENT_ID" VARCHAR2(200),
	"PARTITION_DATE" DATE,
	"H_TYPE" CHAR(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
