-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_PRODUCT_INGREDIENT_PRICE"
   (	"PRODUCT_INGREDIENT_PRICE_NUM" NUMBER(18,0),
	"PRICE_CALC_RESULT_NUM" NUMBER(18,0),
	"PRODUCT_INGREDIENT_NUM" NUMBER(18,0),
	"AMOUNT" NUMBER(17,6),
	"BASIS_OF_COST" CHAR(2),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"DISPENSED_QTY" NUMBER(13,3),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
