-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_DISPENSING_PROFILE"
   (	"DISPENSING_TEMPLATE_NUM" NUMBER(18,0),
	"DISPENSING_PROFILE_SEQ" NUMBER(18,0),
	"LOCATION_GROUP_NUM" NUMBER(18,0),
	"PROFILE_NAME" VARCHAR2(45),
	"PRIORITY" NUMBER(9,0),
	"IS_LABEL_PRINT" CHAR(1),
	"DATA_GROUP" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"IS_ACTIVE" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PARTITION_DATE" DATE,
	"H_TYPE" CHAR(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
