-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_INVENTORY_ITEM_GRP_SUMMARY"
   (	"FACILITY_NUM" NUMBER(18,0),
	"PRODUCT_NUM" NUMBER(18,0),
	"DRUG_NUM" NUMBER(18,0),
	"INVENTORY_ITEM_NUM" NUMBER(18,0),
	"LOCATION_GROUP_NUM" NUMBER(18,0),
	"GROUP_NUM" NUMBER(18,0),
	"INV_ITEM_LAST_ACQ_COST_DATE" DATE,
	"INV_ITEM_LAST_ACQ_UNIT_COST" NUMBER(17,6),
	"STORAGE_LOC_DATA_GROUP" NUMBER(18,0),
	"STORAGE_LOC_CURRENT_QTY" NUMBER(17,6),
	"STORAGE_LOC_DATESTAMP" DATE,
	"CURRENT_SUMMARY_DATESTAMP" DATE,
	"COST_BASIS_SOURCE_VALUE_COST" NUMBER(18,8),
	"ERX_CLIENT_ID" VARCHAR2(100)
   ) ;
-- ==========================================
