-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_ANCILLARY_ITEM"
   (	"ANCILLARY_ITEM_NUM" NUMBER(18,0),
	"INVENTORY_SKU_NUM" NUMBER(18,0),
	"EXPIRATION_DATE" DATE,
	"ORIGIN_DATE" DATE,
	"COST" NUMBER(17,6),
	"PRICE" NUMBER(17,6),
	"QUANTITY" NUMBER(16,8),
	"ORIGINAL_QUANTITY" NUMBER(16,8),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PARTITION_DATE" DATE,
	"RECOMMENDED_QTY" NUMBER(16,8),
	"NUM_UPDATES" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(18,0)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
