-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_PO_DATA_REQUEST"
   (	"PO_DATA_REQUEST_NUM" NUMBER(18,0),
	"REQUEST_DATETIME" DATE,
	"PURCHASE_ORDER_IDENTIFIER" VARCHAR2(100),
	"RESULT" CHAR(1),
	"SUPPLIER_SGLN" VARCHAR2(100),
	"FACILITY_SGLN" VARCHAR2(100),
	"REQUEST_FACILITY_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	"H_TYPE" VARCHAR2(1),
	"PARTITION_DATE" DATE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("ODS_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
