-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_PCS_PATIENT_COMM_SETTING"
   (	"PCS_PATIENT_COMM_SETTING_NUM" NUMBER(18,0),
	"PATIENT_ID" VARCHAR2(100),
	"PMS_COMM_KEY" NUMBER(18,0),
	"COMM_TYPE" VARCHAR2(15),
	"COMM_VALUE" VARCHAR2(100),
	"DATESTAMP" DATE,
	"PARTITION_DATE" DATE,
	"H_TYPE" CHAR(1),
	"H_LEVEL" NUMBER,
	"SILO_ID" VARCHAR2(50),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("ODS_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
