-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_FREQUENCY"
   (	"FREQUENCY_NUM" NUMBER(18,0),
	"TYPE" CHAR(1),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PERIOD1" CHAR(1),
	"REVERSE1" CHAR(1),
	"PERIOD2" CHAR(1),
	"REVERSE2" CHAR(1),
	"COUNT1" NUMBER(9,0),
	"COUNT2" NUMBER(9,0),
	"START_DATE" DATE,
	"END_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
