-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_CVS_PRODUCT_XREF"
   (	"CVS_PRODUCT_XREF_NUM" NUMBER(18,0),
	"PRODUCT_NUM" NUMBER(18,0),
	"NDC" VARCHAR2(11),
	"GCN_SEQ_NUM" VARCHAR2(30),
	"STORE_PACKAGE_SIZE" NUMBER(16,8),
	"EFFECTIVE_DATE" DATE,
	"TERM_DATE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
