-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_PRESCRIBER_ADDRESS"
   (	"PRESCRIBER_ADDRESS_NUM" NUMBER(18,0),
	"ACTIVE_PRESCRIBER_ADDRESS_NUM" NUMBER(18,0),
	"PRESCRIBER_NUM" NUMBER(18,0),
	"PRESCRIBER_ID_NUM" NUMBER(18,0),
	"OVERRIDE_ID_NUM" NUMBER(18,0),
	"STATUS" CHAR(1),
	"IS_DEFAULT" CHAR(1),
	"EMAIL_ADDRESS" VARCHAR2(256),
	"WEB_ADDRESS" VARCHAR2(256),
	"PRIMARY_CONTACT_TITLE" VARCHAR2(30),
	"PRIMARY_CONTACT_LAST_NAME" VARCHAR2(30),
	"PRIMARY_CONTACT_MIDDLE_NAME" VARCHAR2(30),
	"PRIMARY_CONTACT_FIRST_NAME" VARCHAR2(30),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PRESCRIBER_LOCATION" VARCHAR2(3),
	"SOURCE_CODE" CHAR(1),
	"PRACTICE_NAME" VARCHAR2(50),
	"DRUG_SCHEDULE" VARCHAR2(30),
	"ADDRESS_TYPE_CODE" VARCHAR2(10),
	"ESV_LAST_UPDATE_DATE" DATE,
	"CONTACT_METHOD_NUM" NUMBER(18,0),
	"PROCESS_FLAG" CHAR(1) DEFAULT 'P',
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"IS_340B" CHAR(1),
	"ESV_PRESCRIBER_ID" VARCHAR2(50),
	"ESV_PRESCRIBER_ADDR_LOC_ID" VARCHAR2(10),
	"ESV_PRESCRIBER_ADDR_RANK" NUMBER
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
