-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_PO_ACKNOWLEDGEMENT_ITEM"
   (	"PO_ACKNOWLEDGEMENT_ITEM_NUM" NUMBER(18,0),
	"PURCHASE_ORDER_ACK_NUM" NUMBER(18,0),
	"PURCHASE_ORDER_ITEM_NUM" NUMBER(18,0),
	"QUANTITY" NUMBER(9,0),
	"ACQUISITION_COST" NUMBER(17,6),
	"SHIPPING_STATUS" CHAR(2),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0)
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
