-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_LOCATION_GROUP"
   (	"LOCATION_GROUP_NUM" NUMBER(18,0),
	"LOCATION_GROUP_NAME" VARCHAR2(45),
	"SHORT_NAME" VARCHAR2(10),
	"DESCRIPTION" VARCHAR2(60),
	"IS_ACTIVE" CHAR(1),
	"DISPENSE_PRIORITY" NUMBER(9,0),
	"IS_CONTROL_ORDER_COMMIT" CHAR(1),
	"IS_CONTROL_DISPENSING_COMMIT" CHAR(1),
	"IS_ITEM_LOCATION" CHAR(1),
	"LOCATION_GROUP_TYPE_NUM" NUMBER(9,0),
	"COST_MODEL_NUM" NUMBER(9,0),
	"PARENT_LOCATION_GROUP_NUM" NUMBER(18,0),
	"DATA_GROUP" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
