-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_PATIENT_MED_CONDITION"
   (	"PATIENT_NUM" NUMBER(18,0),
	"PATIENT_MED_CONDITION_SEQ" NUMBER(18,0),
	"STATUS" CHAR(1),
	"ONSET_DATE" DATE,
	"CREATE_DATE" DATE,
	"CREATE_USER" NUMBER(18,0),
	"DEACTIVATE_DATE" DATE,
	"DEACTIVATE_USER" NUMBER(18,0),
	"ICD9_CODE" VARCHAR2(10),
	"ICD9_DESCRIPTION" VARCHAR2(255),
	"MEDICAL_CONDITION_NUM" NUMBER(18,0),
	"TYPE_NUM" NUMBER(9,0),
	"DURATION_IN_DAYS" NUMBER(9,0),
	"REPORTED_DATE" DATE,
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"PROCESS_FLAG" CHAR(1) DEFAULT 'P',
	"PARTITION_DATE" DATE,
	"ADDED_VIA_MODULE" VARCHAR2(50),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
