-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_TP_BILLING_FORMAT_SET"
   (	"TP_BILLING_FORMAT_SET_NUM" NUMBER(18,0),
	"CLAIM_TP_BILLING_FORMAT_NUM" NUMBER(18,0),
	"REV_TP_BILLING_FORMAT_NUM" NUMBER(18,0),
	"ELIG_TP_BILLING_FORMAT_NUM" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"N1_TP_BILLING_FORMAT_NUM" NUMBER(18,0),
	"N2_TP_BILLING_FORMAT_NUM" NUMBER(18,0),
	"S1_TP_BILLING_FORMAT_NUM" NUMBER(18,0),
	"S2_TP_BILLING_FORMAT_NUM" NUMBER(18,0)
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
