-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_TP_DATA_RULE"
   (	"TP_DATA_RULE_NUM" NUMBER(18,0),
	"TP_RULE_SET_NUM" NUMBER(18,0),
	"FIELD_ID" NUMBER(9,0),
	"IS_REQUIRED" CHAR(1),
	"IS_ON_ADDITIONAL_INFO_SCREEN" CHAR(1),
	"FORMAT_TYPE" VARCHAR2(18),
	"MASK" VARCHAR2(100),
	"MIN_LENGTH" NUMBER(9,0),
	"MAX_LENGTH" NUMBER(9,0),
	"WARN_LEV" NUMBER(9,0),
	"ALT_LABEL" VARCHAR2(45),
	"ATTRIBUTE_GROUP_NUM" NUMBER(9,0),
	"POSITIVE_VALUE_LIST" CHAR(1),
	"FIELD_HELP_MESSAGE" VARCHAR2(255),
	"PRE_EDIT_MESSAGE" VARCHAR2(2000),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"PARTITION_DATE" DATE,
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" CHAR(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("ODS_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2013-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
