-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_CLINICAL_PROGRAM"
   (	"CLINICAL_PROGRAM_NUM" NUMBER(18,0),
	"PROGRAM_NAME" VARCHAR2(100),
	"PROGRAM_CODE" CHAR(1),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PARTITION_DATE" DATE,
	"H_TYPE" CHAR(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("ODS_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
