-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_ANCILLARY_ITEM_COMMIT"
   (	"ANCILLARY_ITEM_COMMIT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ANCILLARY_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"COMMIT_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"QUANTITY" NUMBER(16,8) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"FACILITY_ITEM_NUM" VARCHAR2(10) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" VARCHAR2(100) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"DATESTAMP" DATE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("ODS_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
