-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_LAST_LOAD_SEQ"
   (	"TABLE_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"SEQ#" NUMBER,
	"LAST_LOAD_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0)
   ) ;
  CREATE UNIQUE INDEX "TREXONE_ODS_DATA"."PK_ODS_LAST_LOAD_SEQ" ON "TREXONE_ODS_DATA"."ODS_LAST_LOAD_SEQ" ("TABLE_NAME")
  ;
ALTER TABLE "TREXONE_ODS_DATA"."ODS_LAST_LOAD_SEQ" ADD CONSTRAINT "PK_ODS_LAST_LOAD_SEQ" PRIMARY KEY ("TABLE_NAME")
  USING INDEX "TREXONE_ODS_DATA"."PK_ODS_LAST_LOAD_SEQ"  ENABLE;
-- ==========================================
