-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_WF_PROCESS_INSTANCE"
   (	"WF_PROCESS_DEFINITION_NUM" NUMBER(18,0),
	"PROC_INST_SEQ" NUMBER(18,0),
	"PROCESS_STATE" VARCHAR2(30),
	"COMMENT_TEXT" VARCHAR2(255),
	"CREATE_DATE" DATE,
	"CREATE_USER" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"IS_LOCAL" CHAR(1),
	"IS_DUR_EXCEPTION" CHAR(1),
	"IS_ADJ_EXCEPTION" CHAR(1),
	"IS_AR_EXCEPTION" CHAR(1),
	"IS_PRE_EDIT_EXCEPTION" CHAR(1),
	"IS_DELETE_PENDING" CHAR(1),
	"IS_DECLINING" CHAR(1),
	"IS_FORCED_FOA" CHAR(1),
	"DECLINE_REASON" VARCHAR2(128),
	"ORDER_NUM" NUMBER(18,0),
	"ITEM_SEQ" NUMBER(18,0),
	"PARENT_PROCESS_DEFINITION_NUM" NUMBER(18,0),
	"PARENT_PROC_INST_SEQ" NUMBER(18,0),
	"DATESTAMP" DATE,
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"IS_PULLED_BACK" CHAR(1),
	"IS_PACKED" CHAR(1),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"IS_ADS_EXCEPTION" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"ON_HOLD_REASON_CODE" CHAR(1)
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
