-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_INBOUND_MSG_QUEUE"
   (	"INBOUND_MSG_QUEUE_NUM" NUMBER(18,0),
	"OUTBOUND_MSG_QUEUE_NUM" NUMBER(18,0),
	"HTTP_HEADERS" VARCHAR2(4000),
	"HTTP_METHOD" VARCHAR2(20),
	"REQUEST_CONTENT" CLOB,
	"HTTP_STATUS" NUMBER(18,0),
	"RESPONSE_CONTENT" CLOB,
	"REQUEST_URI" VARCHAR2(4000),
	"PARTITION_DATE" DATE,
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" CHAR(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("ODS_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2013-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
