-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_DUR_CONFLICT_MESSAGE"
   (	"DUR_CONFLICT_NUM" NUMBER(18,0),
	"DRUG_CUSTOM_ID" VARCHAR2(15),
	"DRUG_DESC" VARCHAR2(50),
	"DRUG_ID" VARCHAR2(15),
	"MESSAGE" VARCHAR2(1023),
	"MESSAGE_TYPE" VARCHAR2(5),
	"SEVERITY" VARCHAR2(5),
	"SOURCE" VARCHAR2(5),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
