-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_TP_PRIOR_AUTH"
   (	"TP_PRIOR_AUTH_NUM" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"TP_PATIENT_NUM" NUMBER(18,0),
	"AUTHORIZATION_NUMBER" VARCHAR2(20),
	"AUTH_TYPE_NUM" NUMBER(9,0),
	"EFFECTIVE_DATE" DATE,
	"EXPIRATION_DATE" DATE,
	"QUANTITY_AUTHORIZED" NUMBER(16,8),
	"DOLLARS_AUTHORIZED" NUMBER(17,6),
	"REFILLS_AUTHORIZED" NUMBER(9,0),
	"PROCESSED_DATE" DATE,
	"QUANTITY_ACCUMULATED" NUMBER(16,8),
	"AUTH_REP_FIRST_NAME" VARCHAR2(30),
	"AUTH_REP_LAST_NAME" VARCHAR2(30),
	"DOCUMENTATION" VARCHAR2(500),
	"REQUEST_TYPE" CHAR(1),
	"REQUEST_PERIOD_BEGIN_DATE" DATE,
	"REQUEST_PERIOD_END_DATE" DATE,
	"BASIS_OF_REQUEST" VARCHAR2(2),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"DOLLARS_ACCUMULATED" NUMBER(17,6),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"REFILLS_ACCUMULATED" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
