-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_TOTE"
   (	"TOTE_NUM" NUMBER(18,0),
	"TOTE_ID" VARCHAR2(7),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"FACILITY_NUM" NUMBER(18,0),
	"IS_AVAILABLE" CHAR(1),
	"IS_CLOSED" CHAR(1),
	"IS_ACTIVE" CHAR(1),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
