-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_RX_HOLD_DETAIL"
   (	"RX_HOLD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_FILL_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"CPS_MESSAGE_NUM" NUMBER(18,0),
	"ASSIGNEE" VARCHAR2(100),
	"DUE_DATE" DATE,
	"GLOBAL_FILL_SEQ_ID" VARCHAR2(100),
	"SENT_EPOCH" NUMBER(10,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" VARCHAR2(100) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"WORKFLOW_STEP_NAME" VARCHAR2(50),
	"WORKFLOW_STEP_SEQ" NUMBER(3,0),
	"DUE_DATE_TIME" DATE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("ODS_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
