-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."PRICING_TABLE_STG"
   (	"PRICING_TABLE_DETAIL_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(30) NOT NULL ENABLE,
	"CASH_TP_IND" CHAR(1) NOT NULL ENABLE,
	"PUBLISH_STATUS" CHAR(1),
	"PUBLISH_USER" VARCHAR2(30),
	"PUBLISH_DATE" DATE,
	"CONFIG_EFFECTIVE_DATE" DATE NOT NULL ENABLE,
	"CONFIG_TERM_DATE" DATE,
	"INDEX_LOW_VALUE" NUMBER(17,6),
	"INDEX_HIGH_VALUE" NUMBER(17,6),
	"BASIS_OF_COST_CD" CHAR(2),
	"COST_BASIS_NAME" VARCHAR2(30),
	"COST_BASIS_DESC" VARCHAR2(255),
	"COST_BASIS_DATA_GROUP" NUMBER(18,0),
	"TABLE_CALCULATION" VARCHAR2(4000),
	"LINKED_TABLE_NAME" VARCHAR2(30),
	"DATESTAMP" DATE NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100)
   ) ;
-- ==========================================
