-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."PRODUCT_LOAD_STG"
   (	"IL_KEY" NUMBER(18,0),
	"FACILITY_ID" VARCHAR2(10),
	"TIMEZONE_ID" VARCHAR2(60),
	"USER_DEFINED_INFO_1" VARCHAR2(255),
	"NDC_NUMBER" VARCHAR2(20),
	"INVITEM_RECOMMENDED_PO_IND" CHAR(1),
	"MINIMUM_QTY" NUMBER(12,3),
	"MAXIMUM_QTY" NUMBER(12,3),
	"FACILITY_PRODUCT_LAST_USED" DATE,
	"CORP_PRODUCT_SCHEDULE" CHAR(1),
	"CREATE_DT" DATE,
	"UPDATE_DT" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100)
   ) ;
-- ==========================================
