-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."RX_FILL_STG_CTL"
   (	"STG_PROC_NAME" VARCHAR2(100),
	"LAST_RX_TRANS_DATE" DATE,
	"LAST_STATUS_CODE" CHAR(1),
	"LAST_STMT" VARCHAR2(20),
	"LAST_FACILITY_KEY" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"SEQ#" NUMBER,
	 CONSTRAINT "UC_RX_FILL_STG_CTL_01" UNIQUE ("STG_PROC_NAME", "ERX_CLIENT_ID")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
