-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."WIPE_BATCH_LOG"
   (	"TABLE_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"SCHEMA_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"LOG_MSG" VARCHAR2(1000) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ORA_ERROR_MSG" VARCHAR2(1000),
	"ROW_RANGE" VARCHAR2(500)
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
