-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_ACC_AR_CHARGE_TYPE_AMOUNT"
   (	"ACC_AR_OTHER_AMOUNT_NUM" NUMBER(18,0),
	"ACC_AR_CHARGE_TYPE_AMOUNT_NUM" NUMBER(18,0),
	"ACC_CHARGE_TYPE_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
