-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_DT_PRESCRIBER"
   (	"DT_TX_NUM" NUMBER(19,0),
	"FACILITY_NUM" NUMBER(18,0),
	"FIRST_NAME" VARCHAR2(30),
	"MIDDLE_INITIAL" VARCHAR2(30),
	"LAST_NAME" VARCHAR2(30),
	"ADDRESS" VARCHAR2(100),
	"CITY" VARCHAR2(40),
	"STATE_CODE" CHAR(2),
	"ZIP_CODE" VARCHAR2(20),
	"PHONE" VARCHAR2(20),
	"DEA_NUMBER" VARCHAR2(30),
	"LICENSE_NUMBER" VARCHAR2(30),
	"UPIN_NUMBER" VARCHAR2(30),
	"PRESCRIBER_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"PARTITION_KEY" NUMBER(18,0),
	"DEA_SUFFIX" VARCHAR2(20),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
