-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_PRICING_LIST_CONFIG"
   (	"PRICING_LIST_CONFIG_NUM" NUMBER(18,0),
	"PRICING_LIST_NUM" NUMBER(18,0),
	"EFFECTIVE_DATE" DATE,
	"TERM_DATE" DATE,
	"GENERIC_INDICATOR" CHAR(1),
	"GENERIC_PRICE_IND" CHAR(1),
	"GENERIC_PRICE_SPREAD_IND" CHAR(1),
	"GENERIC_MNFCTR_IND" CHAR(1),
	"GENERIC_NAMED_DRUG_IND" CHAR(1),
	"GENERIC_THERAPEUTIC_IND" CHAR(1),
	"USER_DEFINED_GENERIC_IND" CHAR(1),
	"PUBLISH_STATUS" CHAR(1),
	"PUBLISH_USER" NUMBER(18,0),
	"PUBLISH_DATE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
