-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_DATA_GROUP_LINK"
   (	"DATA_GROUP" NUMBER(18,0),
	"PARENT_DATA_GROUP" NUMBER(18,0),
	"DISTANCE_TO_PARENT" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PROCESS_FLAG" CHAR(1) DEFAULT 'P',
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
