-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_RX_STATUS_DETAIL"
   (	"RX_STATUS_SEQ" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"PREVIOUS_RX_STATUS_NUM" NUMBER(18,0),
	"RX_STATUS_REASON_NUM" NUMBER(18,0),
	"EFFECTIVE_DATE" DATE,
	"COMMENTARY" VARCHAR2(255),
	"CREATE_USER" NUMBER(18,0),
	"CREATE_DATE" DATE,
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
