-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_PPI_MESSAGE_EXTRA_INFO"
   (	"PPI_MESSAGE_EXTRA_INFO_NUM" NUMBER(18,0),
	"PPI_MESSAGE_NUM" NUMBER(18,0),
	"DRUG_NAME" VARCHAR2(35),
	"CONCAT_LOC" VARCHAR2(35),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
