-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_MANIFEST"
   (	"MANIFEST_NUM" NUMBER(18,0),
	"CREATE_DATESTAMP" DATE,
	"TOTE_NUM" NUMBER(18,0),
	"DELIVERY_NUM" NUMBER(18,0),
	"CLOSED_DATESTAMP" DATE,
	"CLOSED_USER" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
