-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_PPI_MESSAGE"
   (	"PPI_MESSAGE_NUM" NUMBER(18,0),
	"SOURCE" VARCHAR2(80),
	"DESTINATION" VARCHAR2(80),
	"MESSAGE_ID" VARCHAR2(35),
	"MESSAGE_TYPE" NUMBER(2,0),
	"SENT_TIME" DATE,
	"RELATED_MESSAGE_ID" VARCHAR2(35),
	"TEST_MESSAGE_IND" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"FACILITY_NUM" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"IMAGE_NUM" NUMBER(18,0),
	"PROCESSED_CODE" CHAR(1),
	"IS_MATCHED" CHAR(1),
	"ERROR_CODE" NUMBER(3,0),
	"RX_FILL_SEQ" NUMBER(18,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"ELECTRONIC_ORDER_NUM" NUMBER(18,0),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"BATCH_REASON" CHAR(1),
	"PPI_NETWORK_NUM" NUMBER(18,0)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
