-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_ACC_CODE"
   (	"ACC_CODE_NUM" NUMBER(18,0),
	"ACC_CODE_TYPE_NUM" NUMBER(18,0),
	"ACC_CODE_SET_NUM" NUMBER(18,0),
	"CODE" VARCHAR2(30),
	"DESCRIPTION" VARCHAR2(255),
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
