-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_MANIFEST_ITEM"
   (	"MANIFEST_ITEM_NUM" NUMBER(18,0),
	"ORDER_NUM" NUMBER(18,0),
	"CHECK_OUT_DATESTAMP" DATE,
	"CHECK_OUT_USER" NUMBER(18,0),
	"CHECK_IN_DATESTAMP" DATE,
	"CHECK_IN_USER" NUMBER(18,0),
	"RETURN_DATESTAMP" DATE,
	"RETURN_USER" NUMBER(18,0),
	"RETURN_RECEIVED_DATESTAMP" DATE,
	"RETURN_RECEIVED_USER" NUMBER(18,0),
	"RETURN_REASON_TYPE" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"ITEM_SEQ" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"MANIFEST_NUM" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"CF_FACILITY_NUM" NUMBER(18,0),
	"IS_PULLED_BACK" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
