-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_PURCHASING_PLAN"
   (	"PURCHASING_PLAN_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"NAME" VARCHAR2(50),
	"IS_ACTIVE" CHAR(1),
	"IS_DEFAULT_PLAN" CHAR(1),
	"PURCHASING_METHOD_CODE" CHAR(1),
	"MINIMUM_QTY" NUMBER(12,3),
	"MAXIMUM_QTY" NUMBER(12,3),
	"MIN_DAYS_SUPPLY" NUMBER(9,0),
	"MAX_DAYS_SUPPLY" NUMBER(9,0),
	"ORDER_QTY_ROUNDING_METHOD_CODE" CHAR(1),
	"NUMBER_DAYS_IN_BASE_PERIOD" NUMBER(3,0),
	"PERIOD_END_NUM_DAYS_AGO" NUMBER(3,0),
	"PERIOD_END_DATE" DATE,
	"PERCENTAGE_LEAD_TIME_DEMAND" NUMBER(3,0),
	"NEGATIVE_TOLERANCE_LEVEL_PCT" NUMBER(3,0),
	"POSITIVE_TOLERANCE_LEVEL_PCT" NUMBER(3,0),
	"EVAL_DEMAND_ADJUSTMENT_PCT" NUMBER(3,0),
	"EVAL_NUM_DAYS_IN_BASE_PERIOD" NUMBER(3,0),
	"EVAL_PERIOD_END_NUM_DAYS_AGO" NUMBER(3,0),
	"EVAL_PERIOD_END_DATE" DATE,
	"EVAL_LIFETIME_NUM_DAYS" NUMBER(3,0),
	"EVAL_ROUNDING_METHOD_CODE" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
