-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_GEOGRAPHIC_CODE"
   (	"GEOGRAPHIC_CODE_NUM" NUMBER(18,0),
	"GEOGRAPHIC_CODE_TYPE" VARCHAR2(4),
	"GEOGRAPHIC_CODE" VARCHAR2(30),
	"DESCRIPTION" VARCHAR2(300),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
