-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_SIG"
   (	"SIG_NUM" NUMBER(18,0),
	"MACRO" VARCHAR2(15),
	"DAILY_DOSAGE" NUMBER(16,8),
	"QTY_PER_DOSE" NUMBER(16,8),
	"LATIN_FREQUENCY_CODE" VARCHAR2(10),
	"IS_PRN_SIG" CHAR(1),
	"LATIN_FREQUENCY_QTY" NUMBER(9,0),
	"CONVERSION_FACTOR" NUMBER(9,3),
	"DATA_GROUP" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
