-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_INVENTORY_ADJUSTMENT_REASN"
   (	"INV_ADJUST_REASON_NUM" NUMBER(18,0),
	"CODE" VARCHAR2(3),
	"DESCRIPTION" VARCHAR2(50),
	"IS_ACTIVE" CHAR(1),
	"IS_USER_DEFINED" CHAR(1),
	"IS_DEFAULT" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
