-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_FACILITY_DAILY_HOURS"
   (	"FACILITY_DAILY_HOURS_NUM" NUMBER(18,0),
	"FACILITY_SCHEDULE_GROUP_NUM" NUMBER(18,0),
	"DAY_OF_WEEK_NUM" NUMBER(9,0),
	"OPEN_TIME" DATE,
	"CLOSE_TIME" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER(20,0),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
