-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_DUR_CONFLICT_DRUG_DISEASE"
   (	"DUR_CONFLICT_NUM" NUMBER(18,0),
	"CONDITION_CUSTOM_ID" VARCHAR2(35),
	"CONDITION_DESC" VARCHAR2(255),
	"CONDITION_ID" VARCHAR2(15),
	"DISEASE_DESC" VARCHAR2(255),
	"DETAIL_DRUG_DESC" VARCHAR2(255),
	"DRUG_CUSTOM_ID" VARCHAR2(15),
	"DRUG_DESC" VARCHAR2(50),
	"INTERNAL_DRUG_ID" VARCHAR2(15),
	"MEDICAL_CONDITION_DESC" VARCHAR2(255),
	"MEDICAL_CONDITION_ID" VARCHAR2(15),
	"SCREEN_MESSAGE" VARCHAR2(4000),
	"SEVERITY" VARCHAR2(20),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
