-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_SYSTEM_USER"
   (	"SYSTEM_USER_NUM" NUMBER(18,0),
	"LOGIN_NAME" VARCHAR2(30),
	"FIRST_NAME" VARCHAR2(30),
	"MIDDLE_NAME" VARCHAR2(30),
	"LAST_NAME" VARCHAR2(30),
	"INITIALS" VARCHAR2(3),
	"USER_PASSWORD" VARCHAR2(255),
	"EMPLOYEE_CODE" VARCHAR2(20),
	"IS_PRIVATE" CHAR(1),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"DEFAULT_DATA_GROUP" NUMBER(18,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"DISPLAY_NAME" VARCHAR2(100),
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"USER_DN" VARCHAR2(1000),
	"ROLE_SET" VARCHAR2(4000),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
