-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_TP_PRESCRIBER_ID_DEFAULT"
   (	"TP_PRESCRIBER_ID_DEFAULT_NUM" NUMBER(18,0),
	"TP_RULE_SET_NUM" NUMBER(18,0),
	"DOCTOR_TYPE_CODE" VARCHAR2(20),
	"PRESCRIBER_ID_TYPE" NUMBER(9,0),
	"DEFAULT_ID" VARCHAR2(20),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"RULE_EXPRESSION" CLOB,
	"VALUE_EXPRESSION" CLOB,
	"RANK" NUMBER(9,0),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
