-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_KEEP_IMAGE"
   (	"IMAGE_NUM" NUMBER(18,0),
	"TYPE" VARCHAR2(30),
	"IS_ASSIGNED" CHAR(1),
	"IMAGE" BLOB,
	"NAME" VARCHAR2(30),
	"FILE_FORMAT" VARCHAR2(10),
	"SCAN_USER" NUMBER(18,0),
	"SCAN_DATE" DATE,
	"ASSIGN_USER" NUMBER(18,0),
	"ASSIGN_DATE" DATE,
	"BARCODE" VARCHAR2(255),
	"DATA_GROUP" NUMBER(18,0),
	"DEVICE_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(18,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER(20,0),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PARTITION_DATE" DATE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
