-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_ACC_STATEMENT_ADDRESS"
   (	"ACC_STATEMENT_ADDRESS_NUM" NUMBER(18,0),
	"BILLING_NAME" VARCHAR2(200),
	"ADDRESS1" VARCHAR2(100),
	"ADDRESS2" VARCHAR2(50),
	"CITY" VARCHAR2(40),
	"STATE_CODE" VARCHAR2(2),
	"ZIPCODE" VARCHAR2(20),
	"CTRY_CODE" VARCHAR2(8),
	"COUNTY" VARCHAR2(30),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"HOLDER_NAME" VARCHAR2(200),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"ACCT_HOLDER_ADDRESS1" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
