-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_SM_TRANS_RESPONSE"
   (	"SM_TRANS_RESPONSE_NUM" NUMBER(18,0),
	"SM_TRANS_REQUEST_NUM" NUMBER(18,0),
	"SM_TRANS_SHIPPER_ID" VARCHAR2(30),
	"SM_TRANS_STATUS_CODE" VARCHAR2(20),
	"SM_TRANS_STATUS_MESSAGE" VARCHAR2(100),
	"SM_TRANS_SHIP_FIRST_NAME" VARCHAR2(30),
	"SM_TRANS_SHIP_MIDDLE_NAME" VARCHAR2(30),
	"SM_TRANS_SHIP_LAST_NAME" VARCHAR2(30),
	"SM_TRANS_SHIP_ADDRESS1" VARCHAR2(100),
	"SM_TRANS_SHIP_ADDRESS2" VARCHAR2(50),
	"SM_TRANS_SHIP_CITY" VARCHAR2(40),
	"SM_TRANS_SHIP_STATE_CODE" VARCHAR2(2),
	"SM_TRANS_SHIP_ZIP_CODE" VARCHAR2(20),
	"SM_TRANS_AREA_CODE" VARCHAR2(4),
	"SM_TRANS_PHONE_NUMBER" VARCHAR2(20),
	"SM_TRANS_SIGNATURE_REQUIRED" VARCHAR2(20),
	"SM_TRANS_EMAIL" VARCHAR2(100),
	"SM_TRANS_COURIER" VARCHAR2(50),
	"SM_TRANS_COURIER_SHIP_METHOD" VARCHAR2(45),
	"SM_TRANS_NUMBER_OF_PACKAGES" NUMBER(9,0),
	"SM_TRANS_SPECIAL_INSTRUCTIONS" VARCHAR2(300),
	"SM_TRANS_EXPECTED_DELIVERY_DT" DATE,
	"SM_TRANS_COURIER_INSTRUCTIONS" VARCHAR2(300),
	"SM_TRANS_DEA_CLASS" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"PARTITION_DATE" DATE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_20110411"  VALUES LESS THAN (TO_DATE(' 2011-04-12 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ,
 PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
