-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_TP_MEDICAID_DRUG"
   (	"TP_MEDICAID_DRUG_NUM" NUMBER(18,0),
	"TP_MEDICAID_LOAD_NUM" NUMBER(18,0),
	"STATE_CODE" VARCHAR2(2),
	"NDC_NUMBER" VARCHAR2(11),
	"BILLING_UNITS" VARCHAR2(2),
	"FORMULARY_INDICATOR" VARCHAR2(1),
	"FORMULARY_IND_EFFECTIVE_DATE" DATE,
	"PACKAGE_SIZE_DIVISOR" NUMBER(11,3),
	"QUANTITY_BILL_UNITS" VARCHAR2(10),
	"BILLING_CODE" VARCHAR2(11),
	"BILLING_CODE_EFFECTIVE_DATE" DATE,
	"GENERIC_BILLING_CODE" VARCHAR2(11),
	"GENERIC_BC_EFFECTIVE_DATE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
