-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_TP_MEASUREMENT"
   (	"TP_MEASUREMENT_NUM" NUMBER(18,0),
	"TP_ITEM_CLAIM_NUM" NUMBER(18,0),
	"MEASURED_DATE_TIME" DATE,
	"MEASURED_DIMENSION" VARCHAR2(2),
	"MEASURED_UNIT" VARCHAR2(2),
	"MEASURED_VALUE" VARCHAR2(15),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
