-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_CODE"
   (	"CODE_NUM" NUMBER(18,0),
	"CODE_TYPE_NUM" NUMBER(18,0),
	"CODE_SET_NUM" NUMBER(18,0),
	"CODE" VARCHAR2(30),
	"DESCRIPTION" VARCHAR2(255),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"INTERNAL" CHAR(1),
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
