-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_EXPORTED_PRESCRIBER"
   (	"EXPORTED_PRESCRIBER_NUM" NUMBER(18,0),
	"PRESCRIBER_EXPORT_REQUEST_NUM" NUMBER(18,0),
	"SCHEDULED_PRESCRIBER_NUM" NUMBER(18,0),
	"EXPORT_DATE" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE,
	"SYS_USER" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
