-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_RX_PURGE_OPTION"
   (	"DATA_GROUP" NUMBER(18,0),
	"ACTIVE_RX_LIFE" NUMBER(5,0),
	"INACTIVE_RX_LIFE" NUMBER(5,0),
	"TRANSFERRED_RX_LIFE" NUMBER(5,0),
	"RX_REFILL_LIFE" NUMBER(5,0),
	"PROFILED_RX_LIFE" NUMBER(5,0),
	"DENIED_RX_LIFE" NUMBER(5,0),
	"CANCELLED_RX_LIFE" NUMBER(5,0),
	"DUR_BUFFER" NUMBER(5,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
