-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_PRINT_DEVICE_PREF"
   (	"PRINT_DEVICE_PREF_NUM" NUMBER(18,0),
	"PRINT_DOC_MEDIA_GROUP_NUM" NUMBER(18,0),
	"CLIENT_LOCATION_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"FACILITY_PRINTER_TRAY_NUM" NUMBER(18,0),
	"ORDER_OF_PREFERENCE" NUMBER(10,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
