-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_PRODUCT_ID_TYPE"
   (	"PRODUCT_ID_TYPE_CODE" CHAR(2),
	"DESCRIPTION" VARCHAR2(255),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
