-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_NOTE"
   (	"NOTE_NUM" NUMBER(18,0),
	"NOTE_TYPE" CHAR(1),
	"ORIGIN" NUMBER(18,0),
	"ORIGIN_TYPE" NUMBER(9,0),
	"ORIGIN_SEQ1" NUMBER(18,0),
	"ORIGIN_SEQ2" NUMBER(18,0),
	"ORIGIN_SEQ3" NUMBER(18,0),
	"NOTE_TEXT" VARCHAR2(4000),
	"DATA_GROUP" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
