-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_PRESCRIBER_ACTIVITY_LOG"
   (	"PRESCRIBER_ACTIVITY_LOG_NUM" NUMBER(18,0),
	"PRESCRIBER_NUM" NUMBER(18,0),
	"MERGED_TO_PRESCRIBER_NUM" NUMBER(18,0),
	"STATUS" CHAR(1),
	"INACTIVITY_CODE" VARCHAR2(4),
	"COMMENTS" VARCHAR2(500),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
