-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_DISPENSING_TEMPLATE"
   (	"DISPENSING_TEMPLATE_NUM" NUMBER(18,0),
	"TEMPLATE_NAME" VARCHAR2(45),
	"TEMPLATE_DESCRIPTION" VARCHAR2(255),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PARTITION_DATE" DATE,
	"H_TYPE" CHAR(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
