-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_ACC_PERSON"
   (	"ACC_PERSON_NUM" NUMBER(18,0),
	"TITLE" VARCHAR2(10),
	"LAST_NAME" VARCHAR2(30),
	"MIDDLE_NAME" VARCHAR2(30),
	"FIRST_NAME" VARCHAR2(30),
	"NAME_SUFFIX" VARCHAR2(10),
	"BIRTH_DATE" DATE,
	"SSN_NUM" VARCHAR2(9),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
