-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_PHONE"
   (	"PHONE_NUM" NUMBER(18,0),
	"CTRY_CODE" VARCHAR2(8),
	"AREA_CODE" VARCHAR2(4),
	"PHONE_NUMBER" VARCHAR2(20),
	"EXT" VARCHAR2(6),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"CARRIER" VARCHAR2(32)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
