-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_PRICE_QUOTE"
   (	"PRICE_QUOTE_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"PRODUCT_NUM" NUMBER(18,0),
	"PATIENT_NUM" NUMBER(18,0),
	"TP_PLAN_NUM" NUMBER(18,0),
	"TP_BENEFIT_GROUP_SEQ" NUMBER(18,0),
	"TP_NETWORK_NUM" NUMBER(18,0),
	"SYSTEM_USER_NUM" NUMBER(18,0),
	"WRITTEN_DATE" DATE,
	"EXPIRE_DATE" DATE,
	"QUANTITY" NUMBER(16,8),
	"QOH_AT_QUOTE" NUMBER(16,8),
	"INGREDIENT_COST" NUMBER(17,6),
	"FEE" NUMBER(17,6),
	"TAX" NUMBER(17,6),
	"DISCOUNT" NUMBER(17,6),
	"OVERRIDE" NUMBER(17,6),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
