-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_C1_RECON"
   (	"C1_RECON_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"TOTAL_NUMBER" NUMBER(18,0),
	"TOTAL_NUMBER_10_POS" NUMBER(18,0),
	"TOTAL_NUMBER_10_NEG" NUMBER(18,0),
	"TOTAL_NUMBER_11_POS" NUMBER(18,0),
	"TOTAL_NUMBER_11_NEG" NUMBER(18,0),
	"TOTAL_NUMBER_12_POS" NUMBER(18,0),
	"TOTAL_NUMBER_12_NEG" NUMBER(18,0),
	"TOTAL_NUMBER_14_POS" NUMBER(18,0),
	"TOTAL_NUMBER_14_NEG" NUMBER(18,0),
	"TOTAL_NUMBER_17_POS" NUMBER(18,0),
	"TOTAL_NUMBER_17_NEG" NUMBER(18,0),
	"TOTAL_NUMBER_CASH_RX_POS" NUMBER(18,0),
	"TOTAL_NUMBER_CASH_RX_NEG" NUMBER(18,0),
	"TOTAL_NUMBER_TP_RX_POS" NUMBER(18,0),
	"TOTAL_NUMBER_TP_RX_NEG" NUMBER(18,0),
	"NET_DOLLAR_CASH_RX" NUMBER(17,6),
	"NET_DOLLAR_TP_RX" NUMBER(17,6),
	"NET_DOLLAR_11_RX" NUMBER(17,6),
	"NET_DOLLAR_10_RX" NUMBER(17,6),
	"NET_PATIENT_PAY_10_RX" NUMBER(17,6),
	"NET_TAX_10_RX" NUMBER(17,6),
	"START_TIME" DATE,
	"END_TIME" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"NET_TP_AR" NUMBER(17,6),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
