-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_MEDICAL_AUTHORIZATION"
   (	"MEDICAL_AUTHORIZATION_NUM" NUMBER(18,0),
	"PATIENT_NUM" NUMBER(18,0),
	"REPRESENTATIVE_NAME" VARCHAR2(30),
	"AUTHORIZED_PARTY" VARCHAR2(255),
	"EFFECTIVE_DATE" DATE,
	"TERMINATION_DATE" DATE,
	"SIGNATURE_IMAGE_NUM" NUMBER(18,0),
	"AUTH_FORM_IMAGE_NUM" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"COMMENT_TEXT" VARCHAR2(1000),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
