-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_IMH_PATIENT_ALLERGY_SYMPT"
   (	"IMH_PATIENT_ALLERGY_SYMPT_NUM" NUMBER(18,0),
	"IMH_PATIENT_ALLERGY_NUM" NUMBER(18,0),
	"EXTERNAL_SYMPTOM_NUM" NUMBER(18,0),
	"DESCRIPTION" VARCHAR2(255),
	"STATUS" VARCHAR2(10),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID'),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
