-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_PATIENT_ID_NCPDP"
   (	"PATIENT_ID_NCPDP_NUM" NUMBER(18,0),
	"PATIENT_NUM" NUMBER(18,0),
	"QUALIFIER" VARCHAR2(2),
	"IDENTIFIER" VARCHAR2(20),
	"ID_STATE" VARCHAR2(2),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID'),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"ID_EXPIRATION_DATE" DATE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
