-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_TP_PRODUCT_ID"
   (	"TP_PRODUCT_ID_NUM" NUMBER(18,0),
	"TP_PLAN_NUM" NUMBER(18,0),
	"TP_BENEFIT_GROUP_SEQ" NUMBER(18,0),
	"TP_NETWORK_NUM" NUMBER(18,0),
	"PRODUCT_NUM" NUMBER(18,0),
	"PRODUCT_ID" VARCHAR2(20),
	"PRODUCT_ID_TYPE" VARCHAR2(20),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
