-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_PRICING_TABLE_DETAIL"
   (	"PRICING_TABLE_DETAIL_NUM" NUMBER(18,0),
	"PRICING_TABLE_CONFIG_NUM" NUMBER(18,0),
	"INDEX_LOW_VALUE" NUMBER(17,6),
	"INDEX_HIGH_VALUE" NUMBER(17,6),
	"TABLE_CALCULATION" VARCHAR2(4000),
	"LINKED_TABLE_NUM" NUMBER(18,0),
	"LINKED_TABLE_NAME" VARCHAR2(30),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
