-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_PATIENT_EXTRA_TP_INFO"
   (	"PATIENT_EXTRA_TP_INFO_NUM" NUMBER(18,0),
	"GUARANTOR_MIDDLE_NAME" VARCHAR2(30),
	"PATIENT_NUM" NUMBER(18,0),
	"GUARANTOR_FIRST_NAME" VARCHAR2(30),
	"GUARANTOR_LAST_NAME" VARCHAR2(30),
	"GUARANTOR_SUFFIX_ABBR" VARCHAR2(12),
	"SERVICE_FACILITY_NAME" VARCHAR2(30),
	"SERVICE_FACILITY_ID_QUALIFIER1" VARCHAR2(10),
	"SERVICE_FACILITY_ID1" VARCHAR2(30),
	"SERVICE_FACILITY_ID_QUALIFIER2" VARCHAR2(10),
	"SERVICE_FACILITY_ID2" VARCHAR2(30),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
