-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_PRICING_FORMULA_ROLE"
   (	"PRICING_FORMULA_ROLE_NUM" NUMBER(18,0),
	"PRICING_FORMULA_CONFIG_NUM" NUMBER(18,0),
	"ROLE_TYPE" NUMBER(9,0),
	"SELECTION_RULE" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
