-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_TP_RULE_ATTRIBUTE_VALUE"
   (	"TP_RULE_ATTRIBUTE_VALUE_NUM" NUMBER(18,0),
	"TP_RULE_SET_NUM" NUMBER(18,0),
	"TP_RULE_ATTRIBUTE_NUM" NUMBER(9,0),
	"ATTRIBUTE_GROUP_NUM" NUMBER(9,0),
	"ATTRIBUTE_SEQUENCE" NUMBER(9,0),
	"VALUE" VARCHAR2(400),
	"WARN_LEV" NUMBER(9,0),
	"EDIT_MESSAGE" VARCHAR2(255),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
