-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_DT_USER_LOG"
   (	"DT_USER_LOG_NUM" NUMBER(10,0),
	"FACILITY_NUM" NUMBER(18,0),
	"LOGIN_TIME" DATE,
	"LOGOUT_TIME" DATE,
	"USER_ID" VARCHAR2(30),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
