-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_LATIN_FREQUENCY"
   (	"LATIN_FREQUENCY_CODE" VARCHAR2(10),
	"DESCRIPTION" VARCHAR2(60),
	"DAYS_MULTIPLIER" NUMBER(16,8),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(18,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
