-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_ACC_STMT_CHARGE_SUMMARY"
   (	"ACC_STMT_CHARGE_SUMMARY_NUM" NUMBER(18,0),
	"ACC_STATEMENT_NUM" NUMBER(18,0),
	"BUCKET_ORDER" NUMBER(9,0),
	"BUCKET_DESCRIPTION" VARCHAR2(1000),
	"BUCKET_MESSAGE" VARCHAR2(1000),
	"AMOUNT" NUMBER(17,6),
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE,
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
