-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_PURCHASE_ORDER"
   (	"PURCHASE_ORDER_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"VENDOR_NUM" NUMBER(18,0),
	"PO_NUMBER" VARCHAR2(10),
	"CREATE_DATE" DATE,
	"CREATE_USER" NUMBER(18,0),
	"EXPIRATION_DATE" DATE,
	"PURCHASE_ORDER_TYPE_CODE" CHAR(1),
	"STATUS_CODE" CHAR(1),
	"RECEIVED_DATE" DATE,
	"IS_SCHEDULE_2_ORDER" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"PARTITION_DATE" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"EXTERNAL_REFERENCE_ID" VARCHAR2(30),
	"MCK_CONNECT_PO_STATUS" CHAR(1)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
