-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_COUNTRY"
   (	"CTRY_CODE" VARCHAR2(8),
	"NAME" VARCHAR2(30),
	"IS_STATE_REQD" CHAR(1),
	"INTL_PHONE_CODE" VARCHAR2(3),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ISO_CTRY_CODE" VARCHAR2(2),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
