-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_PATIENT_NOTE"
   (	"PATIENT_NUM" NUMBER(18,0),
	"PATIENT_NOTE_SEQ" NUMBER(18,0),
	"NOTE_TEXT" VARCHAR2(4000),
	"CREATE_DATE" DATE,
	"CREATE_USER" NUMBER(18,0),
	"PRIORITY" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PRIORITY_INDICATOR" CHAR(1),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PATIENT_NOTE_TYPE_CODE" CHAR(1),
	"PROCESS_FLAG" CHAR(1) DEFAULT 'P',
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
