-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_FACILITY_LINK"
   (	"FACILITY_LINK_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"FACILITY_LINK_TYPE" CHAR(1),
	"LINKED_FACILITY_NUM" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"IS_ACTIVE" CHAR(1),
	"PRIORITY" NUMBER(3,0),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"FULFILLMENT_TYPE" CHAR(1)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
