-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_IMH_MESSAGE"
   (	"IMH_MESSAGE_NUM" NUMBER(18,0),
	"PATIENT_NUM" NUMBER(18,0),
	"RECEIVED_DATE" DATE,
	"PATIENT_ID_SOURCE_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID'),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"EXTERNAL_MESSAGE_ID" VARCHAR2(30)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
