-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_GOOD_FAITH_EFFORT_REASON"
   (	"GOOD_FAITH_EFFORT_REASON_NUM" NUMBER(18,0),
	"DESCRIPTION" VARCHAR2(45),
	"SATISFY_ATTEMPTS_NUM" NUMBER(2,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
