-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_PRICING_HOTLIST_ITEM"
   (	"PRICING_HOTLIST_ITEM_NUM" NUMBER(18,0),
	"PRICING_HOTLIST_CONFIG_NUM" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"QUANTITY" NUMBER(16,8),
	"COST" NUMBER(17,6),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER(20,0),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
