-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_PO_ACKNOWLEDGEMENT_ITEM"
   (	"PO_ACKNOWLEDGEMENT_ITEM_NUM" NUMBER(18,0),
	"PURCHASE_ORDER_ACK_NUM" NUMBER(18,0),
	"PURCHASE_ORDER_ITEM_NUM" NUMBER(18,0),
	"QUANTITY" NUMBER(9,0),
	"ACQUISITION_COST" NUMBER(17,6),
	"SHIPPING_STATUS" CHAR(2),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
