-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_ACC_PREPAYMENT_LIST"
   (	"ACC_PREPAYMENT_LIST_NUM" NUMBER(18,0),
	"DESCRIPTION" VARCHAR2(200),
	"NUM_UPDATES" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"FACILITY_NUM" NUMBER(18,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
