-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_OUTBOUND_EMAIL_MESSAGE"
   (	"OUTBOUND_EMAIL_MESSAGE_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"PATIENT_NUM" NUMBER(18,0),
	"ORDER_NUM" NUMBER(18,0),
	"TO_ADDR" VARCHAR2(511),
	"SUBJECT" VARCHAR2(100),
	"MESSAGE" VARCHAR2(4000),
	"MESSAGE_TYPE" VARCHAR2(20),
	"MESSAGE_STATUS" VARCHAR2(20),
	"IS_SUCCESSFUL" NUMBER(1,0),
	"ERROR_MESSAGE" VARCHAR2(2000),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"COMMUNICATION_DATE" DATE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_20110411"  VALUES LESS THAN (TO_DATE(' 2011-04-12 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ,
 PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
