-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_RX_PURGE_LOG"
   (	"PURGE_LOG_NUM" NUMBER(18,0),
	"PURGE_DATE" DATE,
	"ACTIVE_RX_COUNT" NUMBER(18,0),
	"INACTIVE_RX_COUNT" NUMBER(18,0),
	"TRANSFERRED_RX_COUNT" NUMBER(18,0),
	"DUR_RX_COUNT" NUMBER(18,0),
	"PROFILED_RX_COUNT" NUMBER(18,0),
	"IN_PROFILED_RX_COUNT" NUMBER(18,0),
	"IN_DUR_RX_COUNT" NUMBER(18,0),
	"DENIED_RX_COUNT" NUMBER(18,0),
	"CANCELLED_RX_COUNT" NUMBER(18,0),
	"ERROR_RX_COUNT" NUMBER(18,0),
	"TOTAL_RX_COUNT" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
