-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_CSR_STATE_FIELD_RULE"
   (	"CSR_STATE_FIELD_RULE_NUM" NUMBER(18,0),
	"CSR_STATE_NUM" NUMBER(18,0),
	"CSR_FIELD_NUM" NUMBER(9,0),
	"MESSAGE_TEXT" VARCHAR2(255),
	"REQ_OPT_NOT" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"DATA_FILTER" CLOB,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
