-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_ITEM_MESSAGE"
   (	"ITEM_MESSAGE_NUM" NUMBER(18,0),
	"ORDER_NUM" NUMBER(18,0),
	"ITEM_SEQ" NUMBER(18,0),
	"MESSAGE_CODE" VARCHAR2(100),
	"MESSAGE_TEXT" VARCHAR2(1000),
	"WARN_LEV" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"MESSAGE_SOURCE" VARCHAR2(100),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
