-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_WF_CENTRAL_FILL_DECLINE"
   (	"WF_PROCESS_DEFINITION_NUM" NUMBER(18,0),
	"PROC_INST_SEQ" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"TYPE" CHAR(1),
	"RESTOCK_PRODUCT_NUM" NUMBER(18,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
