-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_TP_DUR_PPS"
   (	"TP_DUR_PPS_NUM" NUMBER(18,0),
	"TP_ITEM_CLAIM_NUM" NUMBER(18,0),
	"DISPLAY_SEQ" NUMBER(18,0),
	"REASON_FOR_SERVICE_CODE" VARCHAR2(2),
	"PROFESSIONAL_SERVICE_CODE" VARCHAR2(2),
	"RESULT_OF_SERVICE" VARCHAR2(2),
	"LEVEL_OF_EFFORT" VARCHAR2(2),
	"CO_AGENT_ID_QUALIFIER" VARCHAR2(100),
	"CO_AGENT_ID" VARCHAR2(100),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE,
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
