-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_SHIPPING_METHOD"
   (	"SHIPPING_METHOD_NUM" NUMBER(18,0),
	"DESCRIPTION" VARCHAR2(100),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"METHOD_CODE" VARCHAR2(25),
	"IS_DEFAULT_COURIER_METHOD" CHAR(1),
	"SHIPPING_COST" NUMBER(17,6),
	"SHIPPING_COURIER_NUM" NUMBER(18,0)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
