-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_GENERIC_SUB_GROUP_PRODUCT"
   (	"GENERIC_SUB_GROUP_PRODUCT_NUM" NUMBER(18,0),
	"GENERIC_SUB_GROUP_NUM" NUMBER(18,0),
	"PRODUCT_NUM" NUMBER(18,0),
	"RANK" NUMBER(3,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"SUBSTITUTION_TYPE" VARCHAR2(1),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
