-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_PRODUCT_STATE_OVERRIDE"
   (	"PRODUCT_STATE_OVERRIDE_NUM" NUMBER(18,0),
	"PRODUCT_NUM" NUMBER(18,0),
	"CTRY_CODE" VARCHAR2(8),
	"STATE_CODE" VARCHAR2(2),
	"DRUG_SCHEDULE" VARCHAR2(30),
	"IS_REPORTABLE" CHAR(1),
	"IS_SCHEDULED_RX_ID_REQ" CHAR(1),
	"IS_TAX_EXEMPT" CHAR(1),
	"IS_MANDATED" CHAR(1),
	"PRICE_BOARD_QUANTITY" NUMBER(16,8),
	"PRICE_BOARD_QUANTITY2" NUMBER(16,8),
	"PRICE_BOARD_QUANTITY3" NUMBER(16,8),
	"PRICE_BOARD_QUANTITY4" NUMBER(16,8),
	"PRICE_BOARD_QUANTITY5" NUMBER(16,8),
	"BILLING_UNITS" VARCHAR2(2),
	"FORMULARY_INDICATOR" VARCHAR2(1),
	"FORMULARY_IND_EFFECTIVE_DATE" DATE,
	"PACKAGE_SIZE_DIVISOR" NUMBER(11,3),
	"QUANTITY_BILL_UNITS" VARCHAR2(10),
	"BILLING_CODE" VARCHAR2(11),
	"BILLING_CODE_EFFECTIVE_DATE" DATE,
	"GENERIC_BILLING_CODE" VARCHAR2(11),
	"GENERIC_BC_EFFECTIVE_DATE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
