-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_IMPORTED_PRESCRIBER_ERROR"
   (	"IMPORTED_PRESCRIBER_ERROR_NUM" NUMBER(18,0),
	"IMPORTED_PRESCRIBER_NUM" NUMBER(18,0),
	"ERROR_TEXT" VARCHAR2(255),
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE,
	"SYS_USER" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"ERROR_VALUE" VARCHAR2(256),
	"ERROR_TABLE" VARCHAR2(30),
	"ERROR_COLUMN" VARCHAR2(30),
	"ERROR_TABLE_PK" NUMBER(18,0),
	"ERROR_REASON" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
