-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_HEALTH_CARD_RANGE"
   (	"HEALTH_CARD_RANGE_NUM" NUMBER(18,0),
	"HEALTH_CARD_BIN_NUM" NUMBER(18,0),
	"HEALTH_CARD_RANGE_LOW" NUMBER(20,0),
	"HEALTH_CARD_RANGE_HIGH" NUMBER(20,0),
	"HEALTH_CARD_RANGE_DELETED" CHAR(1),
	"HEALTH_CARD_TYPE" VARCHAR2(30),
	"HEALTH_CARD_BIN_PARTIAL_DATE" DATE,
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE,
	"ERX_CLIENT_ID" VARCHAR2(200),
	"PARTITION_DATE" DATE,
	"H_TYPE" CHAR(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("ODS_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
