-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_PRICING_HOTLIST_CONFIG"
   (	"PRICING_HOTLIST_CONFIG_NUM" NUMBER(18,0),
	"PRICING_HOTLIST_NUM" NUMBER(18,0),
	"IS_TOTAL_COST" CHAR(1),
	"IS_APPLY_DISCOUNTS" CHAR(1),
	"ADJUST_MASTER_PRODUCT_NUM" NUMBER(18,0),
	"ADJUST_COST_BASIS_NUM" NUMBER(18,0),
	"IS_AUTO_ADJUST_PRICES" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"EFFECTIVE_DATE" DATE,
	"TERM_DATE" DATE,
	"PUBLISH_STATUS" CHAR(1),
	"PUBLISH_USER" NUMBER(18,0),
	"PUBLISH_DATE" DATE,
	"EXTRACTION_METHOD" VARCHAR2(30),
	"DATA_FILTER" CLOB,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER(20,0),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
