-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_ZIPCODE"
   (	"CSZ_NUM" NUMBER(18,0),
	"ZIPCODE" VARCHAR2(20),
	"CTRY_CODE" VARCHAR2(8),
	"STATE_CODE" VARCHAR2(2),
	"COUNTY" VARCHAR2(30),
	"CITY" VARCHAR2(40),
	"POST_OFFICE" VARCHAR2(40),
	"IS_USER_DEFINED" CHAR(1),
	"IS_DEFAULT" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER(20,0),
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;

