-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_ACC_STATEMENT"
   (	"ACC_STATEMENT_NUM" NUMBER(18,0),
	"ACC_AR_ACCT_NUM" NUMBER(18,0),
	"BALANCE_AMOUNT" NUMBER(17,6),
	"IS_PAID" CHAR(1),
	"GENERATION_DATE" DATE,
	"DUE_DATE" DATE,
	"DISCOUNT_DUE_DATE" DATE,
	"UNPAID_AMOUNT" NUMBER(17,6),
	"MINIMUM_AMOUNT" NUMBER(17,6),
	"DISCOUNT_AMOUNT" NUMBER(17,6),
	"PAYMENT_TERMS_DAYS" NUMBER(18,0),
	"PAYMENT_APPLY_DISCOUNT" CHAR(1),
	"PAYMENT_DISCOUNT_DAYS" NUMBER(18,0),
	"PAYMENT_DISCOUNT_PERCENTAGE" NUMBER(18,0),
	"PAYMENT_DISCOUNT_MONEY" NUMBER(18,0),
	"APPLY_FINANCE_CHARGES" CHAR(1),
	"APPLY_FINANCE_CHARGES_DAYS" NUMBER(18,0),
	"APPLY_FINANCE_CHARGES_BAL" NUMBER(18,0),
	"FINANCE_CHARGE_PERCENTAGE" NUMBER(17,6),
	"FINANCE_CHARGE_MONEY" NUMBER(17,6),
	"FINANCE_CHARGE_PERIOD" CHAR(1),
	"MESSAGES" VARCHAR2(4000),
	"NUM_UPDATES" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"PARTITION_DATE" DATE,
	"STATEMENT_DATE" DATE,
	"DUNNING_MESSAGES" VARCHAR2(4000),
	"ACC_TX_NUM" NUMBER(18,0),
	"CURRENT_AMOUNT" NUMBER(17,6),
	"ACC_STATEMENT_ADDRESS_NUM" NUMBER(18,0),
	"PRINT_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"CURRENT_BALANCE_DUE" NUMBER(17,6)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
