-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_RX_TRANSFER_HISTORY"
   (	"RX_TRANSFER_SEQ" NUMBER(18,0),
	"RX_HISTORY_SEQ" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"FILL_NUM" NUMBER(9,0),
	"PRODUCT_NDC" VARCHAR2(11),
	"QTY_DISPENSED" NUMBER(10,3),
	"FILL_DATE" DATE,
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
