-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_ACCOUNT_CREDIT_CARD"
   (	"ACCOUNT_CREDIT_CARD_NUM" NUMBER(18,0),
	"PATIENT_NUM" NUMBER(18,0),
	"CARD_TYPE_NUM" NUMBER(9,0),
	"EXPIRATION_DATE" DATE,
	"CHARGE_CARD_NUM" VARCHAR2(200),
	"KEY_ALIAS" VARCHAR2(20),
	"CARDHOLDER_NAME" VARCHAR2(61),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
