-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_TP_ADJ_DRIVER_CONFIG"
   (	"TP_ADJ_DRIVER_CONFIG_NUM" NUMBER(18,0),
	"TP_ADJ_DRIVER_NUM" NUMBER(18,0),
	"CONFIGURATION_NAME" VARCHAR2(80),
	"CONFIGURATION" VARCHAR2(4000),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
