-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_ACCURACY_SCAN_LOG"
   (	"ACCURACY_SCAN_LOG_NUM" NUMBER(18,0),
	"RX_FILL_SEQ" NUMBER(18,0),
	"RESULT" CHAR(1),
	"REASON" VARCHAR2(50),
	"VIAL_SCAN_DATA" VARCHAR2(40),
	"STOCK_SCAN_DATA" VARCHAR2(40),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
