-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_ACC_ACCT_TYPE"
   (	"ACC_ACCT_TYPE_NUM" NUMBER(18,0),
	"SUB_ACCOUNT_TYPE_OF" NUMBER(18,0),
	"NAME" VARCHAR2(20),
	"ASSET_OR_LIABILITY" CHAR(1),
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
