-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_CONTACT_EVENT_HISTORY"
   (	"CONTACT_EVENT_HISTORY_NUM" NUMBER(18,0),
	"CONTACT_EVENT_NUM" NUMBER(18,0),
	"CONTACT_STATUS_NUM" NUMBER(18,0),
	"CONTACT_METHOD_NUM" NUMBER(18,0),
	"CONTACT_NAME" VARCHAR2(2000),
	"CREATE_USER" NUMBER(18,0),
	"CREATE_DATE" DATE,
	"HISTORY_COMMENT" VARCHAR2(2000),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"FACILITY_NUM" NUMBER(18,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
