-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."ACK_SHIPPING_STATUS_TYPE"
   (	"ACK_SHIPPING_STATUS_TYPE_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"ACK_SHIPPING_STATUS" CHAR(2),
	"DESCRIPTION" VARCHAR2(30),
	"ERX_CLIENT_ID" VARCHAR2(100)
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_ACK_ITEM_STATUS_TYPE" ON "TREXONE_DW_DATA"."ACK_SHIPPING_STATUS_TYPE" ("ACK_SHIPPING_STATUS_TYPE_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."ACK_SHIPPING_STATUS_TYPE" ADD CONSTRAINT "PK_ACK_ITEM_STATUS_TYPE" PRIMARY KEY ("ACK_SHIPPING_STATUS_TYPE_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_ACK_ITEM_STATUS_TYPE"  ENABLE;
-- ==========================================
