-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."AGENCY_TYPE"
   (	"ATD_AGENCY_TYPE_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"ATD_AGENCY_TYPE_NUM" NUMBER(18,0),
	"ATD_AGENCY_NAME" VARCHAR2(50),
	"ATD_BILLING_PRIORITY" NUMBER(10,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_AGENCY_TYPE" ON "TREXONE_DW_DATA"."AGENCY_TYPE" ("ATD_AGENCY_TYPE_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."AGENCY_TYPE" ADD CONSTRAINT "PK_AGENCY_TYPE" PRIMARY KEY ("ATD_AGENCY_TYPE_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_AGENCY_TYPE"  ENABLE;
-- ==========================================
