-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."ALLERGY"
   (	"ALD_ALLERGY_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"ALD_ALLERGEN_REF_TYPE" VARCHAR2(4),
	"ALD_DESCRIPTION" VARCHAR2(255),
	"ALD_ALLERGEN_REF_NUM" CHAR(20),
	"ALD_ALLERGEN_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_ALLERGY" ON "TREXONE_DW_DATA"."ALLERGY" ("ALD_ALLERGY_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."ALLERGY" ADD CONSTRAINT "PK_ALLERGY" PRIMARY KEY ("ALD_ALLERGY_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_ALLERGY"  ENABLE;
-- ==========================================
