-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."ALLERGY_STATUS_DETAIL"
   (	"ASD_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PD_PATIENT_KEY" NUMBER(18,0),
	"ALD_ALLERGY_KEY" NUMBER(18,0),
	"ASD_ALLERGY_STATUS_SEQ" NUMBER(18,0),
	"ASD_NEW_STATUS" CHAR(1),
	"ASD_EFFECTIVE_DATE" DATE,
	"ASD_COMMENTARY" VARCHAR2(255),
	"ASD_CREATE_DATE" DATE,
	"ASD_CREATE_USER" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	 CONSTRAINT "FK_ALLERGY_4" FOREIGN KEY ("ALD_ALLERGY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."ALLERGY" ("ALD_ALLERGY_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_01" FOREIGN KEY ("PD_PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") DISABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_ALLERGY_STATUS_DETAIL" ON "TREXONE_DW_DATA"."ALLERGY_STATUS_DETAIL" ("ASD_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."ALLERGY_STATUS_DETAIL" ADD CONSTRAINT "PK_ALLERGY_STATUS_DETAIL" PRIMARY KEY ("ASD_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_ALLERGY_STATUS_DETAIL"  ENABLE;
-- ==========================================
