-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."BILLING_STATUS_TYPE"
   (	"BS_BILLING_STATUS_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"BS_BILLING_STATUS" CHAR(1),
	"BS_BILLING_STATUS_DESC" VARCHAR2(30),
	"ERX_CLIENT_ID" VARCHAR2(100)
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_BILLING_STATUS_TYPE" ON "TREXONE_DW_DATA"."BILLING_STATUS_TYPE" ("BS_BILLING_STATUS_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."BILLING_STATUS_TYPE" ADD CONSTRAINT "PK_BILLING_STATUS_TYPE" PRIMARY KEY ("BS_BILLING_STATUS_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_BILLING_STATUS_TYPE"  ENABLE;
-- ==========================================
