-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."BIN_TYPE"
   (	"BIN_TYPE_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"STAGING_BIN_TYPE_NUM" NUMBER(18,0),
	"FD_FACILITY_KEY" NUMBER(18,0),
	"BIN_TYPE_NAME" VARCHAR2(30),
	"FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID'),
	 CONSTRAINT "PK_BIN_TYPE" PRIMARY KEY ("BIN_TYPE_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_FACILITY_103" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE
   ) ;
-- ==========================================
