-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."CENTRAL_FILL_INDICATOR"
   (	"CENTRAL_FILL_INDICATOR_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"IS_CENTRAL_FILL" VARCHAR2(7),
	"IS_PULLED_BACK" VARCHAR2(7),
	"IS_PACKED" VARCHAR2(7),
	"IS_CENTRAL_FILL_DECLINED" VARCHAR2(7),
	"ERX_CLIENT_ID" VARCHAR2(100)
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_CENTRAL_FILL_INDICATOR" ON "TREXONE_DW_DATA"."CENTRAL_FILL_INDICATOR" ("CENTRAL_FILL_INDICATOR_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."CENTRAL_FILL_INDICATOR" ADD CONSTRAINT "PK_CENTRAL_FILL_INDICATOR" PRIMARY KEY ("CENTRAL_FILL_INDICATOR_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_CENTRAL_FILL_INDICATOR"  ENABLE;
-- ==========================================
