-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."CENTRAL_FILL_PRODUCT_EXCLUSION"
   (	"FD_FACILITY_KEY" NUMBER(18,0),
	"LOCAL_FD_FACILITY_KEY" NUMBER(18,0),
	"PRODUCT_EXCLUSION_NUM" NUMBER(18,0),
	"PRD_PRODUCT_KEY" NUMBER(18,0),
	"DEA_CLASS" CHAR(1),
	"GC3_CODE" VARCHAR2(20),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	 CONSTRAINT "FK_PRODUCT_34" FOREIGN KEY ("PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_76" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_77" FOREIGN KEY ("LOCAL_FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE
   ) ;
-- ==========================================
