-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."CODE_LIST"
   (	"CODE_LIST_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"CL_CODE_LIST_NUM" NUMBER(18,0),
	"CL_CODE_TYPE_NUM" NUMBER(18,0),
	"CL_CODE_LIST_NAME" VARCHAR2(125),
	"CL_CODE_LIST_DESCRIPTION" VARCHAR2(255),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_CODE_LIST" ON "TREXONE_DW_DATA"."CODE_LIST" ("CODE_LIST_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."CODE_LIST" ADD CONSTRAINT "PK_CODE_LIST" PRIMARY KEY ("CODE_LIST_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_CODE_LIST"  ENABLE;
-- ==========================================
