-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."CODE"
   (	"CODE_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"CODE_NUM" NUMBER(18,0),
	"CODE" VARCHAR2(30),
	"CODE_DESCRIPTION" VARCHAR2(255),
	"CODE_SET_NUM" NUMBER(18,0),
	"CODE_TYPE_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_CODE" ON "TREXONE_DW_DATA"."CODE" ("CODE_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."CODE" ADD CONSTRAINT "PK_CODE" PRIMARY KEY ("CODE_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_CODE"  ENABLE;
-- ==========================================
