-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."CODE_LIST_ITEM"
   (	"CLI_CODE_LIST_ITEM_NUM" NUMBER(18,0),
	"CLI_CODE_LIST_NUM" NUMBER(18,0),
	"CLI_CODE_NUM" NUMBER(18,0),
	"CLI_DATA_GROUP" NUMBER(18,0),
	"CLI_EXCLUDE" CHAR(1),
	"CLI_IS_EDITABLE" CHAR(1),
	"CLI_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_CODE_LIST_ITEM" ON "TREXONE_DW_DATA"."CODE_LIST_ITEM" ("CLI_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."CODE_LIST_ITEM" ADD CONSTRAINT "PK_CODE_LIST_ITEM" PRIMARY KEY ("CLI_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_CODE_LIST_ITEM"  ENABLE;
-- ==========================================
