-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."CONFIG_PROPERTY"
   (	"CP_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"CONFIG_PROPERTY_NUM" NUMBER(18,0),
	"CP_NAME" VARCHAR2(255),
	"CP_DESCRIPTION" VARCHAR2(255),
	"CP_DEFAULT_VALUE" VARCHAR2(3000),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	"FD_FACILITY_KEY" NUMBER(18,0),
	"SYS_USER_KEY" NUMBER(18,0),
	"DATE_KEY" NUMBER(18,0),
	"TIME_KEY" NUMBER(5,0),
	"CP_VALUE" VARCHAR2(4000),
	"CP_APPLICATION_VERSION" VARCHAR2(8),
	 CONSTRAINT "FK_FACILITY_92" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_94" FOREIGN KEY ("DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_SYS_USER_86" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_38" FOREIGN KEY ("TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_CONFIG_PROPERTY" ON "TREXONE_DW_DATA"."CONFIG_PROPERTY" ("CP_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."CONFIG_PROPERTY" ADD CONSTRAINT "PK_CONFIG_PROPERTY" PRIMARY KEY ("CP_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_CONFIG_PROPERTY"  ENABLE;
-- ==========================================
