-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."CONTACT_EVENT_TYPE"
   (	"CET_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"CET_TYPE_NUM" NUMBER(18,0),
	"CET_DESCRIPTION" VARCHAR2(100),
	"ERX_CLIENT_ID" VARCHAR2(100)
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_CONTACT_EVENT_TYPE" ON "TREXONE_DW_DATA"."CONTACT_EVENT_TYPE" ("CET_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."CONTACT_EVENT_TYPE" ADD CONSTRAINT "PK_CONTACT_EVENT_TYPE" PRIMARY KEY ("CET_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_CONTACT_EVENT_TYPE"  ENABLE;
-- ==========================================
