-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."CONTACT_METHOD"
   (	"CM_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"CM_NUMBER" NUMBER(18,0),
	"CM_DESCRIPTION" VARCHAR2(50),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_CONTACT_METHOD" ON "TREXONE_DW_DATA"."CONTACT_METHOD" ("CM_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."CONTACT_METHOD" ADD CONSTRAINT "PK_CONTACT_METHOD" PRIMARY KEY ("CM_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_CONTACT_METHOD"  ENABLE;
-- ==========================================
