-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."CONTACT_EVENT"
   (	"CET_KEY" NUMBER(18,0),
	"CM_KEY" NUMBER(18,0),
	"CONT_STATUS_KEY" NUMBER(18,0),
	"CONT_TYPE_KEY" NUMBER(18,0),
	"DATE_KEY" NUMBER(18,0),
	"FD_FACILITY_KEY" NUMBER(18,0),
	"WFSD_KEY" NUMBER(18,0),
	"PRD_PRODUCT_KEY" NUMBER(18,0),
	"PRS_PRESCRIBER_KEY" NUMBER(18,0),
	"PD_PATIENT_H_KEY" NUMBER(18,0),
	"DRUG_KEY" NUMBER(18,0),
	"SYS_USER_KEY" NUMBER(18,0),
	"CE_CONTACT_EVENT_NUM" NUMBER(18,0),
	"CE_PRODUCT_QUANTITY" NUMBER(13,3),
	"CE_RX_RECORD_NUM" NUMBER(18,0),
	"CE_RX_FILL_SEQ" NUMBER(18,0),
	"CE_EVENT_COMMENT" VARCHAR2(2000),
	"CE_RX_NUMBER" VARCHAR2(20),
	"PARTITION_DATE" DATE,
	"CE_REFILL_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PD_PATIENT_KEY" NUMBER(18,0),
	"CE_CONTACT_NAME" VARCHAR2(2000),
	"H_LEVEL" NUMBER,
	"CREATE_USER" NUMBER(18,0),
	"TRANSACTION_NUM" VARCHAR2(255),
	"DISPENSED_PRD_PRODUCT_KEY" NUMBER(18,0),
	"DISPENSED_DRUG_KEY" NUMBER(18,0),
	"REFILLS_AUTHORIZED" NUMBER(9,0),
	"REFILLS_REMAINING" NUMBER(9,2),
	"SIG" VARCHAR2(2000),
	"PROMISE_DATE_KEY" NUMBER(18,0),
	"PROMISE_TIME_KEY" NUMBER(18,0),
	"INFORM_ON_RESOLUTION" NUMBER(9,0),
	"MANAGING_FD_FACILITY_KEY" NUMBER(18,0),
	"PADR_KEY" NUMBER(18,0),
	"CREATE_DATE_KEY" NUMBER(18,0),
	"CREATE_TIME_KEY" NUMBER(5,0),
	"TIME_KEY" NUMBER(5,0),
	"PARTIAL_FILL_SEQ" NUMBER(2,0),
	"CLARIFICATION_REASON_NUM" NUMBER(9,0),
	 CONSTRAINT "FK_CONTACT_EVENT_TYPE_2" FOREIGN KEY ("CET_KEY")
	  REFERENCES "TREXONE_DW_DATA"."CONTACT_EVENT_TYPE" ("CET_KEY") DISABLE,
	 CONSTRAINT "FK_CONTACT_METHOD_2" FOREIGN KEY ("CM_KEY")
	  REFERENCES "TREXONE_DW_DATA"."CONTACT_METHOD" ("CM_KEY") DISABLE,
	 CONSTRAINT "FK_CONTACT_STATUS_TYPE_2" FOREIGN KEY ("CONT_STATUS_KEY")
	  REFERENCES "TREXONE_DW_DATA"."CONTACT_STATUS_TYPE" ("CONT_STATUS_KEY") DISABLE,
	 CONSTRAINT "FK_CONTACT_TYPE_2" FOREIGN KEY ("CONT_TYPE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."CONTACT_TYPE" ("CONT_TYPE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_33" FOREIGN KEY ("DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DRUG_3" FOREIGN KEY ("DRUG_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DRUG" ("DRUG_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_35" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_H_19" FOREIGN KEY ("PD_PATIENT_H_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT_H" ("PD_PATIENT_H_KEY") DISABLE,
	 CONSTRAINT "FK_PRESCRIBER_2" FOREIGN KEY ("PRS_PRESCRIBER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRESCRIBER" ("PRS_PRESCRIBER_KEY") DISABLE,
	 CONSTRAINT "FK_PRODUCT_16" FOREIGN KEY ("PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE,
	 CONSTRAINT "FK_SYS_USER_39" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE,
	 CONSTRAINT "FK_WF_STEP_5" FOREIGN KEY ("WFSD_KEY")
	  REFERENCES "TREXONE_DW_DATA"."WF_STEP" ("WFSD_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_19" FOREIGN KEY ("PD_PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") DISABLE,
	 CONSTRAINT "FK_PRODUCT_47" FOREIGN KEY ("DISPENSED_PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE,
	 CONSTRAINT "FK_DRUG_20" FOREIGN KEY ("DISPENSED_DRUG_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DRUG" ("DRUG_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_95" FOREIGN KEY ("MANAGING_FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_PRESCRIBER_ADDRESS_08" FOREIGN KEY ("PADR_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRESCRIBER_ADDRESS" ("PADR_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_118" FOREIGN KEY ("PROMISE_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_39" FOREIGN KEY ("PROMISE_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_119" FOREIGN KEY ("CREATE_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_45" FOREIGN KEY ("CREATE_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_46" FOREIGN KEY ("TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
