-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."CONTACT_TYPE"
   (	"CONT_TYPE_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"CONT_TYPE_NUM" NUMBER(18,0),
	"CONTACT_TYPE_DESCRIPTION" VARCHAR2(100),
	"ERX_CLIENT_ID" VARCHAR2(100)
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_CONTACT_TYPE" ON "TREXONE_DW_DATA"."CONTACT_TYPE" ("CONT_TYPE_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."CONTACT_TYPE" ADD CONSTRAINT "PK_CONTACT_TYPE" PRIMARY KEY ("CONT_TYPE_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_CONTACT_TYPE"  ENABLE;
-- ==========================================
