-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."COST_BASIS"
   (	"COST_BASIS_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"COST_BASIS_NUM" NUMBER(18,0),
	"COST_BASIS_NAME" VARCHAR2(30),
	"COST_BASIS_DESC" VARCHAR2(255),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_COST_BASIS" ON "TREXONE_DW_DATA"."COST_BASIS" ("COST_BASIS_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."COST_BASIS" ADD CONSTRAINT "PK_COST_BASIS" PRIMARY KEY ("COST_BASIS_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_COST_BASIS"  ENABLE;
-- ==========================================
