-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."COUPON_TYPE"
   (	"C_COUPON_TYPE_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"C_COUPON_TYPE" VARCHAR2(30),
	"C_COUPON_TYPE_DESC" VARCHAR2(255),
	"ERX_CLIENT_ID" VARCHAR2(100)
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_COUPON_TYPE" ON "TREXONE_DW_DATA"."COUPON_TYPE" ("C_COUPON_TYPE_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."COUPON_TYPE" ADD CONSTRAINT "PK_COUPON_TYPE" PRIMARY KEY ("C_COUPON_TYPE_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_COUPON_TYPE"  ENABLE;
-- ==========================================
