-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."COURIER_SHIPMENT_TYPE"
   (	"COURIER_SHIPMENT_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"SHIPPING_METHOD_NUM" NUMBER(18,0),
	"SHIPPING_METHOD_DESC" VARCHAR2(100),
	"SHIPPING_COURIER_NUM" NUMBER(18,0),
	"COURIER_NAME" VARCHAR2(50),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID'),
	 CONSTRAINT "PK_COURIER_SHIPMENT_TYPE" PRIMARY KEY ("COURIER_SHIPMENT_KEY")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
