-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."CPS_CHECKIN_FACT"
   (	"CPS_CHECKIN_KEY" NUMBER(18,0) CONSTRAINT "PK_CPS_CHECKIN_FACT" NOT NULL ENABLE,
	"CPS_PROGRAM_KEY" NUMBER(18,0),
	"PATIENT_KEY" NUMBER(18,0),
	"FACILITY_KEY" NUMBER(18,0),
	"SYSTEM_DUE_DATE" DATE,
	"OVERRIDE_DUE_DATE" DATE,
	"RESOLVED_DATE" DATE,
	"UPDATED_BY" VARCHAR2(100),
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "FK_CPS_PROGRAM_04" FOREIGN KEY ("CPS_PROGRAM_KEY")
	  REFERENCES "TREXONE_DW_DATA"."CPS_PROGRAM" ("CPS_PROGRAM_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_48" FOREIGN KEY ("PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_116" FOREIGN KEY ("FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE
   )
  PARTITION BY RANGE ("RESOLVED_DATE") INTERVAL (NUMTOYMINTERVAL(1,'MONTH')) STORE IN ("DW_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
