-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."CPS_ENROLLMENT_FACT"
   (	"CPS_PROGRAM_KEY" NUMBER(18,0),
	"CPS_PATIENT_STATUS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"STATUS_DATE" DATE NOT NULL ENABLE,
	"CPS_STATUS_KEY" NUMBER(18,0),
	"FACILITY_KEY" NUMBER(18,0),
	"PATIENT_KEY" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"VENDOR_PATIENT_ID" VARCHAR2(100),
	"UPDATED_BY" VARCHAR2(50),
	 CONSTRAINT "FK_CPS_PROGRAM_01" FOREIGN KEY ("CPS_PROGRAM_KEY")
	  REFERENCES "TREXONE_DW_DATA"."CPS_PROGRAM" ("CPS_PROGRAM_KEY") DISABLE,
	 CONSTRAINT "FK_CPS_STATUS_01" FOREIGN KEY ("CPS_STATUS_KEY")
	  REFERENCES "TREXONE_DW_DATA"."CPS_STATUS" ("CPS_STATUS_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_114" FOREIGN KEY ("FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_45" FOREIGN KEY ("PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") DISABLE
   )
  PARTITION BY RANGE ("STATUS_DATE") INTERVAL (NUMTOYMINTERVAL(1,'MONTH')) STORE IN ("DW_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
