-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."CPS_MESSAGE_FACT"
   (	"CPS_MESSAGE_KEY" NUMBER(18,0) CONSTRAINT "PK_CPS_MEASURE_FACT" NOT NULL ENABLE,
	"MESSAGE_TEXT" CLOB,
	"RECEIVED_DATE" DATE NOT NULL ENABLE,
	"UPDATE_DATE" DATE,
	"CPS_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CPS_PROGRAM_KEY" NUMBER(18,0),
	"CPS_STATUS_KEY" NUMBER(18,0),
	"CPS_MESSAGE_TYPE_KEY" NUMBER(18,0),
	"CPS_MESSAGE_PRIORITY_KEY" NUMBER(18,0),
	"PATIENT_KEY" NUMBER(18,0),
	"FACILITY_KEY" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"DUE_DATE" DATE,
	"EXPIRATION_DATE" DATE,
	"RESOLVED_FACILITY_KEY" NUMBER(18,0),
	"UPDATED_BY" VARCHAR2(50),
	"ELIGIBILITY_RX_NUMBER" VARCHAR2(20),
	"ELIGIBILITY_REFILL_NUM" NUMBER(18,0),
	 CONSTRAINT "FK_CPS_PROGRAM_03" FOREIGN KEY ("CPS_PROGRAM_KEY")
	  REFERENCES "TREXONE_DW_DATA"."CPS_PROGRAM" ("CPS_PROGRAM_KEY") DISABLE,
	 CONSTRAINT "FK_CPS_STATUS_02" FOREIGN KEY ("CPS_STATUS_KEY")
	  REFERENCES "TREXONE_DW_DATA"."CPS_STATUS" ("CPS_STATUS_KEY") DISABLE,
	 CONSTRAINT "FK_CPS_MESSAGE_TYPE_01" FOREIGN KEY ("CPS_MESSAGE_TYPE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."CPS_MESSAGE_TYPE" ("CPS_MESSAGE_TYPE_KEY") DISABLE,
	 CONSTRAINT "FK_CPS_MESSAGE_PRIORITY_01" FOREIGN KEY ("CPS_MESSAGE_PRIORITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."CPS_MESSAGE_PRIORITY" ("CPS_MESSAGE_PRIORITY_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_47" FOREIGN KEY ("PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_115" FOREIGN KEY ("FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE
   )
  PARTITION BY RANGE ("RECEIVED_DATE") INTERVAL (NUMTOYMINTERVAL(1,'MONTH')) STORE IN ("DW_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_CPS_MESSAGE_FACT" ON "TREXONE_DW_DATA"."CPS_MESSAGE_FACT" ("CPS_MESSAGE_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."CPS_MESSAGE_FACT" ADD CONSTRAINT "PK_CPS_MESSAGE_FACT" PRIMARY KEY ("CPS_MESSAGE_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_CPS_MESSAGE_FACT"  ENABLE;
-- ==========================================
