-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."CSR_STATE"
   (	"CSRS_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"CSR_STATE_NUM" NUMBER(18,0),
	"CTRY_CODE" VARCHAR2(8),
	"STATE_CODE" VARCHAR2(2),
	"CSR_ASAP_VERSION" VARCHAR2(90),
	"CSR_INCLUDE_SHIPPED_TO_STATE" CHAR(1),
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_CSRS_STATE" ON "TREXONE_DW_DATA"."CSR_STATE" ("CSRS_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."CSR_STATE" ADD CONSTRAINT "PK_CSRS_STATE" PRIMARY KEY ("CSRS_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_CSRS_STATE"  ENABLE;
-- ==========================================
