-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."DAW_CODE_TYPE"
   (	"DC_DAW_CODE_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"DC_DAW_CODE" CHAR(1),
	"DC_DAW_CODE_DESC" VARCHAR2(100),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_DAW_CODE_TYPE" ON "TREXONE_DW_DATA"."DAW_CODE_TYPE" ("DC_DAW_CODE_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."DAW_CODE_TYPE" ADD CONSTRAINT "PK_DAW_CODE_TYPE" PRIMARY KEY ("DC_DAW_CODE_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_DAW_CODE_TYPE"  ENABLE;
-- ==========================================
