-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."DECLINE_REASON_TYPE"
   (	"DR_DECLINE_REASON_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"DR_DECLINE_REASON" VARCHAR2(100),
	"ERX_CLIENT_ID" VARCHAR2(100)
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_DECLINE_REASON_TYPE" ON "TREXONE_DW_DATA"."DECLINE_REASON_TYPE" ("DR_DECLINE_REASON_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."DECLINE_REASON_TYPE" ADD CONSTRAINT "PK_DECLINE_REASON_TYPE" PRIMARY KEY ("DR_DECLINE_REASON_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_DECLINE_REASON_TYPE"  ENABLE;
-- ==========================================
