-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."DT_TX"
   (	"DT_TX_NUM" NUMBER(16,0) NOT NULL ENABLE,
	"RX_TYPE" CHAR(1),
	"RX_NUMBER" VARCHAR2(12),
	"DT_WRITTEN_DATE" DATE,
	"DT_FILLED_DATE" DATE,
	"DT_RX_NUMBER" VARCHAR2(12),
	"DT_EXPIRATION_DATE" DATE,
	"PARTIAL_FILL_QTY" NUMBER(13,3),
	"DT_DELETED_IND" CHAR(1),
	"DT_DISPENSED_QTY" NUMBER(13,3),
	"DT_SIG" VARCHAR2(255),
	"DT_REFILLS_REMAINING_IND" CHAR(1),
	"DT_NUM_REFILLS_REMAINING" NUMBER(11,2),
	"DT_USE_SAFETY_CAP" CHAR(1),
	"DT_ADDITIONAL_INFO" VARCHAR2(500),
	"DT_RPH_INITIALS" VARCHAR2(3),
	"DT_RPH_NAME" VARCHAR2(50),
	"RX_RECORD_NUM" NUMBER(18,0),
	"RX_FILL_SEQ" NUMBER(18,0),
	"DT_SYS_USER" NUMBER(18,0),
	"DT_PATIENT_FIRST_NAME" VARCHAR2(30),
	"DT_PATIENT_LAST_NAME" VARCHAR2(30),
	"DT_PATIENT_GENDER_CODE" CHAR(1),
	"DT_PATIENT_ADDRESS" VARCHAR2(100),
	"DT_PATIENT_CITY" VARCHAR2(40),
	"DT_PATIENT_DOB" DATE,
	"DT_PATIENT_NUM" NUMBER(18,0),
	"DT_TP_NAME" VARCHAR2(35),
	"DT_TP_PATIENT_CARDHOLDER_ID" VARCHAR2(30),
	"DT_TP_PATIENT_GROUP_NUM" VARCHAR2(30),
	"DT_TP_PATIENT_PERSON_CODE" VARCHAR2(3),
	"DT_TP_PATIENT_NUM" NUMBER(18,0),
	"DT_PRODUCT" VARCHAR2(35),
	"DT_PRODUCT_MFG" VARCHAR2(30),
	"DT_PRODUCT_NDC_MFG" CHAR(5),
	"DT_PRESCRIBER_FIRST_NAME" VARCHAR2(30),
	"DT_PRESCRIBER_LAST_NAME" VARCHAR2(30),
	"DT_PRESCRIBER_MI" VARCHAR2(30),
	"DT_PRESCRIBER_ADDRESS" VARCHAR2(100),
	"DT_PRESCRIBER_CITY" VARCHAR2(40),
	"DT_PRESCRIBER_ZIPCODE" VARCHAR2(20),
	"DT_PRESCRIBER_PHONE" VARCHAR2(20),
	"DT_PRESCRIBER_DEA_NUM" VARCHAR2(30),
	"DT_PRESCRIBER_LICENSE_NUM" VARCHAR2(30),
	"DT_PRESCRIBER_UPIN_NUM" VARCHAR2(30),
	"DT_PRESCRIBER_NUM" NUMBER(30,0),
	"TP_PATIENT_BANK_ID" VARCHAR2(6),
	"DT_UPLOAD_DATESTAMP" DATE,
	"DATESTAMP" DATE,
	"FD_FACILITY_KEY" NUMBER(18,0),
	"DATE_KEY" NUMBER(18,0),
	"SYS_USER_KEY" NUMBER(18,0),
	"PRS_PRESCRIBER_KEY" NUMBER(18,0),
	"TPD_KEY" NUMBER(18,0),
	"PRD_PRODUCT_KEY" NUMBER(18,0),
	"TPLD_PLAN_KEY" NUMBER(18,0),
	"PD_PATIENT_H_KEY" NUMBER(18,0),
	"DRUG_KEY" NUMBER(18,0),
	"DT_DISTRIBUTOR" VARCHAR2(30),
	"DT_TP_RANK" NUMBER(9,0),
	"DT_PATIENT_ZIPCODE" VARCHAR2(20),
	"PRESCRIBED_QTY" NUMBER(13,3),
	"WRITTEN_PRD_PRODUCT_KEY" NUMBER(18,0),
	"DAW_CODE" CHAR(1),
	"REFILLS_AUTHORIZED" NUMBER(9,0),
	"TP_TYPE" CHAR(1),
	"DT_RX_STATUS" NUMBER(1,0),
	"DT_PRESCRIBER_DEA_SUFFIX" VARCHAR2(20),
	"PRINTED_DATE" DATE,
	"REFILL_NUM" NUMBER(18,0),
	"HL7_PATIENT_ID" VARCHAR2(30),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PD_PATIENT_KEY" NUMBER(18,0),
	 CONSTRAINT "FK_DATE_DIM_57" FOREIGN KEY ("DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DRUG_04" FOREIGN KEY ("DRUG_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DRUG" ("DRUG_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_60" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_H_31" FOREIGN KEY ("PD_PATIENT_H_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT_H" ("PD_PATIENT_H_KEY") DISABLE,
	 CONSTRAINT "FK_PRESCRIBER_11" FOREIGN KEY ("PRS_PRESCRIBER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRESCRIBER" ("PRS_PRESCRIBER_KEY") DISABLE,
	 CONSTRAINT "FK_PRODUCT_22" FOREIGN KEY ("PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE,
	 CONSTRAINT "FK_PRODUCT_33" FOREIGN KEY ("WRITTEN_PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE,
	 CONSTRAINT "FK_SYS_USER_64" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE,
	 CONSTRAINT "FK_TP_PATIENT_03" FOREIGN KEY ("TPD_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TP_PATIENT" ("TPD_KEY") DISABLE,
	 CONSTRAINT "FK_TP_PLAN_04" FOREIGN KEY ("TPLD_PLAN_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TP_PLAN" ("TPLD_PLAN_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_31" FOREIGN KEY ("PD_PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") DISABLE
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PKDT_TX" ON "TREXONE_DW_DATA"."DT_TX" ("DT_TX_NUM")
  ;
ALTER TABLE "TREXONE_DW_DATA"."DT_TX" ADD CONSTRAINT "PKDT_TX" PRIMARY KEY ("DT_TX_NUM")
  USING INDEX "TREXONE_DW_DATA"."PKDT_TX"  ENABLE;
-- ==========================================
