-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."DUR_INDICATOR"
   (	"DUR_INDICATOR_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"IS_CRITICAL" CHAR(1),
	"IS_EXCEPTION" CHAR(1),
	"IS_SUPPRESSED" CHAR(1),
	"IS_FILTERED" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100)
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_DUR_INDICATOR" ON "TREXONE_DW_DATA"."DUR_INDICATOR" ("DUR_INDICATOR_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."DUR_INDICATOR" ADD CONSTRAINT "PK_DUR_INDICATOR" PRIMARY KEY ("DUR_INDICATOR_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_DUR_INDICATOR"  ENABLE;
-- ==========================================
