-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."EPCS_AUDIT"
   (	"EPCS_AUDIT_KEY" NUMBER(18,0),
	"EPCS_TYPE_KEY" NUMBER(18,0),
	"EPCS_PRIORITY_KEY" NUMBER(18,0),
	"EPCS_MESSAGE" VARCHAR2(4000),
	"PPI_MESSAGE_ID_VALUE" VARCHAR2(35),
	"PPI_MESSAGE_SENDER_VALUE" VARCHAR2(80),
	"PPI_MESSAGE_SENDER_QUAL" VARCHAR2(3),
	"FACILITY_KEY" NUMBER(18,0),
	"EVENT_DATE_KEY" NUMBER(18,0),
	"EVENT_TIME_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"SYS_USER_KEY" NUMBER(18,0),
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"EPCS_OUTCOME_KEY" NUMBER(18,0),
	"EPCS_CATEGORY_KEY" NUMBER(18,0),
	"EPCS_SUB_CATEGORY_KEY" NUMBER(18,0),
	"EPCS_PRES_FIRST_NAME" VARCHAR2(35),
	"EPCS_PRES_LAST_NAME" VARCHAR2(35),
	"EPCS_PRES_DEA_NUMBER" VARCHAR2(35),
	"SUBJECT_LOGIN_NAME" VARCHAR2(255),
	"EXECUTING_LOGIN_NAME" VARCHAR2(255),
	"RX_NUMBER" VARCHAR2(30),
	"EVENT_DATESTAMP" DATE,
	 CONSTRAINT "PK_EPCS_AUDIT" PRIMARY KEY ("EPCS_AUDIT_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_EPCS_TYPE_01" FOREIGN KEY ("EPCS_TYPE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."EPCS_TYPE" ("EPCS_TYPE_KEY") DISABLE,
	 CONSTRAINT "FK_EPCS_PRIORITY_01" FOREIGN KEY ("EPCS_PRIORITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."EPCS_PRIORITY" ("EPCS_PRIORITY_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_110" FOREIGN KEY ("FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_150" FOREIGN KEY ("EVENT_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_63" FOREIGN KEY ("EVENT_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_SYS_USER_93" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE,
	 CONSTRAINT "FK_EPCS_OUTCOME_01" FOREIGN KEY ("EPCS_OUTCOME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."EPCS_OUTCOME" ("EPCS_OUTCOME_KEY") DISABLE,
	 CONSTRAINT "FK_EPCS_CATEGORY_02" FOREIGN KEY ("EPCS_CATEGORY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."EPCS_CATEGORY" ("EPCS_CATEGORY_KEY") DISABLE,
	 CONSTRAINT "FK_EPCS_SUB_CATEGORY_01" FOREIGN KEY ("EPCS_SUB_CATEGORY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."EPCS_SUB_CATEGORY" ("EPCS_SUB_CATEGORY_KEY") DISABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("DW_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
