-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."EPCS_OUTCOME"
   (	"EPCS_OUTCOME_KEY" NUMBER(18,0),
	"EPCS_OUTCOME_CODE" CHAR(1),
	"EPCS_OUTCOME_DESC" VARCHAR2(400),
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "PK_EPCS_OUTCOME" PRIMARY KEY ("EPCS_OUTCOME_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "UC_EPCS_OUTCOME_01" UNIQUE ("EPCS_OUTCOME_CODE")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
