-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."EPCS_CATEGORY"
   (	"EPCS_CATEGORY_KEY" NUMBER(18,0),
	"EPCS_CATEGORY_CODE" VARCHAR2(255),
	"EPCS_CATEGORY_DESC" VARCHAR2(400),
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "PK_EPCS_CATEGORY" PRIMARY KEY ("EPCS_CATEGORY_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "UC_EPCS_CATEGORY_01" UNIQUE ("EPCS_CATEGORY_CODE")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
