-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."FACILITY_PERFORMANCE_SUMMARY"
   (	"FD_FACILITY_KEY" NUMBER NOT NULL ENABLE,
	"DATE_KEY" NUMBER NOT NULL ENABLE,
	"TOTAL_ITEMS" NUMBER,
	"TOTAL_COMPLETED_FILLS" NUMBER,
	"TOTAL_PARTIAL_FILLS" NUMBER,
	"TOTAL_WAIT_FILLS" NUMBER,
	"TOTAL_READY_AS_PROMISED" NUMBER,
	"TOTAL_WAIT_MINUTES" NUMBER,
	"TOTAL_NON_WAIT_FILLS" NUMBER,
	"TOTAL_NON_WAIT_READY_FILLS" NUMBER,
	"TOTAL_GENERIC_OPPORTUNITY" NUMBER,
	"TOTAL_GENERIC_SUBS" NUMBER,
	"TOTAL_TP_PAID" NUMBER,
	"TOTAL_PATIENT_PAID" NUMBER,
	"TOTAL_TP_FILLS" NUMBER,
	"TOTAL_NON_TP_FILLS" NUMBER,
	"TOTAL_IVR_FILLS" NUMBER,
	"TOTAL_PPI_FILLS" NUMBER,
	"TOTAL_WEB_FILLS" NUMBER,
	"TOTAL_FAX_FILLS" NUMBER,
	"TOTAL_CHAIN_TRANFERS_IN" NUMBER,
	"TOTAL_CHAIN_TRANFERS_OUT" NUMBER,
	"TOTAL_EXTERNAL_TRANSFERS_IN" NUMBER,
	"TOTAL_EXTERNAL_TRANFERS_OUT" NUMBER,
	"TOTAL_DOWNTIME_FILLS" NUMBER,
	"TOTAL_OUT_OF_STOCK_FILLS" NUMBER,
	"PARTITION_DATE" DATE,
	"TOTAL_CANCELLED_FILLS" NUMBER,
	"TOTAL_GENERIC_WRTN_AND_DISP" NUMBER,
	"TOTAL_SAME_DAY_CANCELLED_FILLS" NUMBER,
	"TOTAL_NET_FILLS" NUMBER,
	"TOTAL_CF_FILLS" NUMBER,
	"TOTAL_CF_FILLS_SUBMITTED" NUMBER,
	"TOTAL_CF_FILLS_PULLED_BACK" NUMBER,
	"TOTAL_CF_FILLS_RECEIVED" NUMBER,
	"TOTAL_CF_FILLS_DECLINED" NUMBER,
	"TOTAL_CF_FILLS_CANCELLED_BACK" NUMBER,
	"TOTAL_CF_FILLS_CHECKED_OUT" NUMBER,
	"TOTAL_CF_FILLS_CHECKED_IN" NUMBER,
	"TOTAL_PRICE_GEN_SUB" NUMBER,
	"TOTAL_COST_GEN_SUB" NUMBER,
	"TOTAL_PRICE_WRT_DSP_GEN" NUMBER,
	"TOTAL_COST_WRT_DSP_GEN" NUMBER,
	"TOTAL_TP_TAX" NUMBER,
	"TOTAL_PATIENT_TAX" NUMBER,
	"TOTAL_USER_DEFINED_STEP_AMT" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "FK_DATE_DIM_74" FOREIGN KEY ("DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_71" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_FACILITY_PERFORMANCE_SUM" ON "TREXONE_DW_DATA"."FACILITY_PERFORMANCE_SUMMARY" ("FD_FACILITY_KEY", "DATE_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."FACILITY_PERFORMANCE_SUMMARY" ADD CONSTRAINT "PK_FACILITY_PERFORMANCE_SUM" PRIMARY KEY ("FD_FACILITY_KEY", "DATE_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_FACILITY_PERFORMANCE_SUM"  ENABLE;
-- ==========================================
