-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."FACILITY_LINK"
   (	"FD_FACILITY_KEY" NUMBER(18,0),
	"LINKED_FD_FACILITY_KEY" NUMBER(18,0),
	"FACILITY_LINK_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"FACILITY_LINK_TYPE" CHAR(1),
	"IS_ACTIVE" CHAR(1),
	"PRIORITY" NUMBER(3,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	 CONSTRAINT "FK_FACILITY_81" FOREIGN KEY ("LINKED_FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_82" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE
   ) ;
-- ==========================================
