-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."FACILITY_INVENTORY_ACCUM"
   (	"FACILITY_NUM" NUMBER(18,0),
	"SALES_YR" VARCHAR2(4),
	"SALES_MON" VARCHAR2(2),
	"PRODUCT_NUM" NUMBER(18,0),
	"GCN_SEQ_NUM" VARCHAR2(30),
	"IS_GENERIC" VARCHAR2(1),
	"TOTAL_NON_340B_QTY_SOLD" NUMBER(17,3),
	"TOTAL_CF_QTY_SOLD" NUMBER(17,3),
	"TOTAL_340B_QTY_SOLD" NUMBER(17,3),
	"TOTAL_NUM_RXS_SOLD" NUMBER(9,0),
	"HIGHEST_DAILY_QTY_SOLD" NUMBER(17,3),
	"HIGHEST_RX_QTY" NUMBER(13,3),
	"HIGHEST_QTY_RX_NUMBER" VARCHAR2(20),
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"TOTAL_CM_QTY_SOLD" NUMBER
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("DW_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2001-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
