-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."FACILITY_SCHEDULE"
   (	"FACILITY_SCHEDULE_KEY" NUMBER(18,0),
	"FACILITY_KEY" NUMBER(18,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"SCHEDULE_NUM" NUMBER(18,0),
	"SCHEDULE_H_LEVEL" NUMBER,
	"SCHEDULE_DATE" DATE,
	"DAY_OF_WEEK" NUMBER(1,0),
	"OPEN_SCHEDULE_TIME_KEY" NUMBER(2,0),
	"CLOSE_SCHEDULE_TIME_KEY" NUMBER(2,0),
	"DESCRIPTION" VARCHAR2(255),
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "PK_FACILITY_SCHEDULE" PRIMARY KEY ("FACILITY_SCHEDULE_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_FACILITY_111" FOREIGN KEY ("FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_SCHEDULE_TIME_01" FOREIGN KEY ("OPEN_SCHEDULE_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SCHEDULE_TIME" ("SCHEDULE_TIME_KEY") DISABLE,
	 CONSTRAINT "FK_SCHEDULE_TIME_02" FOREIGN KEY ("CLOSE_SCHEDULE_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SCHEDULE_TIME" ("SCHEDULE_TIME_KEY") DISABLE
   ) ;
-- ==========================================
