-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."FACILITY_ID"
   (	"FD_FACILITY_ID_NUM" NUMBER(18,0),
	"FD_FACILITY_NUM" NUMBER(18,0),
	"FD_TP_PLAN_NUM" NUMBER(18,0),
	"FD_TP_BENEFIT_GROUP_ID" VARCHAR2(10),
	"FD_TYPE" VARCHAR2(3),
	"FD_VALUE" VARCHAR2(80),
	"FD_ARCHIVE_LEVEL" NUMBER(9,0),
	"FD_SYS_USER" NUMBER(9,0),
	"FD_DATESTAMP" DATE,
	"FD_NUM_UPDATES" NUMBER(9,0),
	"FD_CTRY_CODE" VARCHAR2(8),
	"FD_STATE_CODE" VARCHAR2(2),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
-- ==========================================
