-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."FILL_CATEGORY_TYPE"
   (	"FILL_CATEGORY_KEY" NUMBER(2,0) NOT NULL ENABLE,
	"FILL_CATEGORY_NAME" VARCHAR2(20),
	"ERX_CLIENT_ID" VARCHAR2(100)
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_FILL_CATEGORY_TYPE" ON "TREXONE_DW_DATA"."FILL_CATEGORY_TYPE" ("FILL_CATEGORY_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."FILL_CATEGORY_TYPE" ADD CONSTRAINT "PK_FILL_CATEGORY_TYPE" PRIMARY KEY ("FILL_CATEGORY_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_FILL_CATEGORY_TYPE"  ENABLE;
-- ==========================================
