-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."FILL_INDICATOR"
   (	"FILL_INDICATOR_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"ALLOW_SUBSTITUTION" VARCHAR2(7),
	"PARTIAL_FILL_INDICATOR" VARCHAR2(7),
	"IS_THERAPEUTIC_SUBSTITUTION" VARCHAR2(7),
	"FILL_SUB_INDICATOR" VARCHAR2(7),
	"IS_REFILL" VARCHAR2(7),
	"IS_REFILL_ALLOWED" VARCHAR2(7),
	"CASH_TP_INDICATOR" VARCHAR2(7),
	"IS_LETTER_ON_FILE" VARCHAR2(7),
	"IS_OUT_OF_STOCK" VARCHAR2(7),
	"AUTO_RETRY_RELEASED" VARCHAR2(7) DEFAULT 'U',
	"COUNSELING_PERFORMED" CHAR(1),
	"AUTO_REFILL" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100)
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_FILL_INDICATOR" ON "TREXONE_DW_DATA"."FILL_INDICATOR" ("FILL_INDICATOR_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."FILL_INDICATOR" ADD CONSTRAINT "PK_FILL_INDICATOR" PRIMARY KEY ("FILL_INDICATOR_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_FILL_INDICATOR"  ENABLE;
-- ==========================================
