-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."GENERIC_SUB_TYPE"
   (	"GS_GENERIC_SUB_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"GS_GENERIC_SUB_CODE" CHAR(1),
	"GS_GENERIC_SUB_DESC" VARCHAR2(80),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_GENERIC_SUB_TYPE" ON "TREXONE_DW_DATA"."GENERIC_SUB_TYPE" ("GS_GENERIC_SUB_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."GENERIC_SUB_TYPE" ADD CONSTRAINT "PK_GENERIC_SUB_TYPE" PRIMARY KEY ("GS_GENERIC_SUB_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_GENERIC_SUB_TYPE"  ENABLE;
-- ==========================================
