-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."GROUPS"
   (	"GRP_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"GRP_GROUP_NUM" NUMBER(18,0),
	"GRP_NAME" VARCHAR2(30),
	"GRP_DESCRIPTION" VARCHAR2(300),
	"GRP_TYPE" CHAR(1),
	"GRP_IS_ACTIVE" CHAR(1),
	"GRP_IS_EXTERNALLY_MAINTAINED" CHAR(1),
	"GRP_CREATE_DATE" DATE,
	"GRP_LAST_UPD_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_GROUPS" ON "TREXONE_DW_DATA"."GROUPS" ("GRP_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."GROUPS" ADD CONSTRAINT "PK_GROUPS" PRIMARY KEY ("GRP_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_GROUPS"  ENABLE;
-- ==========================================
