-- ==========================================

  CREATE GLOBAL TEMPORARY TABLE "TREXONE_DW_DATA"."GTT_SHIPMENT"
   (	"SHIPPING_METHOD_NUM" NUMBER(18,0),
	"DELIVERY_METHOD_NUM" NUMBER(18,0),
	"SHIP_DATE" DATE,
	"ORIGINAL_EXP_MAIL_DELIVERY_DT" DATE,
	"ORIGINAL_SHIP_DATE" DATE,
	"EXPECTED_MAIL_DELIVERY_DATE" DATE,
	"SHIPMENT_NUM" NUMBER(18,0),
	"ORDER_NUM" NUMBER(18,0),
	"NUMBER_OF_PACKAGES" NUMBER(9,0),
	"DEA_CLASS" CHAR(1),
	"REFRIGERATION" CHAR(1),
	"SHIP_HANDLE_FEE" NUMBER(17,6),
	"WEIGHT" NUMBER(16,8),
	"WEIGHT_UNITS" VARCHAR2(10),
	"TRACKING_NUMBER" VARCHAR2(200),
	"COURIER_SHIPPING_CHARGE" NUMBER(17,6),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"IS_SHIPPING_COMPLETE" CHAR(1),
	"SHIPPING_ADDRESS_NUM" NUMBER(18,0),
	"ORIGINAL_SHIPPING_METHOD_NUM" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"IS_SHIP_ADDR_CONFIRMED" CHAR(1),
	"ALTERNATE_RECIPIENT_NUM" NUMBER(18,0),
	"H_LEVEL" NUMBER,
	"PREVIOUS_SHIP_HANDLE_FEE" NUMBER(17,6),
	"SHIP_HANDLE_FEE_EXEMPT_REASON" VARCHAR2(200)
   ) ON COMMIT DELETE ROWS ;
-- ==========================================
