-- ==========================================

  CREATE GLOBAL TEMPORARY TABLE "TREXONE_DW_DATA"."GTT_INVENTORY_ITEM"
   (	"IL_KEY" NUMBER(18,0),
	"INVENTORY_ITEM_NUM" NUMBER(18,0),
	"PRD_PRODUCT_KEY" NUMBER(18,0),
	"DRUG_KEY" NUMBER(18,0),
	"FD_FACILITY_KEY" NUMBER(18,0),
	"DATE_KEY" NUMBER(18,0),
	"BIN_TYPE_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"LAST_ACQ_COST" NUMBER(17,6),
	"LAST_ACQ_COST_DATE" DATE,
	"LAST_ACQ_UNIT_COST" NUMBER(17,6),
	"CURRENT_QTY" NUMBER(17,6),
	"COMMITTED_QTY" NUMBER(17,6),
	"IS_COMMIT_CHG" CHAR(1),
	"EXPECTED_COST" NUMBER(18,8),
	"EXPECTED_UNIT_COST" NUMBER(18,8),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PRIMARY_VENDOR_NUM" NUMBER(18,0),
	"INVENTORY_GROUP_KEY" NUMBER(18,0),
	"H_LEVEL" NUMBER,
	"IS_AUTO_DISPENSED" CHAR(1)
   ) ON COMMIT DELETE ROWS ;
-- ==========================================
