-- ==========================================

  CREATE GLOBAL TEMPORARY TABLE "TREXONE_DW_DATA"."GTT_DUR_CONFLICT_FACT"
   (	"DATE_KEY" NUMBER(18,0),
	"FD_FACILITY_KEY" NUMBER(18,0),
	"PD_PATIENT_H_KEY" NUMBER(18,0),
	"PRS_PRESCRIBER_KEY" NUMBER(18,0),
	"PRD_PRODUCT_KEY" NUMBER(18,0),
	"SYS_USER_KEY" NUMBER(18,0),
	"TPLD_PLAN_KEY" NUMBER(18,0),
	"DUR_CONFLICT_CODE_KEY" NUMBER(18,0),
	"DUR_CONFLICT_TYPE_KEY" NUMBER(18,0),
	"DUR_SEVERITY_TYPE_KEY" NUMBER(18,0),
	"DUR_INDICATOR_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"RX_NUMBER" VARCHAR2(20),
	"FILL_SEQ_NUM" NUMBER(18,0),
	"REFILL_NUM" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PD_PATIENT_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"H_LEVEL" NUMBER,
	"REASON_FOR_SERVICE_CODE" VARCHAR2(2),
	"RESULT_SERVICE_CODE" CHAR(2),
	"PROF_SERVICE_CODE" CHAR(2),
	"LEVEL_OF_EFFORT_NUM" NUMBER(9,0),
	"TP_MESSAGE_NUM" NUMBER(18,0),
	"PARTIAL_FILL_SEQ" NUMBER(2,0),
	"DUR_CONFLICT_NUM" NUMBER(18,0)
   ) ON COMMIT DELETE ROWS ;
-- ==========================================
