-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."IMAGE_OLD"
   (	"IMAGE_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"IMAGE_NUM" NUMBER(18,0),
	"SYS_USER_KEY" NUMBER(18,0),
	"IMAGE_ASSIGN_USER" NUMBER(18,0),
	"IMAGE_TYPE" VARCHAR2(30),
	"IMAGE_IS_ASSIGNED" CHAR(1),
	"IMAGE" BLOB,
	"IMAGE_NAME" VARCHAR2(30),
	"IMAGE_FILE_FORMAT" VARCHAR2(10),
	"IMAGE_BARCODE" VARCHAR2(255),
	"IMAGE_SCAN_DATE" DATE,
	"IMAGE_ASSIGN_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	 CONSTRAINT "TK_SYS_USER_49" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE,
	 CONSTRAINT "TK_SYS_USER_50" FOREIGN KEY ("IMAGE_ASSIGN_USER")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."TK_IMAGE" ON "TREXONE_DW_DATA"."IMAGE_OLD" ("IMAGE_KEY")
  ;
  ALTER INDEX "TREXONE_DW_DATA"."TK_IMAGE"  UNUSABLE;
ALTER TABLE "TREXONE_DW_DATA"."IMAGE_OLD" ADD CONSTRAINT "TK_IMAGE" PRIMARY KEY ("IMAGE_KEY")
  USING INDEX "TREXONE_DW_DATA"."TK_IMAGE"  ENABLE;
-- ==========================================
