-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."IMAGE"
   (	"IMAGE_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"IMAGE_NUM" NUMBER(18,0),
	"SYS_USER_KEY" NUMBER(18,0),
	"IMAGE_ASSIGN_USER" NUMBER(18,0),
	"IMAGE_TYPE" VARCHAR2(30),
	"IMAGE_IS_ASSIGNED" CHAR(1),
	"IMAGE" BLOB,
	"IMAGE_NAME" VARCHAR2(70),
	"IMAGE_FILE_FORMAT" VARCHAR2(10),
	"IMAGE_BARCODE" VARCHAR2(255),
	"IMAGE_SCAN_DATE" DATE,
	"IMAGE_ASSIGN_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"ASSET_GROUP_ID" VARCHAR2(100),
	"SCANNED_DOCUMENT_TYPE_KEY" NUMBER(18,0),
	 CONSTRAINT "FK_SYS_USER_50" FOREIGN KEY ("IMAGE_ASSIGN_USER")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE,
	 CONSTRAINT "FK_SYS_USER_49" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE,
	 CONSTRAINT "FK_SCANNED_DOCUMENT_TYPE_01" FOREIGN KEY ("SCANNED_DOCUMENT_TYPE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SCANNED_DOCUMENT_TYPE" ("SCANNED_DOCUMENT_TYPE_KEY") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2001-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ,
 PARTITION "P_20130104"  VALUES LESS THAN (TO_DATE(' 2013-01-05 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_IMAGE" ON "TREXONE_DW_DATA"."IMAGE" ("IMAGE_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."IMAGE" ADD CONSTRAINT "PK_IMAGE" PRIMARY KEY ("IMAGE_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_IMAGE"  ENABLE;
-- ==========================================
