-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."INV_ADJUSTMENT_FACT"
   (	"FD_FACILITY_KEY" NUMBER(18,0),
	"PRD_PRODUCT_KEY" NUMBER(18,0),
	"DRUG_KEY" NUMBER(18,0),
	"DATE_KEY" NUMBER(18,0),
	"TIME_KEY" NUMBER(5,0),
	"IAR_KEY" NUMBER(18,0),
	"IL_KEY" NUMBER(18,0),
	"SYS_USER_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"ADJUSTMENT_QUANTITY" NUMBER(18,8),
	"ADJUSTMENT_UNIT_COST" NUMBER(17,6),
	"ADJUSTMENT_EXTENDED_COST" NUMBER(17,6),
	"REFERENCE_NUMBER" VARCHAR2(100),
	"ADJUSTMENT_TYPE_CODE" VARCHAR2(3),
	"INVENTORY_ADJUSTMENT_NUM" NUMBER(18,0) DEFAULT 0,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	"INVENTORY_GROUP_KEY" NUMBER(18,0) DEFAULT 0,
	"INVENTORY_ITEM_NUM" NUMBER(18,0),
	 CONSTRAINT "FK_DATE_DIM_71" FOREIGN KEY ("DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DRUG_8" FOREIGN KEY ("DRUG_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DRUG" ("DRUG_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_67" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_INVENTORY_LOCATION_1" FOREIGN KEY ("IL_KEY")
	  REFERENCES "TREXONE_DW_DATA"."INVENTORY_LOCATION" ("IL_KEY") DISABLE,
	 CONSTRAINT "FK_INV_ADJUSTMENT_RSN_TYPE_1" FOREIGN KEY ("IAR_KEY")
	  REFERENCES "TREXONE_DW_DATA"."INV_ADJUSTMENT_REASON_TYPE" ("IAR_KEY") DISABLE,
	 CONSTRAINT "FK_PRODUCT_28" FOREIGN KEY ("PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE,
	 CONSTRAINT "FK_SYS_USER_70" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_7" FOREIGN KEY ("TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_INVENTORY_GROUP_01" FOREIGN KEY ("INVENTORY_GROUP_KEY")
	  REFERENCES "TREXONE_DW_DATA"."INVENTORY_GROUP" ("INVENTORY_GROUP_KEY") DISABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
