-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."INVENTORY_LOT"
   (	"INVENTORY_LOT_KEY" NUMBER(18,0),
	"INVENTORY_LOT_NUM" NUMBER(18,0),
	"LOT_NUMBER" VARCHAR2(20),
	"SERIAL_NUMBER" VARCHAR2(20),
	"PURCHASE_DATE" DATE,
	"EXPIRATION_DATE" DATE,
	"QUANTITY" NUMBER(16,8),
	"COST" NUMBER(17,6),
	"INVENTORY_ITEM_NUM" NUMBER(18,0),
	"SYS_USER_KEY" NUMBER(18,0),
	"DATESTAMP" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	 CONSTRAINT "PK_INVENTORY_LOT" PRIMARY KEY ("INVENTORY_LOT_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SYS_USER_116" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") ENABLE NOVALIDATE
   ) ;
-- ==========================================
