-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."INVENTORY_LOCATION"
   (	"IL_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"FD_FACILITY_KEY" NUMBER(18,0),
	"PRD_PRODUCT_KEY" NUMBER(18,0),
	"IS_ACTIVE" CHAR(1),
	"DISPENSING_NAME" VARCHAR2(30),
	"INVITEM_RECOMMENDED_PO_IND" CHAR(1),
	"INVITEM_STATUS" CHAR(1),
	"GRP_1_SHORT_NAME" VARCHAR2(10),
	"GRP_1_DESCRIPTION" VARCHAR2(60),
	"GRP_1_IS_ACTIVE" CHAR(1),
	"GRP_1_IS_STORAGE_LOC_IND" CHAR(1),
	"GRP_2_SHORT_NAME" VARCHAR2(10),
	"GRP_2_DESCRIPTION" VARCHAR2(60),
	"GRP_2_IS_ACTIVE" CHAR(1),
	"GRP_2_IS_STORAGE_LOC_IND" CHAR(1),
	"GRP_3_SHORT_NAME" VARCHAR2(10),
	"GRP_3_DESCRIPTION" VARCHAR2(60),
	"GRP_3_IS_ACTIVE" CHAR(1),
	"GRP_3_IS_STORAGE_LOC_IND" CHAR(1),
	"GRP_4_SHORT_NAME" VARCHAR2(10),
	"GRP_4_DESCRIPTION" VARCHAR2(60),
	"GRP_4_IS_ACTIVE" CHAR(1),
	"GRP_4_IS_STORAGE_LOC_IND" CHAR(1),
	"GRP_5_SHORT_NAME" VARCHAR2(10),
	"GRP_5_DESCRIPTION" VARCHAR2(60),
	"GRP_5_IS_ACTIVE" CHAR(1),
	"GRP_5_IS_STORAGE_LOC_IND" CHAR(1),
	"GRP_6_SHORT_NAME" VARCHAR2(10),
	"GRP_6_DESCRIPTION" VARCHAR2(60),
	"GRP_6_IS_ACTIVE" CHAR(1),
	"GRP_6_IS_STORAGE_LOC_IND" CHAR(1),
	"GRP_7_SHORT_NAME" VARCHAR2(10),
	"GRP_7_DESCRIPTION" VARCHAR2(60),
	"GRP_7_IS_ACTIVE" CHAR(1),
	"GRP_7_IS_STORAGE_LOC_IND" CHAR(1),
	"LOCATION_GROUP_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	"DRUG_PDID" VARCHAR2(20),
	 CONSTRAINT "FK_FACILITY_68" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_PRODUCT_29" FOREIGN KEY ("PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_INVENTORY_LOCATION" ON "TREXONE_DW_DATA"."INVENTORY_LOCATION" ("IL_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."INVENTORY_LOCATION" ADD CONSTRAINT "PK_INVENTORY_LOCATION" PRIMARY KEY ("IL_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_INVENTORY_LOCATION"  ENABLE;
-- ==========================================
