-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."INVENTORY_GROUP"
   (	"INVENTORY_GROUP_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"INVENTORY_GROUP_NUM" NUMBER(18,0),
	"INVENTORY_ITEM_NUM" NUMBER(18,0),
	"GRP_KEY" NUMBER(18,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID'),
	 CONSTRAINT "PK_INVENTORY_GROUP" PRIMARY KEY ("INVENTORY_GROUP_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_GROUPS_03" FOREIGN KEY ("GRP_KEY")
	  REFERENCES "TREXONE_DW_DATA"."GROUPS" ("GRP_KEY") DISABLE
   ) ;
-- ==========================================
