-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."IVR_ORDER"
   (	"DATE_KEY" NUMBER(18,0),
	"FD_FACILITY_KEY" NUMBER(18,0),
	"SYS_USER_KEY" NUMBER(18,0),
	"UA_KEY" NUMBER(18,0),
	"IVR_ORDER_NUM" NUMBER(18,0),
	"IVR_ELECTRONIC_ORDER_NUM" NUMBER(18,0),
	"IVR_SUBMIT_DATE" DATE,
	"IVR_PICKUP_DATE" DATE,
	"IVR_PICKUP_DATE_SRC" CHAR(1),
	"IVR_IS_SUBMIT_HANGUP" CHAR(1),
	"IVR_LANGUAGE_NUM" NUMBER(18,0),
	"IVR_ORDER_ITEM_NUM" NUMBER(18,0),
	"IVR_RX_NUMBER" VARCHAR2(20),
	"IVR_IS_CALL_DOCTOR" CHAR(1),
	"IVR_IS_BAD_PICKUP_TIME" CHAR(1),
	"PRS_PRESCRIBER_KEY" NUMBER(18,0),
	"PD_PATIENT_H_KEY" NUMBER(18,0),
	"IVR_IS_REFILLABLE" CHAR(1),
	"IVR_REASON_CODE" VARCHAR2(2),
	"IVR_PURPOSE" CHAR(1),
	"IVR_CREATE_DT" DATE,
	"IVR_UPDT_DATE" DATE,
	"IVR_IS_PROCESSED" CHAR(1),
	"IVR_REFILL_NUM" NUMBER(18,0),
	"IVR_RX_RECORD_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PD_PATIENT_KEY" NUMBER(18,0),
	"H_LEVEL" NUMBER,
	 CONSTRAINT "FK_DATE_DIM_43" FOREIGN KEY ("DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_46" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_H_21" FOREIGN KEY ("PD_PATIENT_H_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT_H" ("PD_PATIENT_H_KEY") DISABLE,
	 CONSTRAINT "FK_PRESCRIBER_4" FOREIGN KEY ("PRS_PRESCRIBER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRESCRIBER" ("PRS_PRESCRIBER_KEY") DISABLE,
	 CONSTRAINT "FK_SYS_USER_51" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE,
	 CONSTRAINT "FK_USER_ACTION_TYPE_613" FOREIGN KEY ("UA_KEY")
	  REFERENCES "TREXONE_DW_DATA"."USER_ACTION_TYPE" ("UA_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_21" FOREIGN KEY ("PD_PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") DISABLE
   )
  PARTITION BY RANGE ("IVR_CREATE_DT") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
