-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."LATIN_FREQUENCY_TYPE"
   (	"LF_LATIN_FREQUENCY_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"LF_LATIN_FREQUENCY_CODE" VARCHAR2(10),
	"LF_LATIN_FREQUENCY_DESC" VARCHAR2(60),
	"LF_DAYS_MULTIPLIER" NUMBER(16,8),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_LATIN_FREQUENCY_TYPE" ON "TREXONE_DW_DATA"."LATIN_FREQUENCY_TYPE" ("LF_LATIN_FREQUENCY_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."LATIN_FREQUENCY_TYPE" ADD CONSTRAINT "PK_LATIN_FREQUENCY_TYPE" PRIMARY KEY ("LF_LATIN_FREQUENCY_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_LATIN_FREQUENCY_TYPE"  ENABLE;
-- ==========================================
