-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."LOT_COMMIT"
   (	"LOT_COMMIT_KEY" NUMBER(18,0),
	"LOT_COMMIT_NUM" NUMBER(18,0),
	"ITEM_SEQ" NUMBER(18,0),
	"ORDER_NUM" NUMBER(18,0),
	"LOT_COMMIT_TYPE" CHAR(1),
	"DATESTAMP" DATE,
	"SYS_USER_KEY" NUMBER(18,0),
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"RX_NUMBER" VARCHAR2(20),
	"PATIENT_KEY" NUMBER(18,0),
	"PRODUCT_KEY" NUMBER(18,0),
	"NDC" VARCHAR2(20),
	"RX_FILL_SEQ" NUMBER(18,0),
	 CONSTRAINT "PK_LOT_COMMIT" PRIMARY KEY ("LOT_COMMIT_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SYS_USER_115" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_PATIENT_60" FOREIGN KEY ("PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_PRODUCT_65" FOREIGN KEY ("PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") ENABLE NOVALIDATE
   ) ;
-- ==========================================
