-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."LOT_ADJUSTMENT"
   (	"LOT_ADJUSTMENT_KEY" NUMBER(18,0),
	"LOT_ADJUSTMENT_NUM" NUMBER(18,0),
	"INVENTORY_LOT_KEY" NUMBER(18,0),
	"LOT_COMMIT_KEY" NUMBER(18,0),
	"QUANTITY" NUMBER(16,8),
	"SYS_USER_KEY" NUMBER(18,0),
	"DATESTAMP" DATE,
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"IAR_KEY" NUMBER(18,0),
	 CONSTRAINT "PK_LOT_ADJUSTMENT" PRIMARY KEY ("LOT_ADJUSTMENT_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SYS_USER_117" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_INVENTORY_LOT_02" FOREIGN KEY ("INVENTORY_LOT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."INVENTORY_LOT" ("INVENTORY_LOT_KEY") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_LOT_COMMIT_02" FOREIGN KEY ("LOT_COMMIT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."LOT_COMMIT" ("LOT_COMMIT_KEY") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_INV_ADJUSTMENT_RSN_TYPE_2" FOREIGN KEY ("IAR_KEY")
	  REFERENCES "TREXONE_DW_DATA"."INV_ADJUSTMENT_REASON_TYPE" ("IAR_KEY") ENABLE NOVALIDATE
   ) ;
-- ==========================================
