-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."LTC_PRESCRIBER_ORDER_FACT"
   (	"LTC_PRESCRIBER_ORDER_FACT_KEY" NUMBER(18,0),
	"PRS_PRESCRIBER_KEY" NUMBER(18,0),
	"FD_FACILITY_KEY" NUMBER(18,0),
	"LTC_FACILITY_KEY" NUMBER(18,0),
	"LTC_FACILITY_NODE_KEY" NUMBER(18,0),
	"LTC_PRESCRIBER_ORDER_TYPE_KEY" NUMBER(18,0),
	"LTC_PRESCRIBER_ORDER_TEXT_KEY" NUMBER(18,0),
	"PD_PATIENT_KEY" NUMBER(18,0),
	"LTC_PATIENT_KEY" NUMBER(18,0),
	"LTC_HOA_KEY" NUMBER(18,0),
	"EFFECTIVE_DATE_KEY" NUMBER(18,0),
	"TERMINATION_DATE_KEY" NUMBER(18,0),
	"LTC_PRESCRIBER_ORDER_NUM" NUMBER(18,0),
	"LTC_RX_PRESCRIBER_ORDER_NUM" NUMBER(18,0),
	"IS_STANDING_ORDER" CHAR(1),
	"RX_RECORD_NUM" NUMBER(18,0),
	"RX_FILL_SEQ" NUMBER(18,0),
	"REFILL_NO" NUMBER(18,0),
	"PRINT_ORDER" NUMBER(9,0),
	"IS_ON_HOLD" CHAR(1),
	"IS_ACTIVE" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PARTITION_DATE" DATE,
	"RX_NUMBER" VARCHAR2(20),
	 CONSTRAINT "PK_LTC_PRESCRIBER_ORD_FACT_KEY" PRIMARY KEY ("LTC_PRESCRIBER_ORDER_FACT_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_LTC_FACILITY_02" FOREIGN KEY ("LTC_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."LTC_FACILITY" ("LTC_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_LTC_PRESCRIBER_ORDER_FACT_3" FOREIGN KEY ("PD_PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") DISABLE,
	 CONSTRAINT "FK_LTC_PATIENT_01" FOREIGN KEY ("LTC_PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."LTC_PATIENT" ("LTC_PATIENT_KEY") DISABLE,
	 CONSTRAINT "FK_LTC_PRESCRIBER_ORDER_TYPE_1" FOREIGN KEY ("LTC_PRESCRIBER_ORDER_TYPE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."LTC_PRESCRIBER_ORDER_TYPE" ("LTC_PRESCRIBER_ORDER_TYPE_KEY") DISABLE,
	 CONSTRAINT "FK_PRESCRIBER_ORDER_TEXT_01" FOREIGN KEY ("LTC_PRESCRIBER_ORDER_TEXT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."LTC_PRESCRIBER_ORDER_TEXT" ("LTC_PRESCRIBER_ORDER_TEXT_KEY") DISABLE,
	 CONSTRAINT "FK_LTC_HOA_01" FOREIGN KEY ("LTC_HOA_KEY")
	  REFERENCES "TREXONE_DW_DATA"."LTC_HOA" ("LTC_HOA_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_114" FOREIGN KEY ("EFFECTIVE_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_115" FOREIGN KEY ("TERMINATION_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_106" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_LTC_FACILITY_NODE_07" FOREIGN KEY ("LTC_FACILITY_NODE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."LTC_FACILITY_NODE" ("LTC_FACILITY_NODE_KEY") DISABLE,
	 CONSTRAINT "FK_PRESCRIBER_18" FOREIGN KEY ("PRS_PRESCRIBER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRESCRIBER" ("PRS_PRESCRIBER_KEY") DISABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
