-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."LTC_PACKAGING_METHOD_TYPE"
   (	"LTC_PACKAGING_METHOD_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"LTC_PACKAGING_METHOD_NAME" VARCHAR2(100),
	"LTC_PACKAGING_METHOD_NUM" NUMBER(18,0),
	"LTC_FACILITY_NODE_NUM" NUMBER(18,0),
	"LTC_FACILITY_NODE_KEY" NUMBER(18,0),
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CONTEXT'),
	 CONSTRAINT "PK_LTC_PACKAGING_METHOD_TYPE" PRIMARY KEY ("LTC_PACKAGING_METHOD_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_LTC_FACILITY_NODE_06" FOREIGN KEY ("LTC_FACILITY_NODE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."LTC_FACILITY_NODE" ("LTC_FACILITY_NODE_KEY") DISABLE
   ) ;
-- ==========================================
