-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."LTC_FACILITY_NODE_LINK"
   (	"LTC_FACILITY_NODE_LINK_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"LTC_FACILITY_NODE_LINK_NUM" NUMBER(18,0),
	"CHILD" NUMBER(18,0),
	"PARENT" NUMBER(18,0),
	"DISTANCE_TO_PARENT" NUMBER(18,0),
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CONTEXT'),
	 CONSTRAINT "PK_LTC_FACILITY_NODE_LINK" PRIMARY KEY ("LTC_FACILITY_NODE_LINK_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_LTC_FACILITY_NODE_01" FOREIGN KEY ("CHILD")
	  REFERENCES "TREXONE_DW_DATA"."LTC_FACILITY_NODE" ("LTC_FACILITY_NODE_KEY") DISABLE,
	 CONSTRAINT "FK_LTC_FACILITY_NODE_02" FOREIGN KEY ("PARENT")
	  REFERENCES "TREXONE_DW_DATA"."LTC_FACILITY_NODE" ("LTC_FACILITY_NODE_KEY") DISABLE
   ) ;
-- ==========================================
