-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."LTC_HOA"
   (	"LTC_HOA_KEY" NUMBER(18,0),
	"LTC_HOA_NUM" NUMBER(18,0),
	"LTC_HOA_NAME" VARCHAR2(64),
	"LTC_ADMIN_TYPE" VARCHAR2(20),
	"OVERRIDE_LTC_HOA_NUM" NUMBER(18,0),
	"HOA_SEQUENCE" NUMBER(2,0),
	"LTC_HOA_OVERIDE_NUM" NUMBER(18,0),
	"LTC_FACILITY_NODE_KEY" NUMBER(18,0),
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "PK_LTC_HOA" PRIMARY KEY ("LTC_HOA_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_LTC_FACILITY_NODE_03" FOREIGN KEY ("LTC_FACILITY_NODE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."LTC_FACILITY_NODE" ("LTC_FACILITY_NODE_KEY") DISABLE
   ) ;
-- ==========================================
