-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."LTC_FACILITY"
   (	"LTC_FACILITY_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"LTC_FACILITY_NUM" NUMBER(18,0),
	"NAME" VARCHAR2(32),
	"FD_FACILITY_KEY" NUMBER(18,0),
	"LTC_FACILITY_NODE_NUM" NUMBER(18,0),
	"TYPE" VARCHAR2(10),
	"NUMBER_OF_BEDS" NUMBER(9,0),
	"TERMINATION_DATE_KEY" NUMBER(18,0),
	"EFFECTIVE_DATE_KEY" NUMBER(18,0),
	"REACTIVATION_DATE_KEY" NUMBER(18,0),
	"ADDRESS1" VARCHAR2(100),
	"ADDRESS2" VARCHAR2(100),
	"CITY" VARCHAR2(60),
	"ZIPCODE" VARCHAR2(20),
	"STATE_CODE" VARCHAR2(2),
	"ZIP_EXT" VARCHAR2(6),
	"PHONE1" VARCHAR2(20),
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CONTEXT'),
	"FACILITY_ID" VARCHAR2(10),
	 CONSTRAINT "PK_LTC_FACILITY" PRIMARY KEY ("LTC_FACILITY_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_FACILITY_100" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_111" FOREIGN KEY ("TERMINATION_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_112" FOREIGN KEY ("EFFECTIVE_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_102" FOREIGN KEY ("REACTIVATION_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE
   ) ;
-- ==========================================
