-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."LTC_ORDER_EXCLUDE"
   (	"LTC_ORDER_EXCLUDE_KEY" NUMBER(18,0),
	"LTC_ORDER_EXCLUDE_NUM" NUMBER(18,0),
	"LTC_PATIENT_KEY" NUMBER(18,0),
	"LTC_PRESCRIBER_ORDER_FACT_KEY" NUMBER(18,0),
	"EXCLUDED_DATE" DATE,
	"INCLUDE_OVERRIDE" CHAR(1),
	"NOTE_TEXT" VARCHAR2(255),
	"SYS_USER_KEY" NUMBER(18,0),
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "PK_LTC_ORDER_EXCLUDE" PRIMARY KEY ("LTC_ORDER_EXCLUDE_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_LTC_PATIENT_05" FOREIGN KEY ("LTC_PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."LTC_PATIENT" ("LTC_PATIENT_KEY") DISABLE,
	 CONSTRAINT "FK_LTC_ORDER_EXCLUDE_01" FOREIGN KEY ("LTC_PRESCRIBER_ORDER_FACT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."LTC_PRESCRIBER_ORDER_FACT" ("LTC_PRESCRIBER_ORDER_FACT_KEY") DISABLE,
	 CONSTRAINT "FK_SYS_USER_85" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE
   ) ;
-- ==========================================
