-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."MESSAGE_CATEGORY_TYPE"
   (	"MC_MESSAGE_CATEGORY_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"MC_MESSAGE_CATEGORY_CODE" CHAR(1),
	"MC_MESSAGE_CATEGORY_DESC" VARCHAR2(30),
	"ERX_CLIENT_ID" VARCHAR2(100)
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_MESSAGE_CATEGORY_TYPE" ON "TREXONE_DW_DATA"."MESSAGE_CATEGORY_TYPE" ("MC_MESSAGE_CATEGORY_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."MESSAGE_CATEGORY_TYPE" ADD CONSTRAINT "PK_MESSAGE_CATEGORY_TYPE" PRIMARY KEY ("MC_MESSAGE_CATEGORY_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_MESSAGE_CATEGORY_TYPE"  ENABLE;
-- ==========================================
