-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."ORDER_SOURCE_TYPE"
   (	"OS_ORDER_SOURCE_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"OS_ORDER_SOURCE_CODE" NUMBER(18,0),
	"OS_ORDER_SOURCE_DESC" VARCHAR2(45),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_ORDER_SOURCE_TYPE" ON "TREXONE_DW_DATA"."ORDER_SOURCE_TYPE" ("OS_ORDER_SOURCE_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."ORDER_SOURCE_TYPE" ADD CONSTRAINT "PK_ORDER_SOURCE_TYPE" PRIMARY KEY ("OS_ORDER_SOURCE_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_ORDER_SOURCE_TYPE"  ENABLE;
-- ==========================================
