-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PATIENT_PHONE"
   (	"PATP_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PAD_KEY" NUMBER(18,0),
	"PATP_PHONE_NUM" NUMBER(18,0),
	"PATP_PHONE_USAGE" VARCHAR2(8),
	"PATP_AREA_CODE" VARCHAR2(4),
	"PATP_PHONE_NUMBER" VARCHAR2(20),
	"PATP_EXT" VARCHAR2(6),
	"PATP_USAGE" VARCHAR2(50),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"PD_PATIENT_KEY" NUMBER(18,0),
	"H_LEVEL" NUMBER,
	 CONSTRAINT "FK_PATIENT_ADDRESS_01" FOREIGN KEY ("PAD_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT_ADDRESS" ("PAD_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_28" FOREIGN KEY ("PD_PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") DISABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_PATIENT_PHONE" ON "TREXONE_DW_DATA"."PATIENT_PHONE" ("PATP_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."PATIENT_PHONE" ADD CONSTRAINT "PK_PATIENT_PHONE" PRIMARY KEY ("PATP_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_PATIENT_PHONE"  ENABLE;
-- ==========================================
