-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PATIENT_IMAGE"
   (	"PD_PATIENT_KEY" NUMBER(18,0),
	"IMAGE_TYPE" VARCHAR2(30),
	"IMAGE_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"H_TYPE" VARCHAR2(2),
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "FK_PATIENT_51" FOREIGN KEY ("PD_PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") ENABLE,
	 CONSTRAINT "FK_IMAGE_10" FOREIGN KEY ("IMAGE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."IMAGE" ("IMAGE_KEY") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTOYMINTERVAL(1,'MONTH')) STORE IN ("DW_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
