-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PATIENT_ID"
   (	"PATIENT_ID_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PATIENT_ID_NUM" NUMBER(18,0),
	"PATIENT_ID" VARCHAR2(36),
	"PARTNER_CODE" VARCHAR2(10),
	"PARTNER_NAME" VARCHAR2(40),
	"PID_CREATE_DT" DATE,
	"PD_PATIENT_KEY" NUMBER(18,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	"IS_DEFAULT" CHAR(1),
	 CONSTRAINT "PK_PATIENT_ID" PRIMARY KEY ("PATIENT_ID_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_PATIENT_38" FOREIGN KEY ("PD_PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") DISABLE
   )
  PARTITION BY RANGE ("EFF_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
