-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PATIENT_TO_SPECIALTY_PROG"
   (	"PATIENT_TO_SPECIALTY_PROG_KEY" NUMBER(18,0),
	"PATIENT_TO_SPECIALTY_PROG_NUM" NUMBER(18,0),
	"SPECIALTY_PROGRAM_KEY" NUMBER(18,0),
	"PATIENT_KEY" NUMBER(18,0),
	"FACILITY_KEY" NUMBER(18,0),
	"ELIGIBILITY_START_DATE" DATE,
	"ELIGIBILITY_END_DATE" DATE,
	"DEACTIVATED_DATE" DATE,
	"DEACTIVATION_REASON" VARCHAR2(35),
	"SYS_USER_KEY" NUMBER(18,0),
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "PK_PATIENT_TO_SPECIALTY_PROG" PRIMARY KEY ("PATIENT_TO_SPECIALTY_PROG_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SYS_USER_114" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_PATIENT_52" FOREIGN KEY ("PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_FACILITY_118" FOREIGN KEY ("FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_SPECIALTY_PROGRAM_03" FOREIGN KEY ("SPECIALTY_PROGRAM_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SPECIALTY_PROGRAM" ("SPECIALTY_PROGRAM_KEY") ENABLE NOVALIDATE
   ) ;
-- ==========================================
