-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PATIENT_DEMOGRAPHIC"
   (	"PATIENT_DEMOGRAPHIC_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"GENDER" CHAR(1),
	"AGE_BAND" VARCHAR2(15),
	"HEIGHT_BAND" VARCHAR2(15),
	"WEIGHT_BAND" VARCHAR2(30),
	"BODY_SURFACE_BAND" VARCHAR2(15),
	"LOCATION_CODE" CHAR(2),
	"ERX_CLIENT_ID" VARCHAR2(100)
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_PATIENT_DEMOGRAPHIC" ON "TREXONE_DW_DATA"."PATIENT_DEMOGRAPHIC" ("PATIENT_DEMOGRAPHIC_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."PATIENT_DEMOGRAPHIC" ADD CONSTRAINT "PK_PATIENT_DEMOGRAPHIC" PRIMARY KEY ("PATIENT_DEMOGRAPHIC_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_PATIENT_DEMOGRAPHIC"  ENABLE;
-- ==========================================
