-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PATIENT_PROFILE"
   (	"PATIENT_PROFILE_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"IS_TAX_EXEMPT" VARCHAR2(7),
	"IS_CONFIDENTIAL" VARCHAR2(7),
	"REFILL_REMINDER" VARCHAR2(7),
	"USE_GEN_IF_AVAIL" VARCHAR2(7),
	"DECLINED_STORE_ID_PROGRAM" VARCHAR2(7),
	"SAFETY_PACKAGE" VARCHAR2(7),
	"ERX_CLIENT_ID" VARCHAR2(100)
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_PATIENT_PROFILE" ON "TREXONE_DW_DATA"."PATIENT_PROFILE" ("PATIENT_PROFILE_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."PATIENT_PROFILE" ADD CONSTRAINT "PK_PATIENT_PROFILE" PRIMARY KEY ("PATIENT_PROFILE_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_PATIENT_PROFILE"  ENABLE;
-- ==========================================
