-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PATIENT_OPTION"
   (	"PATIENT_OPTION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"AUTO_NOTIFY_OPTION" VARCHAR2(7),
	"AUTO_REFILL_OPTION" VARCHAR2(7),
	"CENTRAL_FILL_OPTION" VARCHAR2(7),
	"MAIL_ORDER_OPTION" VARCHAR2(7),
	"CARE_PROGRAM_OPTION" VARCHAR2(7),
	"THERAPEUTIC_SUB_OPTION" VARCHAR2(7),
	"TARGETED_MARKETING_OPTION" VARCHAR2(7),
	"ERX_CLIENT_ID" VARCHAR2(100)
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_PATIENT_OPTION" ON "TREXONE_DW_DATA"."PATIENT_OPTION" ("PATIENT_OPTION_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."PATIENT_OPTION" ADD CONSTRAINT "PK_PATIENT_OPTION" PRIMARY KEY ("PATIENT_OPTION_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_PATIENT_OPTION"  ENABLE;
-- ==========================================
