-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PATIENT_NOTE"
   (	"PN_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PD_PATIENT_H_KEY" NUMBER(18,0),
	"PN_PATIENT_NUM" NUMBER(18,0),
	"PN_PATIENT_NOTE_SEQ" NUMBER(18,0),
	"PN_PATIENT_NOTE_TYPE_CODE" CHAR(1),
	"PN_SYS_USER" NUMBER(18,0),
	"PN_CREATE_USER" NUMBER(18,0),
	"PN_NOTE_TEXT" VARCHAR2(4000),
	"PN_CREATE_DT" DATE,
	"PN_PRIORITY" NUMBER(9,0),
	"PN_PRIORITY_INDICATOR" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PD_PATIENT_KEY" NUMBER(18,0),
	"H_LEVEL" NUMBER,
	 CONSTRAINT "FK_PATIENT_H_30" FOREIGN KEY ("PD_PATIENT_H_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT_H" ("PD_PATIENT_H_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_30" FOREIGN KEY ("PD_PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") DISABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_PATIENT_NOTE" ON "TREXONE_DW_DATA"."PATIENT_NOTE" ("PN_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."PATIENT_NOTE" ADD CONSTRAINT "PK_PATIENT_NOTE" PRIMARY KEY ("PN_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_PATIENT_NOTE"  ENABLE;
-- ==========================================
