-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PATIENT_MEDICAL_BRDG"
   (	"PD_PATIENT_KEY" NUMBER(18,0),
	"MCD_KEY" NUMBER(18,0),
	"PMB_BEGIN_EFFECTIVE_DT" DATE,
	"PMB_END_EFFECTIVE_DT" DATE,
	"PMB_REPORTED_DATE" DATE,
	"PMB_DURATION_IN_DAYS" NUMBER(18,0),
	"PMB_STATUS" CHAR(1),
	"SYS_USER_KEY" NUMBER(18,0),
	"FD_FACILITY_KEY" NUMBER(18,0),
	"PMB_MED_CONDITON_SEQ" NUMBER(18,0),
	"PMB_SEVERITY" VARCHAR2(50),
	"PMB_DEACTIVATE_USER" NUMBER(18,0),
	"PMB_UPDATE_DT" DATE,
	"PMB_CREATE_DT" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	 CONSTRAINT "FK_FACILITY_40" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_MEDICAL_CONDITION_4" FOREIGN KEY ("MCD_KEY")
	  REFERENCES "TREXONE_DW_DATA"."MEDICAL_CONDITION" ("MCD_KEY") DISABLE,
	 CONSTRAINT "FK_SYS_USER_1" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_10" FOREIGN KEY ("PD_PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") DISABLE
   ) ;
-- ==========================================
