-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PATIENT_STATUS_DETAIL"
   (	"PD_PATIENT_H_KEY" NUMBER(18,0),
	"PSD_PATIENT_NUM" NUMBER(18,0),
	"PSD_PATIENT_STATUS_SEQ" NUMBER(18,0),
	"PSD_SYS_USER" NUMBER(18,0),
	"PSD_NEW_STATUS" CHAR(1),
	"PSD_EFFECTIVE_DATE" DATE,
	"PSD_TERM_DATE" DATE,
	"PSD_COMMENTARY" VARCHAR2(255),
	"PSD_CREATE_DT" DATE,
	"PSD_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PSD_UPDATE_DT" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PD_PATIENT_KEY" NUMBER(18,0),
	"H_LEVEL" NUMBER,
	 CONSTRAINT "FK_PATIENT_H_29" FOREIGN KEY ("PD_PATIENT_H_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT_H" ("PD_PATIENT_H_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_29" FOREIGN KEY ("PD_PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") DISABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PKPATIENT_STATUS_DETAIL" ON "TREXONE_DW_DATA"."PATIENT_STATUS_DETAIL" ("PSD_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."PATIENT_STATUS_DETAIL" ADD CONSTRAINT "PKPATIENT_STATUS_DETAIL" PRIMARY KEY ("PSD_KEY")
  USING INDEX "TREXONE_DW_DATA"."PKPATIENT_STATUS_DETAIL"  ENABLE;
-- ==========================================
