-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PAYMENT_TYPE"
   (	"PAYMENT_TYPE_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PAYMENT_TYPE_NAME" VARCHAR2(50),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID'),
	"PAYMENT_TYPE_NUM" NUMBER(18,0),
	 CONSTRAINT "PK_PAYMENT_TYPE" PRIMARY KEY ("PAYMENT_TYPE_KEY")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
