-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PO_ACK_SHIPPING_STATUS_TYPE"
   (	"PO_ACK_SHIPPING_STATUS_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PO_ACK_SHIPPING_STATUS" CHAR(2),
	"PO_ACK_SHIPPING_DESC" VARCHAR2(30),
	"ERX_CLIENT_ID" VARCHAR2(100)
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_PO_ACK_SHIPPING_STATUS_TYPE" ON "TREXONE_DW_DATA"."PO_ACK_SHIPPING_STATUS_TYPE" ("PO_ACK_SHIPPING_STATUS_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."PO_ACK_SHIPPING_STATUS_TYPE" ADD CONSTRAINT "PK_PO_ACK_SHIPPING_STATUS_TYPE" PRIMARY KEY ("PO_ACK_SHIPPING_STATUS_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_PO_ACK_SHIPPING_STATUS_TYPE"  ENABLE;
-- ==========================================
