-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PRD_COST_BASIS_OVRD"
   (	"PRODUCT_COST_BASIS_KEY" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PROD_COST_BASIS_OVRD_NUM" NUMBER(18,0),
	"PRD_PRODUCT_KEY" NUMBER(18,0),
	"DRUG_KEY" NUMBER(18,0),
	"COST_BASIS_KEY" NUMBER(18,0),
	"COST_BASIS_SOURCE_KEY" NUMBER(18,0),
	"EFFECTIVE_DATE" DATE,
	"TERMINATION_DATE" DATE,
	"PERCENT_MODIFIER" NUMBER(17,6),
	"ADJUST_MODIFIER" NUMBER(17,6),
	"TEMP_OVERRIDE" CHAR(1),
	"IS_MANUALLY_MAINTAINED" CHAR(1),
	"ANOTHER_PRD_COST_BASIS_NUM" NUMBER(18,0),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"PRD_COST_BASIS_OVRD_KEY" NUMBER(18,0)
   ) ;
  CREATE INDEX "TREXONE_DW_DATA"."PK_PRD_COST_BASIS_OVRD" ON "TREXONE_DW_DATA"."PRD_COST_BASIS_OVRD" ("PRD_COST_BASIS_OVRD_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."PRD_COST_BASIS_OVRD" ADD CONSTRAINT "PK_PRD_COST_BASIS_OVRD" PRIMARY KEY ("PRD_COST_BASIS_OVRD_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_PRD_COST_BASIS_OVRD"  ENABLE;
-- ==========================================
