-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PRESCRIBER_PHONE"
   (	"PRSP_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PRSP_STATUS" CHAR(1),
	"PRSP_PHONE_TYPE" VARCHAR2(4),
	"PRSP_AREA_CODE" VARCHAR2(4),
	"PRSP_PHONE_NUMBER" VARCHAR2(20),
	"PRSP_EXT" VARCHAR2(6),
	"PRSP_PHONE_ADDRESS_TYPE" VARCHAR2(4),
	"PRSP_SOURCE_CODE" CHAR(1),
	"PRS_PRESCRIBER_KEY" NUMBER(18,0),
	"PADR_KEY" NUMBER(18,0),
	"PRSP_PHONE_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	 CONSTRAINT "FK_PRESCRIBER_12" FOREIGN KEY ("PRS_PRESCRIBER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRESCRIBER" ("PRS_PRESCRIBER_KEY") DISABLE,
	 CONSTRAINT "FK_PRESCRIBER_ADDRESS_7" FOREIGN KEY ("PADR_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRESCRIBER_ADDRESS" ("PADR_KEY") DISABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_PRESCRIBER_PHONE" ON "TREXONE_DW_DATA"."PRESCRIBER_PHONE" ("PRSP_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."PRESCRIBER_PHONE" ADD CONSTRAINT "PK_PRESCRIBER_PHONE" PRIMARY KEY ("PRSP_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_PRESCRIBER_PHONE"  ENABLE;
-- ==========================================
