-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PRESCRIBER_ID_TYPE"
   (	"PIT_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PIT_CODE" VARCHAR2(25),
	"PIT_ID_DESCRIPTION" VARCHAR2(255),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_PRESCRIBER_ID_TYPE" ON "TREXONE_DW_DATA"."PRESCRIBER_ID_TYPE" ("PIT_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."PRESCRIBER_ID_TYPE" ADD CONSTRAINT "PK_PRESCRIBER_ID_TYPE" PRIMARY KEY ("PIT_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_PRESCRIBER_ID_TYPE"  ENABLE;
-- ==========================================
