-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PRESCRIBER_IDS"
   (	"PID_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PADR_KEY" NUMBER(18,0),
	"PRS_PRESCRIBER_KEY" NUMBER(18,0),
	"PID_PRESCIBER_ID" VARCHAR2(50),
	"PID_ES_DT" DATE,
	"PID_EE_DT" DATE,
	"PID_PRESCRIBER_ID_NUM" NUMBER(18,0),
	"PID_CREATE_DATE" DATE,
	"PID_ID_TEXT" VARCHAR2(30),
	"PID_ID_SUFFIX" VARCHAR2(20),
	"PID_CTRY_CODE" VARCHAR2(8),
	"PID_STATE_CODE" VARCHAR2(4),
	"PID_STATUS" VARCHAR2(1),
	"PID_SOURCE_CODE" CHAR(1),
	"PIT_KEY" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	"USE_FOR_BILLING" CHAR(1),
	 CONSTRAINT "FK_PRESCRIBER_1" FOREIGN KEY ("PRS_PRESCRIBER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRESCRIBER" ("PRS_PRESCRIBER_KEY") DISABLE,
	 CONSTRAINT "FK_PRESCRIBER_ADDRESS_6" FOREIGN KEY ("PADR_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRESCRIBER_ADDRESS" ("PADR_KEY") DISABLE,
	 CONSTRAINT "FK_PRESCRIBER_ID_TYPE_01" FOREIGN KEY ("PIT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRESCRIBER_ID_TYPE" ("PIT_KEY") DISABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_PRESCRIBER_IDS" ON "TREXONE_DW_DATA"."PRESCRIBER_IDS" ("PID_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."PRESCRIBER_IDS" ADD CONSTRAINT "PK_PRESCRIBER_IDS" PRIMARY KEY ("PID_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_PRESCRIBER_IDS"  ENABLE;
-- ==========================================
