-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PRICING_LIST"
   (	"PRICING_LIST_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PRICING_LIST_NUM" NUMBER(18,0),
	"NAME" VARCHAR2(30),
	"PUBLISH_STATUS" CHAR(1),
	"EFFECTIVE_DATE" DATE,
	"TERM_DATE" DATE,
	"DATA_FILTER" CLOB,
	"PRICING_FORMULA_NAME" VARCHAR2(30),
	"PROCESS_ORDER" NUMBER(9,0),
	"INCL_EXCL_IND" CHAR(1),
	"DEFAULT_FORMULA_NAME" VARCHAR2(30),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"PRICING_FORMULA_KEY" NUMBER(18,0),
	"DEFAULT_PRICING_FORMULA_KEY" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "FK_PRICING_FORMULA_02" FOREIGN KEY ("PRICING_FORMULA_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRICING_FORMULA" ("PRICING_FORMULA_KEY") DISABLE,
	 CONSTRAINT "FK_PRICING_FORMULA_03" FOREIGN KEY ("DEFAULT_PRICING_FORMULA_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRICING_FORMULA" ("PRICING_FORMULA_KEY") DISABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_PRICING_LIST" ON "TREXONE_DW_DATA"."PRICING_LIST" ("PRICING_LIST_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."PRICING_LIST" ADD CONSTRAINT "PK_PRICING_LIST" PRIMARY KEY ("PRICING_LIST_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_PRICING_LIST"  ENABLE;
-- ==========================================
