-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PRICING_FORMULA"
   (	"PRICING_FORMULA_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PRICING_FORMULA_CONFIG_NUM" NUMBER(18,0),
	"NAME" VARCHAR2(30),
	"CASH_TP_IND" CHAR(1),
	"PRICING_FORMULA_STEP_NUM" NUMBER(9,0),
	"PRICING_FORMULA_STEP_NAME" VARCHAR2(15),
	"PRICING_HIERARCHY_KEY" NUMBER(18,0),
	"USE_PRICE_LINKING" CHAR(1),
	"USE_ALT_COST_DETERMINATION" CHAR(1),
	"COMPOUND_PRICING_OPTION" CHAR(1),
	"PUBLISH_USER_LOGIN_NAME" VARCHAR2(255),
	"PUBLISH_STATUS" CHAR(1),
	"PUBLISH_DATE" DATE,
	"EFFECTIVE_DATE" DATE,
	"TERM_DATE" DATE,
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "FK_PRICING_HIERARCHY_2" FOREIGN KEY ("PRICING_HIERARCHY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRICING_HIERARCHY" ("PRICING_HIERARCHY_KEY") DISABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_PRICING_FORMULA" ON "TREXONE_DW_DATA"."PRICING_FORMULA" ("PRICING_FORMULA_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."PRICING_FORMULA" ADD CONSTRAINT "PK_PRICING_FORMULA" PRIMARY KEY ("PRICING_FORMULA_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_PRICING_FORMULA"  ENABLE;
-- ==========================================
