-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PRICE_QUOTE"
   (	"DATE_KEY" NUMBER(18,0),
	"SYS_USER_KEY" NUMBER(18,0),
	"PQ_PRICE_QUOTE_NUM" NUMBER(18,0),
	"PRD_PRODUCT_KEY" NUMBER(18,0),
	"PD_PATIENT_H_KEY" NUMBER(18,0),
	"PQ_FACILITY_NUM" VARCHAR2(10),
	"FD_FACILITY_KEY" NUMBER(18,0),
	"TPLD_PLAN_KEY" NUMBER(18,0),
	"PQ_WRITTEN_DATE" DATE,
	"PQ_EXPIRE_DATE" DATE,
	"PQ_QUANTITY" NUMBER(16,8),
	"PQ_QOH_AT_QUOTE" NUMBER(16,8),
	"PQ_INGREDIENT_COST" NUMBER(17,6),
	"PQ_FEE" NUMBER(17,6),
	"PQ_TAX" NUMBER(17,6),
	"PQ_DISCOUNT" NUMBER(17,6),
	"PQ_OVERRIDE" NUMBER(17,6),
	"PQ_DATESTAMP" DATE,
	"TIME_KEY" NUMBER(5,0),
	"PQ_TP_BENEFIT_GROUP_SEQ" NUMBER(18,0),
	"PQ_TP_NETWORK_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PD_PATIENT_KEY" NUMBER(18,0),
	"H_LEVEL" NUMBER,
	 CONSTRAINT "FK_DATE_DIM_47" FOREIGN KEY ("DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_50" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_H_34" FOREIGN KEY ("PD_PATIENT_H_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT_H" ("PD_PATIENT_H_KEY") DISABLE,
	 CONSTRAINT "FK_PRODUCT_30" FOREIGN KEY ("PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE,
	 CONSTRAINT "FK_SYS_USER_55" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_15" FOREIGN KEY ("TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_TP_PLAN_3" FOREIGN KEY ("TPLD_PLAN_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TP_PLAN" ("TPLD_PLAN_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_34" FOREIGN KEY ("PD_PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") DISABLE
   )
  PARTITION BY RANGE ("PQ_DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
