-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PRICING_TABLE_FORMULA_ROLE"
   (	"PRICING_FORMULA_KEY" NUMBER(18,0),
	"PRICING_TABLE_KEY" NUMBER(18,0),
	"ROLE_TYPE_NAME" VARCHAR2(30),
	"PROCESS_ORDER" NUMBER,
	"SELECTION_RULE" NUMBER,
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "FK_PRICING_FORMULA_1" FOREIGN KEY ("PRICING_FORMULA_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRICING_FORMULA" ("PRICING_FORMULA_KEY") DISABLE,
	 CONSTRAINT "FK_PRICING_TABLE_1" FOREIGN KEY ("PRICING_TABLE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRICING_TABLE" ("PRICING_TABLE_KEY") DISABLE
   ) ;
-- ==========================================
