-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PRICING_HIERARCHY"
   (	"PRICING_HIERARCHY_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"DATA_GROUP_NUM" NUMBER(18,0),
	"DATA_GROUP_NAME" VARCHAR2(30),
	"LEVEL_NUM" NUMBER(5,0),
	"DATA_GROUP_NUM_LEVEL_1" NUMBER(18,0),
	"DATA_GROUP_NAME_LEVEL_1" VARCHAR2(30),
	"DATA_GROUP_NUM_LEVEL_2" NUMBER(18,0),
	"DATA_GROUP_NAME_LEVEL_2" VARCHAR2(30),
	"DATA_GROUP_NUM_LEVEL_3" NUMBER(18,0),
	"DATA_GROUP_NAME_LEVEL_3" VARCHAR2(30),
	"DATA_GROUP_NUM_LEVEL_4" NUMBER(18,0),
	"DATA_GROUP_NAME_LEVEL_4" VARCHAR2(30),
	"DATA_GROUP_NUM_LEVEL_5" NUMBER(18,0),
	"DATA_GROUP_NAME_LEVEL_5" VARCHAR2(30),
	"DATA_GROUP_NUM_LEVEL_6" NUMBER(18,0),
	"DATA_GROUP_NAME_LEVEL_6" VARCHAR2(30),
	"DATA_GROUP_NUM_LEVEL_7" NUMBER(18,0),
	"DATA_GROUP_NAME_LEVEL_7" VARCHAR2(30),
	"DATA_GROUP_NUM_LEVEL_8" NUMBER(18,0),
	"DATA_GROUP_NAME_LEVEL_8" VARCHAR2(30),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_PRICING_HIERARCHY" ON "TREXONE_DW_DATA"."PRICING_HIERARCHY" ("PRICING_HIERARCHY_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."PRICING_HIERARCHY" ADD CONSTRAINT "PK_PRICING_HIERARCHY" PRIMARY KEY ("PRICING_HIERARCHY_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_PRICING_HIERARCHY"  ENABLE;
-- ==========================================
