-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PRODUCT_COST_BASIS"
   (	"PRODUCT_COST_BASIS_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PRODUCT_COST_BASIS_NUM" NUMBER(18,0),
	"PRD_PRODUCT_KEY" NUMBER(18,0),
	"DRUG_KEY" NUMBER(18,0),
	"COST_BASIS_KEY" NUMBER(18,0),
	"COST_BASIS_SOURCE_KEY" NUMBER(18,0),
	"EFFECTIVE_DATE" DATE,
	"TERMINATION_DATE" DATE,
	"PERCENT_MODIFIER" NUMBER(17,6),
	"ADJUST_MODIFIER" NUMBER(17,6),
	"TEMP_OVERRIDE" CHAR(1),
	"IS_MANUALLY_MAINTAINED" CHAR(1),
	"ANOTHER_PRD_COST_BASIS_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	 CONSTRAINT "PK_PRODUCT_COST_BASIS" PRIMARY KEY ("PRODUCT_COST_BASIS_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_PRODUCT_51" FOREIGN KEY ("PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE,
	 CONSTRAINT "FK_DRUG_21" FOREIGN KEY ("DRUG_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DRUG" ("DRUG_KEY") DISABLE,
	 CONSTRAINT "FK_COST_BASIS_SOURCE_01" FOREIGN KEY ("COST_BASIS_SOURCE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."COST_BASIS_SOURCE" ("COST_BASIS_SOURCE_KEY") DISABLE,
	 CONSTRAINT "FK_COST_BASIS_01" FOREIGN KEY ("COST_BASIS_KEY")
	  REFERENCES "TREXONE_DW_DATA"."COST_BASIS" ("COST_BASIS_KEY") DISABLE
   ) ;
  CREATE INDEX "TREXONE_DW_DATA"."UC_PRODUCT_COST_BASIS_01" ON "TREXONE_DW_DATA"."PRODUCT_COST_BASIS" ("PRD_PRODUCT_KEY", "COST_BASIS_KEY", "EFFECTIVE_DATE", "ERX_CLIENT_ID", "PRODUCT_COST_BASIS_NUM")
  ;
ALTER TABLE "TREXONE_DW_DATA"."PRODUCT_COST_BASIS" ADD CONSTRAINT "UC_PRODUCT_COST_BASIS_01" UNIQUE ("PRD_PRODUCT_KEY", "COST_BASIS_KEY", "EFFECTIVE_DATE", "ERX_CLIENT_ID", "PRODUCT_COST_BASIS_NUM")
  USING INDEX "TREXONE_DW_DATA"."UC_PRODUCT_COST_BASIS_01"  ENABLE NOVALIDATE;
-- ==========================================
