-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PRODUCT_STATE_OVERRIDE"
   (	"PRDST_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PRDST_PRODUCT_ST_OVERRIDE_NUM" NUMBER(18,0),
	"PRDST_PRODUCT_NUM" NUMBER(18,0),
	"PRDST_CTRY_CODE" VARCHAR2(8),
	"PRDST_STATE_CODE" VARCHAR2(2),
	"PRDST_DRUG_SCHEDULE" VARCHAR2(30),
	"PRDST_IS_REPORTABLE" CHAR(1),
	"PRDST_IS_SCHEDULED_RX_ID_REQ" CHAR(1),
	"PRDST_IS_TAX_EXEMPT" CHAR(1),
	"PRDST_IS_MANDATED" CHAR(1),
	"PRDST_PRICE_BOARD_QUANTITY" NUMBER(16,8),
	"PRDST_PRICE_BOARD_QUANTITY2" NUMBER(16,8),
	"PRDST_PRICE_BOARD_QUANTITY3" NUMBER(16,8),
	"PRDST_PRICE_BOARD_QUANTITY4" NUMBER(16,8),
	"PRDST_PRICE_BOARD_QUANTITY5" NUMBER(16,8),
	"PRDST_CREATE_DATE" DATE,
	"PRD_PRODUCT_KEY" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	 CONSTRAINT "FK_PROD_STATE_OVERRIDE_1" FOREIGN KEY ("PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_PRODUCT_STATE_OVERRIDE" ON "TREXONE_DW_DATA"."PRODUCT_STATE_OVERRIDE" ("PRDST_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."PRODUCT_STATE_OVERRIDE" ADD CONSTRAINT "PK_PRODUCT_STATE_OVERRIDE" PRIMARY KEY ("PRDST_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_PRODUCT_STATE_OVERRIDE"  ENABLE;
-- ==========================================
