-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PRODUCT_CHARACTERISTICS"
   (	"PRDC_CHAR_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PRD_PRODUCT_KEY" NUMBER(18,0),
	"PRDC_PRD_CHARACTERISTICS_NUM" NUMBER(18,0),
	"PRDC_PRODUCT_NUM" NUMBER(18,0),
	"PRDC_IMAGE_SOURCE_CODE" VARCHAR2(20),
	"PRDC_IS_DEFAULT" CHAR(1),
	"PRDC_ORIGINAL_EFFECTIVE_DATE" DATE,
	"PRDC_ORIGINAL_EXPIRATION_DATE" DATE,
	"PRDC_EFFECTIVE_DATE" DATE,
	"PRDC_EXPIRATION_DATE" DATE,
	"PRDC_FLAVOR_CODE" VARCHAR2(30),
	"PRDC_COLOR_CODE" VARCHAR2(25),
	"PRDC_SHAPE_CODE" VARCHAR2(30),
	"PRDC_IMPRINT1" VARCHAR2(45),
	"PRDC_IMPRINT2" VARCHAR2(45),
	"PRDC_MARKS_CODE" VARCHAR2(25),
	"PRDC_IMAGE_NUM" NUMBER(18,0),
	"PRDC_ORIGINAL_MANUFACTURER" VARCHAR2(30),
	"PRDC_MANUFACTURER" VARCHAR2(30),
	"PRDC_REPACKAGER_CODE" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PRDC_CLARITY_CODE" VARCHAR2(30),
	"PRDC_COATING_CODE" VARCHAR2(30),
	"H_LEVEL" NUMBER,
	 CONSTRAINT "FK_PRODUCT_31" FOREIGN KEY ("PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_PRODUCT_CHARACTERISTICS" ON "TREXONE_DW_DATA"."PRODUCT_CHARACTERISTICS" ("PRDC_CHAR_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."PRODUCT_CHARACTERISTICS" ADD CONSTRAINT "PK_PRODUCT_CHARACTERISTICS" PRIMARY KEY ("PRDC_CHAR_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_PRODUCT_CHARACTERISTICS"  ENABLE;
-- ==========================================
