-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PRODUCT_FACILITY"
   (	"PRODUCT_FACILITY_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PRD_PRODUCT_KEY" NUMBER(18,0),
	"FD_FACILITY_KEY" NUMBER(18,0),
	"IS_AUTO_DISPENSED" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	"DRUG_KEY" NUMBER(18,0),
	"LAST_ACQUISITION_UNIT_COST" NUMBER(17,6),
	"LAST_ACQUISITION_COST" NUMBER(17,6),
	"EXPECTED_ACQ_UNIT_COST" NUMBER(17,6),
	"EXPECTED_ACQ_COST" NUMBER(17,6),
	"BIN_TYPE_KEY" NUMBER(18,0),
	"COMMITTED_QTY" NUMBER(17,6),
	"CURRENT_QTY" NUMBER(17,6),
	"LAST_CHANGED_DATE_KEY" NUMBER(18,0),
	"IL_KEY" NUMBER(18,0),
	"INVENTORY_ITEM_NUM" NUMBER(18,0),
	"LAST_ACQUISITION_COST_DATE" DATE,
	"PRIMARY_VENDOR_NUM" NUMBER(18,0),
	 CONSTRAINT "PK_PRODUCT_FACILITY" PRIMARY KEY ("PRODUCT_FACILITY_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_PRODUCT_50" FOREIGN KEY ("PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_97" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_DRUG_25" FOREIGN KEY ("DRUG_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DRUG" ("DRUG_KEY") DISABLE
   ) ;
-- ==========================================
