-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PRODUCT_SALES_SUMMARY"
   (	"FD_FACILITY_KEY" NUMBER,
	"DATE_KEY" NUMBER,
	"PRD_PRODUCT_KEY" NUMBER,
	"TOTAL_COMPLETED_FILLS" NUMBER,
	"TOTAL_QTY_DISPENSED" NUMBER,
	"TOTAL_TP_PAID" NUMBER,
	"TOTAL_PATIENT_PAID" NUMBER,
	"TOTAL_OUT_OF_STOCK_FILLS" NUMBER,
	"PARTITION_DATE" DATE,
	"TOTAL_CANCELLED_FILLS" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "FK_DATE_DIM_75" FOREIGN KEY ("DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_72" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_PRODUCT_32" FOREIGN KEY ("PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_PRODUCT_SALES_SUMMARY" ON "TREXONE_DW_DATA"."PRODUCT_SALES_SUMMARY" ("FD_FACILITY_KEY", "DATE_KEY", "PRD_PRODUCT_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."PRODUCT_SALES_SUMMARY" ADD CONSTRAINT "PK_PRODUCT_SALES_SUMMARY" PRIMARY KEY ("FD_FACILITY_KEY", "DATE_KEY", "PRD_PRODUCT_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_PRODUCT_SALES_SUMMARY"  ENABLE;
-- ==========================================
