-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PROGRAM_STATUS_CODE"
   (	"PROGRAM_STATUS_CODE_KEY" NUMBER(18,0),
	"STATUS_CODE" VARCHAR2(25),
	"STATUS_DESC" VARCHAR2(255),
	"CODE_NUM" NUMBER(18,0),
	"H_LEVEL" NUMBER(20,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"STATUS_TYPE" CHAR(1),
	 CONSTRAINT "PK_PROGRAM_STATUS_CODE" PRIMARY KEY ("PROGRAM_STATUS_CODE_KEY")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
