-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PURCHASE_ORDER_ITEM_FACT"
   (	"FD_FACILITY_KEY" NUMBER(18,0),
	"VENDOR_KEY" NUMBER(18,0),
	"DRUG_KEY" NUMBER(18,0),
	"PRD_PRODUCT_KEY" NUMBER(18,0),
	"PO_ITEM_CREATED_DATE_KEY" NUMBER(18,0),
	"PO_ITEM_CREATED_TIME_KEY" NUMBER(5,0),
	"PO_ITEM_RECEIVED_DATE_KEY" NUMBER(18,0),
	"PO_ITEM_RECEIVED_TIME_KEY" NUMBER(5,0),
	"PO_ITEM_REMOVED_DATE_KEY" NUMBER(18,0),
	"PO_ITEM_REMOVED_TIME_KEY" NUMBER(5,0),
	"PO_CREATED_DATE_KEY" NUMBER(18,0),
	"PO_CREATED_TIME_KEY" NUMBER(5,0),
	"PO_CREATED_USER_KEY" NUMBER(18,0),
	"PO_LAST_UPD_SYS_USER_KEY" NUMBER(18,0),
	"PO_RECEIVED_DATE_KEY" NUMBER(18,0),
	"PO_RECEIVED_TIME_KEY" NUMBER(5,0),
	"PO_EXPRIATION_DATE_KEY" NUMBER(18,0),
	"PO_EXPIRATION_TIME_KEY" NUMBER(5,0),
	"PO_REMOVED_DATE_KEY" NUMBER(18,0),
	"PO_REMOVED_TIME_KEY" NUMBER(5,0),
	"VENDOR_PRICE_CATALOG_KEY" NUMBER(18,0),
	"SUBSTITUTED_PRICE_CATALOG_KEY" NUMBER(18,0),
	"PO_ACK_SHIPPING_STATUS_KEY" NUMBER(18,0),
	"PO_STATUS_TYPE_KEY" NUMBER(18,0),
	"ACK_SHIPPING_STATUS_TYPE_KEY" NUMBER(18,0),
	"PURCHASE_ORDER_NUM" NUMBER(18,0),
	"PURCHASE_ORDER_ITEM_NUM" NUMBER(18,0),
	"PO_NUMBER" VARCHAR2(10),
	"PO_TYPE_CODE" CHAR(1),
	"IS_SCHEDULE_2_ORDER" CHAR(1),
	"PO_LAST_UPD_DATE" DATE,
	"LINE_NUMBER" NUMBER(9,0),
	"VENDOR_ITEM_RANK" NUMBER(9,0),
	"ORDERED_QTY" NUMBER(9,0),
	"RECEIVED_QTY" NUMBER(9,0),
	"EXPECTED_ACQ_COST" NUMBER(17,6),
	"ACTUAL_ACQ_COST" NUMBER(17,6),
	"RCVNG_EXCPTN_STATUS_CODE" CHAR(1),
	"MODIFIED_AFTER_ORDERED" CHAR(1),
	"PO_ACK_DATE" DATE,
	"PO_ACK_TYPE_CODE" CHAR(2),
	"ACK_QUANTITY" NUMBER(9,0),
	"ACK_ACQUISITION_COST" NUMBER(17,6),
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	"H_TYPE" VARCHAR2(1),
	"DSCSA_QUANTITY" NUMBER(9,0),
	"ADDITIONAL_PO_NUMBERS" VARCHAR2(255),
	 CONSTRAINT "FK_ACK_SHIPPING_STATUS_TYPE_01" FOREIGN KEY ("ACK_SHIPPING_STATUS_TYPE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."ACK_SHIPPING_STATUS_TYPE" ("ACK_SHIPPING_STATUS_TYPE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_01" FOREIGN KEY ("PO_ITEM_CREATED_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_02" FOREIGN KEY ("PO_ITEM_RECEIVED_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_03" FOREIGN KEY ("PO_ITEM_REMOVED_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_04" FOREIGN KEY ("PO_CREATED_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_05" FOREIGN KEY ("PO_RECEIVED_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_06" FOREIGN KEY ("PO_EXPRIATION_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_07" FOREIGN KEY ("PO_REMOVED_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DRUG_18" FOREIGN KEY ("DRUG_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DRUG" ("DRUG_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_87" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_PO_ACK_SHIPPING_STATUS_T_01" FOREIGN KEY ("PO_ACK_SHIPPING_STATUS_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PO_ACK_SHIPPING_STATUS_TYPE" ("PO_ACK_SHIPPING_STATUS_KEY") DISABLE,
	 CONSTRAINT "FK_PO_STATUS_TYPE_01" FOREIGN KEY ("PO_STATUS_TYPE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PO_STATUS_TYPE" ("PO_STATUS_TYPE_KEY") DISABLE,
	 CONSTRAINT "FK_PRODUCT_44" FOREIGN KEY ("PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE,
	 CONSTRAINT "FK_SYS_USER_02" FOREIGN KEY ("PO_CREATED_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE,
	 CONSTRAINT "FK_SYS_USER_03" FOREIGN KEY ("PO_LAST_UPD_SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_31" FOREIGN KEY ("PO_ITEM_CREATED_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_32" FOREIGN KEY ("PO_ITEM_RECEIVED_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_33" FOREIGN KEY ("PO_ITEM_REMOVED_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_34" FOREIGN KEY ("PO_CREATED_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_35" FOREIGN KEY ("PO_RECEIVED_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_36" FOREIGN KEY ("PO_EXPIRATION_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_37" FOREIGN KEY ("PO_REMOVED_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_VENDOR_02" FOREIGN KEY ("VENDOR_KEY")
	  REFERENCES "TREXONE_DW_DATA"."VENDOR" ("VENDOR_KEY") DISABLE,
	 CONSTRAINT "FK_VENDOR_PRICE_CATALOG_01" FOREIGN KEY ("VENDOR_PRICE_CATALOG_KEY")
	  REFERENCES "TREXONE_DW_DATA"."VENDOR_PRICE_CATALOG" ("VENDOR_PRICE_CATALOG_KEY") DISABLE,
	 CONSTRAINT "FK_VENDOR_PRICE_CATALOG_02" FOREIGN KEY ("SUBSTITUTED_PRICE_CATALOG_KEY")
	  REFERENCES "TREXONE_DW_DATA"."VENDOR_PRICE_CATALOG" ("VENDOR_PRICE_CATALOG_KEY") DISABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
