-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PURCHASING_PLAN_ITEM"
   (	"DRUG_KEY" NUMBER(18,0),
	"PRD_PRODUCT_KEY" NUMBER(18,0),
	"FD_FACILITY_KEY" NUMBER(18,0),
	"PURCHASING_PLAN_ITEM_NUM" NUMBER(18,0),
	"PURCHASING_PLAN_NUM" NUMBER(18,0),
	"OVERRIDE_MIN_QTY" NUMBER(9,0),
	"OVERRIDE_MAX_QTY" NUMBER(9,0),
	"OVERRIDE_MIN_DAYS_SUPPLY" NUMBER(9,0),
	"OVERRIDE_MAX_DAYS_SUPPLY" NUMBER(9,0),
	"IS_ACTIVE" CHAR(1),
	"IS_DEFAULT_PLAN" CHAR(1),
	"PURCHASING_METHOD_CODE" CHAR(1),
	"MINIMUM_QTY" NUMBER(12,3),
	"MAXIMUM_QTY" NUMBER(12,3),
	"MIN_DAYS_SUPPLY" NUMBER(9,0),
	"MAX_DAYS_SUPPLY" NUMBER(9,0),
	"ORDER_QTY_ROUNDING_METHOD_CODE" CHAR(1),
	"NUMBER_DAYS_IN_BASE_PERIOD" NUMBER(3,0),
	"PERIOD_END_NUM_DAYS_AGO" NUMBER(3,0),
	"PERIOD_END_DATE" DATE,
	"PERCENTAGE_LEAD_TIME_DEMAND" NUMBER(3,0),
	"NEGATIVE_TOLERANCE_LEVEL_PCT" NUMBER(3,0),
	"POSITIVE_TOLERANCE_LEVEL_PCT" NUMBER(3,0),
	"EXCLUDE_FROM_RECOMMENDED_PO" CHAR(1),
	"EFFECTIVE_START_DATE" DATE,
	"EFFECTIVE_END_DATE" DATE,
	"PURCHASE_PLAN_NAME" VARCHAR2(50),
	"REORDER_PARAM_UPDATE_DATE_KEY" NUMBER(18,0),
	"INVENTORY_ITEM_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	 CONSTRAINT "FK_DRUG_17" FOREIGN KEY ("DRUG_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DRUG" ("DRUG_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_86" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_PRODUCT_43" FOREIGN KEY ("PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_121" FOREIGN KEY ("REORDER_PARAM_UPDATE_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE
   )
  PARTITION BY RANGE ("EFFECTIVE_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
