-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."RESHIPMENT"
   (	"RESHIPMENT_KEY" NUMBER(18,0),
	"RESHIPMENT_NUM" NUMBER(18,0),
	"FD_FACILITY_KEY" NUMBER(18,0),
	"PD_PATIENT_KEY" NUMBER(18,0),
	"ORDER_NUM" NUMBER(18,0),
	"ITEM_SEQ" NUMBER(18,0),
	"FACILITY_ORDER_NUMBER" VARCHAR2(10),
	"REASON_NUM" NUMBER(18,0),
	"SUBREASON_NUM" NUMBER(18,0),
	"RESHIPMENT_COMMENT" VARCHAR2(500),
	"RESHIPMENT_QUANTITY" NUMBER(16,8),
	"ADS_STATUS" CHAR(1),
	"CANCEL_CODE" VARCHAR2(10),
	"REJECT_CODE" VARCHAR2(10),
	"EXCEPTION_TEXT" VARCHAR2(500),
	"REQUEST_SUBMITTED_DATE_KEY" NUMBER(18,0),
	"REQUEST_SUBMITTED_TIME_KEY" NUMBER(5,0),
	"RESPONSE_RECEIVED_DATE_KEY" NUMBER(18,0),
	"RESPONSE_RECEIVED_TIME_KEY" NUMBER(5,0),
	"RPH_FIRST_NAME" VARCHAR2(50),
	"RPH_LAST_NAME" VARCHAR2(50),
	"RPH_NPI_NUMBER" VARCHAR2(20),
	"RPH_STATE_LICENSE_NUMBER" VARCHAR2(20),
	"ACTUAL_SHIPPING_METHOD" VARCHAR2(100),
	"ACTUAL_COURIER" VARCHAR2(50),
	"ACTUAL_SHIP_CHARGE" NUMBER(12,2),
	"ACTUAL_SHIP_DATE_KEY" NUMBER(18,0),
	"ACTUAL_SHIP_TIME_KEY" NUMBER(5,0),
	"SYS_USER_KEY" NUMBER(18,0),
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PARTITION_DATE" DATE,
	"NEXT_RESHIPMENT_NUM" NUMBER(18,0),
	 CONSTRAINT "PK_RESHIPMENT" PRIMARY KEY ("RESHIPMENT_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SYS_USER_151" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_FACILITY_130" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_PATIENT_100" FOREIGN KEY ("PD_PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_DATE_DIM_180" FOREIGN KEY ("REQUEST_SUBMITTED_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_DATE_DIM_181" FOREIGN KEY ("RESPONSE_RECEIVED_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_DATE_DIM_182" FOREIGN KEY ("ACTUAL_SHIP_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_TIME_DIM_80" FOREIGN KEY ("REQUEST_SUBMITTED_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_TIME_DIM_81" FOREIGN KEY ("RESPONSE_RECEIVED_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_TIME_DIM_82" FOREIGN KEY ("ACTUAL_SHIP_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") ENABLE NOVALIDATE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("DW_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
