-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."RESPONSIBLE_PARTY_TYPE"
   (	"RESPONSIBLE_PARTY_KEY" NUMBER(2,0) NOT NULL ENABLE,
	"RESPONSIBLE_PARTY_NAME" VARCHAR2(20),
	"ERX_CLIENT_ID" VARCHAR2(100)
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_RESPONSIBLE_PARTY_TYPE" ON "TREXONE_DW_DATA"."RESPONSIBLE_PARTY_TYPE" ("RESPONSIBLE_PARTY_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."RESPONSIBLE_PARTY_TYPE" ADD CONSTRAINT "PK_RESPONSIBLE_PARTY_TYPE" PRIMARY KEY ("RESPONSIBLE_PARTY_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_RESPONSIBLE_PARTY_TYPE"  ENABLE;
-- ==========================================
