-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."RX_RECORD_IMAGE"
   (	"RX_RECORD_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"IMAGE_TYPE" VARCHAR2(30),
	"IMAGE_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTOYMINTERVAL(1,'MONTH')) STORE IN ("DW_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2012-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
