-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."RX_STATUS"
   (	"RX_STATUS_KEY" NUMBER(18,0),
	"RX_STATUS_NUM" NUMBER(18,0),
	"DESCRIPTION" VARCHAR2(30),
	"DATA_GROUP" NUMBER(18,0),
	"SYS_USER_KEY" NUMBER(18,0),
	"DATESTAMP" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	 CONSTRAINT "PK_RX_STATUS" PRIMARY KEY ("RX_STATUS_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SYS_USER_140" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") ENABLE NOVALIDATE
   ) ;
-- ==========================================
