-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."SCHEDULE"
   (	"SCHEDULE_KEY" NUMBER,
	"SCHEDULE_NUM" NUMBER(18,0),
	"SCHEDULE_LINK_NUM" NUMBER(18,0),
	"SCHEDULE_DATE" DATE,
	"DAY_OF_WEEK" NUMBER(2,0),
	"OPEN_TIME" NUMBER(2,0),
	"CLOSE_TIME" NUMBER(2,0),
	"DESCRIPTION" VARCHAR2(255),
	"SYS_USER_KEY" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	 CONSTRAINT "FK_SYS_USER_91" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_SCHEDULE" ON "TREXONE_DW_DATA"."SCHEDULE" ("SCHEDULE_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."SCHEDULE" ADD CONSTRAINT "PK_SCHEDULE" PRIMARY KEY ("SCHEDULE_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_SCHEDULE"  ENABLE;
-- ==========================================
