-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."SHIPMENT_FACT"
   (	"FD_FACILITY_KEY" NUMBER(18,0),
	"PAD_KEY" NUMBER(18,0),
	"PD_PATIENT_KEY" NUMBER(18,0),
	"COURIER_SHIPMENT_KEY" NUMBER(18,0),
	"DM_DELIVERY_METHOD_KEY" NUMBER(18,0),
	"SHIP_DATE_KEY" NUMBER(18,0),
	"ORIG_EXPECT_DELIVERY_DATE_KEY" NUMBER(18,0),
	"ORIGINAL_SHIP_DATE_KEY" NUMBER(18,0),
	"EXPECTED_DELIVERY_DATE_KEY" NUMBER(18,0),
	"SHIP_ITEM_COUNT" NUMBER(9,0),
	"SHIPMENT_NUM" NUMBER(18,0),
	"ORDER_NUM" NUMBER(18,0),
	"FACILITY_ORDER_NUMBER" VARCHAR2(10),
	"PACKAGE_COUNT" NUMBER(5,0),
	"DEA_CLASS" CHAR(1),
	"REFRIGERATION" CHAR(1),
	"SHIP_HANDLE_FEE" NUMBER(17,6),
	"WEIGHT" NUMBER(16,8),
	"WEIGHT_UNITS" VARCHAR2(10),
	"TRACKING_NUMBER" VARCHAR2(200),
	"COURIER_SHIP_CHARGE" NUMBER(17,6),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID'),
	"PARTITION_DATE" DATE,
	"IS_SHIPPING_COMPLETE" CHAR(1),
	"EXPECTED_DELIVERY_TIME_KEY" NUMBER(18,0),
	"ORIGINAL_SHIP_TIME_KEY" NUMBER(18,0),
	"ORIG_EXPECT_DELIVERY_TIME_KEY" NUMBER(18,0),
	"SHIP_TIME_KEY" NUMBER(18,0),
	"ORIG_COURIER_SHIPMENT_KEY" NUMBER(18,0),
	"SHIPMENT_ADDRESS1" VARCHAR2(100),
	"SHIPMENT_ADDRESS2" VARCHAR2(100),
	"SHIPMENT_CITY" VARCHAR2(40),
	"SHIPMENT_STATE" VARCHAR2(2),
	"SHIPMENT_COUNTY" VARCHAR2(30),
	"SHIPMENT_ZIPCODE" VARCHAR2(20),
	"IS_SHIP_ADDR_CONFIRMED" CHAR(1),
	"ALTERNATE_RECIPIENT_KEY" NUMBER(18,0),
	"H_LEVEL" NUMBER,
	"PREVIOUS_SHIP_HANDLE_FEE" NUMBER(17,6),
	"SHIP_HANDLE_FEE_EXEMPT_REASON" VARCHAR2(200),
	 CONSTRAINT "FK_PATIENT_ADDRESS_02" FOREIGN KEY ("PAD_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT_ADDRESS" ("PAD_KEY") DISABLE,
	 CONSTRAINT "FK_COURIER_SHIPMENT_TYPE_01" FOREIGN KEY ("COURIER_SHIPMENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."COURIER_SHIPMENT_TYPE" ("COURIER_SHIPMENT_KEY") DISABLE,
	 CONSTRAINT "FK_DELIVERY_METHOD_TYPE_01" FOREIGN KEY ("DM_DELIVERY_METHOD_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DELIVERY_METHOD_TYPE" ("DM_DELIVERY_METHOD_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_98" FOREIGN KEY ("SHIP_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_99" FOREIGN KEY ("EXPECTED_DELIVERY_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_101" FOREIGN KEY ("ORIG_EXPECT_DELIVERY_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_100" FOREIGN KEY ("ORIGINAL_SHIP_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_89" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_42" FOREIGN KEY ("PD_PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") DISABLE,
	 CONSTRAINT "FK_COURIER_SHIPMENT_TYPE_02" FOREIGN KEY ("ORIG_COURIER_SHIPMENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."COURIER_SHIPMENT_TYPE" ("COURIER_SHIPMENT_KEY") DISABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
