-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."SIG"
   (	"SIG_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"SIG_MACRO" VARCHAR2(15),
	"SIG_DAILY_DOSAGE" NUMBER(16,8),
	"SIG_QTY_PER_DOSE" NUMBER(16,8),
	"SIG_LATIN_FREQUENCY_CODE" VARCHAR2(10),
	"SIG_IS_PRN_SIG" CHAR(1),
	"SIG_LATIN_FREQUENCY_QTY" NUMBER(9,0),
	"SIG_CONVERSION_FACTOR" NUMBER(9,3),
	"SIG_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_SIG" ON "TREXONE_DW_DATA"."SIG" ("SIG_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."SIG" ADD CONSTRAINT "PK_SIG" PRIMARY KEY ("SIG_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_SIG"  ENABLE;
-- ==========================================
