-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."SIG_ELEMENT_CONVERSION"
   (	"SEC_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"SEC_ELEMENT_TYPE" VARCHAR2(10),
	"SEC_SOURCE_WORD" VARCHAR2(50),
	"SEC_CONVERTED_WORD" VARCHAR2(50),
	"SEC_SIG_ELEMENT_CONV_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_SIG_ELEMENT_CONVERSION" ON "TREXONE_DW_DATA"."SIG_ELEMENT_CONVERSION" ("SEC_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."SIG_ELEMENT_CONVERSION" ADD CONSTRAINT "PK_SIG_ELEMENT_CONVERSION" PRIMARY KEY ("SEC_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_SIG_ELEMENT_CONVERSION"  ENABLE;
-- ==========================================
