-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."SPECIALTY_PROGRAM"
   (	"SPECIALTY_PROGRAM_KEY" NUMBER(18,0),
	"SPECIALTY_PROGRAM_NUM" NUMBER(18,0),
	"SYS_USER_KEY" NUMBER(18,0),
	"START_DATE" DATE,
	"END_DATE" DATE,
	"DATESTAMP" DATE,
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"SPECIALTY_PROG_TYPE_NAME" VARCHAR2(100),
	"SPECIALTY_PROG_SUB_TYPE_NAME" VARCHAR2(100),
	"SPECIALTY_PROGRAM_GROUP_NAME" VARCHAR2(100),
	"CENTRAL_FILL" VARCHAR2(20),
	"PROGRAM_CODE" VARCHAR2(10),
	 CONSTRAINT "PK_SPECIALTY_PROGRAM" PRIMARY KEY ("SPECIALTY_PROGRAM_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SYS_USER_113" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") ENABLE NOVALIDATE
   ) ;
-- ==========================================
