-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."SPEC_PROG_ANC_ITEM_LIST"
   (	"SPECIALTY_PROG_ANC_ITEM_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"SPECIALTY_PROG_ANC_ITEM_NUM" NUMBER(18,0),
	"ANCILLARY_ITEM_KEY" NUMBER(18,0),
	"SPECIALTY_PROGRAM_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"SYS_USER_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER(20,0),
	 CONSTRAINT "SPECLTY_PROG_ANC_ITEM_LIST_PK" PRIMARY KEY ("SPECIALTY_PROG_ANC_ITEM_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "SPCLTY_PROG_ANC_ITEM_LIST_FK01" FOREIGN KEY ("ANCILLARY_ITEM_KEY")
	  REFERENCES "TREXONE_DW_DATA"."ANCILLARY_ITEM" ("ANCILLARY_ITEM_KEY") ENABLE,
	 CONSTRAINT "SPCLTY_PROG_ANC_ITEM_LIST_FK02" FOREIGN KEY ("SPECIALTY_PROGRAM_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SPECIALTY_PROGRAM" ("SPECIALTY_PROGRAM_KEY") ENABLE,
	 CONSTRAINT "SPCLTY_PROG_ANC_ITEM_LIST_FK03" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("DW_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
