-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."SUPERVISOR_PRESCRIBER"
   (	"PRS_SUPV_PRESCRIBER_KEY" NUMBER(18,0),
	"PRS_PRESCRIBER_KEY" NUMBER(18,0),
	"IS_ACTIVE" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	 CONSTRAINT "PK_SUPERVISOR_PRESCRIBER" PRIMARY KEY ("PRS_SUPV_PRESCRIBER_KEY", "PRS_PRESCRIBER_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_PRESCRIBER_16" FOREIGN KEY ("PRS_SUPV_PRESCRIBER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRESCRIBER" ("PRS_PRESCRIBER_KEY") DISABLE,
	 CONSTRAINT "FK_PRESCRIBER_17" FOREIGN KEY ("PRS_PRESCRIBER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRESCRIBER" ("PRS_PRESCRIBER_KEY") DISABLE
   ) ;
-- ==========================================
