-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."SYS_USER"
   (	"SYS_USER_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER_NUM" NUMBER(18,0),
	"SYS_USER_LOGIN_NAME" VARCHAR2(255),
	"SYS_USER_FNAME" VARCHAR2(30),
	"SYS_USER_MNAME" VARCHAR2(30),
	"SYS_USER_LNAME" VARCHAR2(30),
	"SYS_USER_INITIALS" VARCHAR2(20),
	"SYS_USER_ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER_NUM_UPDATES" NUMBER(18,0),
	"SYS_USER_EMPLOYEE_CODE" VARCHAR2(20),
	"SYS_USER_IS_PRIVATE" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	"SYS_USER_EXTERNAL_USER_ID" VARCHAR2(30)
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_SYS_USER" ON "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."SYS_USER" ADD CONSTRAINT "PK_SYS_USER" PRIMARY KEY ("SYS_USER_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_SYS_USER"  ENABLE;
-- ==========================================
