-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."SYSTEM_EVENT_AUDIT"
   (	"DATE_KEY" NUMBER(18,0),
	"FD_FACILITY_KEY" NUMBER(18,0),
	"WFSD_KEY" NUMBER(18,0),
	"SYS_USER_KEY" NUMBER(18,0),
	"SAE_RX_RECORD_NUM" NUMBER(18,0),
	"SAE_RX_FILL_SEQ" VARCHAR2(20),
	"SAE_COMMENT" VARCHAR2(1000),
	"SAE_ADDITIONAL_PROPS" VARCHAR2(4000),
	"SAE_AUDIT_NAME" VARCHAR2(500),
	"SAE_START_TIME" DATE,
	"SAE_END_TIME" DATE,
	"SAE_TP_ITEM_CLAIM_NUM" NUMBER(18,0),
	"FD_FOR_FACILITY_KEY" NUMBER(18,0),
	"TIME_KEY" NUMBER(5,0),
	"SAE_RX_NUMBER" VARCHAR2(20),
	"SAE_REFILL_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	"PATIENT_KEY" NUMBER(18,0),
	 CONSTRAINT "FK_DATE_DIM_54" FOREIGN KEY ("DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_57" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_SYS_USER_61" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_11" FOREIGN KEY ("TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_WF_STEP_7" FOREIGN KEY ("WFSD_KEY")
	  REFERENCES "TREXONE_DW_DATA"."WF_STEP" ("WFSD_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_104" FOREIGN KEY ("FD_FOR_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_44" FOREIGN KEY ("PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") DISABLE
   )
  PARTITION BY RANGE ("SAE_START_TIME") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
