-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."THERAPEUTIC_SUB_CODE_TYPE"
   (	"TSC_THERAPUETIC_SUB_CODE_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"TSC_THERAPEUTIC_SUB_CODE" CHAR(1),
	"TSC_THERAPUETIC_SUB_CODE_DESC" VARCHAR2(100),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_THERAPEUTIC_SUB_CODE_TYPE" ON "TREXONE_DW_DATA"."THERAPEUTIC_SUB_CODE_TYPE" ("TSC_THERAPUETIC_SUB_CODE_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."THERAPEUTIC_SUB_CODE_TYPE" ADD CONSTRAINT "PK_THERAPEUTIC_SUB_CODE_TYPE" PRIMARY KEY ("TSC_THERAPUETIC_SUB_CODE_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_THERAPEUTIC_SUB_CODE_TYPE"  ENABLE;
-- ==========================================
