-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."THIRD_PARTY_SALES_SUMMARY"
   (	"FD_FACILITY_KEY" NUMBER,
	"DATE_KEY" NUMBER,
	"TPLD_PLAN_KEY" NUMBER,
	"TOTAL_PRICE_PAID" NUMBER,
	"TOTAL_REJECTS" NUMBER,
	"TOTAL_FILLS" NUMBER,
	"PARTITION_DATE" DATE,
	"TOTAL_REVERSAL" NUMBER,
	"TOTAL_CENTRAL_FILLS" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "FK_DATE_DIM_76" FOREIGN KEY ("DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_73" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_TP_PLAN_8" FOREIGN KEY ("TPLD_PLAN_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TP_PLAN" ("TPLD_PLAN_KEY") DISABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_THIRD_PARTY_SALES_SUMMARY" ON "TREXONE_DW_DATA"."THIRD_PARTY_SALES_SUMMARY" ("FD_FACILITY_KEY", "DATE_KEY", "TPLD_PLAN_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."THIRD_PARTY_SALES_SUMMARY" ADD CONSTRAINT "PK_THIRD_PARTY_SALES_SUMMARY" PRIMARY KEY ("FD_FACILITY_KEY", "DATE_KEY", "TPLD_PLAN_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_THIRD_PARTY_SALES_SUMMARY"  ENABLE;
-- ==========================================
