-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."THIRD_PARTY_CLAIM_SUMMARY"
   (	"ADJUDICATION_DATE_KEY" NUMBER(18,0),
	"FD_FACILITY_KEY" NUMBER(18,0),
	"TPLD_PLAN_KEY" NUMBER(18,0),
	"NEW_CLAIM_CNT" NUMBER(20,0),
	"REFILL_CLAIM_CNT" NUMBER(20,0),
	"CLAIM_CNT" NUMBER(20,0),
	"TOTAL_CLAIM_PRICE" NUMBER(20,6),
	"TOTAL_ACQ_COST" NUMBER(20,6),
	"TOTAL_MARGIN" NUMBER(20,6),
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "PK_THIRD_PARTY_CLAIM_SUMMARY" PRIMARY KEY ("ADJUDICATION_DATE_KEY", "FD_FACILITY_KEY", "TPLD_PLAN_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_FACILITY_113" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_154" FOREIGN KEY ("ADJUDICATION_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_TP_PLAN_11" FOREIGN KEY ("TPLD_PLAN_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TP_PLAN" ("TPLD_PLAN_KEY") DISABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("DW_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
