-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."TIME_DIM"
   (	"TIME_KEY" NUMBER(5,0) NOT NULL ENABLE,
	"TIME_TYPE" VARCHAR2(7),
	"HOUR_NUM" NUMBER(2,0),
	"MINUTE_NUM" NUMBER(2,0),
	"SECOND_NUM" NUMBER(2,0),
	"HOUR_TXT" CHAR(2),
	"MINUTE_TXT" CHAR(2),
	"SECOND_TXT" CHAR(2),
	"HOUR_MIN_TXT" CHAR(5),
	"HOUR_MIN_SEC_TXT" CHAR(8),
	"MIN_SEC_TXT" CHAR(5),
	"HOUR_12HR_TXT" CHAR(2),
	"TIME_OF_DAY_TXT" CHAR(11),
	"AM_PM_IND" CHAR(2),
	"DAYPART_QTR_CD" CHAR(1),
	"DAYPART_QTR_TXT" VARCHAR2(9),
	"DAYPART_SEGMENT_TXT" VARCHAR2(15),
	"MINUTES_AFTER_MIDNIGHT" NUMBER(4,0) GENERATED ALWAYS AS ("HOUR_NUM"*60+"MINUTE_NUM") VIRTUAL
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_TIME_DIM" ON "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."TIME_DIM" ADD CONSTRAINT "PK_TIME_DIM" PRIMARY KEY ("TIME_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_TIME_DIM"  ENABLE;
-- ==========================================
