-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."TP_PLAN"
   (	"TPLD_PLAN_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"TPLD_PLAN_CODE" VARCHAR2(10),
	"TPLD_PLAN_NAME" VARCHAR2(45),
	"TPLD_COMMENT_TEXT" VARCHAR2(255),
	"TPLD_IS_TEST_PLAN" CHAR(1),
	"TPLD_IS_MEDICAID_PLAN" CHAR(1),
	"TPLD_IS_MEDICARE_PLAN" CHAR(1),
	"TPLD_IS_WORKERS_COMP_PLAN" CHAR(1),
	"TPLD_PRMRY_INSRNCE_TYPE_CD" VARCHAR2(3),
	"TPLD_IS_ALL_STORE_PLAN" CHAR(1),
	"TPLD_EFFECTIVE_DATE" DATE,
	"TPLD_TERMINATION_DATE" DATE,
	"TPLD_PLAN_NUM" NUMBER(18,0),
	"TPLD_AGENCY_TYPE_NUM" NUMBER(18,0),
	"RUN_MEDICAID_EDITS" CHAR(1),
	"IS_MAIL_ORDER_PLAN" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	"IS_340B" CHAR(1),
	"PROCESSOR_NAME" VARCHAR2(45),
	"PARTIAL_FILL_BILLING" CHAR(1),
	"BILLING_TYPE" CHAR(1),
	"ALLOW_LOWER_COPAY_OVERRIDE" CHAR(1),
	"ALLOW_HIGHER_COPAY_OVERRIDE" CHAR(1),
	"RECALCULATE_COPAY_OVERRIDE" CHAR(1),
	"CLAIM_TP_BILLING_FORMAT" VARCHAR2(60),
	"REV_TP_BILLING_FORMAT" VARCHAR2(60),
	"ELIG_TP_BILLING_FORMAT" VARCHAR2(60),
	"BENEFIT_GROUP_ID" VARCHAR2(15),
	"BENEFIT_GROUP_NAME" VARCHAR2(45),
	"FACILITY_PLAN_NUMBER" VARCHAR2(20),
	"IS_MEDICARE_FACILITATOR" CHAR(1),
	"CONTACT_NAME" VARCHAR2(40),
	"PLAN_ADDRESS1" VARCHAR2(100),
	"PLAN_ADDRESS2" VARCHAR2(50),
	"PLAN_CITY" VARCHAR2(40),
	"PLAN_STATE_CODE" VARCHAR2(8),
	"PLAN_ZIP_CODE" VARCHAR2(20),
	"PLAN_PHONE_NUMBER" VARCHAR2(30),
	"PLAN_FAX_NUMBER" VARCHAR2(30),
	"PLAN_HELPDESK_PHON_NUMBER" VARCHAR2(30),
	"BIN" VARCHAR2(6),
	"PCN" VARCHAR2(10),
	"IS_ERP_ALLOWED" CHAR(1)
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_TP_PLAN" ON "TREXONE_DW_DATA"."TP_PLAN" ("TPLD_PLAN_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."TP_PLAN" ADD CONSTRAINT "PK_TP_PLAN" PRIMARY KEY ("TPLD_PLAN_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_TP_PLAN"  ENABLE;
-- ==========================================
