-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."TP_PATIENT"
   (	"TPD_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PD_PATIENT_H_KEY" NUMBER(18,0),
	"TPD_PATIENT_NUM" NUMBER(9,0),
	"TPD_CARDHOLDER_PATIENT_NUM" NUMBER(18,0),
	"TPD_TP_PLAN_NUM" NUMBER(18,0),
	"TPD_CARDHOLDER_ID" VARCHAR2(20),
	"TPD_BENEFIT_GROUP_ID" VARCHAR2(15),
	"TPD_HOME_PLAN" VARCHAR2(3),
	"TPD_PLAN_ID" VARCHAR2(8),
	"TPD_RELATIONSHIP_NUM" NUMBER(9,0),
	"TPD_PERSON_CODE" VARCHAR2(3),
	"TPD_BILLING_ORDER" NUMBER(9,0),
	"TPD_IS_ACTIVE" CHAR(1),
	"TPD_EFFECTIVE_DATE" DATE,
	"TPD_TERMINATION_DATE" DATE,
	"TPD_MULTI_SOURCE_COPAY_AMT" NUMBER(17,6),
	"TPD_MULTI_SOURCE_COPAY_PER" NUMBER(17,6),
	"TPD_SING_SRC_COPAY_AMT" NUMBER(17,6),
	"TPD_SING_SRC_COPAY_PER" NUMBER(17,6),
	"TPD_GENERIC_COPAY_AMOUNT" NUMBER(17,6),
	"TPD_GENERIC_COPAY_PERCENT" NUMBER(17,6),
	"TPD_PTD_COVERAGE_AMOUNT" NUMBER(17,6),
	"TPD_PTD_NUM_RXS" NUMBER(9,0),
	"TPD_DEACTIVATION_DATE" DATE,
	"TPD_DEACTIVATION_COMMENT" VARCHAR2(255),
	"TPD_PATIENT_LOCATION" NUMBER(9,0),
	"TPD_USE_FOR_COB" CHAR(1),
	"TPD_FMLY_PTD_COVERAGE_AMT" NUMBER(17,6),
	"TPD_FMLY_PTD_NUM_RXS" NUMBER(9,0),
	"TPD_FMLY_PTD_DEDUCT_AMT" NUMBER(17,6),
	"TPD_PTD_DEDUCT_EXP" DATE,
	"TPD_FMLY_PTD_DEDUCT_EXP" DATE,
	"TPD_PTD_COVERAGE_EXP" DATE,
	"TPD_PTD_NUM_RXS_EXP" DATE,
	"TPD_FMLY_PTD_COVERAGE_EXP" DATE,
	"TPD_FMLY_NUM_RXS_EXP" DATE,
	"TPD_PTD_DEDUCT_AMT" NUMBER(17,6),
	"TPD_ELIGIBILITY_CLARIF_NUM" NUMBER(9,0),
	"TPD_TP_PATIENT_NUM" NUMBER(18,0),
	"TPD_REMAINING_BENEFIT_AMT" NUMBER(17,6),
	"TPD_EFF_START_DATE" DATE,
	"TPD_EFF_END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PD_PATIENT_KEY" NUMBER(18,0),
	"H_LEVEL" NUMBER,
	 CONSTRAINT "FK_PATIENT_H_27" FOREIGN KEY ("PD_PATIENT_H_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT_H" ("PD_PATIENT_H_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_27" FOREIGN KEY ("PD_PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") DISABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PKTP_PATIENT" ON "TREXONE_DW_DATA"."TP_PATIENT" ("TPD_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."TP_PATIENT" ADD CONSTRAINT "PKTP_PATIENT" PRIMARY KEY ("TPD_KEY")
  USING INDEX "TREXONE_DW_DATA"."PKTP_PATIENT"  ENABLE;
-- ==========================================
