-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."TP_RESPONSE_TYPE"
   (	"TP_RESPONSE_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"TP_RESPONSE_CODE" VARCHAR2(50),
	"NCPDP_RESPONSE_CODE" VARCHAR2(1),
	"ERX_CLIENT_ID" VARCHAR2(100)
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PKTP_RESPONSE_TYPE" ON "TREXONE_DW_DATA"."TP_RESPONSE_TYPE" ("TP_RESPONSE_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."TP_RESPONSE_TYPE" ADD CONSTRAINT "PKTP_RESPONSE_TYPE" PRIMARY KEY ("TP_RESPONSE_KEY")
  USING INDEX "TREXONE_DW_DATA"."PKTP_RESPONSE_TYPE"  ENABLE;
-- ==========================================
