-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."TP_WORKERS_COMP_APPROVAL"
   (	"TP_WORKERS_COMP_APPROVAL_KEY" NUMBER(18,0),
	"TP_WORKERS_COMP_APPROVAL_NUM" NUMBER(18,0),
	"TWED_KEY" NUMBER(18,0),
	"APPROVAL_NUMBER" VARCHAR2(30),
	"AUTHORIZED_BY" VARCHAR2(30),
	"STATUS" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	 CONSTRAINT "PK_TP_WORKERS_COMP_APPROVAL" PRIMARY KEY ("TP_WORKERS_COMP_APPROVAL_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_TP_WORKERS_COMP_03" FOREIGN KEY ("TWED_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TP_WORKERS_COMP" ("TWED_KEY") DISABLE
   ) ;
-- ==========================================
