-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."USER_ACTION_TYPE"
   (	"UA_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"US_DESCRIPTION" VARCHAR2(30),
	"ERX_CLIENT_ID" VARCHAR2(100)
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_USER_ACTION_TYPE" ON "TREXONE_DW_DATA"."USER_ACTION_TYPE" ("UA_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."USER_ACTION_TYPE" ADD CONSTRAINT "PK_USER_ACTION_TYPE" PRIMARY KEY ("UA_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_USER_ACTION_TYPE"  ENABLE;
-- ==========================================
