-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."VENDOR_CONFIG"
   (	"VENDOR_CONFIG_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"VENDOR_KEY" NUMBER(18,0),
	"ACCOUNT_NUMBER" VARCHAR2(16),
	"SENDER_ID" VARCHAR2(16),
	"RECEIVER_ID" VARCHAR2(16),
	"PURCHASE_ORDER_SORT_CODE" CHAR(1),
	"LEAD_TIME" NUMBER(9,0),
	"AUTO_TRANSMIT_PO_FLAG" CHAR(1),
	"DELIVERS_ON_SUNDAY" CHAR(1),
	"DELIVERS_ON_MONDAY" CHAR(1),
	"DELIVERS_ON_TUESDAY" CHAR(1),
	"DELIVERS_ON_WEDNESDAY" CHAR(1),
	"DELIVERS_ON_THURSDAY" CHAR(1),
	"DELIVERS_ON_FRIDAY" CHAR(1),
	"DELIVERS_ON_SATURDAY" CHAR(1),
	"C2_PO_STATUS" CHAR(1),
	"RANK" NUMBER(9,0),
	"IS_ACTIVE" CHAR(1),
	"FD_FACILITY_KEY" NUMBER(18,0),
	"EFFECTIVE_START_DATE" DATE,
	"EFFECTIVE_END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID'),
	"H_LEVEL" NUMBER(20,0),
	"DATESTAMP" DATE,
	"VENDOR_CONFIGURATION_NUM" NUMBER(18,0),
	"DSCSA_EXEMPT" CHAR(1),
	"PROMPT_FOR_PO" CHAR(1),
	 CONSTRAINT "PK_VENDOR_CONFIG" PRIMARY KEY ("VENDOR_CONFIG_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_FACILITY_102" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_VENDOR_01" FOREIGN KEY ("VENDOR_KEY")
	  REFERENCES "TREXONE_DW_DATA"."VENDOR" ("VENDOR_KEY") DISABLE
   ) ;
-- ==========================================
