-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."VENDOR_OVERRIDE"
   (	"VENDOR_KEY" NUMBER(18,0),
	"DRUG_KEY" NUMBER(18,0),
	"PRD_PRODUCT_KEY" NUMBER(18,0),
	"FD_FACILITY_KEY" NUMBER(18,0),
	"PURCHASING_PLAN_ITEM_NUM" NUMBER(18,0),
	"VENDOR_NUM" NUMBER(18,0),
	"MINIMUM_QTY" NUMBER(12,3),
	"MAXIMUM_QTY" NUMBER(12,3),
	"MIN_DAYS_SUPPLY" NUMBER(9,0),
	"MAX_DAYS_SUPPLY" NUMBER(9,0),
	"H_LEVEL" NUMBER(20,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"OVERRIDE_DATE_KEY" NUMBER(18,0),
	 CONSTRAINT "FK_VENDOR_03" FOREIGN KEY ("VENDOR_KEY")
	  REFERENCES "TREXONE_DW_DATA"."VENDOR" ("VENDOR_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_08" FOREIGN KEY ("OVERRIDE_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DRUG_24" FOREIGN KEY ("DRUG_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DRUG" ("DRUG_KEY") DISABLE,
	 CONSTRAINT "FK_PRODUCT_45" FOREIGN KEY ("PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_88" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE
   ) ;
-- ==========================================
