-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."WF_STEP"
   (	"WFSD_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"WFSD_STEP_DESCRIPTION" VARCHAR2(100),
	"WFSD_STEP_CODE" VARCHAR2(2),
	"DISPLAY_ORDER" NUMBER(3,0) DEFAULT 0,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_WF_STEP" ON "TREXONE_DW_DATA"."WF_STEP" ("WFSD_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."WF_STEP" ADD CONSTRAINT "PK_WF_STEP" PRIMARY KEY ("WFSD_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_WF_STEP"  ENABLE;
-- ==========================================
