-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ACC_PERSON"
   (	"ACC_PERSON_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TITLE" VARCHAR2(10),
	"LAST_NAME" VARCHAR2(30),
	"MIDDLE_NAME" VARCHAR2(30),
	"FIRST_NAME" VARCHAR2(30),
	"NAME_SUFFIX" VARCHAR2(10),
	"BIRTH_DATE" DATE,
	"SSN_NUM" VARCHAR2(9),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_ACC_PERSON" PRIMARY KEY ("ACC_PERSON_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
