-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ACC_PREPAYMENT"
   (	"ACC_PREPAYMENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACC_PREPAYMENT_LIST_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACC_ACCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PAYER" VARCHAR2(200),
	"TX_DATE" DATE,
	"SERVICE_DATE" DATE,
	"PAYMENT_AMOUNT" NUMBER(17,6),
	"DISCOUNT_AMOUNT" NUMBER(17,6),
	"CHECK_DATE" DATE,
	"CHECK_ACCOUNT_NUMBER" VARCHAR2(20),
	"CHECK_NUMBER" VARCHAR2(20),
	"CHECK_ROUTING_NUMBER" VARCHAR2(20),
	"DESCRIPTION" VARCHAR2(4000),
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_ACC_PREPAYMENT" PRIMARY KEY ("ACC_PREPAYMENT_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_ACC_PREPAYMENT_LIST_1" FOREIGN KEY ("ACC_PREPAYMENT_LIST_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_PREPAYMENT_LIST" ("ACC_PREPAYMENT_LIST_NUM") ENABLE,
	 CONSTRAINT "FK_ACC_ACCT_9" FOREIGN KEY ("ACC_ACCT_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_ACCT" ("ACC_ACCT_NUM") ENABLE
   ) ;
-- ==========================================
