-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ACC_STATEMENT_ADDRESS"
   (	"ACC_STATEMENT_ADDRESS_NUM" NUMBER(18,0),
	"BILLING_NAME" VARCHAR2(200),
	"ADDRESS1" VARCHAR2(100),
	"ADDRESS2" VARCHAR2(50),
	"CITY" VARCHAR2(40),
	"STATE_CODE" VARCHAR2(2),
	"ZIPCODE" VARCHAR2(20),
	"CTRY_CODE" VARCHAR2(8),
	"COUNTY" VARCHAR2(30),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"HOLDER_NAME" VARCHAR2(200),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"ACCT_HOLDER_ADDRESS1" VARCHAR2(100),
	 CONSTRAINT "PK_ACC_STATEMENT_ADDRESS" PRIMARY KEY ("ACC_STATEMENT_ADDRESS_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
