-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ACC_AR_ACCT_DUN_DEFAULTS"
   (	"ACC_AR_ACCT_DUN_DEFAULTS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACC_AR_ACCT_TYPE_DEFAULTS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"START_DAY" NUMBER(9,0),
	"END_DAY" NUMBER(9,0),
	"DESCRIPTION" VARCHAR2(1000),
	"MESSAGE" VARCHAR2(1000),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_ACC_AR_ACCT_DUN_DEFAULTS" PRIMARY KEY ("ACC_AR_ACCT_DUN_DEFAULTS_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_ACC_AR_ACCT_TYPE_DEFAULTS_1" FOREIGN KEY ("ACC_AR_ACCT_TYPE_DEFAULTS_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_AR_ACCT_TYPE_DEFAULTS" ("ACC_AR_ACCT_TYPE_DEFAULTS_NUM") ENABLE
   ) ;
-- ==========================================
