-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ACC_TX"
   (	"ACC_TX_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(200),
	"ACC_TX_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"IS_DELETED" CHAR(1) NOT NULL ENABLE,
	"ACC_COST_CENTER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"IS_CURRENT" CHAR(1) NOT NULL ENABLE,
	"CLOSED_DATE" DATE,
	"POST_DATE" DATE,
	"TX_DATE" DATE,
	"DESCRIPTION" VARCHAR2(4000),
	"REASON" VARCHAR2(200),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"TX_NUMBER" VARCHAR2(255) NOT NULL ENABLE,
	"EXTERNAL_REFERENCE" VARCHAR2(40),
	"ACC_RECURRING_TX_NUM" NUMBER(18,0),
	"SEPARATE_LINE_ITEM" CHAR(1),
	"TEMPLATE_TX_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_ACC_TX" PRIMARY KEY ("ACC_TX_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_ACC_COST_CENTER_02" FOREIGN KEY ("ACC_COST_CENTER_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_COST_CENTER" ("ACC_COST_CENTER_NUM") ENABLE,
	 CONSTRAINT "FK_ACC_TX_TYPE_01" FOREIGN KEY ("ACC_TX_TYPE_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_TX_TYPE" ("ACC_TX_TYPE_NUM") ENABLE,
	 CONSTRAINT "FK_ACC_RECURRING_TX_01" FOREIGN KEY ("ACC_RECURRING_TX_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_RECURRING_TX" ("ACC_RECURRING_TX_NUM") ENABLE,
	 CONSTRAINT "FK_ACC_TX_07" FOREIGN KEY ("TEMPLATE_TX_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_TX" ("ACC_TX_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
