-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ACC_STMT_PAYMENT_DETAIL"
   (	"ACC_STMT_PAYMENT_DETAIL_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACC_STATEMENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACC_PAYMENT_DETAIL_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"AMOUNT" CHAR(20),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_ACC_STMT_PAYMENT_DETAIL" PRIMARY KEY ("ACC_STMT_PAYMENT_DETAIL_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_ACC_PAYMENT_DETAIL_02" FOREIGN KEY ("ACC_PAYMENT_DETAIL_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_PAYMENT_DETAIL" ("ACC_PAYMENT_DETAIL_NUM") ENABLE,
	 CONSTRAINT "FK_ACC_STATEMENT_03" FOREIGN KEY ("ACC_STATEMENT_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_STATEMENT" ("ACC_STATEMENT_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
