-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ACC_PREPAYMENT_LIST"
   (	"ACC_PREPAYMENT_LIST_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(200),
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) DEFAULT 100 NOT NULL ENABLE,
	 CONSTRAINT "PK_ACC_PREPAYMENT_LIST" PRIMARY KEY ("ACC_PREPAYMENT_LIST_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_CREATION_FACILITY" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE
   ) ;
-- ==========================================
