-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ACC_STATEMENT_ENTRY"
   (	"ACC_STATEMENT_ENTRY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACC_STATEMENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"IS_PAID" CHAR(1) NOT NULL ENABLE,
	"ACC_ENTRY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_ACC_STATEMENT_ENTRY" PRIMARY KEY ("ACC_STATEMENT_ENTRY_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_ACC_BILL_01" FOREIGN KEY ("ACC_STATEMENT_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_STATEMENT" ("ACC_STATEMENT_NUM") ENABLE,
	 CONSTRAINT "FK_ACC_ENTRY_01" FOREIGN KEY ("ACC_ENTRY_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_ENTRY" ("ACC_ENTRY_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
