-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ACC_ACCT_ENTITY"
   (	"ACC_ACCT_ENTITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACC_PERSON_NUM" NUMBER(18,0),
	"ACC_INSTITUTION_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_ACC_ACCT_ENTITY" PRIMARY KEY ("ACC_ACCT_ENTITY_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_ACC_INSTITUTION_01" FOREIGN KEY ("ACC_INSTITUTION_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_INSTITUTION" ("ACC_INSTITUTION_NUM") ENABLE,
	 CONSTRAINT "FK_ACC_PERSON_01" FOREIGN KEY ("ACC_PERSON_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_PERSON" ("ACC_PERSON_NUM") ENABLE
   ) ;
-- ==========================================
