-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ACCOUNT_MEMBER_CREDIT_CARD"
   (	"ACCOUNT_MEMBER_CREDIT_CARD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACCOUNT_MEMBER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CREDIT_CARD_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"EXPIRATION_DATE" DATE NOT NULL ENABLE,
	"LAST4_PAN" CHAR(4) NOT NULL ENABLE,
	"FIRST_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"MIDDLE_NAME" VARCHAR2(30),
	"LAST_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"CREDIT_CARD_STATUS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CARD_NOTE" VARCHAR2(100),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"IS_ONE_TIME_CHARGE" CHAR(1) DEFAULT 'N' NOT NULL ENABLE,
	"FIRST6_PAN" CHAR(6),
	"HEALTH_CARD_DESIGNATION" VARCHAR2(20),
	"HEALTH_CARD_DESIGNATION_DATE" DATE,
	"CREDIT_CARD_TOKEN" VARCHAR2(100) NOT NULL ENABLE,
	"CREDIT_CARD_TOKEN_TYPE" CHAR(1) DEFAULT 'R' NOT NULL ENABLE,
	"PAYMENT_TYPE_NUM" NUMBER(18,0),
	"FIRST10_PAN" CHAR(10),
	 CONSTRAINT "PK_ACCOUNT_MEMBER_CREDIT_CARD" PRIMARY KEY ("ACCOUNT_MEMBER_CREDIT_CARD_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_ACCOUNT_MEMBER_01" FOREIGN KEY ("ACCOUNT_MEMBER_NUM")
	  REFERENCES "TREXONE_DATA"."ACCOUNT_MEMBER" ("ACCOUNT_MEMBER_NUM") ENABLE,
	 CONSTRAINT "FK_CREDIT_CARD_TYPE_01" FOREIGN KEY ("CREDIT_CARD_TYPE_NUM")
	  REFERENCES "TREXONE_DATA"."CREDIT_CARD_TYPE" ("CREDIT_CARD_TYPE_NUM") ENABLE,
	 CONSTRAINT "FK_CREDIT_CARD_STATUS_01" FOREIGN KEY ("CREDIT_CARD_STATUS_NUM")
	  REFERENCES "TREXONE_DATA"."CREDIT_CARD_STATUS" ("CREDIT_CARD_STATUS_NUM") ENABLE
   ) ;
-- ==========================================
