-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ACCOUNT_CC_DENIAL"
   (	"ACCOUNT_CC_DENIAL_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACCOUNT_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_FILL_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"REGISTER_TXN" NUMBER(9,0) NOT NULL ENABLE,
	"REGISTER_TXN_SEQ" NUMBER(9,0) NOT NULL ENABLE,
	"TENDER_AMOUNT" NUMBER(17,6) NOT NULL ENABLE,
	"DENIAL_CD" CHAR(2) NOT NULL ENABLE,
	"DENIAL_DESC" VARCHAR2(20),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"REGISTER_NUM" NUMBER(9,0),
	"PARTIAL_FILL_NUM" NUMBER(2,0),
	"DENIAL_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_ACCOUNT_01" FOREIGN KEY ("ACCOUNT_NUM")
	  REFERENCES "TREXONE_DATA"."ACCOUNT" ("ACCOUNT_NUM") ENABLE,
	 CONSTRAINT "FK_FACILITY_02" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_RX_FILL_01" FOREIGN KEY ("RX_FILL_SEQ", "RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_FILL" ("RX_FILL_SEQ", "RX_RECORD_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_ACCOUNT_CC_DENIAL" ON "TREXONE_DATA"."ACCOUNT_CC_DENIAL" ("ACCOUNT_CC_DENIAL_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."ACCOUNT_CC_DENIAL" ADD CONSTRAINT "PK_ACCOUNT_CC_DENIAL" PRIMARY KEY ("ACCOUNT_CC_DENIAL_NUM")
  USING INDEX "TREXONE_DATA"."PK_ACCOUNT_CC_DENIAL"  ENABLE;
-- ==========================================
