-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ACCOUNT_CREDIT_CARD"
   (	"ACCOUNT_CREDIT_CARD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PATIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CARD_TYPE_NUM" NUMBER(9,0) NOT NULL ENABLE,
	"EXPIRATION_DATE" DATE NOT NULL ENABLE,
	"CHARGE_CARD_NUM" VARCHAR2(200) NOT NULL ENABLE,
	"KEY_ALIAS" VARCHAR2(20) NOT NULL ENABLE,
	"CARDHOLDER_NAME" VARCHAR2(61) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PATIENT_19" FOREIGN KEY ("PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_ACCOUNT_CREDIT_CARD" ON "TREXONE_DATA"."ACCOUNT_CREDIT_CARD" ("ACCOUNT_CREDIT_CARD_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."ACCOUNT_CREDIT_CARD" ADD CONSTRAINT "PK_ACCOUNT_CREDIT_CARD" PRIMARY KEY ("ACCOUNT_CREDIT_CARD_NUM")
  USING INDEX "TREXONE_DATA"."PK_ACCOUNT_CREDIT_CARD"  ENABLE;
-- ==========================================
