-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ACCOUNT"
   (	"ACCOUNT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACCOUNT_NUMBER" VARCHAR2(30),
	"STATUS" CHAR(1) NOT NULL ENABLE,
	"APPLY_FINANCE_CHARGE_OVERRIDE" CHAR(1),
	"FINANCE_CHG_PERCENT_OVERRIDE" NUMBER(16,8),
	"FINANCE_CHARGE_DAYS_OVERRIDE" NUMBER(9,0),
	"PAYMENT_DISC_ALLOWED_OVERRIDE" CHAR(1),
	"PAYMENT_DISC_PERCENT_OVERRIDE" NUMBER(16,8),
	"PAYMENT_DISCOUNT_DAYS_OVERRIDE" NUMBER(9,0),
	"APPLY_MISC_CHG_TAX" CHAR(1),
	"LAST_CLOSED_DATE" DATE,
	"MERGED_INTO_ACCOUNT" NUMBER(18,0),
	"LOCK_USER" NUMBER(18,0),
	"LOCK_DATE" DATE,
	"ALLOW_HOUSE_CHARGE" CHAR(1) NOT NULL ENABLE,
	"USE_AR" CHAR(1) NOT NULL ENABLE,
	"PRINT_STATEMENT" CHAR(1) NOT NULL ENABLE,
	"PRINT_DUNNING_MSG_OVERRIDE" CHAR(1) NOT NULL ENABLE,
	"APPLY_RECURRING_CHG_TAX" CHAR(1),
	"CREATE_DATE" DATE,
	"DATA_GROUP" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"DEFAULT_ACCOUNT_MEMBER_CC_NUM" NUMBER(18,0),
	"DEFAULT_SHIPPING_ADDRESS_NUM" NUMBER(18,0),
	"USE_ACCOUNT_CREDIT_CARD" CHAR(1),
	 CONSTRAINT "FK_ACCOUNT_MEMBER_CREDIT_CD_03" FOREIGN KEY ("DEFAULT_ACCOUNT_MEMBER_CC_NUM")
	  REFERENCES "TREXONE_DATA"."ACCOUNT_MEMBER_CREDIT_CARD" ("ACCOUNT_MEMBER_CREDIT_CARD_NUM") ENABLE,
	 CONSTRAINT "FK_ADDRESS_02" FOREIGN KEY ("DEFAULT_SHIPPING_ADDRESS_NUM")
	  REFERENCES "TREXONE_DATA"."ADDRESS" ("ADDRESS_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_ACCOUNT" ON "TREXONE_DATA"."ACCOUNT" ("ACCOUNT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."ACCOUNT" ADD CONSTRAINT "PK_ACCOUNT" PRIMARY KEY ("ACCOUNT_NUM")
  USING INDEX "TREXONE_DATA"."PK_ACCOUNT"  ENABLE;
-- ==========================================
