-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ADDRESS_PHONE"
   (	"ADDRESS_LINK_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PHONE_LINK_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_ADDRESS_LINK_01" FOREIGN KEY ("ADDRESS_LINK_NUM")
	  REFERENCES "TREXONE_DATA"."ADDRESS_LINK" ("ADDRESS_LINK_NUM") ENABLE,
	 CONSTRAINT "FK_PHONE_LINK_01" FOREIGN KEY ("PHONE_LINK_NUM")
	  REFERENCES "TREXONE_DATA"."PHONE_LINK" ("PHONE_LINK_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_ADDRESS_PHONE" ON "TREXONE_DATA"."ADDRESS_PHONE" ("ADDRESS_LINK_NUM", "PHONE_LINK_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."ADDRESS_PHONE" ADD CONSTRAINT "PK_ADDRESS_PHONE" PRIMARY KEY ("ADDRESS_LINK_NUM", "PHONE_LINK_NUM")
  USING INDEX "TREXONE_DATA"."PK_ADDRESS_PHONE"  ENABLE;
-- ==========================================
