-- ==========================================

  CREATE TABLE "TREXONE_DATA"."AIM_MESSAGE_ING_INFO"
   (	"AIM_MESSAGE_ING_INFO_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"AIM_MESSAGE_NUM" NUMBER(18,0),
	"NDC" VARCHAR2(11),
	"ITEM_NUM" NUMBER(18,0),
	"DISPENSED_QTY" NUMBER(13,3),
	"DISPENSED_QTY_SIGN" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_AIM_MESSAGE_1" FOREIGN KEY ("AIM_MESSAGE_NUM")
	  REFERENCES "TREXONE_DATA"."AIM_MESSAGE" ("AIM_MESSAGE_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PKAIM_MESSAGE_ING_INFO" ON "TREXONE_DATA"."AIM_MESSAGE_ING_INFO" ("AIM_MESSAGE_ING_INFO_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."AIM_MESSAGE_ING_INFO" ADD CONSTRAINT "PKAIM_MESSAGE_ING_INFO" PRIMARY KEY ("AIM_MESSAGE_ING_INFO_NUM")
  USING INDEX "TREXONE_DATA"."PKAIM_MESSAGE_ING_INFO"  ENABLE;
-- ==========================================
