-- ==========================================

  CREATE TABLE "TREXONE_DATA"."AIM_MESSAGE"
   (	"AIM_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_NUMBER" VARCHAR2(20),
	"REFILL_NUM" NUMBER(18,0),
	"PARTIAL_FILL_SEQ" NUMBER(2,0),
	"FACILITY_ID" VARCHAR2(10),
	"INTENDED_QTY_DISPENSED" NUMBER(13,3),
	"INTENDED_QTY_DISPENSED_SIGN" CHAR(1),
	"PARTIAL_FILL_IND" CHAR(1),
	"DAYS_SUPPLY" NUMBER(9,0),
	"DAYS_SUPPLY_SIGN" CHAR(1),
	"REFILLS_REMAINING" NUMBER(9,0),
	"REFILLS_REMAINING_SIGN" CHAR(1),
	"RX_STATUS" CHAR(1),
	"COMPOUND_IND" CHAR(1),
	"PATIENT_PAY_AMOUNT" NUMBER(17,6),
	"TOTAL_TAX" NUMBER(17,6),
	"FREQUENT_SHOPPER_NUM" VARCHAR2(20),
	"MSG_STATUS" CHAR(1),
	"MSG_RETRY_CNT" NUMBER(5,0),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"IS_EASY_CAP_SIG" CHAR(1),
	"IS_HIPAA_SIG" CHAR(1),
	"IS_RX_ACK_SIG" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"ACQUISITION_COST" NUMBER(18,6),
	"ADJUDICATED_TIMESTAMP" DATE,
	"DOWNTIME_RX_NUMBER" VARCHAR2(12),
	"ORDER_NUM" NUMBER(18,0),
	"ITEM_SEQ" NUMBER(18,0),
	"PATIENT_NUM" NUMBER(18,0),
	"DISPENSED_PRODUCT_NUM" NUMBER(18,0)
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PKAIM_MESSAGE" ON "TREXONE_DATA"."AIM_MESSAGE" ("AIM_MESSAGE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."AIM_MESSAGE" ADD CONSTRAINT "PKAIM_MESSAGE" PRIMARY KEY ("AIM_MESSAGE_NUM")
  USING INDEX "TREXONE_DATA"."PKAIM_MESSAGE"  ENABLE;
-- ==========================================
