-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ANCILLARY_ITEM_ADJUSTMENT"
   (	"ANCILLARY_ITEM_ADJ_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ANCILLARY_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"INV_ADJUST_REASON_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"QUANTITY" NUMBER(16,8) NOT NULL ENABLE,
	"ADJUSTMENT_TYPE_CODE" VARCHAR2(3) NOT NULL ENABLE,
	"CREATE_USER" NUMBER(18,0) NOT NULL ENABLE,
	"CREATE_DATE" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "ANCILLARY_ITEM_ADJUSTMENT_PK" PRIMARY KEY ("ANCILLARY_ITEM_ADJ_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "ANCILLARY_ITEM_ADJUSTMENT_FK01" FOREIGN KEY ("ANCILLARY_ITEM_NUM")
	  REFERENCES "TREXONE_DATA"."ANCILLARY_ITEM" ("ANCILLARY_ITEM_NUM") ENABLE,
	 CONSTRAINT "ANCILLARY_ITEM_ADJUSTMENT_FK02" FOREIGN KEY ("INV_ADJUST_REASON_NUM")
	  REFERENCES "TREXONE_DATA"."INVENTORY_ADJUSTMENT_REASON" ("INV_ADJUST_REASON_NUM") ENABLE
   ) ;
-- ==========================================
