-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ANCILLARY_ITEM"
   (	"ANCILLARY_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"INVENTORY_SKU_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"EXPIRATION_DATE" DATE,
	"ORIGIN_DATE" DATE,
	"COST" NUMBER(17,6),
	"PRICE" NUMBER(17,6),
	"QUANTITY" NUMBER(16,8) NOT NULL ENABLE,
	"ORIGINAL_QUANTITY" NUMBER(16,8) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	"RECOMMENDED_QTY" NUMBER(16,8),
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0) NOT NULL ENABLE,
	 CONSTRAINT "PK_ANCILLARY_ITEM" PRIMARY KEY ("ANCILLARY_ITEM_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_ANCILLARY_ITEM_01" FOREIGN KEY ("INVENTORY_SKU_NUM")
	  REFERENCES "TREXONE_DATA"."INVENTORY_SKU" ("INVENTORY_SKU_NUM") ENABLE
   ) ;
-- ==========================================
