-- ==========================================

  CREATE TABLE "TREXONE_DATA"."AS2_PEER"
   (	"AS2_PEER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"AS2_NAME_ID" VARCHAR2(128),
	"AS2_URL" VARCHAR2(1000),
	"REQUEST_RECEIPT" CHAR(1) DEFAULT 'Y',
	"RECEIPT_PROTOCOL" CHAR(1) DEFAULT 'S',
	"MDN_URL" VARCHAR2(1000),
	"MIC_ALGORITHM" CHAR(1) DEFAULT 1,
	"IS_ENCRYPTED" CHAR(1) DEFAULT 'Y',
	"IS_SIGNED" CHAR(1) DEFAULT 'Y',
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_AS2_PEER" ON "TREXONE_DATA"."AS2_PEER" ("AS2_PEER_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."AS2_PEER" ADD CONSTRAINT "PK_AS2_PEER" PRIMARY KEY ("AS2_PEER_NUM")
  USING INDEX "TREXONE_DATA"."PK_AS2_PEER"  ENABLE;
-- ==========================================
