-- ==========================================

  CREATE TABLE "TREXONE_DATA"."BATCH_STATUS"
   (	"JOB_NAME" VARCHAR2(200) NOT NULL ENABLE,
	"STATUS_CONTEXT" VARCHAR2(150) NOT NULL ENABLE,
	"COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"STATUS" VARCHAR2(1) NOT NULL ENABLE,
	"DATESTAMP" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
-- ==========================================
