-- ==========================================

  CREATE TABLE "TREXONE_DATA"."BILL_TX"
   (	"BILL_TX_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"BILL_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"BILL_QTY" NUMBER(13,3) NOT NULL ENABLE,
	"ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ITEM_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"IS_VOID" CHAR(1 CHAR),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"BILL_DAYS" NUMBER(9,0),
	 CONSTRAINT "PK_BILL_TX" PRIMARY KEY ("BILL_TX_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_BILL_01" FOREIGN KEY ("BILL_NUM")
	  REFERENCES "TREXONE_DATA"."BILL" ("BILL_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
