-- ==========================================

  CREATE TABLE "TREXONE_DATA"."BILL"
   (	"BILL_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"STATUS" CHAR(1 CHAR) NOT NULL ENABLE,
	"BILL_DATE" DATE NOT NULL ENABLE,
	"DATE_OF_SERVICE" DATE NOT NULL ENABLE,
	"DAYS_SUPPLY" NUMBER(9,3) NOT NULL ENABLE,
	"BILLING_QTY" NUMBER(13,3) NOT NULL ENABLE,
	"BILLING_DAYS" NUMBER(5,0) NOT NULL ENABLE,
	"CARRY_OVER_QTY" NUMBER(13,3) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"TYPE" CHAR(1 CHAR),
	"AUTO_RETRY_LAST_ATTEMPT" DATE,
	"AUTO_RETRY_ATTEMPTS" NUMBER(9,0),
	"PREV_CLAIM_BILL_NUM" NUMBER(18,0),
	"ORIGINAL_CLAIM_BILL_NUM" NUMBER(18,0),
	"AUTO_RETRY_FIRST_ATTEMPT" DATE,
	"BILL_START_DATE" DATE,
	"BILL_END_DATE" DATE,
	"OVERRIDE_USER_NUM" NUMBER(18,0),
	"OVERRIDE_REASON" VARCHAR2(255),
	"OVERRIDE_CARRY_OVER" NUMBER(13,3),
	"OVERRIDE_BILLING_QUANTITY" NUMBER(13,3),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CARRY_OVER_DAYS" NUMBER(9,0),
	"OVERRIDE_DAYS_SUPPLY" NUMBER(9,0),
	"OVERRIDE_CARRY_OVER_DAYS" NUMBER(9,0),
	"BILL_EVENT_SEQ_NUM" NUMBER(3,0),
	 CONSTRAINT "PK_BILL" PRIMARY KEY ("BILL_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_BILL_02" FOREIGN KEY ("PREV_CLAIM_BILL_NUM")
	  REFERENCES "TREXONE_DATA"."BILL" ("BILL_NUM") ENABLE,
	 CONSTRAINT "FK_BILL_03" FOREIGN KEY ("ORIGINAL_CLAIM_BILL_NUM")
	  REFERENCES "TREXONE_DATA"."BILL" ("BILL_NUM") ENABLE,
	 CONSTRAINT "FK_FACILITY_95" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
