-- ==========================================

  CREATE TABLE "TREXONE_DATA"."C1_ITEM_ZONE_AUDIT_DETAIL"
   (	"C1_ITEM_ZONE_AUDIT_DETAIL_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"C1_ITEM_ZONE_AUDIT_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRICE_ZONE_CODE" VARCHAR2(2) NOT NULL ENABLE,
	"OLD_ZONE_RETAIL_PRICE" NUMBER(17,6),
	"ZONE_RETAIL_PRICE" NUMBER(17,6) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_C1_ITEM_ZONE_AUDIT_ITEM_01" FOREIGN KEY ("C1_ITEM_ZONE_AUDIT_ITEM_NUM")
	  REFERENCES "TREXONE_DATA"."C1_ITEM_ZONE_AUDIT_ITEM" ("C1_ITEM_ZONE_AUDIT_ITEM_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_C1_ITEM_ZONE_AUDIT_DETAIL" ON "TREXONE_DATA"."C1_ITEM_ZONE_AUDIT_DETAIL" ("C1_ITEM_ZONE_AUDIT_DETAIL_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."C1_ITEM_ZONE_AUDIT_DETAIL" ADD CONSTRAINT "PK_C1_ITEM_ZONE_AUDIT_DETAIL" PRIMARY KEY ("C1_ITEM_ZONE_AUDIT_DETAIL_NUM")
  USING INDEX "TREXONE_DATA"."PK_C1_ITEM_ZONE_AUDIT_DETAIL"  ENABLE;
-- ==========================================
