-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CA_TAR_DETAILS"
   (	"CA_TAR_DETAILS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TYPE_OF_SERVICE_REQUESTED" VARCHAR2(5),
	"IS_REQUEST_RETROACTIVE" CHAR(1),
	"IS_PATIENT_MEDICARE_ELIGIBLE" CHAR(1),
	"IS_CAL_ELIGIBILITY_PENDING" CHAR(1),
	"PATIENT_STATUS" VARCHAR2(15),
	"ICD9_CODE" VARCHAR2(255),
	"ICD9_DESCRIPTION" VARCHAR2(255),
	"MEDICAL_JUSTIFICATION" VARCHAR2(255),
	"REQUEST_RETROACTIVE_DATE" DATE,
	"DATESTAMP" DATE DEFAULT sysdate NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ITEM_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"ICD_CODE_TYPE" VARCHAR2(10),
	 CONSTRAINT "PK_CA_TAR_DETAILS" PRIMARY KEY ("CA_TAR_DETAILS_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_ITEM_16" FOREIGN KEY ("ORDER_NUM", "ITEM_SEQ")
	  REFERENCES "TREXONE_DATA"."ITEM" ("ORDER_NUM", "ITEM_SEQ") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
