-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CASH_ADDITIONAL_INFO"
   (	"CASH_ADDITIONAL_INFO_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ITEM_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"RX_ORIGINATION_NUM" NUMBER(18,0),
	"USER_DEF_1" VARCHAR2(100),
	"USER_DEF_2" VARCHAR2(100),
	"USER_DEF_3" VARCHAR2(100),
	"DATE_OF_SERVICE" DATE,
	"PATIENT_ALTERNATIVE_ID" VARCHAR2(20),
	"PRIOR_AUTHORIZATION_NUMBER" VARCHAR2(20),
	"PRIOR_AUTH_TYPE" NUMBER(9,0),
	"COUPON_NUMBER" VARCHAR2(15),
	"COUPON_TYPE" VARCHAR2(2),
	"COUPON_VALUE" NUMBER(17,6),
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "REFITEM7541" FOREIGN KEY ("ORDER_NUM", "ITEM_SEQ")
	  REFERENCES "TREXONE_DATA"."ITEM" ("ORDER_NUM", "ITEM_SEQ") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_CASH_ADDITIONAL_INFO" ON "TREXONE_DATA"."CASH_ADDITIONAL_INFO" ("CASH_ADDITIONAL_INFO_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."CASH_ADDITIONAL_INFO" ADD CONSTRAINT "PK_CASH_ADDITIONAL_INFO" PRIMARY KEY ("CASH_ADDITIONAL_INFO_NUM")
  USING INDEX "TREXONE_DATA"."PK_CASH_ADDITIONAL_INFO"  ENABLE;
-- ==========================================
