-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CC_TRANS_COMMAND_TYPE"
   (	"CC_TRANS_COMMAND_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CC_TRANS_REQUEST_TYPE" VARCHAR2(100) NOT NULL ENABLE,
	"CC_TRANS_FUNCTION_TYPE" VARCHAR2(100) NOT NULL ENABLE,
	"CC_TRANS_COMMAND_TYPE" VARCHAR2(100) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_CC_TRANS_COMMAND_TYPE" PRIMARY KEY ("CC_TRANS_COMMAND_TYPE_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
