-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CENTRAL_FILL_RESPONSE"
   (	"CENTRAL_FILL_RESPONSE_NUM" NUMBER(18,0),
	"CF_RESPONSE_MSG" CLOB,
	"TRANSACTION_ID" VARCHAR2(36),
	"CF_REQUEST_NUM" NUMBER(18,0),
	"ADS_RESPONSE_NUM" NUMBER(18,0),
	"RESPONSE_TYPE" VARCHAR2(40),
	"PROCESS_STATUS" VARCHAR2(10),
	"ORDER_NUM" NUMBER(18,0),
	"ITEM_SEQ" VARCHAR2(40),
	"REJECT_CODE" VARCHAR2(10),
	"EXCEPTION_TEXT" VARCHAR2(250),
	"RESHIPMENT_NUM" NUMBER(18,0),
	"ITEM_TYPE" VARCHAR2(30),
	"CF_FACILTIY_IDENTIFIER" VARCHAR2(30),
	"PARTITION_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_CENTRAL_FILL_RESPONSE" PRIMARY KEY ("CENTRAL_FILL_RESPONSE_NUM")
  USING INDEX  ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTOYMINTERVAL(3,'MONTH')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
