-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CF_DELIVERY_METHOD"
   (	"CF_DELIVERY_METHOD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CF_DELIVERY_METHOD_NAME" VARCHAR2(50) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT sysdate NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_CF_DELIVERY_METHOD" PRIMARY KEY ("CF_DELIVERY_METHOD_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_45" FOREIGN KEY ("SYS_USER")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE NOVALIDATE
   ) ;
-- ==========================================
