-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CLAIM_MAX_COVERAGE"
   (	"CLAIM_MAX_COVERAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_ITEM_CLAIM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"COVERAGE_STATUS" CHAR(1),
	"COVERAGE_TYPE" VARCHAR2(1),
	"COVERAGE_SEVERITY" NUMBER(1,0),
	"COVERAGE_TIMEFRAME" VARCHAR2(10),
	"COVERAGE_TIMEFRAME_VALUE" NUMBER(3,0),
	"COVERAGE_EXCEEDED_AMOUNT" NUMBER(17,3),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_TP_ITEM_CLAIM_10" FOREIGN KEY ("TP_ITEM_CLAIM_NUM")
	  REFERENCES "TREXONE_DATA"."TP_ITEM_CLAIM" ("TP_ITEM_CLAIM_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_CLAIM_MAX_COVERAGE" ON "TREXONE_DATA"."CLAIM_MAX_COVERAGE" ("CLAIM_MAX_COVERAGE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."CLAIM_MAX_COVERAGE" ADD CONSTRAINT "PK_CLAIM_MAX_COVERAGE" PRIMARY KEY ("CLAIM_MAX_COVERAGE_NUM")
  USING INDEX "TREXONE_DATA"."PK_CLAIM_MAX_COVERAGE"  ENABLE;
-- ==========================================
