-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CLINICAL_PROGRAM"
   (	"CLINICAL_PROGRAM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PROGRAM_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"PROGRAM_CODE" CHAR(1) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_CLINICAL_PROGRAM" PRIMARY KEY ("CLINICAL_PROGRAM_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "UC_CLINICAL_PROGRAM_01" UNIQUE ("PROGRAM_CODE")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
