-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CLINICAL_PROGRAM_MESSAGE"
   (	"CLINICAL_PROGRAM_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CLINICAL_PROGRAM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PATIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RECEIVE_DATE" DATE NOT NULL ENABLE,
	"READ_DATE" DATE,
	"READ_USER" NUMBER(18,0),
	"PROGRAM_MSG_TEXT" CLOB,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_CLINICAL_PROGRAM_MESSAGE" PRIMARY KEY ("CLINICAL_PROGRAM_MESSAGE_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_CLINICAL_PROGRAM_02" FOREIGN KEY ("CLINICAL_PROGRAM_NUM")
	  REFERENCES "TREXONE_DATA"."CLINICAL_PROGRAM" ("CLINICAL_PROGRAM_NUM") ENABLE,
	 CONSTRAINT "FK_PATIENT_36" FOREIGN KEY ("PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
