-- ==========================================

  CREATE TABLE "TREXONE_DATA"."COMPETITOR_GROUP"
   (	"COMPETITOR_GROUP_NUM" NUMBER(18,0),
	"COMPETITOR_GROUP_CODE" VARCHAR2(15) NOT NULL ENABLE,
	"COMPETITOR_GROUP_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"COMPETITOR_GROUP_STATUS" CHAR(1) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_COMPETITOR_GROUP" PRIMARY KEY ("COMPETITOR_GROUP_NUM")
  USING INDEX  ENABLE
   ) ;
  CREATE INDEX "TREXONE_DATA"."IN_COMPETITOR_GROUP_01" ON "TREXONE_DATA"."COMPETITOR_GROUP" ("COMPETITOR_GROUP_CODE", "ERX_CLIENT_ID")
  ;
ALTER TABLE "TREXONE_DATA"."COMPETITOR_GROUP" ADD CONSTRAINT "UC_COMPETITOR_GROUP_01" UNIQUE ("COMPETITOR_GROUP_CODE", "ERX_CLIENT_ID")
  USING INDEX "TREXONE_DATA"."IN_COMPETITOR_GROUP_01"  ENABLE;
-- ==========================================
