-- ==========================================

  CREATE TABLE "TREXONE_DATA"."COMPETITOR_FACILITY"
   (	"COMPETITOR_FACILITY_NUM" NUMBER(18,0),
	"COMPETITOR_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_COMPETITOR_FACILITY" PRIMARY KEY ("COMPETITOR_FACILITY_NUM")
  USING INDEX  ENABLE
   ) ;
  CREATE INDEX "TREXONE_DATA"."IN_COMPETITOR_FACILITY_01" ON "TREXONE_DATA"."COMPETITOR_FACILITY" ("FACILITY_NUM", "COMPETITOR_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."COMPETITOR_FACILITY" ADD CONSTRAINT "UC_COMPETITOR_FACILITY_01" UNIQUE ("FACILITY_NUM", "COMPETITOR_NUM")
  USING INDEX "TREXONE_DATA"."IN_COMPETITOR_FACILITY_01"  ENABLE;
-- ==========================================
