-- ==========================================

  CREATE TABLE "TREXONE_DATA"."COMPETITOR"
   (	"COMPETITOR_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"COMPETITOR_CODE" VARCHAR2(10) NOT NULL ENABLE,
	"COMPETITOR_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"STATUS" CHAR(1) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ADDRESS1" VARCHAR2(100),
	"ADDRESS2" VARCHAR2(50),
	"CITY" VARCHAR2(40),
	"STATE" VARCHAR2(2),
	"ZIP_CODE" VARCHAR2(10),
	"COUNTRY" VARCHAR2(8),
	"PHONE_EXCHANGE" VARCHAR2(4),
	"AREA_CODE" VARCHAR2(3),
	"PHONE_NUMBER" VARCHAR2(7),
	"PHONE_EXTENSION" VARCHAR2(5),
	"STORE_DEA_NUMBER" VARCHAR2(30),
	"REC_PHARMACIST" VARCHAR2(45),
	"REC_PHARMACIST_LIC_NUM" VARCHAR2(20),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"PHARMACY_LEGAL_NAME" VARCHAR2(30),
	"NCPDP_PROVIDER_ID" VARCHAR2(30),
	"STORE_NPI" VARCHAR2(20),
	"COMPETITOR_GROUP_NUM" NUMBER(18,0),
	"STORE_NUMBER" VARCHAR2(10),
	"FACILITY_NUM" NUMBER(18,0),
	"FAX_AREA_CODE" VARCHAR2(10),
	"FAX_EXCHANGE" VARCHAR2(10),
	"FAX_NUMBER" VARCHAR2(15),
	"FAX_EXTENSION" VARCHAR2(10),
	"IS_EREFERRAL" CHAR(1),
	 CONSTRAINT "FK_COMPETITOR_GROUP_01" FOREIGN KEY ("COMPETITOR_GROUP_NUM")
	  REFERENCES "TREXONE_DATA"."COMPETITOR_GROUP" ("COMPETITOR_GROUP_NUM") ENABLE
   ) ;
  CREATE INDEX "TREXONE_DATA"."IN_COMPETITOR_01" ON "TREXONE_DATA"."COMPETITOR" ("COMPETITOR_NAME", "AREA_CODE", "PHONE_EXCHANGE", "PHONE_NUMBER", "ERX_CLIENT_ID")
  ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_COMPETITOR" ON "TREXONE_DATA"."COMPETITOR" ("COMPETITOR_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."COMPETITOR" ADD CONSTRAINT "PK_COMPETITOR" PRIMARY KEY ("COMPETITOR_NUM")
  USING INDEX "TREXONE_DATA"."PK_COMPETITOR"  ENABLE;
ALTER TABLE "TREXONE_DATA"."COMPETITOR" ADD CONSTRAINT "UC_COMPETITOR_01" UNIQUE ("COMPETITOR_NAME", "AREA_CODE", "PHONE_EXCHANGE", "PHONE_NUMBER", "ERX_CLIENT_ID")
  USING INDEX "TREXONE_DATA"."IN_COMPETITOR_01"  ENABLE NOVALIDATE;
-- ==========================================
