-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CONFIG_VALUE"
   (	"CONFIG_PROPERTY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"VALUE" VARCHAR2(4000),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_CONFIG_PROPERTY_01" FOREIGN KEY ("CONFIG_PROPERTY_NUM")
	  REFERENCES "TREXONE_DATA"."CONFIG_PROPERTY" ("CONFIG_PROPERTY_NUM") ENABLE,
	 CONSTRAINT "FK_DATA_GROUP_01" FOREIGN KEY ("DATA_GROUP")
	  REFERENCES "TREXONE_DATA"."DATA_GROUP" ("DATA_GROUP") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_CONFIG_VALUE" ON "TREXONE_DATA"."CONFIG_VALUE" ("CONFIG_PROPERTY_NUM", "DATA_GROUP")
  ;
ALTER TABLE "TREXONE_DATA"."CONFIG_VALUE" ADD CONSTRAINT "PK_CONFIG_VALUE" PRIMARY KEY ("CONFIG_PROPERTY_NUM", "DATA_GROUP")
  USING INDEX "TREXONE_DATA"."PK_CONFIG_VALUE"  ENABLE;
-- ==========================================
