-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CONFIG_DOCUMENT"
   (	"CONFIG_DOCUMENT_NUM" NUMBER(18,0),
	"DOCUMENT" CLOB NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_CONFIG_DOCUMENT" PRIMARY KEY ("CONFIG_DOCUMENT_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
