-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CONTACT"
   (	"CONTACT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"TYPE" CHAR(10),
	"TITLE" VARCHAR2(64),
	"NAME" VARCHAR2(64),
	"EMAIL" VARCHAR2(64),
	"ADDITIONAL_INFO" VARCHAR2(128),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_CONTACT" PRIMARY KEY ("CONTACT_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
