-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CONTACT_LINK"
   (	"CONTACT_LINK_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"OWNER" NUMBER(18,0) NOT NULL ENABLE,
	"OWNER_TYPE_CODE" CHAR(1) NOT NULL ENABLE,
	"USAGE" NUMBER(18,0) NOT NULL ENABLE,
	"CONTACT_USAGE" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"CONTACT_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_CONTACT_LINK" PRIMARY KEY ("CONTACT_LINK_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
