-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CONTACT_EVENT"
   (	"CONTACT_EVENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CONTACT_EVENT_TYPE_NUM" NUMBER(9,0),
	"WF_PROCESS_DEFINITION_NUM" NUMBER(18,0),
	"PROC_INST_SEQ" NUMBER(18,0),
	"RX_FILL_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"CONTACT_TYPE_NUM" NUMBER(9,0) NOT NULL ENABLE,
	"CONTACT_METHOD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CONTACT_STATUS_NUM" NUMBER(9,0) NOT NULL ENABLE,
	"CONTACT_NAME" VARCHAR2(2000),
	"EVENT_COMMENT" VARCHAR2(2000),
	"INFORM_ON_RESOLUTION" NUMBER(9,0),
	"CREATE_USER" NUMBER(18,0) NOT NULL ENABLE,
	"CREATE_DATE" DATE NOT NULL ENABLE,
	"FOLLOW_UP_TIME" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"CLARIFICATION_REASON_NUM" NUMBER(9,0),
	"FOLLOW_UP_REQUESTS" NUMBER(9,0),
	 CONSTRAINT "FK_RX_FILL_04" FOREIGN KEY ("RX_FILL_SEQ", "RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_FILL" ("RX_FILL_SEQ", "RX_RECORD_NUM") ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_02" FOREIGN KEY ("CREATE_USER")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE,
	 CONSTRAINT "FK_WF_PROCESS_INSTANCE_01" FOREIGN KEY ("WF_PROCESS_DEFINITION_NUM", "PROC_INST_SEQ")
	  REFERENCES "TREXONE_DATA"."WF_PROCESS_INSTANCE" ("WF_PROCESS_DEFINITION_NUM", "PROC_INST_SEQ") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_CONTACT_EVENT" ON "TREXONE_DATA"."CONTACT_EVENT" ("CONTACT_EVENT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."CONTACT_EVENT" ADD CONSTRAINT "PK_CONTACT_EVENT" PRIMARY KEY ("CONTACT_EVENT_NUM")
  USING INDEX "TREXONE_DATA"."PK_CONTACT_EVENT"  ENABLE;
-- ==========================================
