-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CORE_SALES_SUMMARY"
   (	"CF_FACILITY_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"CSS_TP_PLAN_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CSS_SALES_DATE" DATE NOT NULL ENABLE,
	"CSS_TP_PLAN_NAME" VARCHAR2(45) NOT NULL ENABLE,
	"CSS_TRANSACTION_CNT" NUMBER(10,0) NOT NULL ENABLE,
	"CSS_TOTAL_TP_DUE_AMT" NUMBER(18,6) NOT NULL ENABLE,
	"CSS_TOTAL_PATIENT_PAY_AMT" NUMBER(18,6) NOT NULL ENABLE,
	"CSS_TOTAL_REIMBURSEMENT_AMT" NUMBER(18,6) NOT NULL ENABLE,
	"CSS_TOTAL_SALES_TAX_AMT" NUMBER(18,6) NOT NULL ENABLE,
	"LOCK_AVOIDANCE_BUCKET" NUMBER(18,0),
	"CSS_SALES_DATE_LOCAL" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_CORE_SALES_SUMMARY" PRIMARY KEY ("CF_FACILITY_KEY", "CSS_TP_PLAN_NUM", "CSS_SALES_DATE_LOCAL", "LOCK_AVOIDANCE_BUCKET")
  USING INDEX  ENABLE,
	 CONSTRAINT "CK_CORE_SALES_SUMMARY_01" CHECK (CSS_SALES_DATE is not null) ENABLE NOVALIDATE,
	 CONSTRAINT "FK_CORE_FACILITY_4" FOREIGN KEY ("CF_FACILITY_KEY")
	  REFERENCES "TREXONE_DATA"."CORE_FACILITY" ("CF_FACILITY_KEY") ENABLE
   )
  PARTITION BY RANGE ("CSS_SALES_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
