-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CORE_REPORT_DEFINITION"
   (	"CORE_REPORT_DEFINITION_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"REPORT_NAME" VARCHAR2(32) NOT NULL ENABLE,
	"REPORT_RENDER_TYPE" VARCHAR2(16) NOT NULL ENABLE,
	"REPORT_RENDER_DATA" BLOB,
	"REPORT_META_DATA" CLOB,
	"REPORT_QUERY" CLOB,
	"DB_TYPE" VARCHAR2(8) NOT NULL ENABLE,
	"STATUS" VARCHAR2(1) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_CORE_REPORT_DEFINITION" ON "TREXONE_DATA"."CORE_REPORT_DEFINITION" ("CORE_REPORT_DEFINITION_SEQ")
  ;
ALTER TABLE "TREXONE_DATA"."CORE_REPORT_DEFINITION" ADD CONSTRAINT "PK_CORE_REPORT_DEFINITION" PRIMARY KEY ("CORE_REPORT_DEFINITION_SEQ")
  USING INDEX "TREXONE_DATA"."PK_CORE_REPORT_DEFINITION"  ENABLE NOVALIDATE;
-- ==========================================
