-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CORE_CLAIM_SUMMARY"
   (	"FACILITY_NUM" NUMBER(18,0),
	"TP_PLAN_NUM" NUMBER(18,0),
	"ADJUDICATION_DATE" DATE,
	"TP_ID" VARCHAR2(10),
	"TP_NAME" VARCHAR2(45),
	"CLAIM_COUNT" NUMBER,
	"FILL_COUNT" NUMBER,
	"TP_AMT" NUMBER,
	"PATIENT_AMT" NUMBER,
	"PATIENT_TAX_AMT" NUMBER,
	"TP_TAX_AMT" NUMBER,
	"TOTAL_PRICE" NUMBER,
	"LOCK_AVOIDANCE_BUCKET" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_CORE_CLAIM_SUMMARY" PRIMARY KEY ("FACILITY_NUM", "TP_PLAN_NUM", "ADJUDICATION_DATE", "LOCK_AVOIDANCE_BUCKET")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_FACILITY_91" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_TP_PLAN_10" FOREIGN KEY ("TP_PLAN_NUM")
	  REFERENCES "TREXONE_DATA"."TP_PLAN" ("TP_PLAN_NUM") ENABLE
   ) ;
-- ==========================================
