-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CORE_RX_XFER"
   (	"CF_FACILITY_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"CRX_LAST_TOT_PATIENT_PMT" NUMBER NOT NULL ENABLE,
	"CRX_PATIENT_LAST_NAME" VARCHAR2(30),
	"CRX_PATIENT_FIRST_NAME" VARCHAR2(30),
	"CRX_PATIENT_MIDDLE_NAME" VARCHAR2(30),
	"CRX_PATIENT_PHONE_NUM" VARCHAR2(20),
	"CRX_PRES_FIRST_NAME" VARCHAR2(30),
	"CRX_PRES_LAST_NAME" VARCHAR2(30),
	"CRX_PRES_MIDDLE_NAME" VARCHAR2(30),
	"CRX_PRODUCT_NAME" VARCHAR2(40),
	"CRX_PRODUCT_NDC" VARCHAR2(20),
	"CRX_PRODUCT_MFG" VARCHAR2(30),
	"CRX_PRODUCT_SCHEDULE" VARCHAR2(10),
	"CRX_PRODUCT_STRENGTH" VARCHAR2(30),
	"CRX_LAST_FILL_DATE" DATE,
	"CRX_TOTAL_PATIENT_AMOUNT_DUE" NUMBER,
	"CRX_REFILLS_REMAINING" NUMBER,
	"CRX_QUANTITY_REMAINING" NUMBER,
	"CRX_TRANSFER_METHOD" VARCHAR2(12),
	"CRX_TRANSFER_TYPE" VARCHAR2(1),
	"CRX_SINGLE_ENTIRE" VARCHAR2(1),
	"CRX_FACILITY_NAME" VARCHAR2(50),
	"CRX_FACILITY_ADDRESS1" VARCHAR2(100),
	"CRX_FACILITY_ADDRESS2" VARCHAR2(50),
	"CRX_FACILITY_CITY" VARCHAR2(40),
	"CRX_FACILITY_STATE_CODE" VARCHAR2(2),
	"CRX_FACILITY_POSTAL" VARCHAR2(10),
	"CRX_FACILITY_CTRY_CODE" VARCHAR2(8),
	"CRX_FACILITY_PHONE" VARCHAR2(15),
	"CRX_FACILITY_DEA_NUM" VARCHAR2(30),
	"CRX_LOCAL_PHARMACIST_NAME" VARCHAR2(45),
	"CRX_REMOTE_PHARMACIST_NAME" VARCHAR2(45),
	"CRX_COMPETITOR_PRICE" NUMBER,
	"CRX_TRANSFER_DATE" DATE,
	"CRX_TRANSFER_MONTH" DATE NOT NULL ENABLE,
	"CRX_TRANSFER_QTR" VARCHAR2(6) NOT NULL ENABLE,
	"CRX_RX_NUMBER" VARCHAR2(20),
	"CRX_FACILITY_STORE_NUM" CHAR(6),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"CRX_FACILITY_ID" VARCHAR2(10),
	 CONSTRAINT "FK_CORE_FACILITY_2" FOREIGN KEY ("CF_FACILITY_KEY")
	  REFERENCES "TREXONE_DATA"."CORE_FACILITY" ("CF_FACILITY_KEY") ENABLE
   )
  PARTITION BY RANGE ("CRX_LAST_FILL_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
