-- ==========================================

  CREATE TABLE "TREXONE_DATA"."COST_BASIS_SOURCE"
   (	"COST_BASIS_SOURCE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(65) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(255),
	"PROVIDER" VARCHAR2(30),
	"IS_UNIT_COST" CHAR(1),
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_COST_BASIS_SOURCE" ON "TREXONE_DATA"."COST_BASIS_SOURCE" ("COST_BASIS_SOURCE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."COST_BASIS_SOURCE" ADD CONSTRAINT "PK_COST_BASIS_SOURCE" PRIMARY KEY ("COST_BASIS_SOURCE_NUM")
  USING INDEX "TREXONE_DATA"."PK_COST_BASIS_SOURCE"  ENABLE;
-- ==========================================
