-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CPS_PATIENT_STATUS"
   (	"CPS_PATIENT_STATUS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CPS_PROGRAM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"GLOBAL_PATIENT_ID" VARCHAR2(100) NOT NULL ENABLE,
	"STATUS" VARCHAR2(30) NOT NULL ENABLE,
	"LAST_UPDATED" DATE,
	"UPDATED_BY" VARCHAR2(50),
	"PATIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_CPS_PATIENT_STATUS" PRIMARY KEY ("CPS_PATIENT_STATUS_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_CPS_PROGRAM_01" FOREIGN KEY ("CPS_PROGRAM_NUM")
	  REFERENCES "TREXONE_DATA"."CPS_PROGRAM" ("CPS_PROGRAM_NUM") ENABLE,
	 CONSTRAINT "FK_PATIENT_37" FOREIGN KEY ("PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE
   ) ;
-- ==========================================
