-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CPS_PROGRAM"
   (	"CPS_PROGRAM_NUM" NUMBER(18,0),
	"NAME" VARCHAR2(60),
	"TAG" VARCHAR2(30),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_CPS_PROGRAM" PRIMARY KEY ("CPS_PROGRAM_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
