-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CS_VERIFICATION_REPORT"
   (	"CS_VERIFICATION_REPORT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"VERIFICATION_REPORT" CLOB NOT NULL ENABLE,
	"STATE_CODE" VARCHAR2(2) NOT NULL ENABLE,
	"DATE_GENERATED" DATE NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FILENAME" VARCHAR2(512),
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_CS_VERIFICATION_REPORT" PRIMARY KEY ("CS_VERIFICATION_REPORT_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_FACILITY_88" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE
   ) ;
-- ==========================================
