-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CSR_PROPERTY_VALUE"
   (	"CSR_PROPERTY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CSR_STATE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"VALUE" CLOB,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT sysdate NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_CSR_PROPERTY_01" FOREIGN KEY ("CSR_PROPERTY_NUM")
	  REFERENCES "TREXONE_DATA"."CSR_PROPERTY" ("CSR_PROPERTY_NUM") ENABLE,
	 CONSTRAINT "FK_CSR_STATE_03" FOREIGN KEY ("CSR_STATE_NUM")
	  REFERENCES "TREXONE_DATA"."CSR_STATE" ("CSR_STATE_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_CSR_PROPERTY_VALUE" ON "TREXONE_DATA"."CSR_PROPERTY_VALUE" ("CSR_PROPERTY_NUM", "CSR_STATE_NUM", "ERX_CLIENT_ID")
  ;
ALTER TABLE "TREXONE_DATA"."CSR_PROPERTY_VALUE" ADD CONSTRAINT "PK_CSR_PROPERTY_VALUE" PRIMARY KEY ("CSR_PROPERTY_NUM", "CSR_STATE_NUM", "ERX_CLIENT_ID")
  USING INDEX "TREXONE_DATA"."PK_CSR_PROPERTY_VALUE"  ENABLE;
-- ==========================================
