-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CSR_STATE_REPORTING_RULE"
   (	"CSR_STATE_RPRT_RULE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CSR_STATE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PROCESS_ORDER" NUMBER(9,0) NOT NULL ENABLE,
	"IS_INCLUDED" CHAR(1) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATA_FILTER" CLOB NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_CSR_STATE_02" FOREIGN KEY ("CSR_STATE_NUM")
	  REFERENCES "TREXONE_DATA"."CSR_STATE" ("CSR_STATE_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_CSR_STATE_REPORTING_RULE" ON "TREXONE_DATA"."CSR_STATE_REPORTING_RULE" ("CSR_STATE_RPRT_RULE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."CSR_STATE_REPORTING_RULE" ADD CONSTRAINT "PK_CSR_STATE_REPORTING_RULE" PRIMARY KEY ("CSR_STATE_RPRT_RULE_NUM")
  USING INDEX "TREXONE_DATA"."PK_CSR_STATE_REPORTING_RULE"  ENABLE;
-- ==========================================
