-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CSR_STATE_FIELD_RULE"
   (	"CSR_STATE_FIELD_RULE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CSR_STATE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CSR_FIELD_NUM" NUMBER(9,0) NOT NULL ENABLE,
	"MESSAGE_TEXT" VARCHAR2(255),
	"REQ_OPT_NOT" CHAR(1) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATA_FILTER" CLOB,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_CSR_STATE_01" FOREIGN KEY ("CSR_STATE_NUM")
	  REFERENCES "TREXONE_DATA"."CSR_STATE" ("CSR_STATE_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_CSR_STATE_FIELD_RULE" ON "TREXONE_DATA"."CSR_STATE_FIELD_RULE" ("CSR_STATE_FIELD_RULE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."CSR_STATE_FIELD_RULE" ADD CONSTRAINT "PK_CSR_STATE_FIELD_RULE" PRIMARY KEY ("CSR_STATE_FIELD_RULE_NUM")
  USING INDEX "TREXONE_DATA"."PK_CSR_STATE_FIELD_RULE"  ENABLE;
-- ==========================================
