-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CVS_PRODUCT_XREF"
   (	"CVS_PRODUCT_XREF_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRODUCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NDC" VARCHAR2(11) NOT NULL ENABLE,
	"GCN_SEQ_NUM" VARCHAR2(30) NOT NULL ENABLE,
	"STORE_PACKAGE_SIZE" NUMBER(16,8),
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE,
	"TERM_DATE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PRODUCT_04" FOREIGN KEY ("PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT" ("PRODUCT_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_CVS_PRODUCT_XREF" ON "TREXONE_DATA"."CVS_PRODUCT_XREF" ("CVS_PRODUCT_XREF_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."CVS_PRODUCT_XREF" ADD CONSTRAINT "PK_CVS_PRODUCT_XREF" PRIMARY KEY ("CVS_PRODUCT_XREF_NUM")
  USING INDEX "TREXONE_DATA"."PK_CVS_PRODUCT_XREF"  ENABLE;
-- ==========================================
