-- ==========================================

  CREATE TABLE "TREXONE_DATA"."D_GENERICS_PROGRAM"
   (	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRODUCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_D_GENERICS_PROGRAM" PRIMARY KEY ("FACILITY_NUM", "PRODUCT_NUM", "ERX_CLIENT_ID")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
