-- ==========================================

  CREATE TABLE "TREXONE_DATA"."D_INV_PRIMARY_VENDOR"
   (	"INVENTORY_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRIMARY_VENDOR_NUM" NUMBER(18,0),
	"PRODUCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID'),
	 CONSTRAINT "PK_D_INV_PRIMARY_VENDOR" PRIMARY KEY ("INVENTORY_ITEM_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
