-- ==========================================

  CREATE TABLE "TREXONE_DATA"."D_PRESCRIBER"
   (	"PRESCRIBER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACTIVE_PRESCRIBER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SOURCE_NUM" NUMBER(18,0),
	"STATUS" CHAR(1) NOT NULL ENABLE,
	"INACTIVITY_CODE" VARCHAR2(4),
	"INACTIVE_STATUS_DATE" DATE,
	"TITLE_ABBR" VARCHAR2(10),
	"SALUTATION_ABBR" VARCHAR2(10),
	"FIRST_NAME" VARCHAR2(30),
	"MIDDLE_NAME" VARCHAR2(30),
	"LAST_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"NAME_SUFFIX_ABBR" VARCHAR2(10),
	"GENDER_CODE" VARCHAR2(1),
	"SPECIALTY_1" VARCHAR2(20),
	"SPECIALTY_2" VARCHAR2(20),
	"SPECIALTY_3" VARCHAR2(20),
	"PROFESSIONAL_ACTIVITY" VARCHAR2(20),
	"DECEASED_DATE" DATE,
	"EMAIL_ADDRESS" VARCHAR2(256),
	"PREF_GENERIC_IF_AVAIL" CHAR(1),
	"PREF_THERAPEUTIC_SUB" CHAR(1),
	"PREFERRED_CONTACT_METHOD" NUMBER(18,0),
	"VALIDATED" CHAR(1),
	"CREATE_DATE" DATE,
	"PRESCRIBER_TYPE" VARCHAR2(4),
	"PRESCRIBER_NUM_UPDATES" NUMBER(18,0) NOT NULL ENABLE,
	"OWNER_NUM_UPDATES" NUMBER(18,0),
	"LAST_UPDATED_BY" NUMBER(18,0),
	"LAST_UPDATED_ON" DATE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"SOURCE_CODE" CHAR(1),
	"LICENSE_STATUS" CHAR(1),
	"SPECIALTY_4" VARCHAR2(20),
	"SPECIALTY_5" VARCHAR2(20),
	"ON_HOLD" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"INTERNALLY_VALIDATED" CHAR(1),
	"ESV_PRESCRIBER_ID" VARCHAR2(50),
	"REACTIVATE_DATE" DATE,
	"HAS_ESV_PRESCRIBER_ID" CHAR(1) GENERATED ALWAYS AS (DECODE("ESV_PRESCRIBER_ID",NULL,'N','Y')) VIRTUAL  NOT NULL ENABLE,
	"ESV_MATCHED_IND" CHAR(1)
   ) ;
  CREATE INDEX "TREXONE_DATA"."PK_D_PRESCRIBER" ON "TREXONE_DATA"."D_PRESCRIBER" ("PRESCRIBER_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."D_PRESCRIBER" ADD CONSTRAINT "PK_D_PRESCRIBER" PRIMARY KEY ("PRESCRIBER_NUM")
  USING INDEX "TREXONE_DATA"."PK_D_PRESCRIBER"  ENABLE;
-- ==========================================
