-- ==========================================

  CREATE TABLE "TREXONE_DATA"."D_PRESCRIBER_PHONE"
   (	"PRESCRIBER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRESCRIBER_PHONE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PHONE_LINK_NUM" NUMBER(18,0),
	"PHONE_NUM" NUMBER(18,0),
	"SOURCE" NUMBER(18,0),
	"PHONE_TYPE" VARCHAR2(4),
	"AREA_CODE" VARCHAR2(4),
	"PHONE_NUMBER" VARCHAR2(20),
	"EXT" VARCHAR2(6),
	"STATUS" VARCHAR2(1) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(18,0) NOT NULL ENABLE,
	"LINK_NUM_UPDATES" NUMBER(18,0),
	"PHONE_NUM_UPDATES" NUMBER(18,0),
	"DATESTAMP" DATE NOT NULL ENABLE,
	"SOURCE_CODE" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"REACTIVATE_DATE" DATE
   ) ;
  CREATE INDEX "TREXONE_DATA"."PK_D_PRESCRIBER_PHONE" ON "TREXONE_DATA"."D_PRESCRIBER_PHONE" ("PRESCRIBER_NUM", "PRESCRIBER_PHONE_NUM", "PHONE_NUMBER")
  ;
ALTER TABLE "TREXONE_DATA"."D_PRESCRIBER_PHONE" ADD CONSTRAINT "PK_D_PRESCRIBER_PHONE" PRIMARY KEY ("PRESCRIBER_NUM", "PRESCRIBER_PHONE_NUM")
  USING INDEX "TREXONE_DATA"."PK_D_PRESCRIBER_PHONE"  ENABLE;
-- ==========================================
