-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DATA_TRANSFER_STATUS"
   (	"DATA_TRANSFER_STATUS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"STATUS" VARCHAR2(50) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PKDATA_TRANSFER_STATUS" ON "TREXONE_DATA"."DATA_TRANSFER_STATUS" ("DATA_TRANSFER_STATUS_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DATA_TRANSFER_STATUS" ADD CONSTRAINT "PKDATA_TRANSFER_STATUS" PRIMARY KEY ("DATA_TRANSFER_STATUS_NUM")
  USING INDEX "TREXONE_DATA"."PKDATA_TRANSFER_STATUS"  ENABLE;
-- ==========================================
