-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DATA_TRANSFER_TYPE"
   (	"DATA_TRANSFER_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TRANSFER_TYPE" VARCHAR2(50) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PKDATA_TRANSFER_TYPE" ON "TREXONE_DATA"."DATA_TRANSFER_TYPE" ("DATA_TRANSFER_TYPE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DATA_TRANSFER_TYPE" ADD CONSTRAINT "PKDATA_TRANSFER_TYPE" PRIMARY KEY ("DATA_TRANSFER_TYPE_NUM")
  USING INDEX "TREXONE_DATA"."PKDATA_TRANSFER_TYPE"  ENABLE;
-- ==========================================
