-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DATA_GROUP_NUMBER_VALUE"
   (	"DATA_GROUP_NUMBER_VALUE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"TYPE_ID" NUMBER(9,0) NOT NULL ENABLE,
	"VALUE" VARCHAR2(30) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_DATA_GROUP_NUMBER_VALUE" PRIMARY KEY ("DATA_GROUP_NUMBER_VALUE_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
