-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DATA_TRANSFER"
   (	"DATA_TRANSFER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RUN_DATE" DATE NOT NULL ENABLE,
	"START_DATE_CRITERIA" DATE,
	"END_DATE_CRITERIA" DATE,
	"SOURCE" VARCHAR2(50),
	"TARGET" VARCHAR2(50),
	"PROCESS_ID" NUMBER(18,0),
	"DATA_TRANSFER_STATUS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DATA_TRANSFER_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DATA_TRANSFER_STATUS_01" FOREIGN KEY ("DATA_TRANSFER_STATUS_NUM")
	  REFERENCES "TREXONE_DATA"."DATA_TRANSFER_STATUS" ("DATA_TRANSFER_STATUS_NUM") ENABLE,
	 CONSTRAINT "FK_DATA_TRANSFER_TYPE_01" FOREIGN KEY ("DATA_TRANSFER_TYPE_NUM")
	  REFERENCES "TREXONE_DATA"."DATA_TRANSFER_TYPE" ("DATA_TRANSFER_TYPE_NUM") ENABLE,
	 CONSTRAINT "FK_FACILITY_63" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PKDATA_TRANSFER" ON "TREXONE_DATA"."DATA_TRANSFER" ("DATA_TRANSFER_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DATA_TRANSFER" ADD CONSTRAINT "PKDATA_TRANSFER" PRIMARY KEY ("DATA_TRANSFER_NUM")
  USING INDEX "TREXONE_DATA"."PKDATA_TRANSFER"  ENABLE;
-- ==========================================
