-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DEFAULT_SPEC_PROG_TYPE"
   (	"DEFAULT_SPEC_PROG_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SPECIALTY_ID_PARAM_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	"SPECIALTY_PROGRAM_GROUP_NUM" NUMBER(18,0),
	 CONSTRAINT "DEFAULT_SPEC_PROG_TYPE_PK" PRIMARY KEY ("DEFAULT_SPEC_PROG_TYPE_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "DEFAULT_SPEC_PROG_TYPE_FK01" FOREIGN KEY ("SPECIALTY_ID_PARAM_TYPE_NUM")
	  REFERENCES "TREXONE_DATA"."SPECIALTY_ID_PARAM_TYPE" ("SPECIALTY_ID_PARAM_TYPE_NUM") ENABLE,
	 CONSTRAINT "DEFAULT_SPEC_PROG_TYPE_FK02" FOREIGN KEY ("SPECIALTY_PROGRAM_GROUP_NUM")
	  REFERENCES "TREXONE_DATA"."SPECIALTY_PROGRAM_GROUP" ("SPECIALTY_PROGRAM_GROUP_NUM") ENABLE
   ) ;
-- ==========================================
