-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DELIVERY_METHOD"
   (	"DELIVERY_METHOD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(45) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE INDEX "TREXONE_DATA"."PK_DELIVERY_METHOD" ON "TREXONE_DATA"."DELIVERY_METHOD" ("DELIVERY_METHOD_NUM", "DESCRIPTION")
  ;
ALTER TABLE "TREXONE_DATA"."DELIVERY_METHOD" ADD CONSTRAINT "PK_DELIVERY_METHOD" PRIMARY KEY ("DELIVERY_METHOD_NUM")
  USING INDEX "TREXONE_DATA"."PK_DELIVERY_METHOD"  ENABLE;
-- ==========================================
