-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DELIVERY_ROUTE"
   (	"DELIVERY_ROUTE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DELIVERY_ROUTE_ID" VARCHAR2(7) NOT NULL ENABLE,
	"DELIVERY_ROUTE_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"DEPARTURE_TIME" NUMBER(4,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"IS_MONDAY" CHAR(1),
	"IS_TUESDAY" CHAR(1),
	"IS_WEDNESDAY" CHAR(1),
	"IS_THURSDAY" CHAR(1),
	"IS_FRIDAY" CHAR(1),
	"IS_SATURDAY" CHAR(1),
	"IS_SUNDAY" CHAR(1),
	"IS_ACTIVE" CHAR(1) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_FACILITY_72" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DELIVERY_ROUTE" ON "TREXONE_DATA"."DELIVERY_ROUTE" ("DELIVERY_ROUTE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DELIVERY_ROUTE" ADD CONSTRAINT "PK_DELIVERY_ROUTE" PRIMARY KEY ("DELIVERY_ROUTE_NUM")
  USING INDEX "TREXONE_DATA"."PK_DELIVERY_ROUTE"  ENABLE;
-- ==========================================
