-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DELIVERY_STOP"
   (	"DELIVERY_STOP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DELIVERY_ROUTE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DELIVERY_TIME" NUMBER(4,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"IS_ACTIVE" CHAR(1) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DELIVERY_ROUTE_1" FOREIGN KEY ("DELIVERY_ROUTE_NUM")
	  REFERENCES "TREXONE_DATA"."DELIVERY_ROUTE" ("DELIVERY_ROUTE_NUM") ENABLE,
	 CONSTRAINT "FK_FACILITY_73" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DELIVERY_STOP" ON "TREXONE_DATA"."DELIVERY_STOP" ("DELIVERY_STOP_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DELIVERY_STOP" ADD CONSTRAINT "PK_DELIVERY_STOP" PRIMARY KEY ("DELIVERY_STOP_NUM")
  USING INDEX "TREXONE_DATA"."PK_DELIVERY_STOP"  ENABLE;
-- ==========================================
