-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DEVICE_PREFERENCE"
   (	"DEVICE_PREFERENCE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DEVICE_COMPONENT_NUM" NUMBER(10,0),
	"DEVICE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DEVICE_CONTEXT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CLIENT_LOCATION_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ORDER_OF_PREFERENCE" NUMBER(3,0) NOT NULL ENABLE,
	"ENABLED" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_CLIENT_LOCATION_02" FOREIGN KEY ("CLIENT_LOCATION_NUM")
	  REFERENCES "TREXONE_DATA"."CLIENT_LOCATION" ("CLIENT_LOCATION_NUM") ENABLE,
	 CONSTRAINT "FK_DEVICE_02" FOREIGN KEY ("DEVICE_NUM")
	  REFERENCES "TREXONE_DATA"."DEVICE" ("DEVICE_NUM") ENABLE,
	 CONSTRAINT "FK_DEVICE_COMPONENT_01" FOREIGN KEY ("DEVICE_COMPONENT_NUM")
	  REFERENCES "TREXONE_DATA"."DEVICE_COMPONENT" ("DEVICE_COMPONENT_NUM") ENABLE,
	 CONSTRAINT "FK_DEVICE_CONTEXT_01" FOREIGN KEY ("DEVICE_CONTEXT_NUM")
	  REFERENCES "TREXONE_DATA"."DEVICE_CONTEXT" ("DEVICE_CONTEXT_NUM") ENABLE,
	 CONSTRAINT "FK_FACILITY_54" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DEVICE_PREFERENCE" ON "TREXONE_DATA"."DEVICE_PREFERENCE" ("DEVICE_PREFERENCE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DEVICE_PREFERENCE" ADD CONSTRAINT "PK_DEVICE_PREFERENCE" PRIMARY KEY ("DEVICE_PREFERENCE_NUM")
  USING INDEX "TREXONE_DATA"."PK_DEVICE_PREFERENCE"  ENABLE;
-- ==========================================
