-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DEVICE_FACILITY"
   (	"DEVICE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DEVICE_04" FOREIGN KEY ("DEVICE_NUM")
	  REFERENCES "TREXONE_DATA"."DEVICE" ("DEVICE_NUM") ENABLE,
	 CONSTRAINT "FK_FACILITY_53" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DEVICE_FACILITY" ON "TREXONE_DATA"."DEVICE_FACILITY" ("DEVICE_NUM", "FACILITY_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DEVICE_FACILITY" ADD CONSTRAINT "PK_DEVICE_FACILITY" PRIMARY KEY ("DEVICE_NUM", "FACILITY_NUM")
  USING INDEX "TREXONE_DATA"."PK_DEVICE_FACILITY"  ENABLE;
-- ==========================================
