-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DEVICE_CLIENT_LOCATION"
   (	"DEVICE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CLIENT_LOCATION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"MAC_KEY" VARCHAR2(50),
	"MAC_LABEL" VARCHAR2(50),
	 CONSTRAINT "FK_CLIENT_LOCATION_03" FOREIGN KEY ("CLIENT_LOCATION_NUM")
	  REFERENCES "TREXONE_DATA"."CLIENT_LOCATION" ("CLIENT_LOCATION_NUM") ENABLE,
	 CONSTRAINT "FK_DEVICE_FACILITY_01" FOREIGN KEY ("DEVICE_NUM", "FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."DEVICE_FACILITY" ("DEVICE_NUM", "FACILITY_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DEVICE_CLIENT_LOCATION" ON "TREXONE_DATA"."DEVICE_CLIENT_LOCATION" ("DEVICE_NUM", "FACILITY_NUM", "CLIENT_LOCATION_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DEVICE_CLIENT_LOCATION" ADD CONSTRAINT "PK_DEVICE_CLIENT_LOCATION" PRIMARY KEY ("DEVICE_NUM", "FACILITY_NUM", "CLIENT_LOCATION_NUM")
  USING INDEX "TREXONE_DATA"."PK_DEVICE_CLIENT_LOCATION"  ENABLE;
-- ==========================================
