-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DISPENSING_EVENT"
   (	"ITEM_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DISPENSING_EVENT_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"DISPENSING_SERVICE_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"DISPENSING_TEMPLATE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"INVENTORY_ADJUSTMENT_NUM" NUMBER(18,0),
	"DISPENSING_PROFILE_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"IS_SUCCESSFUL" CHAR(1) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"REQUEST_UID" CHAR(36),
	"REQUEST_TYPE" CHAR(8),
	 CONSTRAINT "FK_DISPENSING_PROFILE_01" FOREIGN KEY ("DISPENSING_TEMPLATE_NUM", "DISPENSING_PROFILE_SEQ")
	  REFERENCES "TREXONE_DATA"."DISPENSING_PROFILE" ("DISPENSING_TEMPLATE_NUM", "DISPENSING_PROFILE_SEQ") ENABLE,
	 CONSTRAINT "FK_DISPENSING_SERVICE_01" FOREIGN KEY ("DISPENSING_SERVICE_SEQ", "DISPENSING_TEMPLATE_NUM")
	  REFERENCES "TREXONE_DATA"."DISPENSING_SERVICE" ("DISPENSING_SERVICE_SEQ", "DISPENSING_TEMPLATE_NUM") ENABLE,
	 CONSTRAINT "FK_ITEM_02" FOREIGN KEY ("ORDER_NUM", "ITEM_SEQ")
	  REFERENCES "TREXONE_DATA"."ITEM" ("ORDER_NUM", "ITEM_SEQ") ENABLE,
	 CONSTRAINT "FK_INVENTORY_ADJUSTMENT_01" FOREIGN KEY ("INVENTORY_ADJUSTMENT_NUM")
	  REFERENCES "TREXONE_DATA"."INVENTORY_ADJUSTMENT" ("INVENTORY_ADJUSTMENT_NUM") ENABLE NOVALIDATE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DISPENSING_EVENT" ON "TREXONE_DATA"."DISPENSING_EVENT" ("ITEM_SEQ", "ORDER_NUM", "DISPENSING_EVENT_SEQ")
  ;
ALTER TABLE "TREXONE_DATA"."DISPENSING_EVENT" ADD CONSTRAINT "PK_DISPENSING_EVENT" PRIMARY KEY ("ITEM_SEQ", "ORDER_NUM", "DISPENSING_EVENT_SEQ")
  USING INDEX "TREXONE_DATA"."PK_DISPENSING_EVENT"  ENABLE;
-- ==========================================
