-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DISPENSING_TEMPLATE"
   (	"DISPENSING_TEMPLATE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TEMPLATE_NAME" VARCHAR2(45) NOT NULL ENABLE,
	"TEMPLATE_DESCRIPTION" VARCHAR2(255),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DISPENSING_TEMPLATE" ON "TREXONE_DATA"."DISPENSING_TEMPLATE" ("DISPENSING_TEMPLATE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DISPENSING_TEMPLATE" ADD CONSTRAINT "PK_DISPENSING_TEMPLATE" PRIMARY KEY ("DISPENSING_TEMPLATE_NUM")
  USING INDEX "TREXONE_DATA"."PK_DISPENSING_TEMPLATE"  ENABLE;
-- ==========================================
