-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DISPENSING_SERVICE"
   (	"DISPENSING_SERVICE_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"DISPENSING_TEMPLATE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DISPENSING_SERVICE_NAME" VARCHAR2(45),
	"DESCRIPTION" VARCHAR2(255),
	"MESSAGE_FORMAT_TYPE" VARCHAR2(45),
	"SERVICE_TYPE" VARCHAR2(45),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DISPENSING_TEMPLATE_02" FOREIGN KEY ("DISPENSING_TEMPLATE_NUM")
	  REFERENCES "TREXONE_DATA"."DISPENSING_TEMPLATE" ("DISPENSING_TEMPLATE_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DISPENSING_SERVICE" ON "TREXONE_DATA"."DISPENSING_SERVICE" ("DISPENSING_SERVICE_SEQ", "DISPENSING_TEMPLATE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DISPENSING_SERVICE" ADD CONSTRAINT "PK_DISPENSING_SERVICE" PRIMARY KEY ("DISPENSING_SERVICE_SEQ", "DISPENSING_TEMPLATE_NUM")
  USING INDEX "TREXONE_DATA"."PK_DISPENSING_SERVICE"  ENABLE;
-- ==========================================
