-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DISPENSING_CELL_ASSIGNMENT"
   (	"DISPENSING_CELL_ASSIGNMENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DISPENSING_PROFILE_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"INVENTORY_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CELL" VARCHAR2(30) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "DISPENSING_CELL_ASSIGNMENT_PK" PRIMARY KEY ("DISPENSING_CELL_ASSIGNMENT_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "DISPENSING_CELL_ASSGNMNT_UIDX" UNIQUE ("DISPENSING_PROFILE_SEQ", "INVENTORY_ITEM_NUM", "ERX_CLIENT_ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "DISPENSING_CELL_ASSGNMNT_FK01" FOREIGN KEY ("DISPENSING_PROFILE_SEQ")
	  REFERENCES "TREXONE_DATA"."DISPENSING_PROFILE" ("DISPENSING_PROFILE_SEQ") ENABLE,
	 CONSTRAINT "DISPENSING_CELL_ASSGNMNT_FK02" FOREIGN KEY ("INVENTORY_ITEM_NUM")
	  REFERENCES "TREXONE_DATA"."INVENTORY_ITEM" ("INVENTORY_ITEM_NUM") ENABLE
   ) ;
-- ==========================================
