-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DISPENSING_EVENT_LOG"
   (	"ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ITEM_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"DISPENSING_EVENT_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"COMMENT_SEQUENCE" NUMBER(18,0) NOT NULL ENABLE,
	"COMMENT_TEXT" VARCHAR2(255),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DISPENSING_EVENT_01" FOREIGN KEY ("ITEM_SEQ", "ORDER_NUM", "DISPENSING_EVENT_SEQ")
	  REFERENCES "TREXONE_DATA"."DISPENSING_EVENT" ("ITEM_SEQ", "ORDER_NUM", "DISPENSING_EVENT_SEQ") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DISPENSING_EVENT_LOG" ON "TREXONE_DATA"."DISPENSING_EVENT_LOG" ("ORDER_NUM", "ITEM_SEQ", "DISPENSING_EVENT_SEQ", "COMMENT_SEQUENCE")
  ;
ALTER TABLE "TREXONE_DATA"."DISPENSING_EVENT_LOG" ADD CONSTRAINT "PK_DISPENSING_EVENT_LOG" PRIMARY KEY ("ORDER_NUM", "ITEM_SEQ", "DISPENSING_EVENT_SEQ", "COMMENT_SEQUENCE")
  USING INDEX "TREXONE_DATA"."PK_DISPENSING_EVENT_LOG"  ENABLE;
-- ==========================================
