-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DISPENSING_PROFILE"
   (	"DISPENSING_TEMPLATE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DISPENSING_PROFILE_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"LOCATION_GROUP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PROFILE_NAME" VARCHAR2(45) NOT NULL ENABLE,
	"PRIORITY" NUMBER(9,0),
	"IS_LABEL_PRINT" CHAR(1),
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"IS_ACTIVE" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "DISPENSING_PROFILE_UK01" UNIQUE ("DISPENSING_PROFILE_SEQ")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_DISPENSING_TEMPLATE_01" FOREIGN KEY ("DISPENSING_TEMPLATE_NUM")
	  REFERENCES "TREXONE_DATA"."DISPENSING_TEMPLATE" ("DISPENSING_TEMPLATE_NUM") ENABLE,
	 CONSTRAINT "FK_LOCATION_GROUP_01" FOREIGN KEY ("LOCATION_GROUP_NUM")
	  REFERENCES "TREXONE_DATA"."LOCATION_GROUP" ("LOCATION_GROUP_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DISPENSING_PROFILE" ON "TREXONE_DATA"."DISPENSING_PROFILE" ("DISPENSING_TEMPLATE_NUM", "DISPENSING_PROFILE_SEQ")
  ;
ALTER TABLE "TREXONE_DATA"."DISPENSING_PROFILE" ADD CONSTRAINT "PK_DISPENSING_PROFILE" PRIMARY KEY ("DISPENSING_TEMPLATE_NUM", "DISPENSING_PROFILE_SEQ")
  USING INDEX "TREXONE_DATA"."PK_DISPENSING_PROFILE"  ENABLE;
-- ==========================================
