-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DOC_GROUP_SIZE"
   (	"DOC_GROUP_SIZE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DOC_CONTENT_PROVIDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"WIDTH" NUMBER(8,5),
	"HEIGHT" NUMBER(8,5),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(32),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DOC_CONTENT_PROVIDER_02" FOREIGN KEY ("DOC_CONTENT_PROVIDER_NUM")
	  REFERENCES "TREXONE_DATA"."DOC_CONTENT_PROVIDER" ("DOC_CONTENT_PROVIDER_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DOC_GROUP_SIZE" ON "TREXONE_DATA"."DOC_GROUP_SIZE" ("DOC_GROUP_SIZE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DOC_GROUP_SIZE" ADD CONSTRAINT "PK_DOC_GROUP_SIZE" PRIMARY KEY ("DOC_GROUP_SIZE_NUM")
  USING INDEX "TREXONE_DATA"."PK_DOC_GROUP_SIZE"  ENABLE;
-- ==========================================
