-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DOC_FORMAT"
   (	"DOC_FORMAT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DOC_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRINT_DEVICE_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ORDER_OF_PREFERENCE" NUMBER(3,0),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"SOFT_FONTS" VARCHAR2(512),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DOC_TYPE_01" FOREIGN KEY ("DOC_TYPE_NUM")
	  REFERENCES "TREXONE_DATA"."DOC_TYPE" ("DOC_TYPE_NUM") ENABLE,
	 CONSTRAINT "FK_PRINT_DEVICE_TYPE_01" FOREIGN KEY ("PRINT_DEVICE_TYPE_NUM")
	  REFERENCES "TREXONE_DATA"."PRINT_DEVICE_TYPE" ("PRINT_DEVICE_TYPE_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DOC_FORMAT" ON "TREXONE_DATA"."DOC_FORMAT" ("DOC_FORMAT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DOC_FORMAT" ADD CONSTRAINT "PK_DOC_FORMAT" PRIMARY KEY ("DOC_FORMAT_NUM")
  USING INDEX "TREXONE_DATA"."PK_DOC_FORMAT"  ENABLE;
-- ==========================================
