-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DOC_GROUP"
   (	"DOC_GROUP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DOC_PAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DOC_GROUP_SIZE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DOC_CONTENT_PROVIDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"Y_POS" NUMBER(9,0),
	"X_POS" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(30) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DOC_CONTENT_PROVIDER_01" FOREIGN KEY ("DOC_CONTENT_PROVIDER_NUM")
	  REFERENCES "TREXONE_DATA"."DOC_CONTENT_PROVIDER" ("DOC_CONTENT_PROVIDER_NUM") ENABLE,
	 CONSTRAINT "FK_DOC_GROUP_SIZE_03" FOREIGN KEY ("DOC_GROUP_SIZE_NUM")
	  REFERENCES "TREXONE_DATA"."DOC_GROUP_SIZE" ("DOC_GROUP_SIZE_NUM") ENABLE,
	 CONSTRAINT "FK_DOC_PAGE_01" FOREIGN KEY ("DOC_PAGE_NUM")
	  REFERENCES "TREXONE_DATA"."DOC_PAGE" ("DOC_PAGE_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DOC_GROUP" ON "TREXONE_DATA"."DOC_GROUP" ("DOC_GROUP_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DOC_GROUP" ADD CONSTRAINT "PK_DOC_GROUP" PRIMARY KEY ("DOC_GROUP_NUM")
  USING INDEX "TREXONE_DATA"."PK_DOC_GROUP"  ENABLE;
-- ==========================================
