-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DOC_FIELD"
   (	"DOC_FIELD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DOC_VERSION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DATA_FIELD_NAME" VARCHAR2(256),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DOC_VERSION_02" FOREIGN KEY ("DOC_VERSION_NUM")
	  REFERENCES "TREXONE_DATA"."DOC_VERSION" ("DOC_VERSION_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DOC_FIELD" ON "TREXONE_DATA"."DOC_FIELD" ("DOC_FIELD_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DOC_FIELD" ADD CONSTRAINT "PK_DOC_FIELD" PRIMARY KEY ("DOC_FIELD_NUM")
  USING INDEX "TREXONE_DATA"."PK_DOC_FIELD"  ENABLE;
-- ==========================================
