-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DOC_VERSION_MEDIA_TYPE"
   (	"DOC_VERSION_MEDIA_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DOC_VERSION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRINT_DOC_MEDIA_GROUP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DOC_VERSION_04" FOREIGN KEY ("DOC_VERSION_NUM")
	  REFERENCES "TREXONE_DATA"."DOC_VERSION" ("DOC_VERSION_NUM") ENABLE,
	 CONSTRAINT "FK_PRINT_DOC_MEDIA_GROUP_02" FOREIGN KEY ("PRINT_DOC_MEDIA_GROUP_NUM")
	  REFERENCES "TREXONE_DATA"."PRINT_DOC_MEDIA_GROUP" ("PRINT_DOC_MEDIA_GROUP_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DOC_VERSION_MEDIA_TYPE" ON "TREXONE_DATA"."DOC_VERSION_MEDIA_TYPE" ("DOC_VERSION_MEDIA_TYPE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DOC_VERSION_MEDIA_TYPE" ADD CONSTRAINT "PK_DOC_VERSION_MEDIA_TYPE" PRIMARY KEY ("DOC_VERSION_MEDIA_TYPE_NUM")
  USING INDEX "TREXONE_DATA"."PK_DOC_VERSION_MEDIA_TYPE"  ENABLE;
-- ==========================================
