-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DOC_TYPE"
   (	"DOC_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(30),
	"DESCRIPTION" VARCHAR2(80),
	"DATA_OBJECT" VARCHAR2(256),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DOC_TYPE" ON "TREXONE_DATA"."DOC_TYPE" ("DOC_TYPE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DOC_TYPE" ADD CONSTRAINT "PK_DOC_TYPE" PRIMARY KEY ("DOC_TYPE_NUM")
  USING INDEX "TREXONE_DATA"."PK_DOC_TYPE"  ENABLE;
-- ==========================================
