-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DOC_PAGE"
   (	"DOC_PAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DOC_VERSION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRINT_MEDIA_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRINT_MEDIA_SIDE" CHAR(127),
	"NAME" VARCHAR2(30),
	"SEQ_NUM" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DOC_VERSION_03" FOREIGN KEY ("DOC_VERSION_NUM")
	  REFERENCES "TREXONE_DATA"."DOC_VERSION" ("DOC_VERSION_NUM") ENABLE,
	 CONSTRAINT "FK_PRINT_MEDIA_TYPE_01" FOREIGN KEY ("PRINT_MEDIA_TYPE_NUM")
	  REFERENCES "TREXONE_DATA"."PRINT_MEDIA_TYPE" ("PRINT_MEDIA_TYPE_NUM") ENABLE NOVALIDATE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DOC_PAGE" ON "TREXONE_DATA"."DOC_PAGE" ("DOC_PAGE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DOC_PAGE" ADD CONSTRAINT "PK_DOC_PAGE" PRIMARY KEY ("DOC_PAGE_NUM")
  USING INDEX "TREXONE_DATA"."PK_DOC_PAGE"  ENABLE;
-- ==========================================
