-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DSCSA_DOCUMENT"
   (	"DSCSA_DOCUMENT_NUM" NUMBER(18,0),
	"DOCUMENT_ID" VARCHAR2(100),
	"FILE_NAME" VARCHAR2(256),
	"SENDER_CREATE_DATETIME" DATE,
	"RECEIVED_DATETIME" DATE NOT NULL ENABLE,
	"SENDING_PARTY_SGLN" VARCHAR2(100) NOT NULL ENABLE,
	"RECEIVING_PARTY_SGLN" VARCHAR2(100) NOT NULL ENABLE,
	"VERSION" VARCHAR2(50) NOT NULL ENABLE,
	"PURCHASE_ORDER_IDENTIFIER" VARCHAR2(100) NOT NULL ENABLE,
	"RECEIVING_PARTY_GLN" VARCHAR2(100) NOT NULL ENABLE,
	"PARTITION_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_DSCSA_DOCUMENT" PRIMARY KEY ("DSCSA_DOCUMENT_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_80" FOREIGN KEY ("SYS_USER")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE NOVALIDATE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTOYMINTERVAL(3,'MONTH')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
