-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DT_DRUG"
   (	"DT_TX_NUM" NUMBER(19,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRODUCT" VARCHAR2(35) NOT NULL ENABLE,
	"MANUFACTURER" VARCHAR2(30),
	"NDC_MFG" CHAR(5),
	"NDC_PRODUCT" CHAR(4),
	"NDC_SIZE" CHAR(2),
	"DRUG_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DISTRIBUTOR" VARCHAR2(30),
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"PRODUCT_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DRUG_XREF_05" FOREIGN KEY ("DRUG_NUM")
	  REFERENCES "TREXONE_DATA"."DRUG_XREF" ("DRUG_NUM") ENABLE,
	 CONSTRAINT "FK_DT_TX_04" FOREIGN KEY ("DT_TX_NUM", "FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."DT_TX" ("DT_TX_NUM", "FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_PRODUCT_43" FOREIGN KEY ("PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT" ("PRODUCT_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DT_DRUG" ON "TREXONE_DATA"."DT_DRUG" ("DT_TX_NUM", "FACILITY_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DT_DRUG" ADD CONSTRAINT "PK_DT_DRUG" PRIMARY KEY ("DT_TX_NUM", "FACILITY_NUM")
  USING INDEX "TREXONE_DATA"."PK_DT_DRUG"  ENABLE;
-- ==========================================
