-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DT_PRESCRIBER"
   (	"DT_TX_NUM" NUMBER(19,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FIRST_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"MIDDLE_INITIAL" VARCHAR2(30),
	"LAST_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"ADDRESS" VARCHAR2(100),
	"CITY" VARCHAR2(40),
	"STATE_CODE" CHAR(2),
	"ZIP_CODE" VARCHAR2(20),
	"PHONE" VARCHAR2(20),
	"DEA_NUMBER" VARCHAR2(30),
	"LICENSE_NUMBER" VARCHAR2(30),
	"UPIN_NUMBER" VARCHAR2(30),
	"PRESCRIBER_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"DEA_SUFFIX" VARCHAR2(20),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PRESCRIBER_17" FOREIGN KEY ("PRESCRIBER_NUM")
	  REFERENCES "TREXONE_DATA"."PRESCRIBER" ("PRESCRIBER_NUM") ENABLE,
	 CONSTRAINT "FK_DT_TX_01" FOREIGN KEY ("DT_TX_NUM", "FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."DT_TX" ("DT_TX_NUM", "FACILITY_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DT_PRESCRIBER" ON "TREXONE_DATA"."DT_PRESCRIBER" ("DT_TX_NUM", "FACILITY_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DT_PRESCRIBER" ADD CONSTRAINT "PK_DT_PRESCRIBER" PRIMARY KEY ("DT_TX_NUM", "FACILITY_NUM")
  USING INDEX "TREXONE_DATA"."PK_DT_PRESCRIBER"  ENABLE;
-- ==========================================
