-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DT_RXNUMBER_RESERVE"
   (	"DT_RXNUMBER_RESERVE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"START_VALUE" NUMBER(13,0) NOT NULL ENABLE,
	"END_VALUE" NUMBER(13,0) NOT NULL ENABLE,
	"IS_EXHAUSTED" CHAR(1) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_FACILITY_56" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DT_RXNUMBER_RESERVE" ON "TREXONE_DATA"."DT_RXNUMBER_RESERVE" ("DT_RXNUMBER_RESERVE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DT_RXNUMBER_RESERVE" ADD CONSTRAINT "PK_DT_RXNUMBER_RESERVE" PRIMARY KEY ("DT_RXNUMBER_RESERVE_NUM")
  USING INDEX "TREXONE_DATA"."PK_DT_RXNUMBER_RESERVE"  ENABLE;
-- ==========================================
