-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DT_THIRD_PARTY"
   (	"DT_TX_NUM" NUMBER(19,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(35),
	"CARDHOLDER_ID" VARCHAR2(30),
	"GROUP_NUMBER" VARCHAR2(30),
	"BANK_ID_NUMBER" VARCHAR2(6),
	"PERSON_CODE" VARCHAR2(3),
	"TP_PATIENT_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"TP_RANK" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_TP_PATIENT_03" FOREIGN KEY ("TP_PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."TP_PATIENT" ("TP_PATIENT_NUM") ENABLE,
	 CONSTRAINT "FK_DT_TX_02" FOREIGN KEY ("DT_TX_NUM", "FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."DT_TX" ("DT_TX_NUM", "FACILITY_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DT_THIRD_PARTY" ON "TREXONE_DATA"."DT_THIRD_PARTY" ("DT_TX_NUM", "FACILITY_NUM", "TP_RANK")
  ;
ALTER TABLE "TREXONE_DATA"."DT_THIRD_PARTY" ADD CONSTRAINT "PK_DT_THIRD_PARTY" PRIMARY KEY ("DT_TX_NUM", "FACILITY_NUM", "TP_RANK")
  USING INDEX "TREXONE_DATA"."PK_DT_THIRD_PARTY"  ENABLE;
-- ==========================================
