-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DT_TX"
   (	"DT_TX_NUM" NUMBER(19,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_TYPE" CHAR(1) NOT NULL ENABLE,
	"RX_NUMBER" VARCHAR2(12),
	"DT_RX_NUMBER" VARCHAR2(12) NOT NULL ENABLE,
	"WRITTEN_DATE" DATE NOT NULL ENABLE,
	"EXPIRATION_DATE" DATE NOT NULL ENABLE,
	"PARTIAL_FILL_QTY" NUMBER(13,3),
	"DISPENSED_QTY" NUMBER(13,3) NOT NULL ENABLE,
	"SIG" VARCHAR2(255) NOT NULL ENABLE,
	"REFILLS_REMAINING_IND" CHAR(1) NOT NULL ENABLE,
	"NUM_REFILLS_REMAINING" NUMBER(11,2),
	"USE_SAFETY_CAP" CHAR(1) NOT NULL ENABLE,
	"ADDITIONAL_INFO" VARCHAR2(500),
	"PATIENT_PAY" NUMBER(9,2),
	"RPH_INITIALS" VARCHAR2(3) NOT NULL ENABLE,
	"RPH_NAME" VARCHAR2(50) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0),
	"RX_FILL_SEQ" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DELETED_IND" CHAR(1),
	"FILLED_DATE" DATE,
	"TRANSACTION_NUMBER" VARCHAR2(10),
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"PRESCRIBED_QTY" NUMBER(13,3) NOT NULL ENABLE,
	"WRITTEN_PRODUCT_NUM" NUMBER(18,0),
	"WRITTEN_PRODUCT_NAME" VARCHAR2(35),
	"DAW_CODE" CHAR(1) NOT NULL ENABLE,
	"REFILLS_AUTHORIZED" NUMBER(9,0) NOT NULL ENABLE,
	"TP_TYPE" CHAR(1),
	"DT_RX_STATUS" NUMBER(1,0) NOT NULL ENABLE,
	"PRINTED_DATE" DATE,
	"FACILITY_ID" VARCHAR2(10),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"HL7_PATIENT_ID" VARCHAR2(30),
	 CONSTRAINT "FK_FACILITY_51" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_RX_FILL_15" FOREIGN KEY ("RX_FILL_SEQ", "RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_FILL" ("RX_FILL_SEQ", "RX_RECORD_NUM") ENABLE,
	 CONSTRAINT "FK_PRODUCT_42" FOREIGN KEY ("WRITTEN_PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT" ("PRODUCT_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DT_TX" ON "TREXONE_DATA"."DT_TX" ("DT_TX_NUM", "FACILITY_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DT_TX" ADD CONSTRAINT "PK_DT_TX" PRIMARY KEY ("DT_TX_NUM", "FACILITY_NUM")
  USING INDEX "TREXONE_DATA"."PK_DT_TX"  ENABLE;
-- ==========================================
