-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DUR_ADMIN_DRUG_LIST"
   (	"DUR_ADMIN_DRUG_LIST_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"DRUG_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"LIST_TYPE" VARCHAR2(30) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DATA_GROUP_16" FOREIGN KEY ("DATA_GROUP")
	  REFERENCES "TREXONE_DATA"."DATA_GROUP" ("DATA_GROUP") ENABLE,
	 CONSTRAINT "FK_DRUG_XREF_06" FOREIGN KEY ("DRUG_NUM")
	  REFERENCES "TREXONE_DATA"."DRUG_XREF" ("DRUG_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DUR_ADMIN_DRUG_LIST" ON "TREXONE_DATA"."DUR_ADMIN_DRUG_LIST" ("DUR_ADMIN_DRUG_LIST_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DUR_ADMIN_DRUG_LIST" ADD CONSTRAINT "PK_DUR_ADMIN_DRUG_LIST" PRIMARY KEY ("DUR_ADMIN_DRUG_LIST_NUM")
  USING INDEX "TREXONE_DATA"."PK_DUR_ADMIN_DRUG_LIST"  ENABLE;
-- ==========================================
