-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DUR_CONFLICT_DRUG_ALLERGY"
   (	"DUR_CONFLICT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ALLERGEN_CUSTOM_ID" VARCHAR2(15),
	"DRUG_ALLERGY_DESC" VARCHAR2(255),
	"DRUG_CUSTOM_ID" VARCHAR2(15),
	"DRUG_DESC" VARCHAR2(50),
	"DRUG_ID" VARCHAR2(15),
	"MATCH_DESC" VARCHAR2(100),
	"MATCH_TYPE" CHAR(5),
	"NON_ALLERGIC_RESPONSE" CHAR(1),
	"REACTION_DESC" VARCHAR2(255),
	"SCREEN_MESSAGE" VARCHAR2(4000),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DUR_CONFLICT_03" FOREIGN KEY ("DUR_CONFLICT_NUM")
	  REFERENCES "TREXONE_DATA"."DUR_CONFLICT" ("DUR_CONFLICT_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DUR_CONFLICT_DRUG_ALLERGY" ON "TREXONE_DATA"."DUR_CONFLICT_DRUG_ALLERGY" ("DUR_CONFLICT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DUR_CONFLICT_DRUG_ALLERGY" ADD CONSTRAINT "PK_DUR_CONFLICT_DRUG_ALLERGY" PRIMARY KEY ("DUR_CONFLICT_NUM")
  USING INDEX "TREXONE_DATA"."PK_DUR_CONFLICT_DRUG_ALLERGY"  ENABLE;
-- ==========================================
