-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DUR_CONFLICT_COMPLIANCE"
   (	"DUR_CONFLICT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(1023),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "CK_DUR_CONFLICT_COMPLIANCE_01" CHECK (PARTITION_DATE is not null) ENABLE NOVALIDATE,
	 CONSTRAINT "FK_DUR_CONFLICT_02" FOREIGN KEY ("DUR_CONFLICT_NUM")
	  REFERENCES "TREXONE_DATA"."DUR_CONFLICT" ("DUR_CONFLICT_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DUR_CONFLICT_COMPLIANCE" ON "TREXONE_DATA"."DUR_CONFLICT_COMPLIANCE" ("DUR_CONFLICT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DUR_CONFLICT_COMPLIANCE" ADD CONSTRAINT "PK_DUR_CONFLICT_COMPLIANCE" PRIMARY KEY ("DUR_CONFLICT_NUM")
  USING INDEX "TREXONE_DATA"."PK_DUR_CONFLICT_COMPLIANCE"  ENABLE;
-- ==========================================
