-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DUR_CONFLICT_MESSAGE"
   (	"DUR_CONFLICT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DRUG_CUSTOM_ID" VARCHAR2(15),
	"DRUG_DESC" VARCHAR2(50),
	"DRUG_ID" VARCHAR2(15),
	"MESSAGE" VARCHAR2(1023),
	"MESSAGE_TYPE" VARCHAR2(5),
	"SEVERITY" VARCHAR2(5),
	"SOURCE" VARCHAR2(5),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DUR_CONFLICT_12" FOREIGN KEY ("DUR_CONFLICT_NUM")
	  REFERENCES "TREXONE_DATA"."DUR_CONFLICT" ("DUR_CONFLICT_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DUR_CONFLICT_MESSAGE" ON "TREXONE_DATA"."DUR_CONFLICT_MESSAGE" ("DUR_CONFLICT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DUR_CONFLICT_MESSAGE" ADD CONSTRAINT "PK_DUR_CONFLICT_MESSAGE" PRIMARY KEY ("DUR_CONFLICT_NUM")
  USING INDEX "TREXONE_DATA"."PK_DUR_CONFLICT_MESSAGE"  ENABLE;
-- ==========================================
