-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DUR_ADOLESCENT_DOSE_DRUG"
   (	"DUR_ADOLESCENT_DOSE_DRUG_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DRUG_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DRUG_XREF_02" FOREIGN KEY ("DRUG_NUM")
	  REFERENCES "TREXONE_DATA"."DRUG_XREF" ("DRUG_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DUR_ADOLESCENT_DOSE_DRUG" ON "TREXONE_DATA"."DUR_ADOLESCENT_DOSE_DRUG" ("DUR_ADOLESCENT_DOSE_DRUG_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DUR_ADOLESCENT_DOSE_DRUG" ADD CONSTRAINT "PK_DUR_ADOLESCENT_DOSE_DRUG" PRIMARY KEY ("DUR_ADOLESCENT_DOSE_DRUG_NUM")
  USING INDEX "TREXONE_DATA"."PK_DUR_ADOLESCENT_DOSE_DRUG"  ENABLE;
-- ==========================================
