-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DUR_CONFLICT"
   (	"DUR_CONFLICT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TYPE" NUMBER(9,0),
	"PROF_SERVICE_CODE" CHAR(2),
	"RESULT_SERVICE_CODE" CHAR(2),
	"LEVEL_OF_EFFORT_NUM" NUMBER(9,0),
	"INDIVIDUALLY_RESOLVED" CHAR(1),
	"RESOLVING_USER_NUM" NUMBER(18,0),
	"RX_FILL_DUR_CONFLICT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CODE_SET_NUM" NUMBER(18,0),
	"IS_EXCEPTION" CHAR(1),
	"IS_CRITICAL" CHAR(1),
	"IS_SUPPRESSED" CHAR(1),
	"CONFLICT_CODE" CHAR(2),
	"SORT_PRIORITY" NUMBER(9,0),
	"COLOR" VARCHAR2(20),
	"REQUIRED_ID" CHAR(1),
	"MINIMUM_AUTHORITY_LEVEL" VARCHAR2(20),
	"PROF_CODE_TO_APPROVE" CHAR(1),
	"PROF_CODE_TO_DECLINE" CHAR(1),
	"RESULT_CODE_TO_APPROVE" CHAR(1),
	"RESULT_CODE_TO_DECLINE" CHAR(1),
	"LEVEL_OF_EFFORT_TO_APPROVE" CHAR(1),
	"LEVEL_OF_EFFORT_TO_DECLINE" CHAR(1),
	"REASON_CODE_TO_APPROVE" CHAR(1),
	"REASON_CODE_TO_DECLINE" CHAR(1),
	"LEVEL_ONE_SCREEN_FORMAT" VARCHAR2(255),
	"LEVEL_TWO_SCREEN_FORMAT" VARCHAR2(255),
	"LEVEL_ONE_PRINT_FORMAT" VARCHAR2(255),
	"LEVEL_TWO_PRINT_FORMAT" VARCHAR2(255),
	"COMMENTARY" VARCHAR2(255),
	"TITLE_CHARACTER_SIZE" VARCHAR2(20),
	"CONFLICT_DESCRIPTION" VARCHAR2(255),
	"LEVEL_OF_EFFORT_REQUIRED" CHAR(1),
	"PROF_CODE_REQUIRED" CHAR(1),
	"RESULT_CODE_REQUIRED" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"CO_AGENT_QUALIFIER" VARCHAR2(2),
	"CO_AGENT_ID" VARCHAR2(19),
	"CO_AGENT_IN_TP_CLAIM" CHAR(1),
	"PROF_CODE_IN_TP_CLAIM" CHAR(1),
	"RESOLVE_BEFORE_DISPENSING" CHAR(1),
	"MAY_PRINT_ON_LABEL" CHAR(1),
	"IS_FILTERED" CHAR(1),
	"GCN_SEQ" VARCHAR2(30),
	"RESOLVED_DATESTAMP" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_CODE_SET_02" FOREIGN KEY ("CODE_SET_NUM")
	  REFERENCES "TREXONE_DATA"."CODE_SET" ("CODE_SET_NUM") ENABLE,
	 CONSTRAINT "FK_RX_FILL_DUR_CONFLICT_01" FOREIGN KEY ("RX_FILL_DUR_CONFLICT_NUM")
	  REFERENCES "TREXONE_DATA"."RX_FILL_DUR_CONFLICT" ("RX_FILL_DUR_CONFLICT_NUM") ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_06" FOREIGN KEY ("RESOLVING_USER_NUM")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DUR_CONFLICT" ON "TREXONE_DATA"."DUR_CONFLICT" ("DUR_CONFLICT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DUR_CONFLICT" ADD CONSTRAINT "PK_DUR_CONFLICT" PRIMARY KEY ("DUR_CONFLICT_NUM")
  USING INDEX "TREXONE_DATA"."PK_DUR_CONFLICT"  ENABLE;
-- ==========================================
