-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DUR_CONFLICT_DRUG_DISEASE"
   (	"DUR_CONFLICT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CONDITION_CUSTOM_ID" VARCHAR2(35),
	"CONDITION_DESC" VARCHAR2(255),
	"CONDITION_ID" VARCHAR2(15),
	"DISEASE_DESC" VARCHAR2(255),
	"DETAIL_DRUG_DESC" VARCHAR2(255),
	"DRUG_CUSTOM_ID" VARCHAR2(15),
	"DRUG_DESC" VARCHAR2(50),
	"INTERNAL_DRUG_ID" VARCHAR2(15),
	"MEDICAL_CONDITION_DESC" VARCHAR2(255),
	"MEDICAL_CONDITION_ID" VARCHAR2(15),
	"SCREEN_MESSAGE" VARCHAR2(4000),
	"SEVERITY" VARCHAR2(20),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"SEVERITY_TEXT" VARCHAR2(200),
	"COMMENTARY" CLOB,
	 CONSTRAINT "CK_DUR_CONFLICT_DRUG_DISEAS_01" CHECK (PARTITION_DATE is not null) ENABLE NOVALIDATE,
	 CONSTRAINT "FK_DUR_CONFLICT_04" FOREIGN KEY ("DUR_CONFLICT_NUM")
	  REFERENCES "TREXONE_DATA"."DUR_CONFLICT" ("DUR_CONFLICT_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DUR_CONFLICT_DRUG_DISEASE" ON "TREXONE_DATA"."DUR_CONFLICT_DRUG_DISEASE" ("DUR_CONFLICT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DUR_CONFLICT_DRUG_DISEASE" ADD CONSTRAINT "PK_DUR_CONFLICT_DRUG_DISEASE" PRIMARY KEY ("DUR_CONFLICT_NUM")
  USING INDEX "TREXONE_DATA"."PK_DUR_CONFLICT_DRUG_DISEASE"  ENABLE;
-- ==========================================
