-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DUR_CONFLICT_DRUG_DRUG"
   (	"DUR_CONFLICT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0),
	"EFFECT_CODE_1" CHAR(5),
	"EFFECT_CODE_2" CHAR(5),
	"ANIMAL_USED" CHAR(1),
	"CASE_REPORT_USED" CHAR(1),
	"HUMAN_TRIAL_USED" CHAR(1),
	"MANUFACTURER_INFO_USED" CHAR(1),
	"MEETING_ABSTRACT_INFO_USED" CHAR(1),
	"REVIEW_ARTICLE_INFO_USED" CHAR(1),
	"DRUG_1_CUSTOM_ID" VARCHAR2(15),
	"DRUG_1_DESC" VARCHAR2(50),
	"DRUG_1_ID" VARCHAR2(15),
	"DRUG_2_CUSTOM_ID" VARCHAR2(15),
	"DRUG_2_DESC" VARCHAR2(50),
	"DRUG_2_ID" VARCHAR2(15),
	"EDI_PAGE" VARCHAR2(30),
	"ID" VARCHAR2(15),
	"SCREEN_MESSAGE" VARCHAR2(4000),
	"MONOGRAPH_ID" VARCHAR2(15),
	"SEVERITY" VARCHAR2(5),
	"DESCRIPTION" VARCHAR2(255),
	"USER_DEFINED_CATEGORY" VARCHAR2(50),
	"USER_DEFINED_INTERACTION" CHAR(1),
	"FACILITY_NUM" NUMBER(18,0),
	"RX_FILL_SEQ" NUMBER(18,0),
	"PATIENT_EXTRA_MEDICATION_NUM" NUMBER(18,0),
	"IS_RXFILL" CHAR(1),
	"RX_DAYS_SUPPLY" NUMBER(9,0),
	"RX_DATE_LAST_FILLED" DATE,
	"RX_PICKUP_DATE" DATE,
	"RX_DATE_WRITTEN" DATE,
	"RX_IS_COMPOUND" CHAR(1),
	"RX_PRESCRIBER_NAME" VARCHAR2(100),
	"RX_PRESCRIBER_PHONE_NUM" VARCHAR2(30),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"SEVERITY_TEXT" VARCHAR2(200),
	"DOCUMENTATION_LEVEL" VARCHAR2(50),
	"MECHANISM_OF_ACTION" CLOB,
	"CLINICAL_EFFECTS" CLOB,
	"PATIENT_MANAGEMENT" CLOB,
	"MANAGEMENT_LEVEL_CODE" VARCHAR2(5),
	"AVOIDANCE_LEVEL" VARCHAR2(50),
	"ONSET_TEXT" VARCHAR2(50),
	 CONSTRAINT "FK_DUR_CONFLICT_06" FOREIGN KEY ("DUR_CONFLICT_NUM")
	  REFERENCES "TREXONE_DATA"."DUR_CONFLICT" ("DUR_CONFLICT_NUM") ENABLE,
	 CONSTRAINT "FK_FACILITY_13" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_RX_03" FOREIGN KEY ("RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_BASE" ("RX_RECORD_NUM") ENABLE,
	 CONSTRAINT "FK_PATIENT_PERM_RX_01" FOREIGN KEY ("PATIENT_EXTRA_MEDICATION_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT_PERM_RX" ("PATIENT_PERM_RX_NUM") ENABLE NOVALIDATE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DUR_CONFLICT_DRUG_DRUG" ON "TREXONE_DATA"."DUR_CONFLICT_DRUG_DRUG" ("DUR_CONFLICT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DUR_CONFLICT_DRUG_DRUG" ADD CONSTRAINT "PK_DUR_CONFLICT_DRUG_DRUG" PRIMARY KEY ("DUR_CONFLICT_NUM")
  USING INDEX "TREXONE_DATA"."PK_DUR_CONFLICT_DRUG_DRUG"  ENABLE;
-- ==========================================
