-- ==========================================

  CREATE TABLE "TREXONE_DATA"."EASY_OPEN_CAPS_ACK"
   (	"EASY_OPEN_CAPS_ACK_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACTIVE" CHAR(1) NOT NULL ENABLE,
	"PATIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"IMAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_IMAGE_12" FOREIGN KEY ("IMAGE_NUM")
	  REFERENCES "TREXONE_DATA"."IMAGE" ("IMAGE_NUM") ENABLE,
	 CONSTRAINT "FK_PATIENT_28" FOREIGN KEY ("PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PKEASY_OPEN_CAPS_ACKNOWLEDGMEN" ON "TREXONE_DATA"."EASY_OPEN_CAPS_ACK" ("EASY_OPEN_CAPS_ACK_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."EASY_OPEN_CAPS_ACK" ADD CONSTRAINT "PKEASY_OPEN_CAPS_ACKNOWLEDGMEN" PRIMARY KEY ("EASY_OPEN_CAPS_ACK_NUM")
  USING INDEX "TREXONE_DATA"."PKEASY_OPEN_CAPS_ACKNOWLEDGMEN"  ENABLE;
-- ==========================================
