-- ==========================================

  CREATE TABLE "TREXONE_DATA"."EDI_VERSION"
   (	"EDI_VERSION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"VERSION" VARCHAR2(10) NOT NULL ENABLE,
	"NAME" VARCHAR2(50) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PKEDI_VERSION" ON "TREXONE_DATA"."EDI_VERSION" ("EDI_VERSION_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."EDI_VERSION" ADD CONSTRAINT "PKEDI_VERSION" PRIMARY KEY ("EDI_VERSION_NUM")
  USING INDEX "TREXONE_DATA"."PKEDI_VERSION"  ENABLE;
-- ==========================================
