-- ==========================================

  CREATE TABLE "TREXONE_DATA"."EIF_OUTGOING_MESSAGE"
   (	"EIF_OUTGOING_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"EIF_PEER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SEND_AFTER" DATE,
	"MESSAGE" BLOB NOT NULL ENABLE,
	"STATUS" CHAR(1) NOT NULL ENABLE,
	"ERROR_COUNT" NUMBER(3,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0) NOT NULL ENABLE,
	"MESSAGE_ID" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_EIF_PEER_1" FOREIGN KEY ("EIF_PEER_NUM")
	  REFERENCES "TREXONE_DATA"."EIF_PEER" ("EIF_PEER_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_EIF_OUTGOING_MESSAGE" ON "TREXONE_DATA"."EIF_OUTGOING_MESSAGE" ("EIF_OUTGOING_MESSAGE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."EIF_OUTGOING_MESSAGE" ADD CONSTRAINT "PK_EIF_OUTGOING_MESSAGE" PRIMARY KEY ("EIF_OUTGOING_MESSAGE_NUM")
  USING INDEX "TREXONE_DATA"."PK_EIF_OUTGOING_MESSAGE"  ENABLE;
-- ==========================================
