-- ==========================================

  CREATE TABLE "TREXONE_DATA"."EIF_TRANSMISSION_RECORD"
   (	"EIF_TRANSMISSION_RECORD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"EIF_PEER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"EIF_OUTGOING_MESSAGE_NUM" NUMBER(18,0),
	"MESSAGE" BLOB,
	"MESSAGE_ID" NUMBER(18,0),
	"ORIGINAL_MIC" VARCHAR2(1000),
	"RECEIVED_MIC" VARCHAR2(1000),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_EIF_OUTGOING_MESSAGE_2" FOREIGN KEY ("EIF_OUTGOING_MESSAGE_NUM")
	  REFERENCES "TREXONE_DATA"."EIF_OUTGOING_MESSAGE" ("EIF_OUTGOING_MESSAGE_NUM") ENABLE,
	 CONSTRAINT "FK_EIF_PEER_2" FOREIGN KEY ("EIF_PEER_NUM")
	  REFERENCES "TREXONE_DATA"."EIF_PEER" ("EIF_PEER_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_EIF_TRANSMISSION_RECORD" ON "TREXONE_DATA"."EIF_TRANSMISSION_RECORD" ("EIF_TRANSMISSION_RECORD_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."EIF_TRANSMISSION_RECORD" ADD CONSTRAINT "PK_EIF_TRANSMISSION_RECORD" PRIMARY KEY ("EIF_TRANSMISSION_RECORD_NUM")
  USING INDEX "TREXONE_DATA"."PK_EIF_TRANSMISSION_RECORD"  ENABLE;
-- ==========================================
