-- ==========================================

  CREATE TABLE "TREXONE_DATA"."EIF_OUTGOING_MESSAGE_ERROR"
   (	"EIF_OUTGOING_MESSAGE_ERROR_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"EIF_OUTGOING_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TEXT" VARCHAR2(1000),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_EIF_OUTGOING_MESSAGE_1" FOREIGN KEY ("EIF_OUTGOING_MESSAGE_NUM")
	  REFERENCES "TREXONE_DATA"."EIF_OUTGOING_MESSAGE" ("EIF_OUTGOING_MESSAGE_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_EIF_OUTGOING_MESSAGE_ERROR" ON "TREXONE_DATA"."EIF_OUTGOING_MESSAGE_ERROR" ("EIF_OUTGOING_MESSAGE_ERROR_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."EIF_OUTGOING_MESSAGE_ERROR" ADD CONSTRAINT "PK_EIF_OUTGOING_MESSAGE_ERROR" PRIMARY KEY ("EIF_OUTGOING_MESSAGE_ERROR_NUM")
  USING INDEX "TREXONE_DATA"."PK_EIF_OUTGOING_MESSAGE_ERROR"  ENABLE;
-- ==========================================
