-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ELECTRONIC_ORDER"
   (	"ELECTRONIC_ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DATE_RECVD" DATE NOT NULL ENABLE,
	"ORDER_SOURCE_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"MSG_ID" VARCHAR2(120) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"ACCOUNT_MEMBER_CREDIT_CARD_NUM" NUMBER(18,0),
	"DELIVERY_METHOD_NUM" NUMBER(18,0),
	"SHIPPING_METHOD_NUM" NUMBER(18,0),
	"SHIPPING_ADDRESS_NUM" NUMBER(18,0),
	"EXPECTED_DELIVERY_DATE" DATE,
	"LOCK_USER" NUMBER(18,0),
	"LOCK_DATE" DATE,
	 CONSTRAINT "FK_ACCOUNT_MEMBER_CREDIT_CD_05" FOREIGN KEY ("ACCOUNT_MEMBER_CREDIT_CARD_NUM")
	  REFERENCES "TREXONE_DATA"."ACCOUNT_MEMBER_CREDIT_CARD" ("ACCOUNT_MEMBER_CREDIT_CARD_NUM") ENABLE,
	 CONSTRAINT "FK_DELIVERY_METHOD_06" FOREIGN KEY ("DELIVERY_METHOD_NUM")
	  REFERENCES "TREXONE_DATA"."DELIVERY_METHOD" ("DELIVERY_METHOD_NUM") ENABLE,
	 CONSTRAINT "FK_SHIPPING_METHOD_03" FOREIGN KEY ("SHIPPING_METHOD_NUM")
	  REFERENCES "TREXONE_DATA"."SHIPPING_METHOD" ("SHIPPING_METHOD_NUM") ENABLE,
	 CONSTRAINT "FK_SHIPPING_ADDRESS_01" FOREIGN KEY ("SHIPPING_ADDRESS_NUM")
	  REFERENCES "TREXONE_DATA"."ADDRESS" ("ADDRESS_NUM") ENABLE,
	 CONSTRAINT "FK_SU_ELECTRONIC_ORD" FOREIGN KEY ("LOCK_USER")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE NOVALIDATE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_ELECTRONIC_ORDER" ON "TREXONE_DATA"."ELECTRONIC_ORDER" ("ELECTRONIC_ORDER_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."ELECTRONIC_ORDER" ADD CONSTRAINT "PK_ELECTRONIC_ORDER" PRIMARY KEY ("ELECTRONIC_ORDER_NUM")
  USING INDEX "TREXONE_DATA"."PK_ELECTRONIC_ORDER"  ENABLE;
-- ==========================================
