-- ==========================================

  CREATE TABLE "TREXONE_DATA"."EPCS_MESSAGE"
   (	"EPCS_MESSAGE_NUM" NUMBER(18,0),
	"EPCS_MSG_RAW" BLOB NOT NULL ENABLE,
	"EPCS_MSG_SIGN" VARCHAR2(1024) NOT NULL ENABLE,
	"EPCS_MSG_DIGEST" VARCHAR2(1024),
	"EPCS_MSG_DIGEST_SIGN" VARCHAR2(1024),
	"EPCS_MSG_DIGEST_CERT" VARCHAR2(4000),
	"EPCS_GEN_DIGEST" VARCHAR2(1024),
	"EPCS_GEN_DIGEST_SIGN" VARCHAR2(1024),
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	"EPCS_GEN_DIGEST_CERT" VARCHAR2(4000),
	"EPCS_SIGN_ALG" VARCHAR2(10) DEFAULT 'SHA1' NOT NULL ENABLE,
	"IS_DIGITALLY_SIGNED" CHAR(1),
	 CONSTRAINT "PK_EPCS_MESSAGE" PRIMARY KEY ("EPCS_MESSAGE_NUM")
  USING INDEX  ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
