-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ERP_PATIENT_ENROLL_BATCH"
   (	"PATIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"BATCH_PROCESS_DATE" DATE NOT NULL ENABLE,
	"LAST_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"FIRST_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"BIRTH_DATE" DATE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "ERP_PATIENT_ENROLL_BATCH_PK" PRIMARY KEY ("PATIENT_NUM", "BATCH_PROCESS_DATE")
  USING INDEX  ENABLE,
	 CONSTRAINT "ERP_PATIENT_ENROLL_BATCH_FK01" FOREIGN KEY ("PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE NOVALIDATE
   ) ;
-- ==========================================
