-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ERP_INCLUDE_EXCLUDE_RULE"
   (	"ERP_INCL_EXCL_RULE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DATA_FILTER" CLOB NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"ERP_INCL_EXCL_RULE_SET_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"IS_INCLUDE_RULE" CHAR(1) NOT NULL ENABLE,
	"PROCESS_ORDER" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"IS_ONE_TIME_EXEMPT" CHAR(1),
	 CONSTRAINT "PK_ERP_INCLUDE_EXCLUDE_RULE" PRIMARY KEY ("ERP_INCL_EXCL_RULE_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_ERP_INCLUDE_EXCL_RULE_SET_1" FOREIGN KEY ("ERP_INCL_EXCL_RULE_SET_NUM")
	  REFERENCES "TREXONE_DATA"."ERP_INCLUDE_EXCLUDE_RULE_SET" ("ERP_INCL_EXCL_RULE_SET_NUM") ENABLE
   ) ;
-- ==========================================
