-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ERP_INCLUDE_EXCLUDE_RULE_SET"
   (	"ERP_INCL_EXCL_RULE_SET_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_ERP_INCLUDE_EXCLUD_RULE_SET" PRIMARY KEY ("ERP_INCL_EXCL_RULE_SET_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_DATA_GROUP_23" FOREIGN KEY ("DATA_GROUP")
	  REFERENCES "TREXONE_DATA"."DATA_GROUP" ("DATA_GROUP") ENABLE
   ) ;
-- ==========================================
