-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ERX_COMMAND_LOG"
   (	"ERX_COMMAND_LOG_NUM" NUMBER(18,0),
	"CREATE_DATE" DATE,
	"SCOPE" CHAR(1),
	"SCOPE_ID" NUMBER(18,0),
	"TYPE" VARCHAR2(200),
	"PARAMETERS" VARCHAR2(2000),
	"RESULTS" CLOB,
	"IMPLEMENTATION" BLOB,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CHECK ( SCOPE IN ( 'D', 'C' )) ENABLE,
	 CONSTRAINT "PK_ERX_COMMAND_LOG" PRIMARY KEY ("ERX_COMMAND_LOG_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
