-- ==========================================

  CREATE TABLE "TREXONE_DATA"."EXPORTED_PRESCRIBER"
   (	"EXPORTED_PRESCRIBER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRESCRIBER_EXPORT_REQUEST_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SCHEDULED_PRESCRIBER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"EXPORT_DATE" DATE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PRESCRIBER_EXPORT_REQUEST_1" FOREIGN KEY ("PRESCRIBER_EXPORT_REQUEST_NUM")
	  REFERENCES "TREXONE_DATA"."PRESCRIBER_EXPORT_REQUEST" ("PRESCRIBER_EXPORT_REQUEST_NUM") ENABLE,
	 CONSTRAINT "FK_SCHEDULED_PRESCRIBER_01" FOREIGN KEY ("SCHEDULED_PRESCRIBER_NUM")
	  REFERENCES "TREXONE_DATA"."SCHEDULED_PRESCRIBER" ("SCHEDULED_PRESCRIBER_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_EXPORTED_PRESCRIBER" ON "TREXONE_DATA"."EXPORTED_PRESCRIBER" ("EXPORTED_PRESCRIBER_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."EXPORTED_PRESCRIBER" ADD CONSTRAINT "PK_EXPORTED_PRESCRIBER" PRIMARY KEY ("EXPORTED_PRESCRIBER_NUM")
  USING INDEX "TREXONE_DATA"."PK_EXPORTED_PRESCRIBER"  ENABLE;
-- ==========================================
