-- ==========================================

  CREATE TABLE "TREXONE_DATA"."EZ_PAY_STAGING"
   (	"EZ_PAY_STAGING_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"BASKET_ID" VARCHAR2(50) NOT NULL ENABLE,
	"SIGNATURE_IMAGE" BLOB,
	"FILE_FORMAT" VARCHAR2(10),
	"PICKUP_PERSON_NAME" VARCHAR2(40),
	"PICKUP_PERSON_ID_TYPE_NUM" NUMBER(18,0),
	"PICKUP_PERSON_ID_NUMBER" VARCHAR2(23),
	"PICKUP_PERSON_LAST_NAME" VARCHAR2(30),
	"PICKUP_PERSON_FIRST_NAME" VARCHAR2(30),
	"ALT_PICKUP_PERSON_NAME" VARCHAR2(30),
	"ALT_PICKUP_PERSON_ID_TYPE_NUM" NUMBER(18,0),
	"ALT_PICKUP_PERSON_ID_NUMBER" VARCHAR2(23),
	"ALT_PICKUP_PERSON_LAST_NAME" VARCHAR2(30),
	"ALT_PICKUP_PERSON_FIRST_NAME" VARCHAR2(30),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_EZ_PAY_STAGING" PRIMARY KEY ("EZ_PAY_STAGING_NUM")
  USING INDEX  ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTOYMINTERVAL(3,'MONTH')) STORE IN ("LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
