-- ==========================================

  CREATE TABLE "TREXONE_DATA"."FACILITY_SOFTWARE_VERSION"
   (	"FACILITY_SOFTWARE_VERSION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SOFTWARE_VERSION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"EFFECTIVE_DATESTAMP" DATE NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_FACILITY_82" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_SOFTWARE_VERSION_01" FOREIGN KEY ("SOFTWARE_VERSION_NUM")
	  REFERENCES "TREXONE_DATA"."SOFTWARE_VERSION" ("SOFTWARE_VERSION_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_FACILITY_SOFTWARE_VERSION" ON "TREXONE_DATA"."FACILITY_SOFTWARE_VERSION" ("FACILITY_SOFTWARE_VERSION_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."FACILITY_SOFTWARE_VERSION" ADD CONSTRAINT "PK_FACILITY_SOFTWARE_VERSION" PRIMARY KEY ("FACILITY_SOFTWARE_VERSION_NUM")
  USING INDEX "TREXONE_DATA"."PK_FACILITY_SOFTWARE_VERSION"  ENABLE;
-- ==========================================
