-- ==========================================

  CREATE TABLE "TREXONE_DATA"."FACILITY_PRINTER_TRAY"
   (	"FACILITY_PRINTER_TRAY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_PRINTER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRINT_MEDIA_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TYPE" VARCHAR2(12) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DEFAULT_ORDER_OF_PREF" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_FACILITY_PRINTER_01" FOREIGN KEY ("FACILITY_PRINTER_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY_PRINTER" ("FACILITY_PRINTER_NUM") ENABLE,
	 CONSTRAINT "FK_PRINT_MEDIA_TYPE_02" FOREIGN KEY ("PRINT_MEDIA_TYPE_NUM")
	  REFERENCES "TREXONE_DATA"."PRINT_MEDIA_TYPE" ("PRINT_MEDIA_TYPE_NUM") ENABLE NOVALIDATE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_FACILITY_PRINTER_TRAY" ON "TREXONE_DATA"."FACILITY_PRINTER_TRAY" ("FACILITY_PRINTER_TRAY_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."FACILITY_PRINTER_TRAY" ADD CONSTRAINT "PK_FACILITY_PRINTER_TRAY" PRIMARY KEY ("FACILITY_PRINTER_TRAY_NUM")
  USING INDEX "TREXONE_DATA"."PK_FACILITY_PRINTER_TRAY"  ENABLE;
-- ==========================================
