-- ==========================================

  CREATE TABLE "TREXONE_DATA"."FACILITY_LINK"
   (	"FACILITY_LINK_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_LINK_TYPE" CHAR(1),
	"LINKED_FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"IS_ACTIVE" CHAR(1),
	"PRIORITY" NUMBER(3,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"FULFILLMENT_TYPE" CHAR(1),
	 CONSTRAINT "FK_FACILITY_19" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_FACILITY_65" FOREIGN KEY ("LINKED_FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_FACILITY_LINK" ON "TREXONE_DATA"."FACILITY_LINK" ("FACILITY_LINK_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."FACILITY_LINK" ADD CONSTRAINT "PK_FACILITY_LINK" PRIMARY KEY ("FACILITY_LINK_NUM")
  USING INDEX "TREXONE_DATA"."PK_FACILITY_LINK"  ENABLE;
-- ==========================================
