-- ==========================================

  CREATE TABLE "TREXONE_DATA"."FACILITY"
   (	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TYPE" CHAR(2) NOT NULL ENABLE,
	"LEGAL_NAME" VARCHAR2(30),
	"PRIMARY_CONTACT" VARCHAR2(40),
	"ALTERNATE_CONTACT" VARCHAR2(40),
	"FACILITY_ID" VARCHAR2(10),
	"IS_ACTIVE" CHAR(1),
	"PIC_NAME" VARCHAR2(30),
	"PIC_LICENSE" VARCHAR2(20),
	"PIC_INITIALS" VARCHAR2(3),
	"RP_NAME" VARCHAR2(30),
	"RP_LICENSE" VARCHAR2(20),
	"RP_INITIALS" VARCHAR2(3),
	"DEA_NUMBER" VARCHAR2(30),
	"NCPDP_PROVIDER_ID" VARCHAR2(30),
	"REMOTE_PROC_FLAG" CHAR(1),
	"INTERVIEW_MOD_FLAG" CHAR(1),
	"ROOT_LOCATION_GROUP_NUM" NUMBER(18,0),
	"WF_PROCESS_DEFINITION_NUM" NUMBER(18,0),
	"ACTIVE_DATE" DATE,
	"OPEN_DATE" DATE,
	"CLOSE_DATE" DATE,
	"STORE_LOCK_BOX_NUM" VARCHAR2(25),
	"SENIOR_CITIZEN_EFFECTIVE_DATE" DATE,
	"SENIOR_CITIZEN_AGE_LIMIT" NUMBER(3,0),
	"TIMEZONE_ID" VARCHAR2(60),
	"USER_DEFINED_INFO_1" VARCHAR2(255),
	"USER_DEFINED_INFO_2" VARCHAR2(255),
	"USER_DEFINED_INFO_3" VARCHAR2(255),
	"USER_DEFINED_INFO_4" VARCHAR2(255),
	"USER_DEFINED_INFO_5" VARCHAR2(255),
	"IS_IVR_ENABLED" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"IS_PPI_ENABLED" CHAR(1) DEFAULT 'N' NOT NULL ENABLE,
	"CONVERSION_TYPE_NUM" NUMBER(18,0),
	"CONVERSION_DATE" DATE,
	"FACILITY_STATUS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CF_PROCESSING_TIME" NUMBER(5,0),
	"LAST_VERIFY_USER" NUMBER(18,0),
	"LAST_VERIFY_TIME" DATE,
	"ETL_READY" CHAR(1),
	"OWNING_FACILITY_ID" VARCHAR2(10),
	"IS_CF_ENABLED" CHAR(1),
	"IS_CM_ENABLED" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"IS_LM_ENABLED" CHAR(1),
	"IS_CMS_PART_D" CHAR(1),
	"RETAIL_PHARMACY_SERVICE_TYPE" VARCHAR2(2),
	"MAIL_PHARMACY_SERVICE_TYPE" VARCHAR2(2),
	"LTC_PHARMACY_SERVICE_TYPE" VARCHAR2(2),
	"PHARMACIST_NPI" VARCHAR2(20),
	"COUNSELING_RPH_USER_NUM" NUMBER(18,0),
	"PIC_FIRST_NAME" VARCHAR2(30),
	"PIC_LAST_NAME" VARCHAR2(30),
	"DISPENSER_TYPE_CODE" VARCHAR2(2),
	"IS_MAIL_ORDER_ONLY" CHAR(1),
	 CONSTRAINT "FK_DATA_GROUP_06" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."DATA_GROUP" ("DATA_GROUP") ENABLE,
	 CONSTRAINT "FK_FACILITY_64" FOREIGN KEY ("CONVERSION_TYPE_NUM")
	  REFERENCES "TREXONE_DATA"."CONVERSION_TYPE" ("CONVERSION_TYPE_NUM") ENABLE,
	 CONSTRAINT "FK_FACILITY_STATUS_01" FOREIGN KEY ("FACILITY_STATUS_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY_STATUS" ("FACILITY_STATUS_NUM") ENABLE,
	 CONSTRAINT "FK_LOCATION_GROUP_02" FOREIGN KEY ("ROOT_LOCATION_GROUP_NUM")
	  REFERENCES "TREXONE_DATA"."LOCATION_GROUP" ("LOCATION_GROUP_NUM") ENABLE,
	 CONSTRAINT "FK_WF_PROCESS_DEFINITION_01" FOREIGN KEY ("WF_PROCESS_DEFINITION_NUM")
	  REFERENCES "TREXONE_DATA"."WF_PROCESS_DEFINITION" ("WF_PROCESS_DEFINITION_NUM") ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_27" FOREIGN KEY ("LAST_VERIFY_USER")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_28" FOREIGN KEY ("COUNSELING_RPH_USER_NUM")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE
   ) ;
  CREATE INDEX "TREXONE_DATA"."PK_FACILITY" ON "TREXONE_DATA"."FACILITY" ("FACILITY_NUM", "FACILITY_ID")
  ;
ALTER TABLE "TREXONE_DATA"."FACILITY" ADD CONSTRAINT "PK_FACILITY" PRIMARY KEY ("FACILITY_NUM")
  USING INDEX "TREXONE_DATA"."PK_FACILITY"  ENABLE;
-- ==========================================
