-- ==========================================

  CREATE TABLE "TREXONE_DATA"."FACILITY_ID"
   (	"FACILITY_ID_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_PLAN_NUM" NUMBER(18,0),
	"TP_BENEFIT_GROUP_ID" VARCHAR2(10),
	"TYPE" VARCHAR2(3),
	"VALUE" VARCHAR2(80),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"CTRY_CODE" VARCHAR2(8),
	"STATE_CODE" VARCHAR2(2),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_FACILITY_17" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_STATE_03" FOREIGN KEY ("CTRY_CODE", "STATE_CODE")
	  REFERENCES "TREXONE_DATA"."STATE" ("CTRY_CODE", "STATE_CODE") ENABLE,
	 CONSTRAINT "FK_TP_PLAN_02" FOREIGN KEY ("TP_PLAN_NUM")
	  REFERENCES "TREXONE_DATA"."TP_PLAN" ("TP_PLAN_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_FACILITY_ID" ON "TREXONE_DATA"."FACILITY_ID" ("FACILITY_ID_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."FACILITY_ID" ADD CONSTRAINT "PK_FACILITY_ID" PRIMARY KEY ("FACILITY_ID_NUM")
  USING INDEX "TREXONE_DATA"."PK_FACILITY_ID"  ENABLE;
-- ==========================================
