-- ==========================================

  CREATE TABLE "TREXONE_DATA"."FACILITY_LANGUAGE"
   (	"FACILITY_LANGUAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"LANGUAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"LANGUAGE_PRECEDENCE" NUMBER(9,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_FACILITY_18" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_LANGUAGE_01" FOREIGN KEY ("LANGUAGE_NUM")
	  REFERENCES "TREXONE_DATA"."LANGUAGE" ("LANGUAGE_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_FACILITY_LANGUAGE" ON "TREXONE_DATA"."FACILITY_LANGUAGE" ("FACILITY_LANGUAGE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."FACILITY_LANGUAGE" ADD CONSTRAINT "PK_FACILITY_LANGUAGE" PRIMARY KEY ("FACILITY_LANGUAGE_NUM")
  USING INDEX "TREXONE_DATA"."PK_FACILITY_LANGUAGE"  ENABLE;
-- ==========================================
