-- ==========================================

  CREATE TABLE "TREXONE_DATA"."FACILITY_PRINTER"
   (	"FACILITY_PRINTER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRINT_DEVICE_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"OS_NAME" VARCHAR2(60),
	"IS_ACTIVE" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_FACILITY_23" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_PRINT_DEVICE_TYPE_02" FOREIGN KEY ("PRINT_DEVICE_TYPE_NUM")
	  REFERENCES "TREXONE_DATA"."PRINT_DEVICE_TYPE" ("PRINT_DEVICE_TYPE_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_FACILITY_PRINTER" ON "TREXONE_DATA"."FACILITY_PRINTER" ("FACILITY_PRINTER_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."FACILITY_PRINTER" ADD CONSTRAINT "PK_FACILITY_PRINTER" PRIMARY KEY ("FACILITY_PRINTER_NUM")
  USING INDEX "TREXONE_DATA"."PK_FACILITY_PRINTER"  ENABLE;
-- ==========================================
