-- ==========================================

  CREATE TABLE "TREXONE_DATA"."FACILITY_LOGIN"
   (	"FACILITY_LOGIN_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SYSTEM_USER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"LOGIN_STATUS" CHAR(1) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"LAST_ACTIVITY" DATE,
	"LAST_SERVICE_CALL" VARCHAR2(500),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_FACILITY_20" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_07" FOREIGN KEY ("SYSTEM_USER_NUM")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE
   ) ;
  CREATE INDEX "TREXONE_DATA"."IN_FACILITY_LOGIN_1" ON "TREXONE_DATA"."FACILITY_LOGIN" ("SYSTEM_USER_NUM")
  ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_FACILITY_LOGIN" ON "TREXONE_DATA"."FACILITY_LOGIN" ("FACILITY_LOGIN_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."FACILITY_LOGIN" ADD CONSTRAINT "PK_FACILITY_LOGIN" PRIMARY KEY ("FACILITY_LOGIN_NUM")
  USING INDEX "TREXONE_DATA"."PK_FACILITY_LOGIN"  ENABLE;
ALTER TABLE "TREXONE_DATA"."FACILITY_LOGIN" ADD CONSTRAINT "UC_FACILITY_LOGIN_1" UNIQUE ("SYSTEM_USER_NUM")
  USING INDEX "TREXONE_DATA"."IN_FACILITY_LOGIN_1"  ENABLE;
-- ==========================================
