-- ==========================================

  CREATE TABLE "TREXONE_DATA"."FAST_TRACK_REASON"
   (	"FAST_TRACK_REASON_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"REASON_CODE" NUMBER(18,0) NOT NULL ENABLE,
	"REASON_DESCRIPTION" VARCHAR2(1000) NOT NULL ENABLE,
	"SHOULD_SKIP" CHAR(1) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_FAST_TRACK_REASON" PRIMARY KEY ("FAST_TRACK_REASON_NUM")
  USING INDEX  ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTOYMINTERVAL(3,'MONTH')) STORE IN ("LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
