-- ==========================================

  CREATE TABLE "TREXONE_DATA"."FAX_ORDER_OUT_ITEM"
   (	"FAX_ORDER_OUT_ITEM_NUM" NUMBER(18,0),
	"FAX_ORDER_OUT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"MEDICATION_TYPE" CHAR(1),
	"DRUG_DESC" VARCHAR2(105),
	"PRODUCT_CODE" VARCHAR2(35),
	"PRODUCT_CODE_QUALIFIER" CHAR(3),
	"STRENGTH" VARCHAR2(70),
	"DAYS_SUPPLY" VARCHAR2(35),
	"QUANTITY_VALUE" VARCHAR2(35),
	"DIRECTIONS" VARCHAR2(1000),
	"NOTES" VARCHAR2(210),
	"REFILLS_QUALIFIER" CHAR(3),
	"REFILLS_ALLOWED" VARCHAR2(35),
	"SUBSTITUTIONS" CHAR(3),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_FAX_ORDER_OUT_ITEM" PRIMARY KEY ("FAX_ORDER_OUT_ITEM_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_98" FOREIGN KEY ("SYS_USER")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_FAX_ORDER_OUT_01" FOREIGN KEY ("FAX_ORDER_OUT_NUM")
	  REFERENCES "TREXONE_DATA"."FAX_ORDER_OUT" ("FAX_ORDER_OUT_NUM") ENABLE NOVALIDATE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTOYMINTERVAL(3,'MONTH')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
