-- ==========================================

  CREATE TABLE "TREXONE_DATA"."FAX_ORDER_IN"
   (	"FAX_ORDER_IN_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ELECTRONIC_ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"IMAGE_NUM" NUMBER(18,0),
	"FROM_FAX_NUM" VARCHAR2(12) NOT NULL ENABLE,
	"TO_FAX_NUM" VARCHAR2(12) NOT NULL ENABLE,
	"SENDER_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"RECIPIENT_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"NUM_PAGES" NUMBER(2,0) NOT NULL ENABLE,
	"RX_FILL_SEQ" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"IMAGE_PROC_STATUS" CHAR(1) DEFAULT 'S' NOT NULL ENABLE,
	"PATIENT_NUM" NUMBER(22,0),
	 CONSTRAINT "FK_ELECTRONIC_ORDER_01" FOREIGN KEY ("ELECTRONIC_ORDER_NUM")
	  REFERENCES "TREXONE_DATA"."ELECTRONIC_ORDER" ("ELECTRONIC_ORDER_NUM") ENABLE,
	 CONSTRAINT "FK_FACILITY_26" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_IMAGE_07" FOREIGN KEY ("IMAGE_NUM")
	  REFERENCES "TREXONE_DATA"."IMAGE" ("IMAGE_NUM") ENABLE,
	 CONSTRAINT "FK_RX_FILL_10" FOREIGN KEY ("RX_FILL_SEQ", "RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_FILL" ("RX_FILL_SEQ", "RX_RECORD_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_FAX_ORDER_IN" ON "TREXONE_DATA"."FAX_ORDER_IN" ("FAX_ORDER_IN_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."FAX_ORDER_IN" ADD CONSTRAINT "PK_FAX_ORDER_IN" PRIMARY KEY ("FAX_ORDER_IN_NUM")
  USING INDEX "TREXONE_DATA"."PK_FAX_ORDER_IN"  ENABLE;
-- ==========================================
