-- ==========================================

  CREATE TABLE "TREXONE_DATA"."FILL_STATUS"
   (	"FILL_STATUS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(30) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_FILL_STATUS" ON "TREXONE_DATA"."FILL_STATUS" ("FILL_STATUS_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."FILL_STATUS" ADD CONSTRAINT "PK_FILL_STATUS" PRIMARY KEY ("FILL_STATUS_NUM")
  USING INDEX "TREXONE_DATA"."PK_FILL_STATUS"  ENABLE;
-- ==========================================
