-- ==========================================

  CREATE TABLE "TREXONE_DATA"."FINANCIAL_EVENT"
   (	"FINANCIAL_EVENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"EVENT_LEVEL" CHAR(1) NOT NULL ENABLE,
	"TYPE_NUM" NUMBER(9,0) NOT NULL ENABLE,
	"OCCURRED" TIMESTAMP (6) NOT NULL ENABLE,
	"ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ITEM_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_FILL_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"IS_CASH" CHAR(1) NOT NULL ENABLE,
	"IS_BAR" CHAR(1) NOT NULL ENABLE,
	"IS_LAST_PAYER" CHAR(1) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"TP_ITEM_CLAIM_NUM" NUMBER(18,0),
	"TP_MESSAGE_NUM" NUMBER(18,0),
	"TP_CASH_MESSAGE_NUM" NUMBER(18,0),
	"PRICE_CALC_RESULT_NUM" NUMBER(18,0),
	"ADJUDICATION_GROUP_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "CK_FINANCIAL_EVENT_1" CHECK (EVENT_LEVEL IN ( 'C', 'F' )) ENABLE,
	 CONSTRAINT "CK_FINANCIAL_EVENT_3" CHECK (IS_CASH IN ('Y', 'N')) ENABLE,
	 CONSTRAINT "CK_FINANCIAL_EVENT_4" CHECK (IS_BAR IN ('Y', 'N')) ENABLE,
	 CONSTRAINT "CK_FINANCIAL_EVENT_5" CHECK (IS_LAST_PAYER IN ('Y', 'N')) ENABLE,
	 CONSTRAINT "PK_FINANCIAL_EVENT" PRIMARY KEY ("FINANCIAL_EVENT_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "CK_FINANCIAL_EVENT_2" CHECK (TYPE_NUM BETWEEN 1 and 26) ENABLE,
	 CONSTRAINT "FK_FINANCIAL_EVENT_07" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_FINANCIAL_EVENT_01" FOREIGN KEY ("ORDER_NUM", "ITEM_SEQ")
	  REFERENCES "TREXONE_DATA"."ITEM" ("ORDER_NUM", "ITEM_SEQ") ENABLE,
	 CONSTRAINT "FK_FINANCIAL_EVENT_05" FOREIGN KEY ("TP_ITEM_CLAIM_NUM")
	  REFERENCES "TREXONE_DATA"."TP_ITEM_CLAIM" ("TP_ITEM_CLAIM_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
