-- ==========================================

  CREATE TABLE "TREXONE_DATA"."FORMULARY"
   (	"FORMULARY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"IS_POSITIVE" CHAR(1) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DATA_GROUP_07" FOREIGN KEY ("DATA_GROUP")
	  REFERENCES "TREXONE_DATA"."DATA_GROUP" ("DATA_GROUP") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_FORMULARY" ON "TREXONE_DATA"."FORMULARY" ("FORMULARY_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."FORMULARY" ADD CONSTRAINT "PK_FORMULARY" PRIMARY KEY ("FORMULARY_NUM")
  USING INDEX "TREXONE_DATA"."PK_FORMULARY"  ENABLE;
-- ==========================================
