-- ==========================================

  CREATE TABLE "TREXONE_DATA"."FREQUENCY"
   (	"FREQUENCY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TYPE" CHAR(1) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PERIOD1" CHAR(1),
	"REVERSE1" CHAR(1),
	"PERIOD2" CHAR(1),
	"REVERSE2" CHAR(1),
	"COUNT1" NUMBER(9,0),
	"COUNT2" NUMBER(9,0),
	"START_DATE" DATE,
	"END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_FREQUENCY" PRIMARY KEY ("FREQUENCY_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
