-- ==========================================

  CREATE TABLE "TREXONE_DATA"."GCN_EXCLUSION"
   (	"GCN_EXCLUSION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"GCN_SEQ" VARCHAR2(30) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_GCN_EXCLUSION" ON "TREXONE_DATA"."GCN_EXCLUSION" ("GCN_EXCLUSION_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."GCN_EXCLUSION" ADD CONSTRAINT "PK_GCN_EXCLUSION" PRIMARY KEY ("GCN_EXCLUSION_NUM")
  USING INDEX "TREXONE_DATA"."PK_GCN_EXCLUSION"  ENABLE;
-- ==========================================
