-- ==========================================

  CREATE TABLE "TREXONE_DATA"."GEOGRAPHIC_CODE"
   (	"GEOGRAPHIC_CODE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"GEOGRAPHIC_CODE_TYPE" VARCHAR2(4) NOT NULL ENABLE,
	"GEOGRAPHIC_CODE" VARCHAR2(30) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(300) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_GEOGRAPHIC_CODE" ON "TREXONE_DATA"."GEOGRAPHIC_CODE" ("GEOGRAPHIC_CODE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."GEOGRAPHIC_CODE" ADD CONSTRAINT "PK_GEOGRAPHIC_CODE" PRIMARY KEY ("GEOGRAPHIC_CODE_NUM")
  USING INDEX "TREXONE_DATA"."PK_GEOGRAPHIC_CODE"  ENABLE;
-- ==========================================
