-- ==========================================

  CREATE TABLE "TREXONE_DATA"."GOOD_FAITH_EFFORT_REASON"
   (	"GOOD_FAITH_EFFORT_REASON_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(45),
	"SATISFY_ATTEMPTS_NUM" NUMBER(2,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_GOOD_FAITH_EFFORT_REASON" ON "TREXONE_DATA"."GOOD_FAITH_EFFORT_REASON" ("GOOD_FAITH_EFFORT_REASON_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."GOOD_FAITH_EFFORT_REASON" ADD CONSTRAINT "PK_GOOD_FAITH_EFFORT_REASON" PRIMARY KEY ("GOOD_FAITH_EFFORT_REASON_NUM")
  USING INDEX "TREXONE_DATA"."PK_GOOD_FAITH_EFFORT_REASON"  ENABLE;
-- ==========================================
