-- ==========================================

  CREATE TABLE "TREXONE_DATA"."GROUPS"
   (	"GROUP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(30) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(300),
	"TYPE" CHAR(1) NOT NULL ENABLE,
	"IS_ACTIVE" CHAR(1) NOT NULL ENABLE,
	"IS_EXTERNALLY_MAINTAINED" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE INDEX "TREXONE_DATA"."PK_GROUPS" ON "TREXONE_DATA"."GROUPS" ("GROUP_NUM", "TYPE")
  ;
ALTER TABLE "TREXONE_DATA"."GROUPS" ADD CONSTRAINT "PK_GROUPS" PRIMARY KEY ("GROUP_NUM")
  USING INDEX "TREXONE_DATA"."PK_GROUPS"  ENABLE;
-- ==========================================
