-- ==========================================

  CREATE GLOBAL TEMPORARY TABLE "TREXONE_DATA"."GTT_ORDER_QUEUE_SESSION"
   (	"ITEM_PRIORITY" NUMBER(18,0),
	"PICKUP_DATE_TIME" DATE,
	"ORDER_NUMBER" VARCHAR2(10),
	"NUMBER_OF_ITEMS_IN_ORDER" NUMBER(9,0),
	"PACK_OR_COMBO_STATUS" VARCHAR2(100),
	"SHIP_STATUS" VARCHAR2(100),
	"PATIENT_FULL_NAME" VARCHAR2(100),
	"TRANSACTION_TYPE" VARCHAR2(100),
	"EXCEPTION_STATUS" VARCHAR2(200),
	"MIN_LOCK_USER" NUMBER(18,0),
	"MAX_LOCK_USER" NUMBER(18,0),
	"STATUS" VARCHAR2(100),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"ORDER_NUM" NUMBER(18,0)
   ) ON COMMIT PRESERVE ROWS ;
-- ==========================================
