-- ==========================================

  CREATE GLOBAL TEMPORARY TABLE "TREXONE_DATA"."GTT_PO_INV_ITEM"
   (	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"INVENTORY_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRODUCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID')
   ) ON COMMIT PRESERVE ROWS ;
-- ==========================================
