-- ==========================================

  CREATE GLOBAL TEMPORARY TABLE "TREXONE_DATA"."GTT_INVENTORY_ADJUST"
   (	"SEQ_NUM" NUMBER NOT NULL ENABLE,
	"FACILITY_ID" VARCHAR2(50),
	"NDC" VARCHAR2(50),
	"OVERRIDE_YN" CHAR(1),
	"REQUEST_QTY" NUMBER,
	"BEFORE_QTY" NUMBER,
	"APPLIED_QTY" NUMBER,
	"AFTER_QTY" NUMBER,
	"STATUS" VARCHAR2(20),
	"ERROR_CODE" NUMBER,
	"ERROR_MESSAGE" VARCHAR2(4000),
	"STEP_TYPE" VARCHAR2(50),
	"IDENTIFIER" VARCHAR2(50),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT NVL(sys_context('ERX_CONTEXT','ERX_CLIENT_ID') , 'ERX'),
	"LOT_NUMBER" VARCHAR2(20),
	"SERIAL_NUMBER" VARCHAR2(20),
	"EXP_DATE" VARCHAR2(20),
	"RTS" CHAR(1),
	 CHECK (RTS IN ('Y', 'N')) ENABLE
   ) ON COMMIT DELETE ROWS ;
-- ==========================================
