-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_ACC_STMT_CHARGE_SUMMARY"
   (	"ACC_STMT_CHARGE_SUMMARY_NUM" NUMBER(18,0),
	"ACC_STATEMENT_NUM" NUMBER(18,0),
	"BUCKET_ORDER" NUMBER(9,0),
	"BUCKET_DESCRIPTION" VARCHAR2(1000),
	"BUCKET_MESSAGE" VARCHAR2(1000),
	"AMOUNT" NUMBER(17,6),
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE,
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
