-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_ACC_PAYMENT"
   (	"ACC_PAYMENT_NUM" NUMBER(18,0),
	"ACC_PAYMENT_TYPE_NUM" NUMBER(18,0),
	"ACC_TX_NUM" NUMBER(18,0),
	"CARD_HOLDER" VARCHAR2(200),
	"DEBIT_INSTITUTION" VARCHAR2(200),
	"CHECK_NAME" VARCHAR2(200),
	"CHECK_DATE" DATE,
	"CHECK_NUMBER" VARCHAR2(20),
	"CHECK_ROUTING_NUMBER" VARCHAR2(20),
	"CHECK_ACCOUNT_NUMBER" VARCHAR2(20),
	"COUPON_TYPE" VARCHAR2(20),
	"COUPON_NAME" VARCHAR2(20),
	"COUPON_EXPIRATION" DATE,
	"GIFT_CARD_NUMBER" VARCHAR2(20),
	"CREDIT_CARD_TYPE" VARCHAR2(20),
	"VOUCHER_TYPE" VARCHAR2(20),
	"VOUCHER_NUMBER" VARCHAR2(20),
	"VOUCHER_EXPIRATION" DATE,
	"PAYER" VARCHAR2(200),
	"AMOUNT_PAID" NUMBER(17,6),
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE,
	"PARTITION_DATE" DATE,
	"AUTHORIZATION_NUMBER" VARCHAR2(20),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
