-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_ACCOUNT"
   (	"ACCOUNT_NUM" NUMBER(18,0),
	"ACCOUNT_NUMBER" VARCHAR2(30),
	"STATUS" CHAR(1),
	"APPLY_FINANCE_CHARGE_OVERRIDE" CHAR(1),
	"FINANCE_CHG_PERCENT_OVERRIDE" NUMBER(16,8),
	"FINANCE_CHARGE_DAYS_OVERRIDE" NUMBER(9,0),
	"PAYMENT_DISC_ALLOWED_OVERRIDE" CHAR(1),
	"PAYMENT_DISC_PERCENT_OVERRIDE" NUMBER(16,8),
	"PAYMENT_DISCOUNT_DAYS_OVERRIDE" NUMBER(9,0),
	"APPLY_MISC_CHG_TAX" CHAR(1),
	"LAST_CLOSED_DATE" DATE,
	"MERGED_INTO_ACCOUNT" NUMBER(18,0),
	"LOCK_USER" NUMBER(18,0),
	"LOCK_DATE" DATE,
	"ALLOW_HOUSE_CHARGE" CHAR(1),
	"USE_AR" CHAR(1),
	"PRINT_STATEMENT" CHAR(1),
	"PRINT_DUNNING_MSG_OVERRIDE" CHAR(1),
	"APPLY_RECURRING_CHG_TAX" CHAR(1),
	"CREATE_DATE" DATE,
	"DATA_GROUP" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null,
	"DEFAULT_ACCOUNT_MEMBER_CC_NUM" NUMBER(18,0),
	"DEFAULT_SHIPPING_ADDRESS_NUM" NUMBER(18,0),
	"USE_ACCOUNT_CREDIT_CARD" CHAR(1)
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
