-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_ANCILLARY_ITEM_COMMIT"
   (	"ANCILLARY_ITEM_COMMIT_NUM" NUMBER(18,0),
	"ORDER_NUM" NUMBER(18,0),
	"ANCILLARY_ITEM_NUM" NUMBER(18,0),
	"COMMIT_TYPE_NUM" NUMBER(18,0),
	"QUANTITY" NUMBER(16,8),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"FACILITY_ITEM_NUM" VARCHAR2(10),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID'),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" VARCHAR2(100),
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"DATESTAMP" DATE
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
