-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_CLINICAL_PROGRAM_STATUS"
   (	"CLINICAL_PROGRAM_STATUS_NUM" NUMBER(18,0),
	"CLINICAL_PROGRAM_NUM" NUMBER(18,0),
	"PROGRAM_STATUS_CODE" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"PATIENT_NUM" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" CHAR(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
