-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_D_INV_PRIMARY_VENDOR"
   (	"INVENTORY_ITEM_NUM" NUMBER(18,0),
	"PRIMARY_VENDOR_NUM" NUMBER(18,0),
	"PRODUCT_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(18,0),
	"DATESTAMP" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
