-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_DSCSA_SHIPPED_ITEM"
   (	"DSCSA_SHIPPED_ITEM_NUM" NUMBER(18,0),
	"DSCSA_DOCUMENT_NUM" NUMBER(18,0),
	"GTIN" VARCHAR2(100),
	"NDC" VARCHAR2(20),
	"LOT_NUMBER" VARCHAR2(100),
	"SERIAL_NUMBER" VARCHAR2(100),
	"EXPIRATION_DATE" VARCHAR2(10),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PARTITION_DATE" DATE,
	"H_LEVEL" NUMBER,
	"H_TYPE" VARCHAR2(1),
	"DOCUMENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
