-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_DT_DRUG"
   (	"DT_TX_NUM" NUMBER(19,0),
	"FACILITY_NUM" NUMBER(18,0),
	"PRODUCT" VARCHAR2(35),
	"MANUFACTURER" VARCHAR2(30),
	"NDC_MFG" CHAR(5),
	"NDC_PRODUCT" CHAR(4),
	"NDC_SIZE" CHAR(2),
	"DRUG_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"DISTRIBUTOR" VARCHAR2(30),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"PRODUCT_NUM" NUMBER(18,0),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
