-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_DUR_CONFLICT_PREGNANCY"
   (	"DUR_CONFLICT_NUM" NUMBER(18,0),
	"COMMENTARY_OLD" VARCHAR2(4000) INVISIBLE,
	"DESCRIPTION" VARCHAR2(255),
	"DRUG_CUSTOM_ID" VARCHAR2(15),
	"DRUG_DESC" VARCHAR2(50),
	"DRUG_ID" VARCHAR2(15),
	"ID" VARCHAR2(15),
	"SCREEN_MESSAGE" VARCHAR2(4000),
	"SEVERITY" CHAR(5),
	"PATIENT_AGE" NUMBER(9,0),
	"PREGNANCY_REPORTED_DATE" DATE,
	"LACTATION_REPORTED_DATE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null,
	"SEVERITY_TEXT" VARCHAR2(200),
	"COMMENTARY" CLOB,
	"PLACENTAL_TRANSFER_CODE" VARCHAR2(5)
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
