-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_EREFERRAL_ITEM_ATTACHMENT"
   (	"EREFERRAL_ITEM_ATTACHMENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FILENAME" VARCHAR2(255) NOT NULL ENABLE,
	"IMAGE_PROC_STATUS" CHAR(1),
	"EREFERRAL_ITEM_NUM" NUMBER(18,0),
	"IMAGE_GROUP_NUM" NUMBER(18,0),
	"ASSET_GROUP_ID" VARCHAR2(100),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"DATESTAMP" DATE DEFAULT SYSDATE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
