-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_IMG_ANNOTATION_NOTE"
   (	"IMG_ANNOTATION_NOTE_SEQ" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"NOTE_TEXT" VARCHAR2(4000),
	"CREATE_USER" NUMBER(18,0),
	"CREATE_DATE" DATE,
	"PARTITION_DATE" DATE,
	"FACILITY_NUM" NUMBER(18,0),
	"FONT_SIZE" NUMBER(3,0),
	"ANNOTATION_UID" VARCHAR2(40),
	"IMAGE_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" CHAR(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
