-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_LTC_FACILITY"
   (	"LTC_FACILITY_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"NAME" VARCHAR2(32),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"LTC_FACILITY_NODE_NUM" NUMBER(18,0),
	"TYPE" VARCHAR2(10),
	"NUMBER_OF_BEDS" NUMBER(9,0),
	"TERMINATION_DATE" DATE,
	"EFFECTIVE_DATE" DATE,
	"REACTIVATION_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null,
	"IS_CMS_PART_D" CHAR(1),
	"FACILITY_ID" VARCHAR2(10),
	"PLACE_OF_SERVICE" VARCHAR2(2)
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
