-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_OUTBOUND_EMAIL_ORDER_ITEM"
   (	"OUTBOUND_EMAIL_ORDER_ITEM_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"PATIENT_NUM" NUMBER(18,0),
	"ORDER_NUM" NUMBER(18,0),
	"RX_NUM" NUMBER(18,0),
	"ITEM_NUM" NUMBER(18,0),
	"ITEM_QTY" NUMBER(18,0),
	"ITEM_PRICE" NUMBER(18,4),
	"ITEM_TAX" NUMBER(18,4),
	"NUM_REFILLS" NUMBER(18,0),
	"DAYS_SUPPLY" NUMBER(18,0),
	"ITEM_NAME" VARCHAR2(50),
	"STATUS" VARCHAR2(12),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"COMMUNICATION_DATE" DATE
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
