-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_PATIENT_EXTRA_MEDICATION"
   (	"PATIENT_EXTRA_MEDICATION_NUM" NUMBER(18,0),
	"PATIENT_NUM" NUMBER(18,0),
	"PRODUCT_NUM" NUMBER(18,0),
	"QUANTITY" NUMBER(10,3),
	"DAYS_SUPPLY" NUMBER(10,3),
	"QTY_PER_DOSE" NUMBER(10,3),
	"FREQUENCY" NUMBER(10,3),
	"IS_ACTIVE" CHAR(1),
	"CREATE_DATE" DATE,
	"CREATE_USER" NUMBER(18,0),
	"DATA_GROUP" NUMBER(18,0),
	"EFFECTIVE_DATE" DATE,
	"TERMINATION_DATE" DATE,
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"DIRECTIONS" VARCHAR2(2000),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
