-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_PAYMENT_GROUP_LIST"
   (	"PAYMENT_GROUP_NUM" NUMBER(18,0),
	"PAYMENT_GROUP_SEQ" NUMBER(18,0),
	"PAYMENT_NUM" NUMBER(18,0),
	"PAYMENT_GROUP_LIST_AMOUNT" NUMBER(17,6),
	"APPLY_BALANCE_PERCENTAGE_RATE" NUMBER(9,0),
	"PARTITION_DATE" DATE,
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE DEFAULT null,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
