-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_PATIENT_EXTRA_TP_INFO"
   (	"PATIENT_EXTRA_TP_INFO_NUM" NUMBER(18,0),
	"GUARANTOR_MIDDLE_NAME" VARCHAR2(30),
	"PATIENT_NUM" NUMBER(18,0),
	"GUARANTOR_FIRST_NAME" VARCHAR2(30),
	"GUARANTOR_LAST_NAME" VARCHAR2(30),
	"GUARANTOR_SUFFIX_ABBR" VARCHAR2(12),
	"SERVICE_FACILITY_NAME" VARCHAR2(30),
	"SERVICE_FACILITY_ID_QUALIFIER1" VARCHAR2(10),
	"SERVICE_FACILITY_ID1" VARCHAR2(30),
	"SERVICE_FACILITY_ID_QUALIFIER2" VARCHAR2(10),
	"SERVICE_FACILITY_ID2" VARCHAR2(30),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
