-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_PRICE_BOARD_REPORT"
   (	"FACILITY_NUM" NUMBER(18,0),
	"PRODUCT_NUM" NUMBER(18,0),
	"PRICE_ON_DATE" DATE,
	"DISPENSED_QTY" NUMBER(16,8),
	"PRICE" NUMBER(17,6),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" CHAR(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1, 'DAY'))
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2013-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
