-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_PRODUCT_EXCLUSION"
   (	"PRODUCT_EXCLUSION_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"PRODUCT_NUM" NUMBER(18,0),
	"DEA_CLASS" CHAR(1),
	"GC3_CODE" VARCHAR2(20),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null,
	"FACILITY_TYPE" CHAR(1)
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
