-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_PRESCRIBER_BASE"
   (	"PRESCRIBER_BASE_NUM" NUMBER(18,0),
	"PRESCRIBER_NUM" NUMBER(18,0),
	"SOURCE_CODE" CHAR(1),
	"STATUS" CHAR(1),
	"INACTIVITY_CODE" VARCHAR2(4),
	"INACTIVE_STATUS_DATE" DATE,
	"TITLE_ABBR" VARCHAR2(10),
	"SALUTATION_ABBR" VARCHAR2(10),
	"FIRST_NAME" VARCHAR2(30),
	"MIDDLE_NAME" VARCHAR2(30),
	"LAST_NAME" VARCHAR2(30),
	"NAME_SUFFIX_ABBR" VARCHAR2(10),
	"GENDER_CODE" VARCHAR2(1),
	"SPECIALTY_1" VARCHAR2(20),
	"SPECIALTY_2" VARCHAR2(20),
	"SPECIALTY_3" VARCHAR2(20),
	"PROFESSIONAL_ACTIVITY" VARCHAR2(20),
	"DECEASED_DATE" DATE,
	"EMAIL_ADDRESS" VARCHAR2(256),
	"PRESCRIBER_TYPE" VARCHAR2(4),
	"PREFERRED_CONTACT_METHOD" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LICENSE_STATUS" CHAR(1),
	"SPECIALTY_4" VARCHAR2(20),
	"SPECIALTY_5" VARCHAR2(20),
	"BIRTH_DATE" DATE,
	"SOCIAL_SECURITY_NUM" VARCHAR2(9),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
