-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_PRC_OVERRIDE_CD_VAL"
   (	"PRICING_OVERRIDE_CDE_VALUE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRICING_OVERRIDE_CODE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"VALUE" VARCHAR2(255) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" CHAR(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1, 'DAY'))
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2013-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
