-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_PRICE_LINK_RULE"
   (	"PRICE_LINK_RULE_NUM" NUMBER(18,0),
	"PRICE_LINK_RULE_SET_NUM" NUMBER(18,0),
	"MASTER_PRODUCT_NUM" NUMBER(18,0),
	"PROCESS_ORDER" NUMBER(9,0),
	"EXCLUDE_FROM_LINKING" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"DATA_FILTER" CLOB,
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" CHAR(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1, 'DAY'))
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2013-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
