-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_PRESCRIBER"
   (	"PRESCRIBER_NUM" NUMBER(18,0),
	"SUPV_PRESCRIBER_NUM" NUMBER(18,0),
	"ACTIVE_PRESCRIBER_NUM" NUMBER(18,0),
	"STATUS" CHAR(1),
	"INACTIVITY_CODE" VARCHAR2(4),
	"PREF_GENERIC_IF_AVAIL" CHAR(1),
	"PREF_THERAPEUTIC_SUB" CHAR(1),
	"CONTACT_METHOD_NUM" NUMBER(18,0),
	"ON_HOLD" CHAR(1),
	"SOURCE_CODE" CHAR(1),
	"ESV_MATCHED_IND" CHAR(1),
	"ESV_PRESCRIBER_ID" VARCHAR2(50),
	"VALIDATED" CHAR(1),
	"CREATE_DATE" DATE,
	"INTERNALLY_VALIDATED" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"NEEDS_REFRESHED" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null,
	"VALIDATED_BY_USER" NUMBER(18,0),
	"VALIDATED_DATESTAMP" DATE,
	"REACTIVATE_DATE" DATE,
	"CREATED_BY_CODE" CHAR(1)
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
