-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_PURCHASE_ORDER"
   (	"PURCHASE_ORDER_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"VENDOR_NUM" NUMBER(18,0),
	"PO_NUMBER" VARCHAR2(10),
	"CREATE_DATE" DATE,
	"CREATE_USER" NUMBER(18,0),
	"EXPIRATION_DATE" DATE,
	"PURCHASE_ORDER_TYPE_CODE" CHAR(1),
	"STATUS_CODE" CHAR(1),
	"RECEIVED_DATE" DATE,
	"IS_SCHEDULE_2_ORDER" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null,
	"EXTERNAL_REFERENCE_ID" VARCHAR2(100),
	"MCK_CONNECT_PO_STATUS" CHAR(1),
	"SUPPLIER_PO_NUMBER" VARCHAR2(22),
	"ADDITIONAL_PO_NUMBERS" VARCHAR2(255)
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
