-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_READJUDICATION_REQUEST_TP"
   (	"READJUDICATION_REQUEST_TP_NUM" NUMBER(18,0),
	"READJUDICATION_REQUEST_NUM" NUMBER(18,0),
	"TP_PATIENT_NUM" NUMBER(18,0),
	"BILLING_ORDER" NUMBER(9,0),
	"STATUS" VARCHAR2(100),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PARTITION_DATE" DATE,
	"H_LEVEL" NUMBER,
	"H_TYPE" VARCHAR2(1)
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
