-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_RX_TRANSFER_HISTORY"
   (	"RX_TRANSFER_SEQ" NUMBER(18,0),
	"RX_HISTORY_SEQ" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"FILL_NUM" NUMBER(9,0),
	"PRODUCT_NDC" VARCHAR2(11),
	"QTY_DISPENSED" NUMBER(10,3),
	"FILL_DATE" DATE,
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
