-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_RX_REMS"
   (	"RX_REM_NUM" NUMBER(18,0),
	"RX_FILL_SEQ" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"PRODUCT_NUM" NUMBER(18,0),
	"AUTHORIZATION_ID" VARCHAR2(20),
	"AUTHORIZATION_ID_DATE" DATE,
	"DISPENSING_ID" VARCHAR2(20),
	"DISPENSING_ID_DATE" DATE,
	"CANCEL_ID" VARCHAR2(20),
	"CANCEL_ID_DATE" DATE,
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1, 'DAY')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
