-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_SHIPPING_COURIER"
   (	"SHIPPING_COURIER_NUM" NUMBER(18,0),
	"COURIER_NAME" VARCHAR2(50),
	"IS_DEFAULT_COURIER" CHAR(1),
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SHIPPING_PROCESSOR_NUM" NUMBER(18,0)
   ) ;
-- ==========================================
