-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_SHIPMENT_SIGNATURE"
   (	"SHIPMENT_SIGNATURE_NUM" NUMBER(18,0),
	"DESCRIPTION" VARCHAR2(100),
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null,
	"ARCHIVE_LEVEL" NUMBER(9,0)
   ) ;
-- ==========================================
