-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_SPECIALTY_PROG_CONFIG"
   (	"SPECIALTY_PROG_CONFIG_NUM" NUMBER(18,0),
	"SPECIALTY_PROGRAM_NUM" NUMBER(18,0),
	"DATA_GROUP" NUMBER(18,0),
	"DISPLAY_FOR_SELECTION" CHAR(1),
	"STOP_REFILLS_IN_PV2" CHAR(1),
	"REQUIRE_ELIGIBILITY_START_DATE" CHAR(1),
	"REQUIRE_ELIGIBILITY_END_DATE" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE,
	"SYS_USER" NUMBER(18,0),
	"H_LEVEL" NUMBER,
	"H_TYPE" VARCHAR2(1)
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
