-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_SPECIALTY_ID_PARAM_TYPE"
   (	"SPECIALTY_ID_PARAM_TYPE_NUM" NUMBER(18,0),
	"NAME" VARCHAR2(40),
	"DISPLAY_NAME" VARCHAR2(40),
	"IS_SYSTEM" CHAR(1),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1, 'DAY')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
