-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_TP_MEDICAID_CODE_ATTRIBUTE"
   (	"TP_MEDICAID_CODE_ATTRIBUTE_NUM" NUMBER(18,0),
	"TP_MEDICAID_LOAD_NUM" NUMBER(18,0),
	"TP_MEDICAID_DRUG_ATTRIBUTE_NUM" NUMBER(18,0),
	"STATE_CODE" VARCHAR2(2),
	"DP_CODE" VARCHAR2(4),
	"DP_DESCRIPTION" VARCHAR2(50),
	"DP_CODE_TYPE" VARCHAR2(12),
	"DEFAULT_WARN_LEV" NUMBER(9,0),
	"DEFAULT_PRE_EDIT_MESSAGE" VARCHAR2(255),
	"DEFAULT_DATA_FILTER_NAME" VARCHAR2(60),
	"DEFAULT_DATA_FILTER" VARCHAR2(2000),
	"ACTIVE_STATUS" VARCHAR2(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
