-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_TP_ADJ_DRIVER_CONFIG"
   (	"TP_ADJ_DRIVER_CONFIG_NUM" NUMBER(18,0),
	"TP_ADJ_DRIVER_NUM" NUMBER(18,0),
	"CONFIGURATION_NAME" VARCHAR2(80),
	"CONFIGURATION" VARCHAR2(4000),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
