-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_USER_QUEUE_PREF_NON_WF"
   (	"USER_QUEUE_PREF_NON_WF_NUM" NUMBER(18,0),
	"NAME" NVARCHAR2(60),
	"SYSTEM_USER_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"QUEUE_NAME" VARCHAR2(10),
	"ORDER_SOURCE_TYPE_NUM" NUMBER(18,0),
	"FAX_NUMBER" NUMBER(10,0),
	"PRODUCT_NAME" VARCHAR2(100),
	"PRESCRIBER_FIRST_NAME" VARCHAR2(35),
	"PRESCRIBER_LAST_NAME" VARCHAR2(35),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE,
	"SYS_USER" NUMBER(18,0),
	"H_LEVEL" NUMBER,
	"H_TYPE" VARCHAR2(1),
	"ERROR_CODES" VARCHAR2(4000)
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
