-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_VENDOR_OVERRIDE"
   (	"PURCHASING_PLAN_ITEM_NUM" NUMBER(18,0),
	"VENDOR_NUM" NUMBER(18,0),
	"MINIMUM_QTY" NUMBER(12,3),
	"MAXIMUM_QTY" NUMBER(12,3),
	"MIN_DAYS_SUPPLY" NUMBER(9,0),
	"MAX_DAYS_SUPPLY" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null,
	"H_TYPE" CHAR(1),
	"H_LEVEL" NUMBER(20,0),
	"LOGIN_FACILITY_NUM" NUMBER(18,0)
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
