-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_WF_USER_ITEM"
   (	"WF_PROCESS_DEFINITION_NUM" NUMBER(18,0),
	"PROC_INST_SEQ" NUMBER(18,0),
	"NODE_SEQ" NUMBER(18,0),
	"NODE_INSTANCE_SEQ" NUMBER(18,0),
	"WF_BLOCK_DEFINITION_NUM" NUMBER(18,0),
	"NODE_STATE" VARCHAR2(30),
	"STATE_DATE" DATE,
	"ACTIVATED_DATE" DATE,
	"COMPLETION_DATE" DATE,
	"PRIORITY" NUMBER(18,0),
	"DECISION_VALUE" NUMBER(18,0),
	"COMPLETE_USER" NUMBER(18,0),
	"COMPLETE_FACILITY_NUM" NUMBER(18,0),
	"CREATE_DATE" DATE,
	"LOCK_USER" NUMBER(18,0),
	"LOCK_DATE" DATE,
	"GROUP_ID" NUMBER(18,0),
	"RESERVE_USER" NUMBER(18,0),
	"RESERVE_UNTIL" DATE,
	"IS_HIDDEN" CHAR(1),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_DATE" DATE,
	"FACILITY_NUM" NUMBER(18,0),
	"DECLINE_REASON" VARCHAR2(40),
	"APPLICATION_VERSION" VARCHAR2(8),
	"LOCK_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" CHAR(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
