-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_WF_BLOCK_DEFINITION"
   (	"WF_BLOCK_DEFINITION_NUM" NUMBER(18,0),
	"DESCRIPTION" VARCHAR2(60),
	"DATESTAMP" DATE,
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"APPLICATION_VERSION" VARCHAR2(8),
	"BLOCK_CODE" VARCHAR2(2),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null,
	"DISPLAY_DESCRIPTION" VARCHAR2(100)
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
