-- ==========================================

  CREATE TABLE "TREXONE_DATA"."HEALTH_CARD_RANGE"
   (	"HEALTH_CARD_RANGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"HEALTH_CARD_BIN_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"HEALTH_CARD_RANGE_LOW" NUMBER(20,0) NOT NULL ENABLE,
	"HEALTH_CARD_RANGE_HIGH" NUMBER(20,0) NOT NULL ENABLE,
	"HEALTH_CARD_RANGE_DELETED" CHAR(1) DEFAULT 'N' NOT NULL ENABLE,
	"HEALTH_CARD_TYPE" VARCHAR2(30),
	"HEALTH_CARD_BIN_PARTIAL_DATE" DATE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(200) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_HEALTH_CARD_RANGE" PRIMARY KEY ("HEALTH_CARD_RANGE_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_HEALTH_CARD_BIN_01" FOREIGN KEY ("HEALTH_CARD_BIN_NUM")
	  REFERENCES "TREXONE_DATA"."HEALTH_CARD_BIN" ("HEALTH_CARD_BIN_NUM") ENABLE
   )
  PARTITION BY RANGE ("DATESTAMP")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
