-- ==========================================

  CREATE TABLE "TREXONE_DATA"."HOA"
   (	"HOA_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"HOA_NAME" VARCHAR2(64) NOT NULL ENABLE,
	"SIG_MACRO" VARCHAR2(15),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_HOA" PRIMARY KEY ("HOA_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
