-- ==========================================

  CREATE TABLE "TREXONE_DATA"."HOA_TIME"
   (	"HOA_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"HOA_SCHEDULE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"HOA_TIME_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"TIME" VARCHAR2(30) NOT NULL ENABLE,
	"DOSAGE" NUMBER(18,3),
	"POSITION" NUMBER(2,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_HOA_TIME" PRIMARY KEY ("HOA_NUM", "HOA_SCHEDULE_NUM", "HOA_TIME_SEQ")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
