-- ==========================================

  CREATE TABLE "TREXONE_DATA"."HOA_SCHEDULE"
   (	"HOA_SCHEDULE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"HOA_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SCHEDULE_TYPE" VARCHAR2(20) NOT NULL ENABLE,
	"INTERVAL_DAYS" NUMBER(3,0),
	"INTERVAL_WEEKS" NUMBER(2,0),
	"DAY_OF_THE_WEEK" VARCHAR2(20),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_HOA_SCHEDULE" PRIMARY KEY ("HOA_SCHEDULE_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
