-- ==========================================

  CREATE TABLE "TREXONE_DATA"."HS_MESSAGE"
   (	"HS_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PATIENT_ID_SOURCE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TYPE" CHAR(1) NOT NULL ENABLE,
	"DIRECTION" CHAR(1) NOT NULL ENABLE,
	"PATIENT_ID" VARCHAR2(30),
	"LAST_NAME" VARCHAR2(30),
	"FIRST_NAME" VARCHAR2(30),
	"STATUS" CHAR(1) NOT NULL ENABLE,
	"MESSAGE" CLOB NOT NULL ENABLE,
	"MESSAGE_DATE" DATE DEFAULT sysdate NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT sysdate NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"MSG_CONTROL_ID" VARCHAR2(40),
	"ERROR_MESSAGE" VARCHAR2(4000),
	 CONSTRAINT "PK_HS_MESSAGE" PRIMARY KEY ("HS_MESSAGE_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_PATIENT_ID_SOURCE_03" FOREIGN KEY ("PATIENT_ID_SOURCE_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT_ID_SOURCE" ("PATIENT_ID_SOURCE_NUM") ENABLE
   ) ;
-- ==========================================
