-- ==========================================

  CREATE TABLE "TREXONE_DATA"."IMAGE"
   (	"IMAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TYPE" VARCHAR2(30),
	"IS_ASSIGNED" CHAR(1),
	"IMAGE" BLOB NOT NULL ENABLE,
	"NAME" VARCHAR2(70) NOT NULL ENABLE,
	"FILE_FORMAT" VARCHAR2(10),
	"SCAN_USER" NUMBER(18,0),
	"SCAN_DATE" DATE,
	"ASSIGN_USER" NUMBER(18,0),
	"ASSIGN_DATE" DATE,
	"BARCODE" VARCHAR2(255),
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"DEVICE_NUM" NUMBER(18,0),
	"PREFERRED_ROTATE_ANGLE" NUMBER(6,2),
	"PREFERRED_BRIGHTNESS" NUMBER(4,0),
	"PREFERRED_CONTRAST" NUMBER(4,0),
	"PREFERRED_SCALE" NUMBER(6,2),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"IMAGE_LENGTH" NUMBER(10,0) GENERATED ALWAYS AS ("SYS"."DBMS_LOB"."GETLENGTH"("IMAGE")) VIRTUAL ,
	"ASSET_GROUP_ID" VARCHAR2(100),
	"SCANNED_DOCUMENT_TYPE_NUM" NUMBER(18,0),
	 CONSTRAINT "FK_DEVICE_05" FOREIGN KEY ("DEVICE_NUM")
	  REFERENCES "TREXONE_DATA"."DEVICE" ("DEVICE_NUM") ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_08" FOREIGN KEY ("ASSIGN_USER")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_09" FOREIGN KEY ("SCAN_USER")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE,
	 CONSTRAINT "IMAGE_SCANNED_DOC_TYPE_NUM_FK" FOREIGN KEY ("SCANNED_DOCUMENT_TYPE_NUM")
	  REFERENCES "TREXONE_DATA"."SCANNED_DOCUMENT_TYPE" ("SCANNED_DOCUMENT_TYPE_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_IMAGE" ON "TREXONE_DATA"."IMAGE" ("IMAGE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."IMAGE" ADD CONSTRAINT "PK_IMAGE" PRIMARY KEY ("IMAGE_NUM")
  USING INDEX "TREXONE_DATA"."PK_IMAGE"  ENABLE;
-- ==========================================
