-- ==========================================

  CREATE TABLE "TREXONE_DATA"."IMAGE_GROUP"
   (	"IMAGE_GROUP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_IMAGE_GROUP" ON "TREXONE_DATA"."IMAGE_GROUP" ("IMAGE_GROUP_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."IMAGE_GROUP" ADD CONSTRAINT "PK_IMAGE_GROUP" PRIMARY KEY ("IMAGE_GROUP_NUM")
  USING INDEX "TREXONE_DATA"."PK_IMAGE_GROUP"  ENABLE;
-- ==========================================
