-- ==========================================

  CREATE TABLE "TREXONE_DATA"."IMG_ANNOTATION_NOTE"
   (	"IMG_ANNOTATION_NOTE_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0),
	"NOTE_TEXT" VARCHAR2(4000) NOT NULL ENABLE,
	"CREATE_USER" NUMBER(18,0) NOT NULL ENABLE,
	"CREATE_DATE" DATE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0),
	"FONT_SIZE" NUMBER(3,0),
	"ANNOTATION_UID" VARCHAR2(40),
	"IMAGE_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "IMG_ANNOTATION_NOTE_IMAGE_FK" FOREIGN KEY ("IMAGE_NUM")
	  REFERENCES "TREXONE_DATA"."IMAGE" ("IMAGE_NUM") ENABLE,
	 CONSTRAINT "FK_RX_17" FOREIGN KEY ("RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_BASE" ("RX_RECORD_NUM") ENABLE,
	 CONSTRAINT "FK_FACILITY_109" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTOYMINTERVAL(3,'MONTH')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2016-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
  CREATE INDEX "TREXONE_DATA"."PK_IMG_ANNOTATION_NOTE" ON "TREXONE_DATA"."IMG_ANNOTATION_NOTE" ("IMG_ANNOTATION_NOTE_SEQ")
  ;
ALTER TABLE "TREXONE_DATA"."IMG_ANNOTATION_NOTE" ADD CONSTRAINT "PK_IMG_ANNOTATION_NOTE" PRIMARY KEY ("IMG_ANNOTATION_NOTE_SEQ")
  USING INDEX "TREXONE_DATA"."PK_IMG_ANNOTATION_NOTE"  ENABLE;
-- ==========================================
