-- ==========================================

  CREATE TABLE "TREXONE_DATA"."IMG_ANNOTATION_NOTE_ERXD_65039"
   (	"IMG_ANNOTATION_NOTE_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0),
	"NOTE_TEXT" VARCHAR2(4000) NOT NULL ENABLE,
	"CREATE_USER" NUMBER(18,0) NOT NULL ENABLE,
	"CREATE_DATE" DATE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0),
	"FONT_SIZE" NUMBER(3,0),
	"ANNOTATION_UID" VARCHAR2(40),
	"IMAGE_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
-- ==========================================
