-- ==========================================

  CREATE TABLE "TREXONE_DATA"."IMH_PATIENT_ALLERGY_SYMPT"
   (	"IMH_PATIENT_ALLERGY_SYMPT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"IMH_PATIENT_ALLERGY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"EXTERNAL_SYMPTOM_NUM" NUMBER(18,0),
	"DESCRIPTION" VARCHAR2(255),
	"STATUS" VARCHAR2(10),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_IMH_PATIENT_ALLERGY_SYMPT" PRIMARY KEY ("IMH_PATIENT_ALLERGY_SYMPT_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_IMH_PATIENT_ALLERGY_01" FOREIGN KEY ("IMH_PATIENT_ALLERGY_NUM")
	  REFERENCES "TREXONE_DATA"."IMH_PATIENT_ALLERGY" ("IMH_PATIENT_ALLERGY_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
