-- ==========================================

  CREATE TABLE "TREXONE_DATA"."IMPORTED_PRESCRIBER"
   (	"IMPORTED_PRESCRIBER_NUM" NUMBER(18,0) NOT NULL DISABLE,
	"STATUS" CHAR(1) NOT NULL DISABLE,
	"PRESCRIBER_NUM" NUMBER(18,0),
	"STATUS_DATE" DATE,
	"SCRUB_ID" NUMBER(18,0),
	"IMPORT_DATE" DATE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL DISABLE,
	"DATESTAMP" DATE NOT NULL DISABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL DISABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL DISABLE,
	"ESV_PRESCRIBER_ID" VARCHAR2(50),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PRESCRIBER_18" FOREIGN KEY ("PRESCRIBER_NUM")
	  REFERENCES "TREXONE_DATA"."PRESCRIBER" ("PRESCRIBER_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_IMPORTED_PRESCRIBER" ON "TREXONE_DATA"."IMPORTED_PRESCRIBER" ("IMPORTED_PRESCRIBER_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."IMPORTED_PRESCRIBER" ADD CONSTRAINT "PK_IMPORTED_PRESCRIBER" PRIMARY KEY ("IMPORTED_PRESCRIBER_NUM")
  USING INDEX "TREXONE_DATA"."PK_IMPORTED_PRESCRIBER"  ENABLE;
-- ==========================================
