-- ==========================================

  CREATE TABLE "TREXONE_DATA"."IMPORTED_PRESCRIBER_ERROR"
   (	"IMPORTED_PRESCRIBER_ERROR_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"IMPORTED_PRESCRIBER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ERROR_TEXT" VARCHAR2(255),
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"ERROR_VALUE" VARCHAR2(256),
	"ERROR_TABLE" VARCHAR2(30),
	"ERROR_COLUMN" VARCHAR2(30),
	"ERROR_TABLE_PK" NUMBER(18,0),
	"ERROR_REASON" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_IMPORTED_PRESCRIBER_02" FOREIGN KEY ("IMPORTED_PRESCRIBER_NUM")
	  REFERENCES "TREXONE_DATA"."IMPORTED_PRESCRIBER" ("IMPORTED_PRESCRIBER_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_IMPORTED_PRESCRIBER_ERROR" ON "TREXONE_DATA"."IMPORTED_PRESCRIBER_ERROR" ("IMPORTED_PRESCRIBER_ERROR_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."IMPORTED_PRESCRIBER_ERROR" ADD CONSTRAINT "PK_IMPORTED_PRESCRIBER_ERROR" PRIMARY KEY ("IMPORTED_PRESCRIBER_ERROR_NUM")
  USING INDEX "TREXONE_DATA"."PK_IMPORTED_PRESCRIBER_ERROR"  ENABLE;
-- ==========================================
