-- ==========================================

  CREATE TABLE "TREXONE_DATA"."INBOUND_MSG_QUEUE"
   (	"INBOUND_MSG_QUEUE_NUM" NUMBER(18,0),
	"OUTBOUND_MSG_QUEUE_NUM" NUMBER(18,0),
	"HTTP_HEADERS" VARCHAR2(4000),
	"HTTP_METHOD" VARCHAR2(20),
	"REQUEST_CONTENT" CLOB NOT NULL ENABLE,
	"HTTP_STATUS" NUMBER(18,0) NOT NULL ENABLE,
	"RESPONSE_CONTENT" CLOB,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"REQUEST_URI" VARCHAR2(4000) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) DEFAULT 0 NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(18,0) DEFAULT 0 NOT NULL ENABLE,
	"DATESTAMP" DATE,
	 CONSTRAINT "PK_INBOUND_MSG_QUEUE" PRIMARY KEY ("INBOUND_MSG_QUEUE_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_OUTBOUND_MSG_QUEUE_01" FOREIGN KEY ("OUTBOUND_MSG_QUEUE_NUM")
	  REFERENCES "TREXONE_DATA"."OUTBOUND_MSG_QUEUE" ("OUTBOUND_MSG_QUEUE_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTOYMINTERVAL(3,'MONTH'))
 (PARTITION "PART_01"  VALUES LESS THAN (TO_DATE(' 2017-11-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
