-- ==========================================

  CREATE TABLE "TREXONE_DATA"."INVENTORY_SKU"
   (	"INVENTORY_SKU_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SKU" VARCHAR2(20) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	"PRODUCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0) NOT NULL ENABLE,
	 CONSTRAINT "PK_INVENTORY_SKU" PRIMARY KEY ("INVENTORY_SKU_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_INVENTORY_SKU_01" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_INVENTORY_SKU_PROD1" FOREIGN KEY ("PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT" ("PRODUCT_NUM") ENABLE NOVALIDATE
   ) ;
  CREATE INDEX "TREXONE_DATA"."INVENTORY_SKU_IDX03" ON "TREXONE_DATA"."INVENTORY_SKU" ("SKU", "FACILITY_NUM", "ERX_CLIENT_ID")
  ;
ALTER TABLE "TREXONE_DATA"."INVENTORY_SKU" ADD CONSTRAINT "INVENTORY_SKU_UC_FACSKU" UNIQUE ("FACILITY_NUM", "SKU")
  USING INDEX "TREXONE_DATA"."INVENTORY_SKU_IDX03"  ENABLE;
-- ==========================================
