-- ==========================================

  CREATE TABLE "TREXONE_DATA"."INVENTORY_ADJUSTMENT"
   (	"INVENTORY_ADJUSTMENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"INVENTORY_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"QUANTITY" NUMBER(16,8) NOT NULL ENABLE,
	"COMMENT_TEXT" VARCHAR2(255),
	"UNIT_COST" NUMBER(17,6),
	"IS_PROCESSED_FOR_COST" CHAR(1) NOT NULL ENABLE,
	"AVAILABLE_FIFO_QUANTITY" NUMBER(16,8),
	"AVAILABLE_LIFO_QUANTITY" NUMBER(16,8),
	"EXTENDED_COST" NUMBER(17,6),
	"CREATE_USER" NUMBER(18,0) NOT NULL ENABLE,
	"CREATE_DATE" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"LOCATION_GROUP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"INV_ADJUST_REASON_NUM" NUMBER(18,0),
	"REFERENCE_NUMBER" VARCHAR2(100),
	"ADJUSTMENT_TYPE_CODE" VARCHAR2(3),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_INVENTORY_ADJUSTMENT_02" FOREIGN KEY ("INV_ADJUST_REASON_NUM")
	  REFERENCES "TREXONE_DATA"."INVENTORY_ADJUSTMENT_REASON" ("INV_ADJUST_REASON_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_INVENTORY_ITEM_02" FOREIGN KEY ("INVENTORY_ITEM_NUM")
	  REFERENCES "TREXONE_DATA"."INVENTORY_ITEM" ("INVENTORY_ITEM_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_STORAGE_LOCATION_01" FOREIGN KEY ("LOCATION_GROUP_NUM")
	  REFERENCES "TREXONE_DATA"."STORAGE_LOCATION" ("LOCATION_GROUP_NUM") ENABLE NOVALIDATE
   )
  PARTITION BY RANGE ("CREATE_DATE") INTERVAL (NUMTOYMINTERVAL(3,'MONTH'))
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2016-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_INVENTORY_ADJUSTMENT" ON "TREXONE_DATA"."INVENTORY_ADJUSTMENT" ("INVENTORY_ADJUSTMENT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."INVENTORY_ADJUSTMENT" ADD CONSTRAINT "PK_INVENTORY_ADJUSTMENT" PRIMARY KEY ("INVENTORY_ADJUSTMENT_NUM")
  USING INDEX "TREXONE_DATA"."PK_INVENTORY_ADJUSTMENT"  ENABLE NOVALIDATE;
-- ==========================================
