-- ==========================================

  CREATE TABLE "TREXONE_DATA"."INVENTORY_GROUP"
   (	"INVENTORY_GROUP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"GROUP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"INVENTORY_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_INVENTORY_GROUP" PRIMARY KEY ("INVENTORY_GROUP_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_INVENTORY_ITEM_14" FOREIGN KEY ("INVENTORY_ITEM_NUM")
	  REFERENCES "TREXONE_DATA"."INVENTORY_ITEM" ("INVENTORY_ITEM_NUM") ENABLE,
	 CONSTRAINT "FK_GROUPS_05" FOREIGN KEY ("GROUP_NUM")
	  REFERENCES "TREXONE_DATA"."GROUPS" ("GROUP_NUM") ENABLE
   ) ;
  CREATE INDEX "TREXONE_DATA"."IN_INVENTORY_GROUP_1" ON "TREXONE_DATA"."INVENTORY_GROUP" ("GROUP_NUM", "INVENTORY_ITEM_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."INVENTORY_GROUP" ADD CONSTRAINT "UC_INVENTORY_GROUP_01" UNIQUE ("GROUP_NUM", "INVENTORY_ITEM_NUM")
  USING INDEX "TREXONE_DATA"."IN_INVENTORY_GROUP_1"  ENABLE;
-- ==========================================
