-- ==========================================

  CREATE TABLE "TREXONE_DATA"."INVENTORY_LOT"
   (	"INVENTORY_LOT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"LOT_NUMBER" VARCHAR2(20) NOT NULL ENABLE,
	"SERIAL_NUMBER" VARCHAR2(20),
	"PURCHASE_DATE" DATE,
	"EXPIRATION_DATE" DATE,
	"QTY" NUMBER(16,8) NOT NULL ENABLE,
	"COST" NUMBER(17,6),
	"INVENTORY_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "INVENTORY_LOT_PK" PRIMARY KEY ("INVENTORY_LOT_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "INVENTORY_LOT_FK01" FOREIGN KEY ("INVENTORY_ITEM_NUM")
	  REFERENCES "TREXONE_DATA"."INVENTORY_ITEM" ("INVENTORY_ITEM_NUM") ENABLE
   ) ;
-- ==========================================
