-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ITEM_MESSAGE"
   (	"ITEM_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ITEM_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"MESSAGE_CODE" VARCHAR2(100) NOT NULL ENABLE,
	"MESSAGE_TEXT" VARCHAR2(1000) NOT NULL ENABLE,
	"WARN_LEV" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"MESSAGE_SOURCE" VARCHAR2(100),
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_ITEM_07" FOREIGN KEY ("ORDER_NUM", "ITEM_SEQ")
	  REFERENCES "TREXONE_DATA"."ITEM" ("ORDER_NUM", "ITEM_SEQ") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_ITEM_MESSAGE" ON "TREXONE_DATA"."ITEM_MESSAGE" ("ITEM_MESSAGE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."ITEM_MESSAGE" ADD CONSTRAINT "PK_ITEM_MESSAGE" PRIMARY KEY ("ITEM_MESSAGE_NUM")
  USING INDEX "TREXONE_DATA"."PK_ITEM_MESSAGE"  ENABLE;
-- ==========================================
