-- ==========================================

  CREATE TABLE "TREXONE_DATA"."IVR_ORDER"
   (	"IVR_ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ELECTRONIC_ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PICKUP_DATE" DATE NOT NULL ENABLE,
	"LANGUAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"IS_SUBMIT_HANGUP" CHAR(1) NOT NULL ENABLE,
	"SUBMIT_DATE" DATE NOT NULL ENABLE,
	"PICKUP_DATE_SRC" VARCHAR2(1) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0),
	"LOCALE_NUM" NUMBER(18,0),
	"IS_PROCESSED" CHAR(1),
	"TRANSFER_FACILITY_NUM" NUMBER(18,0),
	"DELIVERY_METHOD_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"MAIL_CC_TYPE" VARCHAR2(10),
	"MAIL_CC_LAST4" CHAR(4),
	"SHIPPING_ADDR_USAGE" VARCHAR2(10),
	"MAIL_CC_EXP_DATE" VARCHAR2(7),
	"CLINICAL_PROGRAM_NUM" NUMBER(18,0),
	"ORDER_SOURCE_TYPE_NUM" NUMBER(18,0),
	"PAYMENT_METHOD" VARCHAR2(50),
	 CONSTRAINT "FK_ELECTRONIC_ORDER_02" FOREIGN KEY ("ELECTRONIC_ORDER_NUM")
	  REFERENCES "TREXONE_DATA"."ELECTRONIC_ORDER" ("ELECTRONIC_ORDER_NUM") ENABLE,
	 CONSTRAINT "FK_FACILITY_58" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_LOCALE_01" FOREIGN KEY ("LOCALE_NUM")
	  REFERENCES "TREXONE_DATA"."LOCALE" ("LOCALE_NUM") ENABLE,
	 CONSTRAINT "FK_FACILITY_89" FOREIGN KEY ("TRANSFER_FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_IVR_ORDER_02" FOREIGN KEY ("DELIVERY_METHOD_NUM")
	  REFERENCES "TREXONE_DATA"."DELIVERY_METHOD" ("DELIVERY_METHOD_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_IVR_ORDER" ON "TREXONE_DATA"."IVR_ORDER" ("IVR_ORDER_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."IVR_ORDER" ADD CONSTRAINT "PK_IVR_ORDER" PRIMARY KEY ("IVR_ORDER_NUM")
  USING INDEX "TREXONE_DATA"."PK_IVR_ORDER"  ENABLE;
-- ==========================================
