-- ==========================================

  CREATE TABLE "TREXONE_DATA"."KEEP_IMAGE"
   (	"IMAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TYPE" VARCHAR2(30),
	"IS_ASSIGNED" CHAR(1),
	"IMAGE" BLOB NOT NULL ENABLE,
	"NAME" VARCHAR2(70) NOT NULL ENABLE,
	"FILE_FORMAT" VARCHAR2(10),
	"SCAN_USER" NUMBER(18,0),
	"SCAN_DATE" DATE,
	"ASSIGN_USER" NUMBER(18,0),
	"ASSIGN_DATE" DATE,
	"BARCODE" VARCHAR2(255),
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"DEVICE_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"ASSET_GROUP_ID" VARCHAR2(100),
	 CONSTRAINT "FK_DEVICE_06" FOREIGN KEY ("DEVICE_NUM")
	  REFERENCES "TREXONE_DATA"."DEVICE" ("DEVICE_NUM") ENABLE,
	 CONSTRAINT "FK_DEVICE_27" FOREIGN KEY ("SCAN_USER")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE,
	 CONSTRAINT "FK_DEVICE_28" FOREIGN KEY ("ASSIGN_USER")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_KEEP_IMAGE" ON "TREXONE_DATA"."KEEP_IMAGE" ("IMAGE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."KEEP_IMAGE" ADD CONSTRAINT "PK_KEEP_IMAGE" PRIMARY KEY ("IMAGE_NUM")
  USING INDEX "TREXONE_DATA"."PK_KEEP_IMAGE"  ENABLE;
-- ==========================================
