-- ==========================================

  CREATE TABLE "TREXONE_DATA"."LINK_TYPE"
   (	"LINK_TYPE_CODE" VARCHAR2(30) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(60),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_LINK_TYPE" ON "TREXONE_DATA"."LINK_TYPE" ("LINK_TYPE_CODE")
  ;
ALTER TABLE "TREXONE_DATA"."LINK_TYPE" ADD CONSTRAINT "PK_LINK_TYPE" PRIMARY KEY ("LINK_TYPE_CODE")
  USING INDEX "TREXONE_DATA"."PK_LINK_TYPE"  ENABLE;
-- ==========================================
