-- ==========================================

  CREATE TABLE "TREXONE_DATA"."LOCATION_GROUP_LINK"
   (	"LOCATION_GROUP_LINK_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"LOCATION_GROUP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PARENT_LOCATION_GROUP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DISTANCE_TO_PARENT" NUMBER(9,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_LOCATION_GROUP_04" FOREIGN KEY ("PARENT_LOCATION_GROUP_NUM")
	  REFERENCES "TREXONE_DATA"."LOCATION_GROUP" ("LOCATION_GROUP_NUM") ENABLE,
	 CONSTRAINT "FK_LOCATION_GROUP_05" FOREIGN KEY ("LOCATION_GROUP_NUM")
	  REFERENCES "TREXONE_DATA"."LOCATION_GROUP" ("LOCATION_GROUP_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_LOCATION_GROUP_LINK" ON "TREXONE_DATA"."LOCATION_GROUP_LINK" ("LOCATION_GROUP_LINK_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."LOCATION_GROUP_LINK" ADD CONSTRAINT "PK_LOCATION_GROUP_LINK" PRIMARY KEY ("LOCATION_GROUP_LINK_NUM")
  USING INDEX "TREXONE_DATA"."PK_LOCATION_GROUP_LINK"  ENABLE;
-- ==========================================
