-- ==========================================

  CREATE TABLE "TREXONE_DATA"."LOCATION_GROUP"
   (	"LOCATION_GROUP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"LOCATION_GROUP_NAME" VARCHAR2(45) NOT NULL ENABLE,
	"SHORT_NAME" VARCHAR2(10) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(60),
	"IS_ACTIVE" CHAR(1),
	"DISPENSE_PRIORITY" NUMBER(9,0),
	"IS_CONTROL_ORDER_COMMIT" CHAR(1),
	"IS_CONTROL_DISPENSING_COMMIT" CHAR(1),
	"IS_ITEM_LOCATION" CHAR(1),
	"LOCATION_GROUP_TYPE_NUM" NUMBER(9,0),
	"COST_MODEL_NUM" NUMBER(9,0),
	"PARENT_LOCATION_GROUP_NUM" NUMBER(18,0),
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_LOCATION_GROUP" ON "TREXONE_DATA"."LOCATION_GROUP" ("LOCATION_GROUP_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."LOCATION_GROUP" ADD CONSTRAINT "PK_LOCATION_GROUP" PRIMARY KEY ("LOCATION_GROUP_NUM")
  USING INDEX "TREXONE_DATA"."PK_LOCATION_GROUP"  ENABLE;
-- ==========================================
