-- ==========================================

  CREATE TABLE "TREXONE_DATA"."LOT_ADJUSTMENT"
   (	"LOT_ADJUSTMENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"INVENTORY_LOT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"LOT_COMMIT_NUM" NUMBER(18,0),
	"QUANTITY" NUMBER(16,8) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	"INV_ADJUST_REASON_NUM" NUMBER(18,0) NOT NULL ENABLE,
	 CONSTRAINT "LOT_ADJUSTMENT_PK" PRIMARY KEY ("LOT_ADJUSTMENT_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "LOT_ADJUSTMENT_FK02" FOREIGN KEY ("INVENTORY_LOT_NUM")
	  REFERENCES "TREXONE_DATA"."INVENTORY_LOT" ("INVENTORY_LOT_NUM") ENABLE,
	 CONSTRAINT "LOT_ADJUSTMENT_FK03" FOREIGN KEY ("LOT_COMMIT_NUM")
	  REFERENCES "TREXONE_DATA"."LOT_COMMIT" ("LOT_COMMIT_NUM") ENABLE,
	 CONSTRAINT "FK_INV_ADJUST_REASON_01" FOREIGN KEY ("INV_ADJUST_REASON_NUM")
	  REFERENCES "TREXONE_DATA"."INVENTORY_ADJUSTMENT_REASON" ("INV_ADJUST_REASON_NUM") ENABLE NOVALIDATE
   ) ;
-- ==========================================
