-- ==========================================

  CREATE TABLE "TREXONE_DATA"."LTC_HOA_SCHEDULE"
   (	"LTC_HOA_SCHEDULE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"LTC_HOA_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"INTERVAL_DAYS" NUMBER(3,0),
	"DAYS_OF_THE_WEEK" NUMBER(3,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_LTC_HOA_SCHEDULE" PRIMARY KEY ("LTC_HOA_SCHEDULE_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_LTC_HOA_07" FOREIGN KEY ("LTC_HOA_NUM")
	  REFERENCES "TREXONE_DATA"."LTC_HOA" ("LTC_HOA_NUM") ENABLE
   ) ;
-- ==========================================
