-- ==========================================

  CREATE TABLE "TREXONE_DATA"."LTC_PRESCRIBER"
   (	"LTC_PRESCRIBER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"LTC_FACILITY_NODE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRESCRIBER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PRESCRIBER_ADDRESS_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_LTC_PRESCRIBER" PRIMARY KEY ("LTC_PRESCRIBER_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_LTC_FACILITY_NODE_05" FOREIGN KEY ("LTC_FACILITY_NODE_NUM")
	  REFERENCES "TREXONE_DATA"."LTC_FACILITY_NODE" ("LTC_FACILITY_NODE_NUM") ENABLE,
	 CONSTRAINT "FK_PRESCRIBER_29" FOREIGN KEY ("PRESCRIBER_NUM")
	  REFERENCES "TREXONE_DATA"."PRESCRIBER" ("PRESCRIBER_NUM") ENABLE
   ) ;
-- ==========================================
