-- ==========================================

  CREATE TABLE "TREXONE_DATA"."LTC_PACKAGING_METHOD"
   (	"LTC_PACKAGING_METHOD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"LTC_FACILITY_NODE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(100) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"IS_DEFAULT" CHAR(1),
	"IS_IN_USE" CHAR(1),
	"NUMBER_OF_LABELS" NUMBER(9,0),
	"DOC_TYPE_NAME" VARCHAR2(30),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"SPECIAL_PACKAGING_CODE" CHAR(1),
	 CONSTRAINT "PK_LTC_PKG_METHOD" PRIMARY KEY ("LTC_PACKAGING_METHOD_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_LTC_FACILITY_NODE_04" FOREIGN KEY ("LTC_FACILITY_NODE_NUM")
	  REFERENCES "TREXONE_DATA"."LTC_FACILITY_NODE" ("LTC_FACILITY_NODE_NUM") ENABLE
   ) ;
-- ==========================================
