-- ==========================================

  CREATE TABLE "TREXONE_DATA"."LTC_RX_FILL_PRESCRIBER_ORDER"
   (	"LTC_RX_FILL_PRESCRIB_ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_FILL_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"LTC_RX_PRESCRIBER_ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"IS_ACTIVE" CHAR(1) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PKLTC_RX_FILL_PRESCRIBER_ORDER" PRIMARY KEY ("LTC_RX_FILL_PRESCRIB_ORDER_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_LTC_RX_PRESCRIBER_ORDER_01" FOREIGN KEY ("LTC_RX_PRESCRIBER_ORDER_NUM")
	  REFERENCES "TREXONE_DATA"."LTC_RX_PRESCRIBER_ORDER" ("LTC_RX_PRESCRIBER_ORDER_NUM") ENABLE,
	 CONSTRAINT "FK_RX_FILL_03" FOREIGN KEY ("RX_FILL_SEQ", "RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_FILL" ("RX_FILL_SEQ", "RX_RECORD_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
