-- ==========================================

  CREATE TABLE "TREXONE_DATA"."LTC_PRESCRIBER_ORDER"
   (	"LTC_PRESCRIBER_ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"LTC_FACILITY_NODE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ORDER_RECORD_TYPE" NUMBER(9,0) NOT NULL ENABLE,
	"TYPE" VARCHAR2(30) NOT NULL ENABLE,
	"IS_ON_HOLD" CHAR(1) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"EFFECTIVE_DATE" DATE,
	"TERMINATION_DATE" DATE,
	"PRINT_ORDER" NUMBER(9,0),
	"LTC_HOA_NUM" NUMBER(18,0),
	"LTC_PATIENT_NUM" NUMBER(18,0),
	"PRESCRIBER_NUM" NUMBER(18,0),
	"CHANGE_LOG" VARCHAR2(100),
	"TEXT" VARCHAR2(1500),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_LTC_PRESCRIBER_ORDER" PRIMARY KEY ("LTC_PRESCRIBER_ORDER_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_LTC_FACILITY_NODE_06" FOREIGN KEY ("LTC_FACILITY_NODE_NUM")
	  REFERENCES "TREXONE_DATA"."LTC_FACILITY_NODE" ("LTC_FACILITY_NODE_NUM") ENABLE,
	 CONSTRAINT "FK_LTC_HOA_04" FOREIGN KEY ("LTC_HOA_NUM")
	  REFERENCES "TREXONE_DATA"."LTC_HOA" ("LTC_HOA_NUM") ENABLE,
	 CONSTRAINT "FK_LTC_PATIENT_03" FOREIGN KEY ("LTC_PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."LTC_PATIENT" ("LTC_PATIENT_NUM") ENABLE,
	 CONSTRAINT "FK_PRESCRIBER_27" FOREIGN KEY ("PRESCRIBER_NUM")
	  REFERENCES "TREXONE_DATA"."PRESCRIBER" ("PRESCRIBER_NUM") ENABLE
   ) ;
-- ==========================================
