-- ==========================================

  CREATE TABLE "TREXONE_DATA"."LTC_STANDARD_ORDER"
   (	"LTC_STANDARD_ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"LTC_FACILITY_NODE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ORDER_TYPE" VARCHAR2(15),
	"ORDER_TEXT" VARCHAR2(1500),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_LTC_STANDARD_ORDER" PRIMARY KEY ("LTC_STANDARD_ORDER_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_LTC_FACILITY_NODE_07" FOREIGN KEY ("LTC_FACILITY_NODE_NUM")
	  REFERENCES "TREXONE_DATA"."LTC_FACILITY_NODE" ("LTC_FACILITY_NODE_NUM") ENABLE
   ) ;
-- ==========================================
