-- ==========================================

  CREATE TABLE "TREXONE_DATA"."LTC_FACILITY_NODE_LINK"
   (	"LTC_FACILITY_NODE_LINK_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CHILD" NUMBER(18,0) NOT NULL ENABLE,
	"PARENT" NUMBER(18,0) NOT NULL ENABLE,
	"DISTANCE_TO_PARENT" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_FACILITY_NODE_LINK" PRIMARY KEY ("LTC_FACILITY_NODE_LINK_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_LTC_FACILITY_NODE_09" FOREIGN KEY ("CHILD")
	  REFERENCES "TREXONE_DATA"."LTC_FACILITY_NODE" ("LTC_FACILITY_NODE_NUM") ENABLE,
	 CONSTRAINT "FK_LTC_FACILITY_NODE_10" FOREIGN KEY ("PARENT")
	  REFERENCES "TREXONE_DATA"."LTC_FACILITY_NODE" ("LTC_FACILITY_NODE_NUM") ENABLE
   ) ;
-- ==========================================
