-- ==========================================

  CREATE TABLE "TREXONE_DATA"."LTC_AR"
   (	"LTC_AR_NUM" NUMBER NOT NULL ENABLE,
	"LTC_FACILITY_NODE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_LTC_AR" PRIMARY KEY ("LTC_AR_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_LTC_FACILITY_NODE_01" FOREIGN KEY ("LTC_FACILITY_NODE_NUM")
	  REFERENCES "TREXONE_DATA"."LTC_FACILITY_NODE" ("LTC_FACILITY_NODE_NUM") ENABLE
   ) ;
-- ==========================================
