-- ==========================================

  CREATE TABLE "TREXONE_DATA"."LTC_FACILITY_NODE"
   (	"LTC_FACILITY_NODE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"LTC_FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(32),
	"DELIVERY_DATE_IND" NUMBER(9,0),
	"DELIVERY_DAYS" NUMBER(9,0),
	"IS_FILLING_OVERRIDE" CHAR(1),
	"CYCLE_FILL_FREQUENCY_TYPE" NUMBER(9,0),
	"FILL_CYCLE" NUMBER(18,0),
	"FILL_TOO_SOON_DAYS" NUMBER(9,0),
	"FILL_TOO_LATE_DAYS" NUMBER(9,0),
	"REFILL_TOO_SOON_DAYS" NUMBER(9,0),
	"REFILL_TOO_LATE_DAYS" NUMBER(9,0),
	"BILLING_TYPE" NUMBER(9,0),
	"BILLING_QUANTITY_METHOD" NUMBER(9,0),
	"BILL_CYCLE" NUMBER(18,0),
	"DATE_OF_SERVICE" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"IS_REQUIRE_AR_ACCOUNT" CHAR(1),
	"AUTOCHARGE_PREEDIT_LEVEL" NUMBER(9,0),
	"AUTOCHARGE_PREEDIT_MESSAGE" VARCHAR2(256),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"PATIENT_RESIDENCE" VARCHAR2(2),
	 CONSTRAINT "PK_LTC_FACILITY_NODE" PRIMARY KEY ("LTC_FACILITY_NODE_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_FREQUENCY_01" FOREIGN KEY ("BILL_CYCLE")
	  REFERENCES "TREXONE_DATA"."FREQUENCY" ("FREQUENCY_NUM") ENABLE,
	 CONSTRAINT "FK_FREQUENCY_02" FOREIGN KEY ("FILL_CYCLE")
	  REFERENCES "TREXONE_DATA"."FREQUENCY" ("FREQUENCY_NUM") ENABLE,
	 CONSTRAINT "FK_LTC_FACILITY_01" FOREIGN KEY ("LTC_FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."LTC_FACILITY" ("LTC_FACILITY_NUM") ENABLE
   ) ;
-- ==========================================
