-- ==========================================

  CREATE TABLE "TREXONE_DATA"."MAIL_SHIP_EXMPT_RULE"
   (	"MAIL_SHIP_EXMPT_RULE_NUM" NUMBER(18,0),
	"DATA_FILTER" CLOB NOT NULL ENABLE,
	"MAIL_SHIP_EXMPT_RULE_SET_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"IS_INCLUDE_RULE" CHAR(1),
	"PROCESS_ORDER" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_MAIL_SHIP_EXMPT_RULE" PRIMARY KEY ("MAIL_SHIP_EXMPT_RULE_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_MAIL_SHIP_EXMPT_RULE_SET_01" FOREIGN KEY ("MAIL_SHIP_EXMPT_RULE_SET_NUM")
	  REFERENCES "TREXONE_DATA"."MAIL_SHIP_EXMPT_RULE_SET" ("MAIL_SHIP_EXMPT_RULE_SET_NUM") ENABLE NOVALIDATE
   ) ;
-- ==========================================
