-- ==========================================

  CREATE TABLE "TREXONE_DATA"."MAILORD_INCL_EXCL_RULE_SET"
   (	"MAILORD_INCL_EXCL_RULE_SET_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_MAILORD_INCL_EXCL_RULE_SET" PRIMARY KEY ("MAILORD_INCL_EXCL_RULE_SET_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
