-- ==========================================

  CREATE TABLE "TREXONE_DATA"."MDDB_EXCLUDED_NDC"
   (	"NDC" VARCHAR2(20) NOT NULL ENABLE,
	"MDDB_FILE_DATE" VARCHAR2(8) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_MDDB_EXCLUDED_NDC" PRIMARY KEY ("NDC", "ERX_CLIENT_ID")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
