-- ==========================================

  CREATE TABLE "TREXONE_DATA"."MEDGUIDE"
   (	"MEDGUIDE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CONCEPT_VALUE" VARCHAR2(30) NOT NULL ENABLE,
	"CONCEPT_CODE" VARCHAR2(10) NOT NULL ENABLE,
	"FILE_NAME" VARCHAR2(32) NOT NULL ENABLE,
	"FILE_FORMAT" VARCHAR2(10) NOT NULL ENABLE,
	"LANGUAGE_CODE" VARCHAR2(2) NOT NULL ENABLE,
	"STATUS" CHAR(1) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_MEDGUIDE" PRIMARY KEY ("MEDGUIDE_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
