-- ==========================================

  CREATE TABLE "TREXONE_DATA"."MEDICAL_CONDITION_XREF"
   (	"MEDICAL_CONDITION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"MEDICAL_CONDITION_REF_TYPE" VARCHAR2(10),
	"CONDITION_REF_NUM_PREFIX" CHAR(1),
	"CONDITION_REF_NUM" VARCHAR2(20),
	"CONDITION_REF_NUM_SUFFIX" VARCHAR2(10),
	"FORMATTED_CONDITION_REF_NUM" VARCHAR2(45),
	"DESCRIPTION" VARCHAR2(255),
	"PATIENT_DESCRIPTION" VARCHAR2(60),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"INVALIDATED_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE INDEX "TREXONE_DATA"."PK_MEDICAL_CONDITION_XREF" ON "TREXONE_DATA"."MEDICAL_CONDITION_XREF" ("MEDICAL_CONDITION_NUM", "DESCRIPTION", "FORMATTED_CONDITION_REF_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."MEDICAL_CONDITION_XREF" ADD CONSTRAINT "PK_MEDICAL_CONDITION_XREF" PRIMARY KEY ("MEDICAL_CONDITION_NUM")
  USING INDEX "TREXONE_DATA"."PK_MEDICAL_CONDITION_XREF"  ENABLE;
-- ==========================================
