-- ==========================================

  CREATE TABLE "TREXONE_DATA"."MEDICAL_AUTHORIZATION"
   (	"MEDICAL_AUTHORIZATION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PATIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"REPRESENTATIVE_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"AUTHORIZED_PARTY" VARCHAR2(255),
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE,
	"TERMINATION_DATE" DATE,
	"SIGNATURE_IMAGE_NUM" NUMBER(18,0),
	"AUTH_FORM_IMAGE_NUM" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"COMMENT_TEXT" VARCHAR2(1000),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_IMAGE_01" FOREIGN KEY ("SIGNATURE_IMAGE_NUM")
	  REFERENCES "TREXONE_DATA"."IMAGE" ("IMAGE_NUM") ENABLE,
	 CONSTRAINT "FK_PATIENT_01" FOREIGN KEY ("PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE,
	 CONSTRAINT "FK_KEEP_IMAGE_07" FOREIGN KEY ("AUTH_FORM_IMAGE_NUM")
	  REFERENCES "TREXONE_DATA"."KEEP_IMAGE" ("IMAGE_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_MEDICAL_AUTHORIZATION" ON "TREXONE_DATA"."MEDICAL_AUTHORIZATION" ("MEDICAL_AUTHORIZATION_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."MEDICAL_AUTHORIZATION" ADD CONSTRAINT "PK_MEDICAL_AUTHORIZATION" PRIMARY KEY ("MEDICAL_AUTHORIZATION_NUM")
  USING INDEX "TREXONE_DATA"."PK_MEDICAL_AUTHORIZATION"  ENABLE;
-- ==========================================
