-- ==========================================

  CREATE TABLE "TREXONE_DATA"."NHIN_LOG"
   (	"LLEVEL" NUMBER(4,0) NOT NULL ENABLE,
	"LLEVELDESCRIP" VARCHAR2(10) NOT NULL ENABLE,
	"FILL_STATE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"LTEXT" VARCHAR2(2000),
	"DATESTAMP" DATE DEFAULT SYSDATE,
	"SENT_STATUS" NUMBER(4,0),
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
-- ==========================================
