-- ==========================================

  CREATE TABLE "TREXONE_DATA"."NOTE"
   (	"NOTE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NOTE_TYPE" CHAR(1) NOT NULL ENABLE,
	"ORIGIN" NUMBER(18,0) NOT NULL ENABLE,
	"ORIGIN_TYPE" NUMBER(9,0),
	"ORIGIN_SEQ1" NUMBER(18,0),
	"ORIGIN_SEQ2" NUMBER(18,0),
	"ORIGIN_SEQ3" NUMBER(18,0),
	"NOTE_TEXT" VARCHAR2(4000),
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_NOTE" ON "TREXONE_DATA"."NOTE" ("NOTE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."NOTE" ADD CONSTRAINT "PK_NOTE" PRIMARY KEY ("NOTE_NUM")
  USING INDEX "TREXONE_DATA"."PK_NOTE"  ENABLE;
-- ==========================================
