-- ==========================================

  CREATE TABLE "TREXONE_DATA"."NUTRI_INFO"
   (	"NINFO_JAG_ID" VARCHAR2(6) NOT NULL ENABLE,
	"NINFO_TYPE" CHAR(1) NOT NULL ENABLE,
	"NINFO_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"NINFO_TEXT" VARCHAR2(500),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_NUTRI_INFO" ON "TREXONE_DATA"."NUTRI_INFO" ("NINFO_JAG_ID", "NINFO_TYPE", "NINFO_SEQ")
  ;
ALTER TABLE "TREXONE_DATA"."NUTRI_INFO" ADD CONSTRAINT "PK_NUTRI_INFO" PRIMARY KEY ("NINFO_JAG_ID", "NINFO_TYPE", "NINFO_SEQ")
  USING INDEX "TREXONE_DATA"."PK_NUTRI_INFO"  ENABLE;
-- ==========================================
