-- ==========================================

  CREATE TABLE "TREXONE_DATA"."NUTRI_NDC"
   (	"NNDC_NDCNUM" CHAR(11) NOT NULL ENABLE,
	"NNDC_NAME" VARCHAR2(40),
	"NNDC_JAG_ID" CHAR(6),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_NUTRI_NDC" ON "TREXONE_DATA"."NUTRI_NDC" ("NNDC_NDCNUM")
  ;
ALTER TABLE "TREXONE_DATA"."NUTRI_NDC" ADD CONSTRAINT "PK_NUTRI_NDC" PRIMARY KEY ("NNDC_NDCNUM")
  USING INDEX "TREXONE_DATA"."PK_NUTRI_NDC"  ENABLE;
-- ==========================================
