-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ORDER_SOURCE_TYPE"
   (	"ORDER_SOURCE_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(45) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_ORDER_SOURCE_TYPE" ON "TREXONE_DATA"."ORDER_SOURCE_TYPE" ("ORDER_SOURCE_TYPE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."ORDER_SOURCE_TYPE" ADD CONSTRAINT "PK_ORDER_SOURCE_TYPE" PRIMARY KEY ("ORDER_SOURCE_TYPE_NUM")
  USING INDEX "TREXONE_DATA"."PK_ORDER_SOURCE_TYPE"  ENABLE;
-- ==========================================
