-- ==========================================

  CREATE TABLE "TREXONE_DATA"."OTHER_COVERAGE_CODE"
   (	"OTHER_COVERAGE_CODE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(255),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_OTHER_COVERAGE_CODE" ON "TREXONE_DATA"."OTHER_COVERAGE_CODE" ("OTHER_COVERAGE_CODE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."OTHER_COVERAGE_CODE" ADD CONSTRAINT "PK_OTHER_COVERAGE_CODE" PRIMARY KEY ("OTHER_COVERAGE_CODE_NUM")
  USING INDEX "TREXONE_DATA"."PK_OTHER_COVERAGE_CODE"  ENABLE;
-- ==========================================
