-- ==========================================

  CREATE TABLE "TREXONE_DATA"."OUTBOUND_EMAIL_ORDER_ITEM"
   (	"OUTBOUND_EMAIL_ORDER_ITEM_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"PATIENT_NUM" NUMBER(18,0),
	"ORDER_NUM" NUMBER(18,0),
	"RX_NUM" NUMBER(18,0),
	"ITEM_NUM" NUMBER(18,0),
	"ITEM_QTY" NUMBER(18,0),
	"ITEM_PRICE" NUMBER(18,4),
	"ITEM_TAX" NUMBER(18,4),
	"NUM_REFILLS" NUMBER(18,0),
	"DAYS_SUPPLY" NUMBER(18,0),
	"ITEM_NAME" VARCHAR2(50),
	"STATUS" VARCHAR2(12),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"COMMUNICATION_DATE" DATE,
	 CONSTRAINT "PK_OUTBOUND_EMAIL_ORDER_ITEM" PRIMARY KEY ("OUTBOUND_EMAIL_ORDER_ITEM_NUM")
  USING INDEX  ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
