-- ==========================================

  CREATE TABLE "TREXONE_DATA"."OUTBOUND_CPS_MESSAGE_ITEM"
   (	"MESSAGE_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"OUTBOUND_CPS_MESSAGE_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"ORDER_NUM" NUMBER(18,0),
	"ITEM_SEQ" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"RX_NUMBER" VARCHAR2(20),
	 CONSTRAINT "FK_OCM_01" FOREIGN KEY ("OUTBOUND_CPS_MESSAGE_NUM")
	  REFERENCES "TREXONE_DATA"."OUTBOUND_CPS_MESSAGE" ("OUTBOUND_CPS_MESSAGE_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTOYMINTERVAL(3,'MONTH')) STORE IN ("LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
  CREATE INDEX "TREXONE_DATA"."PK_OUTBOUND_CPS_MESSAGE_ITEM" ON "TREXONE_DATA"."OUTBOUND_CPS_MESSAGE_ITEM" ("MESSAGE_ITEM_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."OUTBOUND_CPS_MESSAGE_ITEM" ADD CONSTRAINT "PK_OUTBOUND_CPS_MESSAGE_ITEM" PRIMARY KEY ("MESSAGE_ITEM_NUM")
  USING INDEX "TREXONE_DATA"."PK_OUTBOUND_CPS_MESSAGE_ITEM"  ENABLE;
-- ==========================================
