-- ==========================================

  CREATE TABLE "TREXONE_DATA"."OUTBOUND_EMAIL_MESSAGE"
   (	"OUTBOUND_EMAIL_MESSAGE_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"PATIENT_NUM" NUMBER(18,0),
	"ORDER_NUM" NUMBER(18,0),
	"TO_ADDR" VARCHAR2(511),
	"SUBJECT" VARCHAR2(100),
	"MESSAGE" VARCHAR2(4000),
	"MESSAGE_TYPE" VARCHAR2(20),
	"MESSAGE_STATUS" VARCHAR2(20),
	"IS_SUCCESSFUL" NUMBER(1,0),
	"ERROR_MESSAGE" VARCHAR2(2000),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"COMMUNICATION_DATE" DATE,
	 CONSTRAINT "PK_OUTBOUND_EMAIL_MESSAGE" PRIMARY KEY ("OUTBOUND_EMAIL_MESSAGE_NUM")
  USING INDEX  ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
