-- ==========================================

  CREATE TABLE "TREXONE_DATA"."OUTBOUND_MSG_QUEUE"
   (	"OUTBOUND_MSG_QUEUE_NUM" NUMBER(18,0),
	"MSG_STATUS" CHAR(1),
	"TRANSMISSION_ATTEMPTS" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"DATETIME_LAST_ATTEMPT" DATE,
	"DATETIME_ADDED" DATE DEFAULT sysdate NOT NULL ENABLE,
	"DESTINATION_URL" VARCHAR2(255) NOT NULL ENABLE,
	"MESSAGE" CLOB NOT NULL ENABLE,
	"LAST_ERROR_MESSAGE" VARCHAR2(255),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	"HTTP_STATUS" NUMBER(4,0),
	"RESPONSE_MESSAGE" CLOB,
	"ELAPSED_TIME" NUMBER,
	"PARTITION_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) DEFAULT 0 NOT NULL ENABLE,
	 CONSTRAINT "PK_OUTBOUND_MSG_QUEUE" PRIMARY KEY ("OUTBOUND_MSG_QUEUE_NUM")
  USING INDEX  ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTOYMINTERVAL(3, 'MONTH'))
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2013-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
