-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PARTITION_SPLIT"
   (	"TABLE_NAME" VARCHAR2(30),
	"NEW_PARTITION_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"PARTITION_TO_SPLIT" VARCHAR2(30),
	"SPLIT_AT_DATE" DATE,
	"SPLIT_START_TIME" TIMESTAMP (6),
	"SPLIT_END_TIME" TIMESTAMP (6),
	"SPLIT_STATUS" VARCHAR2(500),
	"INDEX_REBUILD_START_TIME" TIMESTAMP (6),
	"INDEX_REBUILD_END_TIME" TIMESTAMP (6),
	"INDEX_REBUILD_STATUS" VARCHAR2(500),
	"NUM_ROWS" NUMBER,
	"PURGE_STATUS" VARCHAR2(500),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_PARTITION_SPLIT" PRIMARY KEY ("TABLE_NAME", "NEW_PARTITION_NAME")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
