-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PARTITION_MAX"
   (	"TABLE_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"COLUMN_NAME" VARCHAR2(30),
	"COLUMN_POSITION" NUMBER(2,0),
	"MIN_VALUE" DATE,
	"MAX_VALUE" DATE,
	"NUM_ROWS" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_PARTITION_MAX" PRIMARY KEY ("TABLE_NAME", "COLUMN_NAME")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
