-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PATIENT_PERM_RX"
   (	"PATIENT_PERM_RX_NUM" NUMBER(18,0),
	"PATIENT_NUM" NUMBER(18,0),
	"PRODUCT_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"FIRST_FILL_QTY" NUMBER(13,3),
	"TOTAL_DAILY_DOSE" NUMBER(13,3),
	"CREATE_DATE" DATE,
	"EXPIRY_DATE" DATE,
	"LATIN_FREQUENCY_CODE" VARCHAR2(10),
	"LATIN_FREQUENCY_QTY" NUMBER(9,0),
	"DAYS_SUPPLY" NUMBER(9,0),
	"USER_INSTRUCTIONS" VARCHAR2(2000),
	"UNEXPANDED_DIRECTIONS" VARCHAR2(2000),
	"IS_ACTIVE" CHAR(1),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	"LTC_PRINT_ON_MAR_REPORT" CHAR(1),
	"LTC_PRINT_ON_POF_REPORT" CHAR(1),
	"DOSE" NUMBER(13,3),
	 CONSTRAINT "PK_PATIENT_PERM_RX" PRIMARY KEY ("PATIENT_PERM_RX_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_PATIENT_33" FOREIGN KEY ("PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE,
	 CONSTRAINT "FK_PRODUCT_45" FOREIGN KEY ("PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT" ("PRODUCT_NUM") ENABLE,
	 CONSTRAINT "FK_FACILITY_96" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_LATIN_FREQUENCY_03" FOREIGN KEY ("LATIN_FREQUENCY_CODE")
	  REFERENCES "TREXONE_DATA"."LATIN_FREQUENCY" ("LATIN_FREQUENCY_CODE") ENABLE
   ) ;
-- ==========================================
