-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PATIENT_GROUP_POSITION"
   (	"POSITION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(45) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PATIENT_GROUP_POSITION" ON "TREXONE_DATA"."PATIENT_GROUP_POSITION" ("POSITION_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PATIENT_GROUP_POSITION" ADD CONSTRAINT "PK_PATIENT_GROUP_POSITION" PRIMARY KEY ("POSITION_NUM")
  USING INDEX "TREXONE_DATA"."PK_PATIENT_GROUP_POSITION"  ENABLE;
-- ==========================================
