-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PATIENT_NOTE"
   (	"PATIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PATIENT_NOTE_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"NOTE_TEXT" VARCHAR2(4000) NOT NULL ENABLE,
	"CREATE_DATE" DATE,
	"CREATE_USER" NUMBER(18,0) NOT NULL ENABLE,
	"PRIORITY" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PRIORITY_INDICATOR" CHAR(1),
	"PATIENT_NOTE_TYPE_CODE" CHAR(1) DEFAULT 'G' NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PATIENT_10" FOREIGN KEY ("PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PATIENT_NOTE" ON "TREXONE_DATA"."PATIENT_NOTE" ("PATIENT_NUM", "PATIENT_NOTE_SEQ")
  ;
ALTER TABLE "TREXONE_DATA"."PATIENT_NOTE" ADD CONSTRAINT "PK_PATIENT_NOTE" PRIMARY KEY ("PATIENT_NUM", "PATIENT_NOTE_SEQ")
  USING INDEX "TREXONE_DATA"."PK_PATIENT_NOTE"  ENABLE;
-- ==========================================
