-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PATIENT_ID_NCPDP"
   (	"PATIENT_ID_NCPDP_NUM" NUMBER(18,0),
	"PATIENT_NUM" NUMBER(18,0),
	"QUALIFIER" VARCHAR2(2),
	"IDENTIFIER" VARCHAR2(20),
	"ID_STATE" VARCHAR2(2),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"ID_EXPIRATION_DATE" DATE,
	 CONSTRAINT "PK_PATIENT_ID_NCPDP" PRIMARY KEY ("PATIENT_ID_NCPDP_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_PATIENT_34" FOREIGN KEY ("PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE
   ) ;
-- ==========================================
