-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PATIENT_EXTRA_MEDICATION"
   (	"PATIENT_EXTRA_MEDICATION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PATIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRODUCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"QUANTITY" NUMBER(10,3),
	"DAYS_SUPPLY" NUMBER(10,3),
	"QTY_PER_DOSE" NUMBER(10,3),
	"FREQUENCY" NUMBER(10,3),
	"IS_ACTIVE" CHAR(1) NOT NULL ENABLE,
	"CREATE_DATE" DATE NOT NULL ENABLE,
	"CREATE_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"EFFECTIVE_DATE" DATE,
	"TERMINATION_DATE" DATE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DIRECTIONS" VARCHAR2(2000),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PATIENT_05" FOREIGN KEY ("PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE,
	 CONSTRAINT "FK_PRODUCT_08" FOREIGN KEY ("PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT" ("PRODUCT_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PATIENT_EXTRA_MEDICATION" ON "TREXONE_DATA"."PATIENT_EXTRA_MEDICATION" ("PATIENT_EXTRA_MEDICATION_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PATIENT_EXTRA_MEDICATION" ADD CONSTRAINT "PK_PATIENT_EXTRA_MEDICATION" PRIMARY KEY ("PATIENT_EXTRA_MEDICATION_NUM")
  USING INDEX "TREXONE_DATA"."PK_PATIENT_EXTRA_MEDICATION"  ENABLE;
-- ==========================================
