-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PATIENT_RX_MOVE"
   (	"PATIENT_RX_MOVE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SOURCE_PATIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TARGET_PATIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_FACILITY_55" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_PATIENT_24" FOREIGN KEY ("SOURCE_PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE,
	 CONSTRAINT "FK_PATIENT_25" FOREIGN KEY ("TARGET_PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE,
	 CONSTRAINT "FK_RX_12" FOREIGN KEY ("RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_BASE" ("RX_RECORD_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PATIENT_RX_MOVE" ON "TREXONE_DATA"."PATIENT_RX_MOVE" ("PATIENT_RX_MOVE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PATIENT_RX_MOVE" ADD CONSTRAINT "PK_PATIENT_RX_MOVE" PRIMARY KEY ("PATIENT_RX_MOVE_NUM")
  USING INDEX "TREXONE_DATA"."PK_PATIENT_RX_MOVE"  ENABLE;
-- ==========================================
