-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PATIENT_ALLERGY_SYMPTOM"
   (	"PATIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ALLERGEN_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SYMPTOM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"STATUS" CHAR(1) NOT NULL ENABLE,
	"CREATE_DATE" DATE NOT NULL ENABLE,
	"CREATE_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(255),
	"SEVERITY_NUM" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_ALLERGY_SYMPTOM_01" FOREIGN KEY ("SYMPTOM_NUM")
	  REFERENCES "TREXONE_DATA"."ALLERGY_SYMPTOM" ("SYMPTOM_NUM") ENABLE,
	 CONSTRAINT "FK_PATIENT_ALLERGY_02" FOREIGN KEY ("PATIENT_NUM", "ALLERGEN_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT_ALLERGY" ("PATIENT_NUM", "ALLERGEN_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PATIENT_ALLERGY_SYMPTOM" ON "TREXONE_DATA"."PATIENT_ALLERGY_SYMPTOM" ("PATIENT_NUM", "ALLERGEN_NUM", "SYMPTOM_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PATIENT_ALLERGY_SYMPTOM" ADD CONSTRAINT "PK_PATIENT_ALLERGY_SYMPTOM" PRIMARY KEY ("PATIENT_NUM", "ALLERGEN_NUM", "SYMPTOM_NUM")
  USING INDEX "TREXONE_DATA"."PK_PATIENT_ALLERGY_SYMPTOM"  ENABLE;
-- ==========================================
