-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PATIENT_TO_SPECIALTY_PROG"
   (	"PATIENT_TO_SPECIALTY_PROG_NUM" NUMBER(22,0),
	"SPECIALTY_PROGRAM_NUM" NUMBER(22,0),
	"PATIENT_NUM" NUMBER(22,0),
	"DATA_GROUP" NUMBER(22,0),
	"ELIGIBILITY_START_DATE" DATE,
	"ELIGIBILITY_END_DATE" DATE,
	"DEACTIVATED_DATE" DATE,
	"SYS_USER" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID'),
	"DEACTIVATION_REASON" NUMBER(9,0),
	 CONSTRAINT "PATIENT_TO_SPECIALTY_PROG_PK" PRIMARY KEY ("PATIENT_TO_SPECIALTY_PROG_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SPECIALTY_PROGRAM_01" FOREIGN KEY ("SPECIALTY_PROGRAM_NUM")
	  REFERENCES "TREXONE_DATA"."SPECIALTY_PROGRAM" ("SPECIALTY_PROGRAM_NUM") ENABLE,
	 CONSTRAINT "FK_PATIENT_40" FOREIGN KEY ("PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE,
	 CONSTRAINT "FK_DATA_GROUP_25" FOREIGN KEY ("DATA_GROUP")
	  REFERENCES "TREXONE_DATA"."DATA_GROUP" ("DATA_GROUP") ENABLE
   ) ;
-- ==========================================
