-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PATIENT_ID_SOURCE"
   (	"PATIENT_ID_SOURCE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(40) NOT NULL ENABLE,
	"CODE" VARCHAR2(10) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"IS_ACTIVE" CHAR(1),
	"TIMEZONE_ID" VARCHAR2(60),
	"IS_TZ_OVERRIDE" CHAR(1),
	"PID_MIN_LENGTH" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"PID_MAX_LENGTH" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"PID_DATA_TYPE" CHAR(1) DEFAULT 'A',
	"CHECK_DIGIT" CHAR(1) DEFAULT 'N',
	"PID_SYS_GENERATED" CHAR(1) DEFAULT 'N',
	"PID_REQUIRED" CHAR(1) DEFAULT 'N',
	"PARTNER_TYPE" CHAR(1) DEFAULT 'H',
	"PID_NEXT_VALUE" VARCHAR2(30),
	 CONSTRAINT "PK_PATIENT_ID_SOURCE" PRIMARY KEY ("PATIENT_ID_SOURCE_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
