-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PATIENT_USER_DEFINED_FIELD"
   (	"PATIENT_USER_DEFINED_FIELD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PATIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FIELD_LABEL" NUMBER(9,0),
	"FIELD_VALUE" VARCHAR2(50),
	"DATESTAMP" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PATIENT_12" FOREIGN KEY ("PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PATIENT_USER_DEFINED_FIELD" ON "TREXONE_DATA"."PATIENT_USER_DEFINED_FIELD" ("PATIENT_USER_DEFINED_FIELD_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PATIENT_USER_DEFINED_FIELD" ADD CONSTRAINT "PK_PATIENT_USER_DEFINED_FIELD" PRIMARY KEY ("PATIENT_USER_DEFINED_FIELD_NUM")
  USING INDEX "TREXONE_DATA"."PK_PATIENT_USER_DEFINED_FIELD"  ENABLE;
-- ==========================================
