-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PATIENT_EXTRA_TP_INFO"
   (	"PATIENT_EXTRA_TP_INFO_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"GUARANTOR_MIDDLE_NAME" VARCHAR2(30),
	"PATIENT_NUM" NUMBER(18,0),
	"GUARANTOR_FIRST_NAME" VARCHAR2(30),
	"GUARANTOR_LAST_NAME" VARCHAR2(30),
	"GUARANTOR_SUFFIX_ABBR" VARCHAR2(12),
	"SERVICE_FACILITY_NAME" VARCHAR2(30),
	"SERVICE_FACILITY_ID_QUALIFIER1" VARCHAR2(10),
	"SERVICE_FACILITY_ID1" VARCHAR2(30),
	"SERVICE_FACILITY_ID_QUALIFIER2" VARCHAR2(10),
	"SERVICE_FACILITY_ID2" VARCHAR2(30),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PATIENT_06" FOREIGN KEY ("PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PATIENT_EXTRA_TP_INFO" ON "TREXONE_DATA"."PATIENT_EXTRA_TP_INFO" ("PATIENT_EXTRA_TP_INFO_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PATIENT_EXTRA_TP_INFO" ADD CONSTRAINT "PK_PATIENT_EXTRA_TP_INFO" PRIMARY KEY ("PATIENT_EXTRA_TP_INFO_NUM")
  USING INDEX "TREXONE_DATA"."PK_PATIENT_EXTRA_TP_INFO"  ENABLE;
-- ==========================================
