-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PAYMENT_TYPE"
   (	"PAYMENT_TYPE_NUM" NUMBER(18,0),
	"PAYMENT_TYPE_NAME" VARCHAR2(50) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"FOR_PAYMENT_ONLY" CHAR(1),
	 CONSTRAINT "PK_PAYMENT_TYPE" PRIMARY KEY ("PAYMENT_TYPE_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
