-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PAYMENT_EXCEPTION_LINK"
   (	"PAYMENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PAYMENT_EXCEPTION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CC_TRANS_REQUEST_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RESOLVED" NUMBER(9,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"AVS_VALIDATION_MESSAGE" VARCHAR2(100),
	"CVV_VALIDATION_MESSAGE" VARCHAR2(100),
	"ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	 CONSTRAINT "PK_PAYMENT_EXCEPTION_LINK" PRIMARY KEY ("PAYMENT_NUM", "PAYMENT_EXCEPTION_NUM", "CC_TRANS_REQUEST_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_PAYMENT_EXCEPTION_01" FOREIGN KEY ("PAYMENT_EXCEPTION_NUM")
	  REFERENCES "TREXONE_DATA"."PAYMENT_EXCEPTION" ("PAYMENT_EXCEPTION_NUM") ENABLE,
	 CONSTRAINT "FK_PAYMENT_02" FOREIGN KEY ("PAYMENT_NUM")
	  REFERENCES "TREXONE_DATA"."PAYMENT" ("PAYMENT_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
