-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PAYMENT_EXCEPTION"
   (	"PAYMENT_EXCEPTION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CREDIT_CARD_PROCESSOR_NUM" NUMBER(18,0),
	"EXCEPTION_CODE" VARCHAR2(20),
	"EXCEPTION_CODE_DESCRIPTION" VARCHAR2(100) NOT NULL ENABLE,
	"EXCEPTION_TRANSACTION_TYPE" VARCHAR2(100) NOT NULL ENABLE,
	"EXCEPTION_TYPE" CHAR(1) NOT NULL ENABLE,
	"EXCEPTION_MESSAGE" VARCHAR2(200),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"EXCEPTION_TRANS_TYPE_FILTER" VARCHAR2(100),
	"EXCEPTION_MESSAGE_FILTER" VARCHAR2(200),
	 CONSTRAINT "PK_PAYMENT_EXCEPTION" PRIMARY KEY ("PAYMENT_EXCEPTION_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_CREDIT_CARD_PROCESSOR_01" FOREIGN KEY ("CREDIT_CARD_PROCESSOR_NUM")
	  REFERENCES "TREXONE_DATA"."CREDIT_CARD_PROCESSOR" ("CREDIT_CARD_PROCESSOR_NUM") ENABLE
   ) ;
-- ==========================================
