-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PAYMENT_GROUP"
   (	"PAYMENT_GROUP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"GROUP_HEALTH_CARD_TYPE" VARCHAR2(30),
	"PAYMENT_GROUP_AMOUNT_CALC" NUMBER(17,6),
	"PATIENT_PAY_AMOUNT_CALC" NUMBER(17,6),
	"CALCULATION_DTSTAMP" DATE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT sysdate NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_PAYMENT_GROUP" PRIMARY KEY ("PAYMENT_GROUP_NUM")
  USING INDEX  ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
