-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PAYMENT_GROUP_LIST"
   (	"PAYMENT_GROUP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PAYMENT_GROUP_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"PAYMENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PAYMENT_GROUP_LIST_AMOUNT" NUMBER(17,6),
	"APPLY_BALANCE_PERCENTAGE_RATE" NUMBER(9,0),
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT sysdate NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_PAYMENT_GROUP_LIST" PRIMARY KEY ("PAYMENT_GROUP_NUM", "PAYMENT_GROUP_SEQ")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_PAYMENT_GROUP_01" FOREIGN KEY ("PAYMENT_GROUP_NUM")
	  REFERENCES "TREXONE_DATA"."PAYMENT_GROUP" ("PAYMENT_GROUP_NUM") ENABLE,
	 CONSTRAINT "FK_PAYMENT_03" FOREIGN KEY ("PAYMENT_NUM")
	  REFERENCES "TREXONE_DATA"."PAYMENT" ("PAYMENT_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
