-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PAYMENT_STATUS"
   (	"PAYMENT_STATUS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PAYMENT_STATUS_NAME" VARCHAR2(50) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_PAYMENT_STATUS" PRIMARY KEY ("PAYMENT_STATUS_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
