-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PCD_REPORT"
   (	"PCD_REPORT_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"REQUEST_SYS_USER" NUMBER(18,0),
	"REQUEST_DATE" DATE,
	"USER_COMMENT" VARCHAR2(4000),
	"REPORT_TYPE" VARCHAR2(100),
	"REPORT_FROM_DATE" DATE,
	"REPORT_TO_DATE" DATE,
	"CUSTOMER_NAME" VARCHAR2(100),
	"REPORT_SOURCE" VARCHAR2(100),
	"REPORT_STATUS" VARCHAR2(100),
	"BATCH_START_DATE" DATE,
	"BATCH_END_DATE" DATE,
	"BATCH_ERROR_MESSAGE" VARCHAR2(4000),
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"PCD_REPORT_NAME" VARCHAR2(200),
	 CONSTRAINT "PK_PCD_REPORT" PRIMARY KEY ("PCD_REPORT_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_FACILITY_105" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_SYSTEM_USER_55" FOREIGN KEY ("REQUEST_SYS_USER")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE NOVALIDATE
   ) ;
-- ==========================================
