-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PDMP_NARX_SCORES"
   (	"PDMP_NARX_SCORES_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PDMP_RESPONSE_NUM" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"RX_FILL_SEQ" NUMBER(18,0),
	"IS_ACTIVE" CHAR(1),
	"NARCOTICS_NARX_SCORE" VARCHAR2(10),
	"SEDATIVES_NARX_SCORE" VARCHAR2(10),
	"STIMULANTS_NARX_SCORE" VARCHAR2(10),
	"OVERDOSE_NARX_SCORE" VARCHAR2(10),
	"MISUSE_NARX_SCORE" VARCHAR2(10),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	"PARTITION_DATE" DATE DEFAULT sysdate NOT NULL ENABLE,
	 CONSTRAINT "PDMP_NARX_SCORES_PK" PRIMARY KEY ("PDMP_NARX_SCORES_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "PDMP_NARX_SCORES_FK01" FOREIGN KEY ("PDMP_RESPONSE_NUM")
	  REFERENCES "TREXONE_DATA"."PDMP_RESPONSE" ("PDMP_RESPONSE_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "PDMP_NARX_SCORES_FK02" FOREIGN KEY ("RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_BASE" ("RX_RECORD_NUM") ENABLE NOVALIDATE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTOYMINTERVAL(3,'MONTH')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
