-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PHONE"
   (	"PHONE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CTRY_CODE" VARCHAR2(8),
	"AREA_CODE" VARCHAR2(4),
	"PHONE_NUMBER" VARCHAR2(20),
	"EXT" VARCHAR2(6),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"CARRIER" VARCHAR2(32),
	 CONSTRAINT "FK_COUNTRY_01" FOREIGN KEY ("CTRY_CODE")
	  REFERENCES "TREXONE_DATA"."COUNTRY" ("CTRY_CODE") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PHONE" ON "TREXONE_DATA"."PHONE" ("PHONE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PHONE" ADD CONSTRAINT "PK_PHONE" PRIMARY KEY ("PHONE_NUM")
  USING INDEX "TREXONE_DATA"."PK_PHONE"  ENABLE;
-- ==========================================
