-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PHONE_TYPE"
   (	"PHONE_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(30) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PHONE_TYPE" ON "TREXONE_DATA"."PHONE_TYPE" ("PHONE_TYPE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PHONE_TYPE" ADD CONSTRAINT "PK_PHONE_TYPE" PRIMARY KEY ("PHONE_TYPE_NUM")
  USING INDEX "TREXONE_DATA"."PK_PHONE_TYPE"  ENABLE;
-- ==========================================
