-- ==========================================

  CREATE TABLE "TREXONE_DATA"."POLICY_DATA"
   (	"POLICY_ID" NUMBER(10,0) NOT NULL ENABLE,
	"POLICY" CLOB NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PKPOLICY_DATA2" ON "TREXONE_DATA"."POLICY_DATA" ("POLICY_ID")
  ;
ALTER TABLE "TREXONE_DATA"."POLICY_DATA" ADD CONSTRAINT "PKPOLICY_DATA2" PRIMARY KEY ("POLICY_ID")
  USING INDEX "TREXONE_DATA"."PKPOLICY_DATA2"  ENABLE;
-- ==========================================
