-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PPI_MESSAGE_OBSERVATION"
   (	"PPI_MESSAGE_OBSERVATION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PPI_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DIMENSION" VARCHAR2(500) NOT NULL ENABLE,
	"VALUE" NUMBER(38,20) NOT NULL ENABLE,
	"OBSERVATION_DATE" DATE,
	"MEASUREMENT_DATA_QUAL" CHAR(1),
	"MEASUREMENT_SOURCE_CODE" VARCHAR2(2),
	"MEASUREMENT_UNIT_CODE" VARCHAR2(15),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	"LOINC_VERSION" VARCHAR2(500),
	"UNIT_OF_MEASURE" VARCHAR2(500),
	"UCUM_VERSION" VARCHAR2(500),
	 CONSTRAINT "PK_PPI_MESSAGE_OBSERVATION" PRIMARY KEY ("PPI_MESSAGE_OBSERVATION_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_PPI_MESSAGE_10" FOREIGN KEY ("PPI_MESSAGE_NUM")
	  REFERENCES "TREXONE_DATA"."PPI_MESSAGE" ("PPI_MESSAGE_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
