-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PPI_OBSERVATION_LOINC"
   (	"PPI_OBSERVATION_LOINC_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"LOINC_VITAL_SIGN_CODE" VARCHAR2(30) NOT NULL ENABLE,
	"LOINC_SHORT_NAME" VARCHAR2(200),
	"LOINC_LONG_COMMON_NAME" VARCHAR2(500),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_PPI_OBSERVATION_LOINC" PRIMARY KEY ("PPI_OBSERVATION_LOINC_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
