-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PPI_LINK_MIGRATION"
   (	"PPI_LINK_MIGRATION_NUM" NUMBER,
	"MIGRATION_STATUS" CHAR(1) DEFAULT 'U' NOT NULL ENABLE,
	"GATEWAY_ID" CHAR(13),
	"DEA" VARCHAR2(25),
	"FIRST_NAME" VARCHAR2(35),
	"MIDDLE_NAME" VARCHAR2(35),
	"LAST_NAME" VARCHAR2(35),
	"SUFFIX_NAME" VARCHAR2(18),
	"CLINIC_NAME" VARCHAR2(35),
	"ADDRESS_LINE1" VARCHAR2(35),
	"ADDRESS_LINE2" VARCHAR2(35),
	"CITY" VARCHAR2(35),
	"STATE" CHAR(2),
	"ZIP" VARCHAR2(11),
	"PRIMARY_PHONE" VARCHAR2(25),
	"ACTIVE_START_DATE" DATE,
	"ACTIVE_END_DATE" DATE,
	"SERVICE_LEVEL" NUMBER(5,0),
	"IS_MANUALLY_DELETED" CHAR(1),
	"PRESCRIBER_NUM" NUMBER(18,0),
	"PRESCRIBER_ADDRESS_NUM" VARCHAR2(18),
	"LINK_ACTIVE_START_DATE" DATE,
	"LINK_ACTIVE_END_DATE" DATE,
	"LINK_SERVICE_LEVEL" NUMBER(5,0),
	"LINK_TYPE" CHAR(1),
	"IS_PPI_ENABLED" CHAR(1),
	"PPI_REGISTRY_ADDR_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_PPI_LINK_MIGRATION_PK" PRIMARY KEY ("PPI_LINK_MIGRATION_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
