-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PPI_MSG_LOT"
   (	"PPI_MSG_LOT_NUM" NUMBER(18,0),
	"PPI_MESSAGE_MEDICATION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"OTHER_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"TYPE" VARCHAR2(3) DEFAULT 'CI' NOT NULL ENABLE,
	"LOT_NUMBER" VARCHAR2(140),
	"LOT_EXPIRATION_DATE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_PPI_MSG_LOT" PRIMARY KEY ("PPI_MSG_LOT_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_122" FOREIGN KEY ("SYS_USER")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_PPI_MESSAGE_MEDICATION_04" FOREIGN KEY ("PPI_MESSAGE_MEDICATION_NUM")
	  REFERENCES "TREXONE_DATA"."PPI_MESSAGE_MEDICATION" ("PPI_MESSAGE_MEDICATION_NUM") ENABLE NOVALIDATE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTOYMINTERVAL(3,'MONTH')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
