-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PPI_MSG_CODE_QUAL_TEXT"
   (	"PPI_MSG_CODE_QUAL_TEXT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PPI_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ENTITY_TYPE" CHAR(1) NOT NULL ENABLE,
	"CODE_NAME" VARCHAR2(50) NOT NULL ENABLE,
	"CODE" VARCHAR2(50),
	"QUALIFIER" VARCHAR2(30),
	"TEXT" VARCHAR2(500),
	"OTHER_DESCRIPTION" VARCHAR2(500),
	"OTHER_VALUE" VARCHAR2(500),
	"PPI_MSG_ALLERGY_ADVERSE_NUM" NUMBER(18,0),
	"PPI_MESSAGE_MEDICATION_NUM" NUMBER(18,0),
	"PPI_MSG_MED_WOUND_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_PPI_MSG_CODE_QUAL_TEXT" PRIMARY KEY ("PPI_MSG_CODE_QUAL_TEXT_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_PPI_MSG_CODE_QUAL_TEXT_01" FOREIGN KEY ("PPI_MESSAGE_NUM")
	  REFERENCES "TREXONE_DATA"."PPI_MESSAGE" ("PPI_MESSAGE_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTOYMINTERVAL(3,'MONTH')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2016-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
