-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PPI_MESSAGE"
   (	"PPI_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(120) NOT NULL ENABLE,
	"DESTINATION" VARCHAR2(120) NOT NULL ENABLE,
	"MESSAGE_ID" VARCHAR2(35) NOT NULL ENABLE,
	"MESSAGE_TYPE" NUMBER(2,0) NOT NULL ENABLE,
	"SENT_TIME" DATE NOT NULL ENABLE,
	"RELATED_MESSAGE_ID" VARCHAR2(35),
	"TEST_MESSAGE_IND" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"IMAGE_NUM" NUMBER(18,0),
	"PROCESSED_CODE" CHAR(1) DEFAULT 'U' NOT NULL ENABLE,
	"IS_MATCHED" CHAR(1) DEFAULT 'N' NOT NULL ENABLE,
	"ERROR_CODE" NUMBER(3,0),
	"RX_FILL_SEQ" NUMBER(18,0),
	"ELECTRONIC_ORDER_NUM" NUMBER(18,0),
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"PPI_NETWORK_NUM" NUMBER(18,0),
	"BATCH_REASON" CHAR(1) DEFAULT 'A' NOT NULL ENABLE,
	"VERSION" VARCHAR2(10),
	"RELEASE" VARCHAR2(10),
	"HIGHEST_VERSION_SUPPORTED" VARCHAR2(6),
	"RECIPIENT_QUALIFIER" VARCHAR2(3),
	"SENDER_QUALIFIER" VARCHAR2(3),
	"SENDER_SOFTWARE_DEVELOPER" VARCHAR2(35),
	"SENDER_SOFTWARE_PRODUCT" VARCHAR2(35),
	"SENDER_SOFTWARE_VERSION_REL" VARCHAR2(50),
	"TERITARY_IDENTIFIER" VARCHAR2(3),
	"RETURN_RECEIPT" VARCHAR2(3),
	"REQUEST_REFERENCE_NUM" VARCHAR2(35),
	"RECIPIENT_VALUE" VARCHAR2(80),
	"SENDER_VALUE" VARCHAR2(80),
	"IS_AUTOPOPULATED" CHAR(1),
	"EPCS_MESSAGE_NUM" NUMBER(18,0),
	"IS_EPCS" CHAR(1),
	"MATCH_USER" NUMBER(18,0),
	"MATCH_TIME" DATE,
	"ACK_USER" NUMBER(18,0),
	"ACK_TIME" DATE,
	"IS_SKIP_PRE_VERIF_ELIGIBLE" CHAR(1) DEFAULT 'N' NOT NULL ENABLE,
	"IS_SKIP_PRE_VERIF_DECLINED" CHAR(1) DEFAULT 'N' NOT NULL ENABLE,
	"URGENCY_INDICATOR_CODE" VARCHAR2(30),
	"PROHIBIT_RENEWAL_REQUEST" CHAR(1),
	"PATIENT_PERM_RX_NUM" NUMBER(18,0),
	"PPI_MESSAGE_LEVEL" NUMBER,
	"DATATYPES_VERSION" VARCHAR2(35),
	"TRANSPORT_VERSION" VARCHAR2(35),
	"TRANSACTION_DOMAIN_CODE" VARCHAR2(35),
	"STRUCTURE_VERSION" VARCHAR2(35),
	"ECL_VERSION" VARCHAR2(35),
	"MESSAGE_INDICATOR_FLAG" VARCHAR2(35),
	"PRESC_ORDER_GRP_NUM" VARCHAR2(35),
	"PRESC_ORDER_GRP_ITEM_COUNT" NUMBER(18,0),
	"PRESC_ORDER_GRP_TOTAL_COUNT" NUMBER(18,0),
	"PRESC_ORDER_GRP_REASON" VARCHAR2(80),
	"RX_REF_ORDER_GRP_NUM" VARCHAR2(35),
	"RX_REF_ORDER_GRP_ITEM_COUNT" NUMBER(18,0),
	"RX_REF_ORDER_GRP_TOTAL_COUNT" NUMBER(18,0),
	"RX_REF_ORDER_GRP_REASON" VARCHAR2(80),
	"OTHER_REF_NUMBER_VALUE" VARCHAR2(35),
	"OTHER_REF_NUMBER_CODE" VARCHAR2(20),
	 CONSTRAINT "YES_NO_RULE3735" CHECK (is_matched IN ('N', 'Y')) ENABLE,
	 CONSTRAINT "IU_PPI_MESSAGE_01" UNIQUE ("SOURCE", "MESSAGE_ID", "ERX_CLIENT_ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_ELECTRONIC_ORDER_05" FOREIGN KEY ("ELECTRONIC_ORDER_NUM")
	  REFERENCES "TREXONE_DATA"."ELECTRONIC_ORDER" ("ELECTRONIC_ORDER_NUM") ENABLE,
	 CONSTRAINT "FK_FACILITY_39" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_RX_FILL_11" FOREIGN KEY ("RX_FILL_SEQ", "RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_FILL" ("RX_FILL_SEQ", "RX_RECORD_NUM") ENABLE,
	 CONSTRAINT "FK_PPI_NETWORK_02" FOREIGN KEY ("PPI_NETWORK_NUM")
	  REFERENCES "TREXONE_DATA"."PPI_NETWORK" ("PPI_NETWORK_NUM") ENABLE,
	 CONSTRAINT "FK_EPCS_MESSAGE_01" FOREIGN KEY ("EPCS_MESSAGE_NUM")
	  REFERENCES "TREXONE_DATA"."EPCS_MESSAGE" ("EPCS_MESSAGE_NUM") ENABLE,
	 CONSTRAINT "FK_PATIENT_PERM_RX_NUM" FOREIGN KEY ("PATIENT_PERM_RX_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT_PERM_RX" ("PATIENT_PERM_RX_NUM") ENABLE NOVALIDATE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE INDEX "TREXONE_DATA"."PK_PPI_MESSAGE" ON "TREXONE_DATA"."PPI_MESSAGE" ("PPI_MESSAGE_NUM", "MESSAGE_ID", "FACILITY_NUM", "RX_RECORD_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PPI_MESSAGE" ADD CONSTRAINT "PK_PPI_MESSAGE" PRIMARY KEY ("PPI_MESSAGE_NUM")
  USING INDEX "TREXONE_DATA"."PK_PPI_MESSAGE"  ENABLE;
-- ==========================================
