-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PPI_MSG_MED_MEASUREMENT"
   (	"PPI_MSG_MED_MEASUREMENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PPI_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PPI_MESSAGE_MEDICATION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"VITAL_SIGN" VARCHAR2(500),
	"LOINC_VERSION" VARCHAR2(500),
	"VALUE" VARCHAR2(50),
	"UNIT_OF_MEASURE" VARCHAR2(500),
	"UCUM_VERSION" VARCHAR2(500),
	"MIN_MEASUREMENT_VALUE" VARCHAR2(50),
	"MAX_MEASUREMENT_VALUE" VARCHAR2(50),
	"MEASUREMENT_NOTES" VARCHAR2(300),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_PPI_MSG_MED_MEASUREMENT" PRIMARY KEY ("PPI_MSG_MED_MEASUREMENT_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_PPI_MSG_MED_MEASUREMENT_02" FOREIGN KEY ("PPI_MESSAGE_MEDICATION_NUM")
	  REFERENCES "TREXONE_DATA"."PPI_MESSAGE_MEDICATION" ("PPI_MESSAGE_MEDICATION_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_PPI_MSG_MED_MEASUREMENT_01" FOREIGN KEY ("PPI_MESSAGE_NUM")
	  REFERENCES "TREXONE_DATA"."PPI_MESSAGE" ("PPI_MESSAGE_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTOYMINTERVAL(3,'MONTH')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2016-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
