-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PPI_SIG_MAPPING"
   (	"PPI_SIG_MAPPING_NUM" NUMBER(18,0),
	"PPI_SIG_TEXT" VARCHAR2(1000) NOT NULL ENABLE,
	"ERX_SIG_MACRO" VARCHAR2(150) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"STATUS" CHAR(1) DEFAULT 'A' NOT NULL ENABLE,
	"CREATE_USER" NUMBER(18,0) DEFAULT 0 NOT NULL ENABLE,
	"CREATE_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	 CONSTRAINT "PK_PPI_SIG_MAPPING" PRIMARY KEY ("PPI_SIG_MAPPING_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "UC_PPI_SIG_MAPPING_01" UNIQUE ("PPI_SIG_TEXT")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_95" FOREIGN KEY ("SYS_USER")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE NOVALIDATE
   ) ;
-- ==========================================
