-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PPI_MESSAGE_PHONE"
   (	"PPI_MESSAGE_PHONE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PPI_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ENTITY_TYPE" CHAR(1) NOT NULL ENABLE,
	"QUALIFIER" CHAR(3) NOT NULL ENABLE,
	"PHONE_NUMBER" VARCHAR2(80) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"EXTENSION" VARCHAR2(8),
	"SUPPORTS_SMS" CHAR(1),
	"PPI_MESSAGE_COB_NUM" NUMBER(18,0),
	"COUNTRY_CODE" VARCHAR2(3),
	 CONSTRAINT "FK_PPI_MESSAGE_07" FOREIGN KEY ("PPI_MESSAGE_NUM")
	  REFERENCES "TREXONE_DATA"."PPI_MESSAGE" ("PPI_MESSAGE_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PPI_MESSAGE_PHONE" ON "TREXONE_DATA"."PPI_MESSAGE_PHONE" ("PPI_MESSAGE_PHONE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PPI_MESSAGE_PHONE" ADD CONSTRAINT "PK_PPI_MESSAGE_PHONE" PRIMARY KEY ("PPI_MESSAGE_PHONE_NUM")
  USING INDEX "TREXONE_DATA"."PK_PPI_MESSAGE_PHONE"  ENABLE;
-- ==========================================
