-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRACTICE_SNAPSHOTS"
   (	"SCHEMA_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"STATUS" VARCHAR2(10) NOT NULL ENABLE,
	"TIMESTAMP" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRACTICE_SNAPSHOTS" ON "TREXONE_DATA"."PRACTICE_SNAPSHOTS" ("SCHEMA_NAME")
  ;
ALTER TABLE "TREXONE_DATA"."PRACTICE_SNAPSHOTS" ADD CONSTRAINT "PK_PRACTICE_SNAPSHOTS" PRIMARY KEY ("SCHEMA_NAME")
  USING INDEX "TREXONE_DATA"."PK_PRACTICE_SNAPSHOTS"  ENABLE;
-- ==========================================
