-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRESCRIBER_EXPORT_REQUEST"
   (	"PRESCRIBER_EXPORT_REQUEST_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CREATE_DATE" DATE NOT NULL ENABLE,
	"EXPORT_DATE" DATE,
	"RESPONSE_THRESHOLD_IN_DAYS" NUMBER(10,0),
	"MAX_RESPONSE_DAYS" NUMBER(10,0),
	"SOURCE_CODE" CHAR(1) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRESCRIBER_EXPORT_REQUEST" ON "TREXONE_DATA"."PRESCRIBER_EXPORT_REQUEST" ("PRESCRIBER_EXPORT_REQUEST_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRESCRIBER_EXPORT_REQUEST" ADD CONSTRAINT "PK_PRESCRIBER_EXPORT_REQUEST" PRIMARY KEY ("PRESCRIBER_EXPORT_REQUEST_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRESCRIBER_EXPORT_REQUEST"  ENABLE;
-- ==========================================
