-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRESCRIBER_ADDRESS"
   (	"PRESCRIBER_ADDRESS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACTIVE_PRESCRIBER_ADDRESS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRESCRIBER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRESCRIBER_ID_NUM" NUMBER(18,0),
	"OVERRIDE_ID_NUM" NUMBER(18,0),
	"STATUS" CHAR(1) NOT NULL ENABLE,
	"IS_DEFAULT" CHAR(1),
	"EMAIL_ADDRESS" VARCHAR2(256),
	"WEB_ADDRESS" VARCHAR2(256),
	"PRIMARY_CONTACT_TITLE" VARCHAR2(30),
	"PRIMARY_CONTACT_LAST_NAME" VARCHAR2(30),
	"PRIMARY_CONTACT_MIDDLE_NAME" VARCHAR2(30),
	"PRIMARY_CONTACT_FIRST_NAME" VARCHAR2(30),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PRESCRIBER_LOCATION" VARCHAR2(3),
	"SOURCE_CODE" CHAR(1),
	"PRACTICE_NAME" VARCHAR2(50),
	"DRUG_SCHEDULE" VARCHAR2(30),
	"ADDRESS_TYPE_CODE" VARCHAR2(10),
	"ESV_LAST_UPDATE_DATE" DATE,
	"CONTACT_METHOD_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"IS_340B" CHAR(1),
	"ESV_PRESCRIBER_ID" VARCHAR2(50),
	"ESV_PRESCRIBER_ADDR_LOC_ID" VARCHAR2(10),
	"ESV_PRESCRIBER_ADDR_RANK" NUMBER,
	"REACTIVATE_DATE" DATE,
	"HAS_ESV_PRESCRIBER_ID" CHAR(1) GENERATED ALWAYS AS (DECODE("ESV_PRESCRIBER_ID",NULL,'N','Y')) VIRTUAL  NOT NULL ENABLE,
	"CREATED_BY_CODE" CHAR(1) DEFAULT 'M',
	 CONSTRAINT "FK_CONTACT_METHOD_04" FOREIGN KEY ("CONTACT_METHOD_NUM")
	  REFERENCES "TREXONE_DATA"."CONTACT_METHOD" ("CONTACT_METHOD_NUM") ENABLE,
	 CONSTRAINT "FK_PRESCRIBER_ID_03" FOREIGN KEY ("PRESCRIBER_ID_NUM")
	  REFERENCES "TREXONE_DATA"."PRESCRIBER_ID" ("PRESCRIBER_ID_NUM") DEFERRABLE ENABLE NOVALIDATE,
	 CONSTRAINT "FK_PRESCRIBER_ID_04" FOREIGN KEY ("OVERRIDE_ID_NUM")
	  REFERENCES "TREXONE_DATA"."PRESCRIBER_ID" ("PRESCRIBER_ID_NUM") DEFERRABLE ENABLE NOVALIDATE,
	 CONSTRAINT "FK_PRESCRIBER_ADDRESS_01" FOREIGN KEY ("ACTIVE_PRESCRIBER_ADDRESS_NUM")
	  REFERENCES "TREXONE_DATA"."PRESCRIBER_ADDRESS" ("PRESCRIBER_ADDRESS_NUM") DEFERRABLE ENABLE NOVALIDATE,
	 CONSTRAINT "FK_PRESCRIBER_09" FOREIGN KEY ("PRESCRIBER_NUM")
	  REFERENCES "TREXONE_DATA"."PRESCRIBER" ("PRESCRIBER_NUM") DEFERRABLE ENABLE NOVALIDATE
   ) ;
  CREATE INDEX "TREXONE_DATA"."PK_PRESCRIBER_ADDRESS" ON "TREXONE_DATA"."PRESCRIBER_ADDRESS" ("PRESCRIBER_ADDRESS_NUM", "ACTIVE_PRESCRIBER_ADDRESS_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRESCRIBER_ADDRESS" ADD CONSTRAINT "PK_PRESCRIBER_ADDRESS" PRIMARY KEY ("PRESCRIBER_ADDRESS_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRESCRIBER_ADDRESS"  ENABLE;
-- ==========================================
