-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRESCRIBER_ID"
   (	"PRESCRIBER_ID_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACTIVE_PRESCRIBER_ID_NUM" NUMBER(18,0),
	"PRESCRIBER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CREATE_DATE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ID_TYPE" VARCHAR2(20),
	"ID_TEXT" VARCHAR2(30),
	"ID_SUFFIX" VARCHAR2(20),
	"CTRY_CODE" VARCHAR2(8),
	"STATE_CODE" VARCHAR2(4),
	"STATUS" VARCHAR2(1),
	"EFFECTIVE_DATE" DATE,
	"EXPIRATION_DATE" DATE,
	"SOURCE_CODE" CHAR(1),
	"USE_FOR_BILLING" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"ESV_PRESCRIBER_ID" VARCHAR2(50),
	"ESV_PRESCRIBER_ADDR_LOC_ID" VARCHAR2(10),
	"REACTIVATE_DATE" DATE,
	"HAS_ESV_PRESCRIBER_ID" CHAR(1) GENERATED ALWAYS AS (DECODE("ESV_PRESCRIBER_ID",NULL,'N','Y')) VIRTUAL  NOT NULL ENABLE,
	 CONSTRAINT "FK_PRESCRIBER_ID_05" FOREIGN KEY ("ACTIVE_PRESCRIBER_ID_NUM")
	  REFERENCES "TREXONE_DATA"."PRESCRIBER_ID" ("PRESCRIBER_ID_NUM") DEFERRABLE ENABLE NOVALIDATE,
	 CONSTRAINT "FK_PRESCRIBER_11" FOREIGN KEY ("PRESCRIBER_NUM")
	  REFERENCES "TREXONE_DATA"."PRESCRIBER" ("PRESCRIBER_NUM") DEFERRABLE ENABLE NOVALIDATE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRESCRIBER_ID" ON "TREXONE_DATA"."PRESCRIBER_ID" ("PRESCRIBER_ID_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRESCRIBER_ID" ADD CONSTRAINT "PK_PRESCRIBER_ID" PRIMARY KEY ("PRESCRIBER_ID_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRESCRIBER_ID"  ENABLE;
-- ==========================================
