-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRESCRIBER_PHONE"
   (	"PRESCRIBER_PHONE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRESCRIBER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"STATUS" CHAR(1) NOT NULL ENABLE,
	"PHONE_TYPE" VARCHAR2(4),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"SOURCE_CODE" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"REACTIVATE_DATE" DATE,
	 CONSTRAINT "FK_PRESCRIBER_13" FOREIGN KEY ("PRESCRIBER_NUM")
	  REFERENCES "TREXONE_DATA"."PRESCRIBER" ("PRESCRIBER_NUM") DEFERRABLE ENABLE NOVALIDATE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRESCRIBER_PHONE" ON "TREXONE_DATA"."PRESCRIBER_PHONE" ("PRESCRIBER_PHONE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRESCRIBER_PHONE" ADD CONSTRAINT "PK_PRESCRIBER_PHONE" PRIMARY KEY ("PRESCRIBER_PHONE_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRESCRIBER_PHONE"  ENABLE;
-- ==========================================
