-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRESCRIBER_ACTIVITY_LOG"
   (	"PRESCRIBER_ACTIVITY_LOG_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRESCRIBER_NUM" NUMBER(18,0),
	"MERGED_TO_PRESCRIBER_NUM" NUMBER(18,0),
	"STATUS" CHAR(1) NOT NULL ENABLE,
	"INACTIVITY_CODE" VARCHAR2(4),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"COMMENTS" VARCHAR2(500),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PRESCRIBER_08" FOREIGN KEY ("PRESCRIBER_NUM")
	  REFERENCES "TREXONE_DATA"."PRESCRIBER" ("PRESCRIBER_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRESCRIBER_ACTIVITY_LOG" ON "TREXONE_DATA"."PRESCRIBER_ACTIVITY_LOG" ("PRESCRIBER_ACTIVITY_LOG_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRESCRIBER_ACTIVITY_LOG" ADD CONSTRAINT "PK_PRESCRIBER_ACTIVITY_LOG" PRIMARY KEY ("PRESCRIBER_ACTIVITY_LOG_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRESCRIBER_ACTIVITY_LOG"  ENABLE;
-- ==========================================
