-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRESCRIBER"
   (	"PRESCRIBER_NUM" NUMBER(18,0) NOT NULL DISABLE,
	"ACTIVE_PRESCRIBER_NUM" NUMBER(18,0) NOT NULL DISABLE,
	"STATUS" CHAR(1),
	"INACTIVITY_CODE" VARCHAR2(4),
	"PREF_GENERIC_IF_AVAIL" CHAR(1),
	"PREF_THERAPEUTIC_SUB" CHAR(1),
	"CONTACT_METHOD_NUM" NUMBER(18,0),
	"VALIDATED" CHAR(1),
	"CREATE_DATE" DATE NOT NULL DISABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL DISABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL DISABLE,
	"DATESTAMP" DATE NOT NULL DISABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL DISABLE,
	"SOURCE_CODE" CHAR(1),
	"ON_HOLD" CHAR(1),
	"ESV_MATCHED_IND" CHAR(1),
	"ESV_PRESCRIBER_ID" VARCHAR2(50),
	"SUPV_PRESCRIBER_NUM" NUMBER(18,0),
	"INTERNALLY_VALIDATED" CHAR(1),
	"NEEDS_REFRESHED" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"VALIDATED_BY_USER" NUMBER(18,0),
	"VALIDATED_DATESTAMP" DATE,
	"REACTIVATE_DATE" DATE,
	"HAS_ESV_PRESCRIBER_ID" CHAR(1) GENERATED ALWAYS AS (DECODE("ESV_PRESCRIBER_ID",NULL,'N','Y')) VIRTUAL  NOT NULL ENABLE,
	"CREATED_BY_CODE" CHAR(1) DEFAULT 'M',
	 CONSTRAINT "FK_CONTACT_METHOD_03" FOREIGN KEY ("CONTACT_METHOD_NUM")
	  REFERENCES "TREXONE_DATA"."CONTACT_METHOD" ("CONTACT_METHOD_NUM") ENABLE,
	 CONSTRAINT "FK_PRESCRIBER_21" FOREIGN KEY ("ACTIVE_PRESCRIBER_NUM")
	  REFERENCES "TREXONE_DATA"."PRESCRIBER" ("PRESCRIBER_NUM") DEFERRABLE ENABLE NOVALIDATE,
	 CONSTRAINT "FK_PRESCRIBER_22" FOREIGN KEY ("SUPV_PRESCRIBER_NUM")
	  REFERENCES "TREXONE_DATA"."PRESCRIBER" ("PRESCRIBER_NUM") DEFERRABLE ENABLE NOVALIDATE
   ) ;
  CREATE INDEX "TREXONE_DATA"."PK_PRESCRIBER" ON "TREXONE_DATA"."PRESCRIBER" ("PRESCRIBER_NUM", "ACTIVE_PRESCRIBER_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRESCRIBER" ADD CONSTRAINT "PK_PRESCRIBER" PRIMARY KEY ("PRESCRIBER_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRESCRIBER"  ENABLE;
-- ==========================================
