-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRESCRIBER_ADDRESS_PHONE"
   (	"PRESCRIBER_ADDRESS_PHONE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRESCRIBER_PHONE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRESCRIBER_ADDRESS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PHONE_ADDRESS_TYPE" VARCHAR2(4),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PRESCRIBER_PHONE_02" FOREIGN KEY ("PRESCRIBER_PHONE_NUM")
	  REFERENCES "TREXONE_DATA"."PRESCRIBER_PHONE" ("PRESCRIBER_PHONE_NUM") DEFERRABLE ENABLE NOVALIDATE,
	 CONSTRAINT "FK_PRESCRIBER_ADDRESS_05" FOREIGN KEY ("PRESCRIBER_ADDRESS_NUM")
	  REFERENCES "TREXONE_DATA"."PRESCRIBER_ADDRESS" ("PRESCRIBER_ADDRESS_NUM") DEFERRABLE ENABLE NOVALIDATE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRESCRIBER_ADDRESS_PHONE" ON "TREXONE_DATA"."PRESCRIBER_ADDRESS_PHONE" ("PRESCRIBER_ADDRESS_PHONE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRESCRIBER_ADDRESS_PHONE" ADD CONSTRAINT "PK_PRESCRIBER_ADDRESS_PHONE" PRIMARY KEY ("PRESCRIBER_ADDRESS_PHONE_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRESCRIBER_ADDRESS_PHONE"  ENABLE;
-- ==========================================
