-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRESCRIBER_TP_ELIGIBILITY"
   (	"PRESCRIBER_TP_ELIGIBILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRESCRIBER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRESCRIBER_ID_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_PLAN_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"SOURCE_CODE" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PRESCRIBER_14" FOREIGN KEY ("PRESCRIBER_NUM")
	  REFERENCES "TREXONE_DATA"."PRESCRIBER" ("PRESCRIBER_NUM") ENABLE,
	 CONSTRAINT "FK_PRESCRIBER_ID_06" FOREIGN KEY ("PRESCRIBER_ID_NUM")
	  REFERENCES "TREXONE_DATA"."PRESCRIBER_ID" ("PRESCRIBER_ID_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRESCRIBER_TP_ELIGIBILITY" ON "TREXONE_DATA"."PRESCRIBER_TP_ELIGIBILITY" ("PRESCRIBER_TP_ELIGIBILITY_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRESCRIBER_TP_ELIGIBILITY" ADD CONSTRAINT "PK_PRESCRIBER_TP_ELIGIBILITY" PRIMARY KEY ("PRESCRIBER_TP_ELIGIBILITY_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRESCRIBER_TP_ELIGIBILITY"  ENABLE;
-- ==========================================
