-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRICING_PROCESS_CONFIG"
   (	"PRICING_PROCESS_CONFIG_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRICING_PROCESS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE,
	"TERM_DATE" DATE,
	"PUBLISH_STATUS" CHAR(1),
	"PUBLISH_USER" NUMBER(18,0),
	"PUBLISH_DATE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PRICING_PROCESS_01" FOREIGN KEY ("PRICING_PROCESS_NUM")
	  REFERENCES "TREXONE_DATA"."PRICING_PROCESS" ("PRICING_PROCESS_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRICING_PROCESS_CONFIG" ON "TREXONE_DATA"."PRICING_PROCESS_CONFIG" ("PRICING_PROCESS_CONFIG_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRICING_PROCESS_CONFIG" ADD CONSTRAINT "PK_PRICING_PROCESS_CONFIG" PRIMARY KEY ("PRICING_PROCESS_CONFIG_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRICING_PROCESS_CONFIG"  ENABLE;
-- ==========================================
