-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRICING_FORMULA_CONFIG"
   (	"PRICING_FORMULA_CONFIG_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRICING_FORMULA_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE,
	"TERM_DATE" DATE,
	"USE_PRICE_LINKING" CHAR(1),
	"USE_ALT_COST_DETERMINATION" CHAR(1),
	"PUBLISH_STATUS" CHAR(1),
	"PUBLISH_USER" NUMBER(18,0),
	"PUBLISH_DATE" DATE,
	"COMPOUND_PRICING_OPTION" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PRICING_FORMULA_02" FOREIGN KEY ("PRICING_FORMULA_NUM")
	  REFERENCES "TREXONE_DATA"."PRICING_FORMULA" ("PRICING_FORMULA_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRICING_FORMULA_CONFIG" ON "TREXONE_DATA"."PRICING_FORMULA_CONFIG" ("PRICING_FORMULA_CONFIG_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRICING_FORMULA_CONFIG" ADD CONSTRAINT "PK_PRICING_FORMULA_CONFIG" PRIMARY KEY ("PRICING_FORMULA_CONFIG_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRICING_FORMULA_CONFIG"  ENABLE;
-- ==========================================
