-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRICING_DISCOUNT_TYPE"
   (	"PRICING_DISCOUNT_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(30) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(255),
	"CODE" VARCHAR2(10) NOT NULL ENABLE,
	"PRIORITY" NUMBER(9,0) NOT NULL ENABLE,
	"ADJUST_ON_OVERRIDE" CHAR(1) NOT NULL ENABLE,
	"DISCOUNT_APPLICATION_OPTION" CHAR(1) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."UK_PRICING_DISCOUNT_TYPE_1" ON "TREXONE_DATA"."PRICING_DISCOUNT_TYPE" ("CODE", "ERX_CLIENT_ID")
  ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRICING_DISCOUNT_TYPE" ON "TREXONE_DATA"."PRICING_DISCOUNT_TYPE" ("PRICING_DISCOUNT_TYPE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRICING_DISCOUNT_TYPE" ADD CONSTRAINT "PK_PRICING_DISCOUNT_TYPE" PRIMARY KEY ("PRICING_DISCOUNT_TYPE_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRICING_DISCOUNT_TYPE"  ENABLE;
ALTER TABLE "TREXONE_DATA"."PRICING_DISCOUNT_TYPE" ADD CONSTRAINT "UK_PRICING_DISCOUNT_TYPE_1" UNIQUE ("CODE", "ERX_CLIENT_ID")
  USING INDEX "TREXONE_DATA"."UK_PRICING_DISCOUNT_TYPE_1"  ENABLE;
-- ==========================================
