-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRICING_HOTLIST_ITEM"
   (	"PRICING_HOTLIST_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRICING_HOTLIST_CONFIG_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"QUANTITY" NUMBER(16,8) NOT NULL ENABLE,
	"COST" NUMBER(17,6) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PRICING_HOTLIST_CONFIG_01" FOREIGN KEY ("PRICING_HOTLIST_CONFIG_NUM")
	  REFERENCES "TREXONE_DATA"."PRICING_HOTLIST_CONFIG" ("PRICING_HOTLIST_CONFIG_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRICING_HOTLIST_ITEM" ON "TREXONE_DATA"."PRICING_HOTLIST_ITEM" ("PRICING_HOTLIST_ITEM_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRICING_HOTLIST_ITEM" ADD CONSTRAINT "PK_PRICING_HOTLIST_ITEM" PRIMARY KEY ("PRICING_HOTLIST_ITEM_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRICING_HOTLIST_ITEM"  ENABLE;
-- ==========================================
