-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRICING_TABLE_ROLE"
   (	"PRICING_TABLE_ROLE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRICING_TABLE_NUM" NUMBER(18,0),
	"PRICING_TABLE_NAME" VARCHAR2(30),
	"PRICING_FORMULA_ROLE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PROCESS_ORDER" NUMBER(9,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PRICING_FORMULA_ROLE_01" FOREIGN KEY ("PRICING_FORMULA_ROLE_NUM")
	  REFERENCES "TREXONE_DATA"."PRICING_FORMULA_ROLE" ("PRICING_FORMULA_ROLE_NUM") ENABLE,
	 CONSTRAINT "FK_PRICING_TABLE_03" FOREIGN KEY ("PRICING_TABLE_NUM")
	  REFERENCES "TREXONE_DATA"."PRICING_TABLE" ("PRICING_TABLE_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRICING_TABLE_ROLE" ON "TREXONE_DATA"."PRICING_TABLE_ROLE" ("PRICING_TABLE_ROLE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRICING_TABLE_ROLE" ADD CONSTRAINT "PK_PRICING_TABLE_ROLE" PRIMARY KEY ("PRICING_TABLE_ROLE_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRICING_TABLE_ROLE"  ENABLE;
-- ==========================================
