-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRICING_OVERRIDE_CODE"
   (	"PRICING_OVERRIDE_CODE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(30) NOT NULL ENABLE,
	"CODE" VARCHAR2(10) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(255),
	"RESTRICT_OVERRIDE_AMOUNT" CHAR(1) NOT NULL ENABLE,
	"REQUIRE_ADDITIONAL_DATA" CHAR(1) NOT NULL ENABLE,
	"ADDITIONAL_DATA_TYPE" CHAR(1),
	"ADDITIONAL_DATA_LABEL_TEXT" VARCHAR2(30),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRICING_OVERRIDE_CODE" ON "TREXONE_DATA"."PRICING_OVERRIDE_CODE" ("PRICING_OVERRIDE_CODE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRICING_OVERRIDE_CODE" ADD CONSTRAINT "PK_PRICING_OVERRIDE_CODE" PRIMARY KEY ("PRICING_OVERRIDE_CODE_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRICING_OVERRIDE_CODE"  ENABLE;
-- ==========================================
