-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRICE_LINK_RULE"
   (	"PRICE_LINK_RULE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRICE_LINK_RULE_SET_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"MASTER_PRODUCT_NUM" NUMBER(18,0),
	"PROCESS_ORDER" NUMBER(9,0) NOT NULL ENABLE,
	"EXCLUDE_FROM_LINKING" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATA_FILTER" CLOB,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PRICE_LINK_RULE_SET_01" FOREIGN KEY ("PRICE_LINK_RULE_SET_NUM")
	  REFERENCES "TREXONE_DATA"."PRICE_LINK_RULE_SET" ("PRICE_LINK_RULE_SET_NUM") ENABLE,
	 CONSTRAINT "FK_PRODUCT_10" FOREIGN KEY ("MASTER_PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT" ("PRODUCT_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRICE_LINK_RULE" ON "TREXONE_DATA"."PRICE_LINK_RULE" ("PRICE_LINK_RULE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRICE_LINK_RULE" ADD CONSTRAINT "PK_PRICE_LINK_RULE" PRIMARY KEY ("PRICE_LINK_RULE_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRICE_LINK_RULE"  ENABLE;
-- ==========================================
