-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRIVACY_RESTRICTION"
   (	"PATIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ALLOW_CUSTOM_RPT_FLAG" CHAR(1) DEFAULT 'N' NOT NULL ENABLE,
	"IS_EMANCIPATED_MINOR" CHAR(1) NOT NULL ENABLE,
	"CREATE_USER" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0),
	"PRIVACY_LEVEL" CHAR(1),
	"IS_LETTER_ON_FILE" CHAR(1) DEFAULT 'N',
	"RESTRICT_VACCINATION_REPORTING" CHAR(1) DEFAULT 'N' NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "YES_NO_RULE4" CHECK (allow_custom_rpt_flag IN ('N', 'Y')) ENABLE,
	 CONSTRAINT "YES_NO_RULE3732" CHECK (is_emancipated_minor IN ('N', 'Y')) ENABLE,
	 CONSTRAINT "FK_FACILITY_09" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_PATIENT_03" FOREIGN KEY ("PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRIVACY_RESTRICTION" ON "TREXONE_DATA"."PRIVACY_RESTRICTION" ("PATIENT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRIVACY_RESTRICTION" ADD CONSTRAINT "PK_PRIVACY_RESTRICTION" PRIMARY KEY ("PATIENT_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRIVACY_RESTRICTION"  ENABLE;
-- ==========================================
