-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRODUCT_UPC"
   (	"PRODUCT_UPC_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRODUCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"UPC" NUMBER(12,0) NOT NULL ENABLE,
	"FROM_PROVIDER_LOAD" CHAR(1) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PRODUCT_20" FOREIGN KEY ("PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT" ("PRODUCT_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRODUCT_UPC" ON "TREXONE_DATA"."PRODUCT_UPC" ("PRODUCT_UPC_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRODUCT_UPC" ADD CONSTRAINT "PK_PRODUCT_UPC" PRIMARY KEY ("PRODUCT_UPC_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRODUCT_UPC"  ENABLE;
-- ==========================================
