-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRODUCT_ORDERING_GROUP"
   (	"PRODUCT_ORDERING_GROUP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(50) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PKPRODUCT_ORDERING_GROUP" ON "TREXONE_DATA"."PRODUCT_ORDERING_GROUP" ("PRODUCT_ORDERING_GROUP_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRODUCT_ORDERING_GROUP" ADD CONSTRAINT "PKPRODUCT_ORDERING_GROUP" PRIMARY KEY ("PRODUCT_ORDERING_GROUP_NUM")
  USING INDEX "TREXONE_DATA"."PKPRODUCT_ORDERING_GROUP"  ENABLE;
-- ==========================================
