-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRODUCT_GROUP"
   (	"PRODUCT_GROUP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"GROUP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRODUCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_GROUPS_04" FOREIGN KEY ("GROUP_NUM")
	  REFERENCES "TREXONE_DATA"."GROUPS" ("GROUP_NUM") ENABLE,
	 CONSTRAINT "FK_PRODUCT_14" FOREIGN KEY ("PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT" ("PRODUCT_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRODUCT_GROUP" ON "TREXONE_DATA"."PRODUCT_GROUP" ("PRODUCT_GROUP_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRODUCT_GROUP" ADD CONSTRAINT "PK_PRODUCT_GROUP" PRIMARY KEY ("PRODUCT_GROUP_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRODUCT_GROUP"  ENABLE;
-- ==========================================
