-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRODUCT_IDENTIFIER"
   (	"PRODUCT_IDENTIFIER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRODUCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"SOURCE" VARCHAR2(30),
	"DATE_OF_ADD" DATE,
	"CODE" VARCHAR2(25),
	"IDENTIFIER" VARCHAR2(50),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DATA_GROUP_09" FOREIGN KEY ("DATA_GROUP")
	  REFERENCES "TREXONE_DATA"."DATA_GROUP" ("DATA_GROUP") ENABLE,
	 CONSTRAINT "FK_PRODUCT_15" FOREIGN KEY ("PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT" ("PRODUCT_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRODUCT_IDENTIFIER" ON "TREXONE_DATA"."PRODUCT_IDENTIFIER" ("PRODUCT_IDENTIFIER_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRODUCT_IDENTIFIER" ADD CONSTRAINT "PK_PRODUCT_IDENTIFIER" PRIMARY KEY ("PRODUCT_IDENTIFIER_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRODUCT_IDENTIFIER"  ENABLE;
-- ==========================================
