-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRODUCT_INGREDIENT_CODE"
   (	"PRODUCT_INGREDIENT_CODE_NUM" NUMBER(18,0),
	"PRODUCT_INGREDIENT_NUM" NUMBER(18,0),
	"INGREDIENT_CODE" VARCHAR2(2),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_PRODUCT_INGREDIENT_CODE" PRIMARY KEY ("PRODUCT_INGREDIENT_CODE_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_PRODUCT_INGREDIENT_05" FOREIGN KEY ("PRODUCT_INGREDIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT_INGREDIENT" ("PRODUCT_INGREDIENT_NUM") ENABLE
   ) ;
-- ==========================================
