-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRODUCT_COMPOUND"
   (	"PRODUCT_COMPOUND_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"COMPOUNDING_MINUTES" NUMBER(9,0),
	"IS_FILLED" CHAR(1),
	"PRESCRIPTION_QTY" NUMBER(16,8),
	"DISPENSING_UNIT" VARCHAR2(10),
	"RX_CLARIFICATION_CODE" VARCHAR2(10),
	"DOSAGE_FORM_CODE" VARCHAR2(2),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ROUTE_OF_ADMIN" VARCHAR2(25),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"COMPOUND_TYPE" VARCHAR2(2),
	"ROUTE_OF_ADMINISTRATION" VARCHAR2(11)
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRODUCT_COMPOUND" ON "TREXONE_DATA"."PRODUCT_COMPOUND" ("PRODUCT_COMPOUND_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRODUCT_COMPOUND" ADD CONSTRAINT "PK_PRODUCT_COMPOUND" PRIMARY KEY ("PRODUCT_COMPOUND_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRODUCT_COMPOUND"  ENABLE;
-- ==========================================
