-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRODUCT_INGREDIENT"
   (	"PRODUCT_INGREDIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRODUCT_COMPOUND_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRODUCT_NUM" NUMBER(18,0),
	"QUANTITY" NUMBER(16,8) NOT NULL ENABLE,
	"BILLING_QUANTITY" NUMBER(16,8),
	"COST" NUMBER(17,6),
	"DRUG_FORM_CODE" VARCHAR2(30),
	"PRINT_NUTRITIONAL_INFO" CHAR(1),
	"PRINT_PATIENT_EDU_INFO" CHAR(1),
	"NCPDP_CODE" CHAR(2),
	"FREE_FORM_NAME" VARCHAR2(50),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"RANK" NUMBER(2,0),
	"IS_ACTIVE" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE,
	"IS_AVAILABLE_ON_LABEL" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE,
	 CONSTRAINT "FK_PRODUCT_16" FOREIGN KEY ("PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT" ("PRODUCT_NUM") ENABLE,
	 CONSTRAINT "FK_PRODUCT_COMPOUND_02" FOREIGN KEY ("PRODUCT_COMPOUND_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT_COMPOUND" ("PRODUCT_COMPOUND_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRODUCT_INGREDIENT" ON "TREXONE_DATA"."PRODUCT_INGREDIENT" ("PRODUCT_INGREDIENT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRODUCT_INGREDIENT" ADD CONSTRAINT "PK_PRODUCT_INGREDIENT" PRIMARY KEY ("PRODUCT_INGREDIENT_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRODUCT_INGREDIENT"  ENABLE;
-- ==========================================
