-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PURCHASE_ORDER_ACK"
   (	"PURCHASE_ORDER_ACK_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"VENDOR_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PURCHASE_ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DATE_RECEIVED" DATE,
	"ACKNOWLEDGEMENT_TYPE_CODE" CHAR(2),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"TRANSACTION_SET_CTRL_NUMBER" VARCHAR2(9),
	"INTERCHANGE_CTRL_NUMBER" NUMBER(9,0),
	 CONSTRAINT "FK_PURCHASE_ORDER_02" FOREIGN KEY ("PURCHASE_ORDER_NUM")
	  REFERENCES "TREXONE_DATA"."PURCHASE_ORDER" ("PURCHASE_ORDER_NUM") ENABLE,
	 CONSTRAINT "FK_VENDOR_17" FOREIGN KEY ("VENDOR_NUM")
	  REFERENCES "TREXONE_DATA"."VENDOR" ("VENDOR_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PURCHASE_ORDER_ACK" ON "TREXONE_DATA"."PURCHASE_ORDER_ACK" ("PURCHASE_ORDER_ACK_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PURCHASE_ORDER_ACK" ADD CONSTRAINT "PK_PURCHASE_ORDER_ACK" PRIMARY KEY ("PURCHASE_ORDER_ACK_NUM")
  USING INDEX "TREXONE_DATA"."PK_PURCHASE_ORDER_ACK"  ENABLE;
-- ==========================================
