-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PURCHASING_PLAN_ITEM"
   (	"PURCHASING_PLAN_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PURCHASING_PLAN_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"INVENTORY_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"OVERRIDE_MINIMUM_QTY" NUMBER(12,3),
	"OVERRIDE_MAXIMUM_QTY" NUMBER(12,3),
	"OVERRIDE_MIN_DAYS_SUPPLY" NUMBER(9,0),
	"OVERRIDE_MAX_DAYS_SUPPLY" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_INVENTORY_ITEM_08" FOREIGN KEY ("INVENTORY_ITEM_NUM")
	  REFERENCES "TREXONE_DATA"."INVENTORY_ITEM" ("INVENTORY_ITEM_NUM") ENABLE,
	 CONSTRAINT "FK_PURCHASING_PLAN_02" FOREIGN KEY ("PURCHASING_PLAN_NUM")
	  REFERENCES "TREXONE_DATA"."PURCHASING_PLAN" ("PURCHASING_PLAN_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PURCHASING_PLAN_ITEM" ON "TREXONE_DATA"."PURCHASING_PLAN_ITEM" ("PURCHASING_PLAN_ITEM_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PURCHASING_PLAN_ITEM" ADD CONSTRAINT "PK_PURCHASING_PLAN_ITEM" PRIMARY KEY ("PURCHASING_PLAN_ITEM_NUM")
  USING INDEX "TREXONE_DATA"."PK_PURCHASING_PLAN_ITEM"  ENABLE;
-- ==========================================
