-- ==========================================

  CREATE TABLE "TREXONE_DATA"."QUESTION"
   (	"QUESTION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(30) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"QUESTION_CATEGORY" CHAR(1) NOT NULL ENABLE,
	"ENABLE_RECEPTION" CHAR(1),
	"ENABLE_CONTACT_MANAGER" CHAR(1),
	"ENABLE_RELEASE_TO_PATIENT" CHAR(1),
	"TEXT" VARCHAR2(255) NOT NULL ENABLE,
	"RESPONSE_TYPE" CHAR(1) NOT NULL ENABLE,
	"RESPONSE_EXPIRE_TYPE" CHAR(1) NOT NULL ENABLE,
	"RESPONSE_EXPIRE_DURATION" NUMBER(9,0),
	"RESPONSE_EXPIRE_DATE" DATE,
	"LEGALLY_REQUIRED" CHAR(1) NOT NULL ENABLE,
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE,
	"EXPIRED_DATE" DATE,
	"STATUS" CHAR(1) NOT NULL ENABLE,
	"SECURE" CHAR(1) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DATA_GROUP_12" FOREIGN KEY ("DATA_GROUP")
	  REFERENCES "TREXONE_DATA"."DATA_GROUP" ("DATA_GROUP") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_QUESTION" ON "TREXONE_DATA"."QUESTION" ("QUESTION_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."QUESTION" ADD CONSTRAINT "PK_QUESTION" PRIMARY KEY ("QUESTION_NUM")
  USING INDEX "TREXONE_DATA"."PK_QUESTION"  ENABLE;
-- ==========================================
