-- ==========================================

  CREATE TABLE "TREXONE_DATA"."READJUDICATION_REQUEST_TP"
   (	"READJUDICATION_REQUEST_TP_NUM" NUMBER(18,0),
	"READJUDICATION_REQUEST_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_PATIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"BILLING_ORDER" NUMBER(9,0) NOT NULL ENABLE,
	"STATUS" VARCHAR2(100) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"PARTITION_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	 CONSTRAINT "PK_READJUDICATION_REQUEST_TP" PRIMARY KEY ("READJUDICATION_REQUEST_TP_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_136" FOREIGN KEY ("SYS_USER")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_READJUDICATION_REQUEST_01" FOREIGN KEY ("READJUDICATION_REQUEST_NUM")
	  REFERENCES "TREXONE_DATA"."READJUDICATION_REQUEST" ("READJUDICATION_REQUEST_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_TP_PATIENT_04" FOREIGN KEY ("TP_PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."TP_PATIENT" ("TP_PATIENT_NUM") ENABLE NOVALIDATE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTOYMINTERVAL(3,'MONTH')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
