-- ==========================================

  CREATE TABLE "TREXONE_DATA"."RECOMMENDED_PO_REQUEST"
   (	"RECOMMENDED_PO_REQUEST_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"VENDOR_NUM" NUMBER(18,0),
	"REQUEST_DATESTAMP" DATE NOT NULL ENABLE,
	"PROCESS_DATESTAMP" DATE,
	"REQUEST_ID" VARCHAR2(255),
	"IS_INCLUDE_SCHEDULE_2_PRODUCTS" CHAR(1) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"IS_INCLUDE_NON_SCHEDULE_2_PROD" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"SINGLE_VENDOR_PO_OPTION" CHAR(1),
	 CONSTRAINT "FK_FACILITY_77" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_VENDOR_15" FOREIGN KEY ("VENDOR_NUM")
	  REFERENCES "TREXONE_DATA"."VENDOR" ("VENDOR_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_RECOMMENDED_PO_REQUEST" ON "TREXONE_DATA"."RECOMMENDED_PO_REQUEST" ("RECOMMENDED_PO_REQUEST_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."RECOMMENDED_PO_REQUEST" ADD CONSTRAINT "PK_RECOMMENDED_PO_REQUEST" PRIMARY KEY ("RECOMMENDED_PO_REQUEST_NUM")
  USING INDEX "TREXONE_DATA"."PK_RECOMMENDED_PO_REQUEST"  ENABLE;
-- ==========================================
