-- ==========================================

  CREATE TABLE "TREXONE_DATA"."REPORTING_AUDIT"
   (	"USER_ID" VARCHAR2(255),
	"FACILITY_ID" VARCHAR2(45),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID'),
	"USER_GROUP" VARCHAR2(4000),
	"APPLICATION_ACCESSED" VARCHAR2(50),
	"REQUEST_TYPE" VARCHAR2(20),
	"CREATION_TIMESTAMP" TIMESTAMP (6),
	"STATUS" VARCHAR2(20),
	"ERROR_MESSAGE" VARCHAR2(200)
   ) ;
-- ==========================================
