-- ==========================================

  CREATE TABLE "TREXONE_DATA"."RETAIL_STAGING_BIN_TYPE_DM"
   (	"STAGING_BIN_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DELIVERY_METHOD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DELIVERY_METHOD_03" FOREIGN KEY ("DELIVERY_METHOD_NUM")
	  REFERENCES "TREXONE_DATA"."DELIVERY_METHOD" ("DELIVERY_METHOD_NUM") ENABLE,
	 CONSTRAINT "FK_RETAIL_STAGING_BIN_TYPE_03" FOREIGN KEY ("STAGING_BIN_TYPE_NUM", "FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."RETAIL_STAGING_BIN_TYPE" ("STAGING_BIN_TYPE_NUM", "FACILITY_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_RETAIL_STAGING_BIN_TYPE_DM" ON "TREXONE_DATA"."RETAIL_STAGING_BIN_TYPE_DM" ("STAGING_BIN_TYPE_NUM", "FACILITY_NUM", "DELIVERY_METHOD_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."RETAIL_STAGING_BIN_TYPE_DM" ADD CONSTRAINT "PK_RETAIL_STAGING_BIN_TYPE_DM" PRIMARY KEY ("STAGING_BIN_TYPE_NUM", "FACILITY_NUM", "DELIVERY_METHOD_NUM")
  USING INDEX "TREXONE_DATA"."PK_RETAIL_STAGING_BIN_TYPE_DM"  ENABLE;
-- ==========================================
