-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ROLE_RIGHT"
   (	"ROLE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RIGHT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_RIGHT_01" FOREIGN KEY ("RIGHT_NUM")
	  REFERENCES "TREXONE_DATA"."RIGHT" ("RIGHT_NUM") ENABLE,
	 CONSTRAINT "FK_ROLE_02" FOREIGN KEY ("ROLE_NUM")
	  REFERENCES "TREXONE_DATA"."ROLE" ("ROLE_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_ROLE_RIGHT" ON "TREXONE_DATA"."ROLE_RIGHT" ("ROLE_NUM", "RIGHT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."ROLE_RIGHT" ADD CONSTRAINT "PK_ROLE_RIGHT" PRIMARY KEY ("ROLE_NUM", "RIGHT_NUM")
  USING INDEX "TREXONE_DATA"."PK_ROLE_RIGHT"  ENABLE;
-- ==========================================
