-- ==========================================

  CREATE TABLE "TREXONE_DATA"."RX_ACKNOWLEDGMENT"
   (	"RX_ACKNOWLEDGMENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_FILL_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"COUNSELING_ACCEPTED" CHAR(1) NOT NULL ENABLE,
	"RX_RECEIVED" CHAR(1) NOT NULL ENABLE,
	"IMAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"COUNSELING_COMMENTS" VARCHAR2(100),
	"COUNSELING_NAME" VARCHAR2(100),
	"COUNSELING_INITIALS" VARCHAR2(3),
	 CONSTRAINT "FK_RX_FILL_17" FOREIGN KEY ("RX_FILL_SEQ", "RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_FILL" ("RX_FILL_SEQ", "RX_RECORD_NUM") ENABLE,
	 CONSTRAINT "FK_IMAGE_11" FOREIGN KEY ("IMAGE_NUM")
	  REFERENCES "TREXONE_DATA"."IMAGE" ("IMAGE_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PKRX_ACKNOWLEDGMENT" ON "TREXONE_DATA"."RX_ACKNOWLEDGMENT" ("RX_ACKNOWLEDGMENT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."RX_ACKNOWLEDGMENT" ADD CONSTRAINT "PKRX_ACKNOWLEDGMENT" PRIMARY KEY ("RX_ACKNOWLEDGMENT_NUM")
  USING INDEX "TREXONE_DATA"."PKRX_ACKNOWLEDGMENT"  ENABLE;
-- ==========================================
