-- ==========================================

  CREATE TABLE "TREXONE_DATA"."RX_FILL_NOTE"
   (	"RX_FILL_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"RX_FILL_NOTE_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NOTE_TEXT" VARCHAR2(4000),
	"CREATE_DATE" DATE,
	"PRIORITY_INDICATOR" CHAR(1) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_RX_FILL_13" FOREIGN KEY ("RX_FILL_SEQ", "RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_FILL" ("RX_FILL_SEQ", "RX_RECORD_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_RX_FILL_NOTE" ON "TREXONE_DATA"."RX_FILL_NOTE" ("RX_FILL_SEQ", "RX_FILL_NOTE_SEQ", "RX_RECORD_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."RX_FILL_NOTE" ADD CONSTRAINT "PK_RX_FILL_NOTE" PRIMARY KEY ("RX_FILL_SEQ", "RX_FILL_NOTE_SEQ", "RX_RECORD_NUM")
  USING INDEX "TREXONE_DATA"."PK_RX_FILL_NOTE"  ENABLE;
-- ==========================================
