-- ==========================================

  CREATE TABLE "TREXONE_DATA"."RX_NOTE"
   (	"RX_NOTE_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NOTE_TEXT" VARCHAR2(4000),
	"CREATE_DATE" DATE,
	"PRIORITY_INDICATOR" CHAR(1),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_RX_08" FOREIGN KEY ("RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_BASE" ("RX_RECORD_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_RX_NOTE" ON "TREXONE_DATA"."RX_NOTE" ("RX_NOTE_SEQ", "RX_RECORD_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."RX_NOTE" ADD CONSTRAINT "PK_RX_NOTE" PRIMARY KEY ("RX_NOTE_SEQ", "RX_RECORD_NUM")
  USING INDEX "TREXONE_DATA"."PK_RX_NOTE"  ENABLE;
-- ==========================================
