-- ==========================================

  CREATE TABLE "TREXONE_DATA"."RX_STATUS_DETAIL"
   (	"RX_STATUS_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PREVIOUS_RX_STATUS_NUM" NUMBER(18,0),
	"RX_STATUS_REASON_NUM" NUMBER(18,0),
	"EFFECTIVE_DATE" DATE,
	"COMMENTARY" VARCHAR2(255),
	"CREATE_USER" NUMBER(18,0) NOT NULL ENABLE,
	"CREATE_DATE" DATE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_RX_09" FOREIGN KEY ("RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_BASE" ("RX_RECORD_NUM") ENABLE,
	 CONSTRAINT "FK_RX_STATUS_02" FOREIGN KEY ("PREVIOUS_RX_STATUS_NUM")
	  REFERENCES "TREXONE_DATA"."RX_STATUS" ("RX_STATUS_NUM") ENABLE,
	 CONSTRAINT "FK_RX_STATUS_REASON_01" FOREIGN KEY ("RX_STATUS_REASON_NUM")
	  REFERENCES "TREXONE_DATA"."RX_STATUS_REASON" ("RX_STATUS_REASON_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_RX_STATUS_DETAIL" ON "TREXONE_DATA"."RX_STATUS_DETAIL" ("RX_STATUS_SEQ", "RX_RECORD_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."RX_STATUS_DETAIL" ADD CONSTRAINT "PK_RX_STATUS_DETAIL" PRIMARY KEY ("RX_STATUS_SEQ", "RX_RECORD_NUM")
  USING INDEX "TREXONE_DATA"."PK_RX_STATUS_DETAIL"  ENABLE;
-- ==========================================
