-- ==========================================

  CREATE TABLE "TREXONE_DATA"."RX_TRANSFER_FAILURE"
   (	"RX_TRANSFER_FAILURE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"BATCH_RUN_DATE" DATE NOT NULL ENABLE,
	"PARTNER_CODE" VARCHAR2(30),
	"PATIENT_ID" VARCHAR2(36),
	"NCPDP_ID" VARCHAR2(30),
	"RX_NUMBER" VARCHAR2(20),
	"FAILED_REASON" VARCHAR2(250) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	 CONSTRAINT "PK_RX_TRANSFER_FAILURE" PRIMARY KEY ("RX_TRANSFER_FAILURE_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_110" FOREIGN KEY ("SYS_USER")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE NOVALIDATE
   ) ;
-- ==========================================
