-- ==========================================

  CREATE TABLE "TREXONE_DATA"."RX_TRANSFER"
   (	"RX_TRANSFER_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"COMPETITOR_NUM" NUMBER(18,0),
	"FACILITY_NAME" VARCHAR2(50),
	"FACILITY_ADDRESS1" VARCHAR2(100),
	"FACILITY_ADDRESS2" VARCHAR2(50),
	"FACILITY_CITY" VARCHAR2(40),
	"FACILITY_STATE_CODE" VARCHAR2(2),
	"FACILITY_POSTAL" VARCHAR2(10),
	"FACILITY_CTRY_CODE" VARCHAR2(8),
	"FACILITY_PHONE_EXCHANGE" VARCHAR2(4),
	"FACILITY_AREA_CODE" VARCHAR2(3),
	"FACILITY_PHONE_NUMBER" VARCHAR2(7),
	"FACILITY_PHONE_EXTENSION" VARCHAR2(5),
	"FACILITY_STORE_NUM" CHAR(6),
	"FACILITY_DEA_NUM" VARCHAR2(30),
	"PRESCRIPTION_NUM" VARCHAR2(20),
	"TRANSFER_TYPE" CHAR(1),
	"TRANSFER_DATE" DATE,
	"HARDCOPY_LOCATION" VARCHAR2(50),
	"HARDCOPY_RX_NUM" NUMBER(18,0),
	"COMPETITOR_PRICE" NUMBER(17,6),
	"COMMENTARY" VARCHAR2(255),
	"PRESCRIBED_DATE" DATE,
	"FIRST_FILL_DATE" DATE,
	"LAST_FILL_DATE" DATE,
	"NUM_REFILLS" NUMBER(9,0),
	"REFILLS_REMAINING" NUMBER(9,3),
	"QTY_REMAINING" NUMBER(10,3),
	"SINGLE_FILL_QTY" NUMBER(10,3),
	"WRITTEN_QTY" NUMBER(10,0),
	"REFILLS_ALLOWED" NUMBER(9,0),
	"REFILL_QTY" NUMBER(10,0),
	"DAYS_SUPPLY" NUMBER(10,0),
	"LOCAL_PHARMACIST_NAME" VARCHAR2(45),
	"REMOTE_PHARMACIST_NAME" VARCHAR2(45),
	"RX_NUMBER" VARCHAR2(20),
	"TRANSFER_METHOD" VARCHAR2(12),
	"RECEIVING_PHARMACIST" VARCHAR2(45),
	"SENDING_PHARMACIST" VARCHAR2(45),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ORIG_NUM_FILLS" NUMBER(13,0),
	"ORIG_PHARMACY_NAME" VARCHAR2(50),
	"ORIG_PHARMACY_ADDRESS1" VARCHAR2(100),
	"ORIG_PHARMACY_CITY" VARCHAR2(40),
	"ORIG_PHARMACY_STATE" VARCHAR2(2),
	"ORIG_PHARMACY_POSTAL" VARCHAR2(10),
	"PRESCRIBER_DEA" VARCHAR2(30),
	"ORIG_CREATE_DATE" DATE,
	"SENDING_PHARMACIST_LIC_NUM" VARCHAR2(20),
	"RECEIVING_PHARMACIST_LIC_NUM" VARCHAR2(20),
	"RX_FILL_SEQ" NUMBER(18,0),
	"TRANSFER_REASON" VARCHAR2(50),
	"REASON_NUM" NUMBER(18,0),
	"TRANSFER_TO_RX_RECORD_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"RX_TRANSFER_UNIQUE_ID" NUMBER NOT NULL ENABLE,
	"FACILITY_ID" VARCHAR2(10),
	"COMPETITOR_GROUP_CODE" VARCHAR2(15),
	"COMPETITOR_GROUP_NAME" VARCHAR2(30),
	"STORE_NUMBER" VARCHAR2(10),
	"FACILITY_NUM" NUMBER(18,0),
	"COMMENTS" VARCHAR2(4000),
	 CONSTRAINT "FK_COMPETITOR_01" FOREIGN KEY ("COMPETITOR_NUM")
	  REFERENCES "TREXONE_DATA"."COMPETITOR" ("COMPETITOR_NUM") ENABLE,
	 CONSTRAINT "FK_RX_10" FOREIGN KEY ("RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_BASE" ("RX_RECORD_NUM") ENABLE,
	 CONSTRAINT "FK_RX_BASE_14" FOREIGN KEY ("TRANSFER_TO_RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_BASE" ("RX_RECORD_NUM") ENABLE,
	 CONSTRAINT "FK_RX_FILL_14" FOREIGN KEY ("RX_FILL_SEQ", "RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_FILL" ("RX_FILL_SEQ", "RX_RECORD_NUM") ENABLE,
	 CONSTRAINT "FK_RX_TRNSFR_RSN_TYPE_01" FOREIGN KEY ("REASON_NUM")
	  REFERENCES "TREXONE_DATA"."RX_TRANSFER_REASON_TYPE" ("REASON_NUM") ENABLE,
	 CONSTRAINT "FK_STATE_07" FOREIGN KEY ("FACILITY_CTRY_CODE", "FACILITY_STATE_CODE")
	  REFERENCES "TREXONE_DATA"."STATE" ("CTRY_CODE", "STATE_CODE") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_RX_TRANSFER" ON "TREXONE_DATA"."RX_TRANSFER" ("RX_TRANSFER_SEQ", "RX_RECORD_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."RX_TRANSFER" ADD CONSTRAINT "PK_RX_TRANSFER" PRIMARY KEY ("RX_TRANSFER_SEQ", "RX_RECORD_NUM")
  USING INDEX "TREXONE_DATA"."PK_RX_TRANSFER"  ENABLE;
-- ==========================================
