-- ==========================================

  CREATE TABLE "TREXONE_DATA"."RX_TRANSFER_REASON_TYPE"
   (	"REASON_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"REASON_TYPE" VARCHAR2(3) NOT NULL ENABLE,
	"REASON_DESCRIPTION" VARCHAR2(255) NOT NULL ENABLE,
	"STATUS" CHAR(1) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PKRX_TRANSFER_REASON_TYPE" ON "TREXONE_DATA"."RX_TRANSFER_REASON_TYPE" ("REASON_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."RX_TRANSFER_REASON_TYPE" ADD CONSTRAINT "PKRX_TRANSFER_REASON_TYPE" PRIMARY KEY ("REASON_NUM")
  USING INDEX "TREXONE_DATA"."PKRX_TRANSFER_REASON_TYPE"  ENABLE;
-- ==========================================
