-- ==========================================

  CREATE TABLE "TREXONE_DATA"."SCHEDULE"
   (	"SCHEDULE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SCHEDULE_LINK_NUM" NUMBER(18,0),
	"SCHEDULE_DATE" DATE,
	"DAY_OF_WEEK" NUMBER(2,0),
	"OPEN_TIME" NUMBER(2,0),
	"CLOSE_TIME" NUMBER(2,0),
	"DESCRIPTION" VARCHAR2(255),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_SCHEDULE_LINK_01" FOREIGN KEY ("SCHEDULE_LINK_NUM")
	  REFERENCES "TREXONE_DATA"."SCHEDULE_LINK" ("SCHEDULE_LINK_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_SCHEDULE" ON "TREXONE_DATA"."SCHEDULE" ("SCHEDULE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."SCHEDULE" ADD CONSTRAINT "PK_SCHEDULE" PRIMARY KEY ("SCHEDULE_NUM")
  USING INDEX "TREXONE_DATA"."PK_SCHEDULE"  ENABLE;
-- ==========================================
