-- ==========================================

  CREATE TABLE "TREXONE_DATA"."SCHEDULED_PRESCRIBER"
   (	"SCHEDULED_PRESCRIBER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRESCRIBER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CREATE_DATE" DATE NOT NULL ENABLE,
	"IMPORTED_PRESCRIBER_NUM" NUMBER(18,0),
	"MAX_RESPONSE_DAYS" NUMBER(10,0),
	"RESPONSE_THRESHOLD_IN_DAYS" NUMBER(10,0),
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_IMPORTED_PRESCRIBER_01" FOREIGN KEY ("IMPORTED_PRESCRIBER_NUM")
	  REFERENCES "TREXONE_DATA"."IMPORTED_PRESCRIBER" ("IMPORTED_PRESCRIBER_NUM") ENABLE,
	 CONSTRAINT "FK_PRESCRIBER_19" FOREIGN KEY ("PRESCRIBER_NUM")
	  REFERENCES "TREXONE_DATA"."PRESCRIBER" ("PRESCRIBER_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_SCHEDULED_PRESCRIBER" ON "TREXONE_DATA"."SCHEDULED_PRESCRIBER" ("SCHEDULED_PRESCRIBER_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."SCHEDULED_PRESCRIBER" ADD CONSTRAINT "PK_SCHEDULED_PRESCRIBER" PRIMARY KEY ("SCHEDULED_PRESCRIBER_NUM")
  USING INDEX "TREXONE_DATA"."PK_SCHEDULED_PRESCRIBER"  ENABLE;
-- ==========================================
