-- ==========================================

  CREATE TABLE "TREXONE_DATA"."SIG"
   (	"SIG_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"MACRO" VARCHAR2(15) NOT NULL ENABLE,
	"DAILY_DOSAGE" NUMBER(16,8),
	"QTY_PER_DOSE" NUMBER(16,8),
	"LATIN_FREQUENCY_CODE" VARCHAR2(10),
	"IS_PRN_SIG" CHAR(1) NOT NULL ENABLE,
	"LATIN_FREQUENCY_QTY" NUMBER(9,0),
	"CONVERSION_FACTOR" NUMBER(9,3),
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_LATIN_FREQUENCY_02" FOREIGN KEY ("LATIN_FREQUENCY_CODE")
	  REFERENCES "TREXONE_DATA"."LATIN_FREQUENCY" ("LATIN_FREQUENCY_CODE") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."IU_SIG_1" ON "TREXONE_DATA"."SIG" ("MACRO", "DATA_GROUP", "ERX_CLIENT_ID")
  ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_SIG" ON "TREXONE_DATA"."SIG" ("SIG_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."SIG" ADD CONSTRAINT "PK_SIG" PRIMARY KEY ("SIG_NUM")
  USING INDEX "TREXONE_DATA"."PK_SIG"  ENABLE;
ALTER TABLE "TREXONE_DATA"."SIG" ADD CONSTRAINT "IU_SIG_1" UNIQUE ("MACRO", "DATA_GROUP", "ERX_CLIENT_ID")
  USING INDEX "TREXONE_DATA"."IU_SIG_1"  ENABLE;
-- ==========================================
