-- ==========================================

  CREATE TABLE "TREXONE_DATA"."SIG_TEXT"
   (	"SIG_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"LANGUAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"INSTRUCTIONS" VARCHAR2(1000),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"SEARCH_INSTRUCTIONS" VARCHAR2(4000) GENERATED ALWAYS AS ( REGEXP_REPLACE ("INSTRUCTIONS",'(</*[[:alpha:]]+/*>){1,}','')) VIRTUAL ,
	 CONSTRAINT "FK_LANGUAGE_04" FOREIGN KEY ("LANGUAGE_NUM")
	  REFERENCES "TREXONE_DATA"."LANGUAGE" ("LANGUAGE_NUM") ENABLE,
	 CONSTRAINT "FK_SIG_01" FOREIGN KEY ("SIG_NUM")
	  REFERENCES "TREXONE_DATA"."SIG" ("SIG_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_SIG_TEXT" ON "TREXONE_DATA"."SIG_TEXT" ("SIG_NUM", "LANGUAGE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."SIG_TEXT" ADD CONSTRAINT "PK_SIG_TEXT" PRIMARY KEY ("SIG_NUM", "LANGUAGE_NUM")
  USING INDEX "TREXONE_DATA"."PK_SIG_TEXT"  ENABLE;
-- ==========================================
