-- ==========================================

  CREATE TABLE "TREXONE_DATA"."SIG_ELEMENT_DEFAULT"
   (	"SIG_ELEMENT_DEFAULT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ROUTE" VARCHAR2(30) NOT NULL ENABLE,
	"FORM" VARCHAR2(40) NOT NULL ENABLE,
	"VERB" VARCHAR2(30) NOT NULL ENABLE,
	"UNIT" VARCHAR2(30) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PKSIG_ELEMENT_DEFAULT" ON "TREXONE_DATA"."SIG_ELEMENT_DEFAULT" ("SIG_ELEMENT_DEFAULT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."SIG_ELEMENT_DEFAULT" ADD CONSTRAINT "PKSIG_ELEMENT_DEFAULT" PRIMARY KEY ("SIG_ELEMENT_DEFAULT_NUM")
  USING INDEX "TREXONE_DATA"."PKSIG_ELEMENT_DEFAULT"  ENABLE;
-- ==========================================
