-- ==========================================

  CREATE TABLE "TREXONE_DATA"."SKIP_PREVERIF_REASON"
   (	"SKIP_PREVERIF_REASON_NUM" NUMBER(18,0) DEFAULT "TREXONE_DATA"."SQ_SKIP_PREVERIF_REASON_NUM"."NEXTVAL" NOT NULL ENABLE,
	"ID" NUMBER(2,0) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(1000) NOT NULL ENABLE,
	"SHOULD_SKIP" CHAR(1) DEFAULT 'N' NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_SKIP_PREVERIF_REASON" PRIMARY KEY ("SKIP_PREVERIF_REASON_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
