-- ==========================================

  CREATE TABLE "TREXONE_DATA"."SM_TRANS_REQUEST"
   (	"SM_TRANS_REQUEST_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SM_TRANS_SHIPPER_ID" VARCHAR2(30) NOT NULL ENABLE,
	"SM_TRANS_REQUEST_TYPE" VARCHAR2(20) NOT NULL ENABLE,
	"SM_TRANS_ERX_ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SM_TRANS_DATE_SHIPPED" DATE,
	"SM_TRANS_ESTIMATED_DELIVERY_DT" DATE,
	"SM_TRANS_PACKAGE_WEIGHT" NUMBER(16,8),
	"SM_TRANS_PACKAGE_WEIGHT_UNITS" VARCHAR2(10),
	"SM_TRANS_ACTUAL_SHIPPING_COST" NUMBER(17,6),
	"SM_TRANS_TRACKING_NUMBER" VARCHAR2(200),
	"SM_TRANS_MESSAGE" VARCHAR2(300),
	"SM_TRANS_ACTUAL_COURIER" VARCHAR2(50),
	"SM_TRANS_ACTUAL_COUR_SHIP_METH" VARCHAR2(45),
	"SM_TRANS_ACTUAL_SHIP_ADDRESS1" VARCHAR2(100),
	"SM_TRANS_ACTUAL_SHIP_ADDRESS2" VARCHAR2(50),
	"SM_TRANS_ACTUAL_SHIP_CITY" VARCHAR2(40),
	"SM_TRANS_ACTUAL_SHIP_STATE_CD" VARCHAR2(2),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_SM_TRANS_REQUEST" PRIMARY KEY ("SM_TRANS_REQUEST_NUM")
  USING INDEX  ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
