-- ==========================================

  CREATE TABLE "TREXONE_DATA"."SPECIALTY_PROG_LOT_ITEM_LIST"
   (	"SPECIALTY_PROG_LOT_ITM_LST_NUM" NUMBER(18,0),
	"INVENTORY_LOT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SPECIALTY_PROGRAM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	 CONSTRAINT "PK_SPECIALTY_PROG_LOT_ITM_LST" PRIMARY KEY ("SPECIALTY_PROG_LOT_ITM_LST_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "SPECIALTY_PROG_LOT_ITM_LST_FK1" FOREIGN KEY ("INVENTORY_LOT_NUM")
	  REFERENCES "TREXONE_DATA"."INVENTORY_LOT" ("INVENTORY_LOT_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "SPECIALTY_PROG_LOT_ITM_LST_FK2" FOREIGN KEY ("SPECIALTY_PROGRAM_NUM")
	  REFERENCES "TREXONE_DATA"."SPECIALTY_PROGRAM" ("SPECIALTY_PROGRAM_NUM") ENABLE NOVALIDATE
   ) ;
-- ==========================================
