-- ==========================================

  CREATE TABLE "TREXONE_DATA"."SPECIALTY_ID_PARAM_VALUE"
   (	"SPECIALTY_ID_PARAM_VALUE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SPECIALTY_ID_PARAM_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"VALUE" VARCHAR2(100),
	"RX_FILL_SEQ" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	"PARTITION_DATE" DATE,
	"PARTITION_KEY" NUMBER(18,0),
	"HUB_NAME" VARCHAR2(30),
	 CONSTRAINT "SPECIALTY_ID_PARAM_VALUE_PK" PRIMARY KEY ("SPECIALTY_ID_PARAM_VALUE_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "SPECIALTY_ID_PARAM_VALUE_FK01" FOREIGN KEY ("SPECIALTY_ID_PARAM_TYPE_NUM")
	  REFERENCES "TREXONE_DATA"."SPECIALTY_ID_PARAM_TYPE" ("SPECIALTY_ID_PARAM_TYPE_NUM") ENABLE,
	 CONSTRAINT "SPECIALTY_ID_PARAM_VALUE_FK02" FOREIGN KEY ("RX_FILL_SEQ", "RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_FILL" ("RX_FILL_SEQ", "RX_RECORD_NUM") ENABLE
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTOYMINTERVAL(3,'MONTH')) STORE IN ("LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
