-- ==========================================

  CREATE TABLE "TREXONE_DATA"."SPECIALTY_PROGRAM"
   (	"SPECIALTY_PROGRAM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"START_DATE" DATE,
	"END_DATE" DATE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	"SPECIALTY_PROG_TYPE_NUM" NUMBER(18,0),
	"SPECIALTY_PROG_SUB_TYPE_NUM" NUMBER(18,0),
	"SPECIALTY_PROGRAM_GROUP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CENTRAL_FILL" VARCHAR2(20),
	"PROGRAM_CODE" VARCHAR2(10) NOT NULL ENABLE,
	 CONSTRAINT "SPECIALTY_PROGRAM_PK" PRIMARY KEY ("SPECIALTY_PROGRAM_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "UC_CENTRAL_FILL" UNIQUE ("CENTRAL_FILL")
  USING INDEX  ENABLE,
	 CONSTRAINT "SPECIALTY_PROGRAM_FK01" FOREIGN KEY ("SPECIALTY_PROG_TYPE_NUM")
	  REFERENCES "TREXONE_DATA"."SPECIALTY_PROG_TYPE" ("SPECIALTY_PROG_TYPE_NUM") ENABLE,
	 CONSTRAINT "SPECIALTY_PROGRAM_FK02" FOREIGN KEY ("SPECIALTY_PROG_SUB_TYPE_NUM")
	  REFERENCES "TREXONE_DATA"."SPECIALTY_PROG_SUB_TYPE" ("SPECIALTY_PROG_SUB_TYPE_NUM") ENABLE,
	 CONSTRAINT "SPECIALTY_PROGRAM_FK03" FOREIGN KEY ("SPECIALTY_PROGRAM_GROUP_NUM")
	  REFERENCES "TREXONE_DATA"."SPECIALTY_PROGRAM_GROUP" ("SPECIALTY_PROGRAM_GROUP_NUM") ENABLE
   ) ;
-- ==========================================
