-- ==========================================

  CREATE TABLE "TREXONE_DATA"."SPECIALTY_PROG_PHONE_REF"
   (	"SPECIALTY_PROG_PHONE_REF_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"SPECIALTY_PROGRAM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" VARCHAR2(100) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	 CONSTRAINT "PK_SPECIALTY_PROG_PHONE_REF" PRIMARY KEY ("SPECIALTY_PROG_PHONE_REF_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SPECIALTY_PROGRAM_05" FOREIGN KEY ("SPECIALTY_PROGRAM_NUM")
	  REFERENCES "TREXONE_DATA"."SPECIALTY_PROGRAM" ("SPECIALTY_PROGRAM_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_DATA_GROUP_30" FOREIGN KEY ("DATA_GROUP")
	  REFERENCES "TREXONE_DATA"."DATA_GROUP" ("DATA_GROUP") ENABLE NOVALIDATE
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
