-- ==========================================

  CREATE TABLE "TREXONE_DATA"."SPECIALTY_PROG_TYPE"
   (	"SPECIALTY_PROG_TYPE_NUM" NUMBER(18,0),
	"NAME" VARCHAR2(100),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "SPECIALTY_PROG_TYPE_PK" PRIMARY KEY ("SPECIALTY_PROG_TYPE_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
