-- ==========================================

  CREATE TABLE "TREXONE_DATA"."SPECIALTY_PROG_CONFIG"
   (	"SPECIALTY_PROG_CONFIG_NUM" NUMBER(18,0),
	"SPECIALTY_PROGRAM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"DISPLAY_FOR_SELECTION" CHAR(1),
	"STOP_REFILLS_IN_PV2" CHAR(1),
	"REQUIRE_ELIGIBILITY_START_DATE" CHAR(1),
	"REQUIRE_ELIGIBILITY_END_DATE" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	 CONSTRAINT "PK_SPECIALTY_PROG_CONFIG" PRIMARY KEY ("SPECIALTY_PROG_CONFIG_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SPECIALTY_PROGRAM_10" FOREIGN KEY ("SPECIALTY_PROGRAM_NUM")
	  REFERENCES "TREXONE_DATA"."SPECIALTY_PROGRAM" ("SPECIALTY_PROGRAM_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_DATA_GROUP_35" FOREIGN KEY ("DATA_GROUP")
	  REFERENCES "TREXONE_DATA"."DATA_GROUP" ("DATA_GROUP") ENABLE NOVALIDATE
   ) ;
-- ==========================================
