-- ==========================================

  CREATE TABLE "TREXONE_DATA"."SYSTEM_MESSAGE_DATA_GROUP"
   (	"SYSTEM_MESSAGE_DATA_GROUP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SYSTEM_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DATA_GROUP_17" FOREIGN KEY ("DATA_GROUP")
	  REFERENCES "TREXONE_DATA"."DATA_GROUP" ("DATA_GROUP") ENABLE,
	 CONSTRAINT "FK_SYSTEM_MESSAGE_01" FOREIGN KEY ("SYSTEM_MESSAGE_NUM")
	  REFERENCES "TREXONE_DATA"."SYSTEM_MESSAGE" ("SYSTEM_MESSAGE_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_SYSTEM_MESSAGE_DATA_GROUP" ON "TREXONE_DATA"."SYSTEM_MESSAGE_DATA_GROUP" ("SYSTEM_MESSAGE_DATA_GROUP_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."SYSTEM_MESSAGE_DATA_GROUP" ADD CONSTRAINT "PK_SYSTEM_MESSAGE_DATA_GROUP" PRIMARY KEY ("SYSTEM_MESSAGE_DATA_GROUP_NUM")
  USING INDEX "TREXONE_DATA"."PK_SYSTEM_MESSAGE_DATA_GROUP"  ENABLE;
-- ==========================================
