-- ==========================================

  CREATE TABLE "TREXONE_DATA"."SYSTEM_AUDIT"
   (	"SYSTEM_AUDIT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"USER_FACILITY_NUM" NUMBER(18,0),
	"FOR_FACILITY_NUM" NUMBER(18,0),
	"AUDIT_NAME" VARCHAR2(255) NOT NULL ENABLE,
	"AUDIT_USER" NUMBER(18,0),
	"START_TIME" DATE NOT NULL ENABLE,
	"STOP_TIME" DATE,
	"COMMENT_TEXT" VARCHAR2(255),
	"RX_RECORD_NUM" NUMBER(18,0),
	"RX_FILL_SEQ" NUMBER(18,0),
	"TP_ITEM_CLAIM_NUM" NUMBER(18,0),
	"ADDITIONAL_PROPS" VARCHAR2(255),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"PATIENT_NUM" NUMBER(18,0)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE INDEX "TREXONE_DATA"."PK_SYSTEM_AUDIT" ON "TREXONE_DATA"."SYSTEM_AUDIT" ("SYSTEM_AUDIT_NUM", "RX_FILL_SEQ")
  ;
ALTER TABLE "TREXONE_DATA"."SYSTEM_AUDIT" ADD CONSTRAINT "PK_SYSTEM_AUDIT" PRIMARY KEY ("SYSTEM_AUDIT_NUM")
  USING INDEX "TREXONE_DATA"."PK_SYSTEM_AUDIT"  ENABLE;
-- ==========================================
