-- ==========================================

  CREATE TABLE "TREXONE_DATA"."SYSTEM_USER"
   (	"SYSTEM_USER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"LOGIN_NAME" VARCHAR2(255) NOT NULL ENABLE,
	"FIRST_NAME" VARCHAR2(30),
	"MIDDLE_NAME" VARCHAR2(30),
	"LAST_NAME" VARCHAR2(30),
	"INITIALS" VARCHAR2(3),
	"USER_PASSWORD" VARCHAR2(255),
	"EMPLOYEE_CODE" VARCHAR2(20),
	"IS_PRIVATE" CHAR(1),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DEFAULT_DATA_GROUP" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"DISPLAY_NAME" VARCHAR2(100),
	"USER_DN" VARCHAR2(1000),
	"ROLE_SET" VARCHAR2(4000),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"EXTERNAL_USER_ID" VARCHAR2(30),
	 CONSTRAINT "FK_DATA_GROUP_13" FOREIGN KEY ("DEFAULT_DATA_GROUP")
	  REFERENCES "TREXONE_DATA"."DATA_GROUP" ("DATA_GROUP") ENABLE
   ) ;
  CREATE INDEX "TREXONE_DATA"."IN_SYSTEM_USER_2" ON "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM", "LAST_NAME", "FIRST_NAME", "MIDDLE_NAME")
  ;
ALTER TABLE "TREXONE_DATA"."SYSTEM_USER" ADD CONSTRAINT "PK_SYSTEM_USER" PRIMARY KEY ("SYSTEM_USER_NUM")
  USING INDEX "TREXONE_DATA"."IN_SYSTEM_USER_2"  ENABLE;
-- ==========================================
