-- ==========================================

  CREATE TABLE "TREXONE_DATA"."SYSTEM_USER_NOTE"
   (	"SYSTEM_USER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NOTE_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"NOTE_TEXT" VARCHAR2(4000),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_17" FOREIGN KEY ("SYSTEM_USER_NUM")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_SYSTEM_USER_NOTE" ON "TREXONE_DATA"."SYSTEM_USER_NOTE" ("SYSTEM_USER_NUM", "NOTE_SEQ")
  ;
ALTER TABLE "TREXONE_DATA"."SYSTEM_USER_NOTE" ADD CONSTRAINT "PK_SYSTEM_USER_NOTE" PRIMARY KEY ("SYSTEM_USER_NUM", "NOTE_SEQ")
  USING INDEX "TREXONE_DATA"."PK_SYSTEM_USER_NOTE"  ENABLE;
-- ==========================================
