-- ==========================================

  CREATE TABLE "TREXONE_DATA"."THERAPEUTIC_SUB_GROUP"
   (	"THERAPEUTIC_SUB_GROUP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(20),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(60),
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_THERAPEUTIC_SUB_GROUP" ON "TREXONE_DATA"."THERAPEUTIC_SUB_GROUP" ("THERAPEUTIC_SUB_GROUP_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."THERAPEUTIC_SUB_GROUP" ADD CONSTRAINT "PK_THERAPEUTIC_SUB_GROUP" PRIMARY KEY ("THERAPEUTIC_SUB_GROUP_NUM")
  USING INDEX "TREXONE_DATA"."PK_THERAPEUTIC_SUB_GROUP"  ENABLE;
-- ==========================================
