-- ==========================================

  CREATE TABLE "TREXONE_DATA"."THERAPEUTIC_SUB_GROUP_MEMBER"
   (	"THERAPEUTIC_SUB_GROUP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"THERAPEUTIC_SUB_GROUP_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"PRESCRIBER_GROUP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_PLAN_NUM" NUMBER(18,0),
	"TP_BENEFIT_GROUP_SEQ" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PRESCRIBER_GROUP_01" FOREIGN KEY ("PRESCRIBER_GROUP_NUM")
	  REFERENCES "TREXONE_DATA"."PRESCRIBER_GROUP" ("PRESCRIBER_GROUP_NUM") ENABLE,
	 CONSTRAINT "FK_THERAPEUTIC_SUB_GROUP_02" FOREIGN KEY ("THERAPEUTIC_SUB_GROUP_NUM")
	  REFERENCES "TREXONE_DATA"."THERAPEUTIC_SUB_GROUP" ("THERAPEUTIC_SUB_GROUP_NUM") ENABLE,
	 CONSTRAINT "FK_TP_BENEFIT_GROUP_03" FOREIGN KEY ("TP_PLAN_NUM", "TP_BENEFIT_GROUP_SEQ")
	  REFERENCES "TREXONE_DATA"."TP_BENEFIT_GROUP" ("TP_PLAN_NUM", "TP_BENEFIT_GROUP_SEQ") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_THERAPEUTIC_SUB_GROUP_MEM" ON "TREXONE_DATA"."THERAPEUTIC_SUB_GROUP_MEMBER" ("THERAPEUTIC_SUB_GROUP_NUM", "THERAPEUTIC_SUB_GROUP_SEQ")
  ;
ALTER TABLE "TREXONE_DATA"."THERAPEUTIC_SUB_GROUP_MEMBER" ADD CONSTRAINT "PK_THERAPEUTIC_SUB_GROUP_MEM" PRIMARY KEY ("THERAPEUTIC_SUB_GROUP_NUM", "THERAPEUTIC_SUB_GROUP_SEQ")
  USING INDEX "TREXONE_DATA"."PK_THERAPEUTIC_SUB_GROUP_MEM"  ENABLE;
-- ==========================================
