-- ==========================================

  CREATE TABLE "TREXONE_DATA"."THERAPEUTIC_SUB_CODE"
   (	"THERAPEUTIC_SUB_CODE" CHAR(1) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(100) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_THERAPEUTIC_SUB_CODE" ON "TREXONE_DATA"."THERAPEUTIC_SUB_CODE" ("THERAPEUTIC_SUB_CODE")
  ;
ALTER TABLE "TREXONE_DATA"."THERAPEUTIC_SUB_CODE" ADD CONSTRAINT "PK_THERAPEUTIC_SUB_CODE" PRIMARY KEY ("THERAPEUTIC_SUB_CODE")
  USING INDEX "TREXONE_DATA"."PK_THERAPEUTIC_SUB_CODE"  ENABLE;
-- ==========================================
