-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TOTE"
   (	"TOTE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TOTE_ID" VARCHAR2(7) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"IS_AVAILABLE" CHAR(1) NOT NULL ENABLE,
	"IS_CLOSED" CHAR(1) NOT NULL ENABLE,
	"IS_ACTIVE" CHAR(1) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_FACILITY_71" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TOTE" ON "TREXONE_DATA"."TOTE" ("TOTE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TOTE" ADD CONSTRAINT "PK_TOTE" PRIMARY KEY ("TOTE_NUM")
  USING INDEX "TREXONE_DATA"."PK_TOTE"  ENABLE;
-- ==========================================
