-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_ADJ_RETRY_QUEUE"
   (	"TP_ADJ_RETRY_QUEUE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ITEM_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"RETRY_TIME" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"MAX_RETRY_TIME" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"RETRY_STATUS" CHAR(1) DEFAULT 'U',
	 CONSTRAINT "FK_ITEM_09" FOREIGN KEY ("ORDER_NUM", "ITEM_SEQ")
	  REFERENCES "TREXONE_DATA"."ITEM" ("ORDER_NUM", "ITEM_SEQ") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_ADJ_RETRY_QUEUE" ON "TREXONE_DATA"."TP_ADJ_RETRY_QUEUE" ("TP_ADJ_RETRY_QUEUE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_ADJ_RETRY_QUEUE" ADD CONSTRAINT "PK_TP_ADJ_RETRY_QUEUE" PRIMARY KEY ("TP_ADJ_RETRY_QUEUE_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_ADJ_RETRY_QUEUE"  ENABLE;
-- ==========================================
