-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_ADJ_DRIVER"
   (	"TP_ADJ_DRIVER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DRIVER_CLASS_NAME" VARCHAR2(255) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_ADJ_DRIVER" ON "TREXONE_DATA"."TP_ADJ_DRIVER" ("TP_ADJ_DRIVER_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_ADJ_DRIVER" ADD CONSTRAINT "PK_TP_ADJ_DRIVER" PRIMARY KEY ("TP_ADJ_DRIVER_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_ADJ_DRIVER"  ENABLE;
-- ==========================================
