-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_AGENCY_TYPE"
   (	"TP_AGENCY_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(50) NOT NULL ENABLE,
	"BILLING_PRIORITY" NUMBER(9,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE INDEX "TREXONE_DATA"."PK_TP_AGENCY_TYPE" ON "TREXONE_DATA"."TP_AGENCY_TYPE" ("TP_AGENCY_TYPE_NUM", "BILLING_PRIORITY")
  ;
ALTER TABLE "TREXONE_DATA"."TP_AGENCY_TYPE" ADD CONSTRAINT "PK_TP_AGENCY_TYPE" PRIMARY KEY ("TP_AGENCY_TYPE_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_AGENCY_TYPE"  ENABLE;
-- ==========================================
