-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_BILLING_FORMAT_NOTE"
   (	"TP_BILLING_FORMAT_NOTE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_BILLING_FORMAT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NOTE_TEXT" VARCHAR2(4000) NOT NULL ENABLE,
	"PRIORITY" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_TP_BILLING_FORMAT_01" FOREIGN KEY ("TP_BILLING_FORMAT_NUM")
	  REFERENCES "TREXONE_DATA"."TP_BILLING_FORMAT" ("TP_BILLING_FORMAT_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_BILLING_FORMAT_NOTE" ON "TREXONE_DATA"."TP_BILLING_FORMAT_NOTE" ("TP_BILLING_FORMAT_NOTE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_BILLING_FORMAT_NOTE" ADD CONSTRAINT "PK_TP_BILLING_FORMAT_NOTE" PRIMARY KEY ("TP_BILLING_FORMAT_NOTE_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_BILLING_FORMAT_NOTE"  ENABLE;
-- ==========================================
