-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_BILLING_FORMAT_SET"
   (	"TP_BILLING_FORMAT_SET_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CLAIM_TP_BILLING_FORMAT_NUM" NUMBER(18,0),
	"REV_TP_BILLING_FORMAT_NUM" NUMBER(18,0),
	"ELIG_TP_BILLING_FORMAT_NUM" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"N1_TP_BILLING_FORMAT_NUM" NUMBER(18,0),
	"N2_TP_BILLING_FORMAT_NUM" NUMBER(18,0),
	"S1_TP_BILLING_FORMAT_NUM" NUMBER(18,0),
	"S2_TP_BILLING_FORMAT_NUM" NUMBER(18,0),
	 CONSTRAINT "FK_TP_BILLING_FORMAT_02" FOREIGN KEY ("ELIG_TP_BILLING_FORMAT_NUM")
	  REFERENCES "TREXONE_DATA"."TP_BILLING_FORMAT" ("TP_BILLING_FORMAT_NUM") ENABLE,
	 CONSTRAINT "FK_TP_BILLING_FORMAT_03" FOREIGN KEY ("CLAIM_TP_BILLING_FORMAT_NUM")
	  REFERENCES "TREXONE_DATA"."TP_BILLING_FORMAT" ("TP_BILLING_FORMAT_NUM") ENABLE,
	 CONSTRAINT "FK_TP_BILLING_FORMAT_04" FOREIGN KEY ("REV_TP_BILLING_FORMAT_NUM")
	  REFERENCES "TREXONE_DATA"."TP_BILLING_FORMAT" ("TP_BILLING_FORMAT_NUM") ENABLE,
	 CONSTRAINT "FK_TP_BILLING_FORMAT_13" FOREIGN KEY ("N1_TP_BILLING_FORMAT_NUM")
	  REFERENCES "TREXONE_DATA"."TP_BILLING_FORMAT" ("TP_BILLING_FORMAT_NUM") ENABLE,
	 CONSTRAINT "FK_TP_BILLING_FORMAT_14" FOREIGN KEY ("N2_TP_BILLING_FORMAT_NUM")
	  REFERENCES "TREXONE_DATA"."TP_BILLING_FORMAT" ("TP_BILLING_FORMAT_NUM") ENABLE,
	 CONSTRAINT "FK_TP_BILLING_FORMAT_15" FOREIGN KEY ("S1_TP_BILLING_FORMAT_NUM")
	  REFERENCES "TREXONE_DATA"."TP_BILLING_FORMAT" ("TP_BILLING_FORMAT_NUM") ENABLE,
	 CONSTRAINT "FK_TP_BILLING_FORMAT_16" FOREIGN KEY ("S2_TP_BILLING_FORMAT_NUM")
	  REFERENCES "TREXONE_DATA"."TP_BILLING_FORMAT" ("TP_BILLING_FORMAT_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_BILLING_FORMAT_SET" ON "TREXONE_DATA"."TP_BILLING_FORMAT_SET" ("TP_BILLING_FORMAT_SET_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_BILLING_FORMAT_SET" ADD CONSTRAINT "PK_TP_BILLING_FORMAT_SET" PRIMARY KEY ("TP_BILLING_FORMAT_SET_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_BILLING_FORMAT_SET"  ENABLE;
-- ==========================================
