-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_BILLING_FORMAT_VERSION"
   (	"TP_BILLING_FORMAT_VERSION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_BILLING_FORMAT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE,
	"PUBLISH_STATUS" CHAR(1) NOT NULL ENABLE,
	"ADMIN_TEMPLATE" CLOB,
	"TERMINATION_DATE" DATE,
	"VELOCITY_TEMPLATE_NUM" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_TP_BILLING_FORMAT_05" FOREIGN KEY ("TP_BILLING_FORMAT_NUM")
	  REFERENCES "TREXONE_DATA"."TP_BILLING_FORMAT" ("TP_BILLING_FORMAT_NUM") ENABLE,
	 CONSTRAINT "FK_VELOCITY_TEMPLATE_01" FOREIGN KEY ("VELOCITY_TEMPLATE_NUM")
	  REFERENCES "TREXONE_DATA"."VELOCITY_TEMPLATE" ("VELOCITY_TEMPLATE_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_BILLING_FORMAT_VERSION" ON "TREXONE_DATA"."TP_BILLING_FORMAT_VERSION" ("TP_BILLING_FORMAT_VERSION_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_BILLING_FORMAT_VERSION" ADD CONSTRAINT "PK_TP_BILLING_FORMAT_VERSION" PRIMARY KEY ("TP_BILLING_FORMAT_VERSION_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_BILLING_FORMAT_VERSION"  ENABLE;
-- ==========================================
