-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_BENEFIT_GROUP"
   (	"TP_PLAN_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_BENEFIT_GROUP_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"BENEFIT_GROUP_ID" VARCHAR2(15) NOT NULL ENABLE,
	"BENEFIT_GROUP_NAME" VARCHAR2(45),
	"COMMENT_TEXT" VARCHAR2(255),
	"EFFECTIVE_DATE" DATE,
	"TERMINATION_DATE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ALLOW_CENTRAL_FILL" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE,
	"ALLOW_CENTRAL_MAIL" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_TP_PLAN_03" FOREIGN KEY ("TP_PLAN_NUM")
	  REFERENCES "TREXONE_DATA"."TP_PLAN" ("TP_PLAN_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_BENEFIT_GROUP" ON "TREXONE_DATA"."TP_BENEFIT_GROUP" ("TP_PLAN_NUM", "TP_BENEFIT_GROUP_SEQ")
  ;
ALTER TABLE "TREXONE_DATA"."TP_BENEFIT_GROUP" ADD CONSTRAINT "PK_TP_BENEFIT_GROUP" PRIMARY KEY ("TP_PLAN_NUM", "TP_BENEFIT_GROUP_SEQ")
  USING INDEX "TREXONE_DATA"."PK_TP_BENEFIT_GROUP"  ENABLE;
-- ==========================================
