-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_BILLING_STANDARD"
   (	"TP_BILLING_STANDARD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"STANDARD_TYPE" VARCHAR2(8) NOT NULL ENABLE,
	"VERSION_RELEASE" VARCHAR2(8) NOT NULL ENABLE,
	"TRANSACTION_TYPE" VARCHAR2(2) NOT NULL ENABLE,
	"TEMPLATE" CLOB,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_BILLING_STANDARD" ON "TREXONE_DATA"."TP_BILLING_STANDARD" ("TP_BILLING_STANDARD_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_BILLING_STANDARD" ADD CONSTRAINT "PK_TP_BILLING_STANDARD" PRIMARY KEY ("TP_BILLING_STANDARD_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_BILLING_STANDARD"  ENABLE;
-- ==========================================
