-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_CASH_MESSAGE"
   (	"TP_CASH_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ITEM_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"TP_PROCESSOR_NUM" NUMBER(18,0),
	"TP_PROCESSOR_DESTINATION_SEQ" NUMBER(18,0),
	"TP_ADJ_DRIVER_CONFIG_NUM" NUMBER(18,0),
	"TP_BILLING_FORMAT_NUM" NUMBER(18,0),
	"SUBMISSION_DATE" DATE,
	"SUBMISSION_STATUS" CHAR(1) NOT NULL ENABLE,
	"MESSAGE_CATEGORY" CHAR(1),
	"REQUEST_MESSAGE" CLOB,
	"RESPONSE_MESSAGE" CLOB,
	"COMM_FAILURE" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"FINANCIAL_FEED_NUM" NUMBER(18,0),
	"IS_BAR_TRANSACTION" CHAR(1),
	"TRANSACTION_STATUS" VARCHAR2(50),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"SUBMISSION_TIMESTAMP" TIMESTAMP (6),
	"OUTBOUND_MSG_QUEUE_NUM" NUMBER(18,0),
	 CONSTRAINT "FK_ITEM_10" FOREIGN KEY ("ORDER_NUM", "ITEM_SEQ")
	  REFERENCES "TREXONE_DATA"."ITEM" ("ORDER_NUM", "ITEM_SEQ") ENABLE,
	 CONSTRAINT "FK_TP_ADJ_DRIVER_CONFIG_01" FOREIGN KEY ("TP_ADJ_DRIVER_CONFIG_NUM")
	  REFERENCES "TREXONE_DATA"."TP_ADJ_DRIVER_CONFIG" ("TP_ADJ_DRIVER_CONFIG_NUM") ENABLE,
	 CONSTRAINT "FK_TP_BILLING_FORMAT_06" FOREIGN KEY ("TP_BILLING_FORMAT_NUM")
	  REFERENCES "TREXONE_DATA"."TP_BILLING_FORMAT" ("TP_BILLING_FORMAT_NUM") ENABLE,
	 CONSTRAINT "FK_TP_PROCESSOR_DESTINATION_01" FOREIGN KEY ("TP_PROCESSOR_NUM", "TP_PROCESSOR_DESTINATION_SEQ")
	  REFERENCES "TREXONE_DATA"."TP_PROCESSOR_DESTINATION" ("TP_PROCESSOR_NUM", "TP_PROCESSOR_DESTINATION_SEQ") ENABLE,
	 CONSTRAINT "FK_OB_MSG_QUEUE_02" FOREIGN KEY ("OUTBOUND_MSG_QUEUE_NUM")
	  REFERENCES "TREXONE_DATA"."OUTBOUND_MSG_QUEUE" ("OUTBOUND_MSG_QUEUE_NUM") ENABLE NOVALIDATE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_CASH_MESSAGE" ON "TREXONE_DATA"."TP_CASH_MESSAGE" ("TP_CASH_MESSAGE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_CASH_MESSAGE" ADD CONSTRAINT "PK_TP_CASH_MESSAGE" PRIMARY KEY ("TP_CASH_MESSAGE_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_CASH_MESSAGE"  ENABLE;
-- ==========================================
