-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_DUR_PPS"
   (	"TP_DUR_PPS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_ITEM_CLAIM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DISPLAY_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"REASON_FOR_SERVICE_CODE" VARCHAR2(2),
	"PROFESSIONAL_SERVICE_CODE" VARCHAR2(2),
	"RESULT_OF_SERVICE" VARCHAR2(2),
	"LEVEL_OF_EFFORT" VARCHAR2(2),
	"CO_AGENT_ID_QUALIFIER" VARCHAR2(100),
	"CO_AGENT_ID" VARCHAR2(100),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_TP_DUR_PPS" PRIMARY KEY ("TP_DUR_PPS_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
