-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_DAW_TABLE_DETAIL"
   (	"TP_DAW_TABLE_DETAIL_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_DAW_TABLE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DAW_CODE" CHAR(1) NOT NULL ENABLE,
	"OVERRIDE_DESCRIPTION" VARCHAR2(100),
	"GENERIC_INDICATOR" NUMBER(2,0),
	"GENERIC_PRICE_INDICATOR" NUMBER(2,0),
	"GENERIC_MFG_INDICATOR" NUMBER(2,0),
	"GENERIC_NAMED_DRUG_INDICATOR" NUMBER(2,0),
	"GENERIC_PRICE_SPREAD_INDICATOR" NUMBER(2,0),
	"GENERIC_THERAPEUTIC_INDICATOR" NUMBER(2,0),
	"USER_DEFINED_GENERIC_INDICATOR" NUMBER(2,0),
	"MANDATED_BY_LAW" CHAR(1),
	"IS_AUTO_SELECTABLE" CHAR(1),
	"NEW_RX_MESSAGE" VARCHAR2(255),
	"REFILL_MESSAGE" VARCHAR2(255),
	"HELP_MESSAGE" VARCHAR2(255),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"REFILL_MESSAGE_LEVEL" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"IS_EXCLUDE" CHAR(1) DEFAULT 'N' NOT NULL ENABLE,
	 CONSTRAINT "FK_DAW_CODE_03" FOREIGN KEY ("DAW_CODE")
	  REFERENCES "TREXONE_DATA"."DAW_CODE" ("DAW_CODE") ENABLE,
	 CONSTRAINT "FK_TP_DAW_TABLE_02" FOREIGN KEY ("TP_DAW_TABLE_NUM")
	  REFERENCES "TREXONE_DATA"."TP_DAW_TABLE" ("TP_DAW_TABLE_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."UC_TP_DAW_TABLE_DETAIL_01" ON "TREXONE_DATA"."TP_DAW_TABLE_DETAIL" ("TP_DAW_TABLE_NUM", "DAW_CODE", "ERX_CLIENT_ID")
  ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_DAW_TABLE_DETAIL" ON "TREXONE_DATA"."TP_DAW_TABLE_DETAIL" ("TP_DAW_TABLE_DETAIL_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_DAW_TABLE_DETAIL" ADD CONSTRAINT "PK_TP_DAW_TABLE_DETAIL" PRIMARY KEY ("TP_DAW_TABLE_DETAIL_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_DAW_TABLE_DETAIL"  ENABLE;
ALTER TABLE "TREXONE_DATA"."TP_DAW_TABLE_DETAIL" ADD CONSTRAINT "UC_TP_DAW_TABLE_DETAIL_01" UNIQUE ("TP_DAW_TABLE_NUM", "DAW_CODE", "ERX_CLIENT_ID")
  USING INDEX "TREXONE_DATA"."UC_TP_DAW_TABLE_DETAIL_01"  ENABLE;
-- ==========================================
