-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_DAW_TABLE"
   (	"TP_DAW_TABLE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(30) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_DAW_TABLE" ON "TREXONE_DATA"."TP_DAW_TABLE" ("TP_DAW_TABLE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_DAW_TABLE" ADD CONSTRAINT "PK_TP_DAW_TABLE" PRIMARY KEY ("TP_DAW_TABLE_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_DAW_TABLE"  ENABLE;
-- ==========================================
