-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_DIAGNOSIS_CODE"
   (	"TP_DIAGNOSIS_CODE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRODUCT_NUM" NUMBER(18,0),
	"TP_PLAN_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_NETWORK_NUM" NUMBER(18,0),
	"MEDICAL_CONDITION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"BENEFIT_GROUP_ID" VARCHAR2(15),
	"PLAN_SPECIFIC_DIAGNOSIS_CODE" VARCHAR2(15),
	"PLAN_SPECIFIC_DESCRIPTION" VARCHAR2(80),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_MEDICAL_CONDITION_XREF_03" FOREIGN KEY ("MEDICAL_CONDITION_NUM")
	  REFERENCES "TREXONE_DATA"."MEDICAL_CONDITION_XREF" ("MEDICAL_CONDITION_NUM") ENABLE,
	 CONSTRAINT "FK_PRODUCT_27" FOREIGN KEY ("PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT" ("PRODUCT_NUM") ENABLE,
	 CONSTRAINT "FK_TP_NETWORK_03" FOREIGN KEY ("TP_NETWORK_NUM")
	  REFERENCES "TREXONE_DATA"."TP_NETWORK" ("TP_NETWORK_NUM") ENABLE,
	 CONSTRAINT "FK_TP_PLAN_04" FOREIGN KEY ("TP_PLAN_NUM")
	  REFERENCES "TREXONE_DATA"."TP_PLAN" ("TP_PLAN_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_DIAGNOSIS_CODE" ON "TREXONE_DATA"."TP_DIAGNOSIS_CODE" ("TP_DIAGNOSIS_CODE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_DIAGNOSIS_CODE" ADD CONSTRAINT "PK_TP_DIAGNOSIS_CODE" PRIMARY KEY ("TP_DIAGNOSIS_CODE_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_DIAGNOSIS_CODE"  ENABLE;
-- ==========================================
