-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_DATA_RULE_VALUE"
   (	"TP_DATA_RULE_VALUE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_DATA_RULE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FIELD_VALUE" VARCHAR2(284) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_TP_DATA_RULE_01" FOREIGN KEY ("TP_DATA_RULE_NUM")
	  REFERENCES "TREXONE_DATA"."TP_DATA_RULE" ("TP_DATA_RULE_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_DATA_RULE_VALUE" ON "TREXONE_DATA"."TP_DATA_RULE_VALUE" ("TP_DATA_RULE_VALUE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_DATA_RULE_VALUE" ADD CONSTRAINT "PK_TP_DATA_RULE_VALUE" PRIMARY KEY ("TP_DATA_RULE_VALUE_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_DATA_RULE_VALUE"  ENABLE;
-- ==========================================
