-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_ELIGIBILITY_MESSAGE"
   (	"TP_ELIGIBILITY_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_PROCESSOR_NUM" NUMBER(18,0),
	"TP_PROCESSOR_DESTINATION_SEQ" NUMBER(18,0),
	"TP_ADJ_DRIVER_CONFIG_NUM" NUMBER(18,0),
	"TP_BILLING_FORMAT_NUM" NUMBER(18,0),
	"SUBMISSION_DATE" DATE,
	"SUBMISSION_STATUS" CHAR(1) NOT NULL ENABLE,
	"MESSAGE_CATEGORY" CHAR(1),
	"REQUEST_MESSAGE" CLOB,
	"RESPONSE_MESSAGE" CLOB,
	"COMM_FAILURE" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"TP_PLAN_NUM" NUMBER(18,0),
	"PATIENT_NUM" NUMBER(18,0),
	"CARDHOLDER_ID" VARCHAR2(20),
	"FIRST_NAME" VARCHAR2(30),
	"LAST_NAME" VARCHAR2(30),
	"GENDER" CHAR(1),
	"BIRTH_DATE" DATE,
	"ZIPCODE" VARCHAR2(20),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_TP_ADJ_DRIVER_CONFIG_06" FOREIGN KEY ("TP_ADJ_DRIVER_CONFIG_NUM")
	  REFERENCES "TREXONE_DATA"."TP_ADJ_DRIVER_CONFIG" ("TP_ADJ_DRIVER_CONFIG_NUM") ENABLE,
	 CONSTRAINT "FK_TP_BILLING_FORMAT_12" FOREIGN KEY ("TP_BILLING_FORMAT_NUM")
	  REFERENCES "TREXONE_DATA"."TP_BILLING_FORMAT" ("TP_BILLING_FORMAT_NUM") ENABLE,
	 CONSTRAINT "FK_TP_PLAN_08" FOREIGN KEY ("TP_PLAN_NUM")
	  REFERENCES "TREXONE_DATA"."TP_PLAN" ("TP_PLAN_NUM") ENABLE,
	 CONSTRAINT "FK_TP_PROCESSOR_DESTINATION_05" FOREIGN KEY ("TP_PROCESSOR_NUM", "TP_PROCESSOR_DESTINATION_SEQ")
	  REFERENCES "TREXONE_DATA"."TP_PROCESSOR_DESTINATION" ("TP_PROCESSOR_NUM", "TP_PROCESSOR_DESTINATION_SEQ") ENABLE,
	 CONSTRAINT "FK_PATIENT_30" FOREIGN KEY ("PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_ELIGIBILITY_MESSAGE" ON "TREXONE_DATA"."TP_ELIGIBILITY_MESSAGE" ("TP_ELIGIBILITY_MESSAGE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_ELIGIBILITY_MESSAGE" ADD CONSTRAINT "PK_TP_ELIGIBILITY_MESSAGE" PRIMARY KEY ("TP_ELIGIBILITY_MESSAGE_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_ELIGIBILITY_MESSAGE"  ENABLE;
-- ==========================================
