-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_EOB_CODE"
   (	"TP_EOB_CODE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_RULE_SET_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"EOB_CODE" VARCHAR2(15) NOT NULL ENABLE,
	"CODE_TYPE" NUMBER(9,0),
	"DESCRIPTION" VARCHAR2(255),
	"IS_DOWNTIME_CODE" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"IS_DUPLICATE_CODE" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_TP_RULE_SET_02" FOREIGN KEY ("TP_RULE_SET_NUM")
	  REFERENCES "TREXONE_DATA"."TP_RULE_SET" ("TP_RULE_SET_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_EOB_CODE" ON "TREXONE_DATA"."TP_EOB_CODE" ("TP_EOB_CODE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_EOB_CODE" ADD CONSTRAINT "PK_TP_EOB_CODE" PRIMARY KEY ("TP_EOB_CODE_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_EOB_CODE"  ENABLE;
-- ==========================================
