-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_FORMULARY_DATA_RULE"
   (	"TP_FORMULARY_DATA_RULE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_RULE_SET_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FIELD_ID" NUMBER(9,0) NOT NULL ENABLE,
	"IS_REQUIRED" CHAR(1) NOT NULL ENABLE,
	"IS_ON_ADDITIONAL_INFO_SCREEN" CHAR(1) NOT NULL ENABLE,
	"FORMAT_TYPE" VARCHAR2(18),
	"MASK" VARCHAR2(100),
	"MIN_LENGTH" NUMBER(9,0),
	"MAX_LENGTH" NUMBER(9,0),
	"WARN_LEV" NUMBER(9,0),
	"ALT_LABEL" VARCHAR2(45),
	"ATTRIBUTE_GROUP_NUM" NUMBER(9,0),
	"POSITIVE_VALUE_LIST" CHAR(1),
	"FIELD_HELP_MESSAGE" VARCHAR2(255),
	"PRE_EDIT_MESSAGE" VARCHAR2(2000),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_TP_RULE_SET_09" FOREIGN KEY ("TP_RULE_SET_NUM")
	  REFERENCES "TREXONE_DATA"."TP_RULE_SET" ("TP_RULE_SET_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_FORMULARY_DATA_RULE" ON "TREXONE_DATA"."TP_FORMULARY_DATA_RULE" ("TP_FORMULARY_DATA_RULE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_FORMULARY_DATA_RULE" ADD CONSTRAINT "PK_TP_FORMULARY_DATA_RULE" PRIMARY KEY ("TP_FORMULARY_DATA_RULE_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_FORMULARY_DATA_RULE"  ENABLE;
-- ==========================================
