-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_FAMILY_ACCUMULATORS"
   (	"TP_FAMILY_ACCUMULATORS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_PLAN_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CARDHOLDER_ID" VARCHAR2(20) NOT NULL ENABLE,
	"BENEFIT_GROUP_ID" VARCHAR2(15),
	"FAMILY_PTD_COVERAGE_AMOUNT" NUMBER(17,6),
	"FAMILY_PTD_NUM_RXS" NUMBER(9,0),
	"FAMILY_PTD_DEDUCTIBLE_AMOUNT" NUMBER(17,6),
	"FAMILY_PTD_DEDUCTIBLE_EXP" DATE,
	"FAMILY_PTD_COVERAGE_EXPIRATION" DATE,
	"FAMILY_NUM_RXS_EXPIRATION" DATE,
	"FAMILY_COVERAGE_BASIS_USED" VARCHAR2(30),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_TP_PLAN_09" FOREIGN KEY ("TP_PLAN_NUM")
	  REFERENCES "TREXONE_DATA"."TP_PLAN" ("TP_PLAN_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."UC_TP_FAMILY_ACCUMULATORS_1" ON "TREXONE_DATA"."TP_FAMILY_ACCUMULATORS" ("TP_PLAN_NUM", "CARDHOLDER_ID", "BENEFIT_GROUP_ID", "ERX_CLIENT_ID")
  ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_FAMILY_ACCUMULATORS" ON "TREXONE_DATA"."TP_FAMILY_ACCUMULATORS" ("TP_FAMILY_ACCUMULATORS_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_FAMILY_ACCUMULATORS" ADD CONSTRAINT "PK_TP_FAMILY_ACCUMULATORS" PRIMARY KEY ("TP_FAMILY_ACCUMULATORS_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_FAMILY_ACCUMULATORS"  ENABLE;
ALTER TABLE "TREXONE_DATA"."TP_FAMILY_ACCUMULATORS" ADD CONSTRAINT "UC_TP_FAMILY_ACCUMULATORS_1" UNIQUE ("TP_PLAN_NUM", "CARDHOLDER_ID", "BENEFIT_GROUP_ID", "ERX_CLIENT_ID")
  USING INDEX "TREXONE_DATA"."UC_TP_FAMILY_ACCUMULATORS_1"  ENABLE;
-- ==========================================
