-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_ITEM_OTHER_PAYMENT"
   (	"TP_ITEM_OTHER_PAYMENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_ITEM_OTHER_PAYER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"AMOUNT_PAID_QUALIFIER" VARCHAR2(2),
	"AMOUNT_PAID" NUMBER(17,6),
	"AMOUNT_PAID_SOURCE" VARCHAR2(1),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"AMOUNT_OF_COPAY_COINSURANCE" NUMBER(8,2),
	"REMAINING_BENEFIT_AMOUNT" NUMBER(8,2),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_TP_ITEM_OTHER_PAYER_01" FOREIGN KEY ("TP_ITEM_OTHER_PAYER_NUM")
	  REFERENCES "TREXONE_DATA"."TP_ITEM_OTHER_PAYER" ("TP_ITEM_OTHER_PAYER_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_ITEM_OTHER_PAYMENT" ON "TREXONE_DATA"."TP_ITEM_OTHER_PAYMENT" ("TP_ITEM_OTHER_PAYMENT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_ITEM_OTHER_PAYMENT" ADD CONSTRAINT "PK_TP_ITEM_OTHER_PAYMENT" PRIMARY KEY ("TP_ITEM_OTHER_PAYMENT_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_ITEM_OTHER_PAYMENT"  ENABLE;
-- ==========================================
