-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_ITEM_FIELD"
   (	"TP_ITEM_FIELD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FIELD_NAME" VARCHAR2(50) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_TP_ITEM_FIELD" PRIMARY KEY ("TP_ITEM_FIELD_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
