-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_ITEM_OTHER_PAYER"
   (	"TP_ITEM_OTHER_PAYER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_ITEM_CLAIM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"OTHER_PAYER_COVERAGE_TYPE" VARCHAR2(2),
	"OTHER_PAYER_ID_QUALIFIER" VARCHAR2(2),
	"OTHER_PAYER_ID" VARCHAR2(10),
	"OTHER_PAYER_DATE" DATE,
	"PATIENT_PAY_AMOUNT" NUMBER(17,6),
	"PATIENT_PAY_AMOUNT_SOURCE" VARCHAR2(1),
	"TOTAL_AMOUNT_PAID" NUMBER(17,6),
	"TOTAL_AMOUNT_PAID_SOURCE" VARCHAR2(1),
	"OTHER_PAYER_DATE_SOURCE" VARCHAR2(1),
	"OTHER_PAYER_ID_SOURCE" VARCHAR2(1),
	"COVERAGE_TYPE_SOURCE" VARCHAR2(1),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"BILLING_ORDER" NUMBER(9,0),
	"PERIODIC_DEDUCTIBLE_AMT" NUMBER(17,6),
	"PERIODIC_DEDUCTIBLE_AMT_SOURCE" VARCHAR2(1),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_TP_ITEM_CLAIM_05" FOREIGN KEY ("TP_ITEM_CLAIM_NUM")
	  REFERENCES "TREXONE_DATA"."TP_ITEM_CLAIM" ("TP_ITEM_CLAIM_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_ITEM_OTHER_PAYER" ON "TREXONE_DATA"."TP_ITEM_OTHER_PAYER" ("TP_ITEM_OTHER_PAYER_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_ITEM_OTHER_PAYER" ADD CONSTRAINT "PK_TP_ITEM_OTHER_PAYER" PRIMARY KEY ("TP_ITEM_OTHER_PAYER_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_ITEM_OTHER_PAYER"  ENABLE;
-- ==========================================
