-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_MEDICAID_DRUG"
   (	"TP_MEDICAID_DRUG_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_MEDICAID_LOAD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"STATE_CODE" VARCHAR2(2) NOT NULL ENABLE,
	"NDC_NUMBER" VARCHAR2(11),
	"BILLING_UNITS" VARCHAR2(2),
	"FORMULARY_INDICATOR" VARCHAR2(1),
	"FORMULARY_IND_EFFECTIVE_DATE" DATE,
	"PACKAGE_SIZE_DIVISOR" NUMBER(11,3),
	"QUANTITY_BILL_UNITS" VARCHAR2(10),
	"BILLING_CODE" VARCHAR2(11),
	"BILLING_CODE_EFFECTIVE_DATE" DATE,
	"GENERIC_BILLING_CODE" VARCHAR2(11),
	"GENERIC_BC_EFFECTIVE_DATE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_TP_MEDICAID_LOAD_02" FOREIGN KEY ("TP_MEDICAID_LOAD_NUM")
	  REFERENCES "TREXONE_DATA"."TP_MEDICAID_LOAD" ("TP_MEDICAID_LOAD_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_MEDICAID_DRUG" ON "TREXONE_DATA"."TP_MEDICAID_DRUG" ("TP_MEDICAID_DRUG_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_MEDICAID_DRUG" ADD CONSTRAINT "PK_TP_MEDICAID_DRUG" PRIMARY KEY ("TP_MEDICAID_DRUG_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_MEDICAID_DRUG"  ENABLE;
-- ==========================================
