-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_MEDICAID_LOAD"
   (	"TP_MEDICAID_LOAD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"LOAD_DATE" DATE NOT NULL ENABLE,
	"LOAD_STATUS" VARCHAR2(1) NOT NULL ENABLE,
	"LOAD_STATUS_DATE" DATE NOT NULL ENABLE,
	"UPDATE_TYPE" VARCHAR2(11) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_MEDICAID_LOAD" ON "TREXONE_DATA"."TP_MEDICAID_LOAD" ("TP_MEDICAID_LOAD_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_MEDICAID_LOAD" ADD CONSTRAINT "PK_TP_MEDICAID_LOAD" PRIMARY KEY ("TP_MEDICAID_LOAD_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_MEDICAID_LOAD"  ENABLE;
-- ==========================================
