-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_MESSAGE_PREF_PRODUCT"
   (	"TP_MESSAGE_PREF_PRODUCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PREF_PRODUCT_ID_QUALIFIER" VARCHAR2(2),
	"PREF_PRODUCT_ID" VARCHAR2(19),
	"PREF_PRODUCT_INCENTIVE" NUMBER(17,6),
	"PREF_PRODUCT_COPAY_INCENTIVE" NUMBER(17,6),
	"PREF_PRODUCT_DESCRIPTION" VARCHAR2(40),
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_TP_MESSAGE_03" FOREIGN KEY ("TP_MESSAGE_NUM")
	  REFERENCES "TREXONE_DATA"."TP_MESSAGE" ("TP_MESSAGE_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PKTP_MESSAGE_PREF_PRODUCT" ON "TREXONE_DATA"."TP_MESSAGE_PREF_PRODUCT" ("TP_MESSAGE_PREF_PRODUCT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_MESSAGE_PREF_PRODUCT" ADD CONSTRAINT "PKTP_MESSAGE_PREF_PRODUCT" PRIMARY KEY ("TP_MESSAGE_PREF_PRODUCT_NUM")
  USING INDEX "TREXONE_DATA"."PKTP_MESSAGE_PREF_PRODUCT"  ENABLE;
-- ==========================================
