-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_MESSAGE"
   (	"TP_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_ITEM_CLAIM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_PROCESSOR_DESTINATION_SEQ" NUMBER(18,0),
	"TP_PROCESSOR_NUM" NUMBER(18,0),
	"TP_ADJ_DRIVER_CONFIG_NUM" NUMBER(18,0),
	"TP_BILLING_FORMAT_NUM" NUMBER(18,0),
	"MESSAGE_CATEGORY" CHAR(1),
	"REQUEST_MESSAGE" CLOB,
	"RESPONSE_MESSAGE" CLOB,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"SUBMISSION_DATE" DATE,
	"SUBMISSION_STATUS" VARCHAR2(20),
	"COMM_FAILURE" CHAR(1),
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"TRANSACTION_STATUS" VARCHAR2(50),
	"AUTHORIZATION_NUMBER" VARCHAR2(20),
	"FINANCIAL_FEED_NUM" NUMBER(18,0),
	"HOSTBILL_COMMENTS" VARCHAR2(200),
	"ADJUDICATION_GROUP_NUM" NUMBER(18,0),
	"IS_BAR_TRANSACTION" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"SUBMISSION_TIMESTAMP" TIMESTAMP (6),
	"OUTBOUND_MSG_QUEUE_NUM" NUMBER(18,0),
	"GOVERNMENT_SPONSORED_PLAN" CHAR(1) GENERATED ALWAYS AS (CASE  WHEN "RESPONSE_MESSAGE" IS NULL THEN 'N' ELSE DECODE(INSTR("RESPONSE_MESSAGE",'*G*'),0,DECODE(INSTR("RESPONSE_MESSAGE",'*g*'),0,'N','Y'),'Y') END) VIRTUAL ,
	 CONSTRAINT "FK_TP_ADJ_DRIVER_CONFIG_04" FOREIGN KEY ("TP_ADJ_DRIVER_CONFIG_NUM")
	  REFERENCES "TREXONE_DATA"."TP_ADJ_DRIVER_CONFIG" ("TP_ADJ_DRIVER_CONFIG_NUM") ENABLE,
	 CONSTRAINT "FK_TP_BILLING_FORMAT_09" FOREIGN KEY ("TP_BILLING_FORMAT_NUM")
	  REFERENCES "TREXONE_DATA"."TP_BILLING_FORMAT" ("TP_BILLING_FORMAT_NUM") ENABLE,
	 CONSTRAINT "FK_TP_ITEM_CLAIM_07" FOREIGN KEY ("TP_ITEM_CLAIM_NUM")
	  REFERENCES "TREXONE_DATA"."TP_ITEM_CLAIM" ("TP_ITEM_CLAIM_NUM") ENABLE,
	 CONSTRAINT "FK_TP_PROCESSOR_DESTINATION_03" FOREIGN KEY ("TP_PROCESSOR_NUM", "TP_PROCESSOR_DESTINATION_SEQ")
	  REFERENCES "TREXONE_DATA"."TP_PROCESSOR_DESTINATION" ("TP_PROCESSOR_NUM", "TP_PROCESSOR_DESTINATION_SEQ") ENABLE,
	 CONSTRAINT "FK_OUTBOUND_MSG_QUEUE_02" FOREIGN KEY ("OUTBOUND_MSG_QUEUE_NUM")
	  REFERENCES "TREXONE_DATA"."OUTBOUND_MSG_QUEUE" ("OUTBOUND_MSG_QUEUE_NUM") ENABLE NOVALIDATE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_MESSAGE" ON "TREXONE_DATA"."TP_MESSAGE" ("TP_MESSAGE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_MESSAGE" ADD CONSTRAINT "PK_TP_MESSAGE" PRIMARY KEY ("TP_MESSAGE_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_MESSAGE"  ENABLE;
-- ==========================================
