-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_MEDICAID_CODE_ATTRIBUTE"
   (	"TP_MEDICAID_CODE_ATTRIBUTE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_MEDICAID_LOAD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_MEDICAID_DRUG_ATTRIBUTE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"STATE_CODE" VARCHAR2(2) NOT NULL ENABLE,
	"DP_CODE" VARCHAR2(4) NOT NULL ENABLE,
	"DP_DESCRIPTION" VARCHAR2(50),
	"DP_CODE_TYPE" VARCHAR2(12),
	"DEFAULT_WARN_LEV" NUMBER(9,0),
	"DEFAULT_PRE_EDIT_MESSAGE" VARCHAR2(255),
	"DEFAULT_DATA_FILTER_NAME" VARCHAR2(60),
	"DEFAULT_DATA_FILTER" VARCHAR2(2000),
	"ACTIVE_STATUS" VARCHAR2(1) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_TP_MEDICAID_DRUG_ATTR_02" FOREIGN KEY ("TP_MEDICAID_DRUG_ATTRIBUTE_NUM")
	  REFERENCES "TREXONE_DATA"."TP_MEDICAID_DRUG_ATTRIBUTE" ("TP_MEDICAID_DRUG_ATTRIBUTE_NUM") ENABLE,
	 CONSTRAINT "FK_TP_MEDICAID_LOAD_04" FOREIGN KEY ("TP_MEDICAID_LOAD_NUM")
	  REFERENCES "TREXONE_DATA"."TP_MEDICAID_LOAD" ("TP_MEDICAID_LOAD_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_MEDICAID_CODE_ATTRIBUTE" ON "TREXONE_DATA"."TP_MEDICAID_CODE_ATTRIBUTE" ("TP_MEDICAID_CODE_ATTRIBUTE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_MEDICAID_CODE_ATTRIBUTE" ADD CONSTRAINT "PK_TP_MEDICAID_CODE_ATTRIBUTE" PRIMARY KEY ("TP_MEDICAID_CODE_ATTRIBUTE_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_MEDICAID_CODE_ATTRIBUTE"  ENABLE;
-- ==========================================
