-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_NETWORK_FACILITY"
   (	"TP_NETWORK_FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0),
	"TP_NETWORK_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"EFFECTIVE_DATE" DATE,
	"TERMINATION_DATE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_FACILITY_48" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_TP_NETWORK_04" FOREIGN KEY ("TP_NETWORK_NUM")
	  REFERENCES "TREXONE_DATA"."TP_NETWORK" ("TP_NETWORK_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_NETWORK_FACILITY" ON "TREXONE_DATA"."TP_NETWORK_FACILITY" ("TP_NETWORK_FACILITY_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_NETWORK_FACILITY" ADD CONSTRAINT "PK_TP_NETWORK_FACILITY" PRIMARY KEY ("TP_NETWORK_FACILITY_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_NETWORK_FACILITY"  ENABLE;
-- ==========================================
