-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_OCNA"
   (	"TP_OCNA_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"INSURANCE_NAME" VARCHAR2(80),
	"OCNA_NUMBER" VARCHAR2(80) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_OCNA" ON "TREXONE_DATA"."TP_OCNA" ("TP_OCNA_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_OCNA" ADD CONSTRAINT "PK_TP_OCNA" PRIMARY KEY ("TP_OCNA_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_OCNA"  ENABLE;
-- ==========================================
