-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_PROCESSOR_GROUP"
   (	"TP_PROCESSOR_GROUP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(45),
	"DESCRIPTION" VARCHAR2(255),
	"STATUS" CHAR(1) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_PROCESSOR_GROUP" ON "TREXONE_DATA"."TP_PROCESSOR_GROUP" ("TP_PROCESSOR_GROUP_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_PROCESSOR_GROUP" ADD CONSTRAINT "PK_TP_PROCESSOR_GROUP" PRIMARY KEY ("TP_PROCESSOR_GROUP_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_PROCESSOR_GROUP"  ENABLE;
-- ==========================================
