-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_PLAN_NOTE"
   (	"TP_PLAN_NOTE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_PLAN_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NOTE_TEXT" VARCHAR2(2000) NOT NULL ENABLE,
	"CREATE_DATE" DATE NOT NULL ENABLE,
	"CREATE_USER" NUMBER(18,0) NOT NULL ENABLE,
	"PRIORITY_INDICATOR" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_TP_PLAN_06" FOREIGN KEY ("TP_PLAN_NUM")
	  REFERENCES "TREXONE_DATA"."TP_PLAN" ("TP_PLAN_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_PLAN_NOTE" ON "TREXONE_DATA"."TP_PLAN_NOTE" ("TP_PLAN_NOTE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_PLAN_NOTE" ADD CONSTRAINT "PK_TP_PLAN_NOTE" PRIMARY KEY ("TP_PLAN_NOTE_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_PLAN_NOTE"  ENABLE;
-- ==========================================
