-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_PROCESSOR_DESTINATION"
   (	"TP_PROCESSOR_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_PROCESSOR_DESTINATION_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"TP_ADJ_DRIVER_CONFIG_NUM" NUMBER(18,0),
	"BIN_NUMBER" VARCHAR2(6),
	"PROCESSOR_CONTROL_NUMBER" VARCHAR2(10),
	"PAYMENT_TYPE" CHAR(1),
	"PLAN_ID" VARCHAR2(8),
	"SOFTWARE_CERTIFICATION_ID" VARCHAR2(10),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_TP_ADJ_DRIVER_CONFIG_05" FOREIGN KEY ("TP_ADJ_DRIVER_CONFIG_NUM")
	  REFERENCES "TREXONE_DATA"."TP_ADJ_DRIVER_CONFIG" ("TP_ADJ_DRIVER_CONFIG_NUM") ENABLE,
	 CONSTRAINT "FK_TP_PROCESSOR_01" FOREIGN KEY ("TP_PROCESSOR_NUM")
	  REFERENCES "TREXONE_DATA"."TP_PROCESSOR" ("TP_PROCESSOR_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_PROCESSOR_DESTINATION" ON "TREXONE_DATA"."TP_PROCESSOR_DESTINATION" ("TP_PROCESSOR_NUM", "TP_PROCESSOR_DESTINATION_SEQ")
  ;
ALTER TABLE "TREXONE_DATA"."TP_PROCESSOR_DESTINATION" ADD CONSTRAINT "PK_TP_PROCESSOR_DESTINATION" PRIMARY KEY ("TP_PROCESSOR_NUM", "TP_PROCESSOR_DESTINATION_SEQ")
  USING INDEX "TREXONE_DATA"."PK_TP_PROCESSOR_DESTINATION"  ENABLE;
-- ==========================================
