-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_RULE_SET"
   (	"TP_RULE_SET_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(40),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE INDEX "TREXONE_DATA"."PK_TP_RULE_SET" ON "TREXONE_DATA"."TP_RULE_SET" ("TP_RULE_SET_NUM", "NAME", "NUM_UPDATES")
  ;
ALTER TABLE "TREXONE_DATA"."TP_RULE_SET" ADD CONSTRAINT "PK_TP_RULE_SET" PRIMARY KEY ("TP_RULE_SET_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_RULE_SET"  ENABLE;
-- ==========================================
