-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_RULE_ATTRIBUTE_VALUE"
   (	"TP_RULE_ATTRIBUTE_VALUE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_RULE_SET_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_RULE_ATTRIBUTE_NUM" NUMBER(9,0),
	"ATTRIBUTE_GROUP_NUM" NUMBER(9,0),
	"ATTRIBUTE_SEQUENCE" NUMBER(9,0),
	"VALUE" VARCHAR2(400),
	"WARN_LEV" NUMBER(9,0),
	"EDIT_MESSAGE" VARCHAR2(255),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_TP_RULE_SET_07" FOREIGN KEY ("TP_RULE_SET_NUM")
	  REFERENCES "TREXONE_DATA"."TP_RULE_SET" ("TP_RULE_SET_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_RULE_ATTRIBUTE_VALUE" ON "TREXONE_DATA"."TP_RULE_ATTRIBUTE_VALUE" ("TP_RULE_ATTRIBUTE_VALUE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_RULE_ATTRIBUTE_VALUE" ADD CONSTRAINT "PK_TP_RULE_ATTRIBUTE_VALUE" PRIMARY KEY ("TP_RULE_ATTRIBUTE_VALUE_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_RULE_ATTRIBUTE_VALUE"  ENABLE;
-- ==========================================
