-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_SIM_SCENARIO"
   (	"TP_SIM_SCENARIO_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0),
	"TP_PLAN_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PATIENT_NUM" NUMBER(18,0),
	"PRESCRIBER_NUM" NUMBER(18,0),
	"PRODUCT_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"SCENARIO_NAME" VARCHAR2(60) NOT NULL ENABLE,
	"SCENARIO_STATUS" VARCHAR2(32) NOT NULL ENABLE,
	"USE_PENDING_LINKS" CHAR(1) NOT NULL ENABLE,
	"ACCESS_DATE" DATE NOT NULL ENABLE,
	"SIM_DATE" DATE NOT NULL ENABLE,
	"TX_INFO_PROD" CLOB,
	"TX_INFO_OVERRIDE" CLOB,
	"SOURCE_BILLING_FORMAT" VARCHAR2(20),
	"HELP_DESK_PHONE_NUMBER" VARCHAR2(20),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_TP_PLAN_07" FOREIGN KEY ("TP_PLAN_NUM")
	  REFERENCES "TREXONE_DATA"."TP_PLAN" ("TP_PLAN_NUM") ENABLE,
	 CONSTRAINT "FK_FACILITY_60" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_PRESCRIBER_23" FOREIGN KEY ("PRESCRIBER_NUM")
	  REFERENCES "TREXONE_DATA"."PRESCRIBER" ("PRESCRIBER_NUM") ENABLE,
	 CONSTRAINT "FK_RX_13" FOREIGN KEY ("RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_BASE" ("RX_RECORD_NUM") ENABLE,
	 CONSTRAINT "FK_PRODUCT_30" FOREIGN KEY ("PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT" ("PRODUCT_NUM") ENABLE,
	 CONSTRAINT "FK_PATIENT_27" FOREIGN KEY ("PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_SIM_SCENARIO" ON "TREXONE_DATA"."TP_SIM_SCENARIO" ("TP_SIM_SCENARIO_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_SIM_SCENARIO" ADD CONSTRAINT "PK_TP_SIM_SCENARIO" PRIMARY KEY ("TP_SIM_SCENARIO_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_SIM_SCENARIO"  ENABLE;
-- ==========================================
