-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_SIM_MESSAGE"
   (	"TP_SIM_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_SIM_SCENARIO_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_BILLING_FORMAT_NUM" NUMBER(18,0),
	"REQUEST_MESSAGE" CLOB,
	"RESPONSE_MESSAGE" CLOB,
	"SUBMISSION_DATE" DATE,
	"COMM_FAILURE" CHAR(1),
	"ATTEMPT_NUM" NUMBER(18,0),
	"TRANS_STATUS" VARCHAR2(20),
	"HEADER_STATUS" VARCHAR2(20),
	"TRANS_CODE" VARCHAR2(2),
	"AUTH_NUMBER" VARCHAR2(25),
	"CLAIM_BILLING_FORMAT" VARCHAR2(50),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"RX_FILL_NUMBER" VARCHAR2(2),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_TP_SIM_SCENARIO_01" FOREIGN KEY ("TP_SIM_SCENARIO_NUM")
	  REFERENCES "TREXONE_DATA"."TP_SIM_SCENARIO" ("TP_SIM_SCENARIO_NUM") ENABLE,
	 CONSTRAINT "FK_TP_BILLING_FORMAT_10" FOREIGN KEY ("TP_BILLING_FORMAT_NUM")
	  REFERENCES "TREXONE_DATA"."TP_BILLING_FORMAT" ("TP_BILLING_FORMAT_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_SIM_MESSAGE" ON "TREXONE_DATA"."TP_SIM_MESSAGE" ("TP_SIM_MESSAGE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_SIM_MESSAGE" ADD CONSTRAINT "PK_TP_SIM_MESSAGE" PRIMARY KEY ("TP_SIM_MESSAGE_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_SIM_MESSAGE"  ENABLE;
-- ==========================================
