-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_WORKERS_COMP_LOG"
   (	"TP_WORKERS_COMP_LOG_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_WORKERS_COMP_CLAIM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CONTACT_NAME" VARCHAR2(40),
	"COMMENT_TEXT" VARCHAR2(2000),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_TP_WORKERS_COMP_CLAIM_04" FOREIGN KEY ("TP_WORKERS_COMP_CLAIM_NUM")
	  REFERENCES "TREXONE_DATA"."TP_WORKERS_COMP_CLAIM" ("TP_WORKERS_COMP_CLAIM_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_WORKERS_COMP_LOG" ON "TREXONE_DATA"."TP_WORKERS_COMP_LOG" ("TP_WORKERS_COMP_LOG_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_WORKERS_COMP_LOG" ADD CONSTRAINT "PK_TP_WORKERS_COMP_LOG" PRIMARY KEY ("TP_WORKERS_COMP_LOG_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_WORKERS_COMP_LOG"  ENABLE;
-- ==========================================
