-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_WORKERS_COMP_CLAIM"
   (	"TP_WORKERS_COMP_CLAIM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PATIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACTIVE_STATUS" CHAR(1) NOT NULL ENABLE,
	"CLAIM_REFERENCE_ID" VARCHAR2(30),
	"INJURY_DESCRIPTION" VARCHAR2(60),
	"DATE_OF_INJURY" DATE,
	"CLAIM_TERMINATION_DATE" DATE,
	"CLAIM_AUTHORIZED_BY" VARCHAR2(60),
	"EMPLOYER_NAME" VARCHAR2(30),
	"EMPLOYER_CONTACT_NAME" VARCHAR2(30),
	"EMPLOYER_ID" VARCHAR2(15),
	"EMPLOYER_TAX_ID" VARCHAR2(15),
	"CARRIER_ID" VARCHAR2(10),
	"CARRIER_NAME" VARCHAR2(25),
	"CARRIER_INSURANCE_ID" VARCHAR2(15),
	"CARRIER_CONTACT_NAME" VARCHAR2(30),
	"APPROVAL_NUMBER" VARCHAR2(30),
	"REFILLS_AUTHORIZED" NUMBER(9,0),
	"DIAGNOSIS_CODE_SUBMITTED" VARCHAR2(15),
	"CLAIM_EFFECTIVE_DATE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"JURISDICTION_STATE" VARCHAR2(2),
	"PAYEE_QUALIFIER" VARCHAR2(2),
	"PAYEE_ID" VARCHAR2(15),
	"PAYEE_NAME" VARCHAR2(20),
	"PAYEE_CONTACT_NAME" VARCHAR2(30),
	"CLAIM_TYPE_CODE" VARCHAR2(2),
	 CONSTRAINT "FK_PATIENT_18" FOREIGN KEY ("PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_WORKERS_COMP_CLAIM" ON "TREXONE_DATA"."TP_WORKERS_COMP_CLAIM" ("TP_WORKERS_COMP_CLAIM_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_WORKERS_COMP_CLAIM" ADD CONSTRAINT "PK_TP_WORKERS_COMP_CLAIM" PRIMARY KEY ("TP_WORKERS_COMP_CLAIM_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_WORKERS_COMP_CLAIM"  ENABLE;
-- ==========================================
