-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TREXONE_RELEASE"
   (	"BUILD_NUMBER" VARCHAR2(50) NOT NULL ENABLE,
	"CHANGE_NUMBER" VARCHAR2(100) NOT NULL ENABLE,
	"STATUS" VARCHAR2(25) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE
   ) ;
  CREATE INDEX "TREXONE_DATA"."PK_TREXONE_RELEASE" ON "TREXONE_DATA"."TREXONE_RELEASE" ("CHANGE_NUMBER")
  ;
ALTER TABLE "TREXONE_DATA"."TREXONE_RELEASE" ADD CONSTRAINT "PK_TREXONE_RELEASE" PRIMARY KEY ("CHANGE_NUMBER")
  USING INDEX "TREXONE_DATA"."PK_TREXONE_RELEASE"  ENABLE;
-- ==========================================
