-- ==========================================

  CREATE TABLE "TREXONE_DATA"."UNIT_OF_MEASURE"
   (	"UOM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(30) NOT NULL ENABLE,
	"TO_STANDARD_RATE" NUMBER(16,8),
	"SHORT_NAME" VARCHAR2(8),
	"DESCRIPTION" VARCHAR2(60),
	"DATESTAMP" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_UNIT_OF_MEASURE" ON "TREXONE_DATA"."UNIT_OF_MEASURE" ("UOM_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."UNIT_OF_MEASURE" ADD CONSTRAINT "PK_UNIT_OF_MEASURE" PRIMARY KEY ("UOM_NUM")
  USING INDEX "TREXONE_DATA"."PK_UNIT_OF_MEASURE"  ENABLE;
-- ==========================================
