-- ==========================================

  CREATE TABLE "TREXONE_DATA"."URL"
   (	"URL_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"URL" VARCHAR2(2000) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_URL" ON "TREXONE_DATA"."URL" ("URL_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."URL" ADD CONSTRAINT "PK_URL" PRIMARY KEY ("URL_NUM")
  USING INDEX "TREXONE_DATA"."PK_URL"  ENABLE;
-- ==========================================
