-- ==========================================

  CREATE TABLE "TREXONE_DATA"."USER_QUEUE_PREFERENCES"
   (	"USER_QUEUE_PREFERENCES_NUM" NUMBER(18,0),
	"NAME" NVARCHAR2(60) NOT NULL ENABLE,
	"SYSTEM_USER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"WF_QUEUE_DEFINITION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"SPECIALTY_PROGRAM_NUMS" VARCHAR2(4000),
	"ASSIGNEE_NAME" VARCHAR2(500),
	"ON_HOLD" VARCHAR2(15),
	"THERAPY_TYPE" VARCHAR2(20),
	"PRODUCT_NAME" VARCHAR2(35),
	"STATUS" VARCHAR2(50),
	"IS_REFILL" VARCHAR2(10),
	"INCLUDE_MY_PV_1_RXS" CHAR(1),
	"DELIVERY_METHOD" VARCHAR2(1500),
	"REJECT_CODE" VARCHAR2(4000),
	"PATIENT_GROUP" VARCHAR2(4000),
	"PRESCRIBER_GROUP" VARCHAR2(4000),
	"PRE_EDIT_ERROR" VARCHAR2(1500),
	"TP_NAME" VARCHAR2(4000),
	"PRODUCT_SCHEDULE" VARCHAR2(500),
	"IS_DEFAULT" CHAR(1),
	"PRODUCT_GROUP" VARCHAR2(4000),
	"LOCKED_STATUS" CHAR(1),
	"SOURCE" VARCHAR2(1500),
	"PACKAGING_TYPE_NUMS" VARCHAR2(4000),
	"RX_COUNT" CHAR(1),
	 CONSTRAINT "PK_USER_QUEUE_PREFERENCES" PRIMARY KEY ("USER_QUEUE_PREFERENCES_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_50" FOREIGN KEY ("SYSTEM_USER_NUM")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_FACILITY_120" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_WF_QUEUE_DEFINITION_10" FOREIGN KEY ("WF_QUEUE_DEFINITION_NUM")
	  REFERENCES "TREXONE_DATA"."WF_QUEUE_DEFINITION" ("WF_QUEUE_DEFINITION_NUM") ENABLE NOVALIDATE
   ) ;
-- ==========================================
