-- ==========================================

  CREATE TABLE "TREXONE_DATA"."USER_QUEUE_PREF_NON_WF"
   (	"USER_QUEUE_PREF_NON_WF_NUM" NUMBER(18,0),
	"NAME" NVARCHAR2(60) NOT NULL ENABLE,
	"SYSTEM_USER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"QUEUE_NAME" VARCHAR2(10) NOT NULL ENABLE,
	"ORDER_SOURCE_TYPE_NUM" NUMBER(18,0),
	"FAX_NUMBER" NUMBER(10,0),
	"PRODUCT_NAME" VARCHAR2(100),
	"PRESCRIBER_FIRST_NAME" VARCHAR2(35),
	"PRESCRIBER_LAST_NAME" VARCHAR2(35),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"ERROR_CODES" VARCHAR2(4000),
	 CONSTRAINT "PK_USER_QUEUE_PREF_NON_WF" PRIMARY KEY ("USER_QUEUE_PREF_NON_WF_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "CK_USER_QUEUE_PREF_NON_WF" CHECK (QUEUE_NAME IN('ICQ')) ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_60" FOREIGN KEY ("SYSTEM_USER_NUM")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_FACILITY_125" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_ORDER_SOURCE_TYPE_02" FOREIGN KEY ("ORDER_SOURCE_TYPE_NUM")
	  REFERENCES "TREXONE_DATA"."ORDER_SOURCE_TYPE" ("ORDER_SOURCE_TYPE_NUM") ENABLE NOVALIDATE
   ) ;
-- ==========================================
