-- ==========================================

  CREATE TABLE "TREXONE_DATA"."USER_LICENSE"
   (	"USER_LICENSE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SYSTEM_USER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CTRY_CODE" VARCHAR2(8),
	"STATE_CODE" VARCHAR2(2),
	"LICENSE_NUMBER" VARCHAR2(15) NOT NULL ENABLE,
	"LICENSE_TYPE" CHAR(1) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_STATE_08" FOREIGN KEY ("CTRY_CODE", "STATE_CODE")
	  REFERENCES "TREXONE_DATA"."STATE" ("CTRY_CODE", "STATE_CODE") ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_21" FOREIGN KEY ("SYSTEM_USER_NUM")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_USER_LICENSE" ON "TREXONE_DATA"."USER_LICENSE" ("USER_LICENSE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."USER_LICENSE" ADD CONSTRAINT "PK_USER_LICENSE" PRIMARY KEY ("USER_LICENSE_NUM")
  USING INDEX "TREXONE_DATA"."PK_USER_LICENSE"  ENABLE;
-- ==========================================
