-- ==========================================

  CREATE TABLE "TREXONE_DATA"."VACCINE_DATA_FILTER"
   (	"VACCINE_DATA_FILTER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DATA_FILTER_VALUE" CLOB NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_VACCINE_DATA_FILTER" PRIMARY KEY ("VACCINE_DATA_FILTER_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
