-- ==========================================

  CREATE TABLE "TREXONE_DATA"."VACCINATION_DETAIL"
   (	"VACCINATION_DETAIL_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_FILL_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"REFUSAL" CHAR(1) NOT NULL ENABLE,
	"MISSED_APT" CHAR(1) NOT NULL ENABLE,
	"ADMINISTERING_SITE" VARCHAR2(30),
	"ROUTE_OF_ADMINISTRATION" VARCHAR2(30),
	"DOSE_NUMBER" VARCHAR2(30),
	"SERIES_COMPLETE" VARCHAR2(30),
	"ADMINISTERING_PROVIDER_NAME" VARCHAR2(90),
	"ADMINISTERING_PROVIDER_SUFFIX" VARCHAR2(30),
	"LOCATION_TYPE" VARCHAR2(30),
	"LOCATION_NAME" VARCHAR2(255),
	"LOCATION_ADDRESS_1" VARCHAR2(100),
	"LOCATION_ADDRESS_2" VARCHAR2(50),
	"LOCATION_ZIPCODE" VARCHAR2(20),
	"LOCATION_CITY" VARCHAR2(40),
	"LOCATION_STATE" VARCHAR2(2),
	"LOCATION_COUNTY_CODE" VARCHAR2(5),
	"LOCATION_PHONE" VARCHAR2(10),
	"VTRCKS_PROVIDER_PIN" VARCHAR2(30),
	"COMORBIDITY_STATUS" VARCHAR2(30),
	"SEROLOGY_RESULTS" VARCHAR2(30),
	"ARE_FIELDS_REQUIRED" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	"CONSENT_TO_REPORT" CHAR(1),
	"GUARDIAN_L_NAME" VARCHAR2(50),
	"GUARDIAN_F_NAME" VARCHAR2(30),
	"GUARDIAN_RELATION" VARCHAR2(50),
	"LOT_NUMBER" VARCHAR2(20),
	"EXPIRATION_DATE" DATE,
	"PROVIDER_L_NAME" VARCHAR2(50),
	"PROVIDER_F_NAME" VARCHAR2(30),
	"PROVIDER_ID" VARCHAR2(15),
	"FUNDING_SOURCE" VARCHAR2(30),
	"VFC_STATUS" VARCHAR2(20),
	"TARGET_POPULATION" VARCHAR2(30),
	"ADMINISTRATION_DATE" DATE,
	"LOCATION_ID" VARCHAR2(80),
	 CONSTRAINT "VACCINATION_DETAIL_PK" PRIMARY KEY ("VACCINATION_DETAIL_NUM")
  USING INDEX (CREATE UNIQUE INDEX "TREXONE_DATA"."VACCINATION_DETAIL_IDX01" ON "TREXONE_DATA"."VACCINATION_DETAIL" ("VACCINATION_DETAIL_NUM")
  )  ENABLE,
	 CONSTRAINT "VACCINATION_DETAIL_FK01" FOREIGN KEY ("ORDER_NUM")
	  REFERENCES "TREXONE_DATA"."ORDER_RECORD_BASE" ("ORDER_NUM") ENABLE,
	 CONSTRAINT "VACCINATION_DETAIL_FK02" FOREIGN KEY ("RX_FILL_SEQ", "RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_FILL" ("RX_FILL_SEQ", "RX_RECORD_NUM") ENABLE,
	 CONSTRAINT "VACCINATION_DETAIL_FK03" FOREIGN KEY ("RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_BASE" ("RX_RECORD_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTOYMINTERVAL(3,'MONTH'))
 (PARTITION "P_20160101"  VALUES LESS THAN (TO_DATE(' 2016-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
