-- ==========================================

  CREATE TABLE "TREXONE_DATA"."VENDOR_COST_BASIS"
   (	"VENDOR_COST_BASIS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"VENDOR_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"COST_BASIS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"COST_BASIS_SOURCE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"IS_ACQUISITION_COST" CHAR(1) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_COST_BASIS_04" FOREIGN KEY ("COST_BASIS_NUM")
	  REFERENCES "TREXONE_DATA"."COST_BASIS" ("COST_BASIS_NUM") ENABLE,
	 CONSTRAINT "FK_COST_BASIS_SOURCE_03" FOREIGN KEY ("COST_BASIS_SOURCE_NUM")
	  REFERENCES "TREXONE_DATA"."COST_BASIS_SOURCE" ("COST_BASIS_SOURCE_NUM") ENABLE,
	 CONSTRAINT "FK_VENDOR_13" FOREIGN KEY ("VENDOR_NUM")
	  REFERENCES "TREXONE_DATA"."VENDOR" ("VENDOR_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_VENDOR_COST_BASIS" ON "TREXONE_DATA"."VENDOR_COST_BASIS" ("VENDOR_COST_BASIS_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."VENDOR_COST_BASIS" ADD CONSTRAINT "PK_VENDOR_COST_BASIS" PRIMARY KEY ("VENDOR_COST_BASIS_NUM")
  USING INDEX "TREXONE_DATA"."PK_VENDOR_COST_BASIS"  ENABLE;
-- ==========================================
