-- ==========================================

  CREATE TABLE "TREXONE_DATA"."VENDOR_COMMUNICATION_METHOD"
   (	"VENDOR_COMM_METHOD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(30) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PKVENDOR_COMMUNICATION_METHOD" ON "TREXONE_DATA"."VENDOR_COMMUNICATION_METHOD" ("VENDOR_COMM_METHOD_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."VENDOR_COMMUNICATION_METHOD" ADD CONSTRAINT "PKVENDOR_COMMUNICATION_METHOD" PRIMARY KEY ("VENDOR_COMM_METHOD_NUM")
  USING INDEX "TREXONE_DATA"."PKVENDOR_COMMUNICATION_METHOD"  ENABLE;
-- ==========================================
