-- ==========================================

  CREATE TABLE "TREXONE_DATA"."VENDOR_X12_INTERFACE"
   (	"VENDOR_X12_INTERFACE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"EIF_PEER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"VENDOR_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"X12_INTERFACE_VERSION" VARCHAR2(30),
	"SEGMENT_DELIMITER" CHAR(1),
	"DATA_DELIMITER" CHAR(1),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_EIF_PEER_3" FOREIGN KEY ("EIF_PEER_NUM")
	  REFERENCES "TREXONE_DATA"."EIF_PEER" ("EIF_PEER_NUM") ENABLE,
	 CONSTRAINT "FK_VENDOR_18" FOREIGN KEY ("VENDOR_NUM")
	  REFERENCES "TREXONE_DATA"."VENDOR" ("VENDOR_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_VENDOR_X12_INTERFACE" ON "TREXONE_DATA"."VENDOR_X12_INTERFACE" ("VENDOR_X12_INTERFACE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."VENDOR_X12_INTERFACE" ADD CONSTRAINT "PK_VENDOR_X12_INTERFACE" PRIMARY KEY ("VENDOR_X12_INTERFACE_NUM")
  USING INDEX "TREXONE_DATA"."PK_VENDOR_X12_INTERFACE"  ENABLE;
-- ==========================================
