-- ==========================================

  CREATE TABLE "TREXONE_DATA"."VENDOR_INVENTORY_CONTACT"
   (	"VENDOR_INVENTORY_CONTACT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"VENDOR_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(80) NOT NULL ENABLE,
	"EMAIL" VARCHAR2(255),
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_VENDOR_05" FOREIGN KEY ("VENDOR_NUM")
	  REFERENCES "TREXONE_DATA"."VENDOR" ("VENDOR_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_VENDOR_INVENTORY_CONTACT" ON "TREXONE_DATA"."VENDOR_INVENTORY_CONTACT" ("VENDOR_INVENTORY_CONTACT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."VENDOR_INVENTORY_CONTACT" ADD CONSTRAINT "PK_VENDOR_INVENTORY_CONTACT" PRIMARY KEY ("VENDOR_INVENTORY_CONTACT_NUM")
  USING INDEX "TREXONE_DATA"."PK_VENDOR_INVENTORY_CONTACT"  ENABLE;
-- ==========================================
