-- ==========================================

  CREATE TABLE "TREXONE_DATA"."VENDOR_OVERRIDE"
   (	"PURCHASING_PLAN_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"VENDOR_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"MINIMUM_QTY" NUMBER(12,3),
	"MAXIMUM_QTY" NUMBER(12,3),
	"MIN_DAYS_SUPPLY" NUMBER(9,0),
	"MAX_DAYS_SUPPLY" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PURCHASING_PLAN_ITEM_02" FOREIGN KEY ("PURCHASING_PLAN_ITEM_NUM")
	  REFERENCES "TREXONE_DATA"."PURCHASING_PLAN_ITEM" ("PURCHASING_PLAN_ITEM_NUM") ENABLE,
	 CONSTRAINT "FK_VENDOR_19" FOREIGN KEY ("VENDOR_NUM")
	  REFERENCES "TREXONE_DATA"."VENDOR" ("VENDOR_NUM") ENABLE
   ) ;
  CREATE INDEX "TREXONE_DATA"."PK_VENDOR_OVERRIDE" ON "TREXONE_DATA"."VENDOR_OVERRIDE" ("PURCHASING_PLAN_ITEM_NUM", "VENDOR_NUM", "DATESTAMP")
  ;
ALTER TABLE "TREXONE_DATA"."VENDOR_OVERRIDE" ADD CONSTRAINT "PK_VENDOR_OVERRIDE" PRIMARY KEY ("PURCHASING_PLAN_ITEM_NUM", "VENDOR_NUM")
  USING INDEX "TREXONE_DATA"."PK_VENDOR_OVERRIDE"  ENABLE;
-- ==========================================
