-- ==========================================

  CREATE TABLE "TREXONE_DATA"."VENDOR_PRICE_CATALOG"
   (	"VENDOR_PRICE_CATALOG_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"QUEUE_STATUS" CHAR(1) NOT NULL ENABLE,
	"VENDOR_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"VENDOR_PRODUCT_ID" VARCHAR2(48),
	"NDC_NUMBER" VARCHAR2(11),
	"COST_BASIS_NUM" NUMBER(18,0),
	"COST_BASIS_NAME" VARCHAR2(30),
	"COST_BASIS_SOURCE_NUM" NUMBER(18,0),
	"COST" NUMBER(17,6),
	"PACKAGE_SIZE" NUMBER(16,8),
	"PURCHASE_INCREMENT" NUMBER(9,0),
	"IS_ACQ" CHAR(1),
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"ONESTOP_SLOT_INDICATOR" VARCHAR2(10),
	"IS_GENERICS_PROGRAM" CHAR(1),
	 CONSTRAINT "PK_VENDOR_PRICE_CATALOG" PRIMARY KEY ("VENDOR_PRICE_CATALOG_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
