-- ==========================================

  CREATE TABLE "TREXONE_DATA"."VENDOR_CONFIGURATION"
   (	"VENDOR_CONFIGURATION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACCOUNT_NUMBER" VARCHAR2(16),
	"SENDER_ID" VARCHAR2(16),
	"RECEIVER_ID" VARCHAR2(16),
	"PURCHASE_ORDER_SORT_CODE" CHAR(1),
	"LEAD_TIME" NUMBER(9,0),
	"AUTO_TRANSMIT_PO_FLAG" CHAR(1),
	"DELIVERS_ON_SUNDAY" CHAR(1),
	"DELIVERS_ON_MONDAY" CHAR(1),
	"DELIVERS_ON_TUESDAY" CHAR(1),
	"DELIVERS_ON_WEDNESDAY" CHAR(1),
	"DELIVERS_ON_THURSDAY" CHAR(1),
	"DELIVERS_ON_FRIDAY" CHAR(1),
	"DELIVERS_ON_SATURDAY" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"VENDOR_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"C2_PO_STATUS" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"SINGLE_VENDOR_PO_OPTION" CHAR(1),
	"IS_340B" CHAR(1),
	"IS_TERM_REACTIVATE_AUTO" CHAR(1) DEFAULT 'N' NOT NULL ENABLE,
	"TERM_PRODUCT_COST_BASIS_DAYS" NUMBER(3,0),
	"DSCSA_EXEMPT" CHAR(1),
	"PROMPT_FOR_PO" CHAR(1),
	 CONSTRAINT "FK_DATA_GROUP_18" FOREIGN KEY ("DATA_GROUP")
	  REFERENCES "TREXONE_DATA"."DATA_GROUP" ("DATA_GROUP") ENABLE,
	 CONSTRAINT "FK_VENDOR_08" FOREIGN KEY ("VENDOR_NUM")
	  REFERENCES "TREXONE_DATA"."VENDOR" ("VENDOR_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PKVENDOR_CONFIGURATION" ON "TREXONE_DATA"."VENDOR_CONFIGURATION" ("VENDOR_CONFIGURATION_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."VENDOR_CONFIGURATION" ADD CONSTRAINT "PKVENDOR_CONFIGURATION" PRIMARY KEY ("VENDOR_CONFIGURATION_NUM")
  USING INDEX "TREXONE_DATA"."PKVENDOR_CONFIGURATION"  ENABLE;
-- ==========================================
