-- ==========================================

  CREATE TABLE "TREXONE_DATA"."VENDOR_PRECEDENCE_CONFIG"
   (	"VENDOR_PRECEDENCE_CONFIG_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RANK" NUMBER(9,0) NOT NULL ENABLE,
	"IS_ACTIVE" CHAR(1) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"VENDOR_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DATA_GROUP_21" FOREIGN KEY ("DATA_GROUP")
	  REFERENCES "TREXONE_DATA"."DATA_GROUP" ("DATA_GROUP") ENABLE,
	 CONSTRAINT "FK_VENDOR_14" FOREIGN KEY ("VENDOR_NUM")
	  REFERENCES "TREXONE_DATA"."VENDOR" ("VENDOR_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_VENDOR_PRECEDENCE_CONFIG" ON "TREXONE_DATA"."VENDOR_PRECEDENCE_CONFIG" ("VENDOR_PRECEDENCE_CONFIG_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."VENDOR_PRECEDENCE_CONFIG" ADD CONSTRAINT "PK_VENDOR_PRECEDENCE_CONFIG" PRIMARY KEY ("VENDOR_PRECEDENCE_CONFIG_NUM")
  USING INDEX "TREXONE_DATA"."PK_VENDOR_PRECEDENCE_CONFIG"  ENABLE;
-- ==========================================
