-- ==========================================

  CREATE TABLE "TREXONE_DATA"."VENDOR_ITEM"
   (	"VENDOR_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"VENDOR_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRODUCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"VENDOR_PRODUCT_ID" VARCHAR2(48),
	"PKG_SIZE" NUMBER(16,8),
	"UNIT_PRICE" NUMBER(17,6),
	"UNIT_PRICE_DATE" DATE,
	"PURCHASE_INCREMENT" NUMBER(9,0),
	"STATUS" CHAR(1),
	"AVG_LEAD_TIME" NUMBER(9,0),
	"MIN_ORDER_QTY" NUMBER(16,8),
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"MINIMUM_QTY" NUMBER(12,3),
	"MAXIMUM_QTY" NUMBER(12,3),
	"MIN_DAYS_SUPPLY" NUMBER(9,0),
	"MAX_DAYS_SUPPLY" NUMBER(9,0),
	"GENERICS_PROGRAM" CHAR(1),
	"VENDOR_PKG_SIZE" NUMBER(16,8),
	"VENDOR_PURCHASE_INCREMENT" NUMBER(9,0),
	"USE_VENDOR_PKG_SIZE" CHAR(1),
	"USE_VENDOR_PURCHASE_INCREMENT" CHAR(1),
	"ACTIVE_PRODUCT_NUM" NUMBER GENERATED ALWAYS AS (DECODE("STATUS",'A',"PRODUCT_NUM",NULL)) VIRTUAL ,
	"ACTIVE_VENDOR_NUM" NUMBER GENERATED ALWAYS AS (DECODE("STATUS",'A',"VENDOR_NUM",NULL)) VIRTUAL ,
	"ACTIVE_DATA_GROUP" NUMBER GENERATED ALWAYS AS (DECODE("STATUS",'A',"DATA_GROUP",NULL)) VIRTUAL ,
	 CONSTRAINT "FK_PRODUCT_29" FOREIGN KEY ("PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT" ("PRODUCT_NUM") ENABLE,
	 CONSTRAINT "FK_VENDOR_07" FOREIGN KEY ("VENDOR_NUM")
	  REFERENCES "TREXONE_DATA"."VENDOR" ("VENDOR_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."UC_VENDOR_ITEM_01" ON "TREXONE_DATA"."VENDOR_ITEM" ("ACTIVE_PRODUCT_NUM", "ACTIVE_VENDOR_NUM", "ACTIVE_DATA_GROUP")
  ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_VENDOR_ITEM" ON "TREXONE_DATA"."VENDOR_ITEM" ("VENDOR_ITEM_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."VENDOR_ITEM" ADD CONSTRAINT "PK_VENDOR_ITEM" PRIMARY KEY ("VENDOR_ITEM_NUM")
  USING INDEX "TREXONE_DATA"."PK_VENDOR_ITEM"  ENABLE;
ALTER TABLE "TREXONE_DATA"."VENDOR_ITEM" ADD CONSTRAINT "UC_VENDOR_ITEM_01" UNIQUE ("ACTIVE_PRODUCT_NUM", "ACTIVE_VENDOR_NUM", "ACTIVE_DATA_GROUP")
  USING INDEX "TREXONE_DATA"."UC_VENDOR_ITEM_01"  ENABLE;
-- ==========================================
