-- ==========================================

  CREATE TABLE "TREXONE_DATA"."WEB_ORDER_ITEM"
   (	"WEB_ORDER_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"WEB_ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"WEB_ORDER_SEQ" NUMBER(9,0) NOT NULL ENABLE,
	"RX_NUMBER" VARCHAR2(20) NOT NULL ENABLE,
	"IS_ERROR" CHAR(1) NOT NULL ENABLE,
	"RX_COMMENT" VARCHAR2(256),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_WEB_ORDER_01" FOREIGN KEY ("WEB_ORDER_NUM")
	  REFERENCES "TREXONE_DATA"."WEB_ORDER" ("WEB_ORDER_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_WEB_ORDER_ITEM" ON "TREXONE_DATA"."WEB_ORDER_ITEM" ("WEB_ORDER_ITEM_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."WEB_ORDER_ITEM" ADD CONSTRAINT "PK_WEB_ORDER_ITEM" PRIMARY KEY ("WEB_ORDER_ITEM_NUM")
  USING INDEX "TREXONE_DATA"."PK_WEB_ORDER_ITEM"  ENABLE;
-- ==========================================
