-- ==========================================

  CREATE TABLE "TREXONE_DATA"."WF_ACTION"
   (	"WF_ACTION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(60) NOT NULL ENABLE,
	"ACTION_CLASS" VARCHAR2(255) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_WF_ACTION" ON "TREXONE_DATA"."WF_ACTION" ("WF_ACTION_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."WF_ACTION" ADD CONSTRAINT "PK_WF_ACTION" PRIMARY KEY ("WF_ACTION_NUM")
  USING INDEX "TREXONE_DATA"."PK_WF_ACTION"  ENABLE;
-- ==========================================
