-- ==========================================

  CREATE TABLE "TREXONE_DATA"."WF_BLOCK_DEFINITION"
   (	"WF_BLOCK_DEFINITION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(60),
	"DATESTAMP" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"APPLICATION_VERSION" VARCHAR2(8) NOT NULL ENABLE,
	"BLOCK_CODE" VARCHAR2(2) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"DISPLAY_DESCRIPTION" VARCHAR2(100)
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_WF_BLOCK_DEFINITION" ON "TREXONE_DATA"."WF_BLOCK_DEFINITION" ("WF_BLOCK_DEFINITION_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."WF_BLOCK_DEFINITION" ADD CONSTRAINT "PK_WF_BLOCK_DEFINITION" PRIMARY KEY ("WF_BLOCK_DEFINITION_NUM")
  USING INDEX "TREXONE_DATA"."PK_WF_BLOCK_DEFINITION"  ENABLE;
-- ==========================================
