-- ==========================================

  CREATE TABLE "TREXONE_DATA"."WF_CURRENT_ITEM"
   (	"WF_CURRENT_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"WF_PROCESS_DEFINITION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PROC_INST_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"NODE_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"NODE_INSTANCE_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"WF_BLOCK_DEFINITION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ITEM_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRIORITY" NUMBER(18,0) NOT NULL ENABLE,
	"PROMISE_TIME" DATE NOT NULL ENABLE,
	"ITEM_COUNT" NUMBER(9,0) NOT NULL ENABLE,
	"ITEM_POSITION" NUMBER(9,0) NOT NULL ENABLE,
	"LOCK_USER" NUMBER(18,0),
	"LOCK_DATE" DATE,
	"IS_HIDDEN" CHAR(1) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"APPLICATION_VERSION" VARCHAR2(8) NOT NULL ENABLE,
	"DELIVERY_METHOD_NUM" NUMBER(18,0),
	"IS_PAST_PROMISE" CHAR(1),
	"LOCK_FACILITY_NUM" NUMBER(18,0),
	"PATIENT_NUM" NUMBER(18,0),
	"PRESCRIBER_NUM" NUMBER(18,0),
	"PRODUCT_NUM" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"RX_FILL_SEQ" NUMBER(18,0),
	"RX_FACILITY_NUM" NUMBER(18,0),
	"PICKUP_FACILITY_NUM" NUMBER(18,0),
	"PATIENT_LAST_NAME" VARCHAR2(30),
	"PRESCRIBER_LAST_NAME" VARCHAR2(30),
	"PRODUCT_NAME" VARCHAR2(35),
	"RX_NUMBER" VARCHAR2(20),
	"RX_FACILITY_ID" VARCHAR2(10),
	"CURRENT_FACILITY_ID" VARCHAR2(10),
	"PICKUP_FACILITY_ID" VARCHAR2(10),
	"CF_FACILITY_NUM" NUMBER(18,0),
	"CF_FACILITY_ID" VARCHAR2(10),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"PROFILE_INCLUSION_DATE" DATE,
	"IS_SAVED" CHAR(1) DEFAULT 'N',
	"IS_ADS" CHAR(1) DEFAULT 'N' NOT NULL ENABLE,
	"ON_HOLD_UNTIL" TIMESTAMP (6),
	"IS_DEVISUALINDICATOR_ELIGIBLE" CHAR(1),
	 CONSTRAINT "FK_DELIVERY_METHOD_04" FOREIGN KEY ("DELIVERY_METHOD_NUM")
	  REFERENCES "TREXONE_DATA"."DELIVERY_METHOD" ("DELIVERY_METHOD_NUM") ENABLE,
	 CONSTRAINT "FK_FACILITY_59" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_ITEM_13" FOREIGN KEY ("ORDER_NUM", "ITEM_SEQ")
	  REFERENCES "TREXONE_DATA"."ITEM" ("ORDER_NUM", "ITEM_SEQ") ENABLE,
	 CONSTRAINT "FK_WF_BLOCK_DEFINITION_05" FOREIGN KEY ("WF_BLOCK_DEFINITION_NUM")
	  REFERENCES "TREXONE_DATA"."WF_BLOCK_DEFINITION" ("WF_BLOCK_DEFINITION_NUM") ENABLE,
	 CONSTRAINT "FK_WF_PROCESS_INSTANCE_06" FOREIGN KEY ("WF_PROCESS_DEFINITION_NUM", "PROC_INST_SEQ")
	  REFERENCES "TREXONE_DATA"."WF_PROCESS_INSTANCE" ("WF_PROCESS_DEFINITION_NUM", "PROC_INST_SEQ") ENABLE,
	 CONSTRAINT "FK_FACILITY_86" FOREIGN KEY ("LOCK_FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_PATIENT_31" FOREIGN KEY ("PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE,
	 CONSTRAINT "FK_PRESCRIBER_30" FOREIGN KEY ("PRESCRIBER_NUM")
	  REFERENCES "TREXONE_DATA"."PRESCRIBER" ("PRESCRIBER_NUM") ENABLE,
	 CONSTRAINT "FK_PRODUCT_44" FOREIGN KEY ("PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT" ("PRODUCT_NUM") ENABLE,
	 CONSTRAINT "FK_RX_15" FOREIGN KEY ("RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_BASE" ("RX_RECORD_NUM") ENABLE,
	 CONSTRAINT "FK_RX_FILL_18" FOREIGN KEY ("RX_FILL_SEQ", "RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_FILL" ("RX_FILL_SEQ", "RX_RECORD_NUM") ENABLE,
	 CONSTRAINT "FK_FACILITY_92" FOREIGN KEY ("RX_FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_FACILITY_93" FOREIGN KEY ("PICKUP_FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_FACILITY_94" FOREIGN KEY ("CF_FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_WF_CURRENT_ITEM" ON "TREXONE_DATA"."WF_CURRENT_ITEM" ("WF_CURRENT_ITEM_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."WF_CURRENT_ITEM" ADD CONSTRAINT "PK_WF_CURRENT_ITEM" PRIMARY KEY ("WF_CURRENT_ITEM_NUM")
  USING INDEX "TREXONE_DATA"."PK_WF_CURRENT_ITEM"  ENABLE;
-- ==========================================
