-- ==========================================

  CREATE TABLE "TREXONE_DATA"."WF_DECISION_PARAMETER"
   (	"WF_PROCESS_DEFINITION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NODE_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"PARAMETER_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(255) NOT NULL ENABLE,
	"VALUE" VARCHAR2(255) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_WF_NODE_DEFINITION_01" FOREIGN KEY ("WF_PROCESS_DEFINITION_NUM", "NODE_SEQ")
	  REFERENCES "TREXONE_DATA"."WF_NODE_DEFINITION" ("WF_PROCESS_DEFINITION_NUM", "NODE_SEQ") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_WF_DECISION_PARAMETER" ON "TREXONE_DATA"."WF_DECISION_PARAMETER" ("WF_PROCESS_DEFINITION_NUM", "NODE_SEQ", "PARAMETER_SEQ")
  ;
ALTER TABLE "TREXONE_DATA"."WF_DECISION_PARAMETER" ADD CONSTRAINT "PK_WF_DECISION_PARAMETER" PRIMARY KEY ("WF_PROCESS_DEFINITION_NUM", "NODE_SEQ", "PARAMETER_SEQ")
  USING INDEX "TREXONE_DATA"."PK_WF_DECISION_PARAMETER"  ENABLE;
-- ==========================================
