-- ==========================================

  CREATE TABLE "TREXONE_DATA"."WF_PROCESS_DEFINITION"
   (	"WF_PROCESS_DEFINITION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(60) NOT NULL ENABLE,
	"IS_ACTIVE" CHAR(1) NOT NULL ENABLE,
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE,
	"EXPIRATION_DATE" DATE,
	"COMMENT_TEXT" VARCHAR2(255),
	"EXCEPTION_HANDLER_CLASS" VARCHAR2(255),
	"DATESTAMP" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"APPLICATION_VERSION" VARCHAR2(8) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_WF_PROCESS_DEFINITION" ON "TREXONE_DATA"."WF_PROCESS_DEFINITION" ("WF_PROCESS_DEFINITION_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."WF_PROCESS_DEFINITION" ADD CONSTRAINT "PK_WF_PROCESS_DEFINITION" PRIMARY KEY ("WF_PROCESS_DEFINITION_NUM")
  USING INDEX "TREXONE_DATA"."PK_WF_PROCESS_DEFINITION"  ENABLE;
-- ==========================================
