-- ==========================================

  CREATE TABLE "TREXONE_DATA"."WF_PROCESS_INSTANCE"
   (	"WF_PROCESS_DEFINITION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PROC_INST_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"PROCESS_STATE" VARCHAR2(30),
	"COMMENT_TEXT" VARCHAR2(255),
	"CREATE_DATE" DATE NOT NULL ENABLE,
	"CREATE_USER" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"IS_LOCAL" CHAR(1) NOT NULL ENABLE,
	"IS_DUR_EXCEPTION" CHAR(1) NOT NULL ENABLE,
	"IS_ADJ_EXCEPTION" CHAR(1) NOT NULL ENABLE,
	"IS_AR_EXCEPTION" CHAR(1) NOT NULL ENABLE,
	"IS_PRE_EDIT_EXCEPTION" CHAR(1) NOT NULL ENABLE,
	"IS_DELETE_PENDING" CHAR(1) NOT NULL ENABLE,
	"IS_DECLINING" CHAR(1) NOT NULL ENABLE,
	"IS_FORCED_FOA" CHAR(1),
	"DECLINE_REASON" VARCHAR2(128),
	"ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ITEM_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"PARENT_PROCESS_DEFINITION_NUM" NUMBER(18,0),
	"PARENT_PROC_INST_SEQ" NUMBER(18,0),
	"DATESTAMP" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"IS_PULLED_BACK" CHAR(1),
	"IS_PACKED" CHAR(1),
	"IS_ADS_EXCEPTION" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"ON_HOLD_REASON_CODE" CHAR(1),
	 CONSTRAINT "FK_ITEM_12" FOREIGN KEY ("ORDER_NUM", "ITEM_SEQ")
	  REFERENCES "TREXONE_DATA"."ITEM" ("ORDER_NUM", "ITEM_SEQ") ENABLE,
	 CONSTRAINT "FK_WF_PROCESS_DEFINITION_03" FOREIGN KEY ("WF_PROCESS_DEFINITION_NUM")
	  REFERENCES "TREXONE_DATA"."WF_PROCESS_DEFINITION" ("WF_PROCESS_DEFINITION_NUM") ENABLE,
	 CONSTRAINT "FK_WF_PROCESS_INSTANCE_02" FOREIGN KEY ("PARENT_PROCESS_DEFINITION_NUM", "PARENT_PROC_INST_SEQ")
	  REFERENCES "TREXONE_DATA"."WF_PROCESS_INSTANCE" ("WF_PROCESS_DEFINITION_NUM", "PROC_INST_SEQ") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE INDEX "TREXONE_DATA"."PK_WF_PROCESS_INSTANCE" ON "TREXONE_DATA"."WF_PROCESS_INSTANCE" ("WF_PROCESS_DEFINITION_NUM", "PROC_INST_SEQ", "ORDER_NUM", "ITEM_SEQ", "IS_DECLINING", "DECLINE_REASON")
  ;
ALTER TABLE "TREXONE_DATA"."WF_PROCESS_INSTANCE" ADD CONSTRAINT "PK_WF_PROCESS_INSTANCE" PRIMARY KEY ("WF_PROCESS_DEFINITION_NUM", "PROC_INST_SEQ")
  USING INDEX "TREXONE_DATA"."PK_WF_PROCESS_INSTANCE"  ENABLE;
-- ==========================================
