-- ==========================================

  CREATE TABLE "TREXONE_DATA"."WF_QUEUE_DEFINITION"
   (	"WF_QUEUE_DEFINITION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SHORT_CODE" VARCHAR2(30) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(60) NOT NULL ENABLE,
	"IS_SHOW_NEXT" CHAR(1) NOT NULL ENABLE,
	"IS_SHOW_QUEUE" CHAR(1) NOT NULL ENABLE,
	"IS_FOLLOW_ITEM" CHAR(1) NOT NULL ENABLE,
	"IS_VIEW" CHAR(1),
	"DATESTAMP" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"APPLICATION_VERSION" VARCHAR2(8) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"MENU_SORT_ORDER" NUMBER(9,0),
	"MENU_MNEMONIC" VARCHAR2(20)
   ) ;
  CREATE INDEX "TREXONE_DATA"."PK_WF_QUEUE_DEFINITION" ON "TREXONE_DATA"."WF_QUEUE_DEFINITION" ("WF_QUEUE_DEFINITION_NUM", "IS_VIEW")
  ;
ALTER TABLE "TREXONE_DATA"."WF_QUEUE_DEFINITION" ADD CONSTRAINT "PK_WF_QUEUE_DEFINITION" PRIMARY KEY ("WF_QUEUE_DEFINITION_NUM")
  USING INDEX "TREXONE_DATA"."PK_WF_QUEUE_DEFINITION"  ENABLE;
-- ==========================================
