-- ==========================================

  CREATE TABLE "TREXONE_DATA"."WF_QUEUE_FIELD"
   (	"WF_QUEUE_DEFINITION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"QUEUE_FIELD_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"FIELD_NAME" VARCHAR2(60),
	"DESCRIPTION" VARCHAR2(60),
	"DATESTAMP" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_WF_QUEUE_DEFINITION_04" FOREIGN KEY ("WF_QUEUE_DEFINITION_NUM")
	  REFERENCES "TREXONE_DATA"."WF_QUEUE_DEFINITION" ("WF_QUEUE_DEFINITION_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_WF_QUEUE_FIELD" ON "TREXONE_DATA"."WF_QUEUE_FIELD" ("WF_QUEUE_DEFINITION_NUM", "QUEUE_FIELD_SEQ")
  ;
ALTER TABLE "TREXONE_DATA"."WF_QUEUE_FIELD" ADD CONSTRAINT "PK_WF_QUEUE_FIELD" PRIMARY KEY ("WF_QUEUE_DEFINITION_NUM", "QUEUE_FIELD_SEQ")
  USING INDEX "TREXONE_DATA"."PK_WF_QUEUE_FIELD"  ENABLE;
-- ==========================================
