-- ==========================================

  CREATE TABLE "TREXONE_DATA"."WF_QUEUE_BLOCK_DETAIL"
   (	"WF_QUEUE_DEFINITION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"WF_BLOCK_DEFINITION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"BLOCK_PRIORITY" NUMBER(18,0) NOT NULL ENABLE,
	"IS_START_BLOCK" CHAR(1),
	"IS_END_BLOCK" CHAR(1),
	"DATESTAMP" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_WF_BLOCK_DEFINITION_03" FOREIGN KEY ("WF_BLOCK_DEFINITION_NUM")
	  REFERENCES "TREXONE_DATA"."WF_BLOCK_DEFINITION" ("WF_BLOCK_DEFINITION_NUM") ENABLE,
	 CONSTRAINT "FK_WF_QUEUE_DEFINITION_03" FOREIGN KEY ("WF_QUEUE_DEFINITION_NUM")
	  REFERENCES "TREXONE_DATA"."WF_QUEUE_DEFINITION" ("WF_QUEUE_DEFINITION_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_WF_QUEUE_BLOCK_DETAIL" ON "TREXONE_DATA"."WF_QUEUE_BLOCK_DETAIL" ("WF_QUEUE_DEFINITION_NUM", "WF_BLOCK_DEFINITION_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."WF_QUEUE_BLOCK_DETAIL" ADD CONSTRAINT "PK_WF_QUEUE_BLOCK_DETAIL" PRIMARY KEY ("WF_QUEUE_DEFINITION_NUM", "WF_BLOCK_DEFINITION_NUM")
  USING INDEX "TREXONE_DATA"."PK_WF_QUEUE_BLOCK_DETAIL"  ENABLE;
-- ==========================================
