-- ==========================================

  CREATE TABLE "TREXONE_DATA"."WF_QUEUE_STATUS"
   (	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"WF_QUEUE_DEFINITION_NUM" NUMBER(18,0),
	"ITEM_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"PROMISE_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"APPLICATION_VERSION" VARCHAR2(8) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"WF_BLOCK_DEFINITION_NUM" NUMBER(18,0),
	"LOCK_AVOIDANCE_BUCKET" NUMBER(18,0) DEFAULT 0 NOT NULL ENABLE,
	 CONSTRAINT "PK_WF_QUEUE_STATUS" PRIMARY KEY ("FACILITY_NUM", "WF_BLOCK_DEFINITION_NUM", "APPLICATION_VERSION", "LOCK_AVOIDANCE_BUCKET")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_WF_BLOCK_DEFINITION_06" FOREIGN KEY ("WF_BLOCK_DEFINITION_NUM")
	  REFERENCES "TREXONE_DATA"."WF_BLOCK_DEFINITION" ("WF_BLOCK_DEFINITION_NUM") ENABLE
   ) ;
-- ==========================================
