-- ==========================================

  CREATE TABLE "TREXONE_DATA"."WF_QUEUE_FIELD_DATA"
   (	"WF_QUEUE_DEFINITION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"QUEUE_FIELD_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"QUEUE_FIELD_DATA_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"SYSTEM_USER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SORT_ORDER" NUMBER(9,0),
	"IS_VISIBLE" CHAR(1) NOT NULL ENABLE,
	"FIELD_SIZE" NUMBER(18,0),
	"DATESTAMP" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_22" FOREIGN KEY ("SYSTEM_USER_NUM")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE,
	 CONSTRAINT "FK_WF_QUEUE_FIELD_01" FOREIGN KEY ("WF_QUEUE_DEFINITION_NUM", "QUEUE_FIELD_SEQ")
	  REFERENCES "TREXONE_DATA"."WF_QUEUE_FIELD" ("WF_QUEUE_DEFINITION_NUM", "QUEUE_FIELD_SEQ") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_WF_QUEUE_FIELD_DATA" ON "TREXONE_DATA"."WF_QUEUE_FIELD_DATA" ("WF_QUEUE_DEFINITION_NUM", "QUEUE_FIELD_SEQ", "QUEUE_FIELD_DATA_SEQ")
  ;
ALTER TABLE "TREXONE_DATA"."WF_QUEUE_FIELD_DATA" ADD CONSTRAINT "PK_WF_QUEUE_FIELD_DATA" PRIMARY KEY ("WF_QUEUE_DEFINITION_NUM", "QUEUE_FIELD_SEQ", "QUEUE_FIELD_DATA_SEQ")
  USING INDEX "TREXONE_DATA"."PK_WF_QUEUE_FIELD_DATA"  ENABLE;
-- ==========================================
