-- ==========================================

  CREATE TABLE "TREXONE_DATA"."WF_SNOOZE"
   (	"WF_PROCESS_DEFINITION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SYSTEM_USER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PROC_INST_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"NODE_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"NODE_INSTANCE_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"SNOOZE_UNTIL" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_24" FOREIGN KEY ("SYSTEM_USER_NUM")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE,
	 CONSTRAINT "FK_WF_USER_ITEM_02" FOREIGN KEY ("WF_PROCESS_DEFINITION_NUM", "PROC_INST_SEQ", "NODE_SEQ", "NODE_INSTANCE_SEQ")
	  REFERENCES "TREXONE_DATA"."WF_USER_ITEM" ("WF_PROCESS_DEFINITION_NUM", "PROC_INST_SEQ", "NODE_SEQ", "NODE_INSTANCE_SEQ") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_WF_SNOOZE" ON "TREXONE_DATA"."WF_SNOOZE" ("WF_PROCESS_DEFINITION_NUM", "SYSTEM_USER_NUM", "PROC_INST_SEQ", "NODE_SEQ", "NODE_INSTANCE_SEQ")
  ;
ALTER TABLE "TREXONE_DATA"."WF_SNOOZE" ADD CONSTRAINT "PK_WF_SNOOZE" PRIMARY KEY ("WF_PROCESS_DEFINITION_NUM", "SYSTEM_USER_NUM", "PROC_INST_SEQ", "NODE_SEQ", "NODE_INSTANCE_SEQ")
  USING INDEX "TREXONE_DATA"."PK_WF_SNOOZE"  ENABLE;
-- ==========================================
