-- ==========================================

  CREATE TABLE "TREXONE_DATA"."WF_USER_ITEM"
   (	"WF_PROCESS_DEFINITION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PROC_INST_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"NODE_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"NODE_INSTANCE_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"WF_BLOCK_DEFINITION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NODE_STATE" VARCHAR2(30) NOT NULL ENABLE,
	"STATE_DATE" DATE NOT NULL ENABLE,
	"ACTIVATED_DATE" DATE,
	"COMPLETION_DATE" DATE,
	"PRIORITY" NUMBER(18,0) NOT NULL ENABLE,
	"DECISION_VALUE" NUMBER(18,0),
	"COMPLETE_USER" NUMBER(18,0),
	"COMPLETE_FACILITY_NUM" NUMBER(18,0),
	"CREATE_DATE" DATE NOT NULL ENABLE,
	"LOCK_USER" NUMBER(18,0),
	"LOCK_DATE" DATE,
	"GROUP_ID" NUMBER(18,0),
	"RESERVE_USER" NUMBER(18,0),
	"RESERVE_UNTIL" DATE,
	"IS_HIDDEN" CHAR(1) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0),
	"DECLINE_REASON" VARCHAR2(40),
	"APPLICATION_VERSION" VARCHAR2(8) NOT NULL ENABLE,
	"LOCK_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"RETAIL_VRF_PHARMACIST" VARCHAR2(255),
	"BYPASSED_HOLD_ALERTS" CHAR(1),
	"BYPASSED_HOLD_ALERT_DATESTAMP" DATE,
	 CONSTRAINT "FK_FACILITY_57" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_WF_BLOCK_DEFINITION_04" FOREIGN KEY ("WF_BLOCK_DEFINITION_NUM")
	  REFERENCES "TREXONE_DATA"."WF_BLOCK_DEFINITION" ("WF_BLOCK_DEFINITION_NUM") ENABLE,
	 CONSTRAINT "FK_WF_PROCESS_INSTANCE_04" FOREIGN KEY ("WF_PROCESS_DEFINITION_NUM", "PROC_INST_SEQ")
	  REFERENCES "TREXONE_DATA"."WF_PROCESS_INSTANCE" ("WF_PROCESS_DEFINITION_NUM", "PROC_INST_SEQ") ENABLE,
	 CONSTRAINT "FK_FACILITY_85" FOREIGN KEY ("LOCK_FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_WF_USER_ITEM" ON "TREXONE_DATA"."WF_USER_ITEM" ("WF_PROCESS_DEFINITION_NUM", "PROC_INST_SEQ", "NODE_SEQ", "NODE_INSTANCE_SEQ")
  ;
ALTER TABLE "TREXONE_DATA"."WF_USER_ITEM" ADD CONSTRAINT "PK_WF_USER_ITEM" PRIMARY KEY ("WF_PROCESS_DEFINITION_NUM", "PROC_INST_SEQ", "NODE_SEQ", "NODE_INSTANCE_SEQ")
  USING INDEX "TREXONE_DATA"."PK_WF_USER_ITEM"  ENABLE;
-- ==========================================
