-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ZIPCODE_PRELOAD"
   (	"ZIPCODE" VARCHAR2(10),
	"CITY" VARCHAR2(40),
	"STATE" CHAR(2),
	"COUNTY" VARCHAR2(30),
	"DETAIL_TEXT" VARCHAR2(200),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;

