-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."BATCH_MESSAGE"
   (	"BATCH_MESSAGE_NUM" NUMBER(18,0),
	"BATCH_LOG_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PROCEDURE_NAME" VARCHAR2(100),
	"SQL_ERROR_CODE" VARCHAR2(255),
	"STATUS_MSG" VARCHAR2(4000),
	"SEVERITY_CODE" CHAR(1),
	"MSG_TIMESTAMP" TIMESTAMP (6),
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "PK_BATCH_MESSAGE" PRIMARY KEY ("BATCH_MESSAGE_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_BATCH_LOG_01" FOREIGN KEY ("BATCH_LOG_NUM")
	  REFERENCES "TREXONE_ODS_DATA"."BATCH_LOG" ("BATCH_LOG_NUM") ENABLE
   ) ;
-- ==========================================
