-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."BATCH_CTL"
   (	"BATCH_CTL_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"BATCH_TIMESTAMP" TIMESTAMP (6) NOT NULL ENABLE,
	"BATCH_RUN_CODE" CHAR(1) NOT NULL ENABLE,
	"BATCH_PARAM1" VARCHAR2(200),
	"BATCH_PARAM2" VARCHAR2(200),
	"BATCH_PARAM3" VARCHAR2(200),
	"BATCH_PARAM4" VARCHAR2(200),
	 CONSTRAINT "PK_BATCH_CTL" PRIMARY KEY ("BATCH_CTL_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
