-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."CORE_RX_FILL_SOLD_STG"
   (	"RX_NUMBER" VARCHAR2(20) NOT NULL ENABLE,
	"FILL_CNT" NUMBER(1,0),
	"SALES_DATE" DATE,
	"CANCEL_DATE" DATE,
	"IS_340B" CHAR(1),
	"IS_MAIL" CHAR(1),
	"DISPENSED_QUANTITY" NUMBER,
	"CRFS_SEQ_NUM" NUMBER NOT NULL ENABLE,
	"ADJUDICATION_GROUP_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"PRODUCT_NUM" NUMBER(18,0),
	"GENERIC_SUB_CD" NUMBER(1,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"GCN_SEQ_NUM" VARCHAR2(30),
	"SALES_MON" VARCHAR2(2),
	"SALES_DT" VARCHAR2(2),
	"SALES_YR" VARCHAR2(4),
	"PARTIAL_FILL_IND" CHAR(1),
	"WRITTEN_QUANTITY" NUMBER,
	"REFILL_NUM" NUMBER(18,0),
	"PARTIAL_FILL_SEQ" NUMBER(2,0),
	"IS_PARTIAL_FILL_BILLED" CHAR(1),
	"SYS_USER" NUMBER(18,0),
	"CF_INDICATOR" CHAR(2),
	"TARGET_CF_FACILITY_NUM" NUMBER(18,0)
   )
  PARTITION BY RANGE ("SALES_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("ODS_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2001-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
