-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ETL_PROC"
   (	"ETL_PROC_NUM" NUMBER(18,0),
	"ETL_STEP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PROC_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"IS_ACTIVE" CHAR(1) NOT NULL ENABLE,
	"RUN_GROUP" NUMBER(20,2) NOT NULL ENABLE,
	"IS_NEXT_GROUP_DEPENDENT" CHAR(1) NOT NULL ENABLE,
	"RUN_PRIORITY" NUMBER(20,2) NOT NULL ENABLE,
	"LOOP_HOURS" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "PK_ETL_PROC" PRIMARY KEY ("ETL_PROC_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_ETL_STEP_02" FOREIGN KEY ("ETL_STEP_NUM")
	  REFERENCES "TREXONE_ODS_DATA"."ETL_STEP" ("ETL_STEP_NUM") ENABLE
   ) ;
-- ==========================================
