-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ETL_STEP_GROUP"
   (	"ETL_STEP_GROUP_NUM" NUMBER(18,0),
	"STEP_GROUP_NAME" VARCHAR2(20) NOT NULL ENABLE,
	"STEP_GROUP_DESC" VARCHAR2(200),
	"MINUTES_BEFORE_START_TIME" NUMBER(3,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "PK_ETL_STEP_GROUP" PRIMARY KEY ("ETL_STEP_GROUP_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
