-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ETL_RUN_STEP"
   (	"ETL_RUN_STEP_NUM" NUMBER(18,0),
	"ETL_RUN_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ETL_STEP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"START_TIME" DATE NOT NULL ENABLE,
	"END_TIME" DATE,
	"STATUS" CHAR(1) NOT NULL ENABLE,
	"OS_PROCESS_ID" VARCHAR2(20),
	"ROWS_PROCESSED" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "PK_ETL_RUN_STEP" PRIMARY KEY ("ETL_RUN_STEP_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_ETL_RUN_01" FOREIGN KEY ("ETL_RUN_NUM")
	  REFERENCES "TREXONE_ODS_DATA"."ETL_RUN" ("ETL_RUN_NUM") ENABLE,
	 CONSTRAINT "FK_ETL_STEP_03" FOREIGN KEY ("ETL_STEP_NUM")
	  REFERENCES "TREXONE_ODS_DATA"."ETL_STEP" ("ETL_STEP_NUM") ENABLE
   )
  PARTITION BY RANGE ("START_TIME") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("ODS_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
