-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."FINANCIAL_EVENT"
   (	"FINANCIAL_EVENT_NUM" NUMBER(18,0),
	"EVENT_LEVEL" CHAR(1),
	"TYPE_NUM" NUMBER(9,0),
	"OCCURRED" TIMESTAMP (6),
	"ORDER_NUM" NUMBER(18,0),
	"ITEM_SEQ" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"RX_FILL_SEQ" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"IS_CASH" CHAR(1),
	"IS_BAR" CHAR(1),
	"IS_LAST_PAYER" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"TP_ITEM_CLAIM_NUM" NUMBER(18,0),
	"TP_MESSAGE_NUM" NUMBER(18,0),
	"TP_CASH_MESSAGE_NUM" NUMBER(18,0),
	"PRICE_CALC_RESULT_NUM" NUMBER(18,0),
	"ADJUDICATION_GROUP_NUM" NUMBER(18,0)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
