-- ==========================================

  CREATE GLOBAL TEMPORARY TABLE "TREXONE_ODS_DATA"."GTT_IOT_CREDIT_RETURN"
   (	"CREATE_DATE" DATE,
	"FILL_FACT_KEY" NUMBER(18,0),
	"FD_FACILITY_KEY" NUMBER(18,0),
	"CENTRAL_FILL_FD_FACILITY_KEY" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"RX_NUMBER" VARCHAR2(20),
	"RX_FILL_SEQ" NUMBER(18,0),
	"REFILL_NUM" NUMBER(18,0),
	"QTY_DISPENSED" NUMBER(13,3),
	"IS_340B" CHAR(1),
	"READY_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"DISPENSED_DRUG_KEY" NUMBER(18,0),
	"PD_PATIENT_KEY" NUMBER(18,0)
   ) ON COMMIT DELETE ROWS ;
-- ==========================================
