-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."IOT_BATCH_JOB_CTL"
   (	"JOB_IDENTIFIER" VARCHAR2(100) NOT NULL ENABLE,
	"JOB_TYPE_CODE" CHAR(1) NOT NULL ENABLE,
	"JOB_STATUS_CODE" CHAR(1) NOT NULL ENABLE,
	"JOB_STATUS_DATE" DATE NOT NULL ENABLE,
	"JOB_LAST_PROC_SEQ" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100) NOT NULL ENABLE
   ) ;
-- ==========================================
