-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."IOT_STAGE_CREDIT_RETURN"
   (	"CREATE_DATE" DATE,
	"TIMEZONE_ID" VARCHAR2(60),
	"FILL_FACT_KEY" NUMBER(18,0),
	"FACILITY_KEY" NUMBER(18,0),
	"FACILITY_NPI" VARCHAR2(20),
	"FACILITY_NUM" NUMBER(18,0),
	"FACILITY_ID" VARCHAR2(10),
	"CENTRAL_FILL_NPI" VARCHAR2(20),
	"RX_RECORD_NUM" NUMBER(18,0),
	"RX_NUMBER" VARCHAR2(20),
	"RX_FILL_SEQ" NUMBER(18,0),
	"REFILL_NUM" NUMBER(18,0),
	"PRODUCT_KEY" NUMBER(18,0),
	"PRODUCT_NUM" NUMBER(18,0),
	"DRUG_KEY" NUMBER(18,0),
	"INVENTORY_ITEM_NUM" NUMBER(18,0),
	"NDC_NUMBER" VARCHAR2(20),
	"QTY_DISPENSED" NUMBER(13,3),
	"PATIENT_NUM" NUMBER(18,0),
	"IS_340B" CHAR(1),
	"IS_CENTRAL_FILL" CHAR(1),
	"READY_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("CREATE_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("ODS_LARGE_DATA01")
  SUBPARTITION BY LIST ("TIMEZONE_ID")
  SUBPARTITION TEMPLATE (
    SUBPARTITION "US_MOUNTAIN" VALUES ( 'US/MOUNTAIN' ),
    SUBPARTITION "US_CENTRAL" VALUES ( 'US/CENTRAL' ),
    SUBPARTITION "US_HAWAII" VALUES ( 'US/HAWAII' ),
    SUBPARTITION "US_EASTERN" VALUES ( 'US/EASTERN' ),
    SUBPARTITION "PACIFIC_SAIPAN" VALUES ( 'PACIFIC/SAIPAN' ),
    SUBPARTITION "US_PACIFIC_NEW" VALUES ( 'US/PACIFIC-NEW' ),
    SUBPARTITION "US_PACIFIC" VALUES ( 'US/PACIFIC' ),
    SUBPARTITION "US_INDIANA_STARKE" VALUES ( 'US/INDIANA-STARKE' ),
    SUBPARTITION "US_MICHIGAN" VALUES ( 'US/MICHIGAN' ),
    SUBPARTITION "US_ALEUTIAN" VALUES ( 'US/ALEUTIAN' ),
    SUBPARTITION "US_SAMOA" VALUES ( 'US/SAMOA' ),
    SUBPARTITION "US_EAST_INDIANA" VALUES ( 'US/EAST-INDIANA' ),
    SUBPARTITION "US_ARIZONA" VALUES ( 'US/ARIZONA' ),
    SUBPARTITION "US_ALASKA" VALUES ( 'US/ALASKA' ) )
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
