-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."IOT_STAGE_INVENTORY_ADJ"
   (	"CREATE_DATE" DATE NOT NULL ENABLE,
	"TIMEZONE_ID" VARCHAR2(60) NOT NULL ENABLE,
	"FACILITY_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NPI" VARCHAR2(20),
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_ID" VARCHAR2(10),
	"PRODUCT_KEY" NUMBER(18,0),
	"PRODUCT_NUM" NUMBER(18,0),
	"DRUG_KEY" NUMBER(18,0),
	"INVENTORY_ITEM_NUM" NUMBER(18,0),
	"NDC_NUMBER" VARCHAR2(20),
	"ADJUSTMENT_QTY" NUMBER(16,8),
	"QTY_ONHAND_BEGIN" NUMBER(16,8),
	"QTY_ONHAND_END" NUMBER(16,8),
	"ADJ_USER_NAME" VARCHAR2(255),
	"ERX_CLIENT_ID" VARCHAR2(100) NOT NULL ENABLE
   )
  PARTITION BY RANGE ("CREATE_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("ODS_LARGE_DATA01")
  SUBPARTITION BY LIST ("TIMEZONE_ID")
  SUBPARTITION TEMPLATE (
    SUBPARTITION "US_MOUNTAIN" VALUES ( 'US/MOUNTAIN' ),
    SUBPARTITION "US_CENTRAL" VALUES ( 'US/CENTRAL' ),
    SUBPARTITION "US_HAWAII" VALUES ( 'US/HAWAII' ),
    SUBPARTITION "US_EASTERN" VALUES ( 'US/EASTERN' ),
    SUBPARTITION "PACIFIC_SAIPAN" VALUES ( 'PACIFIC/SAIPAN' ),
    SUBPARTITION "US_PACIFIC_NEW" VALUES ( 'US/PACIFIC-NEW' ),
    SUBPARTITION "US_PACIFIC" VALUES ( 'US/PACIFIC' ),
    SUBPARTITION "US_INDIANA_STARKE" VALUES ( 'US/INDIANA-STARKE' ),
    SUBPARTITION "US_MICHIGAN" VALUES ( 'US/MICHIGAN' ),
    SUBPARTITION "US_ALEUTIAN" VALUES ( 'US/ALEUTIAN' ),
    SUBPARTITION "US_SAMOA" VALUES ( 'US/SAMOA' ),
    SUBPARTITION "US_EAST_INDIANA" VALUES ( 'US/EAST-INDIANA' ),
    SUBPARTITION "US_ARIZONA" VALUES ( 'US/ARIZONA' ),
    SUBPARTITION "US_ALASKA" VALUES ( 'US/ALASKA' ) )
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
