-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_CONVERSATION"
   (	"CONVERSATION_NUM" NUMBER(18,0),
	"MESSAGE_NUM" NUMBER(18,0),
	"MESSAGE_TEXT" VARCHAR2(4000),
	"SENDER" VARCHAR2(100),
	"MESSAGE_SENT" DATE,
	"PARTITION_DATE" DATE,
	"LOCATION_ID" VARCHAR2(100),
	"H_TYPE" CHAR(1),
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("ODS_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
