-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_SYSTEM_USER"
   (	"SYSTEM_USER_NUM" NUMBER(18,0),
	"LOGIN_NAME" VARCHAR2(255),
	"FIRST_NAME" VARCHAR2(30),
	"MIDDLE_NAME" VARCHAR2(30),
	"LAST_NAME" VARCHAR2(30),
	"INITIALS" VARCHAR2(3),
	"USER_PASSWORD" VARCHAR2(255),
	"EMPLOYEE_CODE" VARCHAR2(20),
	"IS_PRIVATE" CHAR(1),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"DEFAULT_DATA_GROUP" NUMBER(18,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"DISPLAY_NAME" VARCHAR2(100),
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"USER_DN" VARCHAR2(1000),
	"ROLE_SET" VARCHAR2(4000),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"EXTERNAL_USER_ID" VARCHAR2(30)
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
