-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_FAX_ORDER_IN"
   (	"FAX_ORDER_IN_NUM" NUMBER(18,0),
	"ELECTRONIC_ORDER_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"IMAGE_NUM" NUMBER(18,0),
	"FROM_FAX_NUM" VARCHAR2(12),
	"TO_FAX_NUM" VARCHAR2(12),
	"SENDER_NAME" VARCHAR2(30),
	"RECIPIENT_NAME" VARCHAR2(30),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"NUM_PAGES" NUMBER(2,0),
	"RX_FILL_SEQ" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"IMAGE_PROC_STATUS" CHAR(1),
	"PATIENT_NUM" NUMBER(22,0)
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
