-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_CONTACT_EVENT"
   (	"CONTACT_EVENT_NUM" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"CONTACT_EVENT_TYPE_NUM" NUMBER(9,0),
	"WF_PROCESS_DEFINITION_NUM" NUMBER(18,0),
	"PROC_INST_SEQ" NUMBER(18,0),
	"RX_FILL_SEQ" NUMBER(18,0),
	"CONTACT_TYPE_NUM" NUMBER(9,0),
	"CONTACT_METHOD_NUM" NUMBER(18,0),
	"CONTACT_STATUS_NUM" NUMBER(9,0),
	"CONTACT_NAME" VARCHAR2(2000),
	"EVENT_COMMENT" VARCHAR2(2000),
	"INFORM_ON_RESOLUTION" NUMBER(9,0),
	"CREATE_USER" NUMBER(18,0),
	"CREATE_DATE" DATE,
	"FOLLOW_UP_TIME" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"PROCESS_FLAG" CHAR(1) DEFAULT 'P',
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"CLARIFICATION_REASON_NUM" NUMBER(9,0)
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
