-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_PACKAGING_TYPE_DETAILS"
   (	"PACKAGING_TYPE_DETAILS_NUM" NUMBER(18,0),
	"PACKAGING_TYPE_NUM" NUMBER(18,0),
	"IS_DEFAULT" CHAR(1),
	"IS_ENABLED" CHAR(1),
	"NUMBER_OF_LABELS" NUMBER(9,0),
	"DOC_TYPE_NAME" VARCHAR2(30),
	"SPECIAL_PACKAGING_CODE" CHAR(1),
	"HOA_REQUIRED" CHAR(1),
	"FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE,
	"SYS_USER" NUMBER(18,0),
	"H_LEVEL" NUMBER,
	"H_TYPE" VARCHAR2(1),
	"PARTITION_DATE" DATE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("ODS_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
