-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_EPCS_AUDIT"
   (	"LOG_TYPE" CHAR(1),
	"LOG_PRIORITY" NUMBER(1,0),
	"LOG_MESSAGE" VARCHAR2(4000),
	"PPI_MESSAGE_ID_VALUE" VARCHAR2(35),
	"PPI_MESSAGE_SENDER_VALUE" VARCHAR2(80),
	"PPI_MESSAGE_SENDER_QUAL" VARCHAR2(3),
	"DATA_GROUP" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"EVENT_OUTCOME" CHAR(1),
	"EVENT_CATEGORY" VARCHAR2(255),
	"EVENT_SUB_CATEGORY" VARCHAR2(255),
	"EPCS_PRES_FIRST_NAME" VARCHAR2(35),
	"EPCS_PRES_LAST_NAME" VARCHAR2(35),
	"EPCS_PRES_DEA_NUMBER" VARCHAR2(35),
	"SUBJECT_LOGIN_NAME" VARCHAR2(255),
	"EXECUTING_LOGIN_NAME" VARCHAR2(255),
	"RX_NUMBER" VARCHAR2(30),
	"PARTITION_DATE" DATE,
	"H_TYPE" CHAR(1),
	"H_LEVEL" NUMBER,
	"EVENT_DATESTAMP" DATE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("ODS_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
