-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_PATIENT_STATUS_DETAIL"
   (	"PATIENT_NUM" NUMBER(18,0),
	"PATIENT_STATUS_SEQ" NUMBER(18,0),
	"NEW_STATUS" CHAR(1),
	"EFFECTIVE_DATE" DATE,
	"TERM_DATE" DATE,
	"COMMENTARY" VARCHAR2(255),
	"CREATE_DATE" DATE,
	"CREATE_USER" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PROCESS_FLAG" CHAR(1) DEFAULT 'P',
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
