-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_LOT_ADJUSTMENT"
   (	"LOT_ADJUSTMENT_NUM" NUMBER(18,0),
	"INVENTORY_LOT_NUM" NUMBER(18,0),
	"LOT_COMMIT_NUM" NUMBER(18,0),
	"QUANTITY" NUMBER(16,8),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"INV_ADJUST_REASON_NUM" NUMBER(18,0)
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1, 'DAY')) STORE IN ("ODS_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
