-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_LTC_HOA_TIME"
   (	"LTC_HOA_NUM" NUMBER(18,0),
	"HOA_TIME_SEQ" NUMBER(18,0),
	"TIME" VARCHAR2(16),
	"PRINT_POSITION" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"DOSAGE" NUMBER(18,3),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
