-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_IVR_ORDER_ITEM"
   (	"IVR_ORDER_ITEM_NUM" NUMBER(18,0),
	"IVR_ORDER_NUM" NUMBER(18,0),
	"RX_NUMBER" VARCHAR2(20),
	"IS_CALL_DOCTOR" CHAR(1),
	"IS_BAD_PICKUP_TIME" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"PROCESS_FLAG" CHAR(1) DEFAULT 'P',
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"IS_PAYING_PATIENT" CHAR(1),
	"FAX_JOB_ID" VARCHAR2(50),
	"WRITTEN_QTY" NUMBER(13,3),
	"DISPENSED_QTY" NUMBER(13,3),
	"DAYS_SUPPLY" NUMBER(18,0),
	"REFILL_QTY" NUMBER(13,3),
	"REFILLS_ALLOWED" NUMBER(18,0),
	"SYNC_DATE" DATE,
	"ITEM_SOURCE_TYPE_NUM" NUMBER(18,0),
	"CLINICAL_PROGRAM_NUM" NUMBER(18,0)
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
