-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_PRIVACY_RESTRICTION"
   (	"PATIENT_NUM" NUMBER(18,0),
	"ALLOW_CUSTOM_RPT_FLAG" CHAR(1) DEFAULT 'N',
	"IS_EMANCIPATED_MINOR" CHAR(1),
	"CREATE_USER" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"PRIVACY_LEVEL" CHAR(1),
	"IS_LETTER_ON_FILE" CHAR(1),
	"PROCESS_FLAG" CHAR(1) DEFAULT 'P',
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"RESTRICT_VACCINATION_REPORTING" CHAR(1),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PARTITION_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
