-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_IMH_PATIENT_MED_CONDITION"
   (	"IMH_PATIENT_MED_CONDITION_NUM" NUMBER(18,0),
	"IMH_MESSAGE_NUM" NUMBER(18,0),
	"PATIENT_MED_CONDITION_SEQ" NUMBER(18,0),
	"PATIENT_NUM" NUMBER(18,0),
	"IMH_STATUS" CHAR(1),
	"STATUS" VARCHAR2(10),
	"CREATE_DATE" DATE,
	"REPORTED_DATE" DATE,
	"DESCRIPTION" VARCHAR2(255),
	"CODE" VARCHAR2(10),
	"DAYS_DURATION" VARCHAR2(9),
	"ONSET_DATE" DATE,
	"DEACTIVATED_DATE" DATE,
	"SEVERITY" VARCHAR2(10),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID'),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0)
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
