-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_MAILORD_INCL_EXCL_RULE"
   (	"MAILORD_INCL_EXCL_RULE_NUM" NUMBER(18,0),
	"DATA_FILTER" CLOB,
	"MAILORD_INCL_EXCL_RULE_SET_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"IS_INCLUDE_RULE" CHAR(1),
	"PROCESS_ORDER" NUMBER(9,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("ODS_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
