-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_CREDIT_CARD_TYPE"
   (	"CREDIT_CARD_TYPE_NUM" NUMBER(18,0),
	"CARD_TYPE_DESC" VARCHAR2(100),
	"CARD_NUMBER_LENGTH" NUMBER(9,0),
	"CVV_NUMBER_LENGTH" NUMBER(9,0),
	"CARD_TYPE_STATUS" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"CARD_TYPE_DESC_ABBREVIATION" VARCHAR2(10),
	"PARTITION_DATE" DATE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
