-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_TP_MEDICAID_DRUG_ATTR_VAL"
   (	"TP_MEDICAID_DRUG_ATTR_VAL_NUM" NUMBER(18,0),
	"TP_MEDICAID_DRUG_NUM" NUMBER(18,0),
	"TP_MEDICAID_LOAD_NUM" NUMBER(18,0),
	"TP_MEDICAID_DRUG_ATTRIBUTE_NUM" NUMBER(18,0),
	"DP_VALUE" VARCHAR2(100),
	"OVERRIDE_VALUE" VARCHAR2(100),
	"OVERRIDE_PRE_EDIT_MESSAGE" VARCHAR2(255),
	"OVERRIDE_WARN_LEV" NUMBER(9,0),
	"OVERRIDE_DATA_FILTER_NAME" VARCHAR2(60),
	"OVERRIDE_DATA_FILTER" VARCHAR2(2000),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
