-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_EREFERRAL_ITEM"
   (	"EREFERRAL_ITEM_NUM" NUMBER(18,0),
	"EREFERRAL_ORDER_NUM" NUMBER(18,0),
	"PRODUCT_NUM" NUMBER(18,0),
	"PRODUCT_NAME" VARCHAR2(100),
	"RX_FILL_SEQ" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"IMAGE_GROUP_NUM" NUMBER(18,0),
	"HUB_RX_ID" VARCHAR2(100),
	"ORDER_STATUS" CHAR(1),
	"REASON" CHAR(1),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1, 'DAY')) STORE IN ("ODS_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
