-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_DT_PATIENT"
   (	"DT_TX_NUM" NUMBER(19,0),
	"FACILITY_NUM" NUMBER(18,0),
	"FIRST_NAME" VARCHAR2(30),
	"MIDDLE_INITIAL" VARCHAR2(30),
	"LAST_NAME" VARCHAR2(30),
	"GENDER_CODE" CHAR(1),
	"ADDRESS" VARCHAR2(100),
	"CITY" VARCHAR2(40),
	"STATE_CODE" CHAR(2),
	"ZIP_CODE" VARCHAR2(20),
	"PHONE" VARCHAR2(20),
	"DATE_OF_BIRTH" DATE,
	"PATIENT_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"PARTITION_KEY" NUMBER(18,0),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PARTNER_CODE" VARCHAR2(10),
	"PATIENT_ID" VARCHAR2(30)
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
