-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_DUR_CONFLICT_PEDIATRIC"
   (	"DUR_CONFLICT_NUM" NUMBER(18,0),
	"COMMENTARY" VARCHAR2(4000),
	"MAX_AGE_DAYS" NUMBER(9,0),
	"MIN_AGE_DAYS" NUMBER(9,0),
	"DESCRIPTION" VARCHAR2(255),
	"DRUG_CUSTOM_ID" VARCHAR2(15),
	"DRUG_DESC" VARCHAR2(50),
	"DRUG_ID" VARCHAR2(15),
	"ID" VARCHAR2(5),
	"SCREEN_MESSAGE" VARCHAR2(4000),
	"SEVERITY" VARCHAR2(5),
	"PATIENT_AGE" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
