-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_ACC_BALANCE"
   (	"ACC_BALANCE_NUM" NUMBER(18,0),
	"ACC_ACCT_NUM" NUMBER(18,0),
	"CURRENT_BALANCE" NUMBER(17,6),
	"UNPOSTED_BALANCE" NUMBER(17,6),
	"CLOSED_DATE" DATE,
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE,
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOCK_AVOIDANCE_BUCKET" NUMBER(18,0)
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
