-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_INVENTORY_COMMIT"
   (	"INVENTORY_COMMIT_NUM" NUMBER(18,0),
	"ORDER_NUM" NUMBER(18,0),
	"ITEM_SEQ" NUMBER(18,0),
	"LOCATION_GROUP_NUM" NUMBER(18,0),
	"INVENTORY_ITEM_NUM" NUMBER(18,0),
	"COMMIT_TYPE_NUM" NUMBER(18,0),
	"QUANTITY" NUMBER(16,8),
	"COMMENT_TEXT" VARCHAR2(255),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
