-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_BILL"
   (	"BILL_NUM" NUMBER(18,0),
	"STATUS" CHAR(1),
	"BILL_DATE" DATE,
	"DATE_OF_SERVICE" DATE,
	"DAYS_SUPPLY" NUMBER(9,3),
	"BILLING_QTY" NUMBER(13,3),
	"BILLING_DAYS" NUMBER(5,0),
	"CARRY_OVER_QTY" NUMBER(13,3),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"TYPE" CHAR(1),
	"AUTO_RETRY_LAST_ATTEMPT" DATE,
	"AUTO_RETRY_ATTEMPTS" NUMBER(9,0),
	"PREV_CLAIM_BILL_NUM" NUMBER(18,0),
	"ORIGINAL_CLAIM_BILL_NUM" NUMBER(18,0),
	"AUTO_RETRY_FIRST_ATTEMPT" DATE,
	"BILL_START_DATE" DATE,
	"BILL_END_DATE" DATE,
	"OVERRIDE_USER_NUM" NUMBER(18,0),
	"OVERRIDE_REASON" VARCHAR2(255),
	"OVERRIDE_CARRY_OVER" NUMBER(13,3),
	"OVERRIDE_BILLING_QUANTITY" NUMBER(13,3),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"CARRY_OVER_DAYS" NUMBER(9,0),
	"OVERRIDE_DAYS_SUPPLY" NUMBER(9,0),
	"OVERRIDE_CARRY_OVER_DAYS" NUMBER(9,0),
	"BILL_EVENT_SEQ_NUM" NUMBER(3,0)
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
