-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_EREFERRAL_ORDER"
   (	"EREFERRAL_ORDER_NUM" NUMBER(18,0),
	"EREFERRAL_ORDER_TYPE_NUM" NUMBER(18,0),
	"ELECTRONIC_ORDER_NUM" NUMBER(18,0),
	"INBOUND_MSG_QUEUE_NUM" NUMBER(18,0),
	"PATIENT_NUM" NUMBER(18,0),
	"PRESCRIBER_NUM" NUMBER(18,0),
	"PATIENT_NAME" VARCHAR2(65),
	"PRESCRIBER_NAME" VARCHAR2(65),
	"FACILITY_NUM" NUMBER(22,0),
	"HUB_ORDER_ID" VARCHAR2(18),
	"CORRELATION_ID" VARCHAR2(100),
	"PROGRAM_FAX_NUMBER" VARCHAR2(40),
	"SPECIALTY_PROGRAM_NAME" VARCHAR2(100),
	"SYS_USER" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"ORGANIZATION" VARCHAR2(20),
	"SPECIALTY_PROGRAM_TYPE" VARCHAR2(100),
	"SPECIALTY_PROGRAM_SUB_TYPE" VARCHAR2(100),
	"SPECIALTY_PROGRAM_NUM" NUMBER(18,0),
	"SPECIALTY_PROGRAM_GROUP_NUM" NUMBER(18,0)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
