-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_PAYMENT_GROUP"
   (	"PAYMENT_GROUP_NUM" NUMBER(18,0),
	"GROUP_HEALTH_CARD_TYPE" VARCHAR2(30),
	"PAYMENT_GROUP_AMOUNT_CALC" NUMBER(17,6),
	"PATIENT_PAY_AMOUNT_CALC" NUMBER(17,6),
	"CALCULATION_DTSTAMP" DATE,
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE DEFAULT sysdate,
	"PARTITION_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
