-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_PRIVACY_ACKNOWLEDGMENT"
   (	"PRIVACY_ACKNOWLEDGMENT_NUM" NUMBER(18,0),
	"PATIENT_NUM" NUMBER(18,0),
	"GOOD_FAITH_EFFORT_REASON_NUM" NUMBER(18,0),
	"PRIVACY_ACTION_DATE" DATE,
	"FACILITY_NUM" NUMBER(18,0),
	"DOC_VERSION_NUM" NUMBER(18,0),
	"ACTION_CODE" CHAR(1),
	"ACKNOWLEDGE_TYPE_CODE" CHAR(1),
	"ACKNOWLEDGING_PERSON_NAME" VARCHAR2(100),
	"SIGNATURE_IMAGE_NUM" NUMBER(18,0),
	"COMMENT_TEXT" VARCHAR2(1000),
	"CREATE_USER" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
