-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_PRODUCT_COMPOUND"
   (	"PRODUCT_COMPOUND_NUM" NUMBER(18,0),
	"COMPOUNDING_MINUTES" NUMBER(9,0),
	"IS_FILLED" CHAR(1),
	"PRESCRIPTION_QTY" NUMBER(16,8),
	"DISPENSING_UNIT" VARCHAR2(10),
	"RX_CLARIFICATION_CODE" VARCHAR2(10),
	"DOSAGE_FORM_CODE" VARCHAR2(2),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PROCESS_FLAG" CHAR(1) DEFAULT 'P',
	"PARTITION_DATE" DATE,
	"ROUTE_OF_ADMIN" VARCHAR2(25),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"COMPOUND_TYPE" VARCHAR2(2),
	"ROUTE_OF_ADMINISTRATION" VARCHAR2(11)
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
