-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_PPI_REGISTRY_ADDR_LINK"
   (	"PPI_REGISTRY_ADDR_LINK_NUM" NUMBER(18,0),
	"PPI_REGISTRY_ADDR_NUM" NUMBER(18,0),
	"PRESCRIBER_NUM" NUMBER(18,0),
	"PRESCRIBER_ADDRESS_NUM" NUMBER(18,0),
	"ACTIVE_START_DATE" DATE,
	"ACTIVE_END_DATE" DATE,
	"SERVICE_LEVEL" NUMBER(5,0),
	"LINK_TYPE" CHAR(1),
	"IS_PPI_ENABLED" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PPI_REGISTRY_ADDR_LL_NUM" NUMBER(18,0)
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
