-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_INVENTORY_SKU"
   (	"INVENTORY_SKU_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"SKU" VARCHAR2(20),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PARTITION_DATE" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"PRODUCT_NUM" NUMBER(18,0)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
