-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_PRESCRIBER_ID"
   (	"PRESCRIBER_ID_NUM" NUMBER(18,0),
	"ACTIVE_PRESCRIBER_ID_NUM" NUMBER(18,0),
	"PRESCRIBER_NUM" NUMBER(18,0),
	"CREATE_DATE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"ID_TYPE" VARCHAR2(20),
	"ID_TEXT" VARCHAR2(30),
	"ID_SUFFIX" VARCHAR2(20),
	"CTRY_CODE" VARCHAR2(8),
	"STATE_CODE" VARCHAR2(4),
	"STATUS" VARCHAR2(1),
	"EFFECTIVE_DATE" DATE,
	"EXPIRATION_DATE" DATE,
	"SOURCE_CODE" CHAR(1),
	"USE_FOR_BILLING" CHAR(1),
	"PROCESS_FLAG" CHAR(1) DEFAULT 'P',
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"ESV_PRESCRIBER_ID" VARCHAR2(50),
	"ESV_PRESCRIBER_ADDR_LOC_ID" VARCHAR2(10)
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
