-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_TP_MESSAGE"
   (	"TP_MESSAGE_NUM" NUMBER(18,0),
	"TP_ITEM_CLAIM_NUM" NUMBER(18,0),
	"TP_PROCESSOR_DESTINATION_SEQ" NUMBER(18,0),
	"TP_PROCESSOR_NUM" NUMBER(18,0),
	"TP_ADJ_DRIVER_CONFIG_NUM" NUMBER(18,0),
	"TP_BILLING_FORMAT_NUM" NUMBER(18,0),
	"MESSAGE_CATEGORY" CHAR(1),
	"REQUEST_MESSAGE" CLOB,
	"RESPONSE_MESSAGE" CLOB,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"SUBMISSION_DATE" DATE,
	"SUBMISSION_STATUS" VARCHAR2(20),
	"COMM_FAILURE" CHAR(1),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"TRANSACTION_STATUS" VARCHAR2(50),
	"PROCESS_FLAG" CHAR(1) DEFAULT 'P',
	"AUTHORIZATION_NUMBER" VARCHAR2(20),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"FINANCIAL_FEED_NUM" NUMBER(18,0),
	"HOSTBILL_COMMENTS" VARCHAR2(200),
	"ADJUDICATION_GROUP_NUM" NUMBER(18,0),
	"IS_BAR_TRANSACTION" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"SUBMISSION_TIMESTAMP" TIMESTAMP (6),
	"OUTBOUND_MSG_QUEUE_NUM" NUMBER(18,0)
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
