-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_ACC_PAYMENT_DETAIL"
   (	"ACC_PAYMENT_DETAIL_NUM" NUMBER(18,0),
	"ACC_ENTRY_NUM" NUMBER(18,0),
	"ACC_PAYMENT_NUM" NUMBER(18,0),
	"UNUSED_AMOUNT" NUMBER(17,6),
	"PAYMENT_APPLY_DISCOUNT" CHAR(1),
	"PAYMENT_DISCOUNT_MONEY" NUMBER(17,6),
	"PAYMENT_DISCOUNT_PERCENTAGE" NUMBER(17,6),
	"DESCRIPTION" VARCHAR2(1000),
	"BALANCE" NUMBER(17,6),
	"AMOUNT_DUE" NUMBER(17,6),
	"AMOUNT_DUE_DATE" DATE,
	"DISCOUNT_AMOUNT" NUMBER(17,6),
	"DISCOUNT_AMOUNT_DATE" DATE,
	"DISCOUNTED_AMOUNT_DUE" NUMBER(17,6),
	"MINIMUM_PAYMENT" NUMBER(17,6),
	"AMOUNT" NUMBER(17,6),
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE,
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
