-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_ACC_PREPAYMENT"
   (	"ACC_PREPAYMENT_NUM" NUMBER(18,0),
	"ACC_PREPAYMENT_LIST_NUM" NUMBER(18,0),
	"ACC_ACCT_NUM" NUMBER(18,0),
	"PAYER" VARCHAR2(200),
	"TX_DATE" DATE,
	"SERVICE_DATE" DATE,
	"PAYMENT_AMOUNT" NUMBER(17,6),
	"DISCOUNT_AMOUNT" NUMBER(17,6),
	"CHECK_DATE" DATE,
	"CHECK_ACCOUNT_NUMBER" VARCHAR2(20),
	"CHECK_NUMBER" VARCHAR2(20),
	"CHECK_ROUTING_NUMBER" VARCHAR2(20),
	"DESCRIPTION" VARCHAR2(4000),
	"NUM_UPDATES" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
