-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_PRICING_PROCESS_STEP"
   (	"PRICING_PROCESS_STEP_NUM" NUMBER(18,0),
	"PRICING_PROCESS_CONFIG_NUM" NUMBER(18,0),
	"PRICING_STEP_TYPE_NUM" NUMBER(9,0),
	"EXCLUDE_FROM_PRICE" CHAR(1),
	"PROCESS_ORDER" NUMBER(9,0),
	"PRICING_STEP_QUALIFIER" VARCHAR2(30),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
