-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ODS_INVENTORY_ITEM"
   (	"INVENTORY_ITEM_NUM" NUMBER(18,0),
	"PRODUCT_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"STAGING_BIN_TYPE_NUM" NUMBER(18,0),
	"STATUS" CHAR(1),
	"DATA_GROUP" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"EXCLUDE_FROM_RECOMMENDED_PO" CHAR(1),
	"LAST_ACQUISITION_COST" NUMBER(17,6),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"LAST_ACQUISITION_COST_DATE" DATE,
	"LAST_ACQUISITION_UNIT_COST" NUMBER(17,6),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"IS_AUTO_DISPENSED" CHAR(1),
	"MOVING_AVG_COST" NUMBER(17,6),
	"LAST_LEVEL_CHANGE_DATE" DATE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
