-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."PRICING_FORMULA_STG"
   (	"PRICING_FORMULA_CONFIG_NUM" NUMBER(18,0),
	"NAME" VARCHAR2(30),
	"CASH_TP_INDICATOR" CHAR(1),
	"PRICING_FORMULA_STEP_NUM" NUMBER(9,0),
	"PRICING_FORMULA_STEP_NAME" VARCHAR2(15),
	"PUBLISH_USER" NUMBER(18,0),
	"PUBLISH_STATUS" CHAR(1),
	"PUBLISH_DATE" DATE,
	"DATA_GROUP" NUMBER(18,0),
	"EFFECTIVE_DATE" DATE,
	"TERM_DATE" DATE,
	"DATESTAMP" DATE,
	"USE_PRICE_LINKING" CHAR(1),
	"USE_ALT_COST_DETERMINATION" CHAR(1),
	"COMPOUND_PRICING_OPTION" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100)
   ) ;
-- ==========================================
