-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."PRICING_FORMULA_TBL_ROLE_STG"
   (	"PRICING_TABLE_DETAIL_NUM" NUMBER,
	"FORMULA_CONFIG_NUM" NUMBER,
	"PROCESS_ORDER" NUMBER,
	"ROLE_TYPE" NUMBER,
	"ROLE_TYPE_DESCRIPTION" VARCHAR2(30),
	"SELECTION_RULE" NUMBER,
	"DATESTAMP" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100)
   ) ;
-- ==========================================
