-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."PRICING_HOTLIST_STG"
   (	"PRICING_HOTLIST_STG_NUM" NUMBER,
	"PRICING_HOTLIST_NUM" NUMBER(18,0),
	"NAME" VARCHAR2(30),
	"DATA_GROUP" NUMBER(18,0),
	"PH_EFFECTIVE_DATE" DATE,
	"PH_TERM_DATE" DATE,
	"PH_PUBLISH_STATUS" CHAR(1),
	"PH_PUBLISH_USER" NUMBER(18,0),
	"PH_PUBLISH_DATE" DATE,
	"DATESTAMP" DATE,
	"PRICING_HOTLIST_CONFIG_NUM" NUMBER(18,0),
	"IS_TOTAL_COST" CHAR(1),
	"IS_APPLY_DISCOUNTS" CHAR(1),
	"ADJUST_MASTER_PRODUCT_NUM" NUMBER(18,0),
	"ADJUST_COST_BASIS_NUM" NUMBER(18,0),
	"IS_AUTO_ADJUST_PRICES" CHAR(1),
	"PHC_EFFECTIVE_DATE" DATE,
	"PHC_TERM_DATE" DATE,
	"PHC_PUBLISH_STATUS" CHAR(1),
	"PHC_PUBLISH_USER" NUMBER(18,0),
	"PHC_PUBLISH_DATE" DATE,
	"EXTRACTION_METHOD" VARCHAR2(30),
	"DATA_FILTER" CLOB,
	"PRICING_HOTLIST_ITEM_NUM" NUMBER(18,0),
	"QUANTITY" NUMBER(16,8),
	"COST" NUMBER(17,6),
	"ERX_CLIENT_ID" VARCHAR2(100)
   ) ;
-- ==========================================
