-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."PRICING_LIST_ITEM_STG"
   (	"PRICING_LIST_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRICING_LIST_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"CASH_TP_IND" CHAR(1) NOT NULL ENABLE,
	"PRICING_FORMULA_NAME" VARCHAR2(30),
	"PRICING_FORMULA_NUM" NUMBER(18,0),
	"DEFAULT_PRICING_FORMULA_NUM" NUMBER(18,0),
	"DEFAULT_FORMULA_NAME" VARCHAR2(30),
	"CONFIG_EFFECTIVE_DATE" DATE NOT NULL ENABLE,
	"CONFIG_TERM_DATE" DATE,
	"DATA_FILTER" CLOB,
	"PUBLISH_STATUS" CHAR(1),
	"PUBLISH_USER" NUMBER,
	"PUBLISH_DATE" DATE,
	"PROCESS_ORDER" NUMBER(9,0),
	"INCL_EXCL_IND" CHAR(1),
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100)
   ) ;
-- ==========================================
