-- ==========================================

  CREATE GLOBAL TEMPORARY TABLE "TREXONE_ODS_DATA"."TEMP_ODS_PRODUCT_FACILITY"
   (	"DISPENSING_TEMPLATE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRODUCT_NUM" NUMBER(18,0) NOT NULL ENABLE
   ) ON COMMIT PRESERVE ROWS ;
-- ==========================================
