-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_TP_EOB_CODE"
   (	"TP_EOB_CODE_NUM" NUMBER(18,0),
	"TP_RULE_SET_NUM" NUMBER(18,0),
	"EOB_CODE" VARCHAR2(15),
	"CODE_TYPE" NUMBER(9,0),
	"DESCRIPTION" VARCHAR2(255),
	"IS_DOWNTIME_CODE" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"IS_DUPLICATE_CODE" CHAR(1),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
