-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_DOC_VERSION"
   (	"DOC_VERSION_NUM" NUMBER(18,0),
	"DOC_FORMAT_NUM" NUMBER(18,0),
	"VERSION" VARCHAR2(18),
	"LAYOUT_STREAM" BLOB,
	"MARSHALLING_TEMPLATE" CLOB,
	"STYLESHEET" CLOB,
	"CHECK_IN_DATE" DATE,
	"CHECK_OUT_DATE" DATE,
	"CHECK_OUT_USER" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
