-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_DT_DRUG"
   (	"DT_TX_NUM" NUMBER(19,0),
	"FACILITY_NUM" NUMBER(18,0),
	"PRODUCT" VARCHAR2(35),
	"MANUFACTURER" VARCHAR2(30),
	"NDC_MFG" CHAR(5),
	"NDC_PRODUCT" CHAR(4),
	"NDC_SIZE" CHAR(2),
	"DRUG_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"DISTRIBUTOR" VARCHAR2(30),
	"PARTITION_KEY" NUMBER(18,0),
	"PRODUCT_NUM" NUMBER(18,0),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
