-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_PPI_MESSAGE_DETAIL"
   (	"PPI_MESSAGE_NUM" NUMBER(18,0),
	"STORE_NAME" VARCHAR2(35),
	"PATIENT_LAST_NAME" VARCHAR2(35),
	"PATIENT_FIRST_NAME" VARCHAR2(35),
	"PATIENT_GENDER" CHAR(1),
	"PATIENT_DATE_OF_BIRTH" DATE,
	"MEDICATION_DESCRIPTION" VARCHAR2(105),
	"RX_REFERENCE_NUMBER" VARCHAR2(35),
	"PRESCRIBER_LAST_NAME" VARCHAR2(35),
	"PRESCRIBER_FIRST_NAME" VARCHAR2(35),
	"PRESCRIBER_CLINIC_NAME" VARCHAR2(35),
	"PRESCRIBER_SPECIALTY_QUAL" CHAR(3),
	"PRESCRIBER_SPECIALTY_CODE" CHAR(3),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"RESPONSE_TYPE" CHAR(1),
	"RESPONSE_REFILL_QUALIFIER" CHAR(3),
	"RESPONSE_REFILL_QTY" VARCHAR2(35),
	"RESPONSE_DENIED_CODE" CHAR(3),
	"RESPONSE_NOTE" VARCHAR2(70),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"PRESCRIBER_ORDER_NUM" VARCHAR2(35),
	"SUPERVISOR_LAST_NAME" VARCHAR2(35),
	"SUPERVISOR_FIRST_NAME" VARCHAR2(35),
	"SUPERVISOR_CLINIC_NAME" VARCHAR2(35),
	"SUPERVISOR_SPECIALITY_QUAL" CHAR(3),
	"SUPERVISOR_SPECIALITY_CODE" CHAR(3),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
