-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_TP_PLAN_LINK"
   (	"TP_PLAN_LINK_NUM" NUMBER(18,0),
	"TP_PLAN_NUM" NUMBER(18,0),
	"TP_NETWORK_NUM" NUMBER(18,0),
	"TP_BENEFIT_GROUP_SEQ" NUMBER(18,0),
	"GROUP_EXCLUDE" CHAR(1),
	"IS_ALL_FACILITY_LINK" CHAR(1),
	"NETWORK_EFFECTIVE_DATE" DATE,
	"NETWORK_TERMINATION_DATE" DATE,
	"PLAN_SETUP_CODE" VARCHAR2(12),
	"PUBLISH_STATUS" CHAR(1),
	"TP_BILLING_FORMAT_SET_NUM" NUMBER(18,0),
	"DATA_FILTER_NAME" VARCHAR2(60),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"LINK_TYPE" NUMBER(9,0),
	"EFFECTIVE_DATE" DATE,
	"TERMINATION_DATE" DATE,
	"PRECEDENCE" NUMBER(9,0),
	"TP_PLAN_DESTINATION_NUM" NUMBER(18,0),
	"TP_RULE_SET_NUM" NUMBER(18,0),
	"TP_PLAN_GENERAL_INFO_NUM" NUMBER(18,0),
	"PARENT_TP_PLAN_LINK" NUMBER(18,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"DATA_FILTER" CLOB,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"NCPDP_VERSION" VARCHAR2(2)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
