-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_SYSTEM_AUDIT"
   (	"SYSTEM_AUDIT_NUM" NUMBER(18,0),
	"USER_FACILITY_NUM" NUMBER(18,0),
	"FOR_FACILITY_NUM" NUMBER(18,0),
	"AUDIT_NAME" VARCHAR2(255),
	"AUDIT_USER" NUMBER(18,0),
	"START_TIME" DATE,
	"STOP_TIME" DATE,
	"COMMENT_TEXT" VARCHAR2(255),
	"RX_RECORD_NUM" NUMBER(18,0),
	"RX_FILL_SEQ" NUMBER(18,0),
	"TP_ITEM_CLAIM_NUM" NUMBER(18,0),
	"ADDITIONAL_PROPS" VARCHAR2(255),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
