-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_ACC_ACCT"
   (	"ACC_ACCT_NUM" NUMBER(18,0),
	"ACCT_NUMBER" VARCHAR2(20),
	"IS_DELETED" CHAR(1),
	"ACC_COST_CENTER_NUM" NUMBER(18,0),
	"ACC_ACCT_TYPE_NUM" NUMBER(18,0),
	"STATUS" CHAR(1),
	"ACC_BALANCE_NUM" NUMBER(18,0),
	"NAME" VARCHAR2(200),
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE,
	"STATUS_CHANGE_REASON" VARCHAR2(255),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
