-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_TP_WORKERS_COMP_APPROVAL"
   (	"TP_WORKERS_COMP_APPROVAL_NUM" NUMBER(18,0),
	"TP_WORKERS_COMP_CLAIM_NUM" NUMBER(18,0),
	"APPROVAL_NUMBER" VARCHAR2(30),
	"AUTHORIZED_BY" VARCHAR2(30),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"PARTITION_DATE" DATE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
