-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_PAYMENT_GROUP_LIST"
   (	"PAYMENT_GROUP_NUM" NUMBER(18,0),
	"PAYMENT_GROUP_SEQ" NUMBER(18,0),
	"PAYMENT_NUM" NUMBER(18,0),
	"PAYMENT_GROUP_LIST_AMOUNT" NUMBER(17,6),
	"APPLY_BALANCE_PERCENTAGE_RATE" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE,
	"PARTITION_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
