-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_DUR_CONFLICT_DRUG_ALLERGY"
   (	"DUR_CONFLICT_NUM" NUMBER(18,0),
	"ALLERGEN_CUSTOM_ID" VARCHAR2(15),
	"DRUG_ALLERGY_DESC" VARCHAR2(255),
	"DRUG_CUSTOM_ID" VARCHAR2(15),
	"DRUG_DESC" VARCHAR2(50),
	"DRUG_ID" VARCHAR2(15),
	"MATCH_DESC" VARCHAR2(100),
	"MATCH_TYPE" CHAR(5),
	"NON_ALLERGIC_RESPONSE" CHAR(1),
	"REACTION_DESC" VARCHAR2(255),
	"SCREEN_MESSAGE" VARCHAR2(4000),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
