-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_C1_DISCO_ITEM_TRIGGER"
   (	"C1_DISCO_ITEM_TRIGGER_NUM" NUMBER(18,0),
	"ITEM_NUMBER" VARCHAR2(6),
	"NDC_NUMBER" VARCHAR2(11),
	"LABEL_NAME" VARCHAR2(35),
	"FDB_PACKAGE_SIZE" NUMBER(11,0),
	"ITEM_COMMENT" VARCHAR2(30),
	"LOAD_DATE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"PRODUCT_NUM" NUMBER(18,0),
	"STORE_PACKAGE_SIZE" NUMBER(11,0),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
