-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_PATIENT_ID"
   (	"PATIENT_ID_NUM" NUMBER(18,0),
	"PATIENT_NUM" NUMBER(18,0),
	"PATIENT_ID_SOURCE_NUM" NUMBER(18,0),
	"PATIENT_ID" VARCHAR2(30),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"IS_DEFAULT" CHAR(1)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
