-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_POG_MEMBERSHIP_RULE"
   (	"POG_MEM_RULE_NUM" NUMBER(18,0),
	"PRODUCT_ORDERING_GROUP_NUM" NUMBER(18,0),
	"PRODUCT_NUM" NUMBER(18,0),
	"INCLUDE_EXCLUDE_FLAG" CHAR(1),
	"IS_DIRECT_INCLUSION" CHAR(1),
	"IS_PRIMARY_PRODUCT" CHAR(1),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"PARTITION_DATE" DATE,
	"H_TYPE" CHAR(1),
	"H_LEVEL" NUMBER(20,0),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
