-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_STORAGE_LOCATION"
   (	"LOCATION_GROUP_NUM" NUMBER(18,0),
	"INVENTORY_ITEM_NUM" NUMBER(18,0),
	"IS_ACTIVE" CHAR(1),
	"CURRENT_QTY" NUMBER(16,8),
	"DISPENSING_NAME" VARCHAR2(30),
	"DATA_GROUP" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
