-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_COST_BASIS_SOURCE_VALUE"
   (	"COST_BASIS_SOURCE_VALUE_NUM" NUMBER(18,0),
	"COST_BASIS_SOURCE_NUM" NUMBER(18,0),
	"EFFECTIVE_DATE" DATE,
	"TERMINATION_DATE" DATE,
	"COST" NUMBER(17,6),
	"NDC_NUMBER" VARCHAR2(11),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
