-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_SYSTEM_MESSAGE"
   (	"SYSTEM_MESSAGE_NUM" NUMBER(18,0),
	"TITLE" VARCHAR2(255),
	"MESSAGE" VARCHAR2(4000),
	"TYPE" VARCHAR2(30),
	"SUBJECT" VARCHAR2(50),
	"MESSAGE_LOCATION" CHAR(1),
	"EFFECTIVE_DATE" DATE,
	"EXPIRATION_DATE" DATE,
	"IS_ALERT" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ALERT_LEVEL" NUMBER(9,0),
	"MESSAGE_ORDER" NUMBER(9,0),
	"DATA_GROUP" NUMBER(18,0),
	"IS_FIRST" CHAR(1),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
