-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_ACCOUNT_MEMBER_CREDIT_CARD"
   (	"ACCOUNT_MEMBER_CREDIT_CARD_NUM" NUMBER(18,0),
	"ACCOUNT_MEMBER_NUM" NUMBER(18,0),
	"CREDIT_CARD_TYPE_NUM" NUMBER(18,0),
	"EXPIRATION_DATE" DATE,
	"LAST4_PAN" CHAR(4),
	"FIRST_NAME" VARCHAR2(30),
	"MIDDLE_NAME" VARCHAR2(30),
	"LAST_NAME" VARCHAR2(30),
	"CREDIT_CARD_STATUS_NUM" NUMBER(18,0),
	"CARD_NOTE" VARCHAR2(100),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"IS_ONE_TIME_CHARGE" CHAR(1),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"FIRST6_PAN" CHAR(6),
	"HEALTH_CARD_DESIGNATION" VARCHAR2(20),
	"HEALTH_CARD_DESIGNATION_DATE" DATE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_20110411"  VALUES LESS THAN (TO_DATE(' 2011-04-12 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ,
 PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
