-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_ALLERGY_STATUS_DETAIL"
   (	"PATIENT_NUM" NUMBER(18,0),
	"ALLERGEN_NUM" NUMBER(18,0),
	"ALLERGY_STATUS_SEQ" NUMBER(18,0),
	"NEW_STATUS" CHAR(1),
	"EFFECTIVE_DATE" DATE,
	"COMMENTARY" VARCHAR2(255),
	"CREATE_DATE" DATE,
	"CREATE_USER" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PROCESS_FLAG" CHAR(1) DEFAULT 'P',
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
