-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_D_PRESCRIBER_ID"
   (	"PRESCRIBER_NUM" NUMBER(18,0),
	"ID_NUM" NUMBER(18,0),
	"ACTIVE_ID_NUM" NUMBER(18,0),
	"SOURCE_NUM" NUMBER(18,0),
	"ID_TYPE" VARCHAR2(20),
	"ID_TEXT" VARCHAR2(30),
	"ID_SUFFIX" VARCHAR2(20),
	"CTRY_CODE" VARCHAR2(8),
	"STATE_CODE" VARCHAR2(4),
	"STATUS" VARCHAR2(1),
	"EFFECTIVE_DATE" DATE,
	"EXPIRATION_DATE" DATE,
	"NUM_UPDATES" NUMBER(18,0),
	"DATESTAMP" DATE,
	"SOURCE_CODE" CHAR(1),
	"USE_FOR_BILLING" CHAR(1),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
