-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_VENDOR_COST_BASIS"
   (	"VENDOR_COST_BASIS_NUM" NUMBER(18,0),
	"VENDOR_NUM" NUMBER(18,0),
	"COST_BASIS_NUM" NUMBER(18,0),
	"COST_BASIS_SOURCE_NUM" NUMBER(18,0),
	"IS_ACQUISITION_COST" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
