-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_PURCHASING_PLAN_ITEM"
   (	"PURCHASING_PLAN_ITEM_NUM" NUMBER(18,0),
	"PURCHASING_PLAN_NUM" NUMBER(18,0),
	"INVENTORY_ITEM_NUM" NUMBER(18,0),
	"OVERRIDE_MINIMUM_QTY" NUMBER(12,3),
	"OVERRIDE_MAXIMUM_QTY" NUMBER(12,3),
	"OVERRIDE_MIN_DAYS_SUPPLY" NUMBER(9,0),
	"OVERRIDE_MAX_DAYS_SUPPLY" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
