-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_ACC_DEFAULTS"
   (	"ACC_DEFAULTS_NUM" NUMBER(18,0),
	"CONTACT_NAME" VARCHAR2(255),
	"CONTACT_ADDITIONAL_INFO" VARCHAR2(2000),
	"REMIT_ADDITIONAL_INFO" VARCHAR2(2000),
	"REMIT_NAME" VARCHAR2(60),
	"ACC_COST_CENTER_NUM" NUMBER(18,0),
	"ACCT_NUM_DIGITS" NUMBER(2,0),
	"ACCT_START_NUM" VARCHAR2(20),
	"POSTING_MANUAL_METHOD" VARCHAR2(20),
	"INCLUDE_PENDING_TRANSACTIONS" CHAR(1),
	"POSTING_BEFORE_STMT_GEN" CHAR(1),
	"POSTING_BEFORE_CLOSING" CHAR(1),
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
