-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_SCHEDULED_PRESCRIBER"
   (	"SCHEDULED_PRESCRIBER_NUM" NUMBER(18,0),
	"PRESCRIBER_NUM" NUMBER(18,0),
	"CREATE_DATE" DATE,
	"IMPORTED_PRESCRIBER_NUM" NUMBER(18,0),
	"MAX_RESPONSE_DAYS" NUMBER(10,0),
	"RESPONSE_THRESHOLD_IN_DAYS" NUMBER(10,0),
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE,
	"SYS_USER" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
