-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_MEDICAL_CONDITION_XREF"
   (	"MEDICAL_CONDITION_NUM" NUMBER(18,0),
	"MEDICAL_CONDITION_REF_TYPE" CHAR(4),
	"CONDITION_REF_NUM_PREFIX" CHAR(1),
	"CONDITION_REF_NUM" VARCHAR2(20),
	"CONDITION_REF_NUM_SUFFIX" VARCHAR2(10),
	"FORMATTED_CONDITION_REF_NUM" VARCHAR2(45),
	"DESCRIPTION" VARCHAR2(255),
	"PATIENT_DESCRIPTION" VARCHAR2(60),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"INVALIDATED_DATE" DATE,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
