-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_ELECTRONIC_ORDER"
   (	"ELECTRONIC_ORDER_NUM" NUMBER(18,0),
	"DATE_RECVD" DATE,
	"ORDER_SOURCE_TYPE_NUM" NUMBER(18,0),
	"MSG_ID" VARCHAR2(120),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"ACCOUNT_MEMBER_CREDIT_CARD_NUM" NUMBER(18,0),
	"DELIVERY_METHOD_NUM" NUMBER(18,0),
	"EXPECTED_DELIVERY_DATE" DATE,
	"SHIPPING_ADDRESS_NUM" NUMBER(18,0),
	"SHIPPING_METHOD_NUM" NUMBER(18,0)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
