-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_PRESCRIBER_PHONE"
   (	"PRESCRIBER_PHONE_NUM" NUMBER(18,0),
	"PRESCRIBER_NUM" NUMBER(18,0),
	"STATUS" CHAR(1),
	"PHONE_TYPE" VARCHAR2(4),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"SOURCE_CODE" CHAR(1),
	"PROCESS_FLAG" CHAR(1) DEFAULT 'P',
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
