-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_PURGE_RX_RECS"
   (	"RX_RECORD_NUM" NUMBER(18,0),
	"RX_FILL_SEQ" NUMBER(18,0),
	"ORDER_NUM" NUMBER(18,0),
	"ITEM_SEQ" NUMBER(18,0),
	"H_LEVEL" NUMBER(20,0),
	"PARTITION_KEY" NUMBER(18,0),
	"AUD_DEL_FLG" CHAR(1),
	"EOD_DEL_FLG" CHAR(1),
	"DW_DEL_FLG" CHAR(1),
	"ODS_DEL_FLG" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PARTITION_DATE" DATE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
