-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_PURCHASE_ORDER_ITEM"
   (	"PURCHASE_ORDER_ITEM_NUM" NUMBER(18,0),
	"PURCHASE_ORDER_NUM" NUMBER(18,0),
	"ORDERED_VENDOR_ITEM_NUM" NUMBER(18,0),
	"SUBSTITUTED_VENDOR_ITEM_NUM" NUMBER(18,0),
	"CREATE_DATE" DATE,
	"RECEIVED_DATE" DATE,
	"ORDERED_QUANTITY" NUMBER(9,0),
	"RECEIVED_QUANTITY" NUMBER(9,0),
	"EXPECTED_ACQ_COST" NUMBER(17,6),
	"ACTUAL_ACQ_COST" NUMBER(17,6),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"PARTITION_DATE" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"LINE_NUMBER" NUMBER(9,0),
	"RCVNG_EXCPTN_STATUS_CODE" CHAR(1),
	"MODIFIED_AFTER_ORDERED" CHAR(1),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"FACILITY_NUM" NUMBER(18,0),
	"IS_SUBSTITUTION_ALLOWED" CHAR(1)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
