-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_STORE_CLOSING"
   (	"STORE_CLOSING_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"CLOSING_DATE" CHAR(8),
	"CLOSING_TIME" DATE,
	"THIRD_PARTY_TOTAL" NUMBER(18,6),
	"CLOSING_METHOD" CHAR(1),
	"AUDIT_TOTAL" NUMBER(18,6),
	"AUDIT_TIME" DATE,
	"EXTRACT_TOTAL" NUMBER(18,6),
	"EXTRACT_TIME" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
