-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_D_PRESCRIBER_PHONE"
   (	"PRESCRIBER_NUM" NUMBER(18,0),
	"PRESCRIBER_PHONE_NUM" NUMBER(18,0),
	"PHONE_LINK_NUM" NUMBER(18,0),
	"PHONE_NUM" NUMBER(18,0),
	"SOURCE" NUMBER(18,0),
	"PHONE_TYPE" VARCHAR2(4),
	"AREA_CODE" VARCHAR2(4),
	"PHONE_NUMBER" VARCHAR2(20),
	"EXT" VARCHAR2(6),
	"STATUS" VARCHAR2(1),
	"NUM_UPDATES" NUMBER(18,0),
	"LINK_NUM_UPDATES" NUMBER(18,0),
	"PHONE_NUM_UPDATES" NUMBER(18,0),
	"DATESTAMP" DATE,
	"SOURCE_CODE" CHAR(1),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
