-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_CC_TRANS_RESPONSE"
   (	"CC_TRANS_RESPONSE_NUM" NUMBER(18,0),
	"CC_TRANS_REQUEST_NUM" NUMBER(18,0),
	"CC_TRANS_STATUS_MSG" VARCHAR2(300),
	"CC_TRANS_STATUS_CODE" VARCHAR2(10),
	"CC_TRANS_TERMINATION_MESSAGE" VARCHAR2(200),
	"CC_TRANS_RESPONSE_MESSAGE" VARCHAR2(300),
	"CC_TRANS_AUTHORIZATION_CODE" VARCHAR2(20),
	"CC_TRANS_ROUTING_ID" VARCHAR2(20),
	"CC_TRANS_PAYMENT_MEDIA" VARCHAR2(20),
	"CC_TRANS_PAYMENT_TYPE" VARCHAR2(20),
	"CC_TRANS_AVS_CODE" VARCHAR2(30),
	"CC_TRANS_CVV_VALIDATION_CODE" VARCHAR2(30),
	"CC_TRANS_COMMERCIAL_CARD_TYPE" VARCHAR2(30),
	"CC_TRANS_CC_AMOUNT" NUMBER(17,6),
	"CC_TRANS_PROCESSOR_TRANS_NUM" VARCHAR2(30),
	"CC_TRANS_PROCESSOR_TRANS_DATE" VARCHAR2(30),
	"CC_TRANS_PROCESSOR_TRANS_TIME" VARCHAR2(30),
	"CC_TRANS_REFERENCE_NUM" VARCHAR2(100),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"PARTITION_DATE" DATE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_20110411"  VALUES LESS THAN (TO_DATE(' 2011-04-12 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ,
 PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
