-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_PRODUCT_IDENTIFIER"
   (	"PRODUCT_IDENTIFIER_NUM" NUMBER(18,0),
	"PRODUCT_NUM" NUMBER(18,0),
	"SOURCE" VARCHAR2(30),
	"DATE_OF_ADD" DATE,
	"IDENTIFIER" VARCHAR2(50),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"DATA_GROUP" NUMBER(18,0),
	"CODE" VARCHAR2(25),
	"SYS_USER" NUMBER(18,0)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
