-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_TP_BENEFIT_GROUP"
   (	"TP_PLAN_NUM" NUMBER(18,0),
	"TP_BENEFIT_GROUP_SEQ" NUMBER(18,0),
	"BENEFIT_GROUP_ID" VARCHAR2(15),
	"BENEFIT_GROUP_NAME" VARCHAR2(45),
	"COMMENT_TEXT" VARCHAR2(255),
	"EFFECTIVE_DATE" DATE,
	"TERMINATION_DATE" DATE,
	"ALLOW_CENTRAL_FILL" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"ALLOW_CENTRAL_MAIL" CHAR(1)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
