-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_WF_EXCEPTION"
   (	"WF_PROCESS_DEFINITION_NUM" NUMBER(18,0),
	"PROC_INST_SEQ" NUMBER(18,0),
	"NODE_SEQ" NUMBER(18,0),
	"NODE_INSTANCE_SEQ" NUMBER(18,0),
	"SHORT_MESSAGE" VARCHAR2(30),
	"LONG_MESSAGE" VARCHAR2(512),
	"STACK_TRACE" VARCHAR2(4000),
	"DATA_GROUP" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
