-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_DUR_CONFLICT_DUPL_DRUG"
   (	"DUR_CONFLICT_NUM" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"ALLOWANCE" NUMBER(9,0),
	"CLASS_DESC" VARCHAR2(255),
	"CLASS_ID" VARCHAR2(15),
	"DRUG_NAME" VARCHAR2(50),
	"NDC" VARCHAR2(20),
	"SCREEN_MESSAGE" VARCHAR2(4000),
	"FACILITY_NUM" NUMBER(18,0),
	"RX_FILL_SEQ" NUMBER(18,0),
	"PATIENT_EXTRA_MEDICATION_NUM" NUMBER(18,0),
	"IS_RXFILL" CHAR(1),
	"RX_DAYS_SUPPLY" NUMBER(9,0),
	"RX_DATE_LAST_FILLED" DATE,
	"RX_PICKUP_DATE" DATE,
	"RX_DATE_WRITTEN" DATE,
	"RX_IS_COMPOUND" CHAR(1),
	"RX_PRESCRIBER_NAME" VARCHAR2(100),
	"RX_PRESCRIBER_PHONE_NUM" VARCHAR2(30),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
