-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_TP_REJECT_CODE"
   (	"TP_REJECT_CODE_NUM" NUMBER(18,0),
	"REJECT_CODE" VARCHAR2(8),
	"MESSAGE" VARCHAR2(100),
	"IS_CUSTOM_CODE" CHAR(1),
	"IS_DOWNTIME_CODE" CHAR(1),
	"IS_DUPLICATE_CODE" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
