-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_IVR_ORDER"
   (	"IVR_ORDER_NUM" NUMBER(18,0),
	"ELECTRONIC_ORDER_NUM" NUMBER(18,0),
	"PICKUP_DATE" DATE,
	"LANGUAGE_NUM" NUMBER(18,0),
	"IS_SUBMIT_HANGUP" CHAR(1),
	"SUBMIT_DATE" DATE,
	"PICKUP_DATE_SRC" VARCHAR2(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"FACILITY_NUM" NUMBER(18,0),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"LOCALE_NUM" NUMBER(18,0),
	"IS_PROCESSED" CHAR(1),
	"TRANSFER_FACILITY_NUM" NUMBER(18,0),
	"DELIVERY_METHOD_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
