-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_CASH_ADDITIONAL_INFO"
   (	"CASH_ADDITIONAL_INFO_NUM" NUMBER(18,0),
	"ORDER_NUM" NUMBER(18,0),
	"ITEM_SEQ" NUMBER(18,0),
	"RX_ORIGINATION_NUM" NUMBER(18,0),
	"USER_DEF_1" VARCHAR2(100),
	"USER_DEF_2" VARCHAR2(100),
	"USER_DEF_3" VARCHAR2(100),
	"DATE_OF_SERVICE" DATE,
	"PATIENT_ALTERNATIVE_ID" VARCHAR2(20),
	"PRIOR_AUTHORIZATION_NUMBER" VARCHAR2(20),
	"PRIOR_AUTH_TYPE" NUMBER(9,0),
	"COUPON_NUMBER" VARCHAR2(15),
	"COUPON_TYPE" VARCHAR2(2),
	"COUPON_VALUE" NUMBER(17,6),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
