-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_SHIPPING_COURIER"
   (	"SHIPPING_COURIER_NUM" NUMBER(18,0),
	"COURIER_NAME" VARCHAR2(50),
	"IS_DEFAULT_COURIER" CHAR(1),
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"SHIPPING_PROCESSOR_NUM" NUMBER(18,0),
	"PARTITION_DATE" DATE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_20110411"  VALUES LESS THAN (TO_DATE(' 2011-04-12 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ,
 PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
