-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_PAYMENT_EXCEPTION"
   (	"PAYMENT_EXCEPTION_NUM" NUMBER(18,0),
	"CREDIT_CARD_PROCESSOR_NUM" NUMBER(18,0),
	"EXCEPTION_CODE" VARCHAR2(20),
	"EXCEPTION_CODE_DESCRIPTION" VARCHAR2(100),
	"EXCEPTION_TRANSACTION_TYPE" VARCHAR2(100),
	"EXCEPTION_TYPE" CHAR(1),
	"EXCEPTION_MESSAGE" VARCHAR2(200),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"EXCEPTION_TRANS_TYPE_FILTER" VARCHAR2(100),
	"EXCEPTION_MESSAGE_FILTER" VARCHAR2(200),
	"PARTITION_DATE" DATE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_20110411"  VALUES LESS THAN (TO_DATE(' 2011-04-12 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ,
 PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
