-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_VENDOR_CONFIGURATION"
   (	"VENDOR_CONFIGURATION_NUM" NUMBER(18,0),
	"ACCOUNT_NUMBER" VARCHAR2(16),
	"SENDER_ID" VARCHAR2(16),
	"RECEIVER_ID" VARCHAR2(16),
	"PURCHASE_ORDER_SORT_CODE" CHAR(1),
	"LEAD_TIME" NUMBER(9,0),
	"AUTO_TRANSMIT_PO_FLAG" CHAR(1),
	"DELIVERS_ON_SUNDAY" CHAR(1),
	"DELIVERS_ON_MONDAY" CHAR(1),
	"DELIVERS_ON_TUESDAY" CHAR(1),
	"DELIVERS_ON_WEDNESDAY" CHAR(1),
	"DELIVERS_ON_THURSDAY" CHAR(1),
	"DELIVERS_ON_FRIDAY" CHAR(1),
	"DELIVERS_ON_SATURDAY" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"VENDOR_NUM" NUMBER(18,0),
	"DATA_GROUP" NUMBER(18,0),
	"C2_PO_STATUS" CHAR(1),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"IS_340B" CHAR(1),
	"SINGLE_VENDOR_PO_OPTION" CHAR(1)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
