-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_SCHEDULE"
   (	"SCHEDULE_NUM" NUMBER(18,0),
	"SCHEDULE_LINK_NUM" NUMBER(18,0),
	"SCHEDULE_DATE" DATE,
	"DAY_OF_WEEK" NUMBER(2,0),
	"OPEN_TIME" NUMBER(2,0),
	"CLOSE_TIME" NUMBER(2,0),
	"DESCRIPTION" VARCHAR2(255),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
