-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_DELIVERY_ROUTE"
   (	"DELIVERY_ROUTE_NUM" NUMBER(18,0),
	"DELIVERY_ROUTE_ID" VARCHAR2(7),
	"DELIVERY_ROUTE_NAME" VARCHAR2(30),
	"DEPARTURE_TIME" NUMBER(4,0),
	"FACILITY_NUM" NUMBER(18,0),
	"IS_MONDAY" CHAR(1),
	"IS_TUESDAY" CHAR(1),
	"IS_WEDNESDAY" CHAR(1),
	"IS_THURSDAY" CHAR(1),
	"IS_FRIDAY" CHAR(1),
	"IS_SATURDAY" CHAR(1),
	"IS_SUNDAY" CHAR(1),
	"IS_ACTIVE" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
