-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_WF_BLOCK_DEFINITION"
   (	"WF_BLOCK_DEFINITION_NUM" NUMBER(18,0),
	"DESCRIPTION" VARCHAR2(60),
	"DATESTAMP" DATE,
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"APPLICATION_VERSION" VARCHAR2(8),
	"BLOCK_CODE" VARCHAR2(2),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"DISPLAY_DESCRIPTION" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
