-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_VENDOR_OVERRIDE"
   (	"PURCHASING_PLAN_ITEM_NUM" NUMBER(18,0),
	"VENDOR_NUM" NUMBER(18,0),
	"MINIMUM_QTY" NUMBER(12,3),
	"MAXIMUM_QTY" NUMBER(12,3),
	"MIN_DAYS_SUPPLY" NUMBER(9,0),
	"MAX_DAYS_SUPPLY" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"PARTITION_DATE" DATE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
