-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_ACC_TX"
   (	"ACC_TX_NUM" NUMBER(18,0),
	"SOURCE" VARCHAR2(200),
	"ACC_TX_TYPE_NUM" NUMBER(18,0),
	"IS_DELETED" CHAR(1),
	"ACC_COST_CENTER_NUM" NUMBER(18,0),
	"IS_CURRENT" CHAR(1),
	"CLOSED_DATE" DATE,
	"POST_DATE" DATE,
	"TX_DATE" DATE,
	"DESCRIPTION" VARCHAR2(4000),
	"REASON" VARCHAR2(200),
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE,
	"PARTITION_DATE" DATE,
	"TX_NUMBER" VARCHAR2(255),
	"EXTERNAL_REFERENCE" VARCHAR2(40),
	"ACC_RECURRING_TX_NUM" NUMBER(18,0),
	"SEPARATE_LINE_ITEM" CHAR(1),
	"TEMPLATE_TX_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
