-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_CVS_PRODUCT_XREF"
   (	"CVS_PRODUCT_XREF_NUM" NUMBER(18,0),
	"PRODUCT_NUM" NUMBER(18,0),
	"NDC" VARCHAR2(11),
	"GCN_SEQ_NUM" VARCHAR2(30),
	"STORE_PACKAGE_SIZE" NUMBER(16,8),
	"EFFECTIVE_DATE" DATE,
	"TERM_DATE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
