-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_PPI_CONTROL_MESSAGE"
   (	"PPI_MESSAGE_NUM" NUMBER(18,0),
	"CODE" CHAR(3),
	"DESCRIPTION_CODE" CHAR(3),
	"DESCRIPTION" VARCHAR2(70),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
