-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_ACC_ENTRY"
   (	"ACC_ENTRY_NUM" NUMBER(18,0),
	"ACC_TX_NUM" NUMBER(18,0),
	"ACC_ACCT_NUM" NUMBER(18,0),
	"AMOUNT" NUMBER(17,6),
	"SERVICE_DATE" DATE,
	"ACC_ACCT_ENTITY_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE,
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
