-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_INVENTORY_ITEM"
   (	"INVENTORY_ITEM_NUM" NUMBER(18,0),
	"PRODUCT_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"STAGING_BIN_TYPE_NUM" NUMBER(18,0),
	"STATUS" CHAR(1),
	"DATA_GROUP" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"EXCLUDE_FROM_RECOMMENDED_PO" CHAR(1),
	"LAST_ACQUISITION_COST" NUMBER(17,6),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"LAST_ACQUISITION_COST_DATE" DATE,
	"LAST_ACQUISITION_UNIT_COST" NUMBER(17,6),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"IS_AUTO_DISPENSED" CHAR(1)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
