-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_PRD_COST_BASIS_OVRD"
   (	"PRD_COST_BASIS_OVRD_NUM" NUMBER(18,0),
	"PRODUCT_COST_BASIS_NUM" NUMBER(18,0),
	"PRODUCT_NUM" NUMBER(18,0),
	"COST_BASIS_SOURCE_NUM" NUMBER(18,0),
	"COST_BASIS_NUM" NUMBER(18,0),
	"EFFECTIVE_DATE" DATE,
	"TERMINATION_DATE" DATE,
	"PERCENT_MODIFIER" NUMBER(17,6),
	"ADJUST_MODIFIER" NUMBER(17,6),
	"TEMP_OVERRIDE" CHAR(1),
	"IS_MANUALLY_MAINTAINED" CHAR(1),
	"ANOTHER_PRD_COST_BASIS_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
