-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_VENDOR_ITEM_RANK"
   (	"VENDOR_ITEM_RANK_NUM" NUMBER(18,0),
	"INVENTORY_ITEM_NUM" NUMBER(18,0),
	"VENDOR_NUM" NUMBER(18,0),
	"RANK" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
