-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_KEYSTORE_ENTRY"
   (	"KEYSTORE_ENTRY_NUM" NUMBER(18,0),
	"KEYSTORE_NUM" NUMBER(18,0),
	"KEYSTORE_ENTRY_NAME" VARCHAR2(100),
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE DEFAULT sysdate,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID'),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
