-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_PURCHASE_ORDER_ACK"
   (	"PURCHASE_ORDER_ACK_NUM" NUMBER(18,0),
	"VENDOR_NUM" NUMBER(18,0),
	"PURCHASE_ORDER_NUM" NUMBER(18,0),
	"DATE_RECEIVED" DATE,
	"ACKNOWLEDGEMENT_TYPE_CODE" CHAR(2),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
