-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_PRESCRIBER"
   (	"PRESCRIBER_NUM" NUMBER(18,0),
	"ACTIVE_PRESCRIBER_NUM" NUMBER(18,0),
	"STATUS" CHAR(1),
	"INACTIVITY_CODE" VARCHAR2(4),
	"PREF_GENERIC_IF_AVAIL" CHAR(1),
	"PREF_THERAPEUTIC_SUB" CHAR(1),
	"CONTACT_METHOD_NUM" NUMBER(18,0),
	"VALIDATED" CHAR(1),
	"CREATE_DATE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"ON_HOLD" CHAR(1),
	"SOURCE_CODE" CHAR(1),
	"ESV_MATCHED_IND" CHAR(1),
	"ESV_PRESCRIBER_ID" VARCHAR2(50),
	"SUPV_PRESCRIBER_NUM" NUMBER(18,0),
	"INTERNALLY_VALIDATED" CHAR(1),
	"PROCESS_FLAG" CHAR(1) DEFAULT 'P',
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"NEEDS_REFRESHED" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
