-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_OUTBOUND_EMAIL_ORDER_ITEM"
   (	"OUTBOUND_EMAIL_ORDER_ITEM_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"PATIENT_NUM" NUMBER(18,0),
	"ORDER_NUM" NUMBER(18,0),
	"RX_NUM" NUMBER(18,0),
	"ITEM_NUM" NUMBER(18,0),
	"ITEM_QTY" NUMBER(18,0),
	"ITEM_PRICE" NUMBER(18,4),
	"ITEM_TAX" NUMBER(18,4),
	"NUM_REFILLS" NUMBER(18,0),
	"DAYS_SUPPLY" NUMBER(18,0),
	"ITEM_NAME" VARCHAR2(50),
	"STATUS" VARCHAR2(12),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"COMMUNICATION_DATE" DATE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
