-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_ACC_ACCT_ENTITY"
   (	"ACC_ACCT_ENTITY_NUM" NUMBER(18,0),
	"ACC_PERSON_NUM" NUMBER(18,0),
	"ACC_INSTITUTION_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
