-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_SHIPMENT"
   (	"SHIPMENT_NUM" NUMBER(18,0),
	"ORDER_NUM" NUMBER(18,0),
	"SHIPPING_METHOD_NUM" NUMBER(18,0),
	"SHIPPING_ADDRESS_NUM" NUMBER(18,0),
	"SHIPMENT_SIGNATURE_NUM" NUMBER(18,0),
	"EXPECTED_MAIL_DELIVERY_DATE" DATE,
	"SHIPPING_STATUS_NUM" NUMBER(18,0),
	"NUMBER_OF_PACKAGES" NUMBER(9,0),
	"DEA_CLASS" CHAR(1),
	"REFRIGERATION" CHAR(1),
	"SHIP_HANDLE_FEE" NUMBER(17,6),
	"SHIP_DATE" DATE,
	"WEIGHT" NUMBER(16,8),
	"WEIGHT_UNITS" VARCHAR2(10),
	"DELIVERY_METHOD_NUM" NUMBER(18,0),
	"TRACKING_NUMBER" VARCHAR2(30),
	"SPECIAL_INSTRUCTIONS" VARCHAR2(300),
	"COURIER_SHIPPING_CHARGE" NUMBER(17,6),
	"COURIER_SHIPMENT_MESSAGE" VARCHAR2(100),
	"ORIGINAL_SHIP_DATE" DATE,
	"ORIGINAL_EXP_MAIL_DELIVERY_DT" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"IS_SHIPPING_COMPLETE" CHAR(1),
	"PAYMENT_GROUP_NUM" NUMBER(18,0)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_20110411"  VALUES LESS THAN (TO_DATE(' 2011-04-12 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ,
 PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
