-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_INVENTORY_GROUP"
   (	"INVENTORY_GROUP_NUM" NUMBER(18,0),
	"GROUP_NUM" NUMBER(18,0),
	"INVENTORY_ITEM_NUM" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER(20,0),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
