-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_DUR_CONFLICT_LACTATION"
   (	"DUR_CONFLICT_NUM" NUMBER(18,0),
	"COMMENTARY" VARCHAR2(4000),
	"DESCRIPTION" VARCHAR2(255),
	"DRUG_CUSTOM_ID" VARCHAR2(15),
	"DRUG_DESC" VARCHAR2(50),
	"DRUG_ID" VARCHAR2(15),
	"EXCRETION_EFFECT_CODE" CHAR(5),
	"ID" VARCHAR2(15),
	"EFFECT_CODE" CHAR(5),
	"SCREEN_MESSAGE" VARCHAR2(4000),
	"SEVERITY" CHAR(5),
	"PATIENT_AGE" NUMBER(9,0),
	"LACTATION_REPORTED_DATE" DATE,
	"PREGNANCY_REPORTED_DATE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
