-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_VENDOR"
   (	"VENDOR_NUM" NUMBER(18,0),
	"VENDOR_NAME" VARCHAR2(30),
	"IS_ACTIVE" CHAR(1),
	"DATA_GROUP" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PRIORITY" NUMBER(18,0),
	"DEFAULT_ITEM_PRIORITY" NUMBER(18,0),
	"MAIN_ADDRESS_SEQ" NUMBER(18,0),
	"DISCOUNT_DAY_OF_MONTH" NUMBER(9,0),
	"FACTOR_OFF_RETAIL_PRICE" NUMBER(16,8),
	"DISCOUNT_NET_DAYS" NUMBER(9,0),
	"ACCOUNT_NUMBER" VARCHAR2(16),
	"DESTINATION_NUM" NUMBER(18,0),
	"RECEIVER_ID" VARCHAR2(16),
	"FIXED_AMOUNT_DISCOUNT" NUMBER(16,8),
	"PERCENTAGE_DISCOUNT" NUMBER(16,8),
	"DISCOUNT_NET_DAYS_TYPE" CHAR(1),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"EDI_FIELD_SEPARATOR" CHAR(1),
	"EDI_RECORD_SEPARATOR" CHAR(1),
	"EDI_CONTROL_NUMBER" VARCHAR2(15),
	"VENDOR_COMM_METHOD_NUM" NUMBER(18,0),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"IS_MCK_CONNECT_ENABLED" CHAR(1)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
