-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_TP_STANDARD_CODE"
   (	"TP_STANDARD_CODE_NUM" NUMBER(18,0),
	"FIELD_ID" NUMBER(9,0),
	"CODE" VARCHAR2(4),
	"DESCRIPTION" VARCHAR2(100),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
