-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_DUR_CONFLICT_ERROR"
   (	"DUR_CONFLICT_NUM" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"DRUG_NAME" VARCHAR2(50),
	"MESSAGE" VARCHAR2(1023),
	"DRUG_RX_RECORD_NUM" NUMBER(18,0),
	"NDC" VARCHAR2(20),
	"FACILITY_NUM" NUMBER(18,0),
	"RX_FILL_SEQ" NUMBER(18,0),
	"PATIENT_EXTRA_MEDICATION_NUM" NUMBER(18,0),
	"IS_RXFILL" CHAR(1),
	"RX_DAYS_SUPPLY" NUMBER(9,0),
	"DATE_OF_SERVICE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"RX_NUMBER" VARCHAR2(20),
	"PRODUCT_NAME" VARCHAR2(50),
	"PRODUCT_ID_TYPE" NUMBER(9,0),
	"IS_PROFILE_PRODUCT" CHAR(1),
	"UNKNOWN_ID" VARCHAR2(25),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
