-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_CSR_RXFILL_COMPOUND_DETAIL"
   (	"CSR_RXFILL_EXTRACT_NUM" NUMBER(20,0),
	"INGREDIENT_NDC_ID" VARCHAR2(15),
	"INGREDIENT_QUANTITY" NUMBER(14,3),
	"INGREDIENT_UNITS_CODE" NUMBER(2,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
