-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_IVR_ORDER_ITEM"
   (	"IVR_ORDER_ITEM_NUM" NUMBER(18,0),
	"IVR_ORDER_NUM" NUMBER(18,0),
	"RX_NUMBER" VARCHAR2(20),
	"IS_CALL_DOCTOR" CHAR(1),
	"IS_BAD_PICKUP_TIME" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"PROCESS_FLAG" CHAR(1) DEFAULT 'P',
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
