-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_DT_THIRD_PARTY"
   (	"DT_TX_NUM" NUMBER(19,0),
	"FACILITY_NUM" NUMBER(18,0),
	"NAME" VARCHAR2(35),
	"CARDHOLDER_ID" VARCHAR2(30),
	"GROUP_NUMBER" VARCHAR2(30),
	"BANK_ID_NUMBER" VARCHAR2(6),
	"PERSON_CODE" VARCHAR2(3),
	"TP_PATIENT_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"PARTITION_KEY" NUMBER(18,0),
	"TP_RANK" NUMBER(9,0),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
