-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_VENDOR_INVENTORY_CONTACT"
   (	"VENDOR_INVENTORY_CONTACT_NUM" NUMBER(18,0),
	"VENDOR_NUM" NUMBER(18,0),
	"NAME" VARCHAR2(80),
	"EMAIL" VARCHAR2(255),
	"DATA_GROUP" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
