-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_PRICING_TABLE"
   (	"PRICING_TABLE_NUM" NUMBER(18,0),
	"NAME" VARCHAR2(30),
	"DESCRIPTION" VARCHAR2(45),
	"EFFECTIVE_DATE" DATE,
	"TERM_DATE" DATE,
	"PRICING_STEP_TYPE_NUM" NUMBER(9,0),
	"CASH_TP_INDICATOR" CHAR(1),
	"PUBLISH_STATUS" CHAR(1),
	"PUBLISH_USER" NUMBER(18,0),
	"PUBLISH_DATE" DATE,
	"DATA_GROUP" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
