-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_URL_LINK"
   (	"URL_LINK_NUM" NUMBER(18,0),
	"OWNER" NUMBER(18,0),
	"OWNER_TYPE_CODE" CHAR(1),
	"USAGE" NUMBER(18,0),
	"URL_NUM" NUMBER(18,0),
	"URL_USAGE" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"NOTIFY_PATIENT" CHAR(1)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
