-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_TP_PLAN_GENERAL_INFO"
   (	"TP_PLAN_GENERAL_INFO_NUM" NUMBER(18,0),
	"CONTACT_NAME" VARCHAR2(40),
	"INACTIVITY_DEACTIVATION_PERIOD" NUMBER(9,0),
	"FACILITY_PLAN_NUM" VARCHAR2(20),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
