-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_PRINT_DEVICE_TYPE"
   (	"PRINT_DEVICE_TYPE_NUM" NUMBER(18,0),
	"NAME" VARCHAR2(30),
	"DESCRIPTION" VARCHAR2(256),
	"IS_COLOR_CAPABLE" CHAR(1),
	"IS_DUPLEX_CAPABLE" CHAR(1),
	"IS_DEFAULT" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"LANGUAGE" VARCHAR2(10),
	"FONTS" VARCHAR2(2048),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"DATA_GROUP" NUMBER(18,0)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
