-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_PRIVACY_RESTRICTION"
   (	"PATIENT_NUM" NUMBER(18,0),
	"ALLOW_CUSTOM_RPT_FLAG" CHAR(1) DEFAULT 'N',
	"IS_EMANCIPATED_MINOR" CHAR(1),
	"CREATE_USER" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"FACILITY_NUM" NUMBER(18,0),
	"PRIVACY_LEVEL" CHAR(1),
	"IS_LETTER_ON_FILE" CHAR(1),
	"PROCESS_FLAG" CHAR(1) DEFAULT 'P',
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
