-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_IMH_DISPENSE"
   (	"IMH_DISPENSE_NUM" NUMBER(18,0),
	"IMH_MESSAGE_NUM" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"IMH_STATUS" CHAR(1),
	"RX_SIG" VARCHAR2(2000),
	"FILL_NUMBER" NUMBER(18,0),
	"DISPENSE_DATE" DATE,
	"DISPENSE_QTY" NUMBER(13,3),
	"DISPENSE_UNIT" VARCHAR2(20),
	"DISPENSE_FORM" VARCHAR2(40),
	"RX_NUMBER" VARCHAR2(20),
	"REFILLS_REMAINING" NUMBER(9,0),
	"PRESCRIBER_NAME" VARCHAR2(120),
	"PRESCRIBER_NUMBER" VARCHAR2(30),
	"PRODUCT_STRENGTH" VARCHAR2(30),
	"PRODUCT_STRENGTH_UNIT" VARCHAR2(30),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_DATE" DATE,
	"PARTITION_KEY" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID'),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"PRODUCT_NAME" VARCHAR2(200),
	"DRUG_CODING_SYSTEM_NAME" VARCHAR2(5),
	"DRUG_CODING_SYSTEM_ID" VARCHAR2(20)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
