-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_CSR_RXFILL_TP_DETAIL"
   (	"CSR_RXFILL_EXTRACT_NUM" NUMBER(20,0),
	"TP_PLAN_NUM" NUMBER(18,0),
	"TP_PLAN_CODE" VARCHAR2(12),
	"TP_PLAN_NAME" VARCHAR2(45),
	"TP_PLAN_TYPE" VARCHAR2(10),
	"TP_PLAN_COVERAGE" VARCHAR2(2),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"NUM_UPDATES" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER(20,0),
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"BILLING_ORDER" NUMBER(2,0)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
