-- ==========================================

  CREATE TABLE "TREXONE_ODS_DATA"."ZBK_CODE_LIST_ITEM"
   (	"CODE_LIST_ITEM_NUM" NUMBER(18,0),
	"CODE_LIST_NUM" NUMBER(18,0),
	"CODE_NUM" NUMBER(18,0),
	"IS_EDITABLE" CHAR(1),
	"EXCLUDE" CHAR(1),
	"DATA_GROUP" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100)
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
