-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ACC_STMT_SUMMARY"
   (	"ACC_STMT_SUMMARY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACC_COST_CENTER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"STATEMENT_DATE" DATE NOT NULL ENABLE,
	"STATEMENT_COUNT" NUMBER(10,0),
	"TOTAL_AMOUNT_DUE" NUMBER(20,2),
	"TOTAL_DEBITS" NUMBER(20,2),
	"TOTAL_DISCOUNTS" NUMBER(20,2),
	"TOTAL_SALES_TAX" NUMBER(20,2),
	"TOTAL_FINANCE_CHARGES" NUMBER(20,2),
	"TOTAL_CREDITS" NUMBER(20,2),
	"TOTAL_CURRENT_CHARGES" NUMBER(20,2),
	"BUCKET_1_30_BALANCE" NUMBER(20,2),
	"BUCKET_31_60_BALANCE" NUMBER(20,2),
	"BUCKET_61_90_BALANCE" NUMBER(20,2),
	"BUCKET_91_OVER_BALANCE" NUMBER(20,2),
	"TOTAL_BALANCE" NUMBER(20,2),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_ACC_STMT_SUMMARY" PRIMARY KEY ("ACC_STMT_SUMMARY_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "UC_ACC_STMT_SUMMARY_01" UNIQUE ("STATEMENT_DATE", "ACC_COST_CENTER_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_ACC_COST_CENTER_04" FOREIGN KEY ("ACC_COST_CENTER_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_COST_CENTER" ("ACC_COST_CENTER_NUM") ENABLE
   ) ;
-- ==========================================
