-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ACC_ENTRY_PAYMENT_DETAIL"
   (	"ACC_ENTRY_PAYMENT_DETAIL_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"AMOUNT" NUMBER(17,6) NOT NULL ENABLE,
	"ACC_ENTRY_NUM_PAID" NUMBER(18,0) NOT NULL ENABLE,
	"ACC_ENTRY_NUM_PAYMENT" NUMBER(18,0) NOT NULL ENABLE,
	"ACC_PAYMENT_DETAIL_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_ACC_ENTRY_PAYMENT_DETAIL" PRIMARY KEY ("ACC_ENTRY_PAYMENT_DETAIL_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_ACC_ENTRY_02" FOREIGN KEY ("ACC_ENTRY_NUM_PAID")
	  REFERENCES "TREXONE_DATA"."ACC_ENTRY" ("ACC_ENTRY_NUM") ENABLE,
	 CONSTRAINT "FK_ACC_ENTRY_03" FOREIGN KEY ("ACC_ENTRY_NUM_PAYMENT")
	  REFERENCES "TREXONE_DATA"."ACC_ENTRY" ("ACC_ENTRY_NUM") ENABLE,
	 CONSTRAINT "FK_ACC_PAYMENT_DETAIL_01" FOREIGN KEY ("ACC_PAYMENT_DETAIL_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_PAYMENT_DETAIL" ("ACC_PAYMENT_DETAIL_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
