-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ACC_AR_ACCT_TYPE"
   (	"ACC_AR_ACCT_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(50),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_ACC_AR_ACCT_TYPE" PRIMARY KEY ("ACC_AR_ACCT_TYPE_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
