-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ACC_ENTRY"
   (	"ACC_ENTRY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACC_TX_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACC_ACCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"AMOUNT" NUMBER(17,6),
	"SERVICE_DATE" DATE,
	"ACC_ACCT_ENTITY_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"STATUS" CHAR(1) DEFAULT 'U' NOT NULL ENABLE,
	 CONSTRAINT "PK_ACC_ENTRY" PRIMARY KEY ("ACC_ENTRY_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "UC_ACC_ENTRY_01" CHECK (STATUS in ('U','P','B')) ENABLE,
	 CONSTRAINT "FK_ACC_ACCOUNT_02" FOREIGN KEY ("ACC_ACCT_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_ACCT" ("ACC_ACCT_NUM") ENABLE,
	 CONSTRAINT "FK_ACC_ACCT_ENTITY_04" FOREIGN KEY ("ACC_ACCT_ENTITY_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_ACCT_ENTITY" ("ACC_ACCT_ENTITY_NUM") ENABLE,
	 CONSTRAINT "FK_ACC_TX_01" FOREIGN KEY ("ACC_TX_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_TX" ("ACC_TX_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
