-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ACC_COST_CENTER"
   (	"ACC_COST_CENTER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_ACC_COST_CENTER" PRIMARY KEY ("ACC_COST_CENTER_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
