-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ACC_ITEM"
   (	"ACC_ENTRY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACC_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CHARGE_TYPE_DESCRIPTION" VARCHAR2(200),
	"AMOUNT" NUMBER(17,6),
	"DESCRIPTION" VARCHAR2(200),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_ACC_ITEM" PRIMARY KEY ("ACC_ITEM_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_ACC_ENTRY_04" FOREIGN KEY ("ACC_ENTRY_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_ENTRY" ("ACC_ENTRY_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
