-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ACC_PAYMENT"
   (	"ACC_PAYMENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACC_PAYMENT_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACC_TX_NUM" NUMBER(18,0),
	"CARD_HOLDER" VARCHAR2(200),
	"DEBIT_INSTITUTION" VARCHAR2(200),
	"CHECK_NAME" VARCHAR2(200),
	"CHECK_DATE" DATE,
	"CHECK_NUMBER" VARCHAR2(20),
	"CHECK_ROUTING_NUMBER" VARCHAR2(20),
	"CHECK_ACCOUNT_NUMBER" VARCHAR2(20),
	"COUPON_TYPE" VARCHAR2(20),
	"COUPON_NAME" VARCHAR2(20),
	"COUPON_EXPIRATION" DATE,
	"GIFT_CARD_NUMBER" VARCHAR2(20),
	"CREDIT_CARD_TYPE" VARCHAR2(20),
	"VOUCHER_TYPE" VARCHAR2(20),
	"VOUCHER_NUMBER" VARCHAR2(20),
	"VOUCHER_EXPIRATION" DATE,
	"PAYER" VARCHAR2(200),
	"AMOUNT_PAID" NUMBER(17,6),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"AUTHORIZATION_NUMBER" VARCHAR2(20),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_ACC_PAYMENT" PRIMARY KEY ("ACC_PAYMENT_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_ACC_PAYMENT_TYPE_01" FOREIGN KEY ("ACC_PAYMENT_TYPE_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_PAYMENT_TYPE" ("ACC_PAYMENT_TYPE_NUM") ENABLE,
	 CONSTRAINT "FK_ACC_TX_02" FOREIGN KEY ("ACC_TX_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_TX" ("ACC_TX_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
