-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ACC_RECURRING_TX"
   (	"ACC_RECURRING_TX_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACC_TX_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FREQUENCY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"LAST_SCHEDULE_CHECK" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_ACC_RECURRING_TX" PRIMARY KEY ("ACC_RECURRING_TX_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_FREQUENCY_03" FOREIGN KEY ("FREQUENCY_NUM")
	  REFERENCES "TREXONE_DATA"."FREQUENCY" ("FREQUENCY_NUM") ENABLE,
	 CONSTRAINT "FK_ACC_TX_06" FOREIGN KEY ("ACC_TX_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_TX" ("ACC_TX_NUM") ENABLE
   ) ;
-- ==========================================
