-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ACC_ACCT_HOLDER"
   (	"ACC_ACCT_HOLDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACC_ACCT_ENTITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACC_AR_ACCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_ACC_ACCT_HOLDER" PRIMARY KEY ("ACC_ACCT_HOLDER_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_ACC_ACCOUNT_ENTITY_01" FOREIGN KEY ("ACC_ACCT_ENTITY_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_ACCT_ENTITY" ("ACC_ACCT_ENTITY_NUM") ENABLE,
	 CONSTRAINT "FK_ACC_STATEMENT_ACCOUNT_04" FOREIGN KEY ("ACC_AR_ACCT_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_AR_ACCT" ("ACC_AR_ACCT_NUM") ENABLE
   ) ;
-- ==========================================
