-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ACC_CHARGE_TYPE"
   (	"NAME" VARCHAR2(30) NOT NULL ENABLE,
	"AMOUNT" NUMBER(17,6),
	"DESCRIPTION" VARCHAR2(200),
	"ACC_CHARGE_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACC_DEFAULTS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_ACC_CHARGE_TYPE" PRIMARY KEY ("ACC_CHARGE_TYPE_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_ACC_DEFAULTS_02" FOREIGN KEY ("ACC_DEFAULTS_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_DEFAULTS" ("ACC_DEFAULTS_NUM") ENABLE
   ) ;
-- ==========================================
