-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ACC_BALANCE"
   (	"ACC_BALANCE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACC_ACCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CURRENT_BALANCE" NUMBER(17,6) NOT NULL ENABLE,
	"UNPOSTED_BALANCE" NUMBER(17,6) NOT NULL ENABLE,
	"CLOSED_DATE" DATE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"LOCK_AVOIDANCE_BUCKET" NUMBER(18,0) DEFAULT 0 NOT NULL ENABLE,
	 CONSTRAINT "FK_ACC_ACCOUNT_01" FOREIGN KEY ("ACC_ACCT_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_ACCT" ("ACC_ACCT_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_ACC_BALANCE" ON "TREXONE_DATA"."ACC_BALANCE" ("ACC_BALANCE_NUM", "LOCK_AVOIDANCE_BUCKET")
  ;
ALTER TABLE "TREXONE_DATA"."ACC_BALANCE" ADD CONSTRAINT "PK_ACC_BALANCE" PRIMARY KEY ("ACC_BALANCE_NUM", "LOCK_AVOIDANCE_BUCKET")
  USING INDEX "TREXONE_DATA"."PK_ACC_BALANCE"  ENABLE;
-- ==========================================
