-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ACC_AR_OTHER_AMOUNT"
   (	"ACC_AR_OTHER_AMOUNT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(200),
	"TYPE" CHAR(1) NOT NULL ENABLE,
	"VALUE" NUMBER(17,6) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_ACC_AR_OTHER_AMOUNT" PRIMARY KEY ("ACC_AR_OTHER_AMOUNT_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
