-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ACC_STATEMENT"
   (	"ACC_STATEMENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACC_AR_ACCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"BALANCE_AMOUNT" NUMBER(17,6) NOT NULL ENABLE,
	"IS_PAID" CHAR(1) NOT NULL ENABLE,
	"GENERATION_DATE" DATE,
	"DUE_DATE" DATE,
	"DISCOUNT_DUE_DATE" DATE,
	"UNPAID_AMOUNT" NUMBER(17,6),
	"MINIMUM_AMOUNT" NUMBER(17,6),
	"DISCOUNT_AMOUNT" NUMBER(17,6),
	"PAYMENT_TERMS_DAYS" NUMBER(18,0),
	"PAYMENT_APPLY_DISCOUNT" CHAR(1),
	"PAYMENT_DISCOUNT_DAYS" NUMBER(18,0),
	"PAYMENT_DISCOUNT_PERCENTAGE" NUMBER(24,6),
	"PAYMENT_DISCOUNT_MONEY" NUMBER(24,6),
	"APPLY_FINANCE_CHARGES" CHAR(1),
	"APPLY_FINANCE_CHARGES_DAYS" NUMBER(18,0),
	"APPLY_FINANCE_CHARGES_BAL" NUMBER(24,6),
	"FINANCE_CHARGE_PERCENTAGE" NUMBER(17,6),
	"FINANCE_CHARGE_MONEY" NUMBER(17,6),
	"FINANCE_CHARGE_PERIOD" CHAR(1),
	"MESSAGES" VARCHAR2(4000),
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"STATEMENT_DATE" DATE,
	"DUNNING_MESSAGES" VARCHAR2(4000),
	"ACC_TX_NUM" NUMBER(18,0),
	"CURRENT_AMOUNT" NUMBER(17,6),
	"ACC_STATEMENT_ADDRESS_NUM" NUMBER(18,0),
	"PRINT_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"CURRENT_BALANCE_DUE" NUMBER(17,6),
	 CONSTRAINT "PK_ACC_STATEMENT" PRIMARY KEY ("ACC_STATEMENT_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_ACC_STATEMENT_ACCOUNT_01" FOREIGN KEY ("ACC_AR_ACCT_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_AR_ACCT" ("ACC_AR_ACCT_NUM") ENABLE,
	 CONSTRAINT "FK_ACC_TX_05" FOREIGN KEY ("ACC_TX_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_TX" ("ACC_TX_NUM") ENABLE,
	 CONSTRAINT "FK_ACC_STATEMENT_ADDRESS_01" FOREIGN KEY ("ACC_STATEMENT_ADDRESS_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_STATEMENT_ADDRESS" ("ACC_STATEMENT_ADDRESS_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
