-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ACC_PAYMENT_DETAIL"
   (	"ACC_PAYMENT_DETAIL_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACC_ENTRY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACC_PAYMENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"UNUSED_AMOUNT" NUMBER(17,6),
	"PAYMENT_APPLY_DISCOUNT" CHAR(1),
	"PAYMENT_DISCOUNT_MONEY" NUMBER(17,6),
	"PAYMENT_DISCOUNT_PERCENTAGE" NUMBER(17,6),
	"DESCRIPTION" VARCHAR2(1000),
	"BALANCE" NUMBER(17,6),
	"AMOUNT_DUE" NUMBER(17,6),
	"AMOUNT_DUE_DATE" DATE,
	"DISCOUNT_AMOUNT" NUMBER(17,6),
	"DISCOUNT_AMOUNT_DATE" DATE,
	"DISCOUNTED_AMOUNT_DUE" NUMBER(17,6),
	"MINIMUM_PAYMENT" NUMBER(17,6),
	"AMOUNT" NUMBER(17,6),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_ACC_PAYMENT_DETAIL" PRIMARY KEY ("ACC_PAYMENT_DETAIL_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_ACC_ENTRY_05" FOREIGN KEY ("ACC_ENTRY_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_ENTRY" ("ACC_ENTRY_NUM") ENABLE,
	 CONSTRAINT "FK_ACC_PAYMENT_01" FOREIGN KEY ("ACC_PAYMENT_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_PAYMENT" ("ACC_PAYMENT_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
