-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ACC_AR_DEFAULT_OTHER_AMOUNT"
   (	"ACC_AR_DEFAULT_OTHER_AMT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACC_AR_OTHER_AMOUNT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACC_DEFAULTS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_ACC_AR_DEFAULT_OTHER_AMOUNT" PRIMARY KEY ("ACC_AR_DEFAULT_OTHER_AMT_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_ACC_DEFAULTS_01" FOREIGN KEY ("ACC_DEFAULTS_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_DEFAULTS" ("ACC_DEFAULTS_NUM") ENABLE,
	 CONSTRAINT "FK_CHARGE_01" FOREIGN KEY ("ACC_AR_OTHER_AMOUNT_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_AR_OTHER_AMOUNT" ("ACC_AR_OTHER_AMOUNT_NUM") ENABLE
   ) ;
-- ==========================================
