-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ACC_ACCT_TYPE"
   (	"ACC_ACCT_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SUB_ACCOUNT_TYPE_OF" NUMBER(18,0),
	"NAME" VARCHAR2(20 CHAR) NOT NULL ENABLE,
	"ASSET_OR_LIABILITY" CHAR(1) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_ACC_ACCT_TYPE" PRIMARY KEY ("ACC_ACCT_TYPE_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_ACC_ACCOUNT_TYPE_02" FOREIGN KEY ("SUB_ACCOUNT_TYPE_OF")
	  REFERENCES "TREXONE_DATA"."ACC_ACCT_TYPE" ("ACC_ACCT_TYPE_NUM") ENABLE
   ) ;
-- ==========================================
