-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ACC_INSTITUTION"
   (	"ACC_INSTITUTION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"BILLING_ADDRESS" CHAR(1) NOT NULL ENABLE,
	"ACC_PERSON_NUM" NUMBER(18,0),
	"NAME" VARCHAR2(200),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ACC_ALT_PERSON_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_ACC_INSTITUTION" PRIMARY KEY ("ACC_INSTITUTION_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_ACC_PERSON_02" FOREIGN KEY ("ACC_PERSON_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_PERSON" ("ACC_PERSON_NUM") ENABLE,
	 CONSTRAINT "FK_ACC_PERSON_03" FOREIGN KEY ("ACC_ALT_PERSON_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_PERSON" ("ACC_PERSON_NUM") ENABLE
   ) ;
-- ==========================================
