-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ACC_CODE"
   (	"ACC_CODE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACC_CODE_TYPE_NUM" NUMBER(18,0),
	"ACC_CODE_SET_NUM" NUMBER(18,0),
	"CODE" VARCHAR2(30),
	"DESCRIPTION" VARCHAR2(255),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_ACC_CODE" PRIMARY KEY ("ACC_CODE_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
