-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ACC_RELATED_TX"
   (	"ACC_RELATED_TX_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACC_TX_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PARENT_TX_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_ACC_RELATED_TX" PRIMARY KEY ("ACC_RELATED_TX_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_ACC_TX_03" FOREIGN KEY ("ACC_TX_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_TX" ("ACC_TX_NUM") ENABLE,
	 CONSTRAINT "FK_ACC_TX_04" FOREIGN KEY ("PARENT_TX_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_TX" ("ACC_TX_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
