-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ACC_ACCT"
   (	"ACC_ACCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACCT_NUMBER" VARCHAR2(20) NOT NULL ENABLE,
	"IS_DELETED" CHAR(1) NOT NULL ENABLE,
	"ACC_COST_CENTER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACC_ACCT_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"STATUS" CHAR(1) NOT NULL ENABLE,
	"ACC_BALANCE_NUM" NUMBER(18,0),
	"NAME" VARCHAR2(200),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"STATUS_CHANGE_REASON" VARCHAR2(255),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_ACC_ACCT" PRIMARY KEY ("ACC_ACCT_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_ACC_ACCOUNT_07" FOREIGN KEY ("ACC_ACCT_TYPE_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_ACCT_TYPE" ("ACC_ACCT_TYPE_NUM") ENABLE,
	 CONSTRAINT "FK_ACC_COST_CENTER_03" FOREIGN KEY ("ACC_COST_CENTER_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_COST_CENTER" ("ACC_COST_CENTER_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."UC_ACC_ACCT_1" ON "TREXONE_DATA"."ACC_ACCT" ("ACCT_NUMBER", "ERX_CLIENT_ID")
  ;
ALTER TABLE "TREXONE_DATA"."ACC_ACCT" ADD CONSTRAINT "UC_ACC_ACCT_1" UNIQUE ("ACCT_NUMBER", "ERX_CLIENT_ID")
  USING INDEX "TREXONE_DATA"."UC_ACC_ACCT_1"  ENABLE;
-- ==========================================
