-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ACC_DEFAULTS"
   (	"ACC_DEFAULTS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CONTACT_NAME" VARCHAR2(255),
	"CONTACT_ADDITIONAL_INFO" VARCHAR2(2000),
	"REMIT_ADDITIONAL_INFO" VARCHAR2(2000),
	"REMIT_NAME" VARCHAR2(60),
	"ACC_COST_CENTER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACCT_NUM_DIGITS" NUMBER(2,0),
	"ACCT_START_NUM" VARCHAR2(20),
	"POSTING_MANUAL_METHOD" VARCHAR2(20),
	"INCLUDE_PENDING_TRANSACTIONS" CHAR(1),
	"POSTING_BEFORE_STMT_GEN" CHAR(1),
	"POSTING_BEFORE_CLOSING" CHAR(1),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_ACC_DEFAULTS" PRIMARY KEY ("ACC_DEFAULTS_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_ACC_SOST_CENTER_02" FOREIGN KEY ("ACC_COST_CENTER_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_COST_CENTER" ("ACC_COST_CENTER_NUM") ENABLE
   ) ;
-- ==========================================
