-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ACCOUNT_MEMBER"
   (	"ACCOUNT_MEMBER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PATIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACCOUNT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"STATUS" CHAR(1) NOT NULL ENABLE,
	"REL_CODE" NUMBER(18,0),
	"EFFECTIVE_DATE" DATE,
	"TERM_DATE" DATE,
	"USE_ACCOUNT_CREDIT_CARD" CHAR(1),
	"IS_PRIMARY" CHAR(1) NOT NULL ENABLE,
	"PARTICIPATION_LEVEL" CHAR(1),
	"PARTICIPATION_LEVEL_DATE" DATE,
	"DEACTIVATION_REASON_CODE" CHAR(1),
	"ENROLLMENT_CHANNEL" CHAR(1),
	"FREQUENT_SHOPPER_NUM" VARCHAR2(20),
	"IS_AUTHORIZED" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ACCOUNT_CREDIT_CARD_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"DEFAULT_ACCOUNT_MEMBER_CC_NUM" NUMBER(18,0),
	"DEFAULT_SHIPPING_ADDRESS_NUM" NUMBER(18,0),
	"BACKUP_ACCOUNT_MEMBER_CC_NUM" NUMBER(18,0),
	 CONSTRAINT "FK_ACCOUNT_02" FOREIGN KEY ("ACCOUNT_NUM")
	  REFERENCES "TREXONE_DATA"."ACCOUNT" ("ACCOUNT_NUM") ENABLE,
	 CONSTRAINT "FK_ACCOUNT_CREDIT_CARD_01" FOREIGN KEY ("ACCOUNT_CREDIT_CARD_NUM")
	  REFERENCES "TREXONE_DATA"."ACCOUNT_CREDIT_CARD" ("ACCOUNT_CREDIT_CARD_NUM") ENABLE,
	 CONSTRAINT "FK_PATIENT_20" FOREIGN KEY ("PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE,
	 CONSTRAINT "FK_ACCOUNT_MEMBER_CREDIT_CD_04" FOREIGN KEY ("DEFAULT_ACCOUNT_MEMBER_CC_NUM")
	  REFERENCES "TREXONE_DATA"."ACCOUNT_MEMBER_CREDIT_CARD" ("ACCOUNT_MEMBER_CREDIT_CARD_NUM") ENABLE,
	 CONSTRAINT "FK_ADDRESS_03" FOREIGN KEY ("DEFAULT_SHIPPING_ADDRESS_NUM")
	  REFERENCES "TREXONE_DATA"."ADDRESS" ("ADDRESS_NUM") ENABLE,
	 CONSTRAINT "FK_ACCOUNT_MEMBER_CREDIT_CD_07" FOREIGN KEY ("BACKUP_ACCOUNT_MEMBER_CC_NUM")
	  REFERENCES "TREXONE_DATA"."ACCOUNT_MEMBER_CREDIT_CARD" ("ACCOUNT_MEMBER_CREDIT_CARD_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_ACCOUNT_MEMBER" ON "TREXONE_DATA"."ACCOUNT_MEMBER" ("ACCOUNT_MEMBER_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."ACCOUNT_MEMBER" ADD CONSTRAINT "PK_ACCOUNT_MEMBER" PRIMARY KEY ("ACCOUNT_MEMBER_NUM")
  USING INDEX "TREXONE_DATA"."PK_ACCOUNT_MEMBER"  ENABLE;
-- ==========================================
