-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ACCURACY_SCAN_LOG"
   (	"ACCURACY_SCAN_LOG_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_FILL_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"RESULT" CHAR(1) NOT NULL ENABLE,
	"REASON" VARCHAR2(50),
	"VIAL_SCAN_DATA" VARCHAR2(40),
	"STOCK_SCAN_DATA" VARCHAR2(40),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_RX_FILL_02" FOREIGN KEY ("RX_FILL_SEQ", "RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_FILL" ("RX_FILL_SEQ", "RX_RECORD_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_ACCURACY_SCAN_LOG" ON "TREXONE_DATA"."ACCURACY_SCAN_LOG" ("ACCURACY_SCAN_LOG_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."ACCURACY_SCAN_LOG" ADD CONSTRAINT "PK_ACCURACY_SCAN_LOG" PRIMARY KEY ("ACCURACY_SCAN_LOG_NUM")
  USING INDEX "TREXONE_DATA"."PK_ACCURACY_SCAN_LOG"  ENABLE;
-- ==========================================
