-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ADDRESS_LINK"
   (	"ADDRESS_LINK_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"OWNER" NUMBER(18,0) NOT NULL ENABLE,
	"OWNER_TYPE_CODE" CHAR(1) NOT NULL ENABLE,
	"USAGE" NUMBER(18,0) NOT NULL ENABLE,
	"ADDRESS_NUM" NUMBER(18,0),
	"ADDRESS_USAGE" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"COURIER_INSTRUCTIONS" VARCHAR2(300),
	 CONSTRAINT "FK_OWNER_TYPE_01" FOREIGN KEY ("OWNER_TYPE_CODE")
	  REFERENCES "TREXONE_DATA"."OWNER_TYPE" ("OWNER_TYPE_CODE") ENABLE,
	 CONSTRAINT "FK_ADDRESS_01" FOREIGN KEY ("ADDRESS_NUM")
	  REFERENCES "TREXONE_DATA"."ADDRESS" ("ADDRESS_NUM") DEFERRABLE ENABLE NOVALIDATE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_ADDRESS_LINK" ON "TREXONE_DATA"."ADDRESS_LINK" ("ADDRESS_LINK_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."ADDRESS_LINK" ADD CONSTRAINT "PK_ADDRESS_LINK" PRIMARY KEY ("ADDRESS_LINK_NUM")
  USING INDEX "TREXONE_DATA"."PK_ADDRESS_LINK"  ENABLE;
-- ==========================================
