-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ADDRESS"
   (	"ADDRESS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ADDRESS1" VARCHAR2(100),
	"ADDRESS2" VARCHAR2(50),
	"CSZ_NUM" NUMBER(18,0),
	"EXT" VARCHAR2(6),
	"COUNTY_CODE" VARCHAR2(5),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_ZIPCODE_01" FOREIGN KEY ("CSZ_NUM")
	  REFERENCES "TREXONE_DATA"."ZIPCODE" ("CSZ_NUM") ENABLE
   ) ;
  CREATE INDEX "TREXONE_DATA"."PK_ADDRESS" ON "TREXONE_DATA"."ADDRESS" ("ADDRESS_NUM", "CSZ_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."ADDRESS" ADD CONSTRAINT "PK_ADDRESS" PRIMARY KEY ("ADDRESS_NUM")
  USING INDEX "TREXONE_DATA"."PK_ADDRESS"  ENABLE;
-- ==========================================
