-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ADS_REQUEST_INPUT"
   (	"ADS_REQUEST_INPUT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ADS_REQUEST_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"REQUEST_TYPE" CHAR(1) NOT NULL ENABLE,
	"IS_PROFILED" CHAR(1),
	"REASON" VARCHAR2(100),
	"COMMENT_TEXT" VARCHAR2(300),
	"LINKED_RX_RECORD_NUM" NUMBER(18,0),
	"ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ITEM_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_ADS_REQUEST_INPUT" PRIMARY KEY ("ADS_REQUEST_INPUT_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_ADS_REQUEST_01" FOREIGN KEY ("ADS_REQUEST_NUM")
	  REFERENCES "TREXONE_DATA"."ADS_REQUEST" ("ADS_REQUEST_NUM") ENABLE,
	 CONSTRAINT "FK_ITEM_17" FOREIGN KEY ("ORDER_NUM", "ITEM_SEQ")
	  REFERENCES "TREXONE_DATA"."ITEM" ("ORDER_NUM", "ITEM_SEQ") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
