-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ADS_ACCURACY_SCAN_ATTACHMENT"
   (	"ACCURACY_SCAN_ATTACHMENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACCURACY_SCAN_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FILENAME" VARCHAR2(70) NOT NULL ENABLE,
	"IMAGE_NUM" NUMBER(18,0),
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0),
	 CONSTRAINT "ADS_ACCURACY_SCAN_ATTACHMNT_PK" PRIMARY KEY ("ACCURACY_SCAN_ATTACHMENT_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "ADS_ACCURCY_SCAN_ATTCHMNT_FK01" FOREIGN KEY ("ACCURACY_SCAN_NUM")
	  REFERENCES "TREXONE_DATA"."ADS_ACCURACY_SCAN" ("ACCURACY_SCAN_NUM") ENABLE,
	 CONSTRAINT "ADS_ACCURCY_SCAN_ATTCHMNT_FK02" FOREIGN KEY ("IMAGE_NUM")
	  REFERENCES "TREXONE_DATA"."IMAGE" ("IMAGE_NUM") ENABLE
   ) ;
-- ==========================================
