-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ADS_RESPONSE"
   (	"ADS_RESPONSE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ORDER_NUM" NUMBER(18,0),
	"ITEM_SEQ" NUMBER(18,0),
	"START_WF_PROC_DEFINITION_NUM" NUMBER(18,0),
	"END_WF_PROC_DEFINITION_NUM" NUMBER(18,0),
	"EXTERNAL_ORDER_NUMBER" VARCHAR2(12),
	"VALID" CHAR(1),
	"QTY_DISPENSED" NUMBER(13,3),
	"PACKAGE_SIZE" NUMBER(13,3),
	"NUMBER_OF_VIALS" NUMBER(3,0),
	"NDC_REQUESTED" VARCHAR2(13),
	"NDC_DISPENSED" VARCHAR2(13),
	"RPH_INITIALS" VARCHAR2(3),
	"PACKING_INITIALS" VARCHAR2(3),
	"QC_INITIALS" VARCHAR2(3),
	"IS_EASY_OPEN_CAP" CHAR(1),
	"STATUS" VARCHAR2(10),
	"REJECT_CODE" VARCHAR2(10),
	"CANCEL_CODE" VARCHAR2(10),
	"DATE_FILLED" DATE,
	"DATE_COMPLETED" DATE,
	"DATE_UPDATED" DATE,
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_KEY" NUMBER,
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"TRACKING_NUMBER" VARCHAR2(200),
	"ESTIMATED_DELIVERY_DATE" DATE,
	"PACKAGE_WEIGHT" NUMBER(28,8),
	"ACTUAL_COURIER" VARCHAR2(50),
	"ACTUAL_SHIPPING_METHOD" VARCHAR2(100),
	"ACTUAL_SHIP_DATE" DATE,
	"ACTUAL_SHIP_CHARGE" NUMBER(12,2),
	"TOTE_LICENSE_PLATE" VARCHAR2(50),
	"SHIPMENT_TRACKING_URL" VARCHAR2(250),
	"MANIFEST_SYS_EST_DELIVERY_DATE" VARCHAR2(50),
	"EXCEPTION_TEXT" VARCHAR2(250),
	"CF_INVENTORY_ID" VARCHAR2(20),
	"ITEM_TYPE" VARCHAR2(30),
	"LOT_INFO" VARCHAR2(4000),
	"RPH_FIRST_NAME" VARCHAR2(50),
	"RPH_LAST_NAME" VARCHAR2(50),
	"RPH_STATE_LICENSE_NUMBER" VARCHAR2(20),
	"RPH_NPI_NUMBER" VARCHAR2(20),
	"RESHIPMENT_NUM" NUMBER(18,0),
	"TRANSACTION_ID" VARCHAR2(36),
	 CONSTRAINT "PK_ADS_RESPONSE" PRIMARY KEY ("ADS_RESPONSE_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "CK_ADS_RESPONSE_01" CHECK (PARTITION_DATE is not null) ENABLE NOVALIDATE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."IU_ADS_RESPONSE_01" ON "TREXONE_DATA"."ADS_RESPONSE" ("TRANSACTION_ID")
  ;
ALTER TABLE "TREXONE_DATA"."ADS_RESPONSE" ADD CONSTRAINT "UC_ADS_RESPONSE_01" UNIQUE ("TRANSACTION_ID")
  USING INDEX "TREXONE_DATA"."IU_ADS_RESPONSE_01"  ENABLE NOVALIDATE;
-- ==========================================
