-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ADS_ACCURACY_SCAN"
   (	"ACCURACY_SCAN_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ITEM_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"DISPENSING_EVENT_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"IMAGE_GROUP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DISPENSED_ITEM_SERIAL_NUMBER" VARCHAR2(20) NOT NULL ENABLE,
	"DISPENSED_ITEM_GTIN_NUMBER" VARCHAR2(25) NOT NULL ENABLE,
	"DISPENSED_ITEM_LOT_NUMBER" VARCHAR2(20) NOT NULL ENABLE,
	"DISPENSED_ITEM_EXPIRATION_DATE" DATE NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0),
	 CONSTRAINT "ADS_ACCURACY_SCAN_PK" PRIMARY KEY ("ACCURACY_SCAN_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "ADS_ACCURACY_SCAN_FK01" FOREIGN KEY ("ITEM_SEQ", "ORDER_NUM", "DISPENSING_EVENT_SEQ")
	  REFERENCES "TREXONE_DATA"."DISPENSING_EVENT" ("ITEM_SEQ", "ORDER_NUM", "DISPENSING_EVENT_SEQ") ENABLE,
	 CONSTRAINT "ADS_ACCURACY_SCAN_FK02" FOREIGN KEY ("IMAGE_GROUP_NUM")
	  REFERENCES "TREXONE_DATA"."IMAGE_GROUP" ("IMAGE_GROUP_NUM") ENABLE
   ) ;
-- ==========================================
