-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ALLERGEN_XREF"
   (	"ALLERGEN_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ALLERGEN_REF_TYPE" VARCHAR2(4),
	"ALLERGEN_REF_NUM" VARCHAR2(20) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(255),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_ALLERGEN_XREF" ON "TREXONE_DATA"."ALLERGEN_XREF" ("ALLERGEN_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."ALLERGEN_XREF" ADD CONSTRAINT "PK_ALLERGEN_XREF" PRIMARY KEY ("ALLERGEN_NUM")
  USING INDEX "TREXONE_DATA"."PK_ALLERGEN_XREF"  ENABLE;
-- ==========================================
