-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ALLERGY_SYMPTOM"
   (	"SYMPTOM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(60) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE INDEX "TREXONE_DATA"."PK_ALLERGY_SYMPTOM" ON "TREXONE_DATA"."ALLERGY_SYMPTOM" ("SYMPTOM_NUM", "DESCRIPTION")
  ;
ALTER TABLE "TREXONE_DATA"."ALLERGY_SYMPTOM" ADD CONSTRAINT "PK_ALLERGY_SYMPTOM" PRIMARY KEY ("SYMPTOM_NUM")
  USING INDEX "TREXONE_DATA"."PK_ALLERGY_SYMPTOM"  ENABLE;
-- ==========================================
