-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ALLERGY_STATUS_DETAIL"
   (	"PATIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ALLERGEN_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ALLERGY_STATUS_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"NEW_STATUS" CHAR(1),
	"EFFECTIVE_DATE" DATE,
	"COMMENTARY" VARCHAR2(255),
	"CREATE_DATE" DATE,
	"CREATE_USER" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PATIENT_ALLERGY_01" FOREIGN KEY ("PATIENT_NUM", "ALLERGEN_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT_ALLERGY" ("PATIENT_NUM", "ALLERGEN_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_ALLERGY_STATUS_DETAIL" ON "TREXONE_DATA"."ALLERGY_STATUS_DETAIL" ("PATIENT_NUM", "ALLERGEN_NUM", "ALLERGY_STATUS_SEQ")
  ;
ALTER TABLE "TREXONE_DATA"."ALLERGY_STATUS_DETAIL" ADD CONSTRAINT "PK_ALLERGY_STATUS_DETAIL" PRIMARY KEY ("PATIENT_NUM", "ALLERGEN_NUM", "ALLERGY_STATUS_SEQ")
  USING INDEX "TREXONE_DATA"."PK_ALLERGY_STATUS_DETAIL"  ENABLE;
-- ==========================================
