-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ALTERNATE_RECIPIENT"
   (	"ALTERNATE_RECIPIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PATIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ADDRESS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FIRST_NAME" VARCHAR2(30),
	"LAST_NAME" VARCHAR2(30),
	"PHONE_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	"COMPANY" VARCHAR2(44),
	"STATUS" CHAR(1),
	"DATESTAMP" DATE DEFAULT SYSDATE,
	 CONSTRAINT "PK_ALTERNATE_RECIPIENT" PRIMARY KEY ("ALTERNATE_RECIPIENT_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_PATIENT_41" FOREIGN KEY ("PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE,
	 CONSTRAINT "FK_ADDRESS_04" FOREIGN KEY ("ADDRESS_NUM")
	  REFERENCES "TREXONE_DATA"."ADDRESS" ("ADDRESS_NUM") ENABLE,
	 CONSTRAINT "ALTERNATE_RECIP_PHONE_NUM_FK" FOREIGN KEY ("PHONE_NUM")
	  REFERENCES "TREXONE_DATA"."PHONE" ("PHONE_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTOYMINTERVAL(3,'MONTH')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
