-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ANCILLARY_ITEM_COMMIT"
   (	"ANCILLARY_ITEM_COMMIT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ANCILLARY_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"COMMIT_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"QUANTITY" NUMBER(16,8) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"FACILITY_ITEM_NUM" VARCHAR2(10) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" VARCHAR2(100) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE,
	 CONSTRAINT "PK_ANCILLARY_ITEM_COMMIT" PRIMARY KEY ("ANCILLARY_ITEM_COMMIT_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_ORDER_RECORD_06" FOREIGN KEY ("ORDER_NUM")
	  REFERENCES "TREXONE_DATA"."ORDER_RECORD_BASE" ("ORDER_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_ANCILLARY_ITEM_03" FOREIGN KEY ("ANCILLARY_ITEM_NUM")
	  REFERENCES "TREXONE_DATA"."ANCILLARY_ITEM" ("ANCILLARY_ITEM_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_COMMIT_TYPE_02" FOREIGN KEY ("COMMIT_TYPE_NUM")
	  REFERENCES "TREXONE_DATA"."COMMIT_TYPE" ("COMMIT_TYPE_NUM") ENABLE NOVALIDATE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
