-- ==========================================

  CREATE TABLE "TREXONE_DATA"."AUTHENTICATION_EXCEPTION"
   (	"EXCEPTION_TIME" DATE NOT NULL ENABLE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"LOGIN_SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"LOGIN_USER_ID" VARCHAR2(255),
	"LOGIN_USER_FIRST_NAME" VARCHAR2(30),
	"LOGIN_USER_LAST_NAME" VARCHAR2(30),
	"RX_FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_FILL_SEQ" NUMBER(18,0),
	"RX_FACILITY_ID" VARCHAR2(10),
	"RX_NUMBER" VARCHAR2(20),
	"REFILL_NUM" NUMBER(18,0),
	"DISPENSE_PRODUCT_NUM" NUMBER(18,0),
	"DISPENSE_PRODUCT_NAME" VARCHAR2(40),
	"DISPENSE_DATE" DATE,
	"DISPENSE_QUANTITY" NUMBER(13,3),
	"DISP_PRODUCT_STRENGTH" VARCHAR2(30),
	"DISP_PRODUCT_DEA_SCHEDULE" VARCHAR2(10),
	"PATIENT_NUM" NUMBER(18,0),
	"PATIENT_FIRST_NAME" VARCHAR2(30),
	"PATIENT_LAST_NAME" VARCHAR2(30),
	"PATIENT_SHIP_TO_STATE" VARCHAR2(2),
	"OVERRIDE_SYS_USER" NUMBER(18,0),
	"OVERRIDE_USER_ID" VARCHAR2(255),
	"AUTHENTICATION_TYPE" VARCHAR2(30),
	"IS_LOAD_BALANCED" CHAR(1),
	"WF_BLOCK_DEFINITION_NUM" NUMBER(18,0),
	"WF_DESCRIPTION" VARCHAR2(60),
	"AUDIT_NAME" VARCHAR2(255) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	 CONSTRAINT "FK_FACILITY_110" FOREIGN KEY ("LOGIN_FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_31" FOREIGN KEY ("LOGIN_SYS_USER")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE,
	 CONSTRAINT "FK_FACILITY_111" FOREIGN KEY ("RX_FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_RX_FILL_24" FOREIGN KEY ("RX_FILL_SEQ", "RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_FILL" ("RX_FILL_SEQ", "RX_RECORD_NUM") ENABLE,
	 CONSTRAINT "FK_PRODUCT_48" FOREIGN KEY ("DISPENSE_PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT" ("PRODUCT_NUM") ENABLE,
	 CONSTRAINT "FK_PATIENT_42" FOREIGN KEY ("PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_32" FOREIGN KEY ("OVERRIDE_SYS_USER")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTOYMINTERVAL(3,'MONTH')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
