-- ==========================================

  CREATE TABLE "TREXONE_DATA"."BILLING_FORMAT_TEMPLATE"
   (	"BILLING_FORMAT_TEMPLATE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(50),
	"TEMPLATE_TEXT" CLOB,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_BILLING_FORMAT_TEMPLATE" ON "TREXONE_DATA"."BILLING_FORMAT_TEMPLATE" ("BILLING_FORMAT_TEMPLATE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."BILLING_FORMAT_TEMPLATE" ADD CONSTRAINT "PK_BILLING_FORMAT_TEMPLATE" PRIMARY KEY ("BILLING_FORMAT_TEMPLATE_NUM")
  USING INDEX "TREXONE_DATA"."PK_BILLING_FORMAT_TEMPLATE"  ENABLE;
-- ==========================================
