-- ==========================================

  CREATE TABLE "TREXONE_DATA"."BUSINESS_PARTNER"
   (	"BUSINESS_PARTNER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(30),
	"DESCRIPTION" VARCHAR2(255),
	"ADDRESS1" VARCHAR2(30),
	"ADDRESS2" VARCHAR2(30),
	"CITY" VARCHAR2(30),
	"STATE_CODE" VARCHAR2(2),
	"CTRY_CODE" VARCHAR2(8),
	"ZIPCODE" VARCHAR2(10),
	"AREA_CODE" VARCHAR2(3),
	"PHONE_NUMBER" VARCHAR2(7),
	"PHONE_EXT" VARCHAR2(5),
	"FAX_AREA_CODE" VARCHAR2(3),
	"FAX_NUMBER" VARCHAR2(7),
	"CONTACT_NAME" VARCHAR2(30),
	"CONTACT_AREA_CODE" VARCHAR2(3),
	"CONTACT_PHONE_NUMBER" VARCHAR2(7),
	"CONTACT_PHONE_EXT" VARCHAR2(5),
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_STATE_01" FOREIGN KEY ("CTRY_CODE", "STATE_CODE")
	  REFERENCES "TREXONE_DATA"."STATE" ("CTRY_CODE", "STATE_CODE") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_BUSINESS_PARTNER" ON "TREXONE_DATA"."BUSINESS_PARTNER" ("BUSINESS_PARTNER_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."BUSINESS_PARTNER" ADD CONSTRAINT "PK_BUSINESS_PARTNER" PRIMARY KEY ("BUSINESS_PARTNER_NUM")
  USING INDEX "TREXONE_DATA"."PK_BUSINESS_PARTNER"  ENABLE;
-- ==========================================
