-- ==========================================

  CREATE TABLE "TREXONE_DATA"."C1_ITEM_ZONE_AUDIT_ITEM"
   (	"C1_ITEM_ZONE_AUDIT_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"C1_ITEM_ZONE_AUDIT_LOG_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TRANSACTION_TYPE" VARCHAR2(2) NOT NULL ENABLE,
	"OLD_ITEM_NUMBER" VARCHAR2(6),
	"ITEM_NUMBER" VARCHAR2(6),
	"NDC_NUMBER" VARCHAR2(11) NOT NULL ENABLE,
	"OLD_STORE_PACKAGE_SIZE" NUMBER(16,8),
	"STORE_PACKAGE_SIZE" NUMBER(16,8),
	"OLD_ZONE_01_RETAIL" NUMBER(17,6),
	"ZONE_01_RETAIL" NUMBER(17,6),
	"OLD_PRODUCT_GROUP_CODE" VARCHAR2(2),
	"PRODUCT_GROUP_CODE" VARCHAR2(2),
	"ITEM_COMMENT" VARCHAR2(30),
	"PROCESSED_FLAG" CHAR(1) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_C1_ITEM_ZONE_AUDIT_LOG_01" FOREIGN KEY ("C1_ITEM_ZONE_AUDIT_LOG_NUM")
	  REFERENCES "TREXONE_DATA"."C1_ITEM_ZONE_AUDIT_LOG" ("C1_ITEM_ZONE_AUDIT_LOG_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_C1_ITEM_ZONE_AUDIT_ITEM" ON "TREXONE_DATA"."C1_ITEM_ZONE_AUDIT_ITEM" ("C1_ITEM_ZONE_AUDIT_ITEM_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."C1_ITEM_ZONE_AUDIT_ITEM" ADD CONSTRAINT "PK_C1_ITEM_ZONE_AUDIT_ITEM" PRIMARY KEY ("C1_ITEM_ZONE_AUDIT_ITEM_NUM")
  USING INDEX "TREXONE_DATA"."PK_C1_ITEM_ZONE_AUDIT_ITEM"  ENABLE;
-- ==========================================
