-- ==========================================

  CREATE TABLE "TREXONE_DATA"."C1_ITEM_ZONE_AUDIT_LOG"
   (	"C1_ITEM_ZONE_AUDIT_LOG_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FILE_NAME" VARCHAR2(255) NOT NULL ENABLE,
	"FILE_CREATE_DATE" DATE NOT NULL ENABLE,
	"PROCESS_DATE" DATE NOT NULL ENABLE,
	"C1_TOTAL_RECORD_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"C1_NI_RECORD_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"C1_DI_RECORD_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"C1_PC_RECORD_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"C1_SP_RECORD_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"C1_EX_RECORD_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"C1_IL_RECORD_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"TOTAL_RECORD_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"TOTAL_NI_RECORD_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"TOTAL_DI_RECORD_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"TOTAL_PC_RECORD_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"TOTAL_SP_RECORD_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"TOTAL_EX_RECORD_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"TOTAL_IL_RECORD_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"TOTAL_PROCESSED_RECORD_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"PROCESSED_NI_RECORD_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"PROCESSED_DI_RECORD_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"PROCESSED_PC_RECORD_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"PROCESSED_SP_RECORD_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"PROCESSED_EX_RECORD_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"PROCESSED_IL_RECORD_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"TOTAL_ERROR_RECORD_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"ERROR_NI_RECORD__COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"ERROR_DI_RECORD_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"ERROR_PC_RECORD_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"ERROR_SP_RECORD_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"ERROR_EX_RECORD_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"ERROR_IL_RECORD_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_C1_ITEM_ZONE_AUDIT_LOG" ON "TREXONE_DATA"."C1_ITEM_ZONE_AUDIT_LOG" ("C1_ITEM_ZONE_AUDIT_LOG_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."C1_ITEM_ZONE_AUDIT_LOG" ADD CONSTRAINT "PK_C1_ITEM_ZONE_AUDIT_LOG" PRIMARY KEY ("C1_ITEM_ZONE_AUDIT_LOG_NUM")
  USING INDEX "TREXONE_DATA"."PK_C1_ITEM_ZONE_AUDIT_LOG"  ENABLE;
-- ==========================================
