-- ==========================================

  CREATE TABLE "TREXONE_DATA"."C1_NDC_UNIT_AUDIT_LOG"
   (	"C1_NDC_UNIT_AUDIT_LOG_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FILE_NAME" VARCHAR2(255) NOT NULL ENABLE,
	"FILE_CREATE_DATE" DATE NOT NULL ENABLE,
	"PROCESSED_DATE" DATE NOT NULL ENABLE,
	"TRANSACTION_TYPE" VARCHAR2(2) NOT NULL ENABLE,
	"C1_RECORD_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"TOTAL_RECORD_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"PROCESSED_RECORD_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"ERROR_RECORD_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_C1_NDC_UNIT_AUDIT_LOG" ON "TREXONE_DATA"."C1_NDC_UNIT_AUDIT_LOG" ("C1_NDC_UNIT_AUDIT_LOG_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."C1_NDC_UNIT_AUDIT_LOG" ADD CONSTRAINT "PK_C1_NDC_UNIT_AUDIT_LOG" PRIMARY KEY ("C1_NDC_UNIT_AUDIT_LOG_NUM")
  USING INDEX "TREXONE_DATA"."PK_C1_NDC_UNIT_AUDIT_LOG"  ENABLE;
-- ==========================================
