-- ==========================================

  CREATE TABLE "TREXONE_DATA"."C1_RDAC"
   (	"C1_RDAC_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SYSTEM_USER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACCESS_CODE" NUMBER(6,0) NOT NULL ENABLE,
	"TIME_OUT" DATE NOT NULL ENABLE,
	"PERMISSION_SET" VARCHAR2(4000),
	"ACTIVE" CHAR(1) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"LOGIN_HASH" VARCHAR2(10),
	 CONSTRAINT "FK_SYSTEM_USER_01" FOREIGN KEY ("SYSTEM_USER_NUM")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_C1_RDAC" ON "TREXONE_DATA"."C1_RDAC" ("C1_RDAC_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."C1_RDAC" ADD CONSTRAINT "PK_C1_RDAC" PRIMARY KEY ("C1_RDAC_NUM")
  USING INDEX "TREXONE_DATA"."PK_C1_RDAC"  ENABLE;
-- ==========================================
