-- ==========================================

  CREATE TABLE "TREXONE_DATA"."C1_RECON"
   (	"C1_RECON_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"START_TIME" DATE NOT NULL ENABLE,
	"END_TIME" DATE NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"TOTAL_NUMBER_11_POS" NUMBER(18,0),
	"TOTAL_NUMBER_11_NEG" NUMBER(18,0),
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"TOTAL_NUMBER" NUMBER(18,0),
	"TOTAL_NUMBER_10_POS" NUMBER(18,0),
	"TOTAL_NUMBER_10_NEG" NUMBER(18,0),
	"TOTAL_NUMBER_12_POS" NUMBER(18,0),
	"TOTAL_NUMBER_12_NEG" NUMBER(18,0),
	"TOTAL_NUMBER_14_POS" NUMBER(18,0),
	"TOTAL_NUMBER_14_NEG" NUMBER(18,0),
	"TOTAL_NUMBER_17_POS" NUMBER(18,0),
	"TOTAL_NUMBER_17_NEG" NUMBER(18,0),
	"TOTAL_NUMBER_CASH_RX_POS" NUMBER(18,0),
	"TOTAL_NUMBER_CASH_RX_NEG" NUMBER(18,0),
	"TOTAL_NUMBER_TP_RX_POS" NUMBER(18,0),
	"TOTAL_NUMBER_TP_RX_NEG" NUMBER(18,0),
	"NET_DOLLAR_CASH_RX" NUMBER(17,6),
	"NET_DOLLAR_TP_RX" NUMBER(17,6),
	"NET_DOLLAR_11_RX" NUMBER(17,6),
	"NET_DOLLAR_10_RX" NUMBER(17,6),
	"NET_PATIENT_PAY_10_RX" NUMBER(17,6),
	"NET_TAX_10_RX" NUMBER(17,6),
	"NET_TP_AR" NUMBER(17,6),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_FACILITY_04" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."UC_C1_RECON_1" ON "TREXONE_DATA"."C1_RECON" ("FACILITY_NUM", "START_TIME", "END_TIME", "ERX_CLIENT_ID")
  ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_C1_RECON" ON "TREXONE_DATA"."C1_RECON" ("C1_RECON_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."C1_RECON" ADD CONSTRAINT "PK_C1_RECON" PRIMARY KEY ("C1_RECON_NUM")
  USING INDEX "TREXONE_DATA"."PK_C1_RECON"  ENABLE;
ALTER TABLE "TREXONE_DATA"."C1_RECON" ADD CONSTRAINT "UC_C1_RECON_1" UNIQUE ("FACILITY_NUM", "START_TIME", "END_TIME", "ERX_CLIENT_ID")
  USING INDEX "TREXONE_DATA"."UC_C1_RECON_1"  ENABLE;
-- ==========================================
