-- ==========================================

  CREATE TABLE "TREXONE_DATA"."C1_STORE_ZONE_AUDIT_DETAIL"
   (	"C1_STORE_ZONE_AUDIT_DETAIL_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"C1_STORE_ZONE_AUDIT_LOG_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"STORE_NUMBER" VARCHAR2(5) NOT NULL ENABLE,
	"PRODUCT_GROUP_CODE" VARCHAR2(2) NOT NULL ENABLE,
	"OLD_PRICE_ZONE_CODE" VARCHAR2(2),
	"PRICE_ZONE_CODE" VARCHAR2(2) NOT NULL ENABLE,
	"PROCESSED_FLAG" CHAR(1) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_C1_STORE_ZONE_AUDIT_LOG_01" FOREIGN KEY ("C1_STORE_ZONE_AUDIT_LOG_NUM")
	  REFERENCES "TREXONE_DATA"."C1_STORE_ZONE_AUDIT_LOG" ("C1_STORE_ZONE_AUDIT_LOG_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_C1_STORE_ZONE_AUDIT_DETAIL" ON "TREXONE_DATA"."C1_STORE_ZONE_AUDIT_DETAIL" ("C1_STORE_ZONE_AUDIT_DETAIL_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."C1_STORE_ZONE_AUDIT_DETAIL" ADD CONSTRAINT "PK_C1_STORE_ZONE_AUDIT_DETAIL" PRIMARY KEY ("C1_STORE_ZONE_AUDIT_DETAIL_NUM")
  USING INDEX "TREXONE_DATA"."PK_C1_STORE_ZONE_AUDIT_DETAIL"  ENABLE;
-- ==========================================
