-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CC_TRANS_RESPONSE"
   (	"CC_TRANS_RESPONSE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CC_TRANS_REQUEST_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CC_TRANS_STATUS_MSG" VARCHAR2(300) NOT NULL ENABLE,
	"CC_TRANS_STATUS_CODE" VARCHAR2(10) NOT NULL ENABLE,
	"CC_TRANS_TERMINATION_MESSAGE" VARCHAR2(200),
	"CC_TRANS_RESPONSE_MESSAGE" VARCHAR2(300),
	"CC_TRANS_AUTHORIZATION_CODE" VARCHAR2(20),
	"CC_TRANS_ROUTING_ID" VARCHAR2(20),
	"CC_TRANS_PAYMENT_MEDIA" VARCHAR2(20),
	"CC_TRANS_PAYMENT_TYPE" VARCHAR2(20),
	"CC_TRANS_AVS_CODE" VARCHAR2(30),
	"CC_TRANS_CVV_VALIDATION_CODE" VARCHAR2(30),
	"CC_TRANS_COMMERCIAL_CARD_TYPE" VARCHAR2(30),
	"CC_TRANS_CC_AMOUNT" NUMBER(17,6),
	"CC_TRANS_PROCESSOR_TRANS_NUM" VARCHAR2(30),
	"CC_TRANS_PROCESSOR_TRANS_DATE" VARCHAR2(30),
	"CC_TRANS_PROCESSOR_TRANS_TIME" VARCHAR2(30),
	"CC_TRANS_REFERENCE_NUM" VARCHAR2(100),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"IS_PARTIAL_AUTH" CHAR(1),
	"CC_TRANS_DIFF_AMOUNT_DUE" NUMBER(17,6),
	"CC_TRANS_AUTH_AMOUNT" NUMBER(17,6),
	"CC_TRANS_APPROVAL_AMOUNT" NUMBER(17,6),
	"CC_TRANS_TKN_MATCHING" VARCHAR2(50),
	"CC_TRANS_TKN_USED" VARCHAR2(10),
	"CC_TRANS_TKN_EXPDATE" VARCHAR2(20),
	"CC_TRANS_TKN_PAYMENT" VARCHAR2(50),
	"CC_TRANS_CARD_TOKEN" VARCHAR2(50),
	 CONSTRAINT "PK_CC_TRANS_RESPONSE" PRIMARY KEY ("CC_TRANS_RESPONSE_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_CC_TRANS_REQUEST_02" FOREIGN KEY ("CC_TRANS_REQUEST_NUM")
	  REFERENCES "TREXONE_DATA"."CC_TRANS_REQUEST" ("CC_TRANS_REQUEST_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
