-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CF_ROUTING_RULE"
   (	"CF_ROUTING_RULE_NUM" NUMBER(18,0),
	"CF_RULE_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"CF_RULE_DATA" CLOB NOT NULL ENABLE,
	"CF_RULE_ACTIVE" CHAR(1) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	 CONSTRAINT "PK_CF_ROUTING_RULE" PRIMARY KEY ("CF_ROUTING_RULE_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_111" FOREIGN KEY ("SYS_USER")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE NOVALIDATE
   ) ;
-- ==========================================
