-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CHR_XREF"
   (	"CHR_XREF_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"IMAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TYPE" VARCHAR2(30),
	"CHR_ID" VARCHAR2(18) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_KEEP_IMAGE_01" FOREIGN KEY ("IMAGE_NUM")
	  REFERENCES "TREXONE_DATA"."KEEP_IMAGE" ("IMAGE_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_CHR_XREF" ON "TREXONE_DATA"."CHR_XREF" ("CHR_XREF_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."CHR_XREF" ADD CONSTRAINT "PK_CHR_XREF" PRIMARY KEY ("CHR_XREF_NUM")
  USING INDEX "TREXONE_DATA"."PK_CHR_XREF"  ENABLE;
-- ==========================================
