-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CLIENT_LOCATION"
   (	"CLIENT_LOCATION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0),
	"NAME" VARCHAR2(255),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"CLIENT_TYPE" VARCHAR2(25) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"COMP_TYPE" CHAR(1),
	"FROM_VERSION" VARCHAR2(30),
	"TO_VERSION" VARCHAR2(30),
	"STAGED_VERSION" VARCHAR2(30),
	"DOWNLOAD_TIME" NUMBER(18,0),
	"UPDATE_TIME" NUMBER(18,0),
	"UPDATE_TYPE" CHAR(1),
	"ERROR_CODE" VARCHAR2(200),
	"STATUS" CHAR(1),
	"JREVERSION" VARCHAR2(20),
	"IP_ADDR" VARCHAR2(15),
	"NUM_FILES" NUMBER(9,0),
	"WS_INFO" VARCHAR2(4000),
	"IS_AUTHORIZED" CHAR(1) DEFAULT 'N',
	"AUTH_DATE" DATE,
	"AUTH_USER" NUMBER(22,0),
	"HUB_CURR_CERT" CLOB,
	"HUB_PREV_CERT" CLOB,
	"HUB_ID" VARCHAR2(1024),
	"HUB_CERT_EXPIRY_DATE" DATE,
	"HUB_REMOTE_CONFIG" CHAR(1),
	"HUB_LOGIN_DATE" DATE,
	"HUB_RENEW_DATE" DATE,
	 CONSTRAINT "FK_FACILITY_07" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_CLIENT_LOCATION" ON "TREXONE_DATA"."CLIENT_LOCATION" ("CLIENT_LOCATION_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."CLIENT_LOCATION" ADD CONSTRAINT "PK_CLIENT_LOCATION" PRIMARY KEY ("CLIENT_LOCATION_NUM")
  USING INDEX "TREXONE_DATA"."PK_CLIENT_LOCATION"  ENABLE;
-- ==========================================
