-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CLINICAL_PROGRAM_STATUS"
   (	"CLINICAL_PROGRAM_STATUS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CLINICAL_PROGRAM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PROGRAM_STATUS_CODE" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"PATIENT_NUM" NUMBER(18,0),
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_CLINICAL_PROGRAM_STATUS" PRIMARY KEY ("CLINICAL_PROGRAM_STATUS_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "CK_CLINICAL_PROGRAM_STATUS_01" CHECK ( (PATIENT_NUM is null and RX_RECORD_NUM is not null)
        or (PATIENT_NUM is not null and RX_RECORD_NUM is null)) ENABLE,
	 CONSTRAINT "FK_CLINICAL_PROGRAM_01" FOREIGN KEY ("CLINICAL_PROGRAM_NUM")
	  REFERENCES "TREXONE_DATA"."CLINICAL_PROGRAM" ("CLINICAL_PROGRAM_NUM") ENABLE,
	 CONSTRAINT "FK_RX_BASE_17" FOREIGN KEY ("RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_BASE" ("RX_RECORD_NUM") ENABLE,
	 CONSTRAINT "FK_PATIENT_35" FOREIGN KEY ("PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
