-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CODE"
   (	"CODE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CODE_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CODE_SET_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CODE" VARCHAR2(30) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(255) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"INTERNAL" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_CODE_SET_01" FOREIGN KEY ("CODE_SET_NUM")
	  REFERENCES "TREXONE_DATA"."CODE_SET" ("CODE_SET_NUM") ENABLE,
	 CONSTRAINT "FK_CODE_TYPE_01" FOREIGN KEY ("CODE_TYPE_NUM")
	  REFERENCES "TREXONE_DATA"."CODE_TYPE" ("CODE_TYPE_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_CODE" ON "TREXONE_DATA"."CODE" ("CODE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."CODE" ADD CONSTRAINT "PK_CODE" PRIMARY KEY ("CODE_NUM")
  USING INDEX "TREXONE_DATA"."PK_CODE"  ENABLE;
-- ==========================================
