-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CODE_LIST_ITEM"
   (	"CODE_LIST_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CODE_LIST_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CODE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"IS_EDITABLE" CHAR(1) NOT NULL ENABLE,
	"EXCLUDE" CHAR(1) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_CODE_01" FOREIGN KEY ("CODE_NUM")
	  REFERENCES "TREXONE_DATA"."CODE" ("CODE_NUM") ENABLE,
	 CONSTRAINT "FK_CODE_LIST_01" FOREIGN KEY ("CODE_LIST_NUM")
	  REFERENCES "TREXONE_DATA"."CODE_LIST" ("CODE_LIST_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_CODE_LIST_ITEM" ON "TREXONE_DATA"."CODE_LIST_ITEM" ("CODE_LIST_ITEM_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."CODE_LIST_ITEM" ADD CONSTRAINT "PK_CODE_LIST_ITEM" PRIMARY KEY ("CODE_LIST_ITEM_NUM")
  USING INDEX "TREXONE_DATA"."PK_CODE_LIST_ITEM"  ENABLE;
-- ==========================================
