-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CODE_TYPE"
   (	"CODE_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(125) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"INTERNAL" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_CODE_TYPE" ON "TREXONE_DATA"."CODE_TYPE" ("CODE_TYPE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."CODE_TYPE" ADD CONSTRAINT "PK_CODE_TYPE" PRIMARY KEY ("CODE_TYPE_NUM")
  USING INDEX "TREXONE_DATA"."PK_CODE_TYPE"  ENABLE;
-- ==========================================
