-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CODE_LIST"
   (	"CODE_LIST_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CODE_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(125) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(255) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_CODE_TYPE_02" FOREIGN KEY ("CODE_TYPE_NUM")
	  REFERENCES "TREXONE_DATA"."CODE_TYPE" ("CODE_TYPE_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_CODE_LIST" ON "TREXONE_DATA"."CODE_LIST" ("CODE_LIST_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."CODE_LIST" ADD CONSTRAINT "PK_CODE_LIST" PRIMARY KEY ("CODE_LIST_NUM")
  USING INDEX "TREXONE_DATA"."PK_CODE_LIST"  ENABLE;
-- ==========================================
