-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CODE_SET"
   (	"CODE_SET_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(20) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(255) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"INTERNAL" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_CODE_SET" ON "TREXONE_DATA"."CODE_SET" ("CODE_SET_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."CODE_SET" ADD CONSTRAINT "PK_CODE_SET" PRIMARY KEY ("CODE_SET_NUM")
  USING INDEX "TREXONE_DATA"."PK_CODE_SET"  ENABLE;
-- ==========================================
