-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CONFIG_PROPERTY"
   (	"CONFIG_PROPERTY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(255),
	"DESCRIPTION" VARCHAR2(255),
	"DEFAULT_VALUE" VARCHAR2(3000),
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"APPLICATION_VERSION" VARCHAR2(8) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_CONFIG_PROPERTY" ON "TREXONE_DATA"."CONFIG_PROPERTY" ("CONFIG_PROPERTY_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."CONFIG_PROPERTY" ADD CONSTRAINT "PK_CONFIG_PROPERTY" PRIMARY KEY ("CONFIG_PROPERTY_NUM")
  USING INDEX "TREXONE_DATA"."PK_CONFIG_PROPERTY"  ENABLE;
-- ==========================================
