-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CONFIDENTIAL_COMMUNICATION"
   (	"CONFIDENTIAL_COMMUNICATION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PATIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACKNOWLEDGE_TYPE_CODE" CHAR(1),
	"RESTRICTION_LEVEL_CODE" CHAR(1),
	"SIGNATURE_IMAGE_NUM" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_FACILITY_10" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_IMAGE_04" FOREIGN KEY ("SIGNATURE_IMAGE_NUM")
	  REFERENCES "TREXONE_DATA"."IMAGE" ("IMAGE_NUM") ENABLE,
	 CONSTRAINT "FK_PATIENT_04" FOREIGN KEY ("PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_CONFIDENTIAL_COMMUNICATION" ON "TREXONE_DATA"."CONFIDENTIAL_COMMUNICATION" ("CONFIDENTIAL_COMMUNICATION_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."CONFIDENTIAL_COMMUNICATION" ADD CONSTRAINT "PK_CONFIDENTIAL_COMMUNICATION" PRIMARY KEY ("CONFIDENTIAL_COMMUNICATION_NUM")
  USING INDEX "TREXONE_DATA"."PK_CONFIDENTIAL_COMMUNICATION"  ENABLE;
-- ==========================================
