-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CONTACT_EVENT_HISTORY"
   (	"CONTACT_EVENT_HISTORY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CONTACT_EVENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CONTACT_STATUS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CONTACT_METHOD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CONTACT_NAME" VARCHAR2(2000),
	"CREATE_USER" NUMBER(18,0) NOT NULL ENABLE,
	"CREATE_DATE" DATE NOT NULL ENABLE,
	"HISTORY_COMMENT" VARCHAR2(2000),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0),
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_CONTACT_EVENT_01" FOREIGN KEY ("CONTACT_EVENT_NUM")
	  REFERENCES "TREXONE_DATA"."CONTACT_EVENT" ("CONTACT_EVENT_NUM") ENABLE,
	 CONSTRAINT "FK_FACILITY_08" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_03" FOREIGN KEY ("CREATE_USER")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_CONTACT_EVENT_HISTORY" ON "TREXONE_DATA"."CONTACT_EVENT_HISTORY" ("CONTACT_EVENT_HISTORY_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."CONTACT_EVENT_HISTORY" ADD CONSTRAINT "PK_CONTACT_EVENT_HISTORY" PRIMARY KEY ("CONTACT_EVENT_HISTORY_NUM")
  USING INDEX "TREXONE_DATA"."PK_CONTACT_EVENT_HISTORY"  ENABLE;
-- ==========================================
