-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CONTACT_METHOD"
   (	"CONTACT_METHOD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(45) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_CONTACT_METHOD" ON "TREXONE_DATA"."CONTACT_METHOD" ("CONTACT_METHOD_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."CONTACT_METHOD" ADD CONSTRAINT "PK_CONTACT_METHOD" PRIMARY KEY ("CONTACT_METHOD_NUM")
  USING INDEX "TREXONE_DATA"."PK_CONTACT_METHOD"  ENABLE;
-- ==========================================
