-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CONVERSION_TYPE"
   (	"CONVERSION_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TYPE" VARCHAR2(30) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PKCONVERSION_TYPE" ON "TREXONE_DATA"."CONVERSION_TYPE" ("CONVERSION_TYPE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."CONVERSION_TYPE" ADD CONSTRAINT "PKCONVERSION_TYPE" PRIMARY KEY ("CONVERSION_TYPE_NUM")
  USING INDEX "TREXONE_DATA"."PKCONVERSION_TYPE"  ENABLE;
-- ==========================================
