-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CORE_AR_ENTRY"
   (	"CORE_AR_ENTRY_NUM" NUMBER(20,0) NOT NULL ENABLE,
	"ACC_ENTRY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACC_ACCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACCT_ENTRY_AMOUNT" NUMBER(17,6),
	"ACCT_ENTRY_SERVICE_DATE" DATE,
	"ACC_TX_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACC_TX_SOURCE" VARCHAR2(200),
	"ACC_TX_TYPE_DESCRIPTION" VARCHAR2(200),
	"ACC_TX_IS_DELETED" CHAR(1) NOT NULL ENABLE,
	"ACC_TX_IS_CURRENT" CHAR(1) NOT NULL ENABLE,
	"ACC_TX_CLOSED_DATE" DATE,
	"ACC_TX_POST_DATE" DATE,
	"ACC_TX_DATE" DATE,
	"ACC_TX_DESCRIPTION" VARCHAR2(4000),
	"ACC_TX_REASON" VARCHAR2(200),
	"ACC_TX_EXTERNAL_REFERENCE" VARCHAR2(40),
	"ACC_TX_NUMBER" VARCHAR2(255) NOT NULL ENABLE,
	"ACC_TX_SEPARATE_LINE_ITEM" CHAR(1),
	"ACC_COST_CENTER_NUM" NUMBER(18,0),
	"TEMPLATE_TX_NUM" NUMBER(18,0),
	"ACC_STATEMENT_NUM" NUMBER(18,0),
	"IS_PAID" CHAR(1),
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ACC_TX_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACC_RECURRING_TX_NUM" NUMBER(18,0),
	"FREQUENCY_NUM" NUMBER(18,0),
	"INST_NUM" NUMBER(18,0),
	"INST_NAME" VARCHAR2(200),
	"PERSON_NUM" NUMBER(18,0),
	"PERSON_NAME" VARCHAR2(100),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_CORE_AR_ENTRY" PRIMARY KEY ("CORE_AR_ENTRY_NUM")
  USING INDEX  ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
