-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CORE_FACILITY"
   (	"CF_FACILITY_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"CF_FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CF_FACILITY_NAME" VARCHAR2(30),
	"CF_FACILITY_ADDRESS1" VARCHAR2(100),
	"CF_FACILITY_ADDRESS2" VARCHAR2(50),
	"CF_FACILITY_CITY" VARCHAR2(40),
	"CF_FACILITY_STATE" VARCHAR2(2),
	"CF_FACILITY_ZIP" VARCHAR2(20),
	"CF_FACILITY_FED_TAXID" VARCHAR2(80),
	"CF_NABP_NUM" VARCHAR2(30),
	"CF_FACILITY_GROUP1" VARCHAR2(30),
	"CF_FACILITY_GROUP2" VARCHAR2(30),
	"CF_FACILITY_GROUP3" VARCHAR2(30),
	"CF_FACILITY_GROUP4" VARCHAR2(30),
	"CF_FACILITY_GROUP5" VARCHAR2(30),
	"CF_FACILITY_GROUP6" VARCHAR2(30),
	"CF_FACILITY_GROUP7" VARCHAR2(30),
	"CF_FACILITY_GROUP_NUM1" NUMBER(18,0),
	"CF_FACILITY_GROUP_NUM2" NUMBER(18,0),
	"CF_FACILITY_GROUP_NUM3" NUMBER(18,0),
	"CF_FACILITY_GROUP_NUM4" NUMBER(18,0),
	"CF_FACILITY_GROUP_NUM5" NUMBER(18,0),
	"CF_FACILITY_GROUP_NUM6" NUMBER(18,0),
	"CF_FACILITY_GROUP_NUM7" NUMBER(18,0),
	"CF_FACILITY_ID" VARCHAR2(20),
	"CF_PHONE_NUMBER" VARCHAR2(30),
	"CF_FAX_NUMBER" VARCHAR2(30),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"IS_ACTIVE" CHAR(1),
	"CF_FACILITY_ZIPEXT" VARCHAR2(6),
	"LEGAL_NAME" VARCHAR2(30),
	"TIMEZONE_ID" VARCHAR2(60)
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_CORE_FACILITY" ON "TREXONE_DATA"."CORE_FACILITY" ("CF_FACILITY_KEY")
  ;
  CREATE INDEX "TREXONE_DATA"."IU_CORE_FACILITY_1" ON "TREXONE_DATA"."CORE_FACILITY" ("CF_FACILITY_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."CORE_FACILITY" ADD CONSTRAINT "PK_CORE_FACILITY" PRIMARY KEY ("CF_FACILITY_KEY")
  USING INDEX "TREXONE_DATA"."PK_CORE_FACILITY"  ENABLE;
ALTER TABLE "TREXONE_DATA"."CORE_FACILITY" ADD CONSTRAINT "UC_CORE_FACILITY" UNIQUE ("CF_FACILITY_NUM")
  USING INDEX "TREXONE_DATA"."IU_CORE_FACILITY_1"  ENABLE;
-- ==========================================
