-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CORE_AR_ACCT_MEMBER"
   (	"CORE_ACCT_MEMBER_NUM" NUMBER(20,0) NOT NULL ENABLE,
	"ACC_AR_ACCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PERSON_NUM" NUMBER(18,0),
	"LAST_NAME" VARCHAR2(30),
	"MIDDLE_NAME" VARCHAR2(30),
	"FIRST_NAME" VARCHAR2(30),
	"ADDRESS1" VARCHAR2(100),
	"ADDRESS2" VARCHAR2(50),
	"CITY" VARCHAR2(40),
	"STATE_CODE" VARCHAR2(2),
	"ZIPCODE" VARCHAR2(20),
	"CTRY_CODE" VARCHAR2(8),
	"AREA_CODE" VARCHAR2(4),
	"PHONE_NUMBER" VARCHAR2(20),
	"EXT" VARCHAR2(6),
	"PATIENT_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_CORE_AR_ACCT_MEMBER" PRIMARY KEY ("CORE_ACCT_MEMBER_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
