-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CORE_ERROR_LOG"
   (	"MESSAGE" VARCHAR2(2000),
	"MESSAGE_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	"CORE_ERROR_LOG_NUM" NUMBER(18,0),
	"PROCEDURE_NAME" VARCHAR2(30),
	"MESSAGE_STATUS" CHAR(1) NOT NULL ENABLE,
	 CONSTRAINT "PK_CORE_ERROR_LOG" PRIMARY KEY ("CORE_ERROR_LOG_NUM")
  USING INDEX  ENABLE
   )
  PARTITION BY RANGE ("MESSAGE_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
