-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CORE_PERFORMANCE_SUMMARY"
   (	"CF_FACILITY_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"CPS_SALES_DATE" DATE NOT NULL ENABLE,
	"CPS_TOTAL_FILL_CNT" NUMBER(10,0) NOT NULL ENABLE,
	"CPS_TOTAL_PARTIAL_CNT" NUMBER(10,0) NOT NULL ENABLE,
	"CPS_TOTAL_WAIT_CNT" NUMBER(10,0) NOT NULL ENABLE,
	"CPS_TOTAL_WAIT_READY_CNT" NUMBER(10,0) NOT NULL ENABLE,
	"CPS_TOTAL_WAIT_READY_PCT" NUMBER(3,0) NOT NULL ENABLE,
	"CPS_TOTAL_WAIT_MINUTES" NUMBER(10,0) NOT NULL ENABLE,
	"CPS_AVG_WAIT_MINUTES" NUMBER(10,0) NOT NULL ENABLE,
	"CPS_TOTAL_NON_WAIT_CNT" NUMBER(10,0) NOT NULL ENABLE,
	"CPS_TOTAL_NON_WAIT_READY_CNT" NUMBER(10,0) NOT NULL ENABLE,
	"CPS_TOTAL_NON_WAIT_READY_PCT" NUMBER(3,0) NOT NULL ENABLE,
	"CPS_TOTAL_GENERIC_OPP_CNT" NUMBER(10,0) NOT NULL ENABLE,
	"CPS_TOTAL_GENERIC_FILL_CNT" NUMBER(10,0) NOT NULL ENABLE,
	"CPS_TOTAL_GENERIC_SUB_PCT" NUMBER(3,0) NOT NULL ENABLE,
	"CPS_TOTAL_OUT_OF_STOCK_CNT" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
	"CPS_TOTAL_GENERIC_WRT_DSP_CNT" NUMBER(10,0),
	"CPS_TOTAL_RETURN_COUNT" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
	"LOCK_AVOIDANCE_BUCKET" NUMBER(18,0),
	"CPS_SALES_DATE_LOCAL" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_CORE_PERFORMANCE_SUMMARY" PRIMARY KEY ("CF_FACILITY_KEY", "CPS_SALES_DATE_LOCAL", "LOCK_AVOIDANCE_BUCKET")
  USING INDEX  ENABLE,
	 CONSTRAINT "CK_CORE_PERFORMANCE_SUMMARY_01" CHECK (CPS_SALES_DATE is not null) ENABLE NOVALIDATE,
	 CONSTRAINT "FK_CORE_FACILITY_3" FOREIGN KEY ("CF_FACILITY_KEY")
	  REFERENCES "TREXONE_DATA"."CORE_FACILITY" ("CF_FACILITY_KEY") ENABLE
   )
  PARTITION BY RANGE ("CPS_SALES_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
