-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CORE_CHECKIN_ERROR"
   (	"CORE_CHECKIN_ERROR_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CF_FACILITY_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PATIENT_LAST_NAME" VARCHAR2(30),
	"PATIENT_FIRST_NAME" VARCHAR2(30),
	"PATIENT_MIDDLE_NAME" VARCHAR2(30),
	"PRODUCT_NAME" VARCHAR2(40),
	"EXCEPTION_DESC" VARCHAR2(150),
	"EXCEPTION_TYPE" VARCHAR2(50),
	"TOTE_ID" VARCHAR2(50),
	"EXTERNAL_ORDER_NUMBER" VARCHAR2(12),
	"DATESTAMP" DATE NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	"RX_NUMBER" VARCHAR2(20),
	 CONSTRAINT "PK_CORE_CHECKIN_ERROR" PRIMARY KEY ("CORE_CHECKIN_ERROR_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_CORE_FACILITY_11" FOREIGN KEY ("CF_FACILITY_KEY")
	  REFERENCES "TREXONE_DATA"."CORE_FACILITY" ("CF_FACILITY_KEY") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
