-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CORE_FACILITY_PRODUCT"
   (	"CF_FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CP_PRODUCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CP_DRUG_NUM" NUMBER(18,0),
	"CP_PRODUCT_NAME" VARCHAR2(35) NOT NULL ENABLE,
	"CP_PRODUCT_SCHEDULE" VARCHAR2(10),
	"CP_NDC_MFG" CHAR(5),
	"CP_NDC_PRODUCT" CHAR(4),
	"CP_NDC_SIZE" CHAR(2),
	"CP_PRODUCT_NDC" VARCHAR2(20),
	"CP_DOSAGE_FORM" VARCHAR2(40),
	"CP_LAST_SOLD_DATE" DATE,
	"UNIT_COST" NUMBER(18,6),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"EXPECTED_ACQ_COST" NUMBER(17,6),
	"EAC_VENDOR_NUM" NUMBER(18,0),
	"ALTERNATE_LABEL_NAME" VARCHAR2(40),
	"SUPPLIER_PACKAGE_SIZE" NUMBER(16,8),
	"SUPPLIER_PURCHASE_INCREMENT" NUMBER(9,0),
	"SUPPLIER_UNIT_QUANTITY" NUMBER(16,8),
	 CONSTRAINT "FK_CORE_FACILITY_6" FOREIGN KEY ("CF_FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."CORE_FACILITY" ("CF_FACILITY_NUM") ENABLE
   ) ;
  CREATE INDEX "TREXONE_DATA"."PK_CORE_FACILITY_PRODUCT" ON "TREXONE_DATA"."CORE_FACILITY_PRODUCT" ("CF_FACILITY_NUM", "CP_PRODUCT_NUM", "ERX_CLIENT_ID")
  ;
ALTER TABLE "TREXONE_DATA"."CORE_FACILITY_PRODUCT" ADD CONSTRAINT "PK_CORE_FACILITY_PRODUCT" PRIMARY KEY ("CF_FACILITY_NUM", "CP_PRODUCT_NUM", "ERX_CLIENT_ID")
  USING INDEX "TREXONE_DATA"."PK_CORE_FACILITY_PRODUCT"  ENABLE;
-- ==========================================
