-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CORE_TP_SOLD_SUMMARY"
   (	"CF_FACILITY_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"TP_PLAN_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SOLD_DATE" DATE NOT NULL ENABLE,
	"TP_PLAN_NAME" VARCHAR2(45),
	"TRANSACTION_CNT" NUMBER(10,0),
	"TOTAL_TP_DUE_AMT" NUMBER(18,6),
	"TOTAL_PATIENT_PAY_AMT" NUMBER(18,6),
	"TOTAL_REIMBURSEMENT_AMT" NUMBER(18,6),
	"TOTAL_SALES_TAX_AMT" NUMBER(18,6),
	"LOCK_AVOIDANCE_BUCKET" NUMBER(18,0),
	"SOLD_DATE_LOCAL" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"USER_DEFINED_STEP_AMT" NUMBER(17,6),
	 CONSTRAINT "PK_CORE_TP_SOLD_SUMMARY" PRIMARY KEY ("CF_FACILITY_KEY", "TP_PLAN_NUM", "SOLD_DATE_LOCAL", "LOCK_AVOIDANCE_BUCKET")
  USING INDEX  ENABLE,
	 CONSTRAINT "CK_CORE_TP_SOLD_SUMMARY_01" CHECK (SOLD_DATE is not null) ENABLE NOVALIDATE,
	 CONSTRAINT "FK_CORE_FACILITY_8" FOREIGN KEY ("CF_FACILITY_KEY")
	  REFERENCES "TREXONE_DATA"."CORE_FACILITY" ("CF_FACILITY_KEY") ENABLE
   )
  PARTITION BY RANGE ("SOLD_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
