-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CORPORATE_CERTIFICATE"
   (	"CORPORATE_CERTIFICATE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SECURITY_CERTIFICATE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"CERTIFICATE_PASSWORD" VARCHAR2(128) NOT NULL ENABLE,
	"IS_VALID" CHAR(1),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DATA_GROUP_22" FOREIGN KEY ("DATA_GROUP")
	  REFERENCES "TREXONE_DATA"."DATA_GROUP" ("DATA_GROUP") ENABLE,
	 CONSTRAINT "FK_SECURITY_CERTIFICATE_2" FOREIGN KEY ("SECURITY_CERTIFICATE_NUM")
	  REFERENCES "TREXONE_DATA"."SECURITY_CERTIFICATE" ("SECURITY_CERTIFICATE_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_CORPORATE_CERTIFICATE" ON "TREXONE_DATA"."CORPORATE_CERTIFICATE" ("CORPORATE_CERTIFICATE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."CORPORATE_CERTIFICATE" ADD CONSTRAINT "PK_CORPORATE_CERTIFICATE" PRIMARY KEY ("CORPORATE_CERTIFICATE_NUM")
  USING INDEX "TREXONE_DATA"."PK_CORPORATE_CERTIFICATE"  ENABLE;
-- ==========================================
