-- ==========================================

  CREATE TABLE "TREXONE_DATA"."COST_BASIS"
   (	"COST_BASIS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(30) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(255),
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_COST_BASIS" ON "TREXONE_DATA"."COST_BASIS" ("COST_BASIS_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."COST_BASIS" ADD CONSTRAINT "PK_COST_BASIS" PRIMARY KEY ("COST_BASIS_NUM")
  USING INDEX "TREXONE_DATA"."PK_COST_BASIS"  ENABLE;
-- ==========================================
