-- ==========================================

  CREATE TABLE "TREXONE_DATA"."COST_BASIS_SOURCE_VALUE"
   (	"COST_BASIS_SOURCE_VALUE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"COST_BASIS_SOURCE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE,
	"TERMINATION_DATE" DATE,
	"COST" NUMBER(17,6),
	"NDC_NUMBER" VARCHAR2(11),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_COST_BASIS_SOURCE_01" FOREIGN KEY ("COST_BASIS_SOURCE_NUM")
	  REFERENCES "TREXONE_DATA"."COST_BASIS_SOURCE" ("COST_BASIS_SOURCE_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_COST_BASIS_SOURCE_VALUE" ON "TREXONE_DATA"."COST_BASIS_SOURCE_VALUE" ("COST_BASIS_SOURCE_VALUE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."COST_BASIS_SOURCE_VALUE" ADD CONSTRAINT "PK_COST_BASIS_SOURCE_VALUE" PRIMARY KEY ("COST_BASIS_SOURCE_VALUE_NUM")
  USING INDEX "TREXONE_DATA"."PK_COST_BASIS_SOURCE_VALUE"  ENABLE;
-- ==========================================
