-- ==========================================

  CREATE TABLE "TREXONE_DATA"."COUNSELING_NOTE"
   (	"COUNSELING_NOTE_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NOTE_TEXT" VARCHAR2(4000) NOT NULL ENABLE,
	"CREATE_USER" NUMBER(18,0) NOT NULL ENABLE,
	"CREATE_DATE" DATE,
	"PRIORITY_INDICATOR" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_RX_02" FOREIGN KEY ("RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_BASE" ("RX_RECORD_NUM") ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_04" FOREIGN KEY ("CREATE_USER")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE INDEX "TREXONE_DATA"."PK_COUNSELING_NOTE" ON "TREXONE_DATA"."COUNSELING_NOTE" ("COUNSELING_NOTE_SEQ")
  ;
ALTER TABLE "TREXONE_DATA"."COUNSELING_NOTE" ADD CONSTRAINT "PK_COUNSELING_NOTE" PRIMARY KEY ("COUNSELING_NOTE_SEQ")
  USING INDEX "TREXONE_DATA"."PK_COUNSELING_NOTE"  ENABLE;
-- ==========================================
