-- ==========================================

  CREATE TABLE "TREXONE_DATA"."COUNTRY"
   (	"CTRY_CODE" VARCHAR2(8) NOT NULL ENABLE,
	"NAME" VARCHAR2(30) NOT NULL ENABLE,
	"IS_STATE_REQD" CHAR(1) NOT NULL ENABLE,
	"INTL_PHONE_CODE" VARCHAR2(3),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ISO_CTRY_CODE" VARCHAR2(2),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_COUNTRY" ON "TREXONE_DATA"."COUNTRY" ("CTRY_CODE")
  ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."UC_COUNTRY_01" ON "TREXONE_DATA"."COUNTRY" ("ISO_CTRY_CODE")
  ;
ALTER TABLE "TREXONE_DATA"."COUNTRY" ADD CONSTRAINT "PK_COUNTRY" PRIMARY KEY ("CTRY_CODE")
  USING INDEX "TREXONE_DATA"."PK_COUNTRY"  ENABLE;
ALTER TABLE "TREXONE_DATA"."COUNTRY" ADD CONSTRAINT "UC_COUNTRY_01" UNIQUE ("ISO_CTRY_CODE")
  USING INDEX "TREXONE_DATA"."UC_COUNTRY_01"  ENABLE;
-- ==========================================
