-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CP_PRESCRIBER_ADDR_ERROR"
   (	"CP_PRESCRIBER_ADDR_ERROR_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CP_PRESCRIBER_ERROR_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ADDR_ID" VARCHAR2(20),
	"ORGNAME" VARCHAR2(100),
	"ADDR1" VARCHAR2(100),
	"ADDR2" VARCHAR2(100),
	"CITY" VARCHAR2(50),
	"STATE" VARCHAR2(20),
	"ZIP" VARCHAR2(20),
	"ZIP_SUFFIX" VARCHAR2(20),
	"COUNTRY_CODE" VARCHAR2(20),
	"PHONE" VARCHAR2(20),
	"FAX" VARCHAR2(20),
	"ADDRESS_DATE" VARCHAR2(20),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_CP_PRESCRIBER_ERROR_01" FOREIGN KEY ("CP_PRESCRIBER_ERROR_NUM")
	  REFERENCES "TREXONE_DATA"."CP_PRESCRIBER_ERROR" ("CP_PRESCRIBER_ERROR_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_CP_PRESCRIBER_ADDR_ERROR" ON "TREXONE_DATA"."CP_PRESCRIBER_ADDR_ERROR" ("CP_PRESCRIBER_ADDR_ERROR_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."CP_PRESCRIBER_ADDR_ERROR" ADD CONSTRAINT "PK_CP_PRESCRIBER_ADDR_ERROR" PRIMARY KEY ("CP_PRESCRIBER_ADDR_ERROR_NUM")
  USING INDEX "TREXONE_DATA"."PK_CP_PRESCRIBER_ADDR_ERROR"  ENABLE;
-- ==========================================
