-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CREDIT_CARD_STATUS"
   (	"CREDIT_CARD_STATUS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CARD_STATUS_DESC" VARCHAR2(100) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_CREDIT_CARD_STATUS" PRIMARY KEY ("CREDIT_CARD_STATUS_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
