-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CREDIT_CARD_TYPE"
   (	"CREDIT_CARD_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CARD_TYPE_DESC" VARCHAR2(100) NOT NULL ENABLE,
	"CARD_NUMBER_LENGTH" NUMBER(9,0) NOT NULL ENABLE,
	"CVV_NUMBER_LENGTH" NUMBER(9,0),
	"CARD_TYPE_STATUS" CHAR(1) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"CARD_TYPE_DESC_ABBREVIATION" VARCHAR2(10),
	 CONSTRAINT "PK_CREDIT_CARD_TYPE" PRIMARY KEY ("CREDIT_CARD_TYPE_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
