-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CSR_RXFILL_COMPOUND_DETAIL"
   (	"CSR_RXFILL_EXTRACT_NUM" NUMBER(20,0) NOT NULL ENABLE,
	"INGREDIENT_NDC_ID" VARCHAR2(15),
	"INGREDIENT_QUANTITY" NUMBER(14,3),
	"INGREDIENT_UNITS_CODE" NUMBER(2,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"INGREDIENT_DEA_SCHEDULE" VARCHAR2(2),
	 CONSTRAINT "PK_CSR_RXFILL_CMPD_DTL" PRIMARY KEY ("CSR_RXFILL_EXTRACT_NUM", "INGREDIENT_NDC_ID")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
