-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CSR_STATE"
   (	"CSR_STATE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CTRY_CODE" VARCHAR2(8) NOT NULL ENABLE,
	"STATE_CODE" VARCHAR2(2) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"CSR_ASAP_VERSION" VARCHAR2(90),
	"CSR_INCLUDE_SHIPPED_TO_STATE" CHAR(1) DEFAULT 'N' NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_STATE_02" FOREIGN KEY ("CTRY_CODE", "STATE_CODE")
	  REFERENCES "TREXONE_DATA"."STATE" ("CTRY_CODE", "STATE_CODE") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_CSR_STATE" ON "TREXONE_DATA"."CSR_STATE" ("CSR_STATE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."CSR_STATE" ADD CONSTRAINT "PK_CSR_STATE" PRIMARY KEY ("CSR_STATE_NUM")
  USING INDEX "TREXONE_DATA"."PK_CSR_STATE"  ENABLE;
-- ==========================================
