-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CSR_RXFILL_TP_DETAIL"
   (	"CSR_RXFILL_EXTRACT_NUM" NUMBER(20,0) NOT NULL ENABLE,
	"TP_PLAN_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_PLAN_CODE" VARCHAR2(12),
	"TP_PLAN_NAME" VARCHAR2(45),
	"TP_PLAN_TYPE" VARCHAR2(10),
	"TP_PLAN_COVERAGE" VARCHAR2(2),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"BILLING_ORDER" NUMBER(2,0) NOT NULL ENABLE,
	 CONSTRAINT "PK_CSR_RXFILL_TP_DETAIL" PRIMARY KEY ("CSR_RXFILL_EXTRACT_NUM", "TP_PLAN_NUM", "BILLING_ORDER")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
