-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CSR_PROPERTY"
   (	"CSR_PROPERTY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(255) NOT NULL ENABLE,
	"DEFAULT_VALUE" VARCHAR2(3000),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT sysdate NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_CSR_PROPERTY" PRIMARY KEY ("CSR_PROPERTY_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
