-- ==========================================

  CREATE TABLE "TREXONE_DATA"."CVS_STORE_PRICE_ZONE"
   (	"STORE_PRICE_ZONE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0),
	"GROUP_NUM" NUMBER(18,0),
	"STORE_NUMBER" VARCHAR2(5) NOT NULL ENABLE,
	"PRODUCT_GROUP_CODE" VARCHAR2(2) NOT NULL ENABLE,
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE,
	"TERM_DATE" DATE,
	"COST_BASIS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRICE_ZONE_CODE" VARCHAR2(2) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_COST_BASIS_01" FOREIGN KEY ("COST_BASIS_NUM")
	  REFERENCES "TREXONE_DATA"."COST_BASIS" ("COST_BASIS_NUM") ENABLE,
	 CONSTRAINT "FK_FACILITY_12" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_GROUPS_01" FOREIGN KEY ("GROUP_NUM")
	  REFERENCES "TREXONE_DATA"."GROUPS" ("GROUP_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_CVS_STORE_PRICE_ZONE" ON "TREXONE_DATA"."CVS_STORE_PRICE_ZONE" ("STORE_PRICE_ZONE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."CVS_STORE_PRICE_ZONE" ADD CONSTRAINT "PK_CVS_STORE_PRICE_ZONE" PRIMARY KEY ("STORE_PRICE_ZONE_NUM")
  USING INDEX "TREXONE_DATA"."PK_CVS_STORE_PRICE_ZONE"  ENABLE;
-- ==========================================
