-- ==========================================

  CREATE TABLE "TREXONE_DATA"."D_PRESCRIBER_ID"
   (	"PRESCRIBER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ID_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACTIVE_ID_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SOURCE_NUM" NUMBER(18,0),
	"ID_TYPE" VARCHAR2(20) NOT NULL ENABLE,
	"ID_TEXT" VARCHAR2(30),
	"ID_SUFFIX" VARCHAR2(20),
	"CTRY_CODE" VARCHAR2(8),
	"STATE_CODE" VARCHAR2(4),
	"STATUS" VARCHAR2(1) NOT NULL ENABLE,
	"EFFECTIVE_DATE" DATE,
	"EXPIRATION_DATE" DATE,
	"NUM_UPDATES" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"SOURCE_CODE" CHAR(1),
	"USE_FOR_BILLING" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"ESV_PRESCRIBER_ID" VARCHAR2(20),
	"REACTIVATE_DATE" DATE,
	"HAS_ESV_PRESCRIBER_ID" CHAR(1) GENERATED ALWAYS AS (DECODE("ESV_PRESCRIBER_ID",NULL,'N','Y')) VIRTUAL  NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_D_PRESCRIBER_ID" ON "TREXONE_DATA"."D_PRESCRIBER_ID" ("PRESCRIBER_NUM", "ID_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."D_PRESCRIBER_ID" ADD CONSTRAINT "PK_D_PRESCRIBER_ID" PRIMARY KEY ("PRESCRIBER_NUM", "ID_NUM")
  USING INDEX "TREXONE_DATA"."PK_D_PRESCRIBER_ID"  ENABLE;
-- ==========================================
