-- ==========================================

  CREATE TABLE "TREXONE_DATA"."D_PRESCRIBER_ADDRESS"
   (	"PRESCRIBER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRESCRIBER_ADDRESS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACTIVE_PRESCRIBER_ADDRESS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ADDRESS_LINK_NUM" NUMBER(18,0),
	"ADDRESS_NUM" NUMBER(18,0),
	"CSZ_NUM" NUMBER(18,0),
	"STATUS" CHAR(1) NOT NULL ENABLE,
	"SOURCE" NUMBER(18,0),
	"ADDRESS_TYPE_CODE" VARCHAR2(10) NOT NULL ENABLE,
	"IS_DEFAULT" CHAR(1),
	"DEA_NUMBER" VARCHAR2(30),
	"DEA_SUFFIX" VARCHAR2(20),
	"PRESCRIBER_ID_NUM" NUMBER(18,0),
	"DRUG_SCHEDULE" VARCHAR2(30),
	"PRACTICE_NAME" VARCHAR2(50),
	"ADDRESS1" VARCHAR2(100),
	"ADDRESS2" VARCHAR2(50),
	"CITY" VARCHAR2(40),
	"STATE" VARCHAR2(4),
	"CTRY_CODE" VARCHAR2(8),
	"ZIPCODE" VARCHAR2(20),
	"EMAIL_ADDRESS" VARCHAR2(256),
	"WEB_ADDRESS" VARCHAR2(256),
	"PRIMARY_CONTACT_TITLE" VARCHAR2(30),
	"PRIMARY_CONTACT_FIRST_NAME" VARCHAR2(30),
	"PRIMARY_CONTACT_MIDDLE_NAME" VARCHAR2(30),
	"PRIMARY_CONTACT_LAST_NAME" VARCHAR2(30),
	"NUM_UPDATES" NUMBER(18,0) NOT NULL ENABLE,
	"OWNER_NUM_UPDATES" NUMBER(18,0),
	"LINK_NUM_UPDATES" NUMBER(18,0),
	"ADDRESS_NUM_UPDATES" NUMBER(18,0),
	"CSZ_NUM_UPDATES" NUMBER(18,0),
	"DATESTAMP" DATE NOT NULL ENABLE,
	"PRESCRIBER_LOCATION" VARCHAR2(3),
	"SOURCE_CODE" CHAR(1),
	"CONTACT_METHOD_NUM" NUMBER(18,0),
	"PRIM_PHONE_AREA_CODE" VARCHAR2(4),
	"PRIM_PHONE_NUMBER" VARCHAR2(20),
	"PRIM_PHONE_EXT" VARCHAR2(6),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"IS_340B" CHAR(1),
	"ESV_PRESCRIBER_ID" VARCHAR2(50),
	"ESV_PRESCRIBER_ADDR_LOC_ID" VARCHAR2(10),
	"REACTIVATE_DATE" DATE,
	"HAS_ESV_PRESCRIBER_ID" CHAR(1) GENERATED ALWAYS AS (DECODE("ESV_PRESCRIBER_ID",NULL,'N','Y')) VIRTUAL  NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_D_PRESCRIBER_ADDRESS" ON "TREXONE_DATA"."D_PRESCRIBER_ADDRESS" ("PRESCRIBER_NUM", "PRESCRIBER_ADDRESS_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."D_PRESCRIBER_ADDRESS" ADD CONSTRAINT "PK_D_PRESCRIBER_ADDRESS" PRIMARY KEY ("PRESCRIBER_NUM", "PRESCRIBER_ADDRESS_NUM")
  USING INDEX "TREXONE_DATA"."PK_D_PRESCRIBER_ADDRESS"  ENABLE;
-- ==========================================
