-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DAILY_PRODUCT_SALES_SUMMARY"
   (	"PRODUCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACCUMULATION_DATE" DATE NOT NULL ENABLE,
	"ACCUMULATION_QTY" NUMBER(16,8) NOT NULL ENABLE,
	"CF_FACILITY_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"LOCK_AVOIDANCE_BUCKET" NUMBER(18,0),
	"ACCUMULATION_DATE_LOCAL" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_DAILY_PRODUCT_SALES_SUMMARY" PRIMARY KEY ("CF_FACILITY_KEY", "PRODUCT_NUM", "ACCUMULATION_DATE_LOCAL", "LOCK_AVOIDANCE_BUCKET")
  USING INDEX  ENABLE,
	 CONSTRAINT "CK_DAILY_PRODUCT_SALES_SUMM_01" CHECK (ACCUMULATION_DATE is not null) ENABLE NOVALIDATE,
	 CONSTRAINT "FK_CORE_FACILITY_5" FOREIGN KEY ("CF_FACILITY_KEY")
	  REFERENCES "TREXONE_DATA"."CORE_FACILITY" ("CF_FACILITY_KEY") ENABLE,
	 CONSTRAINT "FK_PRODUCT_40" FOREIGN KEY ("PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT" ("PRODUCT_NUM") ENABLE
   )
  PARTITION BY RANGE ("ACCUMULATION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
