-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DATA_TRANSFER_FILE"
   (	"DATA_TRANSFER_FILE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FILE_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"DATA_TRANSFER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DATA_TRANSFER_01" FOREIGN KEY ("DATA_TRANSFER_NUM")
	  REFERENCES "TREXONE_DATA"."DATA_TRANSFER" ("DATA_TRANSFER_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PKDATA_TRANSFER_FILE" ON "TREXONE_DATA"."DATA_TRANSFER_FILE" ("DATA_TRANSFER_FILE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DATA_TRANSFER_FILE" ADD CONSTRAINT "PKDATA_TRANSFER_FILE" PRIMARY KEY ("DATA_TRANSFER_FILE_NUM")
  USING INDEX "TREXONE_DATA"."PKDATA_TRANSFER_FILE"  ENABLE;
-- ==========================================
