-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DATA_GROUP_SYSTEM_USER"
   (	"DATA_GROUP_SYSTEM_USER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"SYSTEM_USER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"IS_ACTIVE" CHAR(1) NOT NULL ENABLE,
	"IS_DEFAULT" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DATA_GROUP_04" FOREIGN KEY ("DATA_GROUP")
	  REFERENCES "TREXONE_DATA"."DATA_GROUP" ("DATA_GROUP") ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_05" FOREIGN KEY ("SYSTEM_USER_NUM")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DATA_GROUP_SYSTEM_USER" ON "TREXONE_DATA"."DATA_GROUP_SYSTEM_USER" ("DATA_GROUP_SYSTEM_USER_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DATA_GROUP_SYSTEM_USER" ADD CONSTRAINT "PK_DATA_GROUP_SYSTEM_USER" PRIMARY KEY ("DATA_GROUP_SYSTEM_USER_NUM")
  USING INDEX "TREXONE_DATA"."PK_DATA_GROUP_SYSTEM_USER"  ENABLE;
-- ==========================================
