-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DATA_GROUP_LINK"
   (	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"PARENT_DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"DISTANCE_TO_PARENT" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DATA_GROUP_02" FOREIGN KEY ("DATA_GROUP")
	  REFERENCES "TREXONE_DATA"."DATA_GROUP" ("DATA_GROUP") ENABLE,
	 CONSTRAINT "FK_DATA_GROUP_03" FOREIGN KEY ("PARENT_DATA_GROUP")
	  REFERENCES "TREXONE_DATA"."DATA_GROUP" ("DATA_GROUP") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DATA_GROUP_LINK" ON "TREXONE_DATA"."DATA_GROUP_LINK" ("DATA_GROUP", "PARENT_DATA_GROUP", "DISTANCE_TO_PARENT")
  ;
ALTER TABLE "TREXONE_DATA"."DATA_GROUP_LINK" ADD CONSTRAINT "PK_DATA_GROUP_LINK" PRIMARY KEY ("DATA_GROUP", "PARENT_DATA_GROUP", "DISTANCE_TO_PARENT")
  USING INDEX "TREXONE_DATA"."PK_DATA_GROUP_LINK"  ENABLE;
-- ==========================================
