-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DATA_GROUP"
   (	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(30),
	"TREE_TYPE" CHAR(1),
	"NODE_TYPE" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."IU_DATA_GROUP_1" ON "TREXONE_DATA"."DATA_GROUP" ("NAME", "TREE_TYPE", "ERX_CLIENT_ID")
  ;
  CREATE INDEX "TREXONE_DATA"."PK_DATA_GROUP" ON "TREXONE_DATA"."DATA_GROUP" ("DATA_GROUP", "TREE_TYPE")
  ;
ALTER TABLE "TREXONE_DATA"."DATA_GROUP" ADD CONSTRAINT "PK_DATA_GROUP" PRIMARY KEY ("DATA_GROUP")
  USING INDEX "TREXONE_DATA"."PK_DATA_GROUP"  ENABLE;
ALTER TABLE "TREXONE_DATA"."DATA_GROUP" ADD CONSTRAINT "UC_DATA_GROUP_1" UNIQUE ("NAME", "TREE_TYPE", "ERX_CLIENT_ID")
  USING INDEX "TREXONE_DATA"."IU_DATA_GROUP_1"  ENABLE;
-- ==========================================
