-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DAW_CODE"
   (	"DAW_CODE" CHAR(1) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(100) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DAW_CODE" ON "TREXONE_DATA"."DAW_CODE" ("DAW_CODE")
  ;
ALTER TABLE "TREXONE_DATA"."DAW_CODE" ADD CONSTRAINT "PK_DAW_CODE" PRIMARY KEY ("DAW_CODE")
  USING INDEX "TREXONE_DATA"."PK_DAW_CODE"  ENABLE;
-- ==========================================
