-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DELIVERY"
   (	"DELIVERY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DELIVERY_STOP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DELIVERY_DATESTAMP" DATE NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DELIVERY_STOP_1" FOREIGN KEY ("DELIVERY_STOP_NUM")
	  REFERENCES "TREXONE_DATA"."DELIVERY_STOP" ("DELIVERY_STOP_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DELIVERY" ON "TREXONE_DATA"."DELIVERY" ("DELIVERY_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DELIVERY" ADD CONSTRAINT "PK_DELIVERY" PRIMARY KEY ("DELIVERY_NUM")
  USING INDEX "TREXONE_DATA"."PK_DELIVERY"  ENABLE;
-- ==========================================
