-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DESTINATION"
   (	"DESTINATION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(45),
	"IS_SWITCH" CHAR(1) NOT NULL ENABLE,
	"STATUS" CHAR(1) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DESTINATION" ON "TREXONE_DATA"."DESTINATION" ("DESTINATION_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DESTINATION" ADD CONSTRAINT "PK_DESTINATION" PRIMARY KEY ("DESTINATION_NUM")
  USING INDEX "TREXONE_DATA"."PK_DESTINATION"  ENABLE;
-- ==========================================
