-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DEVICE_TYPE"
   (	"DEVICE_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(50) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"CLASSNAME" VARCHAR2(100) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DEVICE_TYPE" ON "TREXONE_DATA"."DEVICE_TYPE" ("DEVICE_TYPE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DEVICE_TYPE" ADD CONSTRAINT "PK_DEVICE_TYPE" PRIMARY KEY ("DEVICE_TYPE_NUM")
  USING INDEX "TREXONE_DATA"."PK_DEVICE_TYPE"  ENABLE;
-- ==========================================
