-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DEVICE_CLASS"
   (	"DEVICE_CLASS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DEVICE_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(50) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(1000),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DEVICE_TYPE_03" FOREIGN KEY ("DEVICE_TYPE_NUM")
	  REFERENCES "TREXONE_DATA"."DEVICE_TYPE" ("DEVICE_TYPE_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DEVICE_CLASS" ON "TREXONE_DATA"."DEVICE_CLASS" ("DEVICE_CLASS_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DEVICE_CLASS" ADD CONSTRAINT "PK_DEVICE_CLASS" PRIMARY KEY ("DEVICE_CLASS_NUM")
  USING INDEX "TREXONE_DATA"."PK_DEVICE_CLASS"  ENABLE;
-- ==========================================
