-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DEVICE"
   (	"DEVICE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DEVICE_CLASS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(50) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(1000),
	"ADDRESS" VARCHAR2(200),
	"PORT" NUMBER(6,0),
	"PATH" VARCHAR2(200),
	"IS_ACTIVE" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DEVICE_CLASS_02" FOREIGN KEY ("DEVICE_CLASS_NUM")
	  REFERENCES "TREXONE_DATA"."DEVICE_CLASS" ("DEVICE_CLASS_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DEVICE" ON "TREXONE_DATA"."DEVICE" ("DEVICE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DEVICE" ADD CONSTRAINT "PK_DEVICE" PRIMARY KEY ("DEVICE_NUM")
  USING INDEX "TREXONE_DATA"."PK_DEVICE"  ENABLE;
-- ==========================================
