-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DEVICE_PROPERTY"
   (	"DEVICE_PROPERTY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DEVICE_NUM" NUMBER(18,0),
	"DEVICE_CLASS_NUM" NUMBER(18,0),
	"DEVICE_PROPERTY_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"VALUE" VARCHAR2(2000) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DEVICE_01" FOREIGN KEY ("DEVICE_NUM")
	  REFERENCES "TREXONE_DATA"."DEVICE" ("DEVICE_NUM") ENABLE,
	 CONSTRAINT "FK_DEVICE_CLASS_01" FOREIGN KEY ("DEVICE_CLASS_NUM")
	  REFERENCES "TREXONE_DATA"."DEVICE_CLASS" ("DEVICE_CLASS_NUM") ENABLE,
	 CONSTRAINT "FK_DEVICE_PROPERTY_TYPE_01" FOREIGN KEY ("DEVICE_PROPERTY_TYPE_NUM")
	  REFERENCES "TREXONE_DATA"."DEVICE_PROPERTY_TYPE" ("DEVICE_PROPERTY_TYPE_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DEVICE_PROPERTY" ON "TREXONE_DATA"."DEVICE_PROPERTY" ("DEVICE_PROPERTY_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DEVICE_PROPERTY" ADD CONSTRAINT "PK_DEVICE_PROPERTY" PRIMARY KEY ("DEVICE_PROPERTY_NUM")
  USING INDEX "TREXONE_DATA"."PK_DEVICE_PROPERTY"  ENABLE;
-- ==========================================
