-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DEVICE_COMPONENT"
   (	"DEVICE_COMPONENT_NUM" NUMBER(10,0) NOT NULL ENABLE,
	"DEVICE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(50) NOT NULL ENABLE,
	"TYPE" VARCHAR2(50),
	"DESCRIPTION" VARCHAR2(1000),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DEVICE_03" FOREIGN KEY ("DEVICE_NUM")
	  REFERENCES "TREXONE_DATA"."DEVICE" ("DEVICE_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DEVICE_COMPONENT" ON "TREXONE_DATA"."DEVICE_COMPONENT" ("DEVICE_COMPONENT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DEVICE_COMPONENT" ADD CONSTRAINT "PK_DEVICE_COMPONENT" PRIMARY KEY ("DEVICE_COMPONENT_NUM")
  USING INDEX "TREXONE_DATA"."PK_DEVICE_COMPONENT"  ENABLE;
-- ==========================================
