-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DISPENSING_PROPERTY"
   (	"DISPENSING_SERVICE_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"DISPENSING_TEMPLATE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DISPENSING_PROPERTY_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"PROPERTY_NAME" VARCHAR2(45) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(255),
	"DEFAULT_VALUE" VARCHAR2(250 CHAR),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DISPENSING_SERVICE_02" FOREIGN KEY ("DISPENSING_SERVICE_SEQ", "DISPENSING_TEMPLATE_NUM")
	  REFERENCES "TREXONE_DATA"."DISPENSING_SERVICE" ("DISPENSING_SERVICE_SEQ", "DISPENSING_TEMPLATE_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DISPENSING_PROPERTY" ON "TREXONE_DATA"."DISPENSING_PROPERTY" ("DISPENSING_SERVICE_SEQ", "DISPENSING_TEMPLATE_NUM", "DISPENSING_PROPERTY_SEQ")
  ;
ALTER TABLE "TREXONE_DATA"."DISPENSING_PROPERTY" ADD CONSTRAINT "PK_DISPENSING_PROPERTY" PRIMARY KEY ("DISPENSING_SERVICE_SEQ", "DISPENSING_TEMPLATE_NUM", "DISPENSING_PROPERTY_SEQ")
  USING INDEX "TREXONE_DATA"."PK_DISPENSING_PROPERTY"  ENABLE;
-- ==========================================
