-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DISPENSING_PROPERTY_VALUE"
   (	"DISPENSING_TEMPLATE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DISPENSING_SERVICE_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"DISPENSING_PROPERTY_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"DISPENSING_PROFILE_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"PROPERTY_VALUE" VARCHAR2(250 CHAR),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DISPENSING_PROFILE_02" FOREIGN KEY ("DISPENSING_TEMPLATE_NUM", "DISPENSING_PROFILE_SEQ")
	  REFERENCES "TREXONE_DATA"."DISPENSING_PROFILE" ("DISPENSING_TEMPLATE_NUM", "DISPENSING_PROFILE_SEQ") ENABLE,
	 CONSTRAINT "FK_DISPENSING_PROPERTY_01" FOREIGN KEY ("DISPENSING_SERVICE_SEQ", "DISPENSING_TEMPLATE_NUM", "DISPENSING_PROPERTY_SEQ")
	  REFERENCES "TREXONE_DATA"."DISPENSING_PROPERTY" ("DISPENSING_SERVICE_SEQ", "DISPENSING_TEMPLATE_NUM", "DISPENSING_PROPERTY_SEQ") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DISPENSING_PROPERTY_VALUE" ON "TREXONE_DATA"."DISPENSING_PROPERTY_VALUE" ("DISPENSING_TEMPLATE_NUM", "DISPENSING_SERVICE_SEQ", "DISPENSING_PROPERTY_SEQ", "DISPENSING_PROFILE_SEQ")
  ;
ALTER TABLE "TREXONE_DATA"."DISPENSING_PROPERTY_VALUE" ADD CONSTRAINT "PK_DISPENSING_PROPERTY_VALUE" PRIMARY KEY ("DISPENSING_TEMPLATE_NUM", "DISPENSING_SERVICE_SEQ", "DISPENSING_PROPERTY_SEQ", "DISPENSING_PROFILE_SEQ")
  USING INDEX "TREXONE_DATA"."PK_DISPENSING_PROPERTY_VALUE"  ENABLE;
-- ==========================================
