-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DOC_VERSION"
   (	"DOC_VERSION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DOC_FORMAT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"VERSION" VARCHAR2(18),
	"LAYOUT_STREAM" BLOB,
	"MARSHALLING_TEMPLATE" CLOB,
	"STYLESHEET" CLOB,
	"CHECK_IN_DATE" DATE,
	"CHECK_OUT_DATE" DATE,
	"CHECK_OUT_USER" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DOC_FORMAT_02" FOREIGN KEY ("DOC_FORMAT_NUM")
	  REFERENCES "TREXONE_DATA"."DOC_FORMAT" ("DOC_FORMAT_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DOC_VERSION" ON "TREXONE_DATA"."DOC_VERSION" ("DOC_VERSION_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DOC_VERSION" ADD CONSTRAINT "PK_DOC_VERSION" PRIMARY KEY ("DOC_VERSION_NUM")
  USING INDEX "TREXONE_DATA"."PK_DOC_VERSION"  ENABLE;
-- ==========================================
