-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DOC_PACKING"
   (	"DOC_PACKING_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ITEM_SEQ" NUMBER(18,0),
	"DOC_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"IS_PACKED" CHAR(1) DEFAULT 'N' NOT NULL ENABLE,
	"IS_PRINTED" CHAR(1) DEFAULT 'N' NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"PACKAGE_NUM" NUMBER(18,0),
	 CONSTRAINT "PK_DOC_PACKING" PRIMARY KEY ("DOC_PACKING_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_DOC_TYPE_02" FOREIGN KEY ("DOC_TYPE_NUM")
	  REFERENCES "TREXONE_DATA"."DOC_TYPE" ("DOC_TYPE_NUM") ENABLE,
	 CONSTRAINT "FK_ORDER_RECORD_03" FOREIGN KEY ("ORDER_NUM")
	  REFERENCES "TREXONE_DATA"."ORDER_RECORD_BASE" ("ORDER_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_PACKAGE_02" FOREIGN KEY ("PACKAGE_NUM")
	  REFERENCES "TREXONE_DATA"."PACKAGE" ("PACKAGE_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
