-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DOC_CURRENT_VERSION"
   (	"DOC_CURRENT_VERSION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"DOC_VERSION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DOC_FORMAT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"END_DATE" DATE,
	"START_DATE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DATA_GROUP_05" FOREIGN KEY ("DATA_GROUP")
	  REFERENCES "TREXONE_DATA"."DATA_GROUP" ("DATA_GROUP") ENABLE,
	 CONSTRAINT "FK_DOC_FORMAT_01" FOREIGN KEY ("DOC_FORMAT_NUM")
	  REFERENCES "TREXONE_DATA"."DOC_FORMAT" ("DOC_FORMAT_NUM") ENABLE,
	 CONSTRAINT "FK_DOC_VERSION_05" FOREIGN KEY ("DOC_VERSION_NUM")
	  REFERENCES "TREXONE_DATA"."DOC_VERSION" ("DOC_VERSION_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DOC_CURRENT_VERSION" ON "TREXONE_DATA"."DOC_CURRENT_VERSION" ("DOC_CURRENT_VERSION_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DOC_CURRENT_VERSION" ADD CONSTRAINT "PK_DOC_CURRENT_VERSION" PRIMARY KEY ("DOC_CURRENT_VERSION_NUM")
  USING INDEX "TREXONE_DATA"."PK_DOC_CURRENT_VERSION"  ENABLE;
-- ==========================================
