-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DSCSA_SHIPPED_ITEM"
   (	"DSCSA_SHIPPED_ITEM_NUM" NUMBER(18,0),
	"DSCSA_DOCUMENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"GTIN" VARCHAR2(100),
	"NDC" VARCHAR2(20),
	"LOT_NUMBER" VARCHAR2(100),
	"SERIAL_NUMBER" VARCHAR2(100),
	"EXPIRATION_DATE" VARCHAR2(10),
	"PARTITION_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"DOCUMENT_ID" VARCHAR2(100),
	 CONSTRAINT "PK_DSCSA_SHIPPED_ITEM" PRIMARY KEY ("DSCSA_SHIPPED_ITEM_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_81" FOREIGN KEY ("SYS_USER")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_DSCSA_DOCUMENT_01" FOREIGN KEY ("DSCSA_DOCUMENT_NUM")
	  REFERENCES "TREXONE_DATA"."DSCSA_DOCUMENT" ("DSCSA_DOCUMENT_NUM") ENABLE NOVALIDATE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTOYMINTERVAL(3,'MONTH')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
