-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DT_PATIENT"
   (	"DT_TX_NUM" NUMBER(19,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FIRST_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"MIDDLE_INITIAL" VARCHAR2(30),
	"LAST_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"GENDER_CODE" CHAR(1) NOT NULL ENABLE,
	"ADDRESS" VARCHAR2(100) NOT NULL ENABLE,
	"CITY" VARCHAR2(40) NOT NULL ENABLE,
	"STATE_CODE" CHAR(2) NOT NULL ENABLE,
	"ZIP_CODE" VARCHAR2(20),
	"PHONE" VARCHAR2(20),
	"DATE_OF_BIRTH" DATE,
	"PATIENT_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"PATIENT_ID" VARCHAR2(30),
	"PARTNER_CODE" VARCHAR2(10),
	 CONSTRAINT "FK_PATIENT_23" FOREIGN KEY ("PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE,
	 CONSTRAINT "FK_DT_TX_03" FOREIGN KEY ("DT_TX_NUM", "FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."DT_TX" ("DT_TX_NUM", "FACILITY_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DT_PATIENT" ON "TREXONE_DATA"."DT_PATIENT" ("DT_TX_NUM", "FACILITY_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DT_PATIENT" ADD CONSTRAINT "PK_DT_PATIENT" PRIMARY KEY ("DT_TX_NUM", "FACILITY_NUM")
  USING INDEX "TREXONE_DATA"."PK_DT_PATIENT"  ENABLE;
-- ==========================================
