-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DT_POS_FINALIZATION"
   (	"DT_POS_FINALIZATION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_NUMBER" VARCHAR2(20),
	"FACILITY_NUM" NUMBER(18,0),
	"REFILL_NUMBER" NUMBER(18,0),
	"TXN_TYPE" CHAR(1),
	"REGISTER_TXN" NUMBER(9,0),
	"REGISTER_TXN_SEQ" NUMBER(9,0),
	"POS_USERID" VARCHAR2(20),
	"POS_AMOUNT" NUMBER(17,6),
	"POS_DATESTAMP" DATE,
	"PATIENT_PAY_SRC" CHAR(1),
	"PRICE_OVERRIDE_RSN_CD" CHAR(2),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"POS_TAX_AMOUNT" NUMBER(17,6),
	"REGISTER_NUM" NUMBER(9,0),
	"PARTIAL_FILL_NUM" NUMBER(2,0),
	"POS_FINALIZATION_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_DT_POS_FINALIZATION" PRIMARY KEY ("DT_POS_FINALIZATION_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "CK_DT_POS_FINALIZATION_01" CHECK (PARTITION_DATE is not null) ENABLE NOVALIDATE,
	 CONSTRAINT "FK_POS_FINALIZATION_01" FOREIGN KEY ("POS_FINALIZATION_NUM")
	  REFERENCES "TREXONE_DATA"."POS_FINALIZATION" ("POS_FINALIZATION_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
