-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DT_USER_LOG"
   (	"DT_USER_LOG_NUM" NUMBER(10,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"LOGIN_TIME" DATE,
	"LOGOUT_TIME" DATE,
	"USER_ID" VARCHAR2(30),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "CK_DT_USER_LOG_01" CHECK (DATESTAMP is not null) ENABLE NOVALIDATE,
	 CONSTRAINT "FK_FACILITY_52" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE
   )
  PARTITION BY RANGE ("DATESTAMP")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DT_USER_LOG" ON "TREXONE_DATA"."DT_USER_LOG" ("DT_USER_LOG_NUM", "FACILITY_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DT_USER_LOG" ADD CONSTRAINT "PK_DT_USER_LOG" PRIMARY KEY ("DT_USER_LOG_NUM", "FACILITY_NUM")
  USING INDEX "TREXONE_DATA"."PK_DT_USER_LOG"  ENABLE;
-- ==========================================
