-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DUR_CONFLICT_DRUG_DOSE"
   (	"DUR_CONFLICT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"STATUS_TEXT" VARCHAR2(255),
	"STATUS" VARCHAR2(15),
	"DATABASE_SOURCE" CHAR(5),
	"DRUG_CUSTOM_ID" VARCHAR2(15),
	"DRUG_DESC" VARCHAR2(50),
	"DRUG_ID" VARCHAR2(15),
	"PATIENT_AGE" NUMBER(9,0),
	"PATIENT_IS_ADULT" CHAR(1),
	"PATIENT_WEIGHT_KG" NUMBER(16,0),
	"PATIENT_GENDER" CHAR(1),
	"PATIENT_SURFACE_AREA" NUMBER(9,0),
	"PATIENT_CONFIGURABLE_AGE" NUMBER(9,0),
	"PATIENT_DOSING_AGE" NUMBER(9,0),
	"PATIENT_MIN_MAX_WEIGHT" VARCHAR2(30),
	"DAILY_DISPENSE_QTY" NUMBER(16,0),
	"DAILY_DISPENSE_QTY_DIVIATION" NUMBER(16,0),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DUR_CONFLICT_05" FOREIGN KEY ("DUR_CONFLICT_NUM")
	  REFERENCES "TREXONE_DATA"."DUR_CONFLICT" ("DUR_CONFLICT_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DUR_CONFLICT_DRUG_DOSE" ON "TREXONE_DATA"."DUR_CONFLICT_DRUG_DOSE" ("DUR_CONFLICT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DUR_CONFLICT_DRUG_DOSE" ADD CONSTRAINT "PK_DUR_CONFLICT_DRUG_DOSE" PRIMARY KEY ("DUR_CONFLICT_NUM")
  USING INDEX "TREXONE_DATA"."PK_DUR_CONFLICT_DRUG_DOSE"  ENABLE;
-- ==========================================
