-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DUR_CONFLICT_DUPL_DRUG"
   (	"DUR_CONFLICT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0),
	"ALLOWANCE" NUMBER(9,0),
	"CLASS_DESC" VARCHAR2(255),
	"CLASS_ID" VARCHAR2(15),
	"DRUG_NAME" VARCHAR2(50),
	"NDC" VARCHAR2(20),
	"SCREEN_MESSAGE" VARCHAR2(4000),
	"FACILITY_NUM" NUMBER(18,0),
	"RX_FILL_SEQ" NUMBER(18,0),
	"PATIENT_EXTRA_MEDICATION_NUM" NUMBER(18,0),
	"IS_RXFILL" CHAR(1),
	"RX_DAYS_SUPPLY" NUMBER(9,0),
	"RX_DATE_LAST_FILLED" DATE,
	"RX_PICKUP_DATE" DATE,
	"RX_DATE_WRITTEN" DATE,
	"RX_IS_COMPOUND" CHAR(1),
	"RX_PRESCRIBER_NAME" VARCHAR2(100),
	"RX_PRESCRIBER_PHONE_NUM" VARCHAR2(30),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DUR_CONFLICT_08" FOREIGN KEY ("DUR_CONFLICT_NUM")
	  REFERENCES "TREXONE_DATA"."DUR_CONFLICT" ("DUR_CONFLICT_NUM") ENABLE,
	 CONSTRAINT "FK_FACILITY_14" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_RX_04" FOREIGN KEY ("RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_BASE" ("RX_RECORD_NUM") ENABLE,
	 CONSTRAINT "FK_PATIENT_PERM_RX_02" FOREIGN KEY ("PATIENT_EXTRA_MEDICATION_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT_PERM_RX" ("PATIENT_PERM_RX_NUM") ENABLE NOVALIDATE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DUR_CONFLICT_DUPL_DRUG" ON "TREXONE_DATA"."DUR_CONFLICT_DUPL_DRUG" ("DUR_CONFLICT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DUR_CONFLICT_DUPL_DRUG" ADD CONSTRAINT "PK_DUR_CONFLICT_DUPL_DRUG" PRIMARY KEY ("DUR_CONFLICT_NUM")
  USING INDEX "TREXONE_DATA"."PK_DUR_CONFLICT_DUPL_DRUG"  ENABLE;
-- ==========================================
