-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DUR_CONFLICT_ERROR"
   (	"DUR_CONFLICT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0),
	"DRUG_NAME" VARCHAR2(50),
	"MESSAGE" VARCHAR2(1023),
	"DRUG_RX_RECORD_NUM" NUMBER(18,0),
	"NDC" VARCHAR2(20),
	"FACILITY_NUM" NUMBER(18,0),
	"RX_FILL_SEQ" NUMBER(18,0),
	"PATIENT_EXTRA_MEDICATION_NUM" NUMBER(18,0),
	"IS_RXFILL" CHAR(1),
	"RX_DAYS_SUPPLY" NUMBER(9,0),
	"DATE_OF_SERVICE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"RX_NUMBER" VARCHAR2(20),
	"PRODUCT_NAME" VARCHAR2(50),
	"PRODUCT_ID_TYPE" NUMBER(9,0),
	"IS_PROFILE_PRODUCT" CHAR(1),
	"UNKNOWN_ID" VARCHAR2(25),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DUR_CONFLICT_09" FOREIGN KEY ("DUR_CONFLICT_NUM")
	  REFERENCES "TREXONE_DATA"."DUR_CONFLICT" ("DUR_CONFLICT_NUM") ENABLE,
	 CONSTRAINT "FK_FACILITY_16" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_RX_FILL_05" FOREIGN KEY ("RX_FILL_SEQ", "RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_FILL" ("RX_FILL_SEQ", "RX_RECORD_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DUR_CONFLICT_ERROR" ON "TREXONE_DATA"."DUR_CONFLICT_ERROR" ("DUR_CONFLICT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DUR_CONFLICT_ERROR" ADD CONSTRAINT "PK_DUR_CONFLICT_ERROR" PRIMARY KEY ("DUR_CONFLICT_NUM")
  USING INDEX "TREXONE_DATA"."PK_DUR_CONFLICT_ERROR"  ENABLE;
-- ==========================================
