-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DUR_CONFLICT_DRUG_FOOD"
   (	"DUR_CONFLICT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"MESSAGE" VARCHAR2(255),
	"DESCRIPTION" VARCHAR2(255),
	"DRUG_CUSTOM_ID" VARCHAR2(15),
	"DRUG_DESC" VARCHAR2(50),
	"DRUG_ID" VARCHAR2(15),
	"ID" VARCHAR2(15),
	"DRUG_TYPE" VARCHAR2(25),
	"MONOGRAPH_ID" VARCHAR2(15),
	"SCREEN_MESSAGE" VARCHAR2(4000),
	"SIGNIFICANCE" CHAR(5),
	"USER_DEFINED_CATEGORY" CHAR(5),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"SEVERITY_TEXT" VARCHAR2(200),
	"DOCUMENTATION_LEVEL" VARCHAR2(50),
	"MECHANISM_OF_ACTION" CLOB,
	"CLINICAL_EFFECTS" CLOB,
	"PATIENT_MANAGEMENT" CLOB,
	"MANAGEMENT_LEVEL_CODE" VARCHAR2(5),
	"AVOIDANCE_LEVEL" VARCHAR2(50),
	"ONSET_TEXT" VARCHAR2(50),
	 CONSTRAINT "FK_DUR_CONFLICT_07" FOREIGN KEY ("DUR_CONFLICT_NUM")
	  REFERENCES "TREXONE_DATA"."DUR_CONFLICT" ("DUR_CONFLICT_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DUR_CONFLICT_DRUG_FOOD" ON "TREXONE_DATA"."DUR_CONFLICT_DRUG_FOOD" ("DUR_CONFLICT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DUR_CONFLICT_DRUG_FOOD" ADD CONSTRAINT "PK_DUR_CONFLICT_DRUG_FOOD" PRIMARY KEY ("DUR_CONFLICT_NUM")
  USING INDEX "TREXONE_DATA"."PK_DUR_CONFLICT_DRUG_FOOD"  ENABLE;
-- ==========================================
