-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DUR_CONFLICT_3RD_PARTY"
   (	"DUR_CONFLICT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"IN_CHAIN_FLAG" CHAR(1),
	"THIRD_PARTY_NAME" VARCHAR2(200),
	"AUTO_RESPONSE_SENT" CHAR(1),
	"REASON_FOR_SERVICE_CODE" VARCHAR2(2),
	"CLINICAL_SIGNIFICANCE_CODE" CHAR(1),
	"PHARMACY" CHAR(1),
	"CONFLICT_DATE" DATE,
	"QUANTITY" NUMBER(13,3),
	"DATABASE_SOURCE" CHAR(1),
	"PRESCRIBER" CHAR(1),
	"MESSAGE" VARCHAR2(1023),
	"OVERFLOW" CHAR(1),
	"CLAIM_BILLING_ORDER" NUMBER(9,0),
	"TP_MESSAGE_NUM" NUMBER(18,0),
	"TP_ITEM_CLAIM_NUM" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"CLAIM_STATUS" VARCHAR2(25),
	"PROF_CODE_IN_TP_CLAIM" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"DUR_ADDITIONAL_TEXT" VARCHAR2(100),
	 CONSTRAINT "FK_DUR_CONFLICT_01" FOREIGN KEY ("DUR_CONFLICT_NUM")
	  REFERENCES "TREXONE_DATA"."DUR_CONFLICT" ("DUR_CONFLICT_NUM") ENABLE,
	 CONSTRAINT "FK_TP_ITEM_CLAIM_01" FOREIGN KEY ("TP_ITEM_CLAIM_NUM")
	  REFERENCES "TREXONE_DATA"."TP_ITEM_CLAIM" ("TP_ITEM_CLAIM_NUM") ENABLE,
	 CONSTRAINT "FK_TP_MESSAGE_01" FOREIGN KEY ("TP_MESSAGE_NUM")
	  REFERENCES "TREXONE_DATA"."TP_MESSAGE" ("TP_MESSAGE_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DUR_CONFLICT_3RD_PARTY" ON "TREXONE_DATA"."DUR_CONFLICT_3RD_PARTY" ("DUR_CONFLICT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DUR_CONFLICT_3RD_PARTY" ADD CONSTRAINT "PK_DUR_CONFLICT_3RD_PARTY" PRIMARY KEY ("DUR_CONFLICT_NUM")
  USING INDEX "TREXONE_DATA"."PK_DUR_CONFLICT_3RD_PARTY"  ENABLE;
-- ==========================================
