-- ==========================================

  CREATE TABLE "TREXONE_DATA"."DUR_CONFLICT_SIDE_EFFECTS"
   (	"DUR_CONFLICT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CONDITION_CUSTOM_ID" VARCHAR2(15),
	"CONDITION_DESC" VARCHAR2(255),
	"CONDITION_ID" VARCHAR2(15),
	"CONDITION_INTERNAL_ID" VARCHAR2(15),
	"CONTACT_PHYSICIAN_FLAG" CHAR(1),
	"CONDITION_DETAIL_DESC" VARCHAR2(511),
	"DRUG_DETAIL_DESC" VARCHAR2(255),
	"DRUG_CUSTOM_ID" VARCHAR2(15),
	"DRUG_DESC" VARCHAR2(50),
	"DRUG_ID" VARCHAR2(15),
	"FREQ_CODE" CHAR(5),
	"DESCRIPTION" VARCHAR2(255),
	"ID" VARCHAR2(15),
	"HYPERSENSITIVITY_FLAG" CHAR(1),
	"LAB_TEST_CODE" CHAR(5),
	"SCREEN_MESSAGE" VARCHAR2(4000),
	"SEVERITY" CHAR(5),
	"VISIBILITY_CODE" CHAR(5),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"SEVERITY_TEXT" VARCHAR2(200),
	 CONSTRAINT "FK_DUR_CONFLICT_16" FOREIGN KEY ("DUR_CONFLICT_NUM")
	  REFERENCES "TREXONE_DATA"."DUR_CONFLICT" ("DUR_CONFLICT_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_DUR_CONFLICT_SIDE_EFFECTS" ON "TREXONE_DATA"."DUR_CONFLICT_SIDE_EFFECTS" ("DUR_CONFLICT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."DUR_CONFLICT_SIDE_EFFECTS" ADD CONSTRAINT "PK_DUR_CONFLICT_SIDE_EFFECTS" PRIMARY KEY ("DUR_CONFLICT_NUM")
  USING INDEX "TREXONE_DATA"."PK_DUR_CONFLICT_SIDE_EFFECTS"  ENABLE;
-- ==========================================
