-- ==========================================

  CREATE TABLE "TREXONE_DATA"."EDI_VERSION_TXN"
   (	"EDI_VERSION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"EDI_TRANSACTION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_EDI_TRANSACTION_01" FOREIGN KEY ("EDI_TRANSACTION_NUM")
	  REFERENCES "TREXONE_DATA"."EDI_TRANSACTION" ("EDI_TRANSACTION_NUM") ENABLE,
	 CONSTRAINT "FK_EDI_VERSION_02" FOREIGN KEY ("EDI_VERSION_NUM")
	  REFERENCES "TREXONE_DATA"."EDI_VERSION" ("EDI_VERSION_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PKEDI_VERSION_TXN" ON "TREXONE_DATA"."EDI_VERSION_TXN" ("EDI_VERSION_NUM", "EDI_TRANSACTION_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."EDI_VERSION_TXN" ADD CONSTRAINT "PKEDI_VERSION_TXN" PRIMARY KEY ("EDI_VERSION_NUM", "EDI_TRANSACTION_NUM")
  USING INDEX "TREXONE_DATA"."PKEDI_VERSION_TXN"  ENABLE;
-- ==========================================
