-- ==========================================

  CREATE TABLE "TREXONE_DATA"."EIF_PEER"
   (	"EIF_PEER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"AS2_PEER_NUM" NUMBER(18,0),
	"FTP_PEER_NUM" NUMBER(18,0),
	"SECURITY_CERTIFICATE_NUM" NUMBER(18,0),
	"MAX_RETRIES" NUMBER(3,0) DEFAULT 3,
	"RETRY_DELAY" NUMBER(6,0),
	"NEXT_MESSAGE_ID" NUMBER(10,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_AS2_PEER_1" FOREIGN KEY ("AS2_PEER_NUM")
	  REFERENCES "TREXONE_DATA"."AS2_PEER" ("AS2_PEER_NUM") ENABLE,
	 CONSTRAINT "FK_FTP_PEER_1" FOREIGN KEY ("FTP_PEER_NUM")
	  REFERENCES "TREXONE_DATA"."FTP_PEER" ("FTP_PEER_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_EIF_PEER" ON "TREXONE_DATA"."EIF_PEER" ("EIF_PEER_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."EIF_PEER" ADD CONSTRAINT "PK_EIF_PEER" PRIMARY KEY ("EIF_PEER_NUM")
  USING INDEX "TREXONE_DATA"."PK_EIF_PEER"  ENABLE;
-- ==========================================
