-- ==========================================

  CREATE TABLE "TREXONE_DATA"."EIF_PEER_CERTIFICATE"
   (	"EIF_PEER_CERTIFICATE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"EIF_PEER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SECURITY_CERTIFICATE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"IS_VALID" CHAR(1),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_EIF_PEER_4" FOREIGN KEY ("EIF_PEER_NUM")
	  REFERENCES "TREXONE_DATA"."EIF_PEER" ("EIF_PEER_NUM") ENABLE,
	 CONSTRAINT "FK_SECURITY_CERTIFICATE_1" FOREIGN KEY ("SECURITY_CERTIFICATE_NUM")
	  REFERENCES "TREXONE_DATA"."SECURITY_CERTIFICATE" ("SECURITY_CERTIFICATE_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_EIF_PEER_CERTIFICATE" ON "TREXONE_DATA"."EIF_PEER_CERTIFICATE" ("EIF_PEER_CERTIFICATE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."EIF_PEER_CERTIFICATE" ADD CONSTRAINT "PK_EIF_PEER_CERTIFICATE" PRIMARY KEY ("EIF_PEER_CERTIFICATE_NUM")
  USING INDEX "TREXONE_DATA"."PK_EIF_PEER_CERTIFICATE"  ENABLE;
-- ==========================================
