-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ELECTRONIC_ORDER_LINK"
   (	"ELECTRONIC_ORDER_LINK_NUM" NUMBER(18,0),
	"ELECTRONIC_ORDER_NUM" NUMBER(18,0),
	"ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_ELECTRONIC_ORDER_06" FOREIGN KEY ("ELECTRONIC_ORDER_NUM")
	  REFERENCES "TREXONE_DATA"."ELECTRONIC_ORDER" ("ELECTRONIC_ORDER_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_ORDER_RECORD_05" FOREIGN KEY ("ORDER_NUM")
	  REFERENCES "TREXONE_DATA"."ORDER_RECORD_BASE" ("ORDER_NUM") ENABLE NOVALIDATE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
  CREATE INDEX "TREXONE_DATA"."PK_ELECTRONIC_ORDER_LINK" ON "TREXONE_DATA"."ELECTRONIC_ORDER_LINK" ("ELECTRONIC_ORDER_LINK_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."ELECTRONIC_ORDER_LINK" ADD CONSTRAINT "PK_ELECTRONIC_ORDER_LINK" PRIMARY KEY ("ELECTRONIC_ORDER_LINK_NUM")
  USING INDEX "TREXONE_DATA"."PK_ELECTRONIC_ORDER_LINK"  ENABLE;
-- ==========================================
