-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ELIGIBILITY_CLARIF"
   (	"ELIGIBILITY_CLARIF_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(30) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_ELIGIBILITY_CLARIF" ON "TREXONE_DATA"."ELIGIBILITY_CLARIF" ("ELIGIBILITY_CLARIF_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."ELIGIBILITY_CLARIF" ADD CONSTRAINT "PK_ELIGIBILITY_CLARIF" PRIMARY KEY ("ELIGIBILITY_CLARIF_NUM")
  USING INDEX "TREXONE_DATA"."PK_ELIGIBILITY_CLARIF"  ENABLE;
-- ==========================================
