-- ==========================================

  CREATE TABLE "TREXONE_DATA"."EREFERRAL_ITEM"
   (	"EREFERRAL_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"EREFERRAL_ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRODUCT_NUM" NUMBER(18,0),
	"PRODUCT_NAME" VARCHAR2(100),
	"RX_FILL_SEQ" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"IMAGE_GROUP_NUM" NUMBER(18,0),
	"HUB_RX_ID" VARCHAR2(100),
	"ORDER_STATUS" CHAR(1) DEFAULT 'N' NOT NULL ENABLE,
	"REASON" CHAR(1),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "EREFERRAL_ITEM_PK" PRIMARY KEY ("EREFERRAL_ITEM_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "EREFERRAL_ITEM_FK01" FOREIGN KEY ("EREFERRAL_ORDER_NUM")
	  REFERENCES "TREXONE_DATA"."EREFERRAL_ORDER" ("EREFERRAL_ORDER_NUM") ENABLE,
	 CONSTRAINT "EREFERRAL_ITEM_FK02" FOREIGN KEY ("PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT" ("PRODUCT_NUM") ENABLE,
	 CONSTRAINT "EREFERRAL_ITEM_FK03" FOREIGN KEY ("RX_FILL_SEQ", "RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_FILL" ("RX_FILL_SEQ", "RX_RECORD_NUM") ENABLE,
	 CONSTRAINT "EREFERRAL_ITEM_FK04" FOREIGN KEY ("IMAGE_GROUP_NUM")
	  REFERENCES "TREXONE_DATA"."IMAGE_GROUP" ("IMAGE_GROUP_NUM") ENABLE
   ) ;
-- ==========================================
