-- ==========================================

  CREATE TABLE "TREXONE_DATA"."EREFERRAL_ORDER_TYPE"
   (	"EREFERRAL_ORDER_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(20) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "EREFERRAL_ORDER_TYPE_PK" PRIMARY KEY ("EREFERRAL_ORDER_TYPE_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
