-- ==========================================

  CREATE TABLE "TREXONE_DATA"."EREFERRAL_ORDER"
   (	"EREFERRAL_ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"EREFERRAL_ORDER_TYPE_NUM" NUMBER(18,0),
	"ELECTRONIC_ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"INBOUND_MSG_QUEUE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PATIENT_NUM" NUMBER(18,0),
	"PRESCRIBER_NUM" NUMBER(18,0),
	"PATIENT_NAME" VARCHAR2(65),
	"PRESCRIBER_NAME" VARCHAR2(65),
	"FACILITY_NUM" NUMBER(22,0) NOT NULL ENABLE,
	"HUB_ORDER_ID" VARCHAR2(18),
	"CORRELATION_ID" VARCHAR2(100),
	"PROGRAM_FAX_NUMBER" VARCHAR2(40),
	"SPECIALTY_PROGRAM_NAME" VARCHAR2(100),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	"ORGANIZATION" VARCHAR2(20),
	"SPECIALTY_PROGRAM_TYPE" VARCHAR2(100),
	"SPECIALTY_PROGRAM_SUB_TYPE" VARCHAR2(100),
	"SPECIALTY_PROGRAM_NUM" NUMBER(18,0),
	"SPECIALTY_PROGRAM_GROUP_NUM" NUMBER(18,0),
	 CONSTRAINT "PK_EREFERRAL_ORDER" PRIMARY KEY ("EREFERRAL_ORDER_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_EREFERRAL_ORDER_01" FOREIGN KEY ("ELECTRONIC_ORDER_NUM")
	  REFERENCES "TREXONE_DATA"."ELECTRONIC_ORDER" ("ELECTRONIC_ORDER_NUM") ENABLE,
	 CONSTRAINT "FK_EREFERRAL_ORDER_02" FOREIGN KEY ("INBOUND_MSG_QUEUE_NUM")
	  REFERENCES "TREXONE_DATA"."INBOUND_MSG_QUEUE" ("INBOUND_MSG_QUEUE_NUM") ENABLE,
	 CONSTRAINT "FK_EREFERRAL_ORDER_03" FOREIGN KEY ("PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE,
	 CONSTRAINT "FK_EREFERRAL_ORDER_04" FOREIGN KEY ("PRESCRIBER_NUM")
	  REFERENCES "TREXONE_DATA"."PRESCRIBER" ("PRESCRIBER_NUM") ENABLE,
	 CONSTRAINT "EREFERRAL_ORDER_FACILITY_FK01" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "ERFRL_ORDR_ERFRL_ORDR_TYPE_FK" FOREIGN KEY ("EREFERRAL_ORDER_TYPE_NUM")
	  REFERENCES "TREXONE_DATA"."EREFERRAL_ORDER_TYPE" ("EREFERRAL_ORDER_TYPE_NUM") ENABLE,
	 CONSTRAINT "SPECIALTY_PROGRAM_FK05" FOREIGN KEY ("SPECIALTY_PROGRAM_NUM")
	  REFERENCES "TREXONE_DATA"."SPECIALTY_PROGRAM" ("SPECIALTY_PROGRAM_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "SPECIALTY_PROGRAM_GROUP_FK05" FOREIGN KEY ("SPECIALTY_PROGRAM_GROUP_NUM")
	  REFERENCES "TREXONE_DATA"."SPECIALTY_PROGRAM_GROUP" ("SPECIALTY_PROGRAM_GROUP_NUM") ENABLE NOVALIDATE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTOYMINTERVAL(3,'MONTH')) STORE IN ("LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
