-- ==========================================

  CREATE TABLE "TREXONE_DATA"."EXTERNAL_INVENTORY_ITEM"
   (	"EXTERNAL_INVENTORY_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"INVENTORY_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SELL_SUB" CHAR(11),
	"TARGET_INVENTORY_LEVEL" NUMBER(9,0),
	"PENDING_DELIVERY_1" NUMBER(9,0),
	"PENDING_DELIVERY_2" NUMBER(9,0),
	"ITEM_SOURCE" CHAR(1),
	"AUTO_REPLENISH" CHAR(1),
	"CYCLE_COUNT" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PENDING_DELIVERY" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_INVENTORY_ITEM_01" FOREIGN KEY ("INVENTORY_ITEM_NUM")
	  REFERENCES "TREXONE_DATA"."INVENTORY_ITEM" ("INVENTORY_ITEM_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_EXTERNAL_INVENTORY_ITEM" ON "TREXONE_DATA"."EXTERNAL_INVENTORY_ITEM" ("EXTERNAL_INVENTORY_ITEM_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."EXTERNAL_INVENTORY_ITEM" ADD CONSTRAINT "PK_EXTERNAL_INVENTORY_ITEM" PRIMARY KEY ("EXTERNAL_INVENTORY_ITEM_NUM")
  USING INDEX "TREXONE_DATA"."PK_EXTERNAL_INVENTORY_ITEM"  ENABLE;
-- ==========================================
