-- ==========================================

  CREATE TABLE "TREXONE_DATA"."EXTERNAL_PROCESS_REQUEST"
   (	"EXTERNAL_PROCESS_REQUEST_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0),
	"EXTERNAL_PROCESS_TYPE_CODE" CHAR(3) NOT NULL ENABLE,
	"STATUS_CODE" CHAR(1) NOT NULL ENABLE,
	"STATUS_DATESTAMP" DATE NOT NULL ENABLE,
	"CREATE_DATESTAMP" DATE NOT NULL ENABLE,
	"PROCESS_ON_DATESTAMP" DATE,
	"COMPLETION_DATESTAMP" DATE,
	"REQUEST_DATA" VARCHAR2(1024),
	"REQUEST_OWNER" NUMBER(18,0) NOT NULL ENABLE,
	"REQUEST_OWNER_TYPE" CHAR(3) NOT NULL ENABLE,
	"ERROR_TEXT" VARCHAR2(1024),
	"FILTER_CRITERIA_1" VARCHAR2(100),
	"FILTER_CRITERIA_2" VARCHAR2(100),
	"FILTER_CRITERIA_3" VARCHAR2(100),
	"FILTER_CRITERIA_4" VARCHAR2(100),
	"FILTER_CRITERIA_5" VARCHAR2(100),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_FACILITY_81" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_EXTERNAL_PROCESS_REQUEST" ON "TREXONE_DATA"."EXTERNAL_PROCESS_REQUEST" ("EXTERNAL_PROCESS_REQUEST_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."EXTERNAL_PROCESS_REQUEST" ADD CONSTRAINT "PK_EXTERNAL_PROCESS_REQUEST" PRIMARY KEY ("EXTERNAL_PROCESS_REQUEST_NUM")
  USING INDEX "TREXONE_DATA"."PK_EXTERNAL_PROCESS_REQUEST"  ENABLE;
-- ==========================================
