-- ==========================================

  CREATE TABLE "TREXONE_DATA"."EXTPAY_TRANS_XREF"
   (	"EXTPAY_ID" NUMBER(18,0),
	"CC_TRANS_REQUEST_NUM" NUMBER(18,0),
	"TX_ID" VARCHAR2(300) NOT NULL ENABLE,
	"STATUS_MESSAGE" VARCHAR2(4000),
	"STATUS_CODE" VARCHAR2(10),
	"ACCEPTED_RX" VARCHAR2(4000),
	"DECLINED_RX" VARCHAR2(4000),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	"RESP_PATIENT_NUM" NUMBER(18,0),
	 CONSTRAINT "PK_EXTPAY_TRANS_XREF" PRIMARY KEY ("EXTPAY_ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_CC_TRANS_REQUEST_NUM_01" FOREIGN KEY ("CC_TRANS_REQUEST_NUM")
	  REFERENCES "TREXONE_DATA"."CC_TRANS_REQUEST" ("CC_TRANS_REQUEST_NUM") ENABLE,
	 CONSTRAINT "FK_RESP_PATIENT_NUM" FOREIGN KEY ("RESP_PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTOYMINTERVAL(3,'MONTH')) STORE IN ("LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
