-- ==========================================

  CREATE TABLE "TREXONE_DATA"."FACILITY_PRESCRIBER"
   (	"FACILITY_PRESCRIBER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRESCRIBER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"LAST_FILL_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_FACILITY_22" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_PRESCRIBER_04" FOREIGN KEY ("PRESCRIBER_NUM")
	  REFERENCES "TREXONE_DATA"."PRESCRIBER" ("PRESCRIBER_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_FACILITY_PRESCRIBER" ON "TREXONE_DATA"."FACILITY_PRESCRIBER" ("FACILITY_PRESCRIBER_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."FACILITY_PRESCRIBER" ADD CONSTRAINT "PK_FACILITY_PRESCRIBER" PRIMARY KEY ("FACILITY_PRESCRIBER_NUM")
  USING INDEX "TREXONE_DATA"."PK_FACILITY_PRESCRIBER"  ENABLE;
-- ==========================================
