-- ==========================================

  CREATE TABLE "TREXONE_DATA"."FACILITY_WORKFLOW_ACTIVITY"
   (	"FACILITY_WORKFLOW_ACTIVITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0),
	"WF_QUEUE_DEFINITION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DISPLAY_SETTING" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_FACILITY_25" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_WF_QUEUE_DEFINITION_01" FOREIGN KEY ("WF_QUEUE_DEFINITION_NUM")
	  REFERENCES "TREXONE_DATA"."WF_QUEUE_DEFINITION" ("WF_QUEUE_DEFINITION_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_FACILITY_WORKFLOW_ACTIVITY" ON "TREXONE_DATA"."FACILITY_WORKFLOW_ACTIVITY" ("FACILITY_WORKFLOW_ACTIVITY_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."FACILITY_WORKFLOW_ACTIVITY" ADD CONSTRAINT "PK_FACILITY_WORKFLOW_ACTIVITY" PRIMARY KEY ("FACILITY_WORKFLOW_ACTIVITY_NUM")
  USING INDEX "TREXONE_DATA"."PK_FACILITY_WORKFLOW_ACTIVITY"  ENABLE;
-- ==========================================
