-- ==========================================

  CREATE TABLE "TREXONE_DATA"."FACILITY_GEOGRAPHIC_CODE"
   (	"FACILITY_GEOGRAPHIC_CODE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"GEOGRAPHIC_CODE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_FACILITY_01" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_GEOGRAPHIC_CODE_01" FOREIGN KEY ("GEOGRAPHIC_CODE_NUM")
	  REFERENCES "TREXONE_DATA"."GEOGRAPHIC_CODE" ("GEOGRAPHIC_CODE_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_FACILITY_GEOGRAPHIC_CODE" ON "TREXONE_DATA"."FACILITY_GEOGRAPHIC_CODE" ("FACILITY_GEOGRAPHIC_CODE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."FACILITY_GEOGRAPHIC_CODE" ADD CONSTRAINT "PK_FACILITY_GEOGRAPHIC_CODE" PRIMARY KEY ("FACILITY_GEOGRAPHIC_CODE_NUM")
  USING INDEX "TREXONE_DATA"."PK_FACILITY_GEOGRAPHIC_CODE"  ENABLE;
-- ==========================================
