-- ==========================================

  CREATE TABLE "TREXONE_DATA"."FACILITY_LINK_QUEUE"
   (	"FACILITY_LINK_QUEUE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_LINK_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"WF_QUEUE_DEFINITION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_FACILITY_LINK_QUEUE" PRIMARY KEY ("FACILITY_LINK_QUEUE_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_FACILITY_LINK_01" FOREIGN KEY ("FACILITY_LINK_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY_LINK" ("FACILITY_LINK_NUM") ENABLE
   ) ;
-- ==========================================
