-- ==========================================

  CREATE TABLE "TREXONE_DATA"."FACILITY_LINK_OVERRIDE"
   (	"FACILITY_LINK_OVERRIDE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TERMINATION_DATE" DATE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_FACILITY_LINK_OVERRIDE" PRIMARY KEY ("FACILITY_LINK_OVERRIDE_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_FACILITY_100" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE
   ) ;
-- ==========================================
