-- ==========================================

  CREATE TABLE "TREXONE_DATA"."FACILITY_NUMBER_VALUE"
   (	"FACILITY_NUMBER_VALUE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TYPE_ID" NUMBER(9,0) NOT NULL ENABLE,
	"CURRENT_VALUE" VARCHAR2(30) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_FACILITY_21" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE
   ) ;
  CREATE INDEX "TREXONE_DATA"."UC_FACILITY_NUMBER_VALUE_02" ON "TREXONE_DATA"."FACILITY_NUMBER_VALUE" ("FACILITY_NUM", "TYPE_ID")
  ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_FACILITY_NUMBER_VALUE" ON "TREXONE_DATA"."FACILITY_NUMBER_VALUE" ("FACILITY_NUMBER_VALUE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."FACILITY_NUMBER_VALUE" ADD CONSTRAINT "PK_FACILITY_NUMBER_VALUE" PRIMARY KEY ("FACILITY_NUMBER_VALUE_NUM")
  USING INDEX "TREXONE_DATA"."PK_FACILITY_NUMBER_VALUE"  ENABLE;
ALTER TABLE "TREXONE_DATA"."FACILITY_NUMBER_VALUE" ADD CONSTRAINT "UC_FACILITY_NUMBER_VALUE_02" UNIQUE ("FACILITY_NUM", "TYPE_ID")
  USING INDEX "TREXONE_DATA"."UC_FACILITY_NUMBER_VALUE_02"  ENABLE NOVALIDATE;
-- ==========================================
