-- ==========================================

  CREATE TABLE "TREXONE_DATA"."FACILITY_PRODUCT_EXCLUSION"
   (	"PRODUCT_EXCLUSION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"FACILITY_TYPE" CHAR(1),
	 CONSTRAINT "FK_FACILITY_68" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_PRODUCT_EXCLUSION_1" FOREIGN KEY ("PRODUCT_EXCLUSION_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT_EXCLUSION" ("PRODUCT_EXCLUSION_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_FACILITY_PRODUCT_EXCLUSION" ON "TREXONE_DATA"."FACILITY_PRODUCT_EXCLUSION" ("PRODUCT_EXCLUSION_NUM", "FACILITY_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."FACILITY_PRODUCT_EXCLUSION" ADD CONSTRAINT "PK_FACILITY_PRODUCT_EXCLUSION" PRIMARY KEY ("PRODUCT_EXCLUSION_NUM", "FACILITY_NUM")
  USING INDEX "TREXONE_DATA"."PK_FACILITY_PRODUCT_EXCLUSION"  ENABLE;
-- ==========================================
