-- ==========================================

  CREATE TABLE "TREXONE_DATA"."FAX_ORDER_OUT"
   (	"FAX_ORDER_OUT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PICKUP_DATE" DATE NOT NULL ENABLE,
	"SEND_COUNT" NUMBER(9,0) NOT NULL ENABLE,
	"FAX_STATUS" CHAR(1) NOT NULL ENABLE,
	"USER_COMMENT" VARCHAR2(256),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"REQUEST_DATE" DATE NOT NULL ENABLE,
	"JOB_ID" VARCHAR2(30),
	"IMAGE_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"AREA_CODE" VARCHAR2(10),
	"PHONE_NUMBER" VARCHAR2(30),
	"DOC_TYPE_NAME" VARCHAR2(50) DEFAULT 'Outbound Fax Request' NOT NULL ENABLE,
	"RX_CHANGE_TYPE" VARCHAR2(20),
	 CONSTRAINT "FK_FACILITY_27" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_RX_05" FOREIGN KEY ("RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_BASE" ("RX_RECORD_NUM") ENABLE,
	 CONSTRAINT "FK_IMAGE_13" FOREIGN KEY ("IMAGE_NUM")
	  REFERENCES "TREXONE_DATA"."IMAGE" ("IMAGE_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_FAX_ORDER_OUT" ON "TREXONE_DATA"."FAX_ORDER_OUT" ("FAX_ORDER_OUT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."FAX_ORDER_OUT" ADD CONSTRAINT "PK_FAX_ORDER_OUT" PRIMARY KEY ("FAX_ORDER_OUT_NUM")
  USING INDEX "TREXONE_DATA"."PK_FAX_ORDER_OUT"  ENABLE;
-- ==========================================
