-- ==========================================

  CREATE TABLE "TREXONE_DATA"."FINGERPRINT_TEMPLATE"
   (	"FINGERPRINT_TEMPLATE_NUM" NUMBER(18,0),
	"SYSTEM_USER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FINGER_POSITION" VARCHAR2(50) NOT NULL ENABLE,
	"TEMPLATE_BLOB" BLOB NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_FINGERPRINT_TEMPLATE" PRIMARY KEY ("FINGERPRINT_TEMPLATE_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_29" FOREIGN KEY ("SYSTEM_USER_NUM")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."IU_FINGERPRINT_TEMPLATE_01" ON "TREXONE_DATA"."FINGERPRINT_TEMPLATE" ("SYSTEM_USER_NUM", "FINGER_POSITION")
  ;
ALTER TABLE "TREXONE_DATA"."FINGERPRINT_TEMPLATE" ADD CONSTRAINT "UC_FINGERPRINT_TEMPLATE_01" UNIQUE ("SYSTEM_USER_NUM", "FINGER_POSITION")
  USING INDEX "TREXONE_DATA"."IU_FINGERPRINT_TEMPLATE_01"  ENABLE;
-- ==========================================
