-- ==========================================

  CREATE TABLE "TREXONE_DATA"."FTP_PEER"
   (	"FTP_PEER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"URL" VARCHAR2(1000),
	"REQUEST_RECEIPT" CHAR(1) DEFAULT 'Y',
	"DROP_OFF_FOLDER" VARCHAR2(1000),
	"PICK_UP_FOLDER" VARCHAR2(1000),
	"LOGIN_ID" VARCHAR2(50),
	"LOGIN_PASSWORD" VARCHAR2(50),
	"MIC_ALGORITHM" CHAR(1) DEFAULT 1,
	"IS_ENCRYPTED" CHAR(1) DEFAULT 'Y',
	"IS_SIGNED" CHAR(1) DEFAULT 'Y',
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_FTP_PEER" ON "TREXONE_DATA"."FTP_PEER" ("FTP_PEER_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."FTP_PEER" ADD CONSTRAINT "PK_FTP_PEER" PRIMARY KEY ("FTP_PEER_NUM")
  USING INDEX "TREXONE_DATA"."PK_FTP_PEER"  ENABLE;
-- ==========================================
