-- ==========================================

  CREATE TABLE "TREXONE_DATA"."GENERIC_SUB_GROUP"
   (	"GENERIC_SUB_GROUP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(40),
	"DESCRIPTION" VARCHAR2(45) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_GENERIC_SUB_GROUP" ON "TREXONE_DATA"."GENERIC_SUB_GROUP" ("GENERIC_SUB_GROUP_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."GENERIC_SUB_GROUP" ADD CONSTRAINT "PK_GENERIC_SUB_GROUP" PRIMARY KEY ("GENERIC_SUB_GROUP_NUM")
  USING INDEX "TREXONE_DATA"."PK_GENERIC_SUB_GROUP"  ENABLE;
-- ==========================================
