-- ==========================================

  CREATE TABLE "TREXONE_DATA"."GENERIC_SUB_GROUP_PRODUCT"
   (	"GENERIC_SUB_GROUP_PRODUCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"GENERIC_SUB_GROUP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRODUCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RANK" NUMBER(3,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"SUBSTITUTION_TYPE" VARCHAR2(1),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_GENERIC_SUB_GROUP_01" FOREIGN KEY ("GENERIC_SUB_GROUP_NUM")
	  REFERENCES "TREXONE_DATA"."GENERIC_SUB_GROUP" ("GENERIC_SUB_GROUP_NUM") ENABLE,
	 CONSTRAINT "FK_PRODUCT_05" FOREIGN KEY ("PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT" ("PRODUCT_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_GENERIC_SUB_GROUP_PRODUCT" ON "TREXONE_DATA"."GENERIC_SUB_GROUP_PRODUCT" ("GENERIC_SUB_GROUP_PRODUCT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."GENERIC_SUB_GROUP_PRODUCT" ADD CONSTRAINT "PK_GENERIC_SUB_GROUP_PRODUCT" PRIMARY KEY ("GENERIC_SUB_GROUP_PRODUCT_NUM")
  USING INDEX "TREXONE_DATA"."PK_GENERIC_SUB_GROUP_PRODUCT"  ENABLE;
-- ==========================================
