-- ==========================================

  CREATE GLOBAL TEMPORARY TABLE "TREXONE_DATA"."GTT_ORDER_QUEUE_SESSION_DTLS"
   (	"PRIORITY" NUMBER(18,0),
	"PROMISE_TIME" DATE,
	"ORDER_NUM" NUMBER(18,0),
	"ITEM_SEQ" NUMBER(18,0),
	"NUMBER_OF_ORDER_ITEMS" NUMBER(9,0),
	"NUMBER_OF_ORDER_ITEMS_FOUND" NUMBER(9,0),
	"PATIENT_NAME" VARCHAR2(100),
	"EXCEPTION_TRANSACTION_TYPE" VARCHAR2(100),
	"EXCEPTION_MESSAGE" VARCHAR2(200),
	"SHIP_STATUS" VARCHAR2(100),
	"LOCK_USER" NUMBER(18,0),
	"WF_PROCESS_DEFINITION_NUM" NUMBER(18,0),
	"PROC_INST_SEQ" NUMBER(18,0),
	"NODE_SEQ" NUMBER(18,0),
	"NODE_INSTANCE_SEQ" NUMBER(18,0),
	"WF_BLOCK_DEFINITION_NUM" NUMBER(18,0),
	"WF_DATESTAMP" DATE,
	"STATUS" VARCHAR2(100),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"ORDER_NUMBER" VARCHAR2(10),
	"PICKUP_FACILITY_NUM" NUMBER(18,0)
   ) ON COMMIT PRESERVE ROWS ;
-- ==========================================
