-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_ACC_ACCT_HOLDER"
   (	"ACC_ACCT_HOLDER_NUM" NUMBER(18,0),
	"ACC_ACCT_ENTITY_NUM" NUMBER(18,0),
	"ACC_AR_ACCT_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
