-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_ACCOUNT_MEMBER"
   (	"ACCOUNT_MEMBER_NUM" NUMBER(18,0),
	"PATIENT_NUM" NUMBER(18,0),
	"ACCOUNT_NUM" NUMBER(18,0),
	"STATUS" CHAR(1),
	"REL_CODE" NUMBER(18,0),
	"EFFECTIVE_DATE" DATE,
	"TERM_DATE" DATE,
	"USE_ACCOUNT_CREDIT_CARD" CHAR(1),
	"IS_PRIMARY" CHAR(1),
	"PARTICIPATION_LEVEL" CHAR(1),
	"PARTICIPATION_LEVEL_DATE" DATE,
	"DEACTIVATION_REASON_CODE" CHAR(1),
	"ENROLLMENT_CHANNEL" CHAR(1),
	"FREQUENT_SHOPPER_NUM" VARCHAR2(20),
	"IS_AUTHORIZED" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ACCOUNT_CREDIT_CARD_NUM" NUMBER(18,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null,
	"DEFAULT_ACCOUNT_MEMBER_CC_NUM" NUMBER(18,0),
	"DEFAULT_SHIPPING_ADDRESS_NUM" NUMBER(18,0),
	"BACKUP_ACCOUNT_MEMBER_CC_NUM" NUMBER(18,0)
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
