-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_ADS_ACCURACY_SCAN"
   (	"ACCURACY_SCAN_NUM" NUMBER(18,0),
	"ORDER_NUM" NUMBER(18,0),
	"ITEM_SEQ" NUMBER(18,0),
	"DISPENSING_EVENT_SEQ" NUMBER(18,0),
	"IMAGE_GROUP_NUM" NUMBER(18,0),
	"DISPENSED_ITEM_SERIAL_NUMBER" VARCHAR2(20),
	"DISPENSED_ITEM_GTIN_NUMBER" VARCHAR2(25),
	"DISPENSED_ITEM_LOT_NUMBER" VARCHAR2(20),
	"DISPENSED_ITEM_EXPIRATION_DATE" DATE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"SYS_USER" NUMBER(18,0)
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
