-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_ANCILLARY_ITEM_ADJUSTMENT"
   (	"ANCILLARY_ITEM_ADJ_NUM" NUMBER(18,0),
	"ANCILLARY_ITEM_NUM" NUMBER(18,0),
	"INV_ADJUST_REASON_NUM" NUMBER(18,0),
	"QUANTITY" NUMBER(16,8),
	"ADJUSTMENT_TYPE_CODE" VARCHAR2(3),
	"CREATE_USER" NUMBER(18,0),
	"CREATE_DATE" DATE,
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1, 'DAY')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
