-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_CC_TRANS_COMMAND_TYPE"
   (	"CC_TRANS_COMMAND_TYPE_NUM" NUMBER(18,0),
	"CC_TRANS_REQUEST_TYPE" VARCHAR2(100),
	"CC_TRANS_FUNCTION_TYPE" VARCHAR2(100),
	"CC_TRANS_COMMAND_TYPE" VARCHAR2(100),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null,
	"ARCHIVE_LEVEL" NUMBER(9,0)
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
