-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_CLIENT_LOCATION"
   (	"CLIENT_LOCATION_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"NAME" VARCHAR2(255),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"CLIENT_TYPE" VARCHAR2(25),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"COMP_TYPE" CHAR(1),
	"FROM_VERSION" VARCHAR2(30),
	"TO_VERSION" VARCHAR2(30),
	"STAGED_VERSION" VARCHAR2(30),
	"DOWNLOAD_TIME" NUMBER(18,0),
	"UPDATE_TIME" NUMBER(18,0),
	"UPDATE_TYPE" CHAR(1),
	"ERROR_CODE" VARCHAR2(200),
	"STATUS" CHAR(1),
	"JREVERSION" VARCHAR2(20),
	"IP_ADDR" VARCHAR2(15),
	"NUM_FILES" NUMBER(9,0),
	"H_TYPE" CHAR(1),
	"H_LEVEL" NUMBER,
	"WS_INFO" VARCHAR2(4000),
	"IS_AUTHORIZED" CHAR(1),
	"AUTH_DATE" DATE,
	"AUTH_USER" NUMBER(22,0),
	"HUB_CURR_CERT" CLOB,
	"HUB_PREV_CERT" CLOB,
	"HUB_ID" VARCHAR2(1024),
	"HUB_CERT_EXPIRY_DATE" DATE,
	"HUB_REMOTE_CONFIG" CHAR(1),
	"HUB_LOGIN_DATE" DATE,
	"HUB_RENEW_DATE" DATE
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
