-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_CSR_STATE"
   (	"CSR_STATE_NUM" NUMBER(18,0),
	"CTRY_CODE" VARCHAR2(8),
	"STATE_CODE" VARCHAR2(2),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"CSR_ASAP_VERSION" VARCHAR2(90),
	"CSR_INCLUDE_SHIPPED_TO_STATE" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
