-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_DUR_CONFLICT_DRUG_DOSE"
   (	"DUR_CONFLICT_NUM" NUMBER(18,0),
	"STATUS_TEXT" VARCHAR2(255),
	"STATUS" VARCHAR2(15),
	"DATABASE_SOURCE" CHAR(5),
	"DRUG_CUSTOM_ID" VARCHAR2(15),
	"DRUG_DESC" VARCHAR2(50),
	"DRUG_ID" VARCHAR2(15),
	"PATIENT_AGE" NUMBER(9,0),
	"PATIENT_IS_ADULT" CHAR(1),
	"PATIENT_WEIGHT_KG" NUMBER(16,0),
	"PATIENT_GENDER" CHAR(1),
	"PATIENT_SURFACE_AREA" NUMBER(9,0),
	"PATIENT_CONFIGURABLE_AGE" NUMBER(9,0),
	"PATIENT_DOSING_AGE" NUMBER(9,0),
	"PATIENT_MIN_MAX_WEIGHT" VARCHAR2(30),
	"DAILY_DISPENSE_QTY" NUMBER(16,0),
	"DAILY_DISPENSE_QTY_DIVIATION" NUMBER(16,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
