-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_DUR_CONFLICT_AGE"
   (	"DUR_CONFLICT_NUM" NUMBER(18,0),
	"COMMENTARY" VARCHAR2(4000),
	"DRUG_ID" VARCHAR2(15),
	"ID" VARCHAR2(15),
	"SCREEN_MESSAGE" VARCHAR2(4000),
	"SEVERITY" CHAR(5),
	"SEVERITY_TEXT" VARCHAR2(200),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null
   )
  PARTITION BY RANGE ("DATESTAMP")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
