-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_DUR_CONFLICT_3RD_PARTY"
   (	"DUR_CONFLICT_NUM" NUMBER(18,0),
	"IN_CHAIN_FLAG" CHAR(1),
	"THIRD_PARTY_NAME" VARCHAR2(200),
	"AUTO_RESPONSE_SENT" CHAR(1),
	"REASON_FOR_SERVICE_CODE" VARCHAR2(2),
	"CLINICAL_SIGNIFICANCE_CODE" CHAR(1),
	"PHARMACY" CHAR(1),
	"CONFLICT_DATE" DATE,
	"QUANTITY" NUMBER(13,3),
	"DATABASE_SOURCE" CHAR(1),
	"PRESCRIBER" CHAR(1),
	"MESSAGE" VARCHAR2(1023),
	"OVERFLOW" CHAR(1),
	"CLAIM_BILLING_ORDER" NUMBER(9,0),
	"TP_MESSAGE_NUM" NUMBER(18,0),
	"TP_ITEM_CLAIM_NUM" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"CLAIM_STATUS" VARCHAR2(25),
	"PROF_CODE_IN_TP_CLAIM" CHAR(1),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null,
	"DUR_ADDITIONAL_TEXT" VARCHAR2(100)
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
