-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_DUR_CONFLICT_ERROR"
   (	"DUR_CONFLICT_NUM" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"DRUG_NAME" VARCHAR2(50),
	"MESSAGE" VARCHAR2(1023),
	"DRUG_RX_RECORD_NUM" NUMBER(18,0),
	"NDC" VARCHAR2(20),
	"FACILITY_NUM" NUMBER(18,0),
	"RX_FILL_SEQ" NUMBER(18,0),
	"PATIENT_EXTRA_MEDICATION_NUM" NUMBER(18,0),
	"IS_RXFILL" CHAR(1),
	"RX_DAYS_SUPPLY" NUMBER(9,0),
	"DATE_OF_SERVICE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"RX_NUMBER" VARCHAR2(20),
	"PRODUCT_NAME" VARCHAR2(50),
	"PRODUCT_ID_TYPE" NUMBER(9,0),
	"IS_PROFILE_PRODUCT" CHAR(1),
	"UNKNOWN_ID" VARCHAR2(25),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
