-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_EASY_OPEN_CAPS_ACK"
   (	"EASY_OPEN_CAPS_ACK_NUM" NUMBER(18,0),
	"ACTIVE" CHAR(1),
	"PATIENT_NUM" NUMBER(18,0),
	"IMAGE_NUM" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT NULL,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1, 'DAY'))
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2013-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
