-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_EREFERRAL_ORDER"
   (	"EREFERRAL_ORDER_NUM" NUMBER(18,0),
	"EREFERRAL_ORDER_TYPE_NUM" NUMBER(18,0),
	"ELECTRONIC_ORDER_NUM" NUMBER(18,0),
	"INBOUND_MSG_QUEUE_NUM" NUMBER(18,0),
	"PATIENT_NUM" NUMBER(18,0),
	"PRESCRIBER_NUM" NUMBER(18,0),
	"PATIENT_NAME" VARCHAR2(65),
	"PRESCRIBER_NAME" VARCHAR2(65),
	"FACILITY_NUM" NUMBER(22,0),
	"HUB_ORDER_ID" VARCHAR2(18),
	"CORRELATION_ID" VARCHAR2(100),
	"PROGRAM_FAX_NUMBER" VARCHAR2(40),
	"SPECIALTY_PROGRAM_NAME" VARCHAR2(100),
	"SYS_USER" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null,
	"PARTITION_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"ORGANIZATION" VARCHAR2(20),
	"SPECIALTY_PROGRAM_TYPE" VARCHAR2(100),
	"SPECIALTY_PROGRAM_SUB_TYPE" VARCHAR2(100),
	"SPECIALTY_PROGRAM_NUM" NUMBER(18,0),
	"SPECIALTY_PROGRAM_GROUP_NUM" NUMBER(18,0)
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1, 'DAY'))
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2013-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
