-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_GEOGRAPHIC_CODE"
   (	"GEOGRAPHIC_CODE_NUM" NUMBER(18,0),
	"GEOGRAPHIC_CODE_TYPE" VARCHAR2(4),
	"GEOGRAPHIC_CODE" VARCHAR2(30),
	"DESCRIPTION" VARCHAR2(300),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
