-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_HOA_TIME"
   (	"HOA_NUM" NUMBER(18,0),
	"HOA_SCHEDULE_NUM" NUMBER(18,0),
	"HOA_TIME_SEQ" NUMBER(18,0),
	"TIME" VARCHAR2(30),
	"DOSAGE" NUMBER(18,3),
	"POSITION" NUMBER(2,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1, 'DAY'))
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2013-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
