-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_HOA_SCHEDULE"
   (	"HOA_SCHEDULE_NUM" NUMBER(18,0),
	"HOA_NUM" NUMBER(18,0),
	"SCHEDULE_TYPE" VARCHAR2(20),
	"INTERVAL_DAYS" NUMBER(3,0),
	"INTERVAL_WEEKS" NUMBER(2,0),
	"DAY_OF_THE_WEEK" VARCHAR2(20),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1, 'DAY'))
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2013-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
