-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_IMH_PATIENT_ALLERGY"
   (	"IMH_PATIENT_ALLERGY_NUM" NUMBER(18,0),
	"IMH_MESSAGE_NUM" NUMBER(18,0),
	"ALLERGEN_NUM" NUMBER(18,0),
	"PATIENT_NUM" NUMBER(18,0),
	"IMH_STATUS" CHAR(1),
	"ALLERGEN_REF_NUM" VARCHAR2(20),
	"DESCRIPTION" VARCHAR2(255),
	"SEVERITY" VARCHAR2(10),
	"CREATE_DATE" DATE,
	"ONSET_DATE" DATE,
	"DEACTIVATE_DATE" DATE,
	"STATUS" VARCHAR2(10),
	"TYPE" VARCHAR2(40),
	"CODING_TYPE" VARCHAR2(40),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0)
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
