-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_INVENTORY_LOT"
   (	"INVENTORY_LOT_NUM" NUMBER(18,0),
	"LOT_NUMBER" VARCHAR2(20),
	"SERIAL_NUMBER" VARCHAR2(20),
	"PURCHASE_DATE" DATE,
	"EXPIRATION_DATE" DATE,
	"QTY" NUMBER(16,8),
	"COST" NUMBER(17,6),
	"INVENTORY_ITEM_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE DEFAULT SYSDATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
