-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_INVENTORY_SKU"
   (	"INVENTORY_SKU_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"SKU" VARCHAR2(20),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT NULL,
	"PRODUCT_NUM" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(18,0)
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
