-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_INVENTORY_ADJUSTMENT"
   (	"INVENTORY_ADJUSTMENT_NUM" NUMBER(18,0),
	"INVENTORY_ITEM_NUM" NUMBER(18,0),
	"QUANTITY" NUMBER(16,8),
	"COMMENT_TEXT" VARCHAR2(255),
	"UNIT_COST" NUMBER(17,6),
	"IS_PROCESSED_FOR_COST" CHAR(1),
	"AVAILABLE_FIFO_QUANTITY" NUMBER(16,8),
	"AVAILABLE_LIFO_QUANTITY" NUMBER(16,8),
	"EXTENDED_COST" NUMBER(17,6),
	"CREATE_USER" NUMBER(18,0),
	"CREATE_DATE" DATE,
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"LOCATION_GROUP_NUM" NUMBER(18,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"INV_ADJUST_REASON_NUM" NUMBER(18,0),
	"REFERENCE_NUMBER" VARCHAR2(100),
	"ADJUSTMENT_TYPE_CODE" VARCHAR2(3),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
