-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_LTC_ORDER_EXCLUDE"
   (	"LTC_ORDER_EXCLUDE_NUM" NUMBER(18,0),
	"LTC_PATIENT_NUM" NUMBER(18,0),
	"LTC_PRESCRIBER_ORDER_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"INCLUDE_OVERRIDE" CHAR(1),
	"NOTE_TEXT" VARCHAR2(255),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
