-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_LTC_PENDING_FILL"
   (	"LTC_PENDING_FILL_NUM" NUMBER(18,0),
	"RX_FILL_SEQ" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"LTC_STATUS" CHAR(1),
	"ERROR_MSG" CHAR(128),
	"DUE_DATE" DATE,
	"STOP_DATE" DATE,
	"DISPENSE_QTY" NUMBER(13,3),
	"CYCLE_FILL_LENGTH" NUMBER(9,0),
	"LTC_PACKAGING_METHOD_NUM" NUMBER(18,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null,
	"LTC_BAG_TYPE_NUM" NUMBER(18,0)
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
