-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_LTC_FACILITY_NODE"
   (	"LTC_FACILITY_NODE_NUM" NUMBER(18,0),
	"LTC_FACILITY_NUM" NUMBER(18,0),
	"NAME" VARCHAR2(32),
	"DELIVERY_DATE_IND" NUMBER(9,0),
	"DELIVERY_DAYS" NUMBER(9,0),
	"IS_FILLING_OVERRIDE" CHAR(1),
	"CYCLE_FILL_FREQUENCY_TYPE" NUMBER(9,0),
	"FILL_CYCLE" NUMBER(18,0),
	"FILL_TOO_SOON_DAYS" NUMBER(9,0),
	"FILL_TOO_LATE_DAYS" NUMBER(9,0),
	"REFILL_TOO_SOON_DAYS" NUMBER(9,0),
	"REFILL_TOO_LATE_DAYS" NUMBER(9,0),
	"BILLING_TYPE" NUMBER(9,0),
	"BILLING_QUANTITY_METHOD" NUMBER(9,0),
	"BILL_CYCLE" NUMBER(18,0),
	"DATE_OF_SERVICE" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"IS_REQUIRE_AR_ACCOUNT" CHAR(1),
	"AUTOCHARGE_PREEDIT_LEVEL" NUMBER(9,0),
	"AUTOCHARGE_PREEDIT_MESSAGE" VARCHAR2(256),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null,
	"PATIENT_RESIDENCE" VARCHAR2(2)
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
