-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_MEDICAL_CONDITION_XREF"
   (	"MEDICAL_CONDITION_NUM" NUMBER(18,0),
	"MEDICAL_CONDITION_REF_TYPE" VARCHAR2(10),
	"CONDITION_REF_NUM_PREFIX" CHAR(1),
	"CONDITION_REF_NUM" VARCHAR2(20),
	"CONDITION_REF_NUM_SUFFIX" VARCHAR2(10),
	"FORMATTED_CONDITION_REF_NUM" VARCHAR2(45),
	"DESCRIPTION" VARCHAR2(255),
	"PATIENT_DESCRIPTION" VARCHAR2(60),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"INVALIDATED_DATE" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
