-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_OUTBOUND_CPS_MESSAGE"
   (	"OUTBOUND_CPS_MESSAGE_NUM" NUMBER(18,0),
	"PATIENT_NUM" NUMBER(18,0),
	"MESSAGE_BODY" CLOB,
	"RECEIVER_URL" VARCHAR2(500),
	"MESSAGE_TYPE" VARCHAR2(100),
	"MESSAGE_STATUS" VARCHAR2(20),
	"ERROR_MESSAGE" VARCHAR2(1000),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_DATE" DATE,
	"PARTITION_KEY" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" CHAR(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
