-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_OUTBOUND_CPS_MESSAGE_ITEM"
   (	"MESSAGE_ITEM_NUM" NUMBER(18,0),
	"OUTBOUND_CPS_MESSAGE_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"ORDER_NUM" NUMBER(18,0),
	"ITEM_SEQ" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_DATE" DATE,
	"PARTITION_KEY" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_TYPE" CHAR(1),
	"H_LEVEL" NUMBER,
	"RX_NUMBER" VARCHAR2(20)
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
