-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_OUTBOUND_MSG_QUEUE"
   (	"OUTBOUND_MSG_QUEUE_NUM" NUMBER(18,0),
	"MSG_STATUS" CHAR(1),
	"TRANSMISSION_ATTEMPTS" NUMBER(9,0),
	"DATETIME_LAST_ATTEMPT" DATE,
	"DATETIME_ADDED" DATE,
	"DESTINATION_URL" VARCHAR2(255),
	"MESSAGE" CLOB,
	"LAST_ERROR_MESSAGE" VARCHAR2(255),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"HTTP_STATUS" NUMBER(4,0),
	"RESPONSE_MESSAGE" CLOB,
	"ELAPSED_TIME" NUMBER,
	"PARTITION_DATE" DATE,
	"PARTITION_KEY" NUMBER(18,0),
	"H_TYPE" CHAR(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1, 'DAY'))
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2013-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
