-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_PAYMENT_EXCEPTION_LINK"
   (	"PAYMENT_NUM" NUMBER(18,0),
	"PAYMENT_EXCEPTION_NUM" NUMBER(18,0),
	"CC_TRANS_REQUEST_NUM" NUMBER(18,0),
	"RESOLVED" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null,
	"AVS_VALIDATION_MESSAGE" VARCHAR2(100),
	"CVV_VALIDATION_MESSAGE" VARCHAR2(100),
	"ORDER_NUM" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0)
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
