-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_PATIENT_ALLERGY"
   (	"PATIENT_NUM" NUMBER(18,0),
	"ALLERGEN_NUM" NUMBER(18,0),
	"SEVERITY" VARCHAR2(10),
	"REACTANT_ONSET_DATE" DATE,
	"UD_REACT_SYMPTOMS" VARCHAR2(60),
	"STATUS" CHAR(1),
	"DESCRIPTION" VARCHAR2(255),
	"CREATE_DATE" DATE,
	"CREATE_USER" NUMBER(18,0),
	"DEACTIVE_DATE" DATE,
	"DEACTIVE_USER" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
