-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_PATIENT_ID_SOURCE"
   (	"PATIENT_ID_SOURCE_NUM" NUMBER(18,0),
	"DESCRIPTION" VARCHAR2(40),
	"CODE" VARCHAR2(10),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"IS_ACTIVE" CHAR(1),
	"PID_NEXT_VALUE" VARCHAR2(30),
	"PID_MIN_LENGTH" NUMBER(2,0),
	"PID_MAX_LENGTH" NUMBER(2,0),
	"PID_DATA_TYPE" CHAR(1),
	"CHECK_DIGIT" CHAR(1),
	"PID_SYS_GENERATED" CHAR(1),
	"PID_REQUIRED" CHAR(1),
	"PARTNER_TYPE" CHAR(1),
	"IS_TZ_OVERRIDE" CHAR(1),
	"TIMEZONE_ID" VARCHAR2(60)
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
