-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_PCD_REPORT"
   (	"PCD_REPORT_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"REQUEST_SYS_USER" NUMBER(18,0),
	"REQUEST_DATE" DATE,
	"USER_COMMENT" VARCHAR2(4000),
	"REPORT_TYPE" VARCHAR2(100),
	"REPORT_FROM_DATE" DATE,
	"REPORT_TO_DATE" DATE,
	"CUSTOMER_NAME" VARCHAR2(100),
	"REPORT_SOURCE" VARCHAR2(100),
	"REPORT_STATUS" VARCHAR2(100),
	"BATCH_START_DATE" DATE,
	"BATCH_END_DATE" DATE,
	"BATCH_ERROR_MESSAGE" VARCHAR2(4000),
	"DATESTAMP" DATE,
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"H_LEVEL" NUMBER,
	"H_TYPE" VARCHAR2(1),
	"PCD_REPORT_NAME" VARCHAR2(200)
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
