-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_PDMP_RESPONSE"
   (	"PDMP_RESPONSE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ASYNC_ID" VARCHAR2(36),
	"VENDOR_NAME" VARCHAR2(100),
	"REQUEST_TYPE" VARCHAR2(100),
	"RX_RECORD_NUM" NUMBER(18,0),
	"RX_FILL_SEQ" NUMBER(18,0),
	"REQUEST_MESSAGE" CLOB,
	"DESTINATION_URL" VARCHAR2(2048),
	"REQUEST_DATE" DATE,
	"HTTP_STATUS" NUMBER(4,0),
	"RESPONSE_MESSAGE" CLOB,
	"REPORT_REQUEST_URL" VARCHAR2(2048),
	"REPORT_LINK" VARCHAR2(2048),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"DATESTAMP" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"REPORT_EXPIRATION" TIMESTAMP (6) WITH TIME ZONE,
	"REPORT_OWNER_NUM" NUMBER(18,0)
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTOYMINTERVAL(3,'MONTH')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
