-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_PDMP_NARX_SCORES"
   (	"PDMP_NARX_SCORES_NUM" NUMBER(18,0),
	"PDMP_RESPONSE_NUM" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"RX_FILL_SEQ" NUMBER(18,0),
	"IS_ACTIVE" CHAR(1),
	"NARCOTICS_NARX_SCORE" VARCHAR2(10),
	"SEDATIVES_NARX_SCORE" VARCHAR2(10),
	"STIMULANTS_NARX_SCORE" VARCHAR2(10),
	"OVERDOSE_NARX_SCORE" VARCHAR2(10),
	"MISUSE_NARX_SCORE" VARCHAR2(10),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PARTITION_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1, 'DAY')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
