-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_PDMP_CHECK"
   (	"PDMP_CHECK_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0),
	"RX_FILL_SEQ" NUMBER(18,0),
	"IS_ACTIVE" CHAR(1),
	"SATISFIED_DATE" DATE,
	"SATISFIED_SYS_USER" NUMBER(18,0),
	"OVERRIDE_DATE" DATE,
	"OVERRIDE_SYS_USER" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"DATESTAMP" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTOYMINTERVAL(3,'MONTH')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
