-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_QUESTION"
   (	"QUESTION_NUM" NUMBER(18,0),
	"NAME" VARCHAR2(30),
	"DATA_GROUP" NUMBER(18,0),
	"QUESTION_CATEGORY" CHAR(1),
	"ENABLE_RECEPTION" CHAR(1),
	"ENABLE_CONTACT_MANAGER" CHAR(1),
	"ENABLE_RELEASE_TO_PATIENT" CHAR(1),
	"TEXT" VARCHAR2(255),
	"RESPONSE_TYPE" CHAR(1),
	"RESPONSE_EXPIRE_TYPE" CHAR(1),
	"RESPONSE_EXPIRE_DURATION" NUMBER(9,0),
	"RESPONSE_EXPIRE_DATE" DATE,
	"LEGALLY_REQUIRED" CHAR(1),
	"EFFECTIVE_DATE" DATE,
	"EXPIRED_DATE" DATE,
	"STATUS" CHAR(1),
	"SECURE" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" CHAR(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
