-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_RX_ACKNOWLEDGMENT"
   (	"RX_ACKNOWLEDGMENT_NUM" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"RX_FILL_SEQ" NUMBER(18,0),
	"COUNSELING_ACCEPTED" CHAR(1),
	"RX_RECEIVED" CHAR(1),
	"IMAGE_NUM" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null,
	"COUNSELING_COMMENTS" VARCHAR2(100),
	"COUNSELING_NAME" VARCHAR2(100),
	"COUNSELING_INITIALS" VARCHAR2(3),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0)
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
