-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_SHIELD_DUR_RULE_CONDITION"
   (	"DUR_RULE_CONDITION_NUM" NUMBER(18,0),
	"CODE_SET_NUM" NUMBER(18,0),
	"CONDITION_TYPE" NUMBER(9,0),
	"PROCESSING_ORDER" NUMBER(9,0),
	"DESCRIPTION" VARCHAR2(255),
	"TRANSACTION_TYPE" NUMBER(9,0),
	"INTERACTION_TYPE" NUMBER(9,0),
	"VALUE_1" VARCHAR2(45),
	"VALUE_2" VARCHAR2(45),
	"VALUE_3" VARCHAR2(45),
	"VALUE_4" VARCHAR2(45),
	"VALUE_5" VARCHAR2(45),
	"VALUE_6" VARCHAR2(45),
	"INTERNAL" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"DATA_GROUP" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null,
	"SCREENING_RESULT_TYPE" NUMBER(9,0)
   )
  PARTITION BY RANGE ("DATESTAMP")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
