-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_SPECIALTY_PROG_LOT_ITEM_LIST"
   (	"SPECIALTY_PROG_LOT_ITM_LST_NUM" NUMBER(18,0),
	"INVENTORY_LOT_NUM" NUMBER(18,0),
	"SPECIALTY_PROGRAM_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"DATESTAMP" DATE,
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"NUM_UPDATES" NUMBER(9,0),
	"H_LEVEL" NUMBER,
	"H_TYPE" VARCHAR2(1)
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
