-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_TP_WORKERS_COMP_APPROVAL"
   (	"TP_WORKERS_COMP_APPROVAL_NUM" NUMBER(18,0),
	"TP_WORKERS_COMP_CLAIM_NUM" NUMBER(18,0),
	"APPROVAL_NUMBER" VARCHAR2(30),
	"AUTHORIZED_BY" VARCHAR2(30),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"LOGIN_FACILITY_NUM" NUMBER(18,0)
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
