-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_TP_RULE_ATTRIBUTE_VALUE"
   (	"TP_RULE_ATTRIBUTE_VALUE_NUM" NUMBER(18,0),
	"TP_RULE_SET_NUM" NUMBER(18,0),
	"TP_RULE_ATTRIBUTE_NUM" NUMBER(9,0),
	"ATTRIBUTE_GROUP_NUM" NUMBER(9,0),
	"ATTRIBUTE_SEQUENCE" NUMBER(9,0),
	"VALUE" VARCHAR2(400),
	"WARN_LEV" NUMBER(9,0),
	"EDIT_MESSAGE" VARCHAR2(255),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
