-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_TP_PLAN"
   (	"TP_PLAN_NUM" NUMBER(18,0),
	"TP_AGENCY_TYPE_NUM" NUMBER(18,0),
	"CODE" VARCHAR2(10),
	"NAME" VARCHAR2(45),
	"COMMENT_TEXT" VARCHAR2(255),
	"EFFECTIVE_DATE" DATE,
	"TERMINATION_DATE" DATE,
	"IS_TEST_PLAN" CHAR(1),
	"IS_MEDICAID_PLAN" CHAR(1),
	"IS_MEDICARE_PLAN" CHAR(1),
	"IS_WORKERS_COMP_PLAN" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"PRIMARY_INSURANCE_TYPE_CODE" VARCHAR2(3),
	"IS_ALL_STORE_PLAN" CHAR(1),
	"MEDICAID_EDIT_STATE" VARCHAR2(2),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"ALLOW_CENTRAL_FILL" CHAR(1),
	"IS_MEDICARE_FACILITATOR" CHAR(1),
	"FACILITATOR_STATE_CODES" VARCHAR2(256),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"RUN_MEDICAID_EDITS" CHAR(1),
	"IS_MAIL_ORDER_PLAN" CHAR(1),
	"ALLOW_CENTRAL_MAIL" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null,
	"USE_SEPARATE_INVENTORY" CHAR(1),
	"IS_340B" CHAR(1),
	"IS_ERP_ALLOWED" CHAR(1),
	"IS_ASSIGNMENT_ACCEPTED" CHAR(1),
	"FACILITATOR_TYPE" CHAR(1),
	"BILLING_DATE_CODE" CHAR(1),
	"REVERAL_DATE_CODE" CHAR(1)
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
