-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_USER_QUEUE_PREFERENCES"
   (	"USER_QUEUE_PREFERENCES_NUM" NUMBER(18,0),
	"NAME" NVARCHAR2(60),
	"SYSTEM_USER_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"WF_QUEUE_DEFINITION_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"NUM_UPDATES" NUMBER(9,0),
	"DATESTAMP" DATE,
	"SYS_USER" NUMBER(18,0),
	"H_LEVEL" NUMBER,
	"H_TYPE" VARCHAR2(1),
	"SPECIALTY_PROGRAM_NUMS" VARCHAR2(4000),
	"ASSIGNEE_NAME" VARCHAR2(500),
	"ON_HOLD" VARCHAR2(15),
	"THERAPY_TYPE" VARCHAR2(20),
	"PRODUCT_NAME" VARCHAR2(35),
	"STATUS" VARCHAR2(50),
	"IS_REFILL" VARCHAR2(10),
	"INCLUDE_MY_PV_1_RXS" CHAR(1),
	"DELIVERY_METHOD" VARCHAR2(1500),
	"REJECT_CODE" VARCHAR2(4000),
	"PATIENT_GROUP" VARCHAR2(4000),
	"PRESCRIBER_GROUP" VARCHAR2(4000),
	"PRE_EDIT_ERROR" VARCHAR2(1500),
	"TP_NAME" VARCHAR2(4000),
	"PRODUCT_SCHEDULE" VARCHAR2(500),
	"IS_DEFAULT" CHAR(1),
	"PRODUCT_GROUP" VARCHAR2(4000),
	"LOCKED_STATUS" CHAR(1),
	"SOURCE" VARCHAR2(1500),
	"PACKAGING_TYPE_NUMS" VARCHAR2(4000),
	"RX_COUNT" CHAR(1)
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
