-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_VENDOR_CONFIGURATION"
   (	"VENDOR_CONFIGURATION_NUM" NUMBER(18,0),
	"ACCOUNT_NUMBER" VARCHAR2(16),
	"SENDER_ID" VARCHAR2(16),
	"RECEIVER_ID" VARCHAR2(16),
	"PURCHASE_ORDER_SORT_CODE" CHAR(1),
	"LEAD_TIME" NUMBER(9,0),
	"AUTO_TRANSMIT_PO_FLAG" CHAR(1),
	"DELIVERS_ON_SUNDAY" CHAR(1),
	"DELIVERS_ON_MONDAY" CHAR(1),
	"DELIVERS_ON_TUESDAY" CHAR(1),
	"DELIVERS_ON_WEDNESDAY" CHAR(1),
	"DELIVERS_ON_THURSDAY" CHAR(1),
	"DELIVERS_ON_FRIDAY" CHAR(1),
	"DELIVERS_ON_SATURDAY" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"VENDOR_NUM" NUMBER(18,0),
	"DATA_GROUP" NUMBER(18,0),
	"C2_PO_STATUS" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"IS_340B" CHAR(1),
	"SINGLE_VENDOR_PO_OPTION" CHAR(1),
	"IS_TERM_REACTIVATE_AUTO" CHAR(1),
	"TERM_PRODUCT_COST_BASIS_DAYS" NUMBER(3,0),
	"DSCSA_EXEMPT" CHAR(1),
	"PROMPT_FOR_PO" CHAR(1)
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
