-- ==========================================

  CREATE TABLE "TREXONE_DATA"."H_VENDOR_ITEM"
   (	"VENDOR_NUM" NUMBER(18,0),
	"VENDOR_ITEM_NUM" NUMBER(18,0),
	"PRODUCT_NUM" NUMBER(18,0),
	"VENDOR_PRODUCT_ID" VARCHAR2(48),
	"PKG_SIZE" NUMBER(16,8),
	"UNIT_PRICE" NUMBER(17,6),
	"UNIT_PRICE_DATE" DATE,
	"PURCHASE_INCREMENT" NUMBER(9,0),
	"STATUS" CHAR(1),
	"AVG_LEAD_TIME" NUMBER(9,0),
	"MIN_ORDER_QTY" NUMBER(16,8),
	"DATA_GROUP" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"H_TYPE" CHAR(1),
	"H_LEVEL" NUMBER(20,0),
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT null,
	"MINIMUM_QTY" NUMBER(12,3),
	"MAXIMUM_QTY" NUMBER(12,3),
	"MIN_DAYS_SUPPLY" NUMBER(9,0),
	"MAX_DAYS_SUPPLY" NUMBER(9,0),
	"GENERICS_PROGRAM" CHAR(1),
	"VENDOR_PKG_SIZE" NUMBER(16,8),
	"VENDOR_PURCHASE_INCREMENT" NUMBER(9,0),
	"USE_VENDOR_PKG_SIZE" CHAR(1),
	"USE_VENDOR_PURCHASE_INCREMENT" CHAR(1)
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
