-- ==========================================

  CREATE TABLE "TREXONE_DATA"."HEALTH_CARD_BIN"
   (	"HEALTH_CARD_BIN_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"HEALTH_CARD_BIN_CURRENT" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE,
	"HEALTH_CARD_BIN_DATE" DATE DEFAULT sysdate NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(200) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_HEALTH_CARD_BIN" PRIMARY KEY ("HEALTH_CARD_BIN_NUM")
  USING INDEX  ENABLE
   )
  PARTITION BY RANGE ("DATESTAMP")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
