-- ==========================================

  CREATE TABLE "TREXONE_DATA"."HOMEPAGE_LINK"
   (	"HOMEPAGE_LINK_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"LINK_ORDER" NUMBER(9,0) NOT NULL ENABLE,
	"LINK_TYPE" CHAR(1) NOT NULL ENABLE,
	"TITLE" VARCHAR2(50) NOT NULL ENABLE,
	"URL" VARCHAR2(2000) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(255),
	"LINK_LOGO_URL" VARCHAR2(2000),
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE,
	"EXPIRATION_DATE" DATE NOT NULL ENABLE,
	"ON_LINKS_MENU" CHAR(1) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_HOMEPAGE_LINK" ON "TREXONE_DATA"."HOMEPAGE_LINK" ("HOMEPAGE_LINK_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."HOMEPAGE_LINK" ADD CONSTRAINT "PK_HOMEPAGE_LINK" PRIMARY KEY ("HOMEPAGE_LINK_NUM")
  USING INDEX "TREXONE_DATA"."PK_HOMEPAGE_LINK"  ENABLE;
-- ==========================================
