-- ==========================================

  CREATE TABLE "TREXONE_DATA"."HS_PATIENT_MATCH"
   (	"HS_PATIENT_MATCH_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ALTERNATE_PATIENT_ID" CHAR(1) NOT NULL ENABLE,
	"WITH_ID_ALT_ID_SEL" CHAR(1),
	"WITH_ID_LAST_NAME_SEL" CHAR(1),
	"WITH_ID_FIRST_NAME_SEL" CHAR(1),
	"WITH_ID_MIDDLE_I_SEL" CHAR(1),
	"WITH_ID_DOB_SEL" CHAR(1),
	"WITH_ID_GENDER_SEL" CHAR(1),
	"WITH_ID_PHONE_SEL" CHAR(1),
	"WITH_ID_SSN_SEL" CHAR(1),
	"WITH_ID_ADDITIONAL_CRIT" NUMBER(2,0) NOT NULL ENABLE,
	"WITHOUT_ID_ALT_ID_SEL" CHAR(1),
	"WITHOUT_ID_GENDER_SEL" CHAR(1),
	"WITHOUT_ID_SSN_SEL" CHAR(1),
	"WITHOUT_ID_PHONE_SEL" CHAR(1),
	"WITHOUT_ID_ADDITIONAL_CRIT" NUMBER(2,0) NOT NULL ENABLE,
	"WITHOUT_ID_ALWAYS_ADD" CHAR(1),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"HS_PARTNER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	 CONSTRAINT "PK_HS_PATIENT_MATCH" PRIMARY KEY ("HS_PATIENT_MATCH_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_HS_PARTNER_01" FOREIGN KEY ("HS_PARTNER_NUM")
	  REFERENCES "TREXONE_DATA"."HS_PARTNER" ("HS_PARTNER_NUM") ENABLE
   ) ;
-- ==========================================
