-- ==========================================

  CREATE TABLE "TREXONE_DATA"."HS_PARTNER"
   (	"HS_PARTNER_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"PATIENT_ID_SOURCE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ENABLE_DISPENS_QRY" CHAR(1) DEFAULT 'N',
	"AUTO_DISPENS_UPD" CHAR(1) DEFAULT '1',
	"STATUS" CHAR(1) DEFAULT 'Y',
	"HL7_VERSION" CHAR(1) DEFAULT 'A',
	"DAYS_HISTORY" NUMBER(3,0) DEFAULT NULL,
	"INCLUDE_DUR" CHAR(1) DEFAULT 'N',
	"INCLUDE_PROFILED" CHAR(1) DEFAULT 'N',
	"INCLUDE_DEACTIVE" CHAR(1) DEFAULT 'N',
	"CONSOLIDATE_FILLS" CHAR(1) DEFAULT '1',
	"RUN_MODE" CHAR(1) DEFAULT 'P',
	"PREFERRED_CONTACT" CHAR(1),
	"DATA_GROUP" NUMBER(18,0),
	"DEFAULT_CODE_TYPE" CHAR(1) DEFAULT 1 NOT NULL ENABLE,
	 CONSTRAINT "PK_HS_PARTNER" PRIMARY KEY ("HS_PARTNER_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_PATIENT_ID_SOURCE_05" FOREIGN KEY ("PATIENT_ID_SOURCE_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT_ID_SOURCE" ("PATIENT_ID_SOURCE_NUM") ENABLE
   ) ;
-- ==========================================
