-- ==========================================

  CREATE TABLE "TREXONE_DATA"."IMAGE_GROUP_LIST"
   (	"IMAGE_GROUP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"IMAGE_GROUP_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"IMAGE_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_IMAGE_08" FOREIGN KEY ("IMAGE_NUM")
	  REFERENCES "TREXONE_DATA"."IMAGE" ("IMAGE_NUM") ENABLE,
	 CONSTRAINT "FK_IMAGE_GROUP_01" FOREIGN KEY ("IMAGE_GROUP_NUM")
	  REFERENCES "TREXONE_DATA"."IMAGE_GROUP" ("IMAGE_GROUP_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_IMAGE_GROUP_LIST" ON "TREXONE_DATA"."IMAGE_GROUP_LIST" ("IMAGE_GROUP_NUM", "IMAGE_GROUP_SEQ")
  ;
ALTER TABLE "TREXONE_DATA"."IMAGE_GROUP_LIST" ADD CONSTRAINT "PK_IMAGE_GROUP_LIST" PRIMARY KEY ("IMAGE_GROUP_NUM", "IMAGE_GROUP_SEQ")
  USING INDEX "TREXONE_DATA"."PK_IMAGE_GROUP_LIST"  ENABLE;
-- ==========================================
