-- ==========================================

  CREATE TABLE "TREXONE_DATA"."IMH_DISPENSE"
   (	"IMH_DISPENSE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"IMH_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0),
	"IMH_STATUS" CHAR(1),
	"DRUG_CODING_SYSTEM_ID" VARCHAR2(20),
	"RX_SIG" VARCHAR2(2000),
	"FILL_NUMBER" NUMBER(18,0),
	"DISPENSE_DATE" DATE,
	"DISPENSE_QTY" NUMBER(13,3),
	"DISPENSE_UNIT" VARCHAR2(20),
	"DISPENSE_FORM" VARCHAR2(40),
	"RX_NUMBER" VARCHAR2(20),
	"REFILLS_REMAINING" NUMBER(9,0),
	"PRESCRIBER_NAME" VARCHAR2(120),
	"PRESCRIBER_NUMBER" VARCHAR2(30),
	"PRODUCT_STRENGTH" VARCHAR2(30),
	"PRODUCT_STRENGTH_UNIT" VARCHAR2(30),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"PRODUCT_NAME" VARCHAR2(200),
	"DRUG_CODING_SYSTEM_NAME" VARCHAR2(5),
	 CONSTRAINT "PK_IMH_DISPENSE" PRIMARY KEY ("IMH_DISPENSE_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_IMH_MESSAGE_01" FOREIGN KEY ("IMH_MESSAGE_NUM")
	  REFERENCES "TREXONE_DATA"."IMH_MESSAGE" ("IMH_MESSAGE_NUM") ENABLE,
	 CONSTRAINT "FK_PATIENT_PERM_RX_03" FOREIGN KEY ("RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT_PERM_RX" ("PATIENT_PERM_RX_NUM") ENABLE NOVALIDATE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
