-- ==========================================

  CREATE TABLE "TREXONE_DATA"."IMH_PATIENT_MED_CONDITION"
   (	"IMH_PATIENT_MED_CONDITION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"IMH_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PATIENT_MED_CONDITION_SEQ" NUMBER(18,0),
	"PATIENT_NUM" NUMBER(18,0),
	"IMH_STATUS" CHAR(1),
	"STATUS" VARCHAR2(10),
	"CREATE_DATE" DATE,
	"REPORTED_DATE" DATE,
	"DESCRIPTION" VARCHAR2(255),
	"CODE" VARCHAR2(10),
	"DAYS_DURATION" VARCHAR2(9),
	"ONSET_DATE" DATE,
	"DEACTIVATED_DATE" DATE,
	"SEVERITY" VARCHAR2(10),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_IMH_PATIENT_MED_CONDITION" PRIMARY KEY ("IMH_PATIENT_MED_CONDITION_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_IMH_MESSAGE_02" FOREIGN KEY ("IMH_MESSAGE_NUM")
	  REFERENCES "TREXONE_DATA"."IMH_MESSAGE" ("IMH_MESSAGE_NUM") ENABLE,
	 CONSTRAINT "FK_PATIENT_MED_CONDITION_03" FOREIGN KEY ("PATIENT_NUM", "PATIENT_MED_CONDITION_SEQ")
	  REFERENCES "TREXONE_DATA"."PATIENT_MED_CONDITION" ("PATIENT_NUM", "PATIENT_MED_CONDITION_SEQ") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
