-- ==========================================

  CREATE TABLE "TREXONE_DATA"."IMH_PATIENT_ALLERGY"
   (	"IMH_PATIENT_ALLERGY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"IMH_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ALLERGEN_NUM" NUMBER(18,0),
	"PATIENT_NUM" NUMBER(18,0),
	"IMH_STATUS" CHAR(1),
	"ALLERGEN_REF_NUM" VARCHAR2(20),
	"DESCRIPTION" VARCHAR2(255),
	"SEVERITY" VARCHAR2(10),
	"CREATE_DATE" DATE,
	"ONSET_DATE" DATE,
	"DEACTIVATE_DATE" DATE,
	"STATUS" VARCHAR2(10),
	"TYPE" VARCHAR2(40),
	"CODING_TYPE" VARCHAR2(40),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_IMH_PATIENT_ALLERGY" PRIMARY KEY ("IMH_PATIENT_ALLERGY_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_IMH_MESSAGE_03" FOREIGN KEY ("IMH_MESSAGE_NUM")
	  REFERENCES "TREXONE_DATA"."IMH_MESSAGE" ("IMH_MESSAGE_NUM") ENABLE,
	 CONSTRAINT "FK_PATIENT_ALLERGY_03" FOREIGN KEY ("PATIENT_NUM", "ALLERGEN_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT_ALLERGY" ("PATIENT_NUM", "ALLERGEN_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
