-- ==========================================

  CREATE TABLE "TREXONE_DATA"."IMH_MESSAGE"
   (	"IMH_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PATIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RECEIVED_DATE" DATE NOT NULL ENABLE,
	"PATIENT_ID_SOURCE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT( 'ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"EXTERNAL_MESSAGE_ID" VARCHAR2(30),
	 CONSTRAINT "PK_IMH_MESSAGE" PRIMARY KEY ("IMH_MESSAGE_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_PATIENT_ID_SOURCE_04" FOREIGN KEY ("PATIENT_ID_SOURCE_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT_ID_SOURCE" ("PATIENT_ID_SOURCE_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
