-- ==========================================

  CREATE TABLE "TREXONE_DATA"."INBOUND_ATTACHMENT_INFO"
   (	"INBOUND_ATTACHMENT_INFO_NUM" NUMBER(18,0),
	"INBOUND_MSG_QUEUE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ASSET_GROUP_ID" VARCHAR2(100) NOT NULL ENABLE,
	"PATIENT_NUM" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0) DEFAULT 0 NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"PARTITION_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	 CONSTRAINT "PK_INBOUND_ATTACHMENT_INFO" PRIMARY KEY ("INBOUND_ATTACHMENT_INFO_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_101" FOREIGN KEY ("SYS_USER")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_INBOUND_MSG_QUEUE_01" FOREIGN KEY ("INBOUND_MSG_QUEUE_NUM")
	  REFERENCES "TREXONE_DATA"."INBOUND_MSG_QUEUE" ("INBOUND_MSG_QUEUE_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_PATIENT_43" FOREIGN KEY ("PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_RX_BASE_20" FOREIGN KEY ("RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_BASE" ("RX_RECORD_NUM") ENABLE NOVALIDATE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTOYMINTERVAL(3,'MONTH')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
