-- ==========================================

  CREATE TABLE "TREXONE_DATA"."INVENTORY_ITEM_NOTE"
   (	"INVENTORY_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"INVENTORY_ITEM_NOTE_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"NOTE_TEXT" VARCHAR2(4000) NOT NULL ENABLE,
	"PRIORITY" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_INVENTORY_ITEM_04" FOREIGN KEY ("INVENTORY_ITEM_NUM")
	  REFERENCES "TREXONE_DATA"."INVENTORY_ITEM" ("INVENTORY_ITEM_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_INVENTORY_ITEM_NOTE" ON "TREXONE_DATA"."INVENTORY_ITEM_NOTE" ("INVENTORY_ITEM_NUM", "INVENTORY_ITEM_NOTE_SEQ")
  ;
ALTER TABLE "TREXONE_DATA"."INVENTORY_ITEM_NOTE" ADD CONSTRAINT "PK_INVENTORY_ITEM_NOTE" PRIMARY KEY ("INVENTORY_ITEM_NUM", "INVENTORY_ITEM_NOTE_SEQ")
  USING INDEX "TREXONE_DATA"."PK_INVENTORY_ITEM_NOTE"  ENABLE;
-- ==========================================
