-- ==========================================

  CREATE TABLE "TREXONE_DATA"."INVENTORY_ADJUSTMENT_REASON"
   (	"INV_ADJUST_REASON_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CODE" VARCHAR2(3) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(50) NOT NULL ENABLE,
	"IS_ACTIVE" CHAR(1) NOT NULL ENABLE,
	"IS_USER_DEFINED" CHAR(1) NOT NULL ENABLE,
	"IS_DEFAULT" CHAR(1) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PKINVENTORY_ADJUSTMENT_REASON" ON "TREXONE_DATA"."INVENTORY_ADJUSTMENT_REASON" ("INV_ADJUST_REASON_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."INVENTORY_ADJUSTMENT_REASON" ADD CONSTRAINT "PKINVENTORY_ADJUSTMENT_REASON" PRIMARY KEY ("INV_ADJUST_REASON_NUM")
  USING INDEX "TREXONE_DATA"."PKINVENTORY_ADJUSTMENT_REASON"  ENABLE;
-- ==========================================
