-- ==========================================

  CREATE TABLE "TREXONE_DATA"."INVENTORY_COMMIT"
   (	"INVENTORY_COMMIT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ITEM_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"LOCATION_GROUP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"INVENTORY_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"COMMIT_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"QUANTITY" NUMBER(16,8) NOT NULL ENABLE,
	"COMMENT_TEXT" VARCHAR2(255),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_COMMIT_TYPE_01" FOREIGN KEY ("COMMIT_TYPE_NUM")
	  REFERENCES "TREXONE_DATA"."COMMIT_TYPE" ("COMMIT_TYPE_NUM") ENABLE,
	 CONSTRAINT "FK_INVENTORY_ITEM_03" FOREIGN KEY ("INVENTORY_ITEM_NUM")
	  REFERENCES "TREXONE_DATA"."INVENTORY_ITEM" ("INVENTORY_ITEM_NUM") ENABLE,
	 CONSTRAINT "FK_ITEM_04" FOREIGN KEY ("ORDER_NUM", "ITEM_SEQ")
	  REFERENCES "TREXONE_DATA"."ITEM" ("ORDER_NUM", "ITEM_SEQ") ENABLE,
	 CONSTRAINT "FK_LOCATION_GROUP_03" FOREIGN KEY ("LOCATION_GROUP_NUM")
	  REFERENCES "TREXONE_DATA"."LOCATION_GROUP" ("LOCATION_GROUP_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_INVENTORY_COMMIT" ON "TREXONE_DATA"."INVENTORY_COMMIT" ("INVENTORY_COMMIT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."INVENTORY_COMMIT" ADD CONSTRAINT "PK_INVENTORY_COMMIT" PRIMARY KEY ("INVENTORY_COMMIT_NUM")
  USING INDEX "TREXONE_DATA"."PK_INVENTORY_COMMIT"  ENABLE;
-- ==========================================
