-- ==========================================

  CREATE TABLE "TREXONE_DATA"."INVENTORY_ITEM"
   (	"INVENTORY_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRODUCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"STAGING_BIN_TYPE_NUM" NUMBER(18,0),
	"STATUS" CHAR(1) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"EXCLUDE_FROM_RECOMMENDED_PO" CHAR(1),
	"LAST_ACQUISITION_COST" NUMBER(17,6),
	"LAST_ACQUISITION_COST_DATE" DATE,
	"LAST_ACQUISITION_UNIT_COST" NUMBER(17,6),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"IS_AUTO_DISPENSED" CHAR(1),
	"MOVING_AVG_COST" NUMBER(17,6),
	"LAST_LEVEL_CHANGE_DATE" DATE DEFAULT sysdate NOT NULL ENABLE,
	"ADS_QUANTITY" NUMBER(16,8),
	 CONSTRAINT "FK_PRODUCT_06" FOREIGN KEY ("PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT" ("PRODUCT_NUM") ENABLE,
	 CONSTRAINT "FK_RETAIL_STAGING_BIN_TYPE_01" FOREIGN KEY ("STAGING_BIN_TYPE_NUM", "FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."RETAIL_STAGING_BIN_TYPE" ("STAGING_BIN_TYPE_NUM", "FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_FACILITY_79" FOREIGN KEY ("DATA_GROUP")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_FACILITY_80" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE
   ) ;
  CREATE INDEX "TREXONE_DATA"."IN_INVENTORY_ITEM_1" ON "TREXONE_DATA"."INVENTORY_ITEM" ("PRODUCT_NUM", "DATA_GROUP")
  ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_INVENTORY_ITEM" ON "TREXONE_DATA"."INVENTORY_ITEM" ("INVENTORY_ITEM_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."INVENTORY_ITEM" ADD CONSTRAINT "PK_INVENTORY_ITEM" PRIMARY KEY ("INVENTORY_ITEM_NUM")
  USING INDEX "TREXONE_DATA"."PK_INVENTORY_ITEM"  ENABLE;
ALTER TABLE "TREXONE_DATA"."INVENTORY_ITEM" ADD CONSTRAINT "UC_INVENTORY_ITEM_01" UNIQUE ("DATA_GROUP", "PRODUCT_NUM")
  USING INDEX "TREXONE_DATA"."IN_INVENTORY_ITEM_1"  ENABLE NOVALIDATE;
-- ==========================================
