-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ITEM_MATCH_REQUEST"
   (	"ITEM_MATCH_REQUEST_NUM" NUMBER(18,0),
	"REQUEST_DATETIME" DATE NOT NULL ENABLE,
	"DSCSA_DOCUMENT_NUM" NUMBER(18,0),
	"DSCSA_SHIPPED_ITEM_NUM" NUMBER(18,0),
	"GTIN" VARCHAR2(100),
	"NDC" VARCHAR2(20),
	"LOT_NUMBER" VARCHAR2(100) NOT NULL ENABLE,
	"SERIAL_NUMBER" VARCHAR2(100) NOT NULL ENABLE,
	"EXPIRATION_DATE" VARCHAR2(10) NOT NULL ENABLE,
	"SUPPLIER_SGLN" VARCHAR2(100),
	"FACILITY_SGLN" VARCHAR2(100) NOT NULL ENABLE,
	"MATCH_RESULT" CHAR(1) NOT NULL ENABLE,
	"PURCHASE_ORDER_IDENTIFIER" VARCHAR2(100),
	"REQUEST_FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_ITEM_MATCH_REQUEST" PRIMARY KEY ("ITEM_MATCH_REQUEST_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_83" FOREIGN KEY ("SYS_USER")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_FACILITY_136" FOREIGN KEY ("REQUEST_FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_DSCSA_DOCUMENT_02" FOREIGN KEY ("DSCSA_DOCUMENT_NUM")
	  REFERENCES "TREXONE_DATA"."DSCSA_DOCUMENT" ("DSCSA_DOCUMENT_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_DSCSA_SHIPPED_ITEM_01" FOREIGN KEY ("DSCSA_SHIPPED_ITEM_NUM")
	  REFERENCES "TREXONE_DATA"."DSCSA_SHIPPED_ITEM" ("DSCSA_SHIPPED_ITEM_NUM") ENABLE NOVALIDATE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTOYMINTERVAL(3,'MONTH')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
