-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ITEM_LOT"
   (	"ITEM_LOT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ITEM_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"LOT_NUMBER" VARCHAR2(20) NOT NULL ENABLE,
	"SERIAL_NUMBER" VARCHAR2(20),
	"EXPIRATION_DATE" VARCHAR2(8) NOT NULL ENABLE,
	"SORT_ORDER" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"QTY" NUMBER(16,8),
	"DSCSA_MATCH_RESULT_NUM" NUMBER(18,0),
	 CONSTRAINT "PK_ITEM_LOT" PRIMARY KEY ("ITEM_LOT_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_75" FOREIGN KEY ("SYS_USER")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_ITEM_20" FOREIGN KEY ("ORDER_NUM", "ITEM_SEQ")
	  REFERENCES "TREXONE_DATA"."ITEM" ("ORDER_NUM", "ITEM_SEQ") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_DSCSA_MATCH_RESULT_01" FOREIGN KEY ("DSCSA_MATCH_RESULT_NUM")
	  REFERENCES "TREXONE_DATA"."DSCSA_MATCH_RESULT" ("DSCSA_MATCH_RESULT_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTOYMINTERVAL(3,'MONTH')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
