-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ITEM_EVENT_LOG"
   (	"ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ITEM_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"ITEM_EVENT_LOG_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"ITEM_EVENT_TYPE_NUM" NUMBER(18,0),
	"IS_REVERSED" CHAR(1) NOT NULL ENABLE,
	"COMMENT_TEXT" VARCHAR2(255),
	"RESULT" VARCHAR2(10),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_ITEM_06" FOREIGN KEY ("ORDER_NUM", "ITEM_SEQ")
	  REFERENCES "TREXONE_DATA"."ITEM" ("ORDER_NUM", "ITEM_SEQ") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_ITEM_EVENT_LOG" ON "TREXONE_DATA"."ITEM_EVENT_LOG" ("ORDER_NUM", "ITEM_SEQ", "ITEM_EVENT_LOG_SEQ")
  ;
ALTER TABLE "TREXONE_DATA"."ITEM_EVENT_LOG" ADD CONSTRAINT "PK_ITEM_EVENT_LOG" PRIMARY KEY ("ORDER_NUM", "ITEM_SEQ", "ITEM_EVENT_LOG_SEQ")
  USING INDEX "TREXONE_DATA"."PK_ITEM_EVENT_LOG"  ENABLE;
-- ==========================================
