-- ==========================================

  CREATE TABLE "TREXONE_DATA"."IVR_ORDER_ITEM"
   (	"IVR_ORDER_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"IVR_ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_NUMBER" VARCHAR2(20) NOT NULL ENABLE,
	"IS_CALL_DOCTOR" CHAR(1) NOT NULL ENABLE,
	"IS_BAD_PICKUP_TIME" CHAR(1) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"IS_PAYING_PATIENT" CHAR(1) DEFAULT 'N' NOT NULL ENABLE,
	"FAX_JOB_ID" VARCHAR2(50),
	"WRITTEN_QTY" NUMBER(13,3),
	"DISPENSED_QTY" NUMBER(13,3),
	"DAYS_SUPPLY" NUMBER(18,0),
	"REFILL_QTY" NUMBER(13,3),
	"REFILLS_ALLOWED" NUMBER(18,0),
	"SYNC_DATE" DATE,
	"ITEM_SOURCE_TYPE_NUM" NUMBER(18,0),
	"CLINICAL_PROGRAM_NUM" NUMBER(18,0),
	 CONSTRAINT "FK_IVR_ORDER_01" FOREIGN KEY ("IVR_ORDER_NUM")
	  REFERENCES "TREXONE_DATA"."IVR_ORDER" ("IVR_ORDER_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_IVR_ORDER_ITEM" ON "TREXONE_DATA"."IVR_ORDER_ITEM" ("IVR_ORDER_ITEM_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."IVR_ORDER_ITEM" ADD CONSTRAINT "PK_IVR_ORDER_ITEM" PRIMARY KEY ("IVR_ORDER_ITEM_NUM")
  USING INDEX "TREXONE_DATA"."PK_IVR_ORDER_ITEM"  ENABLE;
-- ==========================================
