-- ==========================================

  CREATE TABLE "TREXONE_DATA"."IVR_INFO"
   (	"IVR_INFO_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_NUMBER" VARCHAR2(20),
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PURPOSE" VARCHAR2(2) NOT NULL ENABLE,
	"REASON_CODE" VARCHAR2(2),
	"IS_REFILLABLE" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_FACILITY_30" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_IVR_INFO" ON "TREXONE_DATA"."IVR_INFO" ("IVR_INFO_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."IVR_INFO" ADD CONSTRAINT "PK_IVR_INFO" PRIMARY KEY ("IVR_INFO_NUM")
  USING INDEX "TREXONE_DATA"."PK_IVR_INFO"  ENABLE;
-- ==========================================
