-- ==========================================

  CREATE TABLE "TREXONE_DATA"."KAFKA_FAILOVER"
   (	"KAFKA_FAILOVER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" TIMESTAMP (6) NOT NULL ENABLE,
	"TOPIC_CONFIG_KEY" VARCHAR2(100) NOT NULL ENABLE,
	"KEY" VARCHAR2(300),
	"HEADERS" VARCHAR2(4000),
	"MESSAGE" BLOB NOT NULL ENABLE,
	"MESSAGE_CONSUMED" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	 CONSTRAINT "PK_KAFKA_FAILOVER" PRIMARY KEY ("KAFKA_FAILOVER_NUM")
  USING INDEX  ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTOYMINTERVAL(3,'MONTH')) STORE IN ("LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
