-- ==========================================

  CREATE TABLE "TREXONE_DATA"."KEYSTORE_CONTENT"
   (	"KEYSTORE_CONTENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"KEYSTORE_NUM" NUMBER(18,0),
	"KEYSTORE_PROPERTY_NUM" NUMBER(18,0),
	"KEYSTORE_CONTENT" BLOB,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT sysdate NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_KEYSTORE_CONTENT" PRIMARY KEY ("KEYSTORE_CONTENT_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_KEYSTORE_03" FOREIGN KEY ("KEYSTORE_NUM")
	  REFERENCES "TREXONE_DATA"."KEYSTORE" ("KEYSTORE_NUM") ENABLE,
	 CONSTRAINT "FK_KEYSTORE_PROPERTY_01" FOREIGN KEY ("KEYSTORE_PROPERTY_NUM")
	  REFERENCES "TREXONE_DATA"."KEYSTORE_PROPERTY" ("KEYSTORE_PROPERTY_NUM") ENABLE
   ) ;
-- ==========================================
