-- ==========================================

  CREATE TABLE "TREXONE_DATA"."KEYSTORE_PROPERTY"
   (	"KEYSTORE_PROPERTY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"KEYSTORE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"KEYSTORE_PROPERTY_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"KEYSTORE_PROPERTY_STRINGVALUE" VARCHAR2(4000),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT sysdate NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"KEYSTORE_ENTRY_NUM" NUMBER(18,0),
	 CONSTRAINT "PK_KEYSTORE_PROPERTY" PRIMARY KEY ("KEYSTORE_PROPERTY_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "UC_KEYSTORE_PROPERTY_01" UNIQUE ("KEYSTORE_NUM", "KEYSTORE_ENTRY_NUM", "KEYSTORE_PROPERTY_NAME", "ERX_CLIENT_ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_KEYSTORE_01" FOREIGN KEY ("KEYSTORE_NUM")
	  REFERENCES "TREXONE_DATA"."KEYSTORE" ("KEYSTORE_NUM") ENABLE,
	 CONSTRAINT "FK_KEYSTORE_ENTRY_01" FOREIGN KEY ("KEYSTORE_ENTRY_NUM")
	  REFERENCES "TREXONE_DATA"."KEYSTORE_ENTRY" ("KEYSTORE_ENTRY_NUM") ENABLE
   ) ;
-- ==========================================
