-- ==========================================

  CREATE TABLE "TREXONE_DATA"."KEYSTORE"
   (	"KEYSTORE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"KEYSTORE_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT sysdate NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_KEYSTORE" PRIMARY KEY ("KEYSTORE_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "UC_KEYSTORE_01" UNIQUE ("KEYSTORE_NAME", "ERX_CLIENT_ID")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
