-- ==========================================

  CREATE TABLE "TREXONE_DATA"."LANGUAGE"
   (	"LANGUAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(30),
	"LANG_ISO_ID" CHAR(2) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_LANGUAGE" ON "TREXONE_DATA"."LANGUAGE" ("LANGUAGE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."LANGUAGE" ADD CONSTRAINT "PK_LANGUAGE" PRIMARY KEY ("LANGUAGE_NUM")
  USING INDEX "TREXONE_DATA"."PK_LANGUAGE"  ENABLE;
-- ==========================================
