-- ==========================================

  CREATE TABLE "TREXONE_DATA"."LATIN_FREQUENCY"
   (	"LATIN_FREQUENCY_CODE" VARCHAR2(10) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(60),
	"DAYS_MULTIPLIER" NUMBER(16,8),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_LATIN_FREQUENCY" ON "TREXONE_DATA"."LATIN_FREQUENCY" ("LATIN_FREQUENCY_CODE")
  ;
ALTER TABLE "TREXONE_DATA"."LATIN_FREQUENCY" ADD CONSTRAINT "PK_LATIN_FREQUENCY" PRIMARY KEY ("LATIN_FREQUENCY_CODE")
  USING INDEX "TREXONE_DATA"."PK_LATIN_FREQUENCY"  ENABLE;
-- ==========================================
