-- ==========================================

  CREATE TABLE "TREXONE_DATA"."LOCATION"
   (	"LOCATION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(30),
	"DESCRIPTION" VARCHAR2(255),
	"IS_MULTI_USER" CHAR(1) NOT NULL ENABLE,
	"IS_NON_NETWORK" CHAR(1),
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_LOCATION" ON "TREXONE_DATA"."LOCATION" ("LOCATION_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."LOCATION" ADD CONSTRAINT "PK_LOCATION" PRIMARY KEY ("LOCATION_NUM")
  USING INDEX "TREXONE_DATA"."PK_LOCATION"  ENABLE;
-- ==========================================
