-- ==========================================

  CREATE TABLE "TREXONE_DATA"."LOT_COMMIT"
   (	"LOT_COMMIT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ITEM_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"LOT_COMMIT_TYPE" CHAR(1) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	 CONSTRAINT "LOT_COMMIT_PK" PRIMARY KEY ("LOT_COMMIT_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "LOT_COMMIT_FK01" FOREIGN KEY ("ORDER_NUM", "ITEM_SEQ")
	  REFERENCES "TREXONE_DATA"."ITEM" ("ORDER_NUM", "ITEM_SEQ") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTOYMINTERVAL(3,'MONTH'))
 (PARTITION "P_20160101"  VALUES LESS THAN (TO_DATE(' 2016-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
