-- ==========================================

  CREATE TABLE "TREXONE_DATA"."LTC_HOA_TIME"
   (	"LTC_HOA_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"HOA_TIME_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"TIME" VARCHAR2(16) NOT NULL ENABLE,
	"PRINT_POSITION" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DOSAGE" NUMBER(18,3),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_LTC_HOA_TIME" PRIMARY KEY ("LTC_HOA_NUM", "HOA_TIME_SEQ")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_LTC_HOA_01" FOREIGN KEY ("LTC_HOA_NUM")
	  REFERENCES "TREXONE_DATA"."LTC_HOA" ("LTC_HOA_NUM") ENABLE
   ) ;
-- ==========================================
