-- ==========================================

  CREATE TABLE "TREXONE_DATA"."LTC_HOA_SIG"
   (	"LTC_HOA_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SIG_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"MACRO" VARCHAR2(15),
	 CONSTRAINT "PK_LTC_HOA_SIG" PRIMARY KEY ("LTC_HOA_NUM", "MACRO")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_LTC_HOA_02" FOREIGN KEY ("LTC_HOA_NUM")
	  REFERENCES "TREXONE_DATA"."LTC_HOA" ("LTC_HOA_NUM") ENABLE
   ) ;
-- ==========================================
