-- ==========================================

  CREATE TABLE "TREXONE_DATA"."LTC_HOA"
   (	"LTC_HOA_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"LTC_FACILITY_NODE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(64),
	"ADMIN_TYPE" VARCHAR2(20),
	"OVERRIDE_LTC_HOA_NUM" NUMBER(18,0),
	"LTC_HOA_OVERIDE_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"HOA_SEQUENCE" NUMBER(2,0),
	 CONSTRAINT "PK_LTC_HOA" PRIMARY KEY ("LTC_HOA_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_LTC_FACILITY_NODE_03" FOREIGN KEY ("LTC_FACILITY_NODE_NUM")
	  REFERENCES "TREXONE_DATA"."LTC_FACILITY_NODE" ("LTC_FACILITY_NODE_NUM") ENABLE,
	 CONSTRAINT "FK_LTC_HOA_05" FOREIGN KEY ("OVERRIDE_LTC_HOA_NUM")
	  REFERENCES "TREXONE_DATA"."LTC_HOA" ("LTC_HOA_NUM") ENABLE
   ) ;
-- ==========================================
