-- ==========================================

  CREATE TABLE "TREXONE_DATA"."LTC_PENDING_FILL"
   (	"LTC_PENDING_FILL_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_FILL_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"LTC_STATUS" CHAR(1),
	"ERROR_MSG" CHAR(128),
	"DUE_DATE" DATE,
	"STOP_DATE" DATE,
	"DISPENSE_QTY" NUMBER(13,3),
	"CYCLE_FILL_LENGTH" NUMBER(9,0),
	"LTC_PACKAGING_METHOD_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"LTC_BAG_TYPE_NUM" NUMBER(18,0),
	 CONSTRAINT "PK_LTC_PENDING_FILL" PRIMARY KEY ("LTC_PENDING_FILL_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_LTC_PACKAGING_METHOD_01" FOREIGN KEY ("LTC_PACKAGING_METHOD_NUM")
	  REFERENCES "TREXONE_DATA"."LTC_PACKAGING_METHOD" ("LTC_PACKAGING_METHOD_NUM") ENABLE,
	 CONSTRAINT "FK_RX_FILL_19" FOREIGN KEY ("RX_FILL_SEQ", "RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_FILL" ("RX_FILL_SEQ", "RX_RECORD_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
