-- ==========================================

  CREATE TABLE "TREXONE_DATA"."LTC_ORDER_EXCLUDE"
   (	"LTC_ORDER_EXCLUDE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"LTC_PATIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"LTC_PRESCRIBER_ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"INCLUDE_OVERRIDE" CHAR(1),
	"NOTE_TEXT" VARCHAR2(255),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_LTC_ORDER_EXCLUDE" PRIMARY KEY ("LTC_ORDER_EXCLUDE_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_LTC_PATIENT_01" FOREIGN KEY ("LTC_PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."LTC_PATIENT" ("LTC_PATIENT_NUM") ENABLE,
	 CONSTRAINT "FK_LTC_PRESCRIBER_ORDER_01" FOREIGN KEY ("LTC_PRESCRIBER_ORDER_NUM")
	  REFERENCES "TREXONE_DATA"."LTC_PRESCRIBER_ORDER" ("LTC_PRESCRIBER_ORDER_NUM") ENABLE
   ) ;
-- ==========================================
