-- ==========================================

  CREATE TABLE "TREXONE_DATA"."LTC_PATIENT"
   (	"LTC_PATIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"LTC_FACILITY_NODE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PATIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"STATUS" CHAR(1),
	"IS_FACILITY_LOCATION_INFO_USED" CHAR(1),
	"IS_ACTIVE" CHAR(1),
	"DISCHARGED_DATE" DATE,
	"STATUS_EFFECTIVE_DATE" DATE,
	"STATUS_TERMINATION_DATE" DATE,
	"ROOM" VARCHAR2(50),
	"BED" VARCHAR2(50),
	"ADMISSION_INFORMATION" VARCHAR2(255),
	"ADMITTED_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"LTC_PATIENT_ID" VARCHAR2(20),
	"STATUS_CHANGE_DATE" DATE,
	 CONSTRAINT "PK_LTC_PATIENT" PRIMARY KEY ("LTC_PATIENT_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_LTC_FACILITY_NODE_08" FOREIGN KEY ("LTC_FACILITY_NODE_NUM")
	  REFERENCES "TREXONE_DATA"."LTC_FACILITY_NODE" ("LTC_FACILITY_NODE_NUM") ENABLE,
	 CONSTRAINT "FK_PATIENT_21" FOREIGN KEY ("PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE
   ) ;
-- ==========================================
