-- ==========================================

  CREATE TABLE "TREXONE_DATA"."LTC_FACILITY"
   (	"LTC_FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(32) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"LTC_FACILITY_NODE_NUM" NUMBER(18,0),
	"TYPE" VARCHAR2(10),
	"NUMBER_OF_BEDS" NUMBER(9,0),
	"TERMINATION_DATE" DATE,
	"EFFECTIVE_DATE" DATE,
	"REACTIVATION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"IS_CMS_PART_D" CHAR(1),
	"FACILITY_ID" VARCHAR2(10),
	"PLACE_OF_SERVICE" VARCHAR2(2),
	 CONSTRAINT "PK_LTC_FACILITY" PRIMARY KEY ("LTC_FACILITY_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_FACILITY_06" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_LTC_FACILITY_NODE_02" FOREIGN KEY ("LTC_FACILITY_NODE_NUM")
	  REFERENCES "TREXONE_DATA"."LTC_FACILITY_NODE" ("LTC_FACILITY_NODE_NUM") ENABLE
   ) ;
-- ==========================================
