-- ==========================================

  CREATE TABLE "TREXONE_DATA"."LTC_RX_PRESCRIBER_ORDER"
   (	"LTC_RX_PRESCRIBER_ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TYPE" VARCHAR2(30) NOT NULL ENABLE,
	"IS_ON_HOLD" CHAR(1) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"PRESCRIBER_NUM" NUMBER(18,0),
	"LTC_HOA_NUM" NUMBER(18,0),
	"TEXT" VARCHAR2(1500),
	"EFFECTIVE_DATE" DATE,
	"TERMINATION_DATE" DATE,
	"PRINT_ORDER" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_LTC_RX_PRESCRIBER_ORDER" PRIMARY KEY ("LTC_RX_PRESCRIBER_ORDER_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_LTC_HOA_03" FOREIGN KEY ("LTC_HOA_NUM")
	  REFERENCES "TREXONE_DATA"."LTC_HOA" ("LTC_HOA_NUM") ENABLE,
	 CONSTRAINT "FK_PRESCRIBER_28" FOREIGN KEY ("PRESCRIBER_NUM")
	  REFERENCES "TREXONE_DATA"."PRESCRIBER" ("PRESCRIBER_NUM") ENABLE,
	 CONSTRAINT "FK_RX_BASE_03" FOREIGN KEY ("RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_BASE" ("RX_RECORD_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
