-- ==========================================

  CREATE TABLE "TREXONE_DATA"."MAIL_SHIP_EXMPT_RULE_SET"
   (	"MAIL_SHIP_EXMPT_RULE_SET_NUM" NUMBER(18,0),
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_MAIL_SHIP_EXMPT_RULE_SET" PRIMARY KEY ("MAIL_SHIP_EXMPT_RULE_SET_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_DATA_GROUP_40" FOREIGN KEY ("DATA_GROUP")
	  REFERENCES "TREXONE_DATA"."DATA_GROUP" ("DATA_GROUP") ENABLE NOVALIDATE
   ) ;
-- ==========================================
