-- ==========================================

  CREATE TABLE "TREXONE_DATA"."MAILORD_INCL_EXCL_RULE"
   (	"MAILORD_INCL_EXCL_RULE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DATA_FILTER" CLOB NOT NULL ENABLE,
	"MAILORD_INCL_EXCL_RULE_SET_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"IS_INCLUDE_RULE" CHAR(1),
	"PROCESS_ORDER" NUMBER(9,0),
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "CHK_IS_INCLUDE_RULE" CHECK (IS_INCLUDE_RULE  in ('Y','N')) ENABLE,
	 CONSTRAINT "PK_MAILORD_INCL_EXCL_RULE" PRIMARY KEY ("MAILORD_INCL_EXCL_RULE_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_MAILORD_INCL_EXCL_RULE" FOREIGN KEY ("MAILORD_INCL_EXCL_RULE_SET_NUM")
	  REFERENCES "TREXONE_DATA"."MAILORD_INCL_EXCL_RULE_SET" ("MAILORD_INCL_EXCL_RULE_SET_NUM") ENABLE NOVALIDATE
   ) ;
-- ==========================================
