-- ==========================================

  CREATE TABLE "TREXONE_DATA"."MAIL_DELIVERY_OPTIONS"
   (	"OPTIONS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"DELIVERY_METHOD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SHIPPING_COURIER_NUM" NUMBER(18,0),
	"SHIPPING_METHOD_NUM" NUMBER(18,0),
	"COURIER_CHARGE" NUMBER(17,6),
	"SHIP_DAYS" NUMBER(3,0),
	"SHIPMENT_SIGNATURE_NUM" NUMBER(18,0),
	"HIGH_PRIORITY" CHAR(1),
	"PAYMENT_TYPE_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT sysdate NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_MAIL_DELIVERY_OPTIONS" PRIMARY KEY ("OPTIONS_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_65" FOREIGN KEY ("SYS_USER")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_DATA_GROUP_45" FOREIGN KEY ("DATA_GROUP")
	  REFERENCES "TREXONE_DATA"."DATA_GROUP" ("DATA_GROUP") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_DELIVERY_METHOD_10" FOREIGN KEY ("DELIVERY_METHOD_NUM")
	  REFERENCES "TREXONE_DATA"."DELIVERY_METHOD" ("DELIVERY_METHOD_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_SHIPPING_COURIER_05" FOREIGN KEY ("SHIPPING_COURIER_NUM")
	  REFERENCES "TREXONE_DATA"."SHIPPING_COURIER" ("SHIPPING_COURIER_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_SHIPPING_METHOD_08" FOREIGN KEY ("SHIPPING_METHOD_NUM")
	  REFERENCES "TREXONE_DATA"."SHIPPING_METHOD" ("SHIPPING_METHOD_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_SHIPMENT_SIGNATURE_05" FOREIGN KEY ("SHIPMENT_SIGNATURE_NUM")
	  REFERENCES "TREXONE_DATA"."SHIPMENT_SIGNATURE" ("SHIPMENT_SIGNATURE_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_PAYMENT_TYPE_05" FOREIGN KEY ("PAYMENT_TYPE_NUM")
	  REFERENCES "TREXONE_DATA"."PAYMENT_TYPE" ("PAYMENT_TYPE_NUM") ENABLE NOVALIDATE
   ) ;
-- ==========================================
