-- ==========================================

  CREATE TABLE "TREXONE_DATA"."MANIFEST_ITEM"
   (	"MANIFEST_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CHECK_OUT_DATESTAMP" DATE,
	"CHECK_OUT_USER" NUMBER(18,0),
	"CHECK_IN_DATESTAMP" DATE,
	"CHECK_IN_USER" NUMBER(18,0),
	"RETURN_DATESTAMP" DATE,
	"RETURN_USER" NUMBER(18,0),
	"RETURN_RECEIVED_DATESTAMP" DATE,
	"RETURN_RECEIVED_USER" NUMBER(18,0),
	"RETURN_REASON_TYPE" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"ITEM_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"MANIFEST_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"CF_FACILITY_NUM" NUMBER(18,0),
	"IS_PULLED_BACK" CHAR(1) DEFAULT 'N' NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"PRODUCT_NUM" NUMBER(18,0),
	"ITEM_QUANTITY" NUMBER(16,8),
	"RX_FACILITY_NUM" NUMBER(18,0),
	 CONSTRAINT "FK_ITEM_15" FOREIGN KEY ("ORDER_NUM", "ITEM_SEQ")
	  REFERENCES "TREXONE_DATA"."ITEM" ("ORDER_NUM", "ITEM_SEQ") ENABLE,
	 CONSTRAINT "FK_MANIFEST_1" FOREIGN KEY ("MANIFEST_NUM")
	  REFERENCES "TREXONE_DATA"."MANIFEST" ("MANIFEST_NUM") ENABLE,
	 CONSTRAINT "FK_RETURN_REASON_1" FOREIGN KEY ("RETURN_REASON_TYPE")
	  REFERENCES "TREXONE_DATA"."RETURN_REASON" ("RETURN_REASON_TYPE") ENABLE,
	 CONSTRAINT "FK_FACILITY_87" FOREIGN KEY ("CF_FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_PRODUCT_47" FOREIGN KEY ("PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT" ("PRODUCT_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_MANIFEST_ITEM" ON "TREXONE_DATA"."MANIFEST_ITEM" ("MANIFEST_ITEM_NUM", "ORDER_NUM", "ITEM_SEQ", "MANIFEST_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."MANIFEST_ITEM" ADD CONSTRAINT "PK_MANIFEST_ITEM" PRIMARY KEY ("MANIFEST_ITEM_NUM", "ORDER_NUM", "ITEM_SEQ", "MANIFEST_NUM")
  USING INDEX "TREXONE_DATA"."PK_MANIFEST_ITEM"  ENABLE;
-- ==========================================
