-- ==========================================

  CREATE TABLE "TREXONE_DATA"."MANIFEST"
   (	"MANIFEST_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CREATE_DATESTAMP" DATE NOT NULL ENABLE,
	"TOTE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DELIVERY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CLOSED_DATESTAMP" DATE,
	"CLOSED_USER" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"EXTERNAL_TOTE_ID" VARCHAR2(50),
	"CF_DELIVERY_METHOD_NUM" NUMBER(18,0),
	 CONSTRAINT "FK_DELIVERY_1" FOREIGN KEY ("DELIVERY_NUM")
	  REFERENCES "TREXONE_DATA"."DELIVERY" ("DELIVERY_NUM") ENABLE,
	 CONSTRAINT "FK_TOTE_1" FOREIGN KEY ("TOTE_NUM")
	  REFERENCES "TREXONE_DATA"."TOTE" ("TOTE_NUM") ENABLE,
	 CONSTRAINT "FK_CF_DELIVERY_METHOD_05" FOREIGN KEY ("CF_DELIVERY_METHOD_NUM")
	  REFERENCES "TREXONE_DATA"."CF_DELIVERY_METHOD" ("CF_DELIVERY_METHOD_NUM") ENABLE NOVALIDATE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_MANIFEST" ON "TREXONE_DATA"."MANIFEST" ("MANIFEST_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."MANIFEST" ADD CONSTRAINT "PK_MANIFEST" PRIMARY KEY ("MANIFEST_NUM")
  USING INDEX "TREXONE_DATA"."PK_MANIFEST"  ENABLE;
-- ==========================================
