-- ==========================================

  CREATE TABLE "TREXONE_DATA"."NUTRI_REF"
   (	"NREF_JAG_ID" CHAR(6) NOT NULL ENABLE,
	"NREF_TYPE" NUMBER(9,0) NOT NULL ENABLE,
	"NREF_SEQ" NUMBER(9,0) NOT NULL ENABLE,
	"NREF_TEXT" VARCHAR2(500),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_NUTRI_REF" ON "TREXONE_DATA"."NUTRI_REF" ("NREF_JAG_ID", "NREF_TYPE", "NREF_SEQ")
  ;
ALTER TABLE "TREXONE_DATA"."NUTRI_REF" ADD CONSTRAINT "PK_NUTRI_REF" PRIMARY KEY ("NREF_JAG_ID", "NREF_TYPE", "NREF_SEQ")
  USING INDEX "TREXONE_DATA"."PK_NUTRI_REF"  ENABLE;
-- ==========================================
