-- ==========================================

  CREATE TABLE "TREXONE_DATA"."NUTRI_ADMIN"
   (	"NADM_TEXT_ID" CHAR(6) NOT NULL ENABLE,
	"NADM_TEXT" VARCHAR2(500),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_NUTRI_ADMIN" ON "TREXONE_DATA"."NUTRI_ADMIN" ("NADM_TEXT_ID")
  ;
ALTER TABLE "TREXONE_DATA"."NUTRI_ADMIN" ADD CONSTRAINT "PK_NUTRI_ADMIN" PRIMARY KEY ("NADM_TEXT_ID")
  USING INDEX "TREXONE_DATA"."PK_NUTRI_ADMIN"  ENABLE;
-- ==========================================
