-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ORDER_RECORD_BASE"
   (	"ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_ORDER_NUMBER" VARCHAR2(10) NOT NULL ENABLE,
	"ACCOUNT_NUM" NUMBER(18,0),
	"IMAGE_GROUP_NUM" NUMBER(18,0),
	"ORDER_SOURCE_TYPE_NUM" NUMBER(18,0),
	"IS_FILL_AT_LOCAL" CHAR(1) NOT NULL ENABLE,
	"IS_PROCESS_LOCAL" CHAR(1) NOT NULL ENABLE,
	"ORDER_PRIORITY" NUMBER(9,0),
	"ORDER_DATE" DATE NOT NULL ENABLE,
	"ORDER_USER" NUMBER(18,0) NOT NULL ENABLE,
	"ORDER_QUOTE_PRICE" NUMBER(17,6),
	"IS_SIGNATURE_REQUIRED" CHAR(1) NOT NULL ENABLE,
	"PICKUP_TIME" DATE,
	"EXPECTED_NEW_RXS" NUMBER(9,0),
	"EXPECTED_REFILLS" NUMBER(9,0),
	"EXPECTED_OTCS" NUMBER(9,0),
	"EXPECTED_IMAGES" NUMBER(9,0),
	"EXPECTED_ITEMS" NUMBER(9,0),
	"RECEPTION_COMPLETE" CHAR(1),
	"SHIP_HANDLE_FEE" NUMBER(17,6),
	"SHIP_DATE" DATE,
	"TRACKING_NUMBER" VARCHAR2(200),
	"WEIGHT" NUMBER(16,8),
	"DELIVERY_METHOD_NUM" NUMBER(18,0),
	"ORDER_OWNER_FACILITY_NUM" NUMBER(18,0),
	"ORDER_ENTRY_FACILITY_NUM" NUMBER(18,0),
	"PICKUP_FACILITY_NUM" NUMBER(18,0),
	"TARGET_DISP_FACILITY_NUM" NUMBER(18,0),
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"PARENT_ORDER_NUM" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ELECTRONIC_ORDER_NUM" NUMBER(18,0),
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"RX_ORIGIN_CODE" CHAR(1),
	"PACKING_INSTRUCTIONS" VARCHAR2(1000),
	"IS_PACKED" CHAR(1),
	"GROUPING_END_TIME" DATE,
	"IS_SPLIT_ORDER" CHAR(1),
	"SPLIT_ORDER_USER" NUMBER(18,0),
	"SPLIT_ORDER_DATE" DATE,
	"IS_PAYMENT_COLLECTED" CHAR(1),
	"IS_MANUAL_PAYMENT_MODE" CHAR(1),
	"IS_DISPENSE_LOCAL" CHAR(1),
	 CONSTRAINT "FK_ACCOUNT_03" FOREIGN KEY ("ACCOUNT_NUM")
	  REFERENCES "TREXONE_DATA"."ACCOUNT" ("ACCOUNT_NUM") ENABLE,
	 CONSTRAINT "FK_DELIVERY_METHOD_02" FOREIGN KEY ("DELIVERY_METHOD_NUM")
	  REFERENCES "TREXONE_DATA"."DELIVERY_METHOD" ("DELIVERY_METHOD_NUM") ENABLE,
	 CONSTRAINT "FK_FACILITY_31" FOREIGN KEY ("TARGET_DISP_FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_FACILITY_32" FOREIGN KEY ("ORDER_ENTRY_FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_FACILITY_33" FOREIGN KEY ("ORDER_OWNER_FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_FACILITY_34" FOREIGN KEY ("PICKUP_FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_IMAGE_GROUP_02" FOREIGN KEY ("IMAGE_GROUP_NUM")
	  REFERENCES "TREXONE_DATA"."IMAGE_GROUP" ("IMAGE_GROUP_NUM") ENABLE,
	 CONSTRAINT "FK_ORDER_RECORD_02" FOREIGN KEY ("PARENT_ORDER_NUM")
	  REFERENCES "TREXONE_DATA"."ORDER_RECORD_BASE" ("ORDER_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_ORDER_SOURCE_TYPE_01" FOREIGN KEY ("ORDER_SOURCE_TYPE_NUM")
	  REFERENCES "TREXONE_DATA"."ORDER_SOURCE_TYPE" ("ORDER_SOURCE_TYPE_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE INDEX "TREXONE_DATA"."PK_ORDER_RECORD" ON "TREXONE_DATA"."ORDER_RECORD_BASE" ("ORDER_NUM", "ORDER_DATE")
  ;
ALTER TABLE "TREXONE_DATA"."ORDER_RECORD_BASE" ADD CONSTRAINT "PK_ORDER_RECORD" PRIMARY KEY ("ORDER_NUM")
  USING INDEX "TREXONE_DATA"."PK_ORDER_RECORD"  ENABLE NOVALIDATE;
-- ==========================================
