-- ==========================================

  CREATE TABLE "TREXONE_DATA"."OUTBOUND_IVR_REQUEST"
   (	"OUTBOUND_IVR_REQUEST_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ERROR" VARCHAR2(30),
	"IS_CANCELLED" CHAR(1),
	"IS_SUCCESSFUL" CHAR(1),
	"TIME_SENT" DATE,
	"ORDER_NUM" NUMBER(18,0),
	"ITEM_SEQ" NUMBER(18,0),
	"EVENT" NUMBER(1,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"SCHEDULED_SEND_TIME" DATE,
	"SUBMIT_TIME" DATE,
	 CONSTRAINT "FK_ITEM_14" FOREIGN KEY ("ORDER_NUM", "ITEM_SEQ")
	  REFERENCES "TREXONE_DATA"."ITEM" ("ORDER_NUM", "ITEM_SEQ") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_OUTBOUND_IVR_REQUEST" ON "TREXONE_DATA"."OUTBOUND_IVR_REQUEST" ("OUTBOUND_IVR_REQUEST_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."OUTBOUND_IVR_REQUEST" ADD CONSTRAINT "PK_OUTBOUND_IVR_REQUEST" PRIMARY KEY ("OUTBOUND_IVR_REQUEST_NUM")
  USING INDEX "TREXONE_DATA"."PK_OUTBOUND_IVR_REQUEST"  ENABLE;
-- ==========================================
