-- ==========================================

  CREATE TABLE "TREXONE_DATA"."OWNER_TYPE"
   (	"OWNER_TYPE_CODE" CHAR(1) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(30) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_OWNER_TYPE" ON "TREXONE_DATA"."OWNER_TYPE" ("OWNER_TYPE_CODE")
  ;
ALTER TABLE "TREXONE_DATA"."OWNER_TYPE" ADD CONSTRAINT "PK_OWNER_TYPE" PRIMARY KEY ("OWNER_TYPE_CODE")
  USING INDEX "TREXONE_DATA"."PK_OWNER_TYPE"  ENABLE;
-- ==========================================
