-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PACKAGE"
   (	"PACKAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SHIPMENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_PACKAGE" PRIMARY KEY ("PACKAGE_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SHIPMENT_01" FOREIGN KEY ("SHIPMENT_NUM")
	  REFERENCES "TREXONE_DATA"."SHIPMENT" ("SHIPMENT_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
