-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PACKAGING_TYPE_DETAILS"
   (	"PACKAGING_TYPE_DETAILS_NUM" NUMBER(18,0),
	"PACKAGING_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"IS_DEFAULT" CHAR(1),
	"IS_ENABLED" CHAR(1),
	"NUMBER_OF_LABELS" NUMBER(9,0),
	"DOC_TYPE_NAME" VARCHAR2(30),
	"SPECIAL_PACKAGING_CODE" CHAR(1),
	"HOA_REQUIRED" CHAR(1),
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	 CONSTRAINT "PK_PACKAGING_TYPE_DETAILS" PRIMARY KEY ("PACKAGING_TYPE_DETAILS_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_PACKAGING_TYPE_01" FOREIGN KEY ("PACKAGING_TYPE_NUM")
	  REFERENCES "TREXONE_DATA"."PACKAGING_TYPE" ("PACKAGING_TYPE_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_SYSTEM_USER_91" FOREIGN KEY ("SYS_USER")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE NOVALIDATE
   ) ;
-- ==========================================
