-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PACKAGING_TYPE"
   (	"PACKAGING_TYPE_NUM" NUMBER(18,0),
	"NAME" VARCHAR2(100) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	 CONSTRAINT "PK_PACKAGING_TYPE" PRIMARY KEY ("PACKAGING_TYPE_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_90" FOREIGN KEY ("SYS_USER")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE NOVALIDATE
   ) ;
-- ==========================================
