-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PASS_ORDER"
   (	"PASS_ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_FILL_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"ADMINISTRATION_DATE" DATE NOT NULL ENABLE,
	"ADMINISTRATION_HOUR" VARCHAR2(16),
	"DOSAGE" NUMBER(18,3) NOT NULL ENABLE,
	"ORDER_STATUS" CHAR(1) NOT NULL ENABLE,
	"DATE_ORDER_PACKAGED" DATE,
	"MSG_CODES" VARCHAR2(30),
	"BATCH_REQUEST_ID" VARCHAR2(7),
	"BATCH_SUBMISSION_DATE" DATE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	"LTC_HOA_NUM" NUMBER(18,0),
	 CONSTRAINT "PK_PASS_ORDER" PRIMARY KEY ("PASS_ORDER_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_FACILITY_99" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_RX_FILL_22" FOREIGN KEY ("RX_FILL_SEQ", "RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_FILL" ("RX_FILL_SEQ", "RX_RECORD_NUM") ENABLE,
	 CONSTRAINT "FK_LTC_HOA_08" FOREIGN KEY ("LTC_HOA_NUM")
	  REFERENCES "TREXONE_DATA"."LTC_HOA" ("LTC_HOA_NUM") ENABLE
   ) ;
-- ==========================================
