-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PATIENT_MED_CONDITION"
   (	"PATIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PATIENT_MED_CONDITION_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"STATUS" CHAR(1) NOT NULL ENABLE,
	"ONSET_DATE" DATE,
	"CREATE_DATE" DATE,
	"CREATE_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DEACTIVATE_DATE" DATE,
	"DEACTIVATE_USER" NUMBER(18,0),
	"ICD9_CODE" VARCHAR2(10),
	"ICD9_DESCRIPTION" VARCHAR2(255),
	"MEDICAL_CONDITION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TYPE_NUM" NUMBER(9,0),
	"DURATION_IN_DAYS" NUMBER(9,0),
	"REPORTED_DATE" DATE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"ADDED_VIA_MODULE" VARCHAR2(50) DEFAULT 'PATIENT ADMIN',
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_MEDICAL_CONDITION_XREF_01" FOREIGN KEY ("MEDICAL_CONDITION_NUM")
	  REFERENCES "TREXONE_DATA"."MEDICAL_CONDITION_XREF" ("MEDICAL_CONDITION_NUM") ENABLE,
	 CONSTRAINT "FK_PATIENT_09" FOREIGN KEY ("PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PATIENT_MED_CONDITION" ON "TREXONE_DATA"."PATIENT_MED_CONDITION" ("PATIENT_NUM", "PATIENT_MED_CONDITION_SEQ")
  ;
ALTER TABLE "TREXONE_DATA"."PATIENT_MED_CONDITION" ADD CONSTRAINT "PK_PATIENT_MED_CONDITION" PRIMARY KEY ("PATIENT_NUM", "PATIENT_MED_CONDITION_SEQ")
  USING INDEX "TREXONE_DATA"."PK_PATIENT_MED_CONDITION"  ENABLE;
-- ==========================================
