-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PATIENT_GROUP_DETAILS"
   (	"PATIENT_GROUP_DETAILS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"GROUP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"MESSAGE_TERMINATION_DAYS" NUMBER(9,0),
	"MESSAGE_TERMINATION_DATE" DATE,
	"MESSAGE" VARCHAR2(2000),
	"WF_STEPS" VARCHAR2(1000),
	"RX_ORIGINATION_NUMS" VARCHAR2(100),
	"RX_FILL_STATE" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	"MESSAGE_EFFECTIVE_DATE" DATE,
	 CONSTRAINT "PK_PATIENT_GROUP_DETAILS" PRIMARY KEY ("PATIENT_GROUP_DETAILS_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_GROUP_06" FOREIGN KEY ("GROUP_NUM")
	  REFERENCES "TREXONE_DATA"."GROUPS" ("GROUP_NUM") ENABLE
   ) ;
-- ==========================================
