-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PATIENT_EDUCATION_MONOGRAPH"
   (	"PEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NDC_NUMBER" VARCHAR2(11) NOT NULL ENABLE,
	"MSG_TYPE" VARCHAR2(2) NOT NULL ENABLE,
	"LANGUAGE_CODE" CHAR(2),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"MSG" CLOB,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_PEM" PRIMARY KEY ("PEM_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
