-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PATIENT_PREGNANT_ICD"
   (	"PATIENT_PREGNANT_ICD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ICD_CODE_VALUE" VARCHAR2(20) NOT NULL ENABLE,
	"ICD_CODE_TYPE" VARCHAR2(20) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PATIENT_PREGNANT_ICD9" ON "TREXONE_DATA"."PATIENT_PREGNANT_ICD" ("PATIENT_PREGNANT_ICD_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PATIENT_PREGNANT_ICD" ADD CONSTRAINT "PK_PATIENT_PREGNANT_ICD9" PRIMARY KEY ("PATIENT_PREGNANT_ICD_NUM")
  USING INDEX "TREXONE_DATA"."PK_PATIENT_PREGNANT_ICD9"  ENABLE;
-- ==========================================
