-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PATIENT_GROUP"
   (	"PATIENT_GROUP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"GROUP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PATIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"MESSAGE_TERMINATION_DATE" DATE,
	"MESSAGE_TERMINATION_OVERRIDE" CHAR(1),
	 CONSTRAINT "FK_GROUPS_02" FOREIGN KEY ("GROUP_NUM")
	  REFERENCES "TREXONE_DATA"."GROUPS" ("GROUP_NUM") ENABLE,
	 CONSTRAINT "FK_PATIENT_08" FOREIGN KEY ("PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PATIENT_GROUP" ON "TREXONE_DATA"."PATIENT_GROUP" ("PATIENT_GROUP_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PATIENT_GROUP" ADD CONSTRAINT "PK_PATIENT_GROUP" PRIMARY KEY ("PATIENT_GROUP_NUM")
  USING INDEX "TREXONE_DATA"."PK_PATIENT_GROUP"  ENABLE;
-- ==========================================
