-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PATIENT_MERGE_HISTORY"
   (	"PATIENT_MERGE_HISTORY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SOURCE_PATIENT_DATA" CLOB NOT NULL ENABLE,
	"TARGET_PATIENT_DATA" CLOB NOT NULL ENABLE,
	"TARGET_PATIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PATIENT_29" FOREIGN KEY ("TARGET_PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PKPATIENT_MERGE_HISTORY1" ON "TREXONE_DATA"."PATIENT_MERGE_HISTORY" ("PATIENT_MERGE_HISTORY_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PATIENT_MERGE_HISTORY" ADD CONSTRAINT "PKPATIENT_MERGE_HISTORY1" PRIMARY KEY ("PATIENT_MERGE_HISTORY_NUM")
  USING INDEX "TREXONE_DATA"."PKPATIENT_MERGE_HISTORY1"  ENABLE;
-- ==========================================
