-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PATIENT_FACILITY"
   (	"PATIENT_FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PATIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_FACILITY_36" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_PATIENT_07" FOREIGN KEY ("PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PATIENT_FACILITY" ON "TREXONE_DATA"."PATIENT_FACILITY" ("PATIENT_FACILITY_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PATIENT_FACILITY" ADD CONSTRAINT "PK_PATIENT_FACILITY" PRIMARY KEY ("PATIENT_FACILITY_NUM")
  USING INDEX "TREXONE_DATA"."PK_PATIENT_FACILITY"  ENABLE;
-- ==========================================
