-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PATIENT_ALLERGY"
   (	"PATIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ALLERGEN_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SEVERITY" VARCHAR2(10),
	"REACTANT_ONSET_DATE" DATE,
	"UD_REACT_SYMPTOMS" VARCHAR2(60),
	"STATUS" CHAR(1),
	"DESCRIPTION" VARCHAR2(255),
	"CREATE_DATE" DATE,
	"CREATE_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DEACTIVE_DATE" DATE,
	"DEACTIVE_USER" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_ALLERGEN_XREF_01" FOREIGN KEY ("ALLERGEN_NUM")
	  REFERENCES "TREXONE_DATA"."ALLERGEN_XREF" ("ALLERGEN_NUM") ENABLE,
	 CONSTRAINT "FK_PATIENT_22" FOREIGN KEY ("PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PATIENT_ALLERGY" ON "TREXONE_DATA"."PATIENT_ALLERGY" ("PATIENT_NUM", "ALLERGEN_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PATIENT_ALLERGY" ADD CONSTRAINT "PK_PATIENT_ALLERGY" PRIMARY KEY ("PATIENT_NUM", "ALLERGEN_NUM")
  USING INDEX "TREXONE_DATA"."PK_PATIENT_ALLERGY"  ENABLE;
-- ==========================================
