-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PATIENT_STATUS_DETAIL"
   (	"PATIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PATIENT_STATUS_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"NEW_STATUS" CHAR(1) NOT NULL ENABLE,
	"EFFECTIVE_DATE" DATE,
	"TERM_DATE" DATE,
	"COMMENTARY" VARCHAR2(255),
	"CREATE_DATE" DATE,
	"CREATE_USER" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PATIENT_11" FOREIGN KEY ("PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PATIENT_STATUS_DETAIL" ON "TREXONE_DATA"."PATIENT_STATUS_DETAIL" ("PATIENT_NUM", "PATIENT_STATUS_SEQ")
  ;
ALTER TABLE "TREXONE_DATA"."PATIENT_STATUS_DETAIL" ADD CONSTRAINT "PK_PATIENT_STATUS_DETAIL" PRIMARY KEY ("PATIENT_NUM", "PATIENT_STATUS_SEQ")
  USING INDEX "TREXONE_DATA"."PK_PATIENT_STATUS_DETAIL"  ENABLE;
-- ==========================================
