-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PATIENT_ID"
   (	"PATIENT_ID_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PATIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PATIENT_ID_SOURCE_NUM" NUMBER(18,0),
	"PATIENT_ID" VARCHAR2(36),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"IS_DEFAULT" CHAR(1),
	 CONSTRAINT "PK_PATIENT_ID" PRIMARY KEY ("PATIENT_ID_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "UC_PATIENT_ID_1" UNIQUE ("PATIENT_ID", "PATIENT_ID_SOURCE_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_PATIENT_ID_SOURCE_01" FOREIGN KEY ("PATIENT_ID_SOURCE_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT_ID_SOURCE" ("PATIENT_ID_SOURCE_NUM") ENABLE,
	 CONSTRAINT "FK_PATIENT_32" FOREIGN KEY ("PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE
   ) ;
-- ==========================================
