-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PAYMENT"
   (	"PAYMENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACCOUNT_MEMBER_CREDIT_CARD_NUM" NUMBER(18,0),
	"PAYMENT_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PAYMENT_DATE" DATE NOT NULL ENABLE,
	"PAYMENT_STATUS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PAYMENT_SOURCE" CHAR(2) NOT NULL ENABLE,
	"PAYMENT_AMOUNT" NUMBER(17,6),
	"PAYMENT_REVERSAL_AMOUNT" NUMBER(17,6),
	"REVERSAL_PAYMENT_NUM" NUMBER(18,0),
	"CREDIT_AUTHORIZATION_NUMBER" VARCHAR2(100),
	"CHECK_NUMBER" VARCHAR2(100),
	"MONEY_ORDER_NUMBER" VARCHAR2(100),
	"OTHER_PAYMENT_ID" VARCHAR2(100),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"CREDIT_ROUTING_ID" VARCHAR2(100),
	"PRE_OR_VOICE_AUTH_ID" VARCHAR2(100),
	"SETTLEMENT_DATE" DATE,
	"FF_DATE" DATE,
	"AUTHORIZED_DATE" DATE,
	"COMPLETION_DATE" DATE,
	"CANCELLED_DATE" DATE,
	"ACC_AR_ACCT_NUM" NUMBER(18,0),
	"PAYMENT_ITEM_SEQ" NUMBER(18,0),
	"IS_RX_STATUS_CHANGE" CHAR(1),
	"HEALTH_CARD_DESIGNATION" VARCHAR2(20),
	"HEALTH_CARD_DESIGNATION_DATE" DATE,
	"REQUESTED_AMOUNT" NUMBER(17,6),
	"IS_PARTIAL_AUTH_PAYMENT" CHAR(1),
	"IS_BACKUP_AUTH_PAYMENT" CHAR(1),
	"IS_EXTRA_UPDATE" CHAR(1),
	"AR_MAIL_SHIP_CHARGE_DATE" DATE,
	"CC_PAYMENT_TYPE_NUM" NUMBER(18,0),
	 CONSTRAINT "PK_PAYMENT" PRIMARY KEY ("PAYMENT_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_PAYMENT_TYPE_01" FOREIGN KEY ("PAYMENT_TYPE_NUM")
	  REFERENCES "TREXONE_DATA"."PAYMENT_TYPE" ("PAYMENT_TYPE_NUM") ENABLE,
	 CONSTRAINT "FK_PAYMENT_STATUS_01" FOREIGN KEY ("PAYMENT_STATUS_NUM")
	  REFERENCES "TREXONE_DATA"."PAYMENT_STATUS" ("PAYMENT_STATUS_NUM") ENABLE,
	 CONSTRAINT "FK_PAYMENT_01" FOREIGN KEY ("REVERSAL_PAYMENT_NUM")
	  REFERENCES "TREXONE_DATA"."PAYMENT" ("PAYMENT_NUM") ENABLE,
	 CONSTRAINT "FK_ACCOUNT_MEMBER_CREDIT_CD_02" FOREIGN KEY ("ACCOUNT_MEMBER_CREDIT_CARD_NUM")
	  REFERENCES "TREXONE_DATA"."ACCOUNT_MEMBER_CREDIT_CARD" ("ACCOUNT_MEMBER_CREDIT_CARD_NUM") ENABLE,
	 CONSTRAINT "FK_ACC_AR_ACCT_04" FOREIGN KEY ("ACC_AR_ACCT_NUM")
	  REFERENCES "TREXONE_DATA"."ACC_AR_ACCT" ("ACC_AR_ACCT_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
