-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PCS_PATIENT_PREFERENCE"
   (	"PCS_PATIENT_PREFERENCE_NUM" NUMBER(18,0),
	"PATIENT_NUM" NUMBER(18,0),
	"IS_MOBILE_APP_CUSTOMER" CHAR(1),
	"EVENTS_SUBSCRIBED" VARCHAR2(1000),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_PCS_PATIENT_PREFERENCE" PRIMARY KEY ("PCS_PATIENT_PREFERENCE_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_PATIENT_38" FOREIGN KEY ("PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE
   ) ;
-- ==========================================
