-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PDMP_RESPONSE_ERROR"
   (	"PDMP_RESPONSE_ERROR_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PDMP_RESPONSE_NUM" NUMBER(18,0),
	"MESSAGE_TYPE" CHAR(1),
	"MESSAGE" VARCHAR2(2048),
	"DETAILS" CLOB,
	"SOURCE" VARCHAR2(100),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	 CONSTRAINT "PDMP_RESPONSE_ERROR_PK" PRIMARY KEY ("PDMP_RESPONSE_ERROR_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "PDMP_RESPONSE_ERROR_FK01" FOREIGN KEY ("PDMP_RESPONSE_NUM")
	  REFERENCES "TREXONE_DATA"."PDMP_RESPONSE" ("PDMP_RESPONSE_NUM") ENABLE NOVALIDATE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTOYMINTERVAL(3,'MONTH')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
