-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PDMP_RESPONSE"
   (	"PDMP_RESPONSE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ASYNC_ID" VARCHAR2(36),
	"VENDOR_NAME" VARCHAR2(100),
	"REQUEST_TYPE" VARCHAR2(100),
	"RX_RECORD_NUM" NUMBER(18,0),
	"RX_FILL_SEQ" NUMBER(18,0),
	"REQUEST_MESSAGE" CLOB,
	"DESTINATION_URL" VARCHAR2(2048),
	"REQUEST_DATE" DATE,
	"HTTP_STATUS" NUMBER(4,0),
	"RESPONSE_MESSAGE" CLOB,
	"REPORT_REQUEST_URL" VARCHAR2(2048),
	"REPORT_LINK" VARCHAR2(2048),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0) DEFAULT 0,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0,
	"PARTITION_DATE" DATE DEFAULT sysdate NOT NULL ENABLE,
	"REPORT_EXPIRATION" TIMESTAMP (6) WITH TIME ZONE,
	"REPORT_OWNER_NUM" NUMBER(18,0),
	 CONSTRAINT "PK_PDMP_RESPONSE" PRIMARY KEY ("PDMP_RESPONSE_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_RX_FILL_30" FOREIGN KEY ("RX_FILL_SEQ", "RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_FILL" ("RX_FILL_SEQ", "RX_RECORD_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_SYSTEM_USER_86" FOREIGN KEY ("REPORT_OWNER_NUM")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE NOVALIDATE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTOYMINTERVAL(3,'MONTH')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
