-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PDMP_CHECK"
   (	"PDMP_CHECK_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0),
	"RX_FILL_SEQ" NUMBER(18,0),
	"IS_ACTIVE" CHAR(1),
	"SATISFIED_DATE" DATE,
	"SATISFIED_SYS_USER" NUMBER(18,0),
	"OVERRIDE_DATE" DATE,
	"OVERRIDE_SYS_USER" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0) DEFAULT 0,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0,
	"PARTITION_DATE" DATE DEFAULT sysdate NOT NULL ENABLE,
	 CONSTRAINT "PK_PDMP_CHECK" PRIMARY KEY ("PDMP_CHECK_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_RX_FILL_31" FOREIGN KEY ("RX_FILL_SEQ", "RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_FILL" ("RX_FILL_SEQ", "RX_RECORD_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_SYSTEM_USER_35" FOREIGN KEY ("SATISFIED_SYS_USER")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_SYSTEM_USER_36" FOREIGN KEY ("OVERRIDE_SYS_USER")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE NOVALIDATE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTOYMINTERVAL(3,'MONTH')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
