-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PERSON_ID_TYPE"
   (	"PERSON_ID_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ASAP_ID_TYPE_CODE" VARCHAR2(2),
	"DESCRIPTION" VARCHAR2(25) NOT NULL ENABLE,
	"IS_DEFAULT" CHAR(1) NOT NULL ENABLE,
	"DISPLAY_ORDER" NUMBER(3,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."UC_PERSON_ID_TYPE" ON "TREXONE_DATA"."PERSON_ID_TYPE" ("ASAP_ID_TYPE_CODE", "ERX_CLIENT_ID")
  ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PERSON_ID_TYPE" ON "TREXONE_DATA"."PERSON_ID_TYPE" ("PERSON_ID_TYPE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PERSON_ID_TYPE" ADD CONSTRAINT "PK_PERSON_ID_TYPE" PRIMARY KEY ("PERSON_ID_TYPE_NUM")
  USING INDEX "TREXONE_DATA"."PK_PERSON_ID_TYPE"  ENABLE;
ALTER TABLE "TREXONE_DATA"."PERSON_ID_TYPE" ADD CONSTRAINT "UC_PERSON_ID_TYPE" UNIQUE ("ASAP_ID_TYPE_CODE", "ERX_CLIENT_ID")
  USING INDEX "TREXONE_DATA"."UC_PERSON_ID_TYPE"  ENABLE;
-- ==========================================
