-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PHONE_LINK"
   (	"PHONE_LINK_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"OWNER" NUMBER(18,0) NOT NULL ENABLE,
	"OWNER_TYPE_CODE" CHAR(1) NOT NULL ENABLE,
	"USAGE" NUMBER(18,0) NOT NULL ENABLE,
	"PHONE_NUM" NUMBER(18,0),
	"PHONE_USAGE" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"NOTIFY_PATIENT" CHAR(1) DEFAULT 'N',
	 CONSTRAINT "FK_OWNER_TYPE_02" FOREIGN KEY ("OWNER_TYPE_CODE")
	  REFERENCES "TREXONE_DATA"."OWNER_TYPE" ("OWNER_TYPE_CODE") ENABLE,
	 CONSTRAINT "FK_PHONE_01" FOREIGN KEY ("PHONE_NUM")
	  REFERENCES "TREXONE_DATA"."PHONE" ("PHONE_NUM") DEFERRABLE ENABLE NOVALIDATE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PHONE_LINK" ON "TREXONE_DATA"."PHONE_LINK" ("PHONE_LINK_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PHONE_LINK" ADD CONSTRAINT "PK_PHONE_LINK" PRIMARY KEY ("PHONE_LINK_NUM")
  USING INDEX "TREXONE_DATA"."PK_PHONE_LINK"  ENABLE;
-- ==========================================
