-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PO_ACKNOWLEDGEMENT_ITEM"
   (	"PO_ACKNOWLEDGEMENT_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PURCHASE_ORDER_ACK_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PURCHASE_ORDER_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"QUANTITY" NUMBER(9,0),
	"ACQUISITION_COST" NUMBER(17,6),
	"SHIPPING_STATUS" CHAR(2),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PURCHASE_ORDER_ACK_01" FOREIGN KEY ("PURCHASE_ORDER_ACK_NUM")
	  REFERENCES "TREXONE_DATA"."PURCHASE_ORDER_ACK" ("PURCHASE_ORDER_ACK_NUM") ENABLE,
	 CONSTRAINT "FK_PURCHASE_ORDER_ITEM_01" FOREIGN KEY ("PURCHASE_ORDER_ITEM_NUM")
	  REFERENCES "TREXONE_DATA"."PURCHASE_ORDER_ITEM" ("PURCHASE_ORDER_ITEM_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PO_ACKNOWLEDGEMENT_ITEM" ON "TREXONE_DATA"."PO_ACKNOWLEDGEMENT_ITEM" ("PO_ACKNOWLEDGEMENT_ITEM_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PO_ACKNOWLEDGEMENT_ITEM" ADD CONSTRAINT "PK_PO_ACKNOWLEDGEMENT_ITEM" PRIMARY KEY ("PO_ACKNOWLEDGEMENT_ITEM_NUM")
  USING INDEX "TREXONE_DATA"."PK_PO_ACKNOWLEDGEMENT_ITEM"  ENABLE;
-- ==========================================
