-- ==========================================

  CREATE TABLE "TREXONE_DATA"."POG_MEMBERSHIP_RULE"
   (	"POG_MEM_RULE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRODUCT_ORDERING_GROUP_NUM" NUMBER(18,0),
	"PRODUCT_NUM" NUMBER(18,0),
	"INCLUDE_EXCLUDE_FLAG" CHAR(1) NOT NULL ENABLE,
	"IS_DIRECT_INCLUSION" CHAR(1) NOT NULL ENABLE,
	"IS_PRIMARY_PRODUCT" CHAR(1) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"IS_ORDERING_PRODUCT" CHAR(1) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"ACTIVE_POG_NUM" NUMBER GENERATED ALWAYS AS (DECODE("IS_PRIMARY_PRODUCT",'Y',"PRODUCT_ORDERING_GROUP_NUM",NULL)) VIRTUAL ,
	 CONSTRAINT "FK_PRODUCT_32" FOREIGN KEY ("PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT" ("PRODUCT_NUM") ENABLE,
	 CONSTRAINT "FK_PRODUCT_ORDERING_GROUP_1" FOREIGN KEY ("PRODUCT_ORDERING_GROUP_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT_ORDERING_GROUP" ("PRODUCT_ORDERING_GROUP_NUM") ENABLE,
	 CONSTRAINT "FK_DATA_GROUP_24" FOREIGN KEY ("DATA_GROUP")
	  REFERENCES "TREXONE_DATA"."DATA_GROUP" ("DATA_GROUP") ENABLE NOVALIDATE
   ) ;
  CREATE INDEX "TREXONE_DATA"."IN_POG_MEMBERSHIP_RULE_1" ON "TREXONE_DATA"."POG_MEMBERSHIP_RULE" ("PRODUCT_ORDERING_GROUP_NUM", "INCLUDE_EXCLUDE_FLAG", "PRODUCT_NUM", "DATA_GROUP")
  ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."UC_POG_MEMBERSHIP_RULE_01" ON "TREXONE_DATA"."POG_MEMBERSHIP_RULE" ("ACTIVE_POG_NUM")
  ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PKPOG_MEMBERSHIP_RULE" ON "TREXONE_DATA"."POG_MEMBERSHIP_RULE" ("POG_MEM_RULE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."POG_MEMBERSHIP_RULE" ADD CONSTRAINT "PKPOG_MEMBERSHIP_RULE" PRIMARY KEY ("POG_MEM_RULE_NUM")
  USING INDEX "TREXONE_DATA"."PKPOG_MEMBERSHIP_RULE"  ENABLE;
ALTER TABLE "TREXONE_DATA"."POG_MEMBERSHIP_RULE" ADD CONSTRAINT "UC_POG_MEMBERSHIP_RULE_1" UNIQUE ("PRODUCT_ORDERING_GROUP_NUM", "INCLUDE_EXCLUDE_FLAG", "PRODUCT_NUM", "DATA_GROUP")
  USING INDEX "TREXONE_DATA"."IN_POG_MEMBERSHIP_RULE_1"  ENABLE NOVALIDATE;
ALTER TABLE "TREXONE_DATA"."POG_MEMBERSHIP_RULE" ADD CONSTRAINT "UC_POG_MEMBERSHIP_RULE_01" UNIQUE ("ACTIVE_POG_NUM")
  USING INDEX "TREXONE_DATA"."UC_POG_MEMBERSHIP_RULE_01"  ENABLE;
-- ==========================================
