-- ==========================================

  CREATE TABLE "TREXONE_DATA"."POS_FINALIZATION"
   (	"POS_FINALIZATION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_FILL_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"TXN_TYPE" CHAR(1) NOT NULL ENABLE,
	"REGISTER_TXN" NUMBER(9,0) NOT NULL ENABLE,
	"REGISTER_TXN_SEQ" NUMBER(9,0) NOT NULL ENABLE,
	"POS_USERID" VARCHAR2(20) NOT NULL ENABLE,
	"POS_AMOUNT" NUMBER(17,6) NOT NULL ENABLE,
	"POS_DATESTAMP" DATE NOT NULL ENABLE,
	"PATIENT_PAY_SRC" CHAR(1) NOT NULL ENABLE,
	"PRICE_OVERRIDE_RSN_CD" CHAR(2) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"POS_TAX_AMOUNT" NUMBER(17,6) NOT NULL ENABLE,
	"REGISTER_NUM" NUMBER(9,0) NOT NULL ENABLE,
	"PARTIAL_FILL_NUM" NUMBER(2,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_FACILITY_38" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_RX_FILL_08" FOREIGN KEY ("RX_FILL_SEQ", "RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_FILL" ("RX_FILL_SEQ", "RX_RECORD_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_POS_FINALIZATION" ON "TREXONE_DATA"."POS_FINALIZATION" ("POS_FINALIZATION_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."POS_FINALIZATION" ADD CONSTRAINT "PK_POS_FINALIZATION" PRIMARY KEY ("POS_FINALIZATION_NUM")
  USING INDEX "TREXONE_DATA"."PK_POS_FINALIZATION"  ENABLE;
-- ==========================================
