-- ==========================================

  CREATE TABLE "TREXONE_DATA"."POS_ERROR"
   (	"POS_ERROR_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_NUMBER" VARCHAR2(20),
	"POS_DATESTAMP" DATE NOT NULL ENABLE,
	"ERROR_CODE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SALE_AMOUNT" NUMBER(17,6),
	"TAX_AMOUNT" NUMBER(17,6),
	"POS_USERID" VARCHAR2(20) NOT NULL ENABLE,
	"PRICE_OVERRIDE_RSN_CD" CHAR(2),
	"PATIENT_PAY_SRC" CHAR(1),
	"POS_TXN_TYPE" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"REFILL_NUM" NUMBER(18,0),
	"PARTIAL_FILL_SEQ" NUMBER(2,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_FACILITY_37" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_POS_ERROR" ON "TREXONE_DATA"."POS_ERROR" ("POS_ERROR_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."POS_ERROR" ADD CONSTRAINT "PK_POS_ERROR" PRIMARY KEY ("POS_ERROR_NUM")
  USING INDEX "TREXONE_DATA"."PK_POS_ERROR"  ENABLE;
-- ==========================================
