-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PPI_MESSAGE_ADDRESS"
   (	"PPI_MESSAGE_ADDRESS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PPI_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ENTITY_TYPE" CHAR(1) NOT NULL ENABLE,
	"LAST_NAME" VARCHAR2(35),
	"FIRST_NAME" VARCHAR2(35),
	"MIDDLE_NAME" VARCHAR2(35),
	"SUFFIX" VARCHAR2(10),
	"PREFIX" VARCHAR2(10),
	"ADDRESS_LINE_1" VARCHAR2(80),
	"ADDRESS_LINE_2" VARCHAR2(80),
	"CITY" VARCHAR2(40),
	"STATE" VARCHAR2(20),
	"ZIP_CODE" VARCHAR2(20),
	"EMAIL_ADDRESS" VARCHAR2(1000),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"PLACE_LOCATION_QUAL" VARCHAR2(3),
	"FORMER_LAST_NAME" VARCHAR2(35),
	"FORMER_FIRST_NAME" VARCHAR2(35),
	"FORMER_MIDDLE_NAME" VARCHAR2(35),
	"FORMER_SUFFIX" VARCHAR2(10),
	"FORMER_PREFIX" VARCHAR2(10),
	"DIRECT_ADDRESS" VARCHAR2(255),
	"PPI_MESSAGE_COB_NUM" NUMBER(18,0),
	"PREFERRED_FIRST_NAME" VARCHAR2(35),
	"PREFERRED_LAST_NAME" VARCHAR2(35),
	"PREFERRED_MIDDLE_NAME" VARCHAR2(35),
	"PREFERRED_SUFFIX" VARCHAR2(10),
	"PREFERRED_PREFIX" VARCHAR2(10),
	"PRONOUN" VARCHAR2(35),
	"PRONOUN_LOINC_VERSION" VARCHAR2(35),
	"PRONOUN_LOINC_VALUE" VARCHAR2(18),
	 CONSTRAINT "FK_PPI_MESSAGE_02" FOREIGN KEY ("PPI_MESSAGE_NUM")
	  REFERENCES "TREXONE_DATA"."PPI_MESSAGE" ("PPI_MESSAGE_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PPI_MESSAGE_ADDRESS" ON "TREXONE_DATA"."PPI_MESSAGE_ADDRESS" ("PPI_MESSAGE_ADDRESS_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PPI_MESSAGE_ADDRESS" ADD CONSTRAINT "PK_PPI_MESSAGE_ADDRESS" PRIMARY KEY ("PPI_MESSAGE_ADDRESS_NUM")
  USING INDEX "TREXONE_DATA"."PK_PPI_MESSAGE_ADDRESS"  ENABLE;
-- ==========================================
