-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PPI_REGISTRY_PRESCRIBER"
   (	"PPI_REGISTRY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRESCRIBER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_PPI_REGISTRY_PRESCRIBER" PRIMARY KEY ("PPI_REGISTRY_NUM", "PRESCRIBER_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_PPI_REGISTRY_02" FOREIGN KEY ("PPI_REGISTRY_NUM")
	  REFERENCES "TREXONE_DATA"."PPI_REGISTRY" ("PPI_REGISTRY_NUM") ENABLE,
	 CONSTRAINT "FK_PRESCRIBER_31" FOREIGN KEY ("PRESCRIBER_NUM")
	  REFERENCES "TREXONE_DATA"."PRESCRIBER" ("PRESCRIBER_NUM") ENABLE
   ) ;
-- ==========================================
