-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PPI_MSG_MED_CMPD_INGRED"
   (	"PPI_MSG_MED_CMPD_INGRED_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PPI_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PPI_MESSAGE_MEDICATION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ITEM_DESCRIPTION" VARCHAR2(105),
	"ITEM_NUMBER_CODE" VARCHAR2(200),
	"ITEM_NUMBER_QUAL" VARCHAR2(30),
	"ITEM_STRENGTH_VALUE" VARCHAR2(70),
	"ITEM_STRENGTH_FORM_CODE" VARCHAR2(200),
	"ITEM_STRENGTH_UOM_CODE" VARCHAR2(200),
	"ITEM_DEA_SCHEDULE_CODE" VARCHAR2(200),
	"ITEM_QTY" VARCHAR2(30),
	"ITEM_QTY_CODE_LIST_QUAL" VARCHAR2(30),
	"ITEM_QTY_UOM_CODE" VARCHAR2(200),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	"NDC" VARCHAR2(40),
	 CONSTRAINT "PK_PPI_MSG_MED_CMPD_INGRED" PRIMARY KEY ("PPI_MSG_MED_CMPD_INGRED_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_PPI_MSG_MED_CMPD_INGRED_02" FOREIGN KEY ("PPI_MESSAGE_MEDICATION_NUM")
	  REFERENCES "TREXONE_DATA"."PPI_MESSAGE_MEDICATION" ("PPI_MESSAGE_MEDICATION_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_PPI_MSG_MED_CMPD_INGRED_01" FOREIGN KEY ("PPI_MESSAGE_NUM")
	  REFERENCES "TREXONE_DATA"."PPI_MESSAGE" ("PPI_MESSAGE_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTOYMINTERVAL(3,'MONTH')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2016-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
