-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PPI_OBSERVATION_UCUM"
   (	"PPI_OBSERVATION_UCUM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"UCUM_UOM_CODE" VARCHAR2(30) NOT NULL ENABLE,
	"UCUM_DESCRIPTION" VARCHAR2(200),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_PPI_OBSERVATION_UCUM" PRIMARY KEY ("PPI_OBSERVATION_UCUM_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
