-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PPI_MESSAGE_ID"
   (	"PPI_MESSAGE_ID_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PPI_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ENTITY_TYPE" CHAR(1) NOT NULL ENABLE,
	"ID_TYPE" VARCHAR2(36) NOT NULL ENABLE,
	"ID_VALUE" VARCHAR2(80) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"PPI_MESSAGE_COB_NUM" NUMBER(18,0),
	 CONSTRAINT "FK_PPI_MESSAGE_05" FOREIGN KEY ("PPI_MESSAGE_NUM")
	  REFERENCES "TREXONE_DATA"."PPI_MESSAGE" ("PPI_MESSAGE_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PPI_MESSAGE_ID" ON "TREXONE_DATA"."PPI_MESSAGE_ID" ("PPI_MESSAGE_ID_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PPI_MESSAGE_ID" ADD CONSTRAINT "PK_PPI_MESSAGE_ID" PRIMARY KEY ("PPI_MESSAGE_ID_NUM")
  USING INDEX "TREXONE_DATA"."PK_PPI_MESSAGE_ID"  ENABLE;
-- ==========================================
