-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PPI_MSG_MED_DRUG_COVERG"
   (	"PPI_MSG_MED_DRUG_COVERG_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PPI_MESSAGE_MEDICATION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DRUG_COVERAGE_STATUS_CODE" VARCHAR2(2) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_PPI_MSG_MED_DRUG_COVERG" PRIMARY KEY ("PPI_MSG_MED_DRUG_COVERG_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_PPI_MESSAGE_MEDICATION_02" FOREIGN KEY ("PPI_MESSAGE_MEDICATION_NUM")
	  REFERENCES "TREXONE_DATA"."PPI_MESSAGE_MEDICATION" ("PPI_MESSAGE_MEDICATION_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
