-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PPI_REGISTRY"
   (	"PPI_REGISTRY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"GATEWAY_SOURCE" CHAR(1) NOT NULL ENABLE,
	"GATEWAY_ROOT_ID" VARCHAR2(50),
	"PRESCRIBER_NUM" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"PPI_NETWORK_NUM" NUMBER(18,0),
	 CONSTRAINT "FK_PPI_NETWORK_01" FOREIGN KEY ("PPI_NETWORK_NUM")
	  REFERENCES "TREXONE_DATA"."PPI_NETWORK" ("PPI_NETWORK_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PPI_REGISTRY" ON "TREXONE_DATA"."PPI_REGISTRY" ("PPI_REGISTRY_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PPI_REGISTRY" ADD CONSTRAINT "PK_PPI_REGISTRY" PRIMARY KEY ("PPI_REGISTRY_NUM")
  USING INDEX "TREXONE_DATA"."PK_PPI_REGISTRY"  ENABLE;
-- ==========================================
