-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PPI_CONTROL_MESSAGE"
   (	"PPI_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CODE" CHAR(3) NOT NULL ENABLE,
	"DESCRIPTION_CODE" CHAR(4),
	"DESCRIPTION" VARCHAR2(4000),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"RX_REFERENCE_NUMBER" VARCHAR2(35),
	"PRESCRIBER_ORDER_NUM" VARCHAR2(35),
	"PRESCRIPTION_DELIVERY_METHOD" CHAR(1),
	 CONSTRAINT "FK_PPI_MESSAGE_01" FOREIGN KEY ("PPI_MESSAGE_NUM")
	  REFERENCES "TREXONE_DATA"."PPI_MESSAGE" ("PPI_MESSAGE_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PPI_CONTROL_MESSAGE" ON "TREXONE_DATA"."PPI_CONTROL_MESSAGE" ("PPI_MESSAGE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PPI_CONTROL_MESSAGE" ADD CONSTRAINT "PK_PPI_CONTROL_MESSAGE" PRIMARY KEY ("PPI_MESSAGE_NUM")
  USING INDEX "TREXONE_DATA"."PK_PPI_CONTROL_MESSAGE"  ENABLE;
-- ==========================================
