-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PPI_MESSAGE_CODE"
   (	"PPI_MESSAGE_CODE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PPI_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CODE_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CODE_VALUE" VARCHAR2(30) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_PPI_MESSAGE_CODE" PRIMARY KEY ("PPI_MESSAGE_CODE_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_PPI_MESSAGE_08" FOREIGN KEY ("PPI_MESSAGE_NUM")
	  REFERENCES "TREXONE_DATA"."PPI_MESSAGE" ("PPI_MESSAGE_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
