-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PPI_MESSAGE_MED_DIAGNOSIS"
   (	"PPI_MESSAGE_MED_DIAGNOSIS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PPI_MESSAGE_MEDICATION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"QUALIFIER" VARCHAR2(20),
	"PRIMARY_DIAGNOSIS_QUAL" VARCHAR2(10),
	"PRIMARY_DIAGNOSIS_CODE" VARCHAR2(25),
	"SECONDARY_DIAGNOSIS_QUAL" VARCHAR2(10),
	"SECONDARY_DIAGNOSIS_CODE" VARCHAR2(25),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"PRIMARY_DIAGNOSIS_DESC" VARCHAR2(500),
	"PRI_DIAG_LAST_OFFICE_VISIT_DT" DATE,
	"SECONDARY_DIAGNOSIS_DESC" VARCHAR2(500),
	"SEC_DIAG_LAST_OFFICE_VISIT_DT" DATE,
	"EFFECTIVE_DATE" DATE,
	"EXPRIATION_DATE" DATE,
	 CONSTRAINT "FK_PPI_MESSAGE_MED_DIAG_01" FOREIGN KEY ("PPI_MESSAGE_MEDICATION_NUM")
	  REFERENCES "TREXONE_DATA"."PPI_MESSAGE_MEDICATION" ("PPI_MESSAGE_MEDICATION_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PPI_MESSAGE_MED_DIAGNOSIS" ON "TREXONE_DATA"."PPI_MESSAGE_MED_DIAGNOSIS" ("PPI_MESSAGE_MED_DIAGNOSIS_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PPI_MESSAGE_MED_DIAGNOSIS" ADD CONSTRAINT "PK_PPI_MESSAGE_MED_DIAGNOSIS" PRIMARY KEY ("PPI_MESSAGE_MED_DIAGNOSIS_NUM")
  USING INDEX "TREXONE_DATA"."PK_PPI_MESSAGE_MED_DIAGNOSIS"  ENABLE;
-- ==========================================
