-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PPI_MESSAGE_MED_PAT_DIAG"
   (	"PPI_MESSAGE_MED_PAT_DIAG_NUM" NUMBER(18,0),
	"PPI_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CLINICAL_INFO_QUALIFIER" VARCHAR2(20),
	"DIAGNOSIS_QUALIFIER" VARCHAR2(10),
	"DIAGNOSIS_CODE" VARCHAR2(17),
	"DIAGNOSIS_DESC" VARCHAR2(500),
	"LAST_OFFICE_VISIT_DATE" DATE,
	"EFFECTIVE_DATE" DATE,
	"EXPRIATION_DATE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_PPI_MESSAGE_MED_PAT_DIAG" PRIMARY KEY ("PPI_MESSAGE_MED_PAT_DIAG_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_120" FOREIGN KEY ("SYS_USER")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_PPI_MESSAGE_15" FOREIGN KEY ("PPI_MESSAGE_NUM")
	  REFERENCES "TREXONE_DATA"."PPI_MESSAGE" ("PPI_MESSAGE_NUM") ENABLE NOVALIDATE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTOYMINTERVAL(3,'MONTH')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
