-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PPI_NETWORK"
   (	"PPI_NETWORK_NUM" NUMBER(18,0),
	"NETWORK_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"PRIORITY" NUMBER(9,0) DEFAULT 10 NOT NULL ENABLE,
	"STOP_IN_DATA_ENTRY_IND" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE,
	"AUTOPOPULATE_SIG_IND" CHAR(1) DEFAULT 'N' NOT NULL ENABLE,
	"USE_EXPECTED_DISCHARGE_IND" CHAR(1) DEFAULT 'N' NOT NULL ENABLE,
	"OUTBOUND_PPI_MSG_USER_ID" VARCHAR2(50),
	"OUTBOUND_PPI_MSG_PASSWORD" VARCHAR2(200),
	"OUTBOUND_PPI_MSG_URL" VARCHAR2(500) NOT NULL ENABLE,
	"NETWORK_DOMAIN" VARCHAR2(255) NOT NULL ENABLE,
	"PPI_DIRECTORY_URL" VARCHAR2(500) NOT NULL ENABLE,
	"PARTNER_ACCOUNT_ID" VARCHAR2(50),
	"DIRECTORY_LOGIN_ID" VARCHAR2(50),
	"DIRECTORY_PASSWORD" VARCHAR2(50),
	"DIRECTORY_VERSION" VARCHAR2(15) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT sysdate NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"IS_SUPERSET_NETWORK" CHAR(1) DEFAULT 'N' NOT NULL ENABLE,
	"REFILL_QUANT_QUALIFIER_IND" CHAR(1) DEFAULT 'N' NOT NULL ENABLE,
	"IS_TEST_SYSTEM" CHAR(1),
	"INBOUND_PPI_MSG_USER_ID" VARCHAR2(50),
	"INBOUND_PPI_MSG_PASSWORD" VARCHAR2(200),
	"DIRECTORY_DOWNLOAD_BASE_URL" VARCHAR2(500),
	"PORTAL_ID" VARCHAR2(35),
	"DATA_PROVIDER_ID" VARCHAR2(35),
	"OUTBOUND_AUTH_URL" VARCHAR2(255),
	"IS_EXCLUSIVE" CHAR(1) DEFAULT 'N' NOT NULL ENABLE,
	 CONSTRAINT "PK_PPI_NETWORK" PRIMARY KEY ("PPI_NETWORK_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "UC_PPI_NETWORK_01" UNIQUE ("PRIORITY", "ERX_CLIENT_ID")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
