-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PPI_MSG_XML"
   (	"PPI_MSG_XML_NUM" NUMBER(18,0),
	"PPI_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"MESSAGE_XML" "XMLTYPE" NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_PPI_MSG_XML" PRIMARY KEY ("PPI_MSG_XML_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_123" FOREIGN KEY ("SYS_USER")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_PPI_MESSAGE_16" FOREIGN KEY ("PPI_MESSAGE_NUM")
	  REFERENCES "TREXONE_DATA"."PPI_MESSAGE" ("PPI_MESSAGE_NUM") ENABLE NOVALIDATE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTOYMINTERVAL(3,'MONTH')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
