-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PPI_MSG_ALLERGY_ADVERSE"
   (	"PPI_MSG_ALLERGY_ADVERSE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PPI_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SOURCE_OF_INFORMATION" VARCHAR2(30),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	"NO_KNOWN_ALLERGIES" VARCHAR2(20),
	"EFFECTIVE_DATE" DATE,
	"EXPIRATION_DATE" DATE,
	 CONSTRAINT "PK_PPI_MSG_ALLERGY_ADVERSE" PRIMARY KEY ("PPI_MSG_ALLERGY_ADVERSE_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_PPI_MSG_ALLERGY_ADVERSE_01" FOREIGN KEY ("PPI_MESSAGE_NUM")
	  REFERENCES "TREXONE_DATA"."PPI_MESSAGE" ("PPI_MESSAGE_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTOYMINTERVAL(3,'MONTH')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2016-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
