-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PPI_FACILITY_DIRECTORY_MSG"
   (	"PPI_FACILITY_DIRECTORY_MSG_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ACTION" CHAR(1) NOT NULL ENABLE,
	"STATUS" CHAR(1) NOT NULL ENABLE,
	"MODIFICATION_DATE" DATE NOT NULL ENABLE,
	"SENT_DATE" DATE,
	"MESSGAGE" VARCHAR2(50),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_FACILITY_84" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PPI_FACILITY_DIRECTORY_MSG" ON "TREXONE_DATA"."PPI_FACILITY_DIRECTORY_MSG" ("PPI_FACILITY_DIRECTORY_MSG_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PPI_FACILITY_DIRECTORY_MSG" ADD CONSTRAINT "PK_PPI_FACILITY_DIRECTORY_MSG" PRIMARY KEY ("PPI_FACILITY_DIRECTORY_MSG_NUM")
  USING INDEX "TREXONE_DATA"."PK_PPI_FACILITY_DIRECTORY_MSG"  ENABLE;
-- ==========================================
