-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PPI_MESSAGE_EXTRA_INFO"
   (	"PPI_MESSAGE_EXTRA_INFO_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PPI_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DRUG_NAME" VARCHAR2(35) NOT NULL ENABLE,
	"CONCAT_LOC" VARCHAR2(35) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PPI_MESSAGE_04" FOREIGN KEY ("PPI_MESSAGE_NUM")
	  REFERENCES "TREXONE_DATA"."PPI_MESSAGE" ("PPI_MESSAGE_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PPI_MESSAGE_EXTRA_INFO" ON "TREXONE_DATA"."PPI_MESSAGE_EXTRA_INFO" ("PPI_MESSAGE_EXTRA_INFO_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PPI_MESSAGE_EXTRA_INFO" ADD CONSTRAINT "PK_PPI_MESSAGE_EXTRA_INFO" PRIMARY KEY ("PPI_MESSAGE_EXTRA_INFO_NUM")
  USING INDEX "TREXONE_DATA"."PK_PPI_MESSAGE_EXTRA_INFO"  ENABLE;
-- ==========================================
