-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PPI_MESSAGE_COB"
   (	"PPI_MESSAGE_COB_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PPI_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PAYER_NAME" VARCHAR2(70),
	"CARD_HOLDER_ID" VARCHAR2(35),
	"CARD_HOLDER_LAST_NAME" VARCHAR2(35),
	"CARD_HOLDER_FIRST_NAME" VARCHAR2(35),
	"CARD_HOLDER_MIDDLE_NAME" VARCHAR2(35),
	"CARD_HOLDER_SUFFIX" VARCHAR2(10),
	"CARD_HOLDER_PREFIX" VARCHAR2(10),
	"GROUP_ID" VARCHAR2(35),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	"PAYER_RESPONSIBILITY_CODE" VARCHAR2(30),
	"PATIENT_RELATIONSHIP_CODE" VARCHAR2(30),
	"PERSON_CODE" VARCHAR2(10),
	"GROUP_NAME" VARCHAR2(70),
	"PBM_MEMBER_ID" VARCHAR2(80),
	"PAYER_TYPE" VARCHAR2(30),
	"INTERCHANGE_CONTROL_NUM" VARCHAR2(9),
	 CONSTRAINT "PK_PPI_MESSAGE_COB" PRIMARY KEY ("PPI_MESSAGE_COB_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_PPI_MESSAGE_09" FOREIGN KEY ("PPI_MESSAGE_NUM")
	  REFERENCES "TREXONE_DATA"."PPI_MESSAGE" ("PPI_MESSAGE_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
