-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PPI_REGISTRY_ADDR_LINK"
   (	"PPI_REGISTRY_ADDR_LINK_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PPI_REGISTRY_ADDR_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRESCRIBER_NUM" NUMBER(18,0),
	"PRESCRIBER_ADDRESS_NUM" NUMBER(18,0),
	"ACTIVE_START_DATE" DATE,
	"ACTIVE_END_DATE" DATE,
	"SERVICE_LEVEL" NUMBER(5,0),
	"LINK_TYPE" CHAR(1),
	"IS_PPI_ENABLED" CHAR(1) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"PPI_REGISTRY_ADDR_LL_NUM" NUMBER(18,0),
	 CONSTRAINT "FK_PPI_REGISTRY_ADDR_01" FOREIGN KEY ("PPI_REGISTRY_ADDR_NUM")
	  REFERENCES "TREXONE_DATA"."PPI_REGISTRY_ADDR" ("PPI_REGISTRY_ADDR_NUM") ENABLE,
	 CONSTRAINT "FK_PRESCRIBER_07" FOREIGN KEY ("PRESCRIBER_NUM")
	  REFERENCES "TREXONE_DATA"."PRESCRIBER" ("PRESCRIBER_NUM") ENABLE,
	 CONSTRAINT "FK_PRESCRIBER_ADDRESS_02" FOREIGN KEY ("PRESCRIBER_ADDRESS_NUM")
	  REFERENCES "TREXONE_DATA"."PRESCRIBER_ADDRESS" ("PRESCRIBER_ADDRESS_NUM") ENABLE,
	 CONSTRAINT "FK_PPI_REGISTRY_ADDR_LL_01" FOREIGN KEY ("PPI_REGISTRY_ADDR_LL_NUM")
	  REFERENCES "TREXONE_DATA"."PPI_REGISTRY_ADDR_LL" ("PPI_REGISTRY_ADDR_LL_NUM") ENABLE
   ) ;
  CREATE INDEX "TREXONE_DATA"."IN_PPI_REGISTRY_ADDR_LINK_04" ON "TREXONE_DATA"."PPI_REGISTRY_ADDR_LINK" ("PPI_REGISTRY_ADDR_NUM", "PRESCRIBER_ADDRESS_NUM")
  ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PPI_REGISTRY_ADDR_LINK" ON "TREXONE_DATA"."PPI_REGISTRY_ADDR_LINK" ("PPI_REGISTRY_ADDR_LINK_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PPI_REGISTRY_ADDR_LINK" ADD CONSTRAINT "PK_PPI_REGISTRY_ADDR_LINK" PRIMARY KEY ("PPI_REGISTRY_ADDR_LINK_NUM")
  USING INDEX "TREXONE_DATA"."PK_PPI_REGISTRY_ADDR_LINK"  ENABLE;
ALTER TABLE "TREXONE_DATA"."PPI_REGISTRY_ADDR_LINK" ADD CONSTRAINT "UC_PPI_REGISTRY_ADDR_LINK_01" UNIQUE ("PPI_REGISTRY_ADDR_NUM", "PRESCRIBER_ADDRESS_NUM")
  USING INDEX "TREXONE_DATA"."IN_PPI_REGISTRY_ADDR_LINK_04"  ENABLE NOVALIDATE;
-- ==========================================
