-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRACTICE_TABLES"
   (	"TABLE_TYPE" VARCHAR2(10) NOT NULL ENABLE,
	"TABLE_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"FILTER" VARCHAR2(500),
	"TABLE_ORDER" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE INDEX "TREXONE_DATA"."PK_PRACTICE_TABLES" ON "TREXONE_DATA"."PRACTICE_TABLES" ("TABLE_TYPE", "TABLE_NAME")
  ;
ALTER TABLE "TREXONE_DATA"."PRACTICE_TABLES" ADD CONSTRAINT "PK_PRACTICE_TABLES" PRIMARY KEY ("TABLE_TYPE", "TABLE_NAME")
  USING INDEX "TREXONE_DATA"."PK_PRACTICE_TABLES"  ENABLE;
-- ==========================================
