-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRD_COST_BASIS_OVRD"
   (	"PRD_COST_BASIS_OVRD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRODUCT_COST_BASIS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRODUCT_NUM" NUMBER(18,0),
	"COST_BASIS_SOURCE_NUM" NUMBER(18,0),
	"COST_BASIS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE,
	"TERMINATION_DATE" DATE,
	"PERCENT_MODIFIER" NUMBER(17,6),
	"ADJUST_MODIFIER" NUMBER(17,6),
	"TEMP_OVERRIDE" CHAR(1),
	"IS_MANUALLY_MAINTAINED" CHAR(1),
	"ANOTHER_PRD_COST_BASIS_NUM" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_PRD_COST_BASIS_OVRD" PRIMARY KEY ("PRD_COST_BASIS_OVRD_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_PRODUCT_COST_BASIS_02" FOREIGN KEY ("PRODUCT_COST_BASIS_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT_COST_BASIS" ("PRODUCT_COST_BASIS_NUM") ENABLE,
	 CONSTRAINT "FK_PRODUCT_46" FOREIGN KEY ("PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT" ("PRODUCT_NUM") ENABLE,
	 CONSTRAINT "FK_COST_BASIS_SOURCE_04" FOREIGN KEY ("COST_BASIS_SOURCE_NUM")
	  REFERENCES "TREXONE_DATA"."COST_BASIS_SOURCE" ("COST_BASIS_SOURCE_NUM") ENABLE,
	 CONSTRAINT "FK_PRODUCT_COST_BASIS_03" FOREIGN KEY ("ANOTHER_PRD_COST_BASIS_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT_COST_BASIS" ("PRODUCT_COST_BASIS_NUM") ENABLE
   ) ;
-- ==========================================
