-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PREFERRED_PRODUCT_MAP"
   (	"TO_PRODUCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"FROM_PRODUCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_FACILITY_70" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_PRODUCT_34" FOREIGN KEY ("TO_PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT" ("PRODUCT_NUM") ENABLE,
	 CONSTRAINT "FK_PRODUCT_35" FOREIGN KEY ("FROM_PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT" ("PRODUCT_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PREFERRED_PRODUCT_MAP" ON "TREXONE_DATA"."PREFERRED_PRODUCT_MAP" ("FACILITY_NUM", "FROM_PRODUCT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PREFERRED_PRODUCT_MAP" ADD CONSTRAINT "PK_PREFERRED_PRODUCT_MAP" PRIMARY KEY ("FACILITY_NUM", "FROM_PRODUCT_NUM")
  USING INDEX "TREXONE_DATA"."PK_PREFERRED_PRODUCT_MAP"  ENABLE;
-- ==========================================
