-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRESCRIBER_BASE"
   (	"PRESCRIBER_BASE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRESCRIBER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SOURCE_CODE" CHAR(1) NOT NULL ENABLE,
	"STATUS" CHAR(1) NOT NULL ENABLE,
	"INACTIVITY_CODE" VARCHAR2(4),
	"INACTIVE_STATUS_DATE" DATE,
	"TITLE_ABBR" VARCHAR2(10),
	"SALUTATION_ABBR" VARCHAR2(10),
	"FIRST_NAME" VARCHAR2(30),
	"MIDDLE_NAME" VARCHAR2(30),
	"LAST_NAME" VARCHAR2(30),
	"NAME_SUFFIX_ABBR" VARCHAR2(10),
	"GENDER_CODE" VARCHAR2(1),
	"SPECIALTY_1" VARCHAR2(20),
	"SPECIALTY_2" VARCHAR2(20),
	"SPECIALTY_3" VARCHAR2(20),
	"PROFESSIONAL_ACTIVITY" VARCHAR2(20),
	"DECEASED_DATE" DATE,
	"EMAIL_ADDRESS" VARCHAR2(256),
	"PRESCRIBER_TYPE" VARCHAR2(4),
	"PREFERRED_CONTACT_METHOD" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"LICENSE_STATUS" CHAR(1),
	"SPECIALTY_4" VARCHAR2(20),
	"SPECIALTY_5" VARCHAR2(20),
	"BIRTH_DATE" DATE,
	"SOCIAL_SECURITY_NUM" VARCHAR2(9),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PRESCRIBER_20" FOREIGN KEY ("PRESCRIBER_NUM")
	  REFERENCES "TREXONE_DATA"."PRESCRIBER" ("PRESCRIBER_NUM") DEFERRABLE ENABLE NOVALIDATE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRESCRIBER_BASE" ON "TREXONE_DATA"."PRESCRIBER_BASE" ("PRESCRIBER_BASE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRESCRIBER_BASE" ADD CONSTRAINT "PK_PRESCRIBER_BASE" PRIMARY KEY ("PRESCRIBER_BASE_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRESCRIBER_BASE"  ENABLE;
-- ==========================================
