-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRESCRIBER_GROUP"
   (	"PRESCRIBER_GROUP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"GROUP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRESCRIBER_NUM" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"SOURCE_CODE" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_GROUPS_03" FOREIGN KEY ("GROUP_NUM")
	  REFERENCES "TREXONE_DATA"."GROUPS" ("GROUP_NUM") ENABLE,
	 CONSTRAINT "FK_PRESCRIBER_10" FOREIGN KEY ("PRESCRIBER_NUM")
	  REFERENCES "TREXONE_DATA"."PRESCRIBER" ("PRESCRIBER_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRESCRIBER_GROUP" ON "TREXONE_DATA"."PRESCRIBER_GROUP" ("PRESCRIBER_GROUP_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRESCRIBER_GROUP" ADD CONSTRAINT "PK_PRESCRIBER_GROUP" PRIMARY KEY ("PRESCRIBER_GROUP_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRESCRIBER_GROUP"  ENABLE;
-- ==========================================
