-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRESCRIBER_NOTE"
   (	"PRESCRIBER_NOTE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRESCRIBER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NOTE_TEXT" VARCHAR2(4000),
	"CREATE_DATE" DATE,
	"PRIORITY_INDICATOR" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"SOURCE_CODE" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PRESCRIBER_12" FOREIGN KEY ("PRESCRIBER_NUM")
	  REFERENCES "TREXONE_DATA"."PRESCRIBER" ("PRESCRIBER_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRESCRIBER_NOTE" ON "TREXONE_DATA"."PRESCRIBER_NOTE" ("PRESCRIBER_NOTE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRESCRIBER_NOTE" ADD CONSTRAINT "PK_PRESCRIBER_NOTE" PRIMARY KEY ("PRESCRIBER_NOTE_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRESCRIBER_NOTE"  ENABLE;
-- ==========================================
