-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRICING_LIST_ITEM"
   (	"PRICING_LIST_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRICING_LIST_CONFIG_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRICING_FORMULA_NUM" NUMBER(18,0),
	"PRICING_FORMULA_NAME" VARCHAR2(30),
	"PROCESS_ORDER" NUMBER(9,0) NOT NULL ENABLE,
	"EXCLUDE_FROM_PROCESSING" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATA_FILTER" CLOB,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PRICING_FORMULA_03" FOREIGN KEY ("PRICING_FORMULA_NUM")
	  REFERENCES "TREXONE_DATA"."PRICING_FORMULA" ("PRICING_FORMULA_NUM") ENABLE,
	 CONSTRAINT "FK_PRICING_LIST_CONFIG_01" FOREIGN KEY ("PRICING_LIST_CONFIG_NUM")
	  REFERENCES "TREXONE_DATA"."PRICING_LIST_CONFIG" ("PRICING_LIST_CONFIG_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRICING_LIST_ITEM" ON "TREXONE_DATA"."PRICING_LIST_ITEM" ("PRICING_LIST_ITEM_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRICING_LIST_ITEM" ADD CONSTRAINT "PK_PRICING_LIST_ITEM" PRIMARY KEY ("PRICING_LIST_ITEM_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRICING_LIST_ITEM"  ENABLE;
-- ==========================================
