-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRICING_PROCESS_STEP"
   (	"PRICING_PROCESS_STEP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRICING_PROCESS_CONFIG_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRICING_STEP_TYPE_NUM" NUMBER(9,0),
	"EXCLUDE_FROM_PRICE" CHAR(1),
	"PROCESS_ORDER" NUMBER(9,0),
	"PRICING_STEP_QUALIFIER" VARCHAR2(30),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PRICING_PROCESS_CONFIG_01" FOREIGN KEY ("PRICING_PROCESS_CONFIG_NUM")
	  REFERENCES "TREXONE_DATA"."PRICING_PROCESS_CONFIG" ("PRICING_PROCESS_CONFIG_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRICING_PROCESS_STEP" ON "TREXONE_DATA"."PRICING_PROCESS_STEP" ("PRICING_PROCESS_STEP_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRICING_PROCESS_STEP" ADD CONSTRAINT "PK_PRICING_PROCESS_STEP" PRIMARY KEY ("PRICING_PROCESS_STEP_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRICING_PROCESS_STEP"  ENABLE;
-- ==========================================
