-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRICING_PROCESS_STEP_LIST"
   (	"PRICING_PROCESS_STEP_LIST_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRICING_PROCESS_STEP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRICING_LIST_NAME" VARCHAR2(30),
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE,
	"TERM_DATE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PRICING_PROCESS_STEP_01" FOREIGN KEY ("PRICING_PROCESS_STEP_NUM")
	  REFERENCES "TREXONE_DATA"."PRICING_PROCESS_STEP" ("PRICING_PROCESS_STEP_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRICING_PROCESS_STEP_LIST" ON "TREXONE_DATA"."PRICING_PROCESS_STEP_LIST" ("PRICING_PROCESS_STEP_LIST_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRICING_PROCESS_STEP_LIST" ADD CONSTRAINT "PK_PRICING_PROCESS_STEP_LIST" PRIMARY KEY ("PRICING_PROCESS_STEP_LIST_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRICING_PROCESS_STEP_LIST"  ENABLE;
-- ==========================================
