-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRICE_BOARD_REPORT"
   (	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRODUCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRICE_ON_DATE" DATE,
	"DISPENSED_QTY" NUMBER(16,8),
	"PRICE" NUMBER(17,6),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_FACILITY_66" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_PRODUCT_31" FOREIGN KEY ("PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT" ("PRODUCT_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PKPRICE_BOARD_REPORT" ON "TREXONE_DATA"."PRICE_BOARD_REPORT" ("FACILITY_NUM", "PRODUCT_NUM", "DISPENSED_QTY")
  ;
ALTER TABLE "TREXONE_DATA"."PRICE_BOARD_REPORT" ADD CONSTRAINT "PKPRICE_BOARD_REPORT" PRIMARY KEY ("FACILITY_NUM", "PRODUCT_NUM", "DISPENSED_QTY")
  USING INDEX "TREXONE_DATA"."PKPRICE_BOARD_REPORT"  ENABLE;
-- ==========================================
