-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRICING_LIST_CONFIG"
   (	"PRICING_LIST_CONFIG_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRICING_LIST_NUM" NUMBER(18,0),
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE,
	"TERM_DATE" DATE,
	"GENERIC_INDICATOR" CHAR(1),
	"GENERIC_PRICE_IND" CHAR(1),
	"GENERIC_PRICE_SPREAD_IND" CHAR(1),
	"GENERIC_MNFCTR_IND" CHAR(1),
	"GENERIC_NAMED_DRUG_IND" CHAR(1),
	"GENERIC_THERAPEUTIC_IND" CHAR(1),
	"USER_DEFINED_GENERIC_IND" CHAR(1),
	"PUBLISH_STATUS" CHAR(1),
	"PUBLISH_USER" NUMBER(18,0),
	"PUBLISH_DATE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PRICING_LIST_01" FOREIGN KEY ("PRICING_LIST_NUM")
	  REFERENCES "TREXONE_DATA"."PRICING_LIST" ("PRICING_LIST_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRICING_LIST_CONFIG" ON "TREXONE_DATA"."PRICING_LIST_CONFIG" ("PRICING_LIST_CONFIG_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRICING_LIST_CONFIG" ADD CONSTRAINT "PK_PRICING_LIST_CONFIG" PRIMARY KEY ("PRICING_LIST_CONFIG_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRICING_LIST_CONFIG"  ENABLE;
-- ==========================================
