-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRICING_TABLE_CONFIG"
   (	"PRICING_TABLE_CONFIG_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRICING_TABLE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE,
	"TERM_DATE" DATE,
	"MIN_VALUE" NUMBER(17,6),
	"MAX_VALUE" NUMBER(17,6),
	"EXTRACTION_METHOD" VARCHAR2(30),
	"BASIS_OF_COST" CHAR(2),
	"INDEX_VARIABLE" VARCHAR2(30) NOT NULL ENABLE,
	"PUBLISH_STATUS" CHAR(1),
	"PUBLISH_USER" NUMBER(18,0),
	"PUBLISH_DATE" DATE,
	"CALCULATION_TARGET" VARCHAR2(30),
	"COST_BASIS_NUM" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_COST_BASIS_02" FOREIGN KEY ("COST_BASIS_NUM")
	  REFERENCES "TREXONE_DATA"."COST_BASIS" ("COST_BASIS_NUM") ENABLE,
	 CONSTRAINT "FK_PRICING_TABLE_01" FOREIGN KEY ("PRICING_TABLE_NUM")
	  REFERENCES "TREXONE_DATA"."PRICING_TABLE" ("PRICING_TABLE_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRICING_TABLE_CONFIG" ON "TREXONE_DATA"."PRICING_TABLE_CONFIG" ("PRICING_TABLE_CONFIG_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRICING_TABLE_CONFIG" ADD CONSTRAINT "PK_PRICING_TABLE_CONFIG" PRIMARY KEY ("PRICING_TABLE_CONFIG_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRICING_TABLE_CONFIG"  ENABLE;
-- ==========================================
