-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRICE_QUOTE"
   (	"PRICE_QUOTE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0),
	"PRODUCT_NUM" NUMBER(18,0),
	"PATIENT_NUM" NUMBER(18,0),
	"TP_PLAN_NUM" NUMBER(18,0),
	"TP_BENEFIT_GROUP_SEQ" NUMBER(18,0),
	"TP_NETWORK_NUM" NUMBER(18,0),
	"SYSTEM_USER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"WRITTEN_DATE" DATE,
	"EXPIRE_DATE" DATE,
	"QUANTITY" NUMBER(16,8),
	"QOH_AT_QUOTE" NUMBER(16,8),
	"INGREDIENT_COST" NUMBER(17,6),
	"FEE" NUMBER(17,6),
	"TAX" NUMBER(17,6),
	"DISCOUNT" NUMBER(17,6),
	"OVERRIDE" NUMBER(17,6),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_FACILITY_40" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_PATIENT_13" FOREIGN KEY ("PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE,
	 CONSTRAINT "FK_PRODUCT_11" FOREIGN KEY ("PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT" ("PRODUCT_NUM") ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_12" FOREIGN KEY ("SYSTEM_USER_NUM")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE,
	 CONSTRAINT "FK_TP_BENEFIT_GROUP_01" FOREIGN KEY ("TP_PLAN_NUM", "TP_BENEFIT_GROUP_SEQ")
	  REFERENCES "TREXONE_DATA"."TP_BENEFIT_GROUP" ("TP_PLAN_NUM", "TP_BENEFIT_GROUP_SEQ") ENABLE,
	 CONSTRAINT "FK_TP_NETWORK_01" FOREIGN KEY ("TP_NETWORK_NUM")
	  REFERENCES "TREXONE_DATA"."TP_NETWORK" ("TP_NETWORK_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRICE_QUOTE" ON "TREXONE_DATA"."PRICE_QUOTE" ("PRICE_QUOTE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRICE_QUOTE" ADD CONSTRAINT "PK_PRICE_QUOTE" PRIMARY KEY ("PRICE_QUOTE_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRICE_QUOTE"  ENABLE;
-- ==========================================
