-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRICING_OVERRIDE_CODE_VALUE"
   (	"PRICING_OVERRIDE_CDE_VALUE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRICING_OVERRIDE_CODE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"VALUE" VARCHAR2(255) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PRICING_OVERRIDE_CODE_01" FOREIGN KEY ("PRICING_OVERRIDE_CODE_NUM")
	  REFERENCES "TREXONE_DATA"."PRICING_OVERRIDE_CODE" ("PRICING_OVERRIDE_CODE_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRICING_OVERRIDE_CODE_VALUE" ON "TREXONE_DATA"."PRICING_OVERRIDE_CODE_VALUE" ("PRICING_OVERRIDE_CDE_VALUE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRICING_OVERRIDE_CODE_VALUE" ADD CONSTRAINT "PK_PRICING_OVERRIDE_CODE_VALUE" PRIMARY KEY ("PRICING_OVERRIDE_CDE_VALUE_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRICING_OVERRIDE_CODE_VALUE"  ENABLE;
-- ==========================================
