-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRICING_TABLE_DETAIL"
   (	"PRICING_TABLE_DETAIL_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRICING_TABLE_CONFIG_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"INDEX_LOW_VALUE" NUMBER(17,6) NOT NULL ENABLE,
	"INDEX_HIGH_VALUE" NUMBER(17,6) NOT NULL ENABLE,
	"TABLE_CALCULATION" VARCHAR2(4000),
	"LINKED_TABLE_NUM" NUMBER(18,0),
	"LINKED_TABLE_NAME" VARCHAR2(30),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PRICING_TABLE_02" FOREIGN KEY ("LINKED_TABLE_NUM")
	  REFERENCES "TREXONE_DATA"."PRICING_TABLE" ("PRICING_TABLE_NUM") ENABLE,
	 CONSTRAINT "FK_PRICING_TABLE_CONFIG_01" FOREIGN KEY ("PRICING_TABLE_CONFIG_NUM")
	  REFERENCES "TREXONE_DATA"."PRICING_TABLE_CONFIG" ("PRICING_TABLE_CONFIG_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRICING_TABLE_DETAIL" ON "TREXONE_DATA"."PRICING_TABLE_DETAIL" ("PRICING_TABLE_DETAIL_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRICING_TABLE_DETAIL" ADD CONSTRAINT "PK_PRICING_TABLE_DETAIL" PRIMARY KEY ("PRICING_TABLE_DETAIL_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRICING_TABLE_DETAIL"  ENABLE;
-- ==========================================
