-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRICING_TABLE"
   (	"PRICING_TABLE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(30) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(45),
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE,
	"TERM_DATE" DATE,
	"PRICING_STEP_TYPE_NUM" NUMBER(9,0) NOT NULL ENABLE,
	"CASH_TP_INDICATOR" CHAR(1) NOT NULL ENABLE,
	"PUBLISH_STATUS" CHAR(1),
	"PUBLISH_USER" NUMBER(18,0),
	"PUBLISH_DATE" DATE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRICING_TABLE" ON "TREXONE_DATA"."PRICING_TABLE" ("PRICING_TABLE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRICING_TABLE" ADD CONSTRAINT "PK_PRICING_TABLE" PRIMARY KEY ("PRICING_TABLE_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRICING_TABLE"  ENABLE;
-- ==========================================
