-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRICE_LINK_RULE_SET"
   (	"PRICE_LINK_RULE_SET_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE,
	"TERM_DATE" DATE,
	"CASH_TP_INDICATOR" CHAR(1),
	"PUBLISH_STATUS" CHAR(1),
	"PUBLISH_USER" NUMBER(18,0),
	"PUBLISH_DATE" DATE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRICE_LINK_RULE_SET" ON "TREXONE_DATA"."PRICE_LINK_RULE_SET" ("PRICE_LINK_RULE_SET_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRICE_LINK_RULE_SET" ADD CONSTRAINT "PK_PRICE_LINK_RULE_SET" PRIMARY KEY ("PRICE_LINK_RULE_SET_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRICE_LINK_RULE_SET"  ENABLE;
-- ==========================================
