-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRICING_HOTLIST"
   (	"PRICING_HOTLIST_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(30) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE,
	"TERM_DATE" DATE,
	"PUBLISH_STATUS" CHAR(1),
	"PUBLISH_USER" NUMBER(18,0),
	"PUBLISH_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."UC_PRICING_HOTLIST_1" ON "TREXONE_DATA"."PRICING_HOTLIST" ("NAME", "DATA_GROUP", "ERX_CLIENT_ID")
  ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRICING_HOTLIST" ON "TREXONE_DATA"."PRICING_HOTLIST" ("PRICING_HOTLIST_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRICING_HOTLIST" ADD CONSTRAINT "PK_PRICING_HOTLIST" PRIMARY KEY ("PRICING_HOTLIST_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRICING_HOTLIST"  ENABLE;
ALTER TABLE "TREXONE_DATA"."PRICING_HOTLIST" ADD CONSTRAINT "UC_PRICING_HOTLIST_1" UNIQUE ("NAME", "DATA_GROUP", "ERX_CLIENT_ID")
  USING INDEX "TREXONE_DATA"."UC_PRICING_HOTLIST_1"  ENABLE;
-- ==========================================
