-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRICING_HOTLIST_CONFIG"
   (	"PRICING_HOTLIST_CONFIG_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRICING_HOTLIST_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"IS_TOTAL_COST" CHAR(1) NOT NULL ENABLE,
	"IS_APPLY_DISCOUNTS" CHAR(1) NOT NULL ENABLE,
	"ADJUST_MASTER_PRODUCT_NUM" NUMBER(18,0),
	"ADJUST_COST_BASIS_NUM" NUMBER(18,0),
	"IS_AUTO_ADJUST_PRICES" CHAR(1) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE,
	"TERM_DATE" DATE,
	"PUBLISH_STATUS" CHAR(1),
	"PUBLISH_USER" NUMBER(18,0),
	"PUBLISH_DATE" DATE,
	"EXTRACTION_METHOD" VARCHAR2(30),
	"DATA_FILTER" CLOB,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PRICING_HOTLIST_01" FOREIGN KEY ("PRICING_HOTLIST_NUM")
	  REFERENCES "TREXONE_DATA"."PRICING_HOTLIST" ("PRICING_HOTLIST_NUM") ENABLE,
	 CONSTRAINT "FK_PRODUCT_41" FOREIGN KEY ("ADJUST_MASTER_PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT" ("PRODUCT_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRICING_HOTLIST_CONFIG" ON "TREXONE_DATA"."PRICING_HOTLIST_CONFIG" ("PRICING_HOTLIST_CONFIG_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRICING_HOTLIST_CONFIG" ADD CONSTRAINT "PK_PRICING_HOTLIST_CONFIG" PRIMARY KEY ("PRICING_HOTLIST_CONFIG_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRICING_HOTLIST_CONFIG"  ENABLE;
-- ==========================================
