-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRICING_PROCESS"
   (	"PRICING_PROCESS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(30),
	"PROCESS_TYPE" VARCHAR2(30) NOT NULL ENABLE,
	"TP_PLAN_NUM" NUMBER(18,0),
	"TP_BENEFIT_GROUP_SEQ" NUMBER(18,0),
	"TP_NETWORK_NUM" NUMBER(18,0),
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE,
	"TERM_DATE" DATE,
	"PUBLISH_STATUS" CHAR(1),
	"PUBLISH_USER" NUMBER(18,0),
	"PUBLISH_DATE" DATE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_TP_BENEFIT_GROUP_02" FOREIGN KEY ("TP_PLAN_NUM", "TP_BENEFIT_GROUP_SEQ")
	  REFERENCES "TREXONE_DATA"."TP_BENEFIT_GROUP" ("TP_PLAN_NUM", "TP_BENEFIT_GROUP_SEQ") ENABLE,
	 CONSTRAINT "FK_TP_NETWORK_02" FOREIGN KEY ("TP_NETWORK_NUM")
	  REFERENCES "TREXONE_DATA"."TP_NETWORK" ("TP_NETWORK_NUM") ENABLE,
	 CONSTRAINT "FK_TP_PLAN_11" FOREIGN KEY ("TP_PLAN_NUM")
	  REFERENCES "TREXONE_DATA"."TP_PLAN" ("TP_PLAN_NUM") ENABLE NOVALIDATE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRICING_PROCESS" ON "TREXONE_DATA"."PRICING_PROCESS" ("PRICING_PROCESS_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRICING_PROCESS" ADD CONSTRAINT "PK_PRICING_PROCESS" PRIMARY KEY ("PRICING_PROCESS_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRICING_PROCESS"  ENABLE;
-- ==========================================
