-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRINT_DEVICE_TYPE"
   (	"PRINT_DEVICE_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(30) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(256),
	"IS_COLOR_CAPABLE" CHAR(1) NOT NULL ENABLE,
	"IS_DUPLEX_CAPABLE" CHAR(1) NOT NULL ENABLE,
	"IS_DEFAULT" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"LANGUAGE" VARCHAR2(10) NOT NULL ENABLE,
	"FONTS" VARCHAR2(2048),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRINT_DEVICE_TYPE" ON "TREXONE_DATA"."PRINT_DEVICE_TYPE" ("PRINT_DEVICE_TYPE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRINT_DEVICE_TYPE" ADD CONSTRAINT "PK_PRINT_DEVICE_TYPE" PRIMARY KEY ("PRINT_DEVICE_TYPE_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRINT_DEVICE_TYPE"  ENABLE;
-- ==========================================
