-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRINT_DEVICE_PREF"
   (	"PRINT_DEVICE_PREF_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRINT_DOC_MEDIA_GROUP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CLIENT_LOCATION_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_PRINTER_TRAY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ORDER_OF_PREFERENCE" NUMBER(10,0),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_CLIENT_LOCATION_01" FOREIGN KEY ("CLIENT_LOCATION_NUM")
	  REFERENCES "TREXONE_DATA"."CLIENT_LOCATION" ("CLIENT_LOCATION_NUM") ENABLE,
	 CONSTRAINT "FK_FACILITY_41" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_FACILITY_PRINTER_TRAY_01" FOREIGN KEY ("FACILITY_PRINTER_TRAY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY_PRINTER_TRAY" ("FACILITY_PRINTER_TRAY_NUM") ENABLE,
	 CONSTRAINT "FK_PRINT_DOC_MEDIA_GROUP_03" FOREIGN KEY ("PRINT_DOC_MEDIA_GROUP_NUM")
	  REFERENCES "TREXONE_DATA"."PRINT_DOC_MEDIA_GROUP" ("PRINT_DOC_MEDIA_GROUP_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRINT_DEVICE_PREF" ON "TREXONE_DATA"."PRINT_DEVICE_PREF" ("PRINT_DEVICE_PREF_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRINT_DEVICE_PREF" ADD CONSTRAINT "PK_PRINT_DEVICE_PREF" PRIMARY KEY ("PRINT_DEVICE_PREF_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRINT_DEVICE_PREF"  ENABLE;
-- ==========================================
