-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRINT_MEDIA_TYPE"
   (	"PRINT_MEDIA_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(30) NOT NULL ENABLE,
	"WIDTH_IN_INCHES" NUMBER(5,2) NOT NULL ENABLE,
	"HEIGHT_IN_INCHES" NUMBER(5,2) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(256),
	"IS_DOUBLE_SIDED" CHAR(1) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE
   ) ;
  CREATE INDEX "TREXONE_DATA"."PK_PRINT_MEDIA_TYPE" ON "TREXONE_DATA"."PRINT_MEDIA_TYPE" ("PRINT_MEDIA_TYPE_NUM", "ERX_CLIENT_ID")
  ;
ALTER TABLE "TREXONE_DATA"."PRINT_MEDIA_TYPE" ADD CONSTRAINT "PK_PRINT_MEDIA_TYPE" PRIMARY KEY ("PRINT_MEDIA_TYPE_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRINT_MEDIA_TYPE"  ENABLE;
-- ==========================================
