-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRINT_DOC_MEDIA_GROUP"
   (	"PRINT_DOC_MEDIA_GROUP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRINT_MEDIA_TYPE_NUM" NUMBER(18,0),
	"PRINT_DOC_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DEVICE_CONTEXT_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DEVICE_CONTEXT_02" FOREIGN KEY ("DEVICE_CONTEXT_NUM")
	  REFERENCES "TREXONE_DATA"."DEVICE_CONTEXT" ("DEVICE_CONTEXT_NUM") ENABLE,
	 CONSTRAINT "FK_PRINT_DOC_01" FOREIGN KEY ("PRINT_DOC_NUM")
	  REFERENCES "TREXONE_DATA"."PRINT_DOC" ("PRINT_DOC_NUM") ENABLE,
	 CONSTRAINT "FK_PRINT_MEDIA_TYPE_03" FOREIGN KEY ("PRINT_MEDIA_TYPE_NUM")
	  REFERENCES "TREXONE_DATA"."PRINT_MEDIA_TYPE" ("PRINT_MEDIA_TYPE_NUM") ENABLE NOVALIDATE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRINT_DOC_MEDIA_GROUP" ON "TREXONE_DATA"."PRINT_DOC_MEDIA_GROUP" ("PRINT_DOC_MEDIA_GROUP_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRINT_DOC_MEDIA_GROUP" ADD CONSTRAINT "PK_PRINT_DOC_MEDIA_GROUP" PRIMARY KEY ("PRINT_DOC_MEDIA_GROUP_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRINT_DOC_MEDIA_GROUP"  ENABLE;
-- ==========================================
