-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRINT_DOC"
   (	"PRINT_DOC_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRINT_DEVICE_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DOC_TYPE_PROVIDER" VARCHAR2(250) NOT NULL ENABLE,
	"NAME" VARCHAR2(70) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(80),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PRINT_DEVICE_TYPE_03" FOREIGN KEY ("PRINT_DEVICE_TYPE_NUM")
	  REFERENCES "TREXONE_DATA"."PRINT_DEVICE_TYPE" ("PRINT_DEVICE_TYPE_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRINT_DOC" ON "TREXONE_DATA"."PRINT_DOC" ("PRINT_DOC_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRINT_DOC" ADD CONSTRAINT "PK_PRINT_DOC" PRIMARY KEY ("PRINT_DOC_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRINT_DOC"  ENABLE;
-- ==========================================
