-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRIVACY_ACKNOWLEDGMENT"
   (	"PRIVACY_ACKNOWLEDGMENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PATIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"GOOD_FAITH_EFFORT_REASON_NUM" NUMBER(18,0),
	"PRIVACY_ACTION_DATE" DATE NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DOC_VERSION_NUM" NUMBER(18,0),
	"ACTION_CODE" CHAR(1),
	"ACKNOWLEDGE_TYPE_CODE" CHAR(1),
	"ACKNOWLEDGING_PERSON_NAME" VARCHAR2(100),
	"SIGNATURE_IMAGE_NUM" NUMBER(18,0),
	"COMMENT_TEXT" VARCHAR2(1000),
	"CREATE_USER" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DOC_VERSION_01" FOREIGN KEY ("DOC_VERSION_NUM")
	  REFERENCES "TREXONE_DATA"."DOC_VERSION" ("DOC_VERSION_NUM") ENABLE,
	 CONSTRAINT "FK_FACILITY_11" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_GOOD_FAITH_EFFORT_REASON_01" FOREIGN KEY ("GOOD_FAITH_EFFORT_REASON_NUM")
	  REFERENCES "TREXONE_DATA"."GOOD_FAITH_EFFORT_REASON" ("GOOD_FAITH_EFFORT_REASON_NUM") ENABLE,
	 CONSTRAINT "FK_IMAGE_03" FOREIGN KEY ("SIGNATURE_IMAGE_NUM")
	  REFERENCES "TREXONE_DATA"."IMAGE" ("IMAGE_NUM") ENABLE,
	 CONSTRAINT "FK_PATIENT_02" FOREIGN KEY ("PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRIVACY_ACKNOWLEDGMENT" ON "TREXONE_DATA"."PRIVACY_ACKNOWLEDGMENT" ("PRIVACY_ACKNOWLEDGMENT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRIVACY_ACKNOWLEDGMENT" ADD CONSTRAINT "PK_PRIVACY_ACKNOWLEDGMENT" PRIMARY KEY ("PRIVACY_ACKNOWLEDGMENT_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRIVACY_ACKNOWLEDGMENT"  ENABLE;
-- ==========================================
