-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRODUCT_MESSAGE"
   (	"PRODUCT_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRODUCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"MESSAGE_TEXT" VARCHAR2(256),
	"PRIORITY" NUMBER(9,0),
	"EFFECTIVE_DATE" DATE,
	"EXPIRATION_DATE" DATE,
	"IS_ALL_STATE" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PRODUCT_17" FOREIGN KEY ("PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT" ("PRODUCT_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRODUCT_MESSAGE" ON "TREXONE_DATA"."PRODUCT_MESSAGE" ("PRODUCT_MESSAGE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRODUCT_MESSAGE" ADD CONSTRAINT "PK_PRODUCT_MESSAGE" PRIMARY KEY ("PRODUCT_MESSAGE_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRODUCT_MESSAGE"  ENABLE;
-- ==========================================
