-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRODUCT_STATE_OVERRIDE"
   (	"PRODUCT_STATE_OVERRIDE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRODUCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CTRY_CODE" VARCHAR2(8) NOT NULL ENABLE,
	"STATE_CODE" VARCHAR2(2) NOT NULL ENABLE,
	"DRUG_SCHEDULE" VARCHAR2(30),
	"IS_REPORTABLE" CHAR(1),
	"IS_SCHEDULED_RX_ID_REQ" CHAR(1),
	"IS_TAX_EXEMPT" CHAR(1),
	"IS_MANDATED" CHAR(1),
	"PRICE_BOARD_QUANTITY" NUMBER(16,8),
	"PRICE_BOARD_QUANTITY2" NUMBER(16,8),
	"PRICE_BOARD_QUANTITY3" NUMBER(16,8),
	"PRICE_BOARD_QUANTITY4" NUMBER(16,8),
	"PRICE_BOARD_QUANTITY5" NUMBER(16,8),
	"BILLING_UNITS" VARCHAR2(2),
	"FORMULARY_INDICATOR" VARCHAR2(1),
	"FORMULARY_IND_EFFECTIVE_DATE" DATE,
	"PACKAGE_SIZE_DIVISOR" NUMBER(11,3),
	"QUANTITY_BILL_UNITS" VARCHAR2(10),
	"BILLING_CODE" VARCHAR2(11),
	"BILLING_CODE_EFFECTIVE_DATE" DATE,
	"GENERIC_BILLING_CODE" VARCHAR2(11),
	"GENERIC_BC_EFFECTIVE_DATE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"PRODUCT_FACILITY_NUM" NUMBER(18,0),
	 CONSTRAINT "FK_PRODUCT_19" FOREIGN KEY ("PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT" ("PRODUCT_NUM") ENABLE,
	 CONSTRAINT "FK_STATE_05" FOREIGN KEY ("CTRY_CODE", "STATE_CODE")
	  REFERENCES "TREXONE_DATA"."STATE" ("CTRY_CODE", "STATE_CODE") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRODUCT_STATE_OVERRIDE" ON "TREXONE_DATA"."PRODUCT_STATE_OVERRIDE" ("PRODUCT_STATE_OVERRIDE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRODUCT_STATE_OVERRIDE" ADD CONSTRAINT "PK_PRODUCT_STATE_OVERRIDE" PRIMARY KEY ("PRODUCT_STATE_OVERRIDE_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRODUCT_STATE_OVERRIDE"  ENABLE;
-- ==========================================
