-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRODUCT_IMAGE"
   (	"PRODUCT_IMAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DRUG_NUM" NUMBER(18,0),
	"EFFECTIVE_DATE" DATE,
	"EXPIRATION_DATE" DATE,
	"COMMENTS" VARCHAR2(256),
	"IMAGE_URL" VARCHAR2(256),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"NDC_NUMBER" VARCHAR2(20),
	"MANUFACTURER" VARCHAR2(30),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DRUG_XREF_04" FOREIGN KEY ("DRUG_NUM")
	  REFERENCES "TREXONE_DATA"."DRUG_XREF" ("DRUG_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRODUCT_IMAGE" ON "TREXONE_DATA"."PRODUCT_IMAGE" ("PRODUCT_IMAGE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRODUCT_IMAGE" ADD CONSTRAINT "PK_PRODUCT_IMAGE" PRIMARY KEY ("PRODUCT_IMAGE_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRODUCT_IMAGE"  ENABLE;
-- ==========================================
