-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRODUCT_FORMULARY"
   (	"PRODUCT_FORMULARY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRODUCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FORMULARY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"EFFECTIVE_DATE" DATE,
	"TERMINATION_DATE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_FORMULARY_01" FOREIGN KEY ("FORMULARY_NUM")
	  REFERENCES "TREXONE_DATA"."FORMULARY" ("FORMULARY_NUM") ENABLE,
	 CONSTRAINT "FK_PRODUCT_13" FOREIGN KEY ("PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT" ("PRODUCT_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRODUCT_FORMULARY" ON "TREXONE_DATA"."PRODUCT_FORMULARY" ("PRODUCT_FORMULARY_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRODUCT_FORMULARY" ADD CONSTRAINT "PK_PRODUCT_FORMULARY" PRIMARY KEY ("PRODUCT_FORMULARY_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRODUCT_FORMULARY"  ENABLE;
-- ==========================================
