-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRODUCT_INGREDIENT_PRICE"
   (	"PRODUCT_INGREDIENT_PRICE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRICE_CALC_RESULT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRODUCT_INGREDIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"AMOUNT" NUMBER(17,6),
	"BASIS_OF_COST" CHAR(2),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"DISPENSED_QTY" NUMBER(13,3),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PRODUCT_INGREDIENT_02" FOREIGN KEY ("PRODUCT_INGREDIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT_INGREDIENT" ("PRODUCT_INGREDIENT_NUM") ENABLE,
	 CONSTRAINT "FK_PRICE_CALC_RESULT_03" FOREIGN KEY ("PRICE_CALC_RESULT_NUM")
	  REFERENCES "TREXONE_DATA"."PRICE_CALC_RESULT" ("PRICE_CALC_RESULT_NUM") ENABLE NOVALIDATE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRODUCT_INGREDIENT_PRICE" ON "TREXONE_DATA"."PRODUCT_INGREDIENT_PRICE" ("PRODUCT_INGREDIENT_PRICE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRODUCT_INGREDIENT_PRICE" ADD CONSTRAINT "PK_PRODUCT_INGREDIENT_PRICE" PRIMARY KEY ("PRODUCT_INGREDIENT_PRICE_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRODUCT_INGREDIENT_PRICE"  ENABLE;
-- ==========================================
