-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRODUCT_MESSAGE_STATE"
   (	"PRODUCT_MESSAGE_STATE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRODUCT_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CTRY_CODE" VARCHAR2(8),
	"STATE_CODE" VARCHAR2(2),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PRODUCT_MESSAGE_01" FOREIGN KEY ("PRODUCT_MESSAGE_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT_MESSAGE" ("PRODUCT_MESSAGE_NUM") ENABLE,
	 CONSTRAINT "FK_STATE_04" FOREIGN KEY ("CTRY_CODE", "STATE_CODE")
	  REFERENCES "TREXONE_DATA"."STATE" ("CTRY_CODE", "STATE_CODE") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRODUCT_MESSAGE_STATE" ON "TREXONE_DATA"."PRODUCT_MESSAGE_STATE" ("PRODUCT_MESSAGE_STATE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRODUCT_MESSAGE_STATE" ADD CONSTRAINT "PK_PRODUCT_MESSAGE_STATE" PRIMARY KEY ("PRODUCT_MESSAGE_STATE_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRODUCT_MESSAGE_STATE"  ENABLE;
-- ==========================================
