-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRODUCT_ID_TYPE"
   (	"PRODUCT_ID_TYPE_CODE" CHAR(2) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(255),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRODUCT_ID_TYPE" ON "TREXONE_DATA"."PRODUCT_ID_TYPE" ("PRODUCT_ID_TYPE_CODE")
  ;
ALTER TABLE "TREXONE_DATA"."PRODUCT_ID_TYPE" ADD CONSTRAINT "PK_PRODUCT_ID_TYPE" PRIMARY KEY ("PRODUCT_ID_TYPE_CODE")
  USING INDEX "TREXONE_DATA"."PK_PRODUCT_ID_TYPE"  ENABLE;
-- ==========================================
