-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRODUCT_INCLD_PLBLR_NAME"
   (	"PRODUCT_INCLD_PLBLR_NAME_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PLBLR_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DATA_GROUP_10" FOREIGN KEY ("DATA_GROUP")
	  REFERENCES "TREXONE_DATA"."DATA_GROUP" ("DATA_GROUP") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PRODUCT_INCLD_PLBLR_NAME" ON "TREXONE_DATA"."PRODUCT_INCLD_PLBLR_NAME" ("PRODUCT_INCLD_PLBLR_NAME_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRODUCT_INCLD_PLBLR_NAME" ADD CONSTRAINT "PK_PRODUCT_INCLD_PLBLR_NAME" PRIMARY KEY ("PRODUCT_INCLD_PLBLR_NAME_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRODUCT_INCLD_PLBLR_NAME"  ENABLE;
-- ==========================================
