-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PRODUCT_CHARACTERISTICS"
   (	"PRODUCT_CHARACTERISTICS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRODUCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"IMAGE_SOURCE_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"IS_DEFAULT" CHAR(1) DEFAULT 'N' NOT NULL ENABLE,
	"ORIGINAL_EFFECTIVE_DATE" DATE,
	"ORIGINAL_EXPIRATION_DATE" DATE,
	"EFFECTIVE_DATE" DATE,
	"EXPIRATION_DATE" DATE,
	"FLAVOR_CODE" VARCHAR2(30),
	"COLOR_CODE" VARCHAR2(25),
	"SHAPE_CODE" VARCHAR2(30),
	"IMPRINT1" VARCHAR2(45),
	"IMPRINT2" VARCHAR2(45),
	"MARKS_CODE" VARCHAR2(25),
	"IMAGE_NUM" NUMBER(18,0),
	"ORIGINAL_MANUFACTURER" VARCHAR2(30),
	"MANUFACTURER" VARCHAR2(30),
	"REPACKAGER_CODE" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"CLARITY_CODE" VARCHAR2(30),
	"COATING_CODE" VARCHAR2(30),
	 CONSTRAINT "YES_NO_RULE3761" CHECK (is_default IN ('N', 'Y')) ENABLE,
	 CONSTRAINT "POSITIVE_RULE76" CHECK (num_updates >= 0) ENABLE,
	 CONSTRAINT "FK_PRODUCT_01" FOREIGN KEY ("PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT" ("PRODUCT_NUM") ENABLE,
	 CONSTRAINT "FK_KEEP_IMAGE_04" FOREIGN KEY ("IMAGE_NUM")
	  REFERENCES "TREXONE_DATA"."KEEP_IMAGE" ("IMAGE_NUM") ENABLE
   ) ;
  CREATE INDEX "TREXONE_DATA"."PK_PRODUCT_CHARACTERISTICS" ON "TREXONE_DATA"."PRODUCT_CHARACTERISTICS" ("PRODUCT_CHARACTERISTICS_NUM", "PRODUCT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PRODUCT_CHARACTERISTICS" ADD CONSTRAINT "PK_PRODUCT_CHARACTERISTICS" PRIMARY KEY ("PRODUCT_CHARACTERISTICS_NUM", "PRODUCT_NUM")
  USING INDEX "TREXONE_DATA"."PK_PRODUCT_CHARACTERISTICS"  ENABLE;
-- ==========================================
