-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PROF_SERVICE_CODE"
   (	"PROF_SERVICE_CODE" CHAR(2) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(45) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PROF_SERVICE_CODE" ON "TREXONE_DATA"."PROF_SERVICE_CODE" ("PROF_SERVICE_CODE")
  ;
ALTER TABLE "TREXONE_DATA"."PROF_SERVICE_CODE" ADD CONSTRAINT "PK_PROF_SERVICE_CODE" PRIMARY KEY ("PROF_SERVICE_CODE")
  USING INDEX "TREXONE_DATA"."PK_PROF_SERVICE_CODE"  ENABLE;
-- ==========================================
