-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PSCBR_DATA_OWNER_CONFIG"
   (	"PSCBR_DATA_OWNER_CONFIG_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DATA_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"DATA_ID" NUMBER(9,0) NOT NULL ENABLE,
	"OWNERSHIP_FLAG" CHAR(1) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"DISPLAY_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PSCBR_DATA_OWNER_CONFIG" ON "TREXONE_DATA"."PSCBR_DATA_OWNER_CONFIG" ("PSCBR_DATA_OWNER_CONFIG_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PSCBR_DATA_OWNER_CONFIG" ADD CONSTRAINT "PK_PSCBR_DATA_OWNER_CONFIG" PRIMARY KEY ("PSCBR_DATA_OWNER_CONFIG_NUM")
  USING INDEX "TREXONE_DATA"."PK_PSCBR_DATA_OWNER_CONFIG"  ENABLE;
-- ==========================================
