-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PURCHASING_PLAN"
   (	"PURCHASING_PLAN_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(50) NOT NULL ENABLE,
	"IS_ACTIVE" CHAR(1) NOT NULL ENABLE,
	"IS_DEFAULT_PLAN" CHAR(1) NOT NULL ENABLE,
	"PURCHASING_METHOD_CODE" CHAR(1) NOT NULL ENABLE,
	"MINIMUM_QTY" NUMBER(12,3),
	"MAXIMUM_QTY" NUMBER(12,3),
	"MIN_DAYS_SUPPLY" NUMBER(9,0),
	"MAX_DAYS_SUPPLY" NUMBER(9,0),
	"ORDER_QTY_ROUNDING_METHOD_CODE" CHAR(1),
	"NUMBER_DAYS_IN_BASE_PERIOD" NUMBER(3,0),
	"PERIOD_END_NUM_DAYS_AGO" NUMBER(3,0),
	"PERIOD_END_DATE" DATE,
	"PERCENTAGE_LEAD_TIME_DEMAND" NUMBER(3,0),
	"NEGATIVE_TOLERANCE_LEVEL_PCT" NUMBER(3,0),
	"POSITIVE_TOLERANCE_LEVEL_PCT" NUMBER(3,0),
	"EVAL_DEMAND_ADJUSTMENT_PCT" NUMBER(3,0),
	"EVAL_NUM_DAYS_IN_BASE_PERIOD" NUMBER(3,0),
	"EVAL_PERIOD_END_NUM_DAYS_AGO" NUMBER(3,0),
	"EVAL_PERIOD_END_DATE" DATE,
	"EVAL_LIFETIME_NUM_DAYS" NUMBER(3,0),
	"EVAL_ROUNDING_METHOD_CODE" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_FACILITY_76" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PURCHASING_PLAN" ON "TREXONE_DATA"."PURCHASING_PLAN" ("PURCHASING_PLAN_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PURCHASING_PLAN" ADD CONSTRAINT "PK_PURCHASING_PLAN" PRIMARY KEY ("PURCHASING_PLAN_NUM")
  USING INDEX "TREXONE_DATA"."PK_PURCHASING_PLAN"  ENABLE;
-- ==========================================
