-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PURCHASE_ORDER_ITEM"
   (	"PURCHASE_ORDER_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PURCHASE_ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ORDERED_VENDOR_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SUBSTITUTED_VENDOR_ITEM_NUM" NUMBER(18,0),
	"CREATE_DATE" DATE,
	"RECEIVED_DATE" DATE,
	"ORDERED_QUANTITY" NUMBER(9,0) NOT NULL ENABLE,
	"RECEIVED_QUANTITY" NUMBER(9,0),
	"EXPECTED_ACQ_COST" NUMBER(17,6),
	"ACTUAL_ACQ_COST" NUMBER(17,6),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"LINE_NUMBER" NUMBER(9,0) NOT NULL ENABLE,
	"RCVNG_EXCPTN_STATUS_CODE" CHAR(1),
	"MODIFIED_AFTER_ORDERED" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"IS_SUBSTITUTION_ALLOWED" CHAR(1),
	"DSCSA_QUANTITY" NUMBER(9,0),
	 CONSTRAINT "FK_PURCHASE_ORDER_01" FOREIGN KEY ("PURCHASE_ORDER_NUM")
	  REFERENCES "TREXONE_DATA"."PURCHASE_ORDER" ("PURCHASE_ORDER_NUM") ENABLE,
	 CONSTRAINT "FK_VENDOR_ITEM_01" FOREIGN KEY ("ORDERED_VENDOR_ITEM_NUM")
	  REFERENCES "TREXONE_DATA"."VENDOR_ITEM" ("VENDOR_ITEM_NUM") ENABLE,
	 CONSTRAINT "FK_VENDOR_ITEM_02" FOREIGN KEY ("SUBSTITUTED_VENDOR_ITEM_NUM")
	  REFERENCES "TREXONE_DATA"."VENDOR_ITEM" ("VENDOR_ITEM_NUM") ENABLE,
	 CONSTRAINT "FK_FACILITY_98" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE NOVALIDATE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PURCHASE_ORDER_ITEM" ON "TREXONE_DATA"."PURCHASE_ORDER_ITEM" ("PURCHASE_ORDER_ITEM_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PURCHASE_ORDER_ITEM" ADD CONSTRAINT "PK_PURCHASE_ORDER_ITEM" PRIMARY KEY ("PURCHASE_ORDER_ITEM_NUM")
  USING INDEX "TREXONE_DATA"."PK_PURCHASE_ORDER_ITEM"  ENABLE;
-- ==========================================
