-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PURCHASE_ORDER"
   (	"PURCHASE_ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"VENDOR_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PO_NUMBER" VARCHAR2(10) NOT NULL ENABLE,
	"CREATE_DATE" DATE NOT NULL ENABLE,
	"CREATE_USER" NUMBER(18,0),
	"EXPIRATION_DATE" DATE NOT NULL ENABLE,
	"PURCHASE_ORDER_TYPE_CODE" CHAR(1) NOT NULL ENABLE,
	"STATUS_CODE" CHAR(1) NOT NULL ENABLE,
	"RECEIVED_DATE" DATE,
	"IS_SCHEDULE_2_ORDER" CHAR(1) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"MCK_CONNECT_PO_STATUS" CHAR(1),
	"EXTERNAL_REFERENCE_ID" VARCHAR2(100),
	"SUPPLIER_PO_NUMBER" VARCHAR2(22),
	"ADDITIONAL_PO_NUMBERS" VARCHAR2(255),
	 CONSTRAINT "FK_FACILITY_78" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_VENDOR_16" FOREIGN KEY ("VENDOR_NUM")
	  REFERENCES "TREXONE_DATA"."VENDOR" ("VENDOR_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_PURCHASE_ORDER" ON "TREXONE_DATA"."PURCHASE_ORDER" ("PURCHASE_ORDER_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."PURCHASE_ORDER" ADD CONSTRAINT "PK_PURCHASE_ORDER" PRIMARY KEY ("PURCHASE_ORDER_NUM")
  USING INDEX "TREXONE_DATA"."PK_PURCHASE_ORDER"  ENABLE;
-- ==========================================
