-- ==========================================

  CREATE TABLE "TREXONE_DATA"."PURGE_STATUS"
   (	"JOB_NAME" VARCHAR2(50),
	"TABLE_NAME" VARCHAR2(30),
	"STEP" NUMBER(2,0),
	"STATUS" CHAR(1),
	"TABLE_TABLESPACE" VARCHAR2(30),
	"PK_INDEX_NAME" VARCHAR2(30),
	"PK_INDEX_DDL" CLOB,
	"MESSAGE" VARCHAR2(200),
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_PURGE_STATUS" PRIMARY KEY ("JOB_NAME", "TABLE_NAME")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
