-- ==========================================

  CREATE TABLE "TREXONE_DATA"."QUESTION_RESPONSE"
   (	"QUESTION_RESPONSE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"QUESTION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PATIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RESPONSE_CODE" CHAR(1) NOT NULL ENABLE,
	"RESPONSE_DATE" DATE NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"COMMENT_TEXT" VARCHAR2(255),
	"IMAGE_NUM" NUMBER(18,0),
	"EXPIRE_DATE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_FACILITY_43" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_IMAGE_10" FOREIGN KEY ("IMAGE_NUM")
	  REFERENCES "TREXONE_DATA"."IMAGE" ("IMAGE_NUM") ENABLE,
	 CONSTRAINT "FK_PATIENT_14" FOREIGN KEY ("PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE,
	 CONSTRAINT "FK_QUESTION_01" FOREIGN KEY ("QUESTION_NUM")
	  REFERENCES "TREXONE_DATA"."QUESTION" ("QUESTION_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_QUESTION_RESPONSE" ON "TREXONE_DATA"."QUESTION_RESPONSE" ("QUESTION_RESPONSE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."QUESTION_RESPONSE" ADD CONSTRAINT "PK_QUESTION_RESPONSE" PRIMARY KEY ("QUESTION_RESPONSE_NUM")
  USING INDEX "TREXONE_DATA"."PK_QUESTION_RESPONSE"  ENABLE;
-- ==========================================
