-- ==========================================

  CREATE TABLE "TREXONE_DATA"."RELATION_TO_PATIENT_TYPE"
   (	"RELATION_TO_PATIENT_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ASAP_RELATIONSHIP_CODE" VARCHAR2(2),
	"DESCRIPTION" VARCHAR2(25) NOT NULL ENABLE,
	"IS_DEFAULT" CHAR(1) NOT NULL ENABLE,
	"DISPLAY_ORDER" NUMBER(3,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."UC_RELATION_TO_PATIENT_TYPE" ON "TREXONE_DATA"."RELATION_TO_PATIENT_TYPE" ("ASAP_RELATIONSHIP_CODE", "ERX_CLIENT_ID")
  ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_RELATION_TO_PATIENT_TYPE" ON "TREXONE_DATA"."RELATION_TO_PATIENT_TYPE" ("RELATION_TO_PATIENT_TYPE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."RELATION_TO_PATIENT_TYPE" ADD CONSTRAINT "PK_RELATION_TO_PATIENT_TYPE" PRIMARY KEY ("RELATION_TO_PATIENT_TYPE_NUM")
  USING INDEX "TREXONE_DATA"."PK_RELATION_TO_PATIENT_TYPE"  ENABLE;
ALTER TABLE "TREXONE_DATA"."RELATION_TO_PATIENT_TYPE" ADD CONSTRAINT "UC_RELATION_TO_PATIENT_TYPE" UNIQUE ("ASAP_RELATIONSHIP_CODE", "ERX_CLIENT_ID")
  USING INDEX "TREXONE_DATA"."UC_RELATION_TO_PATIENT_TYPE"  ENABLE;
-- ==========================================
