-- ==========================================

  CREATE TABLE "TREXONE_DATA"."RESHIPMENT"
   (	"RESHIPMENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ITEM_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"REASON_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SUBREASON_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RESHIPMENT_COMMENT" VARCHAR2(500),
	"RESHIPMENT_QUANTITY" NUMBER(16,8),
	"ADS_STATUS" CHAR(1) NOT NULL ENABLE,
	"CANCEL_CODE" VARCHAR2(10),
	"REJECT_CODE" VARCHAR2(10),
	"EXCEPTION_TEXT" VARCHAR2(500),
	"REQUEST_SUBMITTED_DATE" DATE,
	"RESPONSE_RECEIVED_DATE" DATE,
	"RPH_FIRST_NAME" VARCHAR2(50),
	"RPH_LAST_NAME" VARCHAR2(50),
	"RPH_NPI_NUMBER" VARCHAR2(20),
	"RPH_STATE_LICENSE_NUMBER" VARCHAR2(20),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"PARTITION_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"ACTUAL_SHIPPING_METHOD" VARCHAR2(100),
	"ACTUAL_COURIER" VARCHAR2(50),
	"ACTUAL_SHIP_CHARGE" NUMBER(12,2),
	"ACTUAL_SHIP_DATE" DATE,
	 CONSTRAINT "PK_RESHIPMENT" PRIMARY KEY ("RESHIPMENT_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_104" FOREIGN KEY ("SYS_USER")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_ITEM_22" FOREIGN KEY ("ORDER_NUM", "ITEM_SEQ")
	  REFERENCES "TREXONE_DATA"."ITEM" ("ORDER_NUM", "ITEM_SEQ") ENABLE NOVALIDATE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTOYMINTERVAL(3,'MONTH')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
