-- ==========================================

  CREATE TABLE "TREXONE_DATA"."RETAIL_STAGING_BIN"
   (	"STAGING_BIN_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(30),
	"DESCRIPTION" VARCHAR2(255),
	"CAPACITY" NUMBER(18,0),
	"NUM_OF_PACKAGES" NUMBER(18,0),
	"IS_AVAILABLE" CHAR(1) NOT NULL ENABLE,
	"START_ALPHA" VARCHAR2(8),
	"END_ALPHA" VARCHAR2(8),
	"IDENTIFIER" VARCHAR2(255),
	"IS_EXCLUSIVE" CHAR(1),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"STAGING_BIN_TYPE_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_FACILITY_44" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_RETAIL_STAGING_BIN_TYPE_02" FOREIGN KEY ("STAGING_BIN_TYPE_NUM", "FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."RETAIL_STAGING_BIN_TYPE" ("STAGING_BIN_TYPE_NUM", "FACILITY_NUM") ENABLE
   ) ;
  CREATE INDEX "TREXONE_DATA"."PK_RETAIL_STAGING_BIN" ON "TREXONE_DATA"."RETAIL_STAGING_BIN" ("STAGING_BIN_NUM", "FACILITY_NUM", "NAME")
  ;
ALTER TABLE "TREXONE_DATA"."RETAIL_STAGING_BIN" ADD CONSTRAINT "PK_RETAIL_STAGING_BIN" PRIMARY KEY ("STAGING_BIN_NUM", "FACILITY_NUM")
  USING INDEX "TREXONE_DATA"."PK_RETAIL_STAGING_BIN"  ENABLE;
-- ==========================================
