-- ==========================================

  CREATE TABLE "TREXONE_DATA"."RETAIL_STAGING_BIN_TYPE"
   (	"STAGING_BIN_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(30) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(255),
	"PRIORITY" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"IS_DEFAULT" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_FACILITY_45" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_RETAIL_STAGING_BIN_TYPE" ON "TREXONE_DATA"."RETAIL_STAGING_BIN_TYPE" ("STAGING_BIN_TYPE_NUM", "FACILITY_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."RETAIL_STAGING_BIN_TYPE" ADD CONSTRAINT "PK_RETAIL_STAGING_BIN_TYPE" PRIMARY KEY ("STAGING_BIN_TYPE_NUM", "FACILITY_NUM")
  USING INDEX "TREXONE_DATA"."PK_RETAIL_STAGING_BIN_TYPE"  ENABLE;
-- ==========================================
