-- ==========================================

  CREATE TABLE "TREXONE_DATA"."RETURN_REASON"
   (	"RETURN_REASON_TYPE" CHAR(1) NOT NULL ENABLE,
	"NAME" VARCHAR2(30) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(255),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_RETURN_REASON" ON "TREXONE_DATA"."RETURN_REASON" ("RETURN_REASON_TYPE")
  ;
ALTER TABLE "TREXONE_DATA"."RETURN_REASON" ADD CONSTRAINT "PK_RETURN_REASON" PRIMARY KEY ("RETURN_REASON_TYPE")
  USING INDEX "TREXONE_DATA"."PK_RETURN_REASON"  ENABLE;
-- ==========================================
