-- ==========================================

  CREATE TABLE "TREXONE_DATA"."RIGHT"
   (	"RIGHT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(40) NOT NULL ENABLE,
	"GROUP_NUM" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_RIGHT" ON "TREXONE_DATA"."RIGHT" ("RIGHT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."RIGHT" ADD CONSTRAINT "PK_RIGHT" PRIMARY KEY ("RIGHT_NUM")
  USING INDEX "TREXONE_DATA"."PK_RIGHT"  ENABLE;
-- ==========================================
