-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ROLE_QUEUE_DEFINITION"
   (	"ROLE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"WF_QUEUE_DEFINITION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_ROLE_01" FOREIGN KEY ("ROLE_NUM")
	  REFERENCES "TREXONE_DATA"."ROLE" ("ROLE_NUM") ENABLE,
	 CONSTRAINT "FK_WF_QUEUE_DEFINITION_02" FOREIGN KEY ("WF_QUEUE_DEFINITION_NUM")
	  REFERENCES "TREXONE_DATA"."WF_QUEUE_DEFINITION" ("WF_QUEUE_DEFINITION_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_ROLE_QUEUE_DEFINITION" ON "TREXONE_DATA"."ROLE_QUEUE_DEFINITION" ("ROLE_NUM", "WF_QUEUE_DEFINITION_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."ROLE_QUEUE_DEFINITION" ADD CONSTRAINT "PK_ROLE_QUEUE_DEFINITION" PRIMARY KEY ("ROLE_NUM", "WF_QUEUE_DEFINITION_NUM")
  USING INDEX "TREXONE_DATA"."PK_ROLE_QUEUE_DEFINITION"  ENABLE;
-- ==========================================
