-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ROLE"
   (	"ROLE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(30),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_ROLE" ON "TREXONE_DATA"."ROLE" ("ROLE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."ROLE" ADD CONSTRAINT "PK_ROLE" PRIMARY KEY ("ROLE_NUM")
  USING INDEX "TREXONE_DATA"."PK_ROLE"  ENABLE;
-- ==========================================
