-- ==========================================

  CREATE TABLE "TREXONE_DATA"."RX_AND_FILL_HOA_AUDIT"
   (	"RX_FILL_HOA_AUDIT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_FILL_SEQ" NUMBER(18,0),
	"CURRENT_VALUE" VARCHAR2(4000),
	"PREVIOUS_VALUE" VARCHAR2(4000),
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	"FIELD" VARCHAR2(30),
	 CONSTRAINT "PK_RX_AND_FILL_HOA_AUDIT" PRIMARY KEY ("RX_FILL_HOA_AUDIT_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
