-- ==========================================

  CREATE TABLE "TREXONE_DATA"."RX_FILL_DUR_CONFLICT"
   (	"RX_FILL_DUR_CONFLICT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_FILL_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RESPONSE_RECEIVED_TIME" DATE,
	"REQUEST_MADE_TIME" DATE,
	"ACKNOWLEDGING_USER_NUM" NUMBER(18,0),
	"COMMENTS_USER_DESC" VARCHAR2(255),
	"RESULT_USER_DESC" VARCHAR2(255),
	"CONSULTED_USER_DESC" VARCHAR2(255),
	"PROBLEM_USER_DESC" VARCHAR2(255),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"IS_INT_DUR_WITH_CLAIM" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"REPEATED_DUR_UNCHANGED" CHAR(1),
	 CONSTRAINT "FK_RX_FILL_09" FOREIGN KEY ("RX_FILL_SEQ", "RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_FILL" ("RX_FILL_SEQ", "RX_RECORD_NUM") ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_16" FOREIGN KEY ("ACKNOWLEDGING_USER_NUM")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_RX_FILL_DUR_CONFLICT" ON "TREXONE_DATA"."RX_FILL_DUR_CONFLICT" ("RX_FILL_DUR_CONFLICT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."RX_FILL_DUR_CONFLICT" ADD CONSTRAINT "PK_RX_FILL_DUR_CONFLICT" PRIMARY KEY ("RX_FILL_DUR_CONFLICT_NUM")
  USING INDEX "TREXONE_DATA"."PK_RX_FILL_DUR_CONFLICT"  ENABLE;
-- ==========================================
