-- ==========================================

  CREATE TABLE "TREXONE_DATA"."RX_FILL_INGREDIENT_INFO"
   (	"RX_FILL_ING_INFO_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_FILL_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRODUCT_INGREDIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"INGREDIENT_LOT_NUMBER" VARCHAR2(20),
	"INGREDIENT_EXPIRATION_DATE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_RX_FILL_INGREDIENT_INFO" PRIMARY KEY ("RX_FILL_ING_INFO_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_RX_FILL_20" FOREIGN KEY ("RX_FILL_SEQ", "RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_FILL" ("RX_FILL_SEQ", "RX_RECORD_NUM") ENABLE,
	 CONSTRAINT "FK_PRODUCT_INGREDIENT_04" FOREIGN KEY ("PRODUCT_INGREDIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT_INGREDIENT" ("PRODUCT_INGREDIENT_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
