-- ==========================================

  CREATE TABLE "TREXONE_DATA"."RX_HOLD_DETAIL"
   (	"RX_HOLD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_FILL_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"CPS_MESSAGE_NUM" NUMBER(18,0),
	"ASSIGNEE" VARCHAR2(100),
	"DUE_DATE" DATE,
	"GLOBAL_FILL_SEQ_ID" VARCHAR2(100),
	"SENT_EPOCH" NUMBER(10,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" VARCHAR2(100) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"WORKFLOW_STEP_NAME" VARCHAR2(50),
	"WORKFLOW_STEP_SEQ" NUMBER(3,0),
	"DUE_DATE_TIME" DATE,
	 CONSTRAINT "PK_RX_HOLD_DETAIL" PRIMARY KEY ("RX_HOLD_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_RX_FILL_23" FOREIGN KEY ("RX_FILL_SEQ", "RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_FILL" ("RX_FILL_SEQ", "RX_RECORD_NUM") ENABLE
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTOYMINTERVAL(3,'MONTH')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
