-- ==========================================

  CREATE TABLE "TREXONE_DATA"."RX_ORIGINATION"
   (	"RX_ORIGINATION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(30) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE INDEX "TREXONE_DATA"."PK_RX_ORIGINATION" ON "TREXONE_DATA"."RX_ORIGINATION" ("RX_ORIGINATION_NUM", "DESCRIPTION")
  ;
ALTER TABLE "TREXONE_DATA"."RX_ORIGINATION" ADD CONSTRAINT "PK_RX_ORIGINATION" PRIMARY KEY ("RX_ORIGINATION_NUM")
  USING INDEX "TREXONE_DATA"."PK_RX_ORIGINATION"  ENABLE;
-- ==========================================
