-- ==========================================

  CREATE TABLE "TREXONE_DATA"."RX_PURGE_OPTION"
   (	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"ACTIVE_RX_LIFE" NUMBER(5,0) NOT NULL ENABLE,
	"INACTIVE_RX_LIFE" NUMBER(5,0) NOT NULL ENABLE,
	"TRANSFERRED_RX_LIFE" NUMBER(5,0) NOT NULL ENABLE,
	"RX_REFILL_LIFE" NUMBER(5,0) NOT NULL ENABLE,
	"PROFILED_RX_LIFE" NUMBER(5,0) NOT NULL ENABLE,
	"DENIED_RX_LIFE" NUMBER(5,0) NOT NULL ENABLE,
	"CANCELLED_RX_LIFE" NUMBER(5,0) NOT NULL ENABLE,
	"DUR_BUFFER" NUMBER(5,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DATA_GROUP_15" FOREIGN KEY ("DATA_GROUP")
	  REFERENCES "TREXONE_DATA"."DATA_GROUP" ("DATA_GROUP") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_RX_PURGE_OPTION" ON "TREXONE_DATA"."RX_PURGE_OPTION" ("DATA_GROUP")
  ;
ALTER TABLE "TREXONE_DATA"."RX_PURGE_OPTION" ADD CONSTRAINT "PK_RX_PURGE_OPTION" PRIMARY KEY ("DATA_GROUP")
  USING INDEX "TREXONE_DATA"."PK_RX_PURGE_OPTION"  ENABLE;
-- ==========================================
