-- ==========================================

  CREATE TABLE "TREXONE_DATA"."RX_PURGE_LOG"
   (	"PURGE_LOG_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PURGE_DATE" DATE NOT NULL ENABLE,
	"ACTIVE_RX_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"INACTIVE_RX_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"TRANSFERRED_RX_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"DUR_RX_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"PROFILED_RX_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"IN_PROFILED_RX_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"IN_DUR_RX_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"DENIED_RX_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"CANCELLED_RX_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"ERROR_RX_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"TOTAL_RX_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_RX_PURGE_LOG" ON "TREXONE_DATA"."RX_PURGE_LOG" ("PURGE_LOG_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."RX_PURGE_LOG" ADD CONSTRAINT "PK_RX_PURGE_LOG" PRIMARY KEY ("PURGE_LOG_NUM")
  USING INDEX "TREXONE_DATA"."PK_RX_PURGE_LOG"  ENABLE;
-- ==========================================
