-- ==========================================

  CREATE TABLE "TREXONE_DATA"."RX_PENDING_TRANSFER"
   (	"RX_PENDING_TRANSFER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"COMPETITOR_NUM" NUMBER(18,0),
	"STATUS" CHAR(1) DEFAULT 'A',
	"FACILITY_NAME" VARCHAR2(255),
	"COMPETITOR_GROUP_NAME" VARCHAR2(255),
	"FACILITY_ADDRESS1" VARCHAR2(100),
	"FACILITY_ADDRESS2" VARCHAR2(100),
	"FACILITY_CITY" VARCHAR2(100),
	"FACILITY_STATE_CODE" VARCHAR2(2),
	"FACILITY_POSTAL" VARCHAR2(10),
	"FACILITY_CTRY_CODE" VARCHAR2(8),
	"FACILITY_AREA_CODE" VARCHAR2(3),
	"FACILITY_PHONE_EXCHANGE" VARCHAR2(4),
	"FACILITY_PHONE_NUMBER" VARCHAR2(7),
	"FACILITY_PHONE_EXTENSION" VARCHAR2(5),
	"FACILITY_DEA_NUM" VARCHAR2(30),
	"RECEIVING_PHARMACIST" VARCHAR2(100),
	"TRANSFER_TYPE" CHAR(1),
	"TRANSFER_METHOD" VARCHAR2(12),
	"COMPETITOR_PRICE" NUMBER(17,6),
	"RECEIVING_PHARMACIST_LIC_NUM" VARCHAR2(20),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	"FAX_AREA_CODE" VARCHAR2(10),
	"FAX_EXCHANGE" VARCHAR2(10),
	"FAX_NUMBER" VARCHAR2(15),
	"FAX_EXTENSION" VARCHAR2(10),
	"COMMENTS" VARCHAR2(4000),
	 CONSTRAINT "RX_PENDING_TRANSFER_PK" PRIMARY KEY ("RX_PENDING_TRANSFER_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_RX_RECORD_NUM" FOREIGN KEY ("RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_BASE" ("RX_RECORD_NUM") ENABLE,
	 CONSTRAINT "FK_COMPETITOR_NUM" FOREIGN KEY ("COMPETITOR_NUM")
	  REFERENCES "TREXONE_DATA"."COMPETITOR" ("COMPETITOR_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTOYMINTERVAL(3,'MONTH')) STORE IN ("LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
