-- ==========================================

  CREATE TABLE "TREXONE_DATA"."RX_REMS"
   (	"RX_REM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_FILL_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRODUCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"AUTHORIZATION_ID" VARCHAR2(20),
	"AUTHORIZATION_ID_DATE" DATE,
	"DISPENSING_ID" VARCHAR2(20),
	"DISPENSING_ID_DATE" DATE,
	"CANCEL_ID" VARCHAR2(20),
	"CANCEL_ID_DATE" DATE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "RX_REMS_PK" PRIMARY KEY ("RX_REM_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "RX_REMS_FK01" FOREIGN KEY ("RX_FILL_SEQ", "RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_FILL" ("RX_FILL_SEQ", "RX_RECORD_NUM") ENABLE,
	 CONSTRAINT "RX_REMS_FK02" FOREIGN KEY ("PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT" ("PRODUCT_NUM") ENABLE
   ) ;
-- ==========================================
