-- ==========================================

  CREATE TABLE "TREXONE_DATA"."RX_STATUS_REASON"
   (	"RX_STATUS_REASON_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(45) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_RX_STATUS_REASON" ON "TREXONE_DATA"."RX_STATUS_REASON" ("RX_STATUS_REASON_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."RX_STATUS_REASON" ADD CONSTRAINT "PK_RX_STATUS_REASON" PRIMARY KEY ("RX_STATUS_REASON_NUM")
  USING INDEX "TREXONE_DATA"."PK_RX_STATUS_REASON"  ENABLE;
-- ==========================================
