-- ==========================================

  CREATE TABLE "TREXONE_DATA"."RX_TRANSFER_HISTORY"
   (	"RX_TRANSFER_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"RX_HISTORY_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FILL_NUM" NUMBER(9,0),
	"PRODUCT_NDC" VARCHAR2(11),
	"QTY_DISPENSED" NUMBER(10,3),
	"FILL_DATE" DATE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_RX_TRANSFER_01" FOREIGN KEY ("RX_TRANSFER_SEQ", "RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_TRANSFER" ("RX_TRANSFER_SEQ", "RX_RECORD_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_RX_TRANSFER_HISTORY" ON "TREXONE_DATA"."RX_TRANSFER_HISTORY" ("RX_TRANSFER_SEQ", "RX_HISTORY_SEQ", "RX_RECORD_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."RX_TRANSFER_HISTORY" ADD CONSTRAINT "PK_RX_TRANSFER_HISTORY" PRIMARY KEY ("RX_TRANSFER_SEQ", "RX_HISTORY_SEQ", "RX_RECORD_NUM")
  USING INDEX "TREXONE_DATA"."PK_RX_TRANSFER_HISTORY"  ENABLE;
-- ==========================================
