-- ==========================================

  CREATE TABLE "TREXONE_DATA"."RX_TYPE"
   (	"RX_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_TYPE_DESC" VARCHAR2(30) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_RX_TYPE" PRIMARY KEY ("RX_TYPE_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
