-- ==========================================

  CREATE TABLE "TREXONE_DATA"."SCANNED_DOCUMENT_TYPE"
   (	"SCANNED_DOCUMENT_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(100) NOT NULL ENABLE,
	"ENABLED" CHAR(1) DEFAULT 'Y',
	"DEFAULT_VALUE" CHAR(1) DEFAULT 'N',
	"SYS_USER" NUMBER(18,0) DEFAULT 0 NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "SCANNED_DOCUMENT_TYPE_CHK01" CHECK (enabled in ('Y', 'N')) ENABLE,
	 CONSTRAINT "SCANNED_DOCUMENT_TYPE_CHK02" CHECK (default_value in ('Y', 'N')) ENABLE,
	 CONSTRAINT "SCANNED_DOCUMENT_TYPE_PK" PRIMARY KEY ("SCANNED_DOCUMENT_TYPE_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
