-- ==========================================

  CREATE TABLE "TREXONE_DATA"."SCHEDULE_DEFINITION"
   (	"SCHEDULE_DEFINITION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"OWNER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"OWNER_TYPE" CHAR(1) NOT NULL ENABLE,
	"USAGE" CHAR(1) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(100),
	"RECURRENCE" CHAR(1),
	"OCCURRENCE_DATE" DATE,
	"MONTH" NUMBER(2,0),
	"DAY" NUMBER(2,0),
	"DAY_OF_WEEK" NUMBER(1,0),
	"DAY_OF_WEEK_IN_MONTH" NUMBER(1,0),
	"IS_MONDAY" CHAR(1),
	"IS_TUESDAY" CHAR(1),
	"IS_WEDNESDAY" CHAR(1),
	"IS_THURSDAY" CHAR(1),
	"IS_FRIDAY" CHAR(1),
	"IS_SATURDAY" CHAR(1),
	"IS_SUNDAY" CHAR(1),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_SCHEDULE_DEFINITION" ON "TREXONE_DATA"."SCHEDULE_DEFINITION" ("SCHEDULE_DEFINITION_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."SCHEDULE_DEFINITION" ADD CONSTRAINT "PK_SCHEDULE_DEFINITION" PRIMARY KEY ("SCHEDULE_DEFINITION_NUM")
  USING INDEX "TREXONE_DATA"."PK_SCHEDULE_DEFINITION"  ENABLE;
-- ==========================================
