-- ==========================================

  CREATE TABLE "TREXONE_DATA"."SCHEDULE_LINK"
   (	"SCHEDULE_LINK_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"OWNER" NUMBER(18,0) NOT NULL ENABLE,
	"OWNER_TYPE_CODE" CHAR(1) NOT NULL ENABLE,
	"USAGE" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_OWNER_TYPE_03" FOREIGN KEY ("OWNER_TYPE_CODE")
	  REFERENCES "TREXONE_DATA"."OWNER_TYPE" ("OWNER_TYPE_CODE") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_SCHEDULE_LINK" ON "TREXONE_DATA"."SCHEDULE_LINK" ("SCHEDULE_LINK_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."SCHEDULE_LINK" ADD CONSTRAINT "PK_SCHEDULE_LINK" PRIMARY KEY ("SCHEDULE_LINK_NUM")
  USING INDEX "TREXONE_DATA"."PK_SCHEDULE_LINK"  ENABLE;
-- ==========================================
