-- ==========================================

  CREATE TABLE "TREXONE_DATA"."SECURITY_CERTIFICATE"
   (	"SECURITY_CERTIFICATE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CERTIFICATE" BLOB,
	"EXPIRY_DATE" DATE,
	"FILENAME" VARCHAR2(128),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0) NOT NULL ENABLE,
	"ISSUER_NAME" VARCHAR2(128),
	"ACTIVE_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_SECURITY_CERTIFICATE" ON "TREXONE_DATA"."SECURITY_CERTIFICATE" ("SECURITY_CERTIFICATE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."SECURITY_CERTIFICATE" ADD CONSTRAINT "PK_SECURITY_CERTIFICATE" PRIMARY KEY ("SECURITY_CERTIFICATE_NUM")
  USING INDEX "TREXONE_DATA"."PK_SECURITY_CERTIFICATE"  ENABLE;
-- ==========================================
