-- ==========================================

  CREATE TABLE "TREXONE_DATA"."SHIELD_DUR_RULE_CONDITION"
   (	"DUR_RULE_CONDITION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CODE_SET_NUM" NUMBER(18,0),
	"CONDITION_TYPE" NUMBER(9,0) NOT NULL ENABLE,
	"PROCESSING_ORDER" NUMBER(9,0) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(255),
	"TRANSACTION_TYPE" NUMBER(9,0) NOT NULL ENABLE,
	"INTERACTION_TYPE" NUMBER(9,0) NOT NULL ENABLE,
	"VALUE_1" VARCHAR2(45),
	"VALUE_2" VARCHAR2(45),
	"VALUE_3" VARCHAR2(45),
	"VALUE_4" VARCHAR2(45),
	"VALUE_5" VARCHAR2(45),
	"VALUE_6" VARCHAR2(45),
	"INTERNAL" CHAR(1) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	"SCREENING_RESULT_TYPE" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	 CONSTRAINT "PK_SHIELD_DUR_RULE_CONDITION" PRIMARY KEY ("DUR_RULE_CONDITION_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SHIELD_CODE_SET_03" FOREIGN KEY ("CODE_SET_NUM")
	  REFERENCES "TREXONE_DATA"."CODE_SET" ("CODE_SET_NUM") ENABLE
   ) ;
-- ==========================================
