-- ==========================================

  CREATE TABLE "TREXONE_DATA"."SHIPMENT"
   (	"SHIPMENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SHIPPING_METHOD_NUM" NUMBER(18,0),
	"SHIPPING_ADDRESS_NUM" NUMBER(18,0),
	"SHIPMENT_SIGNATURE_NUM" NUMBER(18,0),
	"EXPECTED_MAIL_DELIVERY_DATE" DATE,
	"SHIPPING_STATUS_NUM" NUMBER(18,0),
	"NUMBER_OF_PACKAGES" NUMBER(9,0) DEFAULT 1,
	"DEA_CLASS" CHAR(1),
	"REFRIGERATION" CHAR(1),
	"SHIP_HANDLE_FEE" NUMBER(17,6),
	"SHIP_DATE" DATE,
	"WEIGHT" NUMBER(16,8),
	"WEIGHT_UNITS" VARCHAR2(10),
	"DELIVERY_METHOD_NUM" NUMBER(18,0),
	"TRACKING_NUMBER" VARCHAR2(200),
	"SPECIAL_INSTRUCTIONS" VARCHAR2(300),
	"COURIER_SHIPPING_CHARGE" NUMBER(17,6),
	"COURIER_SHIPMENT_MESSAGE" VARCHAR2(100),
	"ORIGINAL_SHIP_DATE" DATE,
	"ORIGINAL_EXP_MAIL_DELIVERY_DT" DATE,
	"IS_SHIPPING_COMPLETE" CHAR(1),
	"PAYMENT_GROUP_NUM" NUMBER(18,0),
	"ORIGINAL_SHIPPING_METHOD_NUM" NUMBER(18,0),
	"ALTERNATE_RECIPIENT_NUM" NUMBER(18,0),
	"IS_SHIP_ADDR_CONFIRMED" CHAR(1),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"PREVIOUS_SHIP_HANDLE_FEE" NUMBER(17,6),
	"SHIP_HANDLE_FEE_EXEMPT_REASON" VARCHAR2(200),
	 CONSTRAINT "PK_SHIPMENT" PRIMARY KEY ("SHIPMENT_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SHIPPING_METHOD_02" FOREIGN KEY ("SHIPPING_METHOD_NUM")
	  REFERENCES "TREXONE_DATA"."SHIPPING_METHOD" ("SHIPPING_METHOD_NUM") ENABLE,
	 CONSTRAINT "FK_SHIPMENT_SIGNATURE_02" FOREIGN KEY ("SHIPMENT_SIGNATURE_NUM")
	  REFERENCES "TREXONE_DATA"."SHIPMENT_SIGNATURE" ("SHIPMENT_SIGNATURE_NUM") ENABLE,
	 CONSTRAINT "FK_DELIVERY_METHOD_05" FOREIGN KEY ("DELIVERY_METHOD_NUM")
	  REFERENCES "TREXONE_DATA"."DELIVERY_METHOD" ("DELIVERY_METHOD_NUM") ENABLE,
	 CONSTRAINT "FK_ORDER_RECORD_04" FOREIGN KEY ("ORDER_NUM")
	  REFERENCES "TREXONE_DATA"."ORDER_RECORD_BASE" ("ORDER_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_PAYMENT_GROUP_02" FOREIGN KEY ("PAYMENT_GROUP_NUM")
	  REFERENCES "TREXONE_DATA"."PAYMENT_GROUP" ("PAYMENT_GROUP_NUM") ENABLE,
	 CONSTRAINT "FK_SHIPPING_METHOD_04" FOREIGN KEY ("ORIGINAL_SHIPPING_METHOD_NUM")
	  REFERENCES "TREXONE_DATA"."SHIPPING_METHOD" ("SHIPPING_METHOD_NUM") ENABLE,
	 CONSTRAINT "FK_ALTERNATE_RECIPIENT_01" FOREIGN KEY ("ALTERNATE_RECIPIENT_NUM")
	  REFERENCES "TREXONE_DATA"."ALTERNATE_RECIPIENT" ("ALTERNATE_RECIPIENT_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
