-- ==========================================

  CREATE TABLE "TREXONE_DATA"."SHIPMENT_SIGNATURE"
   (	"SHIPMENT_SIGNATURE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(100) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	 CONSTRAINT "PK_SHIPMENT_SIGNATURE" PRIMARY KEY ("SHIPMENT_SIGNATURE_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
