-- ==========================================

  CREATE TABLE "TREXONE_DATA"."SHIPPING_PROCESSOR"
   (	"SHIPPING_PROCESSOR_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PROCESSOR_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_SHIPPING_PROCESSOR" PRIMARY KEY ("SHIPPING_PROCESSOR_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
