-- ==========================================

  CREATE TABLE "TREXONE_DATA"."SHIPPING_METHOD"
   (	"SHIPPING_METHOD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(100) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"METHOD_CODE" VARCHAR2(25),
	"IS_DEFAULT_COURIER_METHOD" CHAR(1),
	"SHIPPING_COST" NUMBER(17,6),
	"SHIPPING_COURIER_NUM" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	 CONSTRAINT "PK_SHIPPING_METHOD" PRIMARY KEY ("SHIPPING_METHOD_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SHIPPING_METHOD" FOREIGN KEY ("SHIPPING_COURIER_NUM")
	  REFERENCES "TREXONE_DATA"."SHIPPING_COURIER" ("SHIPPING_COURIER_NUM") ENABLE
   ) ;
-- ==========================================
