-- ==========================================

  CREATE TABLE "TREXONE_DATA"."SHIPPING_COURIER"
   (	"SHIPPING_COURIER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"COURIER_NAME" VARCHAR2(50) NOT NULL ENABLE,
	"IS_DEFAULT_COURIER" CHAR(1),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"SHIPPING_PROCESSOR_NUM" NUMBER(18,0),
	 CONSTRAINT "PK_SHIPPING_COURRIER" PRIMARY KEY ("SHIPPING_COURIER_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SHIPPING_PROCESSOR_01" FOREIGN KEY ("SHIPPING_PROCESSOR_NUM")
	  REFERENCES "TREXONE_DATA"."SHIPPING_PROCESSOR" ("SHIPPING_PROCESSOR_NUM") ENABLE
   ) ;
-- ==========================================
