-- ==========================================

  CREATE TABLE "TREXONE_DATA"."SIG_ELEMENT_CONVERSION"
   (	"SIG_ELEMENT_CONVERSION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ELEMENT_TYPE" VARCHAR2(10) NOT NULL ENABLE,
	"SOURCE_WORD" VARCHAR2(50) NOT NULL ENABLE,
	"CONVERTED_WORD" VARCHAR2(50) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_SIG_ELEMENT_CONVERSION" ON "TREXONE_DATA"."SIG_ELEMENT_CONVERSION" ("SIG_ELEMENT_CONVERSION_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."SIG_ELEMENT_CONVERSION" ADD CONSTRAINT "PK_SIG_ELEMENT_CONVERSION" PRIMARY KEY ("SIG_ELEMENT_CONVERSION_NUM")
  USING INDEX "TREXONE_DATA"."PK_SIG_ELEMENT_CONVERSION"  ENABLE;
-- ==========================================
