-- ==========================================

  CREATE TABLE "TREXONE_DATA"."SIG_LANGUAGE"
   (	"LANGUAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"VERB_ORDER" NUMBER(18,0),
	"QUANTITY_ORDER" NUMBER(18,0),
	"UNIT_ORDER" NUMBER(18,0),
	"ROUTE_ORDER" NUMBER(18,0),
	"FREQUENCY_ORDER" NUMBER(18,0),
	"INDICATION_ORDER" NUMBER(18,0),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_LANGUAGE_03" FOREIGN KEY ("LANGUAGE_NUM")
	  REFERENCES "TREXONE_DATA"."LANGUAGE" ("LANGUAGE_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_SIG_LANGUAGE" ON "TREXONE_DATA"."SIG_LANGUAGE" ("LANGUAGE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."SIG_LANGUAGE" ADD CONSTRAINT "PK_SIG_LANGUAGE" PRIMARY KEY ("LANGUAGE_NUM")
  USING INDEX "TREXONE_DATA"."PK_SIG_LANGUAGE"  ENABLE;
-- ==========================================
