-- ==========================================

  CREATE TABLE "TREXONE_DATA"."SLX_WORKSHEET_COUNT"
   (	"SLX_WORKSHEET_COUNT_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"WORKSHEET_COUNT" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	 CONSTRAINT "PK_SLX_WORKSHEET_COUNT" PRIMARY KEY ("SLX_WORKSHEET_COUNT_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_FACILITY_140" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_SYSTEM_USER_125" FOREIGN KEY ("SYS_USER")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE NOVALIDATE
   ) ;
-- ==========================================
