-- ==========================================

  CREATE TABLE "TREXONE_DATA"."SM_TRANS_RESPONSE"
   (	"SM_TRANS_RESPONSE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SM_TRANS_REQUEST_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SM_TRANS_SHIPPER_ID" VARCHAR2(30) NOT NULL ENABLE,
	"SM_TRANS_STATUS_CODE" VARCHAR2(20),
	"SM_TRANS_STATUS_MESSAGE" VARCHAR2(100),
	"SM_TRANS_SHIP_FIRST_NAME" VARCHAR2(30),
	"SM_TRANS_SHIP_MIDDLE_NAME" VARCHAR2(30),
	"SM_TRANS_SHIP_LAST_NAME" VARCHAR2(30),
	"SM_TRANS_SHIP_ADDRESS1" VARCHAR2(100),
	"SM_TRANS_SHIP_ADDRESS2" VARCHAR2(50),
	"SM_TRANS_SHIP_CITY" VARCHAR2(40),
	"SM_TRANS_SHIP_STATE_CODE" VARCHAR2(2),
	"SM_TRANS_SHIP_ZIP_CODE" VARCHAR2(20),
	"SM_TRANS_AREA_CODE" VARCHAR2(4),
	"SM_TRANS_PHONE_NUMBER" VARCHAR2(20),
	"SM_TRANS_SIGNATURE_REQUIRED" VARCHAR2(20),
	"SM_TRANS_EMAIL" VARCHAR2(100),
	"SM_TRANS_COURIER" VARCHAR2(50),
	"SM_TRANS_COURIER_SHIP_METHOD" VARCHAR2(45),
	"SM_TRANS_NUMBER_OF_PACKAGES" NUMBER(9,0),
	"SM_TRANS_SPECIAL_INSTRUCTIONS" VARCHAR2(300),
	"SM_TRANS_EXPECTED_DELIVERY_DT" DATE,
	"SM_TRANS_COURIER_INSTRUCTIONS" VARCHAR2(300),
	"SM_TRANS_DEA_CLASS" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_SM_TRANS_RESPONSE" PRIMARY KEY ("SM_TRANS_RESPONSE_NUM")
  USING INDEX  ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
