-- ==========================================

  CREATE TABLE "TREXONE_DATA"."SPECIALTY_PROGRAM_PRODUCT_LIST"
   (	"SPECIALTY_PROGRAM_TO_PRDCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SPECIALTY_PROGRAM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRODUCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "SPECIALTY_PROGRAM_PROD_LST_PK" PRIMARY KEY ("SPECIALTY_PROGRAM_TO_PRDCT_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "SPECIALTY_PRGRM_PRDCT_LST_FK02" FOREIGN KEY ("PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT" ("PRODUCT_NUM") ENABLE,
	 CONSTRAINT "SPECIALTY_PRGRM_PRDCT_LST_FK01" FOREIGN KEY ("SPECIALTY_PROGRAM_NUM")
	  REFERENCES "TREXONE_DATA"."SPECIALTY_PROGRAM" ("SPECIALTY_PROGRAM_NUM") ENABLE
   ) ;
-- ==========================================
