-- ==========================================

  CREATE TABLE "TREXONE_DATA"."SPECIALTY_ID_PARAM_TYPE"
   (	"SPECIALTY_ID_PARAM_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(40) NOT NULL ENABLE,
	"DISPLAY_NAME" VARCHAR2(40) NOT NULL ENABLE,
	"IS_SYSTEM" CHAR(1) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT','ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "SPECIALTY_ID_PARAM_TYPE_PK" PRIMARY KEY ("SPECIALTY_ID_PARAM_TYPE_NUM")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
