-- ==========================================

  CREATE TABLE "TREXONE_DATA"."SPONSOR"
   (	"SPONSOR_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(30) NOT NULL ENABLE,
	"IS_DELETEABLE" CHAR(1) NOT NULL ENABLE,
	"CREATE_USER" NUMBER(18,0) NOT NULL ENABLE,
	"CREATE_DATE" DATE NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_SPONSOR" ON "TREXONE_DATA"."SPONSOR" ("SPONSOR_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."SPONSOR" ADD CONSTRAINT "PK_SPONSOR" PRIMARY KEY ("SPONSOR_NUM")
  USING INDEX "TREXONE_DATA"."PK_SPONSOR"  ENABLE;
-- ==========================================
