-- ==========================================

  CREATE TABLE "TREXONE_DATA"."STATE"
   (	"CTRY_CODE" VARCHAR2(8) NOT NULL ENABLE,
	"STATE_CODE" VARCHAR2(2) NOT NULL ENABLE,
	"NAME" VARCHAR2(30) NOT NULL ENABLE,
	"ALLOW_RX_COUPONS" CHAR(1),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"AGE_OF_MAJORITY" NUMBER(2,0),
	"MINIMUM_AGE" NUMBER(2,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_COUNTRY_02" FOREIGN KEY ("CTRY_CODE")
	  REFERENCES "TREXONE_DATA"."COUNTRY" ("CTRY_CODE") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_STATE" ON "TREXONE_DATA"."STATE" ("CTRY_CODE", "STATE_CODE")
  ;
ALTER TABLE "TREXONE_DATA"."STATE" ADD CONSTRAINT "PK_STATE" PRIMARY KEY ("CTRY_CODE", "STATE_CODE")
  USING INDEX "TREXONE_DATA"."PK_STATE"  ENABLE;
-- ==========================================
