-- ==========================================

  CREATE TABLE "TREXONE_DATA"."STORAGE_LOCATION"
   (	"LOCATION_GROUP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"INVENTORY_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"IS_ACTIVE" CHAR(1) NOT NULL ENABLE,
	"CURRENT_QTY" NUMBER(16,8),
	"DISPENSING_NAME" VARCHAR2(30),
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_INVENTORY_ITEM_05" FOREIGN KEY ("INVENTORY_ITEM_NUM")
	  REFERENCES "TREXONE_DATA"."INVENTORY_ITEM" ("INVENTORY_ITEM_NUM") ENABLE,
	 CONSTRAINT "FK_LOCATION_GROUP_06" FOREIGN KEY ("LOCATION_GROUP_NUM")
	  REFERENCES "TREXONE_DATA"."LOCATION_GROUP" ("LOCATION_GROUP_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_STORAGE_LOCATION" ON "TREXONE_DATA"."STORAGE_LOCATION" ("LOCATION_GROUP_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."STORAGE_LOCATION" ADD CONSTRAINT "PK_STORAGE_LOCATION" PRIMARY KEY ("LOCATION_GROUP_NUM")
  USING INDEX "TREXONE_DATA"."PK_STORAGE_LOCATION"  ENABLE;
-- ==========================================
