-- ==========================================

  CREATE TABLE "TREXONE_DATA"."STORE_CLOSING"
   (	"STORE_CLOSING_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CLOSING_DATE" CHAR(8) NOT NULL ENABLE,
	"CLOSING_TIME" DATE NOT NULL ENABLE,
	"THIRD_PARTY_TOTAL" NUMBER(18,6) NOT NULL ENABLE,
	"CLOSING_METHOD" CHAR(1) NOT NULL ENABLE,
	"AUDIT_TOTAL" NUMBER(18,6),
	"AUDIT_TIME" DATE,
	"EXTRACT_TOTAL" NUMBER(18,6),
	"EXTRACT_TIME" DATE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_STORE_CLOSING_1" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_STORE_CLOSING" ON "TREXONE_DATA"."STORE_CLOSING" ("STORE_CLOSING_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."STORE_CLOSING" ADD CONSTRAINT "PK_STORE_CLOSING" PRIMARY KEY ("STORE_CLOSING_NUM")
  USING INDEX "TREXONE_DATA"."PK_STORE_CLOSING"  ENABLE;
-- ==========================================
