-- ==========================================

  CREATE TABLE "TREXONE_DATA"."SUPV_PRESCRIBER"
   (	"PRESCRIBER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SUPV_PRESCRIBER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"SUPV_PRESCRIBER_ADDR_NUM" NUMBER(18,0),
	"SUPV_PRESCRIBER_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PRESCRIBER_24" FOREIGN KEY ("PRESCRIBER_NUM")
	  REFERENCES "TREXONE_DATA"."PRESCRIBER" ("PRESCRIBER_NUM") ENABLE,
	 CONSTRAINT "FK_PRESCRIBER_25" FOREIGN KEY ("SUPV_PRESCRIBER_NUM")
	  REFERENCES "TREXONE_DATA"."PRESCRIBER" ("PRESCRIBER_NUM") ENABLE,
	 CONSTRAINT "FK_PRESCRIBER_ADDRESS_9" FOREIGN KEY ("SUPV_PRESCRIBER_ADDR_NUM")
	  REFERENCES "TREXONE_DATA"."PRESCRIBER_ADDRESS" ("PRESCRIBER_ADDRESS_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."UC_SUPV_PRESCRIBER_1" ON "TREXONE_DATA"."SUPV_PRESCRIBER" ("PRESCRIBER_NUM", "SUPV_PRESCRIBER_NUM", "SUPV_PRESCRIBER_ADDR_NUM", "ERX_CLIENT_ID")
  ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_SUPV_PRESCRIBER" ON "TREXONE_DATA"."SUPV_PRESCRIBER" ("SUPV_PRESCRIBER_KEY")
  ;
ALTER TABLE "TREXONE_DATA"."SUPV_PRESCRIBER" ADD CONSTRAINT "PK_SUPV_PRESCRIBER" PRIMARY KEY ("SUPV_PRESCRIBER_KEY")
  USING INDEX "TREXONE_DATA"."PK_SUPV_PRESCRIBER"  ENABLE;
ALTER TABLE "TREXONE_DATA"."SUPV_PRESCRIBER" ADD CONSTRAINT "UC_SUPV_PRESCRIBER_1" UNIQUE ("PRESCRIBER_NUM", "SUPV_PRESCRIBER_NUM", "SUPV_PRESCRIBER_ADDR_NUM", "ERX_CLIENT_ID")
  USING INDEX "TREXONE_DATA"."UC_SUPV_PRESCRIBER_1"  ENABLE;
-- ==========================================
