-- ==========================================

  CREATE TABLE "TREXONE_DATA"."SYSTEM_USER_ROLE"
   (	"SYSTEM_USER_ROLE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SYSTEM_USER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ROLE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TYPE" CHAR(1) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_ROLE_03" FOREIGN KEY ("ROLE_NUM")
	  REFERENCES "TREXONE_DATA"."ROLE" ("ROLE_NUM") ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_18" FOREIGN KEY ("SYSTEM_USER_NUM")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_SYSTEM_USER_ROLE" ON "TREXONE_DATA"."SYSTEM_USER_ROLE" ("SYSTEM_USER_ROLE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."SYSTEM_USER_ROLE" ADD CONSTRAINT "PK_SYSTEM_USER_ROLE" PRIMARY KEY ("SYSTEM_USER_ROLE_NUM")
  USING INDEX "TREXONE_DATA"."PK_SYSTEM_USER_ROLE"  ENABLE;
-- ==========================================
