-- ==========================================

  CREATE TABLE "TREXONE_DATA"."SYSTEM_MESSAGE"
   (	"SYSTEM_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TITLE" VARCHAR2(255) NOT NULL ENABLE,
	"MESSAGE" VARCHAR2(4000),
	"TYPE" VARCHAR2(30),
	"SUBJECT" VARCHAR2(50),
	"MESSAGE_LOCATION" CHAR(1),
	"EFFECTIVE_DATE" DATE,
	"EXPIRATION_DATE" DATE,
	"IS_ALERT" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ALERT_LEVEL" NUMBER(9,0),
	"MESSAGE_ORDER" NUMBER(9,0),
	"DATA_GROUP" NUMBER(18,0),
	"IS_FIRST" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_SYSTEM_MESSAGE" ON "TREXONE_DATA"."SYSTEM_MESSAGE" ("SYSTEM_MESSAGE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."SYSTEM_MESSAGE" ADD CONSTRAINT "PK_SYSTEM_MESSAGE" PRIMARY KEY ("SYSTEM_MESSAGE_NUM")
  USING INDEX "TREXONE_DATA"."PK_SYSTEM_MESSAGE"  ENABLE;
-- ==========================================
