-- ==========================================

  CREATE TABLE "TREXONE_DATA"."THERAPEUTIC_SUBSTITUTION"
   (	"THERAPEUTIC_SUBSTITUTION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRODUCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"BUSINESS_PARTNER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(35),
	"DESCRIPTION" VARCHAR2(60),
	"PRECEDENCE" NUMBER(18,0),
	"EFFECTIVE_DATE" DATE,
	"TERM_DATE" DATE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"IS_GENERIC_SUB_ALLOWED" CHAR(1),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_BUSINESS_PARTNER_01" FOREIGN KEY ("BUSINESS_PARTNER_NUM")
	  REFERENCES "TREXONE_DATA"."BUSINESS_PARTNER" ("BUSINESS_PARTNER_NUM") ENABLE,
	 CONSTRAINT "FK_PRODUCT_24" FOREIGN KEY ("PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT" ("PRODUCT_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_THERAPEUTIC_SUBSTITUTION" ON "TREXONE_DATA"."THERAPEUTIC_SUBSTITUTION" ("THERAPEUTIC_SUBSTITUTION_NUM", "PRODUCT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."THERAPEUTIC_SUBSTITUTION" ADD CONSTRAINT "PK_THERAPEUTIC_SUBSTITUTION" PRIMARY KEY ("THERAPEUTIC_SUBSTITUTION_NUM", "PRODUCT_NUM")
  USING INDEX "TREXONE_DATA"."PK_THERAPEUTIC_SUBSTITUTION"  ENABLE;
-- ==========================================
