-- ==========================================

  CREATE TABLE "TREXONE_DATA"."THERAPEUTIC_SUB_QUALIFIER"
   (	"THERAPEUTIC_SUBSTITUTION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRODUCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"THERAPEUTIC_SUB_GROUP_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(60),
	"INCLUDE_EXCLUDE" VARCHAR2(20),
	"EFFECTIVE_DATE" DATE,
	"TERM_DATE" DATE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_THERAPEUTIC_SUBSTITUTION_02" FOREIGN KEY ("THERAPEUTIC_SUBSTITUTION_NUM", "PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."THERAPEUTIC_SUBSTITUTION" ("THERAPEUTIC_SUBSTITUTION_NUM", "PRODUCT_NUM") ENABLE,
	 CONSTRAINT "FK_THERAPEUTIC_SUB_GROUP_03" FOREIGN KEY ("THERAPEUTIC_SUB_GROUP_NUM")
	  REFERENCES "TREXONE_DATA"."THERAPEUTIC_SUB_GROUP" ("THERAPEUTIC_SUB_GROUP_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_THERAPEUTIC_SUB_QUALIFIER" ON "TREXONE_DATA"."THERAPEUTIC_SUB_QUALIFIER" ("THERAPEUTIC_SUBSTITUTION_NUM", "PRODUCT_NUM", "THERAPEUTIC_SUB_GROUP_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."THERAPEUTIC_SUB_QUALIFIER" ADD CONSTRAINT "PK_THERAPEUTIC_SUB_QUALIFIER" PRIMARY KEY ("THERAPEUTIC_SUBSTITUTION_NUM", "PRODUCT_NUM", "THERAPEUTIC_SUB_GROUP_NUM")
  USING INDEX "TREXONE_DATA"."PK_THERAPEUTIC_SUB_QUALIFIER"  ENABLE;
-- ==========================================
