-- ==========================================

  CREATE TABLE "TREXONE_DATA"."THERAPEUTIC_SUB_PRODUCT"
   (	"THERAPEUTIC_SUBSTITUTION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRODUCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SUBSTITUTED_PRODUCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"MULTIPLIER" NUMBER(16,8),
	"EFFECTIVE_DATE" DATE,
	"TERM_DATE" DATE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PRODUCT_25" FOREIGN KEY ("SUBSTITUTED_PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT" ("PRODUCT_NUM") ENABLE,
	 CONSTRAINT "FK_THERAPEUTIC_SUBSTITUTION_01" FOREIGN KEY ("THERAPEUTIC_SUBSTITUTION_NUM", "PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."THERAPEUTIC_SUBSTITUTION" ("THERAPEUTIC_SUBSTITUTION_NUM", "PRODUCT_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_THERAPEUTIC_SUB_PRODUCT" ON "TREXONE_DATA"."THERAPEUTIC_SUB_PRODUCT" ("THERAPEUTIC_SUBSTITUTION_NUM", "PRODUCT_NUM", "SUBSTITUTED_PRODUCT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."THERAPEUTIC_SUB_PRODUCT" ADD CONSTRAINT "PK_THERAPEUTIC_SUB_PRODUCT" PRIMARY KEY ("THERAPEUTIC_SUBSTITUTION_NUM", "PRODUCT_NUM", "SUBSTITUTED_PRODUCT_NUM")
  USING INDEX "TREXONE_DATA"."PK_THERAPEUTIC_SUB_PRODUCT"  ENABLE;
-- ==========================================
