-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_ADJ_DRIVER_CONFIG"
   (	"TP_ADJ_DRIVER_CONFIG_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_ADJ_DRIVER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CONFIGURATION_NAME" VARCHAR2(80) NOT NULL ENABLE,
	"CONFIGURATION" VARCHAR2(4000),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_TP_ADJ_DRIVER_01" FOREIGN KEY ("TP_ADJ_DRIVER_NUM")
	  REFERENCES "TREXONE_DATA"."TP_ADJ_DRIVER" ("TP_ADJ_DRIVER_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_ADJ_DRIVER_CONFIG" ON "TREXONE_DATA"."TP_ADJ_DRIVER_CONFIG" ("TP_ADJ_DRIVER_CONFIG_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_ADJ_DRIVER_CONFIG" ADD CONSTRAINT "PK_TP_ADJ_DRIVER_CONFIG" PRIMARY KEY ("TP_ADJ_DRIVER_CONFIG_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_ADJ_DRIVER_CONFIG"  ENABLE;
-- ==========================================
