-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_BILLING_FORMAT_LITERALS"
   (	"TP_BILLING_FORMAT_LITERALS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_BILLING_FORMAT_VERSION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FIELD_CODE" VARCHAR2(10) NOT NULL ENABLE,
	"LITERAL_VALUE" VARCHAR2(255),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_TP_BILLING_FORMAT_LTRL_01" FOREIGN KEY ("TP_BILLING_FORMAT_VERSION_NUM")
	  REFERENCES "TREXONE_DATA"."TP_BILLING_FORMAT_VERSION" ("TP_BILLING_FORMAT_VERSION_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_BILLING_FORMAT_LITERALS" ON "TREXONE_DATA"."TP_BILLING_FORMAT_LITERALS" ("TP_BILLING_FORMAT_LITERALS_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_BILLING_FORMAT_LITERALS" ADD CONSTRAINT "PK_TP_BILLING_FORMAT_LITERALS" PRIMARY KEY ("TP_BILLING_FORMAT_LITERALS_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_BILLING_FORMAT_LITERALS"  ENABLE;
-- ==========================================
