-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_BILLING_FORMAT"
   (	"TP_BILLING_FORMAT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_BILLING_STANDARD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(50),
	"DESCRIPTION" VARCHAR2(60),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "U_TP_BILLING_FORMAT_1" UNIQUE ("NAME", "ERX_CLIENT_ID")
  USING INDEX (CREATE UNIQUE INDEX "TREXONE_DATA"."UI_TP_BILLING_FORMAT_1" ON "TREXONE_DATA"."TP_BILLING_FORMAT" ("NAME", "ERX_CLIENT_ID")
  )  ENABLE,
	 CONSTRAINT "FK_TP_BILLING_STANDARD_01" FOREIGN KEY ("TP_BILLING_STANDARD_NUM")
	  REFERENCES "TREXONE_DATA"."TP_BILLING_STANDARD" ("TP_BILLING_STANDARD_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_BILLING_FORMAT" ON "TREXONE_DATA"."TP_BILLING_FORMAT" ("TP_BILLING_FORMAT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_BILLING_FORMAT" ADD CONSTRAINT "PK_TP_BILLING_FORMAT" PRIMARY KEY ("TP_BILLING_FORMAT_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_BILLING_FORMAT"  ENABLE;
-- ==========================================
