-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_DATA_PARTNER_PRODUCT"
   (	"TP_DATA_PARTNER_PRODUCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_DATA_PARTNER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRODUCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"EFFECTIVE_DATE" DATE,
	"TERMINATION_DATE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PRODUCT_26" FOREIGN KEY ("PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT" ("PRODUCT_NUM") ENABLE,
	 CONSTRAINT "FK_TP_DATA_PARTNER_02" FOREIGN KEY ("TP_DATA_PARTNER_NUM")
	  REFERENCES "TREXONE_DATA"."TP_DATA_PARTNER" ("TP_DATA_PARTNER_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_DATA_PARTNER_PRODUCT" ON "TREXONE_DATA"."TP_DATA_PARTNER_PRODUCT" ("TP_DATA_PARTNER_PRODUCT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_DATA_PARTNER_PRODUCT" ADD CONSTRAINT "PK_TP_DATA_PARTNER_PRODUCT" PRIMARY KEY ("TP_DATA_PARTNER_PRODUCT_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_DATA_PARTNER_PRODUCT"  ENABLE;
-- ==========================================
