-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_DATA_PARTNER"
   (	"TP_DATA_PARTNER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(30) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"TP_ADJ_DRIVER_CONFIG_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_TP_ADJ_DRIVER_CONFIG_02" FOREIGN KEY ("TP_ADJ_DRIVER_CONFIG_NUM")
	  REFERENCES "TREXONE_DATA"."TP_ADJ_DRIVER_CONFIG" ("TP_ADJ_DRIVER_CONFIG_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_DATA_PARTNER" ON "TREXONE_DATA"."TP_DATA_PARTNER" ("TP_DATA_PARTNER_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_DATA_PARTNER" ADD CONSTRAINT "PK_TP_DATA_PARTNER" PRIMARY KEY ("TP_DATA_PARTNER_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_DATA_PARTNER"  ENABLE;
-- ==========================================
