-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_DATA_PARTNER_BATCH_MSG"
   (	"TP_DATA_PARTNER_BATCH_MSG_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SUBMISSION_DATE" DATE NOT NULL ENABLE,
	"DATA_PARTNER_MESSAGE" CLOB,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_DATA_PARTNER_BATCH_MSG" ON "TREXONE_DATA"."TP_DATA_PARTNER_BATCH_MSG" ("TP_DATA_PARTNER_BATCH_MSG_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_DATA_PARTNER_BATCH_MSG" ADD CONSTRAINT "PK_TP_DATA_PARTNER_BATCH_MSG" PRIMARY KEY ("TP_DATA_PARTNER_BATCH_MSG_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_DATA_PARTNER_BATCH_MSG"  ENABLE;
-- ==========================================
