-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_DATA_PARTNER_FORMAT"
   (	"TP_DATA_PARTNER_FORMAT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_DATA_PARTNER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_BILLING_FORMAT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"EFFECTIVE_DATE" DATE,
	"TERMINATION_DATE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_TP_BILLING_FORMAT_07" FOREIGN KEY ("TP_BILLING_FORMAT_NUM")
	  REFERENCES "TREXONE_DATA"."TP_BILLING_FORMAT" ("TP_BILLING_FORMAT_NUM") ENABLE,
	 CONSTRAINT "FK_TP_DATA_PARTNER_01" FOREIGN KEY ("TP_DATA_PARTNER_NUM")
	  REFERENCES "TREXONE_DATA"."TP_DATA_PARTNER" ("TP_DATA_PARTNER_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_DATA_PARTNER_FORMAT" ON "TREXONE_DATA"."TP_DATA_PARTNER_FORMAT" ("TP_DATA_PARTNER_FORMAT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_DATA_PARTNER_FORMAT" ADD CONSTRAINT "PK_TP_DATA_PARTNER_FORMAT" PRIMARY KEY ("TP_DATA_PARTNER_FORMAT_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_DATA_PARTNER_FORMAT"  ENABLE;
-- ==========================================
