-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_DEACTIVATION_REASON"
   (	"TP_DEACTIVATION_REASON_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"REASON_CODE" VARCHAR2(10) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(40) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_DEACTIVATION_REASON" ON "TREXONE_DATA"."TP_DEACTIVATION_REASON" ("TP_DEACTIVATION_REASON_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_DEACTIVATION_REASON" ADD CONSTRAINT "PK_TP_DEACTIVATION_REASON" PRIMARY KEY ("TP_DEACTIVATION_REASON_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_DEACTIVATION_REASON"  ENABLE;
-- ==========================================
