-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_DATA_PARTNER_METRIC"
   (	"TP_DATA_PARTNER_METRIC_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PROCESSING_DATE" DATE NOT NULL ENABLE,
	"REAL_TIME_COUNT" NUMBER(9,0) NOT NULL ENABLE,
	"BATCHED_COUNT" NUMBER(9,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_DATA_PARTNER_METRIC" ON "TREXONE_DATA"."TP_DATA_PARTNER_METRIC" ("TP_DATA_PARTNER_METRIC_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_DATA_PARTNER_METRIC" ADD CONSTRAINT "PK_TP_DATA_PARTNER_METRIC" PRIMARY KEY ("TP_DATA_PARTNER_METRIC_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_DATA_PARTNER_METRIC"  ENABLE;
-- ==========================================
