-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_EXTERNAL_PRE_EDIT"
   (	"TP_EXTERNAL_PRE_EDIT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_BILLING_FORMAT_NUM" NUMBER(18,0),
	"TP_ADJ_DRIVER_CONFIG_NUM" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"TP_PROCESSOR_NUM" NUMBER(18,0),
	"TP_PROCESSOR_DESTINATION_SEQ" NUMBER(18,0),
	"NON_ONLINE_BILLING_FORMAT_NUM" NUMBER(18,0),
	"IS_EXT_PRE_EDIT_NON_ONLINE" CHAR(1),
	"IS_EXT_PRE_EDIT_CASH" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"TP_BILLING_REV_FORMAT_NUM" NUMBER(18,0),
	 CONSTRAINT "FK_TP_ADJ_DRIVER_CONFIG_03" FOREIGN KEY ("TP_ADJ_DRIVER_CONFIG_NUM")
	  REFERENCES "TREXONE_DATA"."TP_ADJ_DRIVER_CONFIG" ("TP_ADJ_DRIVER_CONFIG_NUM") ENABLE,
	 CONSTRAINT "FK_TP_BILLING_FORMAT_08" FOREIGN KEY ("TP_BILLING_FORMAT_NUM")
	  REFERENCES "TREXONE_DATA"."TP_BILLING_FORMAT" ("TP_BILLING_FORMAT_NUM") ENABLE,
	 CONSTRAINT "FK_TP_BILLING_FORMAT_11" FOREIGN KEY ("NON_ONLINE_BILLING_FORMAT_NUM")
	  REFERENCES "TREXONE_DATA"."TP_BILLING_FORMAT" ("TP_BILLING_FORMAT_NUM") ENABLE,
	 CONSTRAINT "FK_TP_PROCESSOR_DESTINATION_02" FOREIGN KEY ("TP_PROCESSOR_NUM", "TP_PROCESSOR_DESTINATION_SEQ")
	  REFERENCES "TREXONE_DATA"."TP_PROCESSOR_DESTINATION" ("TP_PROCESSOR_NUM", "TP_PROCESSOR_DESTINATION_SEQ") ENABLE,
	 CONSTRAINT "FK_TP_BILLING_FORMAT_17" FOREIGN KEY ("TP_BILLING_REV_FORMAT_NUM")
	  REFERENCES "TREXONE_DATA"."TP_BILLING_FORMAT" ("TP_BILLING_FORMAT_NUM") ENABLE NOVALIDATE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_EXTERNAL_PRE_EDIT" ON "TREXONE_DATA"."TP_EXTERNAL_PRE_EDIT" ("TP_EXTERNAL_PRE_EDIT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_EXTERNAL_PRE_EDIT" ADD CONSTRAINT "PK_TP_EXTERNAL_PRE_EDIT" PRIMARY KEY ("TP_EXTERNAL_PRE_EDIT_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_EXTERNAL_PRE_EDIT"  ENABLE;
-- ==========================================
