-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_ITEM_DIAGNOSIS"
   (	"TP_ITEM_DIAGNOSIS_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_ITEM_CLAIM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DIAGNOSIS_CODE_QUALIFIER" VARCHAR2(2),
	"DIAGNOSIS_CODE" VARCHAR2(20),
	"PLAN_SPECIFIC_CODE" VARCHAR2(45),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_TP_ITEM_CLAIM_04" FOREIGN KEY ("TP_ITEM_CLAIM_NUM")
	  REFERENCES "TREXONE_DATA"."TP_ITEM_CLAIM" ("TP_ITEM_CLAIM_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_ITEM_DIAGNOSIS" ON "TREXONE_DATA"."TP_ITEM_DIAGNOSIS" ("TP_ITEM_DIAGNOSIS_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_ITEM_DIAGNOSIS" ADD CONSTRAINT "PK_TP_ITEM_DIAGNOSIS" PRIMARY KEY ("TP_ITEM_DIAGNOSIS_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_ITEM_DIAGNOSIS"  ENABLE;
-- ==========================================
