-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_ITEM_FIELD_VALUE"
   (	"TP_ITEM_FIELD_VALUE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_ITEM_FIELD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"OWNER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"OWNER" VARCHAR2(50) NOT NULL ENABLE,
	"COPY_VALUE_TO_NEXT_FILL" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_TP_ITEM_FIELD_VALUE" PRIMARY KEY ("TP_ITEM_FIELD_VALUE_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_TP_ITEM_FIELD_VALUE_01" FOREIGN KEY ("TP_ITEM_FIELD_NUM")
	  REFERENCES "TREXONE_DATA"."TP_ITEM_FIELD" ("TP_ITEM_FIELD_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
-- ==========================================
