-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_MEDICAID_LOAD_PROCESSING"
   (	"TP_MEDICAID_LOAD_PROC_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_MEDICAID_LOAD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DP_FILE_NAME" VARCHAR2(255) NOT NULL ENABLE,
	"DP_FILE_VERSION" VARCHAR2(12) NOT NULL ENABLE,
	"DP_SPECIFIED_NUM_RECORDS" NUMBER(9,0) NOT NULL ENABLE,
	"NUM_RECORDS_STAGED" NUMBER(9,0) NOT NULL ENABLE,
	"NUM_STAGED_RECORDS_PROCESSED" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_TP_MEDICAID_LOAD_01" FOREIGN KEY ("TP_MEDICAID_LOAD_NUM")
	  REFERENCES "TREXONE_DATA"."TP_MEDICAID_LOAD" ("TP_MEDICAID_LOAD_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_MEDICAID_LOAD_PROCESSING" ON "TREXONE_DATA"."TP_MEDICAID_LOAD_PROCESSING" ("TP_MEDICAID_LOAD_PROC_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_MEDICAID_LOAD_PROCESSING" ADD CONSTRAINT "PK_TP_MEDICAID_LOAD_PROCESSING" PRIMARY KEY ("TP_MEDICAID_LOAD_PROC_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_MEDICAID_LOAD_PROCESSING"  ENABLE;
-- ==========================================
