-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_MEDICAID_DRUG_ATTRIBUTE"
   (	"TP_MEDICAID_DRUG_ATTRIBUTE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ATTRIBUTE_DESCRIPTION" VARCHAR2(50) NOT NULL ENABLE,
	"DATA_TYPE" VARCHAR2(12),
	"MAX_LENGTH" NUMBER(3,0),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_MEDICAID_DRUG_ATTRIBUTE" ON "TREXONE_DATA"."TP_MEDICAID_DRUG_ATTRIBUTE" ("TP_MEDICAID_DRUG_ATTRIBUTE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_MEDICAID_DRUG_ATTRIBUTE" ADD CONSTRAINT "PK_TP_MEDICAID_DRUG_ATTRIBUTE" PRIMARY KEY ("TP_MEDICAID_DRUG_ATTRIBUTE_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_MEDICAID_DRUG_ATTRIBUTE"  ENABLE;
-- ==========================================
