-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_MESSAGE_REJECT"
   (	"TP_MESSAGE_REJECT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"REJECT_CODE" VARCHAR2(4) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT SYS_CONTEXT('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"PARTITION_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	 CONSTRAINT "PK_TP_MESSAGE_REJECT" PRIMARY KEY ("TP_MESSAGE_REJECT_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_115" FOREIGN KEY ("SYS_USER")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_TP_MESSAGE_05" FOREIGN KEY ("TP_MESSAGE_NUM")
	  REFERENCES "TREXONE_DATA"."TP_MESSAGE" ("TP_MESSAGE_NUM") ENABLE NOVALIDATE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTOYMINTERVAL(3,'MONTH')) STORE IN ("MEDIUM_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
