-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_MESSAGE_DETAIL"
   (	"TP_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CARDHOLDER_ID" VARCHAR2(20),
	"CARDHOLDER_FIRST_NAME" VARCHAR2(30),
	"CARDHOLDER_LAST_NAME" VARCHAR2(30),
	"PRODUCT_SERVICE_ID" VARCHAR2(20),
	"GROSS_AMT_DUE" NUMBER(17,6),
	"PATIENT_PAY_AMT_SUBMITTED" NUMBER(17,6),
	"AUTHORIZATION_NUMBER" VARCHAR2(20),
	"PATIENT_PAY_AMT" NUMBER(17,6),
	"TOTAL_AMT_PAID" NUMBER(17,6),
	"REJECT_CODE" VARCHAR2(5),
	"QTY_DISPENSED" NUMBER(10,3),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0),
	"FACILITY_PLAN_NUM" VARCHAR2(20),
	"BILLING_METHOD" CHAR(1),
	"BILLING_INDICATOR" CHAR(1),
	"PAYMENT_TYPE" CHAR(1),
	"TAX_EXEMPT_INDICATOR" CHAR(1),
	"PARTIAL_FILL_BILLING" CHAR(1),
	"SUBMIT_DISCOUNT_U_C" CHAR(1),
	"COMP_NDC_TO_BILL" VARCHAR2(11),
	"QTY_CONVERSION_FACTOR" NUMBER(7,3),
	"MEDICARE_BILLING_ID" VARCHAR2(80),
	"MEDICARE_INSURANCE_TYPE" VARCHAR2(2),
	"INSURANCE_INDICATOR_CODE" VARCHAR2(2),
	"NUM_REFILLS_ALLOWED" NUMBER(5,0),
	"SERVICE_PROVIDER_ID" VARCHAR2(15),
	"SERVICE_PROVIDER_ID_QUAL" VARCHAR2(2),
	"PATIENT_ID" VARCHAR2(20),
	"PATIENT_ID_QUAL" VARCHAR2(2),
	"ORIG_RX_PROD_SVC_ID" VARCHAR2(19),
	"ORIG_RX_PROD_SVC_ID_QUAL" VARCHAR2(2),
	"PROD_SERVICE_ID" VARCHAR2(19),
	"PROD_SERVICE_ID_QUAL" VARCHAR2(2),
	"PRESCRIBER_ID" VARCHAR2(15),
	"PRESCRIBER_ID_QUAL" VARCHAR2(2),
	"PRIM_CARE_PROVIDER_ID" VARCHAR2(15),
	"PRIM_CARE_PROVIDER_ID_QUAL" VARCHAR2(2),
	"PROVIDER_ID" VARCHAR2(15),
	"PROVIDER_ID_QUAL" VARCHAR2(2),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"NETWORK_REIMBURSEMENT_ID" VARCHAR2(20),
	 CONSTRAINT "FK_TP_MESSAGE_04" FOREIGN KEY ("TP_MESSAGE_NUM")
	  REFERENCES "TREXONE_DATA"."TP_MESSAGE" ("TP_MESSAGE_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_MESSAGE_DETAIL" ON "TREXONE_DATA"."TP_MESSAGE_DETAIL" ("TP_MESSAGE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_MESSAGE_DETAIL" ADD CONSTRAINT "PK_TP_MESSAGE_DETAIL" PRIMARY KEY ("TP_MESSAGE_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_MESSAGE_DETAIL"  ENABLE;
-- ==========================================
