-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_MEDICAID_DRUG_ATTR_VALUE"
   (	"TP_MEDICAID_DRUG_ATTR_VAL_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_MEDICAID_DRUG_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_MEDICAID_LOAD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_MEDICAID_DRUG_ATTRIBUTE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DP_VALUE" VARCHAR2(100),
	"OVERRIDE_VALUE" VARCHAR2(100),
	"OVERRIDE_PRE_EDIT_MESSAGE" VARCHAR2(255),
	"OVERRIDE_WARN_LEV" NUMBER(9,0),
	"OVERRIDE_DATA_FILTER_NAME" VARCHAR2(60),
	"OVERRIDE_DATA_FILTER" VARCHAR2(2000),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_TP_MEDICAID_DRUG_01" FOREIGN KEY ("TP_MEDICAID_DRUG_NUM")
	  REFERENCES "TREXONE_DATA"."TP_MEDICAID_DRUG" ("TP_MEDICAID_DRUG_NUM") ENABLE,
	 CONSTRAINT "FK_TP_MEDICAID_DRUG_ATTR_01" FOREIGN KEY ("TP_MEDICAID_DRUG_ATTRIBUTE_NUM")
	  REFERENCES "TREXONE_DATA"."TP_MEDICAID_DRUG_ATTRIBUTE" ("TP_MEDICAID_DRUG_ATTRIBUTE_NUM") ENABLE,
	 CONSTRAINT "FK_TP_MEDICAID_LOAD_03" FOREIGN KEY ("TP_MEDICAID_LOAD_NUM")
	  REFERENCES "TREXONE_DATA"."TP_MEDICAID_LOAD" ("TP_MEDICAID_LOAD_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_MEDICAID_DRUG_ATTR_VALUE" ON "TREXONE_DATA"."TP_MEDICAID_DRUG_ATTR_VALUE" ("TP_MEDICAID_DRUG_ATTR_VAL_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_MEDICAID_DRUG_ATTR_VALUE" ADD CONSTRAINT "PK_TP_MEDICAID_DRUG_ATTR_VALUE" PRIMARY KEY ("TP_MEDICAID_DRUG_ATTR_VAL_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_MEDICAID_DRUG_ATTR_VALUE"  ENABLE;
-- ==========================================
