-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_NETWORK"
   (	"TP_NETWORK_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(45) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(255),
	"NETWORK_NUMBER" VARCHAR2(10),
	"EFFECTIVE_DATE" DATE,
	"TERMINATION_DATE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_NETWORK" ON "TREXONE_DATA"."TP_NETWORK" ("TP_NETWORK_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_NETWORK" ADD CONSTRAINT "PK_TP_NETWORK" PRIMARY KEY ("TP_NETWORK_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_NETWORK"  ENABLE;
-- ==========================================
