-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_PROCESSOR"
   (	"TP_PROCESSOR_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_PROCESSOR_GROUP_NUM" NUMBER(18,0),
	"NAME" VARCHAR2(45) NOT NULL ENABLE,
	"CONTACT_NAME" VARCHAR2(45),
	"EFFECTIVE_DATE" DATE,
	"TERMINATION_DATE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_TP_PROCESSOR_GROUP_01" FOREIGN KEY ("TP_PROCESSOR_GROUP_NUM")
	  REFERENCES "TREXONE_DATA"."TP_PROCESSOR_GROUP" ("TP_PROCESSOR_GROUP_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_PROCESSOR" ON "TREXONE_DATA"."TP_PROCESSOR" ("TP_PROCESSOR_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_PROCESSOR" ADD CONSTRAINT "PK_TP_PROCESSOR" PRIMARY KEY ("TP_PROCESSOR_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_PROCESSOR"  ENABLE;
-- ==========================================
