-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_PRODUCT_ID"
   (	"TP_PRODUCT_ID_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_PLAN_NUM" NUMBER(18,0),
	"TP_BENEFIT_GROUP_SEQ" NUMBER(18,0),
	"TP_NETWORK_NUM" NUMBER(18,0),
	"PRODUCT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PRODUCT_ID" VARCHAR2(20),
	"PRODUCT_ID_TYPE" VARCHAR2(20),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PRODUCT_28" FOREIGN KEY ("PRODUCT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT" ("PRODUCT_NUM") ENABLE,
	 CONSTRAINT "FK_TP_BENEFIT_GROUP_05" FOREIGN KEY ("TP_PLAN_NUM", "TP_BENEFIT_GROUP_SEQ")
	  REFERENCES "TREXONE_DATA"."TP_BENEFIT_GROUP" ("TP_PLAN_NUM", "TP_BENEFIT_GROUP_SEQ") ENABLE,
	 CONSTRAINT "FK_TP_NETWORK_06" FOREIGN KEY ("TP_NETWORK_NUM")
	  REFERENCES "TREXONE_DATA"."TP_NETWORK" ("TP_NETWORK_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_PRODUCT_ID" ON "TREXONE_DATA"."TP_PRODUCT_ID" ("TP_PRODUCT_ID_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_PRODUCT_ID" ADD CONSTRAINT "PK_TP_PRODUCT_ID" PRIMARY KEY ("TP_PRODUCT_ID_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_PRODUCT_ID"  ENABLE;
-- ==========================================
