-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_PATIENT_ELIGIBILITY"
   (	"TP_PATIENT_ELIGIBILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_RULE_SET_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PATIENT_NAME" VARCHAR2(80),
	"CARDHOLDER_ID" VARCHAR2(20) NOT NULL ENABLE,
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE,
	"TERMINATION_DATE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_TP_RULE_SET_03" FOREIGN KEY ("TP_RULE_SET_NUM")
	  REFERENCES "TREXONE_DATA"."TP_RULE_SET" ("TP_RULE_SET_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_PATIENT_ELIGIBILITY" ON "TREXONE_DATA"."TP_PATIENT_ELIGIBILITY" ("TP_PATIENT_ELIGIBILITY_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_PATIENT_ELIGIBILITY" ADD CONSTRAINT "PK_TP_PATIENT_ELIGIBILITY" PRIMARY KEY ("TP_PATIENT_ELIGIBILITY_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_PATIENT_ELIGIBILITY"  ENABLE;
-- ==========================================
