-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_PRESCRIBER_ID_DEFAULT"
   (	"TP_PRESCRIBER_ID_DEFAULT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_RULE_SET_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DOCTOR_TYPE_CODE" VARCHAR2(20),
	"PRESCRIBER_ID_TYPE" NUMBER(9,0),
	"DEFAULT_ID" VARCHAR2(20),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"RULE_EXPRESSION" CLOB,
	"VALUE_EXPRESSION" CLOB,
	"RANK" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_TP_RULE_SET_06" FOREIGN KEY ("TP_RULE_SET_NUM")
	  REFERENCES "TREXONE_DATA"."TP_RULE_SET" ("TP_RULE_SET_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_PRESCRIBER_ID_DEFAULT" ON "TREXONE_DATA"."TP_PRESCRIBER_ID_DEFAULT" ("TP_PRESCRIBER_ID_DEFAULT_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_PRESCRIBER_ID_DEFAULT" ADD CONSTRAINT "PK_TP_PRESCRIBER_ID_DEFAULT" PRIMARY KEY ("TP_PRESCRIBER_ID_DEFAULT_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_PRESCRIBER_ID_DEFAULT"  ENABLE;
-- ==========================================
