-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_PATIENT"
   (	"TP_PATIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PATIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CARDHOLDER_PATIENT_NUM" NUMBER(18,0),
	"TP_PLAN_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CARDHOLDER_ID" VARCHAR2(20),
	"BENEFIT_GROUP_ID" VARCHAR2(15),
	"HOME_PLAN" VARCHAR2(3),
	"PLAN_ID" VARCHAR2(8),
	"RELATIONSHIP_NUM" NUMBER(9,0),
	"PERSON_CODE" VARCHAR2(3),
	"BILLING_ORDER" NUMBER(9,0) NOT NULL ENABLE,
	"IS_ACTIVE" CHAR(1) NOT NULL ENABLE,
	"EFFECTIVE_DATE" DATE,
	"TERMINATION_DATE" DATE,
	"MULTI_SOURCE_COPAY_AMOUNT" NUMBER(17,6),
	"MULTI_SOURCE_COPAY_PERCENT" NUMBER(17,6),
	"SINGLE_SOURCE_COPAY_AMOUNT" NUMBER(17,6),
	"SINGLE_SOURCE_COPAY_PERCENT" NUMBER(17,6),
	"GENERIC_COPAY_AMOUNT" NUMBER(17,6),
	"GENERIC_COPAY_PERCENT" NUMBER(17,6),
	"PTD_COVERAGE_AMOUNT" NUMBER(17,6),
	"PTD_NUM_RXS" NUMBER(9,0),
	"DEACTIVATION_DATE" DATE,
	"DEACTIVATION_COMMENT" VARCHAR2(255),
	"PATIENT_LOCATION" NUMBER(9,0),
	"USE_FOR_COB" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"FAMILY_PTD_COVERAGE_AMOUNT" NUMBER(17,6),
	"FAMILY_PTD_NUM_RXS" NUMBER(9,0),
	"FAMILY_PTD_DEDUCTIBLE_AMOUNT" NUMBER(17,6),
	"PTD_DEDUCTIBLE_EXPIRATION" DATE,
	"FAMILY_PTD_DEDUCTIBLE_EXP" DATE,
	"PTD_COVERAGE_EXPIRATION" DATE,
	"PTD_NUM_RXS_EXPIRATION" DATE,
	"FAMILY_PTD_COVERAGE_EXPIRATION" DATE,
	"FAMILY_NUM_RXS_EXPIRATION" DATE,
	"PTD_DEDUCTIBLE_AMOUNT" NUMBER(17,6),
	"ELIGIBILITY_CLARIF_NUM" NUMBER(18,0),
	"ORIG_ADD_DATE" DATE,
	"MEMBER_COVERAGE_BASIS_USED" VARCHAR2(30),
	"FAMILY_COVERAGE_BASIS_USED" VARCHAR2(30),
	"REMAINING_BENEFIT_AMT" NUMBER(17,6),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"IS_REIMBURSED_DIRECTLY" CHAR(1),
	"OTHER_PAYER_ID" VARCHAR2(10),
	"PATIENT_RESIDENCE" VARCHAR2(2),
	"PROCESSOR_CONTROL_NUMBER" VARCHAR2(10),
	"ACTIVE_PATIENT_NUM" NUMBER GENERATED ALWAYS AS (DECODE(UPPER("IS_ACTIVE"),'Y',"PATIENT_NUM",NULL)) VIRTUAL ,
	"ACTIVE_BILLING_ORDER" NUMBER GENERATED ALWAYS AS (DECODE(UPPER("IS_ACTIVE"),'Y',"BILLING_ORDER",NULL)) VIRTUAL ,
	 CONSTRAINT "FK_PATIENT_16" FOREIGN KEY ("PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE,
	 CONSTRAINT "FK_PATIENT_17" FOREIGN KEY ("CARDHOLDER_PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PATIENT" ("PATIENT_NUM") ENABLE,
	 CONSTRAINT "FK_TP_PLAN_05" FOREIGN KEY ("TP_PLAN_NUM")
	  REFERENCES "TREXONE_DATA"."TP_PLAN" ("TP_PLAN_NUM") ENABLE
   ) ;
  CREATE INDEX "TREXONE_DATA"."IN_TP_PATIENT_08" ON "TREXONE_DATA"."TP_PATIENT" ("ACTIVE_PATIENT_NUM", "ACTIVE_BILLING_ORDER")
  ;
  CREATE INDEX "TREXONE_DATA"."IN_TP_PATIENT_2" ON "TREXONE_DATA"."TP_PATIENT" ("TP_PATIENT_NUM", "TP_PLAN_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_PATIENT" ADD CONSTRAINT "PK_TP_PATIENT" PRIMARY KEY ("TP_PATIENT_NUM")
  USING INDEX "TREXONE_DATA"."IN_TP_PATIENT_2"  ENABLE;
ALTER TABLE "TREXONE_DATA"."TP_PATIENT" ADD CONSTRAINT "UC_TP_PATIENT_01" UNIQUE ("ACTIVE_PATIENT_NUM", "ACTIVE_BILLING_ORDER")
  USING INDEX "TREXONE_DATA"."IN_TP_PATIENT_08"  ENABLE NOVALIDATE;
-- ==========================================
