-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_PROCESSOR_NOTE"
   (	"TP_PROCESSOR_NOTE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_PROCESSOR_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NOTE_TEXT" VARCHAR2(4000) NOT NULL ENABLE,
	"CREATE_DATE" DATE NOT NULL ENABLE,
	"CREATE_USER" NUMBER(18,0) NOT NULL ENABLE,
	"PRIORITY_INDICATOR" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_19" FOREIGN KEY ("CREATE_USER")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE,
	 CONSTRAINT "FK_TP_PROCESSOR_02" FOREIGN KEY ("TP_PROCESSOR_NUM")
	  REFERENCES "TREXONE_DATA"."TP_PROCESSOR" ("TP_PROCESSOR_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_PROCESSOR_NOTE" ON "TREXONE_DATA"."TP_PROCESSOR_NOTE" ("TP_PROCESSOR_NOTE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_PROCESSOR_NOTE" ADD CONSTRAINT "PK_TP_PROCESSOR_NOTE" PRIMARY KEY ("TP_PROCESSOR_NOTE_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_PROCESSOR_NOTE"  ENABLE;
-- ==========================================
