-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_PRODUCT_INGRED_CODE"
   (	"TP_PRODUCT_INGRED_CODE_NUM" NUMBER(18,0),
	"PRODUCT_INGREDIENT_NUM" NUMBER(18,0),
	"TP_ITEM_CLAIM_NUM" NUMBER(18,0),
	"INGREDIENT_CODE" VARCHAR2(2),
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "PK_TP_PRODUCT_INGRED_CODE" PRIMARY KEY ("TP_PRODUCT_INGRED_CODE_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_PRODUCT_INGREDIENT_06" FOREIGN KEY ("PRODUCT_INGREDIENT_NUM")
	  REFERENCES "TREXONE_DATA"."PRODUCT_INGREDIENT" ("PRODUCT_INGREDIENT_NUM") ENABLE,
	 CONSTRAINT "FK_TP_ITEM_CLAIM_11" FOREIGN KEY ("TP_ITEM_CLAIM_NUM")
	  REFERENCES "TREXONE_DATA"."TP_ITEM_CLAIM" ("TP_ITEM_CLAIM_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) ) ;
-- ==========================================
