-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_PLAN_LINK"
   (	"TP_PLAN_LINK_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_PLAN_NUM" NUMBER(18,0),
	"TP_NETWORK_NUM" NUMBER(18,0),
	"TP_BENEFIT_GROUP_SEQ" NUMBER(18,0),
	"GROUP_EXCLUDE" CHAR(1),
	"IS_ALL_FACILITY_LINK" CHAR(1),
	"NETWORK_EFFECTIVE_DATE" DATE,
	"NETWORK_TERMINATION_DATE" DATE,
	"PLAN_SETUP_CODE" VARCHAR2(12),
	"PUBLISH_STATUS" CHAR(1),
	"TP_BILLING_FORMAT_SET_NUM" NUMBER(18,0),
	"DATA_FILTER_NAME" VARCHAR2(60),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"LINK_TYPE" NUMBER(9,0),
	"EFFECTIVE_DATE" DATE,
	"TERMINATION_DATE" DATE,
	"PRECEDENCE" NUMBER(9,0),
	"TP_PLAN_DESTINATION_NUM" NUMBER(18,0),
	"TP_RULE_SET_NUM" NUMBER(18,0),
	"TP_PLAN_GENERAL_INFO_NUM" NUMBER(18,0),
	"PARENT_TP_PLAN_LINK" NUMBER(18,0),
	"DATA_FILTER" CLOB,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"NCPDP_VERSION" VARCHAR2(2),
	 CONSTRAINT "FK_TP_BENEFIT_GROUP_04" FOREIGN KEY ("TP_PLAN_NUM", "TP_BENEFIT_GROUP_SEQ")
	  REFERENCES "TREXONE_DATA"."TP_BENEFIT_GROUP" ("TP_PLAN_NUM", "TP_BENEFIT_GROUP_SEQ") ENABLE,
	 CONSTRAINT "FK_TP_BILLING_FORMAT_SET_01" FOREIGN KEY ("TP_BILLING_FORMAT_SET_NUM")
	  REFERENCES "TREXONE_DATA"."TP_BILLING_FORMAT_SET" ("TP_BILLING_FORMAT_SET_NUM") ENABLE,
	 CONSTRAINT "FK_TP_NETWORK_05" FOREIGN KEY ("TP_NETWORK_NUM")
	  REFERENCES "TREXONE_DATA"."TP_NETWORK" ("TP_NETWORK_NUM") ENABLE,
	 CONSTRAINT "FK_TP_PLAN_DESTINATION_01" FOREIGN KEY ("TP_PLAN_DESTINATION_NUM")
	  REFERENCES "TREXONE_DATA"."TP_PLAN_DESTINATION" ("TP_PLAN_DESTINATION_NUM") ENABLE,
	 CONSTRAINT "FK_TP_PLAN_GENERAL_INFO_01" FOREIGN KEY ("TP_PLAN_GENERAL_INFO_NUM")
	  REFERENCES "TREXONE_DATA"."TP_PLAN_GENERAL_INFO" ("TP_PLAN_GENERAL_INFO_NUM") ENABLE,
	 CONSTRAINT "FK_TP_PLAN_LINK_01" FOREIGN KEY ("PARENT_TP_PLAN_LINK")
	  REFERENCES "TREXONE_DATA"."TP_PLAN_LINK" ("TP_PLAN_LINK_NUM") ENABLE,
	 CONSTRAINT "FK_TP_RULE_SET_04" FOREIGN KEY ("TP_RULE_SET_NUM")
	  REFERENCES "TREXONE_DATA"."TP_RULE_SET" ("TP_RULE_SET_NUM") ENABLE
   ) ;
  CREATE INDEX "TREXONE_DATA"."PK_TP_PLAN_LINK" ON "TREXONE_DATA"."TP_PLAN_LINK" ("TP_PLAN_LINK_NUM", "PARENT_TP_PLAN_LINK", "LINK_TYPE")
  ;
ALTER TABLE "TREXONE_DATA"."TP_PLAN_LINK" ADD CONSTRAINT "PK_TP_PLAN_LINK" PRIMARY KEY ("TP_PLAN_LINK_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_PLAN_LINK"  ENABLE;
-- ==========================================
