-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_PLAN"
   (	"TP_PLAN_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_AGENCY_TYPE_NUM" NUMBER(18,0),
	"CODE" VARCHAR2(10),
	"NAME" VARCHAR2(45) NOT NULL ENABLE,
	"COMMENT_TEXT" VARCHAR2(255),
	"EFFECTIVE_DATE" DATE,
	"TERMINATION_DATE" DATE,
	"IS_TEST_PLAN" CHAR(1),
	"IS_MEDICAID_PLAN" CHAR(1),
	"IS_MEDICARE_PLAN" CHAR(1),
	"IS_WORKERS_COMP_PLAN" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PRIMARY_INSURANCE_TYPE_CODE" VARCHAR2(3),
	"IS_ALL_STORE_PLAN" CHAR(1),
	"MEDICAID_EDIT_STATE" VARCHAR2(2),
	"ALLOW_CENTRAL_FILL" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE,
	"IS_MEDICARE_FACILITATOR" CHAR(1),
	"FACILITATOR_STATE_CODES" VARCHAR2(256),
	"RUN_MEDICAID_EDITS" CHAR(1),
	"IS_MAIL_ORDER_PLAN" CHAR(1),
	"ALLOW_CENTRAL_MAIL" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"USE_SEPARATE_INVENTORY" CHAR(1),
	"IS_340B" CHAR(1),
	"IS_ASSIGNMENT_ACCEPTED" CHAR(1),
	"FACILITATOR_TYPE" CHAR(1),
	"BILLING_DATE_CODE" CHAR(1),
	"REVERAL_DATE_CODE" CHAR(1),
	"IS_ERP_ALLOWED" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE,
	 CONSTRAINT "FK_TP_AGENCY_TYPE_01" FOREIGN KEY ("TP_AGENCY_TYPE_NUM")
	  REFERENCES "TREXONE_DATA"."TP_AGENCY_TYPE" ("TP_AGENCY_TYPE_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_PLAN" ON "TREXONE_DATA"."TP_PLAN" ("TP_PLAN_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_PLAN" ADD CONSTRAINT "PK_TP_PLAN" PRIMARY KEY ("TP_PLAN_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_PLAN"  ENABLE;
-- ==========================================
