-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_PLAN_GENERAL_INFO"
   (	"TP_PLAN_GENERAL_INFO_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CONTACT_NAME" VARCHAR2(40),
	"INACTIVITY_DEACTIVATION_PERIOD" NUMBER(9,0),
	"FACILITY_PLAN_NUM" VARCHAR2(20),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_PLAN_GENERAL_INFO" ON "TREXONE_DATA"."TP_PLAN_GENERAL_INFO" ("TP_PLAN_GENERAL_INFO_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_PLAN_GENERAL_INFO" ADD CONSTRAINT "PK_TP_PLAN_GENERAL_INFO" PRIMARY KEY ("TP_PLAN_GENERAL_INFO_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_PLAN_GENERAL_INFO"  ENABLE;
-- ==========================================
