-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_PRIOR_AUTH"
   (	"TP_PRIOR_AUTH_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0),
	"TP_PATIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"AUTHORIZATION_NUMBER" VARCHAR2(20),
	"AUTH_TYPE_NUM" NUMBER(9,0),
	"EFFECTIVE_DATE" DATE,
	"EXPIRATION_DATE" DATE,
	"QUANTITY_AUTHORIZED" NUMBER(16,8),
	"DOLLARS_AUTHORIZED" NUMBER(17,6),
	"REFILLS_AUTHORIZED" NUMBER(9,0),
	"PROCESSED_DATE" DATE,
	"QUANTITY_ACCUMULATED" NUMBER(16,8),
	"AUTH_REP_FIRST_NAME" VARCHAR2(30),
	"AUTH_REP_LAST_NAME" VARCHAR2(30),
	"DOCUMENTATION" VARCHAR2(500),
	"REQUEST_TYPE" CHAR(1),
	"REQUEST_PERIOD_BEGIN_DATE" DATE,
	"REQUEST_PERIOD_END_DATE" DATE,
	"BASIS_OF_REQUEST" VARCHAR2(2),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"DOLLARS_ACCUMULATED" NUMBER(17,6),
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"REFILLS_ACCUMULATED" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_RX_11" FOREIGN KEY ("RX_RECORD_NUM")
	  REFERENCES "TREXONE_DATA"."RX_BASE" ("RX_RECORD_NUM") ENABLE,
	 CONSTRAINT "FK_TP_PATIENT_02" FOREIGN KEY ("TP_PATIENT_NUM")
	  REFERENCES "TREXONE_DATA"."TP_PATIENT" ("TP_PATIENT_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_PRIOR_AUTH" ON "TREXONE_DATA"."TP_PRIOR_AUTH" ("TP_PRIOR_AUTH_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_PRIOR_AUTH" ADD CONSTRAINT "PK_TP_PRIOR_AUTH" PRIMARY KEY ("TP_PRIOR_AUTH_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_PRIOR_AUTH"  ENABLE;
-- ==========================================
