-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_PLAN_DESTINATION"
   (	"TP_PLAN_DESTINATION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_PROCESSOR_NUM" NUMBER(18,0),
	"TP_PROCESSOR_DESTINATION_SEQ" NUMBER(18,0),
	"NAME" VARCHAR2(40),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_TP_PROCESSOR_DESTINATION_04" FOREIGN KEY ("TP_PROCESSOR_NUM", "TP_PROCESSOR_DESTINATION_SEQ")
	  REFERENCES "TREXONE_DATA"."TP_PROCESSOR_DESTINATION" ("TP_PROCESSOR_NUM", "TP_PROCESSOR_DESTINATION_SEQ") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_PLAN_DESTINATION" ON "TREXONE_DATA"."TP_PLAN_DESTINATION" ("TP_PLAN_DESTINATION_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_PLAN_DESTINATION" ADD CONSTRAINT "PK_TP_PLAN_DESTINATION" PRIMARY KEY ("TP_PLAN_DESTINATION_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_PLAN_DESTINATION"  ENABLE;
-- ==========================================
