-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_REJECT_CODE"
   (	"TP_REJECT_CODE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"REJECT_CODE" VARCHAR2(8),
	"MESSAGE" VARCHAR2(100),
	"IS_CUSTOM_CODE" CHAR(1) NOT NULL ENABLE,
	"IS_DOWNTIME_CODE" CHAR(1) NOT NULL ENABLE,
	"IS_DUPLICATE_CODE" CHAR(1) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_REJECT_CODE" ON "TREXONE_DATA"."TP_REJECT_CODE" ("TP_REJECT_CODE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_REJECT_CODE" ADD CONSTRAINT "PK_TP_REJECT_CODE" PRIMARY KEY ("TP_REJECT_CODE_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_REJECT_CODE"  ENABLE;
-- ==========================================
