-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_SPECIFIC_DIAGNOSIS_CODE"
   (	"TP_SPECIFIC_DIAGNOSIS_CODE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_RULE_SET_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"MEDICAL_CONDITION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PLAN_SPECIFIC_CODE" VARCHAR2(45) NOT NULL ENABLE,
	"PLAN_SPECIFIC_DESC" VARCHAR2(255) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_MEDICAL_CONDITION_XREF_04" FOREIGN KEY ("MEDICAL_CONDITION_NUM")
	  REFERENCES "TREXONE_DATA"."MEDICAL_CONDITION_XREF" ("MEDICAL_CONDITION_NUM") ENABLE,
	 CONSTRAINT "FK_TP_RULE_SET_08" FOREIGN KEY ("TP_RULE_SET_NUM")
	  REFERENCES "TREXONE_DATA"."TP_RULE_SET" ("TP_RULE_SET_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_SPECIFIC_DIAGNOSIS_CODE" ON "TREXONE_DATA"."TP_SPECIFIC_DIAGNOSIS_CODE" ("TP_SPECIFIC_DIAGNOSIS_CODE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_SPECIFIC_DIAGNOSIS_CODE" ADD CONSTRAINT "PK_TP_SPECIFIC_DIAGNOSIS_CODE" PRIMARY KEY ("TP_SPECIFIC_DIAGNOSIS_CODE_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_SPECIFIC_DIAGNOSIS_CODE"  ENABLE;
-- ==========================================
