-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_SIM_ITEM_MESSAGE"
   (	"TP_SIM_ITEM_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_SIM_MESSAGE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"MESSAGE_CODE" VARCHAR2(100),
	"MESSAGE_TEXT" VARCHAR2(1000),
	"WARN_LEV" NUMBER(18,0),
	"MESSAGE_SOURCE" VARCHAR2(100),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_TP_SIM_MESSAGE_01" FOREIGN KEY ("TP_SIM_MESSAGE_NUM")
	  REFERENCES "TREXONE_DATA"."TP_SIM_MESSAGE" ("TP_SIM_MESSAGE_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_SIM_ITEM_MESSAGE" ON "TREXONE_DATA"."TP_SIM_ITEM_MESSAGE" ("TP_SIM_ITEM_MESSAGE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_SIM_ITEM_MESSAGE" ADD CONSTRAINT "PK_TP_SIM_ITEM_MESSAGE" PRIMARY KEY ("TP_SIM_ITEM_MESSAGE_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_SIM_ITEM_MESSAGE"  ENABLE;
-- ==========================================
