-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_STANDARD_CODE"
   (	"TP_STANDARD_CODE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FIELD_ID" NUMBER(9,0) NOT NULL ENABLE,
	"CODE" VARCHAR2(4) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(100),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_STANDARD_CODE" ON "TREXONE_DATA"."TP_STANDARD_CODE" ("TP_STANDARD_CODE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_STANDARD_CODE" ADD CONSTRAINT "PK_TP_STANDARD_CODE" PRIMARY KEY ("TP_STANDARD_CODE_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_STANDARD_CODE"  ENABLE;
-- ==========================================
