-- ==========================================

  CREATE TABLE "TREXONE_DATA"."TP_WORKERS_COMP_CONDITION"
   (	"TP_WORKERS_COMP_CONDITION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TP_WORKERS_COMP_CLAIM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PATIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PATIENT_MED_CONDITION_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PATIENT_MED_CONDITION_02" FOREIGN KEY ("PATIENT_NUM", "PATIENT_MED_CONDITION_SEQ")
	  REFERENCES "TREXONE_DATA"."PATIENT_MED_CONDITION" ("PATIENT_NUM", "PATIENT_MED_CONDITION_SEQ") ENABLE,
	 CONSTRAINT "FK_TP_WORKERS_COMP_CLAIM_03" FOREIGN KEY ("TP_WORKERS_COMP_CLAIM_NUM")
	  REFERENCES "TREXONE_DATA"."TP_WORKERS_COMP_CLAIM" ("TP_WORKERS_COMP_CLAIM_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_TP_WORKERS_COMP_CONDITION" ON "TREXONE_DATA"."TP_WORKERS_COMP_CONDITION" ("TP_WORKERS_COMP_CONDITION_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."TP_WORKERS_COMP_CONDITION" ADD CONSTRAINT "PK_TP_WORKERS_COMP_CONDITION" PRIMARY KEY ("TP_WORKERS_COMP_CONDITION_NUM")
  USING INDEX "TREXONE_DATA"."PK_TP_WORKERS_COMP_CONDITION"  ENABLE;
-- ==========================================
