-- ==========================================

  CREATE TABLE "TREXONE_DATA"."URL_LINK"
   (	"URL_LINK_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"OWNER" NUMBER(18,0) NOT NULL ENABLE,
	"OWNER_TYPE_CODE" CHAR(1) NOT NULL ENABLE,
	"USAGE" NUMBER(18,0) NOT NULL ENABLE,
	"URL_NUM" NUMBER(18,0),
	"URL_USAGE" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"NOTIFY_PATIENT" CHAR(1) DEFAULT 'N',
	 CONSTRAINT "FK_OWNER_TYPE_04" FOREIGN KEY ("OWNER_TYPE_CODE")
	  REFERENCES "TREXONE_DATA"."OWNER_TYPE" ("OWNER_TYPE_CODE") ENABLE,
	 CONSTRAINT "FK_URL_01" FOREIGN KEY ("URL_NUM")
	  REFERENCES "TREXONE_DATA"."URL" ("URL_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_URL_LINK" ON "TREXONE_DATA"."URL_LINK" ("URL_LINK_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."URL_LINK" ADD CONSTRAINT "PK_URL_LINK" PRIMARY KEY ("URL_LINK_NUM")
  USING INDEX "TREXONE_DATA"."PK_URL_LINK"  ENABLE;
-- ==========================================
