-- ==========================================

  CREATE TABLE "TREXONE_DATA"."USER_DATA_VIEW"
   (	"USER_DATA_VIEW_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"SYSTEM_USER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"IS_LOGIN_VIEW" CHAR(1) NOT NULL ENABLE,
	"IS_DEFAULT_VIEW" CHAR(1) NOT NULL ENABLE,
	"IS_PRIVATE_DEFAULT_VIEW" CHAR(1) NOT NULL ENABLE,
	"IS_EXTENDED_VIEW" CHAR(1) NOT NULL ENABLE,
	"IS_PRIVATE_EXTENDED_VIEW" CHAR(1) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_FACILITY_49" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_20" FOREIGN KEY ("SYSTEM_USER_NUM")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_USER_DATA_VIEW" ON "TREXONE_DATA"."USER_DATA_VIEW" ("USER_DATA_VIEW_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."USER_DATA_VIEW" ADD CONSTRAINT "PK_USER_DATA_VIEW" PRIMARY KEY ("USER_DATA_VIEW_NUM")
  USING INDEX "TREXONE_DATA"."PK_USER_DATA_VIEW"  ENABLE;
-- ==========================================
