-- ==========================================

  CREATE TABLE "TREXONE_DATA"."VENDOR_COMM_METHOD_PARAMETER"
   (	"VENDOR_COMM_METHOD_PARAM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(30) NOT NULL ENABLE,
	"DISPLAY_NAME" VARCHAR2(50),
	"DATA_TYPE" NUMBER(9,0) NOT NULL ENABLE,
	"MAXIMUM_LENGTH" NUMBER(9,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"VENDOR_COMM_METHOD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_VENDOR_COMM_METH_01" FOREIGN KEY ("VENDOR_COMM_METHOD_NUM")
	  REFERENCES "TREXONE_DATA"."VENDOR_COMMUNICATION_METHOD" ("VENDOR_COMM_METHOD_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PKVENDOR_COMM_METHOD_PARAMETER" ON "TREXONE_DATA"."VENDOR_COMM_METHOD_PARAMETER" ("VENDOR_COMM_METHOD_PARAM_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."VENDOR_COMM_METHOD_PARAMETER" ADD CONSTRAINT "PKVENDOR_COMM_METHOD_PARAMETER" PRIMARY KEY ("VENDOR_COMM_METHOD_PARAM_NUM")
  USING INDEX "TREXONE_DATA"."PKVENDOR_COMM_METHOD_PARAMETER"  ENABLE;
-- ==========================================
