-- ==========================================

  CREATE TABLE "TREXONE_DATA"."VENDOR_ITEM_RANK"
   (	"VENDOR_ITEM_RANK_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"INVENTORY_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"VENDOR_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RANK" NUMBER(9,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_INVENTORY_ITEM_07" FOREIGN KEY ("INVENTORY_ITEM_NUM")
	  REFERENCES "TREXONE_DATA"."INVENTORY_ITEM" ("INVENTORY_ITEM_NUM") ENABLE,
	 CONSTRAINT "FK_VENDOR_12" FOREIGN KEY ("VENDOR_NUM")
	  REFERENCES "TREXONE_DATA"."VENDOR" ("VENDOR_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."UC_VENDOR_ITEM_RANK_02" ON "TREXONE_DATA"."VENDOR_ITEM_RANK" ("VENDOR_NUM", "INVENTORY_ITEM_NUM", "ERX_CLIENT_ID")
  ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PKVENDOR_ITEM_RANK" ON "TREXONE_DATA"."VENDOR_ITEM_RANK" ("VENDOR_ITEM_RANK_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."VENDOR_ITEM_RANK" ADD CONSTRAINT "PKVENDOR_ITEM_RANK" PRIMARY KEY ("VENDOR_ITEM_RANK_NUM")
  USING INDEX "TREXONE_DATA"."PKVENDOR_ITEM_RANK"  ENABLE;
ALTER TABLE "TREXONE_DATA"."VENDOR_ITEM_RANK" ADD CONSTRAINT "UC_VENDOR_ITEM_RANK_02" UNIQUE ("VENDOR_NUM", "INVENTORY_ITEM_NUM", "ERX_CLIENT_ID")
  USING INDEX "TREXONE_DATA"."UC_VENDOR_ITEM_RANK_02"  ENABLE NOVALIDATE;
-- ==========================================
