-- ==========================================

  CREATE TABLE "TREXONE_DATA"."VENDOR_CONTACT"
   (	"VENDOR_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"VENDOR_CONTACT_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"VENDOR_ADDRESS_SEQ" NUMBER(18,0),
	"CONTACT_NAME" VARCHAR2(25),
	"CONTACT_EMAIL" VARCHAR2(25),
	"PREFERRED_CONTACT_TYPE" VARCHAR2(30),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_VENDOR_04" FOREIGN KEY ("VENDOR_NUM")
	  REFERENCES "TREXONE_DATA"."VENDOR" ("VENDOR_NUM") ENABLE,
	 CONSTRAINT "FK_VENDOR_ADDRESS_02" FOREIGN KEY ("VENDOR_NUM", "VENDOR_ADDRESS_SEQ")
	  REFERENCES "TREXONE_DATA"."VENDOR_ADDRESS" ("VENDOR_NUM", "VENDOR_ADDRESS_SEQ") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_VENDOR_CONTACT" ON "TREXONE_DATA"."VENDOR_CONTACT" ("VENDOR_NUM", "VENDOR_CONTACT_SEQ")
  ;
ALTER TABLE "TREXONE_DATA"."VENDOR_CONTACT" ADD CONSTRAINT "PK_VENDOR_CONTACT" PRIMARY KEY ("VENDOR_NUM", "VENDOR_CONTACT_SEQ")
  USING INDEX "TREXONE_DATA"."PK_VENDOR_CONTACT"  ENABLE;
-- ==========================================
