-- ==========================================

  CREATE TABLE "TREXONE_DATA"."VENDOR_COMM_PARAM_VALUE"
   (	"VENDOR_COMM_PARAM_VALUE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"VENDOR_CONFIGURATION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"VENDOR_COMM_METHOD_PARAM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"VALUE" VARCHAR2(1000) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_VENDOR_COMM_METH_PARAM_01" FOREIGN KEY ("VENDOR_COMM_METHOD_PARAM_NUM")
	  REFERENCES "TREXONE_DATA"."VENDOR_COMM_METHOD_PARAMETER" ("VENDOR_COMM_METHOD_PARAM_NUM") ENABLE,
	 CONSTRAINT "FK_VENDOR_CONFIGURATION_01" FOREIGN KEY ("VENDOR_CONFIGURATION_NUM")
	  REFERENCES "TREXONE_DATA"."VENDOR_CONFIGURATION" ("VENDOR_CONFIGURATION_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PKVENDOR_COMM_PARAM_VALUE" ON "TREXONE_DATA"."VENDOR_COMM_PARAM_VALUE" ("VENDOR_COMM_PARAM_VALUE_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."VENDOR_COMM_PARAM_VALUE" ADD CONSTRAINT "PKVENDOR_COMM_PARAM_VALUE" PRIMARY KEY ("VENDOR_COMM_PARAM_VALUE_NUM")
  USING INDEX "TREXONE_DATA"."PKVENDOR_COMM_PARAM_VALUE"  ENABLE;
-- ==========================================
