-- ==========================================

  CREATE TABLE "TREXONE_DATA"."VENDOR_INVENTORY_ITEM"
   (	"VENDOR_INVENTORY_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"VENDOR_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"INVENTORY_ITEM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ITEM_ID_NUMBER" VARCHAR2(48) NOT NULL ENABLE,
	"PRIORITY" NUMBER(9,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_INVENTORY_ITEM_06" FOREIGN KEY ("INVENTORY_ITEM_NUM")
	  REFERENCES "TREXONE_DATA"."INVENTORY_ITEM" ("INVENTORY_ITEM_NUM") ENABLE,
	 CONSTRAINT "FK_VENDOR_06" FOREIGN KEY ("VENDOR_NUM")
	  REFERENCES "TREXONE_DATA"."VENDOR" ("VENDOR_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_VENDOR_INVENTORY_ITEM" ON "TREXONE_DATA"."VENDOR_INVENTORY_ITEM" ("VENDOR_INVENTORY_ITEM_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."VENDOR_INVENTORY_ITEM" ADD CONSTRAINT "PK_VENDOR_INVENTORY_ITEM" PRIMARY KEY ("VENDOR_INVENTORY_ITEM_NUM")
  USING INDEX "TREXONE_DATA"."PK_VENDOR_INVENTORY_ITEM"  ENABLE;
-- ==========================================
