-- ==========================================

  CREATE TABLE "TREXONE_DATA"."VENDOR"
   (	"VENDOR_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"VENDOR_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"IS_ACTIVE" CHAR(1),
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PRIORITY" NUMBER(18,0),
	"DEFAULT_ITEM_PRIORITY" NUMBER(18,0),
	"MAIN_ADDRESS_SEQ" NUMBER(18,0),
	"DISCOUNT_DAY_OF_MONTH" NUMBER(9,0),
	"FACTOR_OFF_RETAIL_PRICE" NUMBER(16,8),
	"DISCOUNT_NET_DAYS" NUMBER(9,0),
	"ACCOUNT_NUMBER" VARCHAR2(16),
	"DESTINATION_NUM" NUMBER(18,0),
	"RECEIVER_ID" VARCHAR2(16),
	"FIXED_AMOUNT_DISCOUNT" NUMBER(16,8),
	"PERCENTAGE_DISCOUNT" NUMBER(16,8),
	"DISCOUNT_NET_DAYS_TYPE" CHAR(1),
	"EDI_FIELD_SEPARATOR" CHAR(1),
	"EDI_RECORD_SEPARATOR" CHAR(1),
	"EDI_CONTROL_NUMBER" VARCHAR2(15),
	"VENDOR_COMM_METHOD_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"IS_MCK_CONNECT_ENABLED" CHAR(1),
	"SGLN" VARCHAR2(50),
	 CONSTRAINT "FK_DESTINATION_01" FOREIGN KEY ("DESTINATION_NUM")
	  REFERENCES "TREXONE_DATA"."DESTINATION" ("DESTINATION_NUM") ENABLE,
	 CONSTRAINT "FK_VENDOR_ADDRESS_01" FOREIGN KEY ("VENDOR_NUM", "MAIN_ADDRESS_SEQ")
	  REFERENCES "TREXONE_DATA"."VENDOR_ADDRESS" ("VENDOR_NUM", "VENDOR_ADDRESS_SEQ") ENABLE,
	 CONSTRAINT "FK_VENDOR_COMM_METHOD_02" FOREIGN KEY ("VENDOR_COMM_METHOD_NUM")
	  REFERENCES "TREXONE_DATA"."VENDOR_COMMUNICATION_METHOD" ("VENDOR_COMM_METHOD_NUM") ENABLE
   ) ;
  CREATE INDEX "TREXONE_DATA"."PK_VENDOR" ON "TREXONE_DATA"."VENDOR" ("VENDOR_NUM", "MAIN_ADDRESS_SEQ")
  ;
ALTER TABLE "TREXONE_DATA"."VENDOR" ADD CONSTRAINT "PK_VENDOR" PRIMARY KEY ("VENDOR_NUM")
  USING INDEX "TREXONE_DATA"."PK_VENDOR"  ENABLE;
-- ==========================================
