-- ==========================================

  CREATE TABLE "TREXONE_DATA"."VENDOR_EDI_TRANSACTION"
   (	"VENDOR_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"EDI_VERSION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"EDI_TRANSACTION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_VENDOR_11" FOREIGN KEY ("VENDOR_NUM")
	  REFERENCES "TREXONE_DATA"."VENDOR" ("VENDOR_NUM") ENABLE,
	 CONSTRAINT "FK_VENDOR_EDI_TRANSACTION_01" FOREIGN KEY ("EDI_VERSION_NUM", "EDI_TRANSACTION_NUM")
	  REFERENCES "TREXONE_DATA"."EDI_VERSION_TXN" ("EDI_VERSION_NUM", "EDI_TRANSACTION_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PKVENDOR_EDI_TRANSACTION" ON "TREXONE_DATA"."VENDOR_EDI_TRANSACTION" ("VENDOR_NUM", "EDI_VERSION_NUM", "EDI_TRANSACTION_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."VENDOR_EDI_TRANSACTION" ADD CONSTRAINT "PKVENDOR_EDI_TRANSACTION" PRIMARY KEY ("VENDOR_NUM", "EDI_VERSION_NUM", "EDI_TRANSACTION_NUM")
  USING INDEX "TREXONE_DATA"."PKVENDOR_EDI_TRANSACTION"  ENABLE;
-- ==========================================
