-- ==========================================

  CREATE TABLE "TREXONE_DATA"."VENDOR_ADDRESS"
   (	"VENDOR_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"VENDOR_ADDRESS_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"ADDRESS1" VARCHAR2(40),
	"ADDRESS2" VARCHAR2(40),
	"CITY" VARCHAR2(40),
	"STATE_CODE" VARCHAR2(2),
	"ZIP" VARCHAR2(10),
	"CTRY_CODE" VARCHAR2(8),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_STATE_09" FOREIGN KEY ("CTRY_CODE", "STATE_CODE")
	  REFERENCES "TREXONE_DATA"."STATE" ("CTRY_CODE", "STATE_CODE") ENABLE,
	 CONSTRAINT "FK_VENDOR_03" FOREIGN KEY ("VENDOR_NUM")
	  REFERENCES "TREXONE_DATA"."VENDOR" ("VENDOR_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_VENDOR_ADDRESS" ON "TREXONE_DATA"."VENDOR_ADDRESS" ("VENDOR_NUM", "VENDOR_ADDRESS_SEQ")
  ;
ALTER TABLE "TREXONE_DATA"."VENDOR_ADDRESS" ADD CONSTRAINT "PK_VENDOR_ADDRESS" PRIMARY KEY ("VENDOR_NUM", "VENDOR_ADDRESS_SEQ")
  USING INDEX "TREXONE_DATA"."PK_VENDOR_ADDRESS"  ENABLE;
-- ==========================================
