-- ==========================================

  CREATE TABLE "TREXONE_DATA"."VENDOR_CONTACT_PHONE"
   (	"VENDOR_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"VENDOR_CONTACT_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"CONTACT_PHONE_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"PHONE_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"AREA_CODE" VARCHAR2(3),
	"PHONE_NUM" VARCHAR2(7),
	"PHONE_EXT" VARCHAR2(5),
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_PHONE_TYPE_02" FOREIGN KEY ("PHONE_TYPE_NUM")
	  REFERENCES "TREXONE_DATA"."PHONE_TYPE" ("PHONE_TYPE_NUM") ENABLE,
	 CONSTRAINT "FK_VENDOR_CONTACT_03" FOREIGN KEY ("VENDOR_NUM", "VENDOR_CONTACT_SEQ")
	  REFERENCES "TREXONE_DATA"."VENDOR_CONTACT" ("VENDOR_NUM", "VENDOR_CONTACT_SEQ") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_VENDOR_CONTACT_PHONE" ON "TREXONE_DATA"."VENDOR_CONTACT_PHONE" ("VENDOR_NUM", "VENDOR_CONTACT_SEQ", "CONTACT_PHONE_SEQ")
  ;
ALTER TABLE "TREXONE_DATA"."VENDOR_CONTACT_PHONE" ADD CONSTRAINT "PK_VENDOR_CONTACT_PHONE" PRIMARY KEY ("VENDOR_NUM", "VENDOR_CONTACT_SEQ", "CONTACT_PHONE_SEQ")
  USING INDEX "TREXONE_DATA"."PK_VENDOR_CONTACT_PHONE"  ENABLE;
-- ==========================================
