-- ==========================================

  CREATE TABLE "TREXONE_DATA"."VISIBLE_FACILITY"
   (	"LOGIN_SCHEMA" VARCHAR2(30) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_FACILITY_74" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE
   ) ;
-- ==========================================
