-- ==========================================

  CREATE TABLE "TREXONE_DATA"."VISIBLE_SCHEMA_CLASS"
   (	"LOGIN_SCHEMA" VARCHAR2(30) NOT NULL ENABLE,
	"SCHEMA_CLASSIFICATION" VARCHAR2(30) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_VISIBLE_SCHEMA_CLASS" ON "TREXONE_DATA"."VISIBLE_SCHEMA_CLASS" ("LOGIN_SCHEMA", "SCHEMA_CLASSIFICATION")
  ;
ALTER TABLE "TREXONE_DATA"."VISIBLE_SCHEMA_CLASS" ADD CONSTRAINT "PK_VISIBLE_SCHEMA_CLASS" PRIMARY KEY ("LOGIN_SCHEMA", "SCHEMA_CLASSIFICATION")
  USING INDEX "TREXONE_DATA"."PK_VISIBLE_SCHEMA_CLASS"  ENABLE;
-- ==========================================
