-- ==========================================

  CREATE TABLE "TREXONE_DATA"."WEB_ORDER"
   (	"WEB_ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ELECTRONIC_ORDER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CUST_WEB_ORDER" VARCHAR2(12) NOT NULL ENABLE,
	"CUST_PHONE" VARCHAR2(12) NOT NULL ENABLE,
	"PICKUP_DATE" DATE NOT NULL ENABLE,
	"COMMENTS" VARCHAR2(256),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"TRANSFER_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_ELECTRONIC_ORDER_03" FOREIGN KEY ("ELECTRONIC_ORDER_NUM")
	  REFERENCES "TREXONE_DATA"."ELECTRONIC_ORDER" ("ELECTRONIC_ORDER_NUM") ENABLE,
	 CONSTRAINT "FK_FACILITY_50" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE,
	 CONSTRAINT "FK_FACILITY_90" FOREIGN KEY ("TRANSFER_FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_WEB_ORDER" ON "TREXONE_DATA"."WEB_ORDER" ("WEB_ORDER_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."WEB_ORDER" ADD CONSTRAINT "PK_WEB_ORDER" PRIMARY KEY ("WEB_ORDER_NUM")
  USING INDEX "TREXONE_DATA"."PK_WEB_ORDER"  ENABLE;
-- ==========================================
