-- ==========================================

  CREATE TABLE "TREXONE_DATA"."WF_CENTRAL_FILL_DECLINE"
   (	"WF_PROCESS_DEFINITION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PROC_INST_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"FACILITY_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"TYPE" CHAR(1),
	"RESTOCK_PRODUCT_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	"RESTOCK_QUANTITY" NUMBER(13,3),
	 CONSTRAINT "FK_WF_PROCESS_INSTANCE_07" FOREIGN KEY ("WF_PROCESS_DEFINITION_NUM", "PROC_INST_SEQ")
	  REFERENCES "TREXONE_DATA"."WF_PROCESS_INSTANCE" ("WF_PROCESS_DEFINITION_NUM", "PROC_INST_SEQ") ENABLE,
	 CONSTRAINT "FK_FACILITY_69" FOREIGN KEY ("FACILITY_NUM")
	  REFERENCES "TREXONE_DATA"."FACILITY" ("FACILITY_NUM") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_WF_CENTRAL_FILL_DECLINE" ON "TREXONE_DATA"."WF_CENTRAL_FILL_DECLINE" ("WF_PROCESS_DEFINITION_NUM", "PROC_INST_SEQ", "FACILITY_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."WF_CENTRAL_FILL_DECLINE" ADD CONSTRAINT "PK_WF_CENTRAL_FILL_DECLINE" PRIMARY KEY ("WF_PROCESS_DEFINITION_NUM", "PROC_INST_SEQ", "FACILITY_NUM")
  USING INDEX "TREXONE_DATA"."PK_WF_CENTRAL_FILL_DECLINE"  ENABLE;
-- ==========================================
