-- ==========================================

  CREATE TABLE "TREXONE_DATA"."WF_FIELD_MAP"
   (	"FIELD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FIELD_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"TABLE_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"COLUMN_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"DATA_TYPE" VARCHAR2(10) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_WF_FIELD_MAP" ON "TREXONE_DATA"."WF_FIELD_MAP" ("FIELD_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."WF_FIELD_MAP" ADD CONSTRAINT "PK_WF_FIELD_MAP" PRIMARY KEY ("FIELD_NUM")
  USING INDEX "TREXONE_DATA"."PK_WF_FIELD_MAP"  ENABLE;
-- ==========================================
