-- ==========================================

  CREATE TABLE "TREXONE_DATA"."WF_NODE_ACTION"
   (	"WF_PROCESS_DEFINITION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NODE_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"NODE_ACTION_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"NODE_STATE" VARCHAR2(30),
	"RELATIVE_EXEC_SEQUENCE" NUMBER(18,0),
	"WF_ACTION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_WF_ACTION_02" FOREIGN KEY ("WF_ACTION_NUM")
	  REFERENCES "TREXONE_DATA"."WF_ACTION" ("WF_ACTION_NUM") ENABLE,
	 CONSTRAINT "FK_WF_NODE_DEFINITION_02" FOREIGN KEY ("WF_PROCESS_DEFINITION_NUM", "NODE_SEQ")
	  REFERENCES "TREXONE_DATA"."WF_NODE_DEFINITION" ("WF_PROCESS_DEFINITION_NUM", "NODE_SEQ") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_WF_NODE_ACTION" ON "TREXONE_DATA"."WF_NODE_ACTION" ("WF_PROCESS_DEFINITION_NUM", "NODE_SEQ", "NODE_ACTION_SEQ")
  ;
ALTER TABLE "TREXONE_DATA"."WF_NODE_ACTION" ADD CONSTRAINT "PK_WF_NODE_ACTION" PRIMARY KEY ("WF_PROCESS_DEFINITION_NUM", "NODE_SEQ", "NODE_ACTION_SEQ")
  USING INDEX "TREXONE_DATA"."PK_WF_NODE_ACTION"  ENABLE;
-- ==========================================
