-- ==========================================

  CREATE TABLE "TREXONE_DATA"."WF_NODE_DEFINITION"
   (	"WF_PROCESS_DEFINITION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NODE_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"WF_BLOCK_DEFINITION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TYPE_CODE" VARCHAR2(30),
	"SHORT_CODE" VARCHAR2(30),
	"DESCRIPTION" VARCHAR2(60) NOT NULL ENABLE,
	"COMMENT_TEXT" VARCHAR2(255),
	"DECISION_CLASS" VARCHAR2(255),
	"DATESTAMP" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_WF_BLOCK_DEFINITION_01" FOREIGN KEY ("WF_BLOCK_DEFINITION_NUM")
	  REFERENCES "TREXONE_DATA"."WF_BLOCK_DEFINITION" ("WF_BLOCK_DEFINITION_NUM") ENABLE,
	 CONSTRAINT "FK_WF_PROCESS_DEFINITION_02" FOREIGN KEY ("WF_PROCESS_DEFINITION_NUM")
	  REFERENCES "TREXONE_DATA"."WF_PROCESS_DEFINITION" ("WF_PROCESS_DEFINITION_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_WF_NODE_DEFINITION" ON "TREXONE_DATA"."WF_NODE_DEFINITION" ("WF_PROCESS_DEFINITION_NUM", "NODE_SEQ")
  ;
ALTER TABLE "TREXONE_DATA"."WF_NODE_DEFINITION" ADD CONSTRAINT "PK_WF_NODE_DEFINITION" PRIMARY KEY ("WF_PROCESS_DEFINITION_NUM", "NODE_SEQ")
  USING INDEX "TREXONE_DATA"."PK_WF_NODE_DEFINITION"  ENABLE;
-- ==========================================
