-- ==========================================

  CREATE TABLE "TREXONE_DATA"."WF_PROCESS_NOTE"
   (	"WF_PROCESS_DEFINITION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PROC_INST_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"PROC_NOTE_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"WF_BLOCK_DEFINITION_NUM" NUMBER(18,0),
	"IS_ERROR" CHAR(1),
	"NOTE_TEXT" VARCHAR2(4000) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_WF_BLOCK_DEFINITION_02" FOREIGN KEY ("WF_BLOCK_DEFINITION_NUM")
	  REFERENCES "TREXONE_DATA"."WF_BLOCK_DEFINITION" ("WF_BLOCK_DEFINITION_NUM") ENABLE,
	 CONSTRAINT "FK_WF_PROCESS_INSTANCE_03" FOREIGN KEY ("WF_PROCESS_DEFINITION_NUM", "PROC_INST_SEQ")
	  REFERENCES "TREXONE_DATA"."WF_PROCESS_INSTANCE" ("WF_PROCESS_DEFINITION_NUM", "PROC_INST_SEQ") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_WF_PROCESS_NOTE" ON "TREXONE_DATA"."WF_PROCESS_NOTE" ("WF_PROCESS_DEFINITION_NUM", "PROC_INST_SEQ", "PROC_NOTE_SEQ")
  ;
ALTER TABLE "TREXONE_DATA"."WF_PROCESS_NOTE" ADD CONSTRAINT "PK_WF_PROCESS_NOTE" PRIMARY KEY ("WF_PROCESS_DEFINITION_NUM", "PROC_INST_SEQ", "PROC_NOTE_SEQ")
  USING INDEX "TREXONE_DATA"."PK_WF_PROCESS_NOTE"  ENABLE;
-- ==========================================
