-- ==========================================

  CREATE TABLE "TREXONE_DATA"."WF_QUEUE_FILTER"
   (	"WF_QUEUE_DEFINITION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"QUEUE_FIELD_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"QUEUE_FILTER_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"SYSTEM_USER_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"OPERATOR" NUMBER(18,0),
	"VALUE" VARCHAR2(30),
	"DATESTAMP" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_SYSTEM_USER_23" FOREIGN KEY ("SYSTEM_USER_NUM")
	  REFERENCES "TREXONE_DATA"."SYSTEM_USER" ("SYSTEM_USER_NUM") ENABLE,
	 CONSTRAINT "FK_WF_QUEUE_FIELD_02" FOREIGN KEY ("WF_QUEUE_DEFINITION_NUM", "QUEUE_FIELD_SEQ")
	  REFERENCES "TREXONE_DATA"."WF_QUEUE_FIELD" ("WF_QUEUE_DEFINITION_NUM", "QUEUE_FIELD_SEQ") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_WF_QUEUE_FILTER" ON "TREXONE_DATA"."WF_QUEUE_FILTER" ("WF_QUEUE_DEFINITION_NUM", "QUEUE_FIELD_SEQ", "QUEUE_FILTER_SEQ")
  ;
ALTER TABLE "TREXONE_DATA"."WF_QUEUE_FILTER" ADD CONSTRAINT "PK_WF_QUEUE_FILTER" PRIMARY KEY ("WF_QUEUE_DEFINITION_NUM", "QUEUE_FIELD_SEQ", "QUEUE_FILTER_SEQ")
  USING INDEX "TREXONE_DATA"."PK_WF_QUEUE_FILTER"  ENABLE;
-- ==========================================
