-- ==========================================

  CREATE TABLE "TREXONE_DATA"."WF_QUEUE_THRESHOLD"
   (	"WF_QUEUE_THRESHOLD_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"WF_QUEUE_DEFINITION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"DATA_GROUP" NUMBER(18,0) NOT NULL ENABLE,
	"CRITICAL_THRESHOLD" NUMBER(9,0),
	"CAUTION_THRESHOLD" NUMBER(9,0),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_DATA_GROUP_14" FOREIGN KEY ("DATA_GROUP")
	  REFERENCES "TREXONE_DATA"."DATA_GROUP" ("DATA_GROUP") ENABLE,
	 CONSTRAINT "FK_WF_QUEUE_DEFINITION_05" FOREIGN KEY ("WF_QUEUE_DEFINITION_NUM")
	  REFERENCES "TREXONE_DATA"."WF_QUEUE_DEFINITION" ("WF_QUEUE_DEFINITION_NUM") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_WF_QUEUE_THRESHOLD" ON "TREXONE_DATA"."WF_QUEUE_THRESHOLD" ("WF_QUEUE_THRESHOLD_NUM")
  ;
ALTER TABLE "TREXONE_DATA"."WF_QUEUE_THRESHOLD" ADD CONSTRAINT "PK_WF_QUEUE_THRESHOLD" PRIMARY KEY ("WF_QUEUE_THRESHOLD_NUM")
  USING INDEX "TREXONE_DATA"."PK_WF_QUEUE_THRESHOLD"  ENABLE;
-- ==========================================
