-- ==========================================

  CREATE TABLE "TREXONE_DATA"."WF_TRANSITION"
   (	"FROM_WF_PROCESS_DEFINITION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"FROM_NODE_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"TO_WF_PROCESS_DEFINITION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"TO_NODE_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"DECISION_VALUE" NUMBER(18,0),
	"DATESTAMP" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_WF_NODE_DEFINITION_03" FOREIGN KEY ("TO_WF_PROCESS_DEFINITION_NUM", "TO_NODE_SEQ")
	  REFERENCES "TREXONE_DATA"."WF_NODE_DEFINITION" ("WF_PROCESS_DEFINITION_NUM", "NODE_SEQ") ENABLE,
	 CONSTRAINT "FK_WF_NODE_DEFINITION_04" FOREIGN KEY ("FROM_WF_PROCESS_DEFINITION_NUM", "FROM_NODE_SEQ")
	  REFERENCES "TREXONE_DATA"."WF_NODE_DEFINITION" ("WF_PROCESS_DEFINITION_NUM", "NODE_SEQ") ENABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_WF_TRANSITION" ON "TREXONE_DATA"."WF_TRANSITION" ("FROM_WF_PROCESS_DEFINITION_NUM", "FROM_NODE_SEQ", "TO_WF_PROCESS_DEFINITION_NUM", "TO_NODE_SEQ")
  ;
ALTER TABLE "TREXONE_DATA"."WF_TRANSITION" ADD CONSTRAINT "PK_WF_TRANSITION" PRIMARY KEY ("FROM_WF_PROCESS_DEFINITION_NUM", "FROM_NODE_SEQ", "TO_WF_PROCESS_DEFINITION_NUM", "TO_NODE_SEQ")
  USING INDEX "TREXONE_DATA"."PK_WF_TRANSITION"  ENABLE;
-- ==========================================
