-- ==========================================

  CREATE TABLE "TREXONE_DATA"."WF_VARIABLE_INSTANCE"
   (	"WF_PROCESS_DEFINITION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PROC_INST_SEQ" NUMBER(18,0) NOT NULL ENABLE,
	"VALUE" VARCHAR2(100),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"PARTITION_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PARTITION_DATE" DATE NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE,
	 CONSTRAINT "FK_WF_PROCESS_INSTANCE_05" FOREIGN KEY ("WF_PROCESS_DEFINITION_NUM", "PROC_INST_SEQ")
	  REFERENCES "TREXONE_DATA"."WF_PROCESS_INSTANCE" ("WF_PROCESS_DEFINITION_NUM", "PROC_INST_SEQ") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE")
 (PARTITION "P_MAXVALUE"  VALUES LESS THAN (MAXVALUE) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "TREXONE_DATA"."PK_WF_VARIABLE_INSTANCE" ON "TREXONE_DATA"."WF_VARIABLE_INSTANCE" ("WF_PROCESS_DEFINITION_NUM", "PROC_INST_SEQ")
  ;
ALTER TABLE "TREXONE_DATA"."WF_VARIABLE_INSTANCE" ADD CONSTRAINT "PK_WF_VARIABLE_INSTANCE" PRIMARY KEY ("WF_PROCESS_DEFINITION_NUM", "PROC_INST_SEQ")
  USING INDEX "TREXONE_DATA"."PK_WF_VARIABLE_INSTANCE"  ENABLE;
-- ==========================================
