-- ==========================================

  CREATE TABLE "TREXONE_DATA"."ZIPCODE"
   (	"CSZ_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"ZIPCODE" VARCHAR2(20),
	"CTRY_CODE" VARCHAR2(8),
	"STATE_CODE" VARCHAR2(2),
	"COUNTY" VARCHAR2(30),
	"CITY" VARCHAR2(40),
	"POST_OFFICE" VARCHAR2(40),
	"IS_USER_DEFINED" CHAR(1),
	"IS_DEFAULT" CHAR(1),
	"ARCHIVE_LEVEL" NUMBER(9,0) NOT NULL ENABLE,
	"SYS_USER" NUMBER(18,0) NOT NULL ENABLE,
	"DATESTAMP" DATE NOT NULL ENABLE,
	"NUM_UPDATES" NUMBER(9,0) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID') NOT NULL ENABLE
   ) ;
  CREATE INDEX "TREXONE_DATA"."PK_ZIPCODE" ON "TREXONE_DATA"."ZIPCODE" ("CSZ_NUM", "CITY", "STATE_CODE", "CTRY_CODE", "ZIPCODE", "NUM_UPDATES")
  ;
ALTER TABLE "TREXONE_DATA"."ZIPCODE" ADD CONSTRAINT "PK_ZIPCODE" PRIMARY KEY ("CSZ_NUM")
  USING INDEX "TREXONE_DATA"."PK_ZIPCODE"  ENABLE;
-- ==========================================
