-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."ACCOUNT_PATIENT_BRDG"
   (	"PD_PATIENT_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"AD_ACCOUNT_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"APB_STATUS" CHAR(1),
	"APB_REL_CODE" NUMBER(1,0),
	"APB_EFFECTIVE_DATE" DATE,
	"APB_TERM_DATE" DATE,
	"APB_USE_ACCNT_CRDT_CRD" CHAR(1),
	"APB_IS_PRIMARY" CHAR(1),
	"APB_PARTICIPATION_LEVEL" CHAR(1),
	"APB_PRTCPTN_LVL_DT" DATE,
	"APB_DACTIVATION_RSN_CD" CHAR(1),
	"APB_ENROLLMENT_CHANNEL" CHAR(1),
	"APB_FREQUENT_SHOPPER_NUM" VARCHAR2(20),
	"APB_IS_AUTHORIZED" CHAR(1),
	"APB_ACCNT_CRDT_CRD_NUM" NUMBER(18,0),
	"APB_UPDATE_DT" DATE,
	"APB_CREATE_DT" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	 CONSTRAINT "FK_ACCOUNT_6" FOREIGN KEY ("AD_ACCOUNT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."ACCOUNT" ("AD_ACCOUNT_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_8" FOREIGN KEY ("PD_PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") DISABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_ACCOUNT_PATIENT_BRDG" ON "TREXONE_DW_DATA"."ACCOUNT_PATIENT_BRDG" ("PD_PATIENT_KEY", "AD_ACCOUNT_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."ACCOUNT_PATIENT_BRDG" ADD CONSTRAINT "PK_ACCOUNT_PATIENT_BRDG" PRIMARY KEY ("PD_PATIENT_KEY", "AD_ACCOUNT_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_ACCOUNT_PATIENT_BRDG"  ENABLE;
-- ==========================================
