-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."ACCOUNT"
   (	"AD_ACCOUNT_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"AD_ACCOUNT_NUM" NUMBER(18,0),
	"AD_ACCOUNT_NUMBER" VARCHAR2(30),
	"AD_ACCOUNT_STATUS" CHAR(1),
	"AD_APPLY_FNNCE_CHRG_OVRRD" CHAR(1),
	"AD_FNNCE_CHG_PRCNT_OVRRD" NUMBER(18,0),
	"AD_FNNCE_CHRG_DAYS_OVRRD" NUMBER(18,0),
	"AD_PYMNT_DSC_ALLWD_OVRRD" CHAR(1),
	"AD_PYMNT_DSC_PRCNT_OVRRD" NUMBER(18,0),
	"AD_PYMNT_DSCNT_DAYS_OVRRD" NUMBER(10,0),
	"AD_APPLY_MISC_CHG_TAX" CHAR(1),
	"AD_LAST_CLOSED_DATE" DATE,
	"AD_MERGED_INTO_ACCOUNT" NUMBER(10,0),
	"AD_ALLOW_HOUSE_CHARGE" CHAR(1),
	"AD_USE_AR" CHAR(1),
	"AD_APPLY_RCRRNG_CHG_TAX" CHAR(1),
	"AD_CREATE_DT" DATE,
	"AD_UPDATE_DT" DATE,
	"AD_LOCK_DT" DATE,
	"AD_LOCK_USER" NUMBER(18,0),
	"AD_PRINT_STATEMENT" CHAR(1),
	"AD_PRINT_DUNNING_MSG_OVERRIDE" CHAR(1),
	"AD_DATA_GROUP" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_ACCOUNT" ON "TREXONE_DW_DATA"."ACCOUNT" ("AD_ACCOUNT_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."ACCOUNT" ADD CONSTRAINT "PK_ACCOUNT" PRIMARY KEY ("AD_ACCOUNT_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_ACCOUNT"  ENABLE;
-- ==========================================
