-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."ACCURACY_SCAN_LOG_AUDIT"
   (	"ASL_KEY" NUMBER(18,0),
	"DATE_KEY" NUMBER(18,0),
	"FD_FACILITY_KEY" NUMBER(18,0),
	"SYS_USER_KEY" NUMBER(18,0),
	"ASL_ACCURACY_SCAN_LOG_NUM" NUMBER(18,0),
	"ASL_RESULT" CHAR(1),
	"ASL_REASON" VARCHAR2(50),
	"ASL_VIAL_SCAN_DATA" VARCHAR2(40),
	"ASL_STOCK_SCAN_DATA" VARCHAR2(40),
	"ASL_RX_RECORD_NUM" NUMBER(18,0),
	"ASL_RX_FILL_SEQ" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"TIME_KEY" NUMBER(5,0),
	"RX_NUMBER" VARCHAR2(20),
	"REFILL_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	 CONSTRAINT "FK_DATE_DIM_32" FOREIGN KEY ("DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_34" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_SYS_USER_37" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_05" FOREIGN KEY ("TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
