-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."ALLERGY_SYMPTOM"
   (	"ASD_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"ASD_SYMPTOM_NUM" NUMBER(18,0),
	"ASD_DESCRIPTION" VARCHAR2(60),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_ALLERGY_SYMPTOM" ON "TREXONE_DW_DATA"."ALLERGY_SYMPTOM" ("ASD_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."ALLERGY_SYMPTOM" ADD CONSTRAINT "PK_ALLERGY_SYMPTOM" PRIMARY KEY ("ASD_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_ALLERGY_SYMPTOM"  ENABLE;
-- ==========================================
