-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."ALTERNATE_RECIPIENT"
   (	"ALTERNATE_RECIPIENT_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"ALTERNATE_RECIPIENT_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"PATIENT_KEY" NUMBER(18,0),
	"LAST_NAME" VARCHAR2(30),
	"FIRST_NAME" VARCHAR2(30),
	"ADDRESS1" VARCHAR2(100),
	"ADDRESS2" VARCHAR2(50),
	"CITY" VARCHAR2(40),
	"STATE_CODE" VARCHAR2(2),
	"ZIPCODE" VARCHAR2(20),
	"COUNTY" VARCHAR2(30),
	"CNTRY_CD" VARCHAR2(8),
	"POST_OFFICE" VARCHAR2(40),
	"PHONE_NUM" VARCHAR2(30),
	"COMPANY" VARCHAR2(44),
	"SYS_USER_KEY" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "PK_ALTERNATE_RECIPIENT" PRIMARY KEY ("ALTERNATE_RECIPIENT_KEY")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
