-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."ANCILLARY_ITEM_COMMIT"
   (	"ANCILLARY_ITEM_COMMIT_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"ANCILLARY_ITEM_COMMIT_NUM" NUMBER(18,0),
	"ANCILLARY_ITEM_KEY" NUMBER,
	"COMMIT_DESCRIPTION" VARCHAR2(60),
	"ORDER_NUM" NUMBER(18,0),
	"QUANTITY" NUMBER,
	"FACILITY_ITEM_NUM" VARCHAR2(10),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"SYS_USER_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"H_LEVEL" NUMBER(20,0),
	"H_TYPE" VARCHAR2(1),
	 CONSTRAINT "PK_ANCILLARY_ITEM_COMMIT" PRIMARY KEY ("ANCILLARY_ITEM_COMMIT_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SYS_USER_123" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_ANCILLARY_ITEM_1" FOREIGN KEY ("ANCILLARY_ITEM_KEY")
	  REFERENCES "TREXONE_DW_DATA"."ANCILLARY_ITEM" ("ANCILLARY_ITEM_KEY") ENABLE NOVALIDATE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("DW_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
