-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."ANCILLARY_ITEM_ADJUSTMENT"
   (	"ANCILLARY_ITEM_ADJ_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"ANCILLARY_ITEM_ADJ_NUM" NUMBER(18,0),
	"ANCILLARY_ITEM_KEY" NUMBER(18,0),
	"IAR_KEY" NUMBER(18,0),
	"QUANTITY" NUMBER(16,8),
	"ADJUSTMENT_TYPE_CODE" VARCHAR2(3),
	"CREATE_USER_KEY" NUMBER(18,0),
	"CREATE_DATE_KEY" NUMBER(18,0),
	"CREATE_TIME_KEY" NUMBER(8,0),
	"SYS_USER_KEY" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PARTITION_DATE" DATE,
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	 CONSTRAINT "ANCILLARY_ITEM_ADJUSTMENT_PK" PRIMARY KEY ("ANCILLARY_ITEM_ADJ_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "ANCILLARY_ITEM_ADJUSTMENT_FK01" FOREIGN KEY ("ANCILLARY_ITEM_KEY")
	  REFERENCES "TREXONE_DW_DATA"."ANCILLARY_ITEM" ("ANCILLARY_ITEM_KEY") ENABLE,
	 CONSTRAINT "ANCILLARY_ITEM_ADJUSTMENT_FK02" FOREIGN KEY ("IAR_KEY")
	  REFERENCES "TREXONE_DW_DATA"."INV_ADJUSTMENT_REASON_TYPE" ("IAR_KEY") ENABLE,
	 CONSTRAINT "ANCILLARY_ITEM_ADJUSTMENT_FK03" FOREIGN KEY ("CREATE_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") ENABLE,
	 CONSTRAINT "ANCILLARY_ITEM_ADJUSTMENT_FK04" FOREIGN KEY ("CREATE_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") ENABLE,
	 CONSTRAINT "ANCILLARY_ITEM_ADJUSTMENT_FK05" FOREIGN KEY ("CREATE_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") ENABLE,
	 CONSTRAINT "ANCILLARY_ITEM_ADJUSTMENT_FK06" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("DW_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
