-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."ANCILLARY_ITEM"
   (	"ANCILLARY_ITEM_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"ANCILLARY_ITEM_NUM" NUMBER(18,0),
	"INVENTORY_SKU_NUM" NUMBER(18,0),
	"PRODUCT_KEY" NUMBER(18,0),
	"FACILITY_KEY" NUMBER(18,0),
	"SKU" VARCHAR2(20),
	"EXPIRATION_DATE" DATE,
	"COST" NUMBER(17,6),
	"ORIGINAL_QUANTITY" NUMBER(16,6),
	"ORIGIN_DATE" DATE,
	"PRICE" NUMBER(17,6),
	"RECOMMENDED_QTY" NUMBER(16,8),
	"QUANTITY" NUMBER(16,8),
	"SYS_USER_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER(20,0),
	"H_TYPE" VARCHAR2(1),
	 CONSTRAINT "PK_ANCILLARY_ITEM" PRIMARY KEY ("ANCILLARY_ITEM_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SYS_USER_122" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_PRODUCT_62" FOREIGN KEY ("PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_FACILITY_120" FOREIGN KEY ("FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") ENABLE NOVALIDATE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("DW_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
