-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."CALENDAR_CONFIG"
   (	"IS_CALENDAR_BASED" CHAR(1),
	"START_MONTH" NUMBER,
	"START_DAY_OF_MONTH" NUMBER,
	"START_DAY_OF_WEEK" VARCHAR2(10),
	"LAST_DAY_OF_MONTH_MODE" VARCHAR2(10),
	"GROUPING_MODE" VARCHAR2(10),
	"PERIOD_WITH_EXTRA_WEEK" NUMBER,
	"QUARTER_WITH_EXTRA_PERIOD" NUMBER
   ) ;
-- ==========================================
