-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."CLINICAL_PROGRAM_STATUS"
   (	"CLINICAL_PROGRAM_STATUS_KEY" NUMBER(18,0),
	"CLINICAL_PROGRAM_KEY" NUMBER(18,0),
	"PROGRAM_STATUS_CODE_KEY" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"PATIENT_KEY" NUMBER(18,0),
	"CLINICAL_PROGRAM_STATUS_NUM" NUMBER(18,0),
	"H_LEVEL" NUMBER(20,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"STATUS_START_DATE" DATE,
	"STATUS_END_DATE" DATE,
	"FACILITY_KEY" NUMBER(18,0),
	"RX_NUMBER" VARCHAR2(20),
	 CONSTRAINT "PK_CLINICAL_PROGRAM_STATUS" PRIMARY KEY ("CLINICAL_PROGRAM_STATUS_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_CLINICAL_PROGRAM_01" FOREIGN KEY ("CLINICAL_PROGRAM_KEY")
	  REFERENCES "TREXONE_DW_DATA"."CLINICAL_PROGRAM" ("CLINICAL_PROGRAM_KEY") DISABLE,
	 CONSTRAINT "FK_PROGRAM_STATUS_CODE_01" FOREIGN KEY ("PROGRAM_STATUS_CODE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PROGRAM_STATUS_CODE" ("PROGRAM_STATUS_CODE_KEY") DISABLE
   )
  PARTITION BY RANGE ("STATUS_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("DW_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
