-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."CLINICAL_PROGRAM"
   (	"CLINICAL_PROGRAM_KEY" NUMBER(18,0),
	"PROGRAM_NAME" VARCHAR2(100),
	"PROGRAM_CODE" CHAR(1),
	"CLINICAL_PROGRAM_NUM" NUMBER(18,0),
	"H_LEVEL" NUMBER(20,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "PK_CLINICAL_PROGRAM" PRIMARY KEY ("CLINICAL_PROGRAM_KEY")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
