-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."CODE_SET"
   (	"CODE_SET_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"CS_CODE_SET_NUM" NUMBER(18,0),
	"CS_NAME" VARCHAR2(20),
	"CS_DESCRIPTION" VARCHAR2(255),
	"CS_INTERNAL" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_CODE_SET" ON "TREXONE_DW_DATA"."CODE_SET" ("CODE_SET_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."CODE_SET" ADD CONSTRAINT "PK_CODE_SET" PRIMARY KEY ("CODE_SET_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_CODE_SET"  ENABLE;
-- ==========================================
