-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."CODE_TYPE"
   (	"CT_CODE_TYPE_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"CT_CODE_TYPE_NUM" NUMBER(18,0),
	"CT_NAME" VARCHAR2(125),
	"CT_INTERNAL" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_CODE_TYPE" ON "TREXONE_DW_DATA"."CODE_TYPE" ("CT_CODE_TYPE_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."CODE_TYPE" ADD CONSTRAINT "PK_CODE_TYPE" PRIMARY KEY ("CT_CODE_TYPE_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_CODE_TYPE"  ENABLE;
-- ==========================================
