-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."CONTACT_STATUS_TYPE"
   (	"CONT_STATUS_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"CONT_STATUS_NUM" NUMBER(18,0),
	"CONT_STATUS_DESCRIPTION" VARCHAR2(100),
	"ERX_CLIENT_ID" VARCHAR2(100)
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_CONTACT_STATUS_TYPE" ON "TREXONE_DW_DATA"."CONTACT_STATUS_TYPE" ("CONT_STATUS_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."CONTACT_STATUS_TYPE" ADD CONSTRAINT "PK_CONTACT_STATUS_TYPE" PRIMARY KEY ("CONT_STATUS_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_CONTACT_STATUS_TYPE"  ENABLE;
-- ==========================================
