-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."COST_BASIS_SOURCE"
   (	"COST_BASIS_SOURCE_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"COST_BASIS_SOURCE_NUM" NUMBER(18,0),
	"COST_BASIS_SOURCE_NAME" VARCHAR2(65),
	"COST_BASIS_SOURCE_DESC" VARCHAR2(255),
	"PROVIDER" VARCHAR2(30),
	"IS_UNIT_COST" CHAR(1),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_COST_BASIS_SOURCE" ON "TREXONE_DW_DATA"."COST_BASIS_SOURCE" ("COST_BASIS_SOURCE_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."COST_BASIS_SOURCE" ADD CONSTRAINT "PK_COST_BASIS_SOURCE" PRIMARY KEY ("COST_BASIS_SOURCE_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_COST_BASIS_SOURCE"  ENABLE;
-- ==========================================
