-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."COUNSELING_NOTE"
   (	"COUNSELING_NOTE_KEY" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"NOTE_TEXT" VARCHAR2(4000),
	"CREATE_USER_KEY" NUMBER(18,0),
	"CREATE_DATE_KEY" NUMBER(18,0),
	"CREATE_TIME_KEY" NUMBER(5,0),
	"PRIORITY_INDICATOR" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	"COUNSELING_NOTE_SEQ" NUMBER(18,0),
	 CONSTRAINT "PK_COUNSELING_NOTE" PRIMARY KEY ("COUNSELING_NOTE_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SYS_USER_92" FOREIGN KEY ("CREATE_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_149" FOREIGN KEY ("CREATE_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_62" FOREIGN KEY ("CREATE_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE
   ) ;
-- ==========================================
