-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."CPS_PROGRAM"
   (	"CPS_PROGRAM_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"CPS_PROGRAM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CPS_PROGRAM_NAME" VARCHAR2(60) NOT NULL ENABLE,
	"CPS_PROGRAM_DESC" VARCHAR2(600),
	"CPS_PROGRAM_TAG" VARCHAR2(30),
	"CPS_PROGRAM_TYPE" VARCHAR2(50) NOT NULL ENABLE,
	"CPS_ENROLLMENT" VARCHAR2(30) NOT NULL ENABLE,
	"CPS_STATUS_KEY" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"CHECKIN" CHAR(1),
	 CONSTRAINT "FK_CPS_STATUS_03" FOREIGN KEY ("CPS_STATUS_KEY")
	  REFERENCES "TREXONE_DW_DATA"."CPS_STATUS" ("CPS_STATUS_KEY") DISABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_CPS_PROGRAM" ON "TREXONE_DW_DATA"."CPS_PROGRAM" ("CPS_PROGRAM_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."CPS_PROGRAM" ADD CONSTRAINT "PK_CPS_PROGRAM" PRIMARY KEY ("CPS_PROGRAM_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_CPS_PROGRAM"  ENABLE;
-- ==========================================
