-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."CPS_STATUS"
   (	"CPS_STATUS_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"CPS_STATUS_NAME" VARCHAR2(50) NOT NULL ENABLE,
	"CPS_STATUS_TYPE" CHAR(1) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100)
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_CPS_STATUS" ON "TREXONE_DW_DATA"."CPS_STATUS" ("CPS_STATUS_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."CPS_STATUS" ADD CONSTRAINT "PK_CPS_STATUS" PRIMARY KEY ("CPS_STATUS_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_CPS_STATUS"  ENABLE;
-- ==========================================
