-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."CPS_MESSAGE_TYPE"
   (	"CPS_MESSAGE_TYPE_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"TYPE_NAME" VARCHAR2(50) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100)
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_CPS_MESSAGE_TYPE" ON "TREXONE_DW_DATA"."CPS_MESSAGE_TYPE" ("CPS_MESSAGE_TYPE_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."CPS_MESSAGE_TYPE" ADD CONSTRAINT "PK_CPS_MESSAGE_TYPE" PRIMARY KEY ("CPS_MESSAGE_TYPE_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_CPS_MESSAGE_TYPE"  ENABLE;
-- ==========================================
