-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."CPS_CONVERSATION_FACT"
   (	"CPS_MESSAGE_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"CPS_CONVERSATION_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"CONVERSATION_TEXT" VARCHAR2(4000),
	"SENT_DATE" DATE NOT NULL ENABLE,
	"SENDER" VARCHAR2(100) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "FK_CPS_MESSAGE_FACT_01" FOREIGN KEY ("CPS_MESSAGE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."CPS_MESSAGE_FACT" ("CPS_MESSAGE_KEY") DISABLE
   )
  PARTITION BY RANGE ("SENT_DATE") INTERVAL (NUMTOYMINTERVAL(1,'MONTH')) STORE IN ("DW_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
