-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."CPS_MEASURE_FACT"
   (	"CPS_PROGRAM_KEY" NUMBER(18,0),
	"CPS_KEY_VALUE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"KEY_NAME" VARCHAR2(36) NOT NULL ENABLE,
	"KEY_DESC" VARCHAR2(1000) NOT NULL ENABLE,
	"KEY_VALUE" VARCHAR2(4000) NOT NULL ENABLE,
	"UPDATED_BY" VARCHAR2(100) NOT NULL ENABLE,
	"CREATE_DATE" DATE NOT NULL ENABLE,
	"PATIENT_KEY" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"VENDOR_PATIENT_ID" VARCHAR2(100),
	"PATIENT_QUESTIONNAIRE_NUM" NUMBER(18,0),
	 CONSTRAINT "FK_CPS_PROGRAM_02" FOREIGN KEY ("CPS_PROGRAM_KEY")
	  REFERENCES "TREXONE_DW_DATA"."CPS_PROGRAM" ("CPS_PROGRAM_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_46" FOREIGN KEY ("PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") DISABLE
   )
  PARTITION BY RANGE ("CREATE_DATE") INTERVAL (NUMTOYMINTERVAL(1,'MONTH')) STORE IN ("DW_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
