-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."CPS_MESSAGE_PRIORITY"
   (	"CPS_MESSAGE_PRIORITY_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PRIORITY_NAME" VARCHAR2(20) NOT NULL ENABLE,
	"ERX_CLIENT_ID" VARCHAR2(100)
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_CPS_MESSAGE_PRIORITY" ON "TREXONE_DW_DATA"."CPS_MESSAGE_PRIORITY" ("CPS_MESSAGE_PRIORITY_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."CPS_MESSAGE_PRIORITY" ADD CONSTRAINT "PK_CPS_MESSAGE_PRIORITY" PRIMARY KEY ("CPS_MESSAGE_PRIORITY_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_CPS_MESSAGE_PRIORITY"  ENABLE;
-- ==========================================
