-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."CSR_RXFILL_COMPOUND_DETAIL"
   (	"CRE_KEY" NUMBER(18,0),
	"CSR_RXFILL_EXTRACT_NUM" NUMBER(20,0),
	"INGREDIENT_NDC_ID" VARCHAR2(15),
	"INGREDIENT_QUANTITY" NUMBER(14,3),
	"INGREDIENT_UNITS_CODE" NUMBER(2,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	"INGREDIENT_DEA_SCHEDULE" VARCHAR2(2),
	 CONSTRAINT "FK_CSR_RXFILL_DETAIL_01" FOREIGN KEY ("CRE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."CSR_RXFILL_EXTRACT" ("CRE_KEY") DISABLE
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
