-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."CSR_RXFILL_TP_DETAIL"
   (	"CRTD_CSR_RXFILL_EXTRACT_KEY" NUMBER(20,0),
	"CRTD_CSR_RXFILL_EXTRACT_NUM" NUMBER(20,0),
	"CRTD_TP_PLAN_NUM" NUMBER(18,0),
	"CRTD_TP_PLAN_CODE" VARCHAR2(12),
	"CRTD_TP_PLAN_NAME" VARCHAR2(45),
	"CRTD_TP_PLAN_TYPE" VARCHAR2(10),
	"CRTD_TP_PLAN_COVERAGE" VARCHAR2(2),
	"CRTD_SYS_USER_KEY" NUMBER(18,0),
	"BILLING_ORDER" NUMBER(2,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	 CONSTRAINT "FK_SYS_USER_83" FOREIGN KEY ("CRTD_SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_CSR_RXFILL_TP_DETAIL" ON "TREXONE_DW_DATA"."CSR_RXFILL_TP_DETAIL" ("CRTD_CSR_RXFILL_EXTRACT_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."CSR_RXFILL_TP_DETAIL" ADD CONSTRAINT "PK_CSR_RXFILL_TP_DETAIL" PRIMARY KEY ("CRTD_CSR_RXFILL_EXTRACT_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_CSR_RXFILL_TP_DETAIL"  ENABLE;
-- ==========================================
