-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."DELIVERY_ROUTE_SCHEDULE"
   (	"DELIVERY_ROUTE_SCHEDULE_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"CENTRAL_FILL_FD_FACILITY_KEY" NUMBER(18,0),
	"DELIVERY_ROUTE_NUM" NUMBER(18,0),
	"DELIVERY_ROUTE_ID" VARCHAR2(7),
	"DELIVERY_ROUTE_NAME" VARCHAR2(30),
	"SCHEDULE_DEPART_TIME_KEY" NUMBER(5,0),
	"IS_MONDAY" CHAR(1),
	"IS_TUESDAY" CHAR(1),
	"IS_WEDNESDAY" CHAR(1),
	"IS_THURSDAY" CHAR(1),
	"IS_FRIDAY" CHAR(1),
	"IS_SATURDAY" CHAR(1),
	"IS_SUNDAY" CHAR(1),
	"DELIVERY_STOP_NUM" NUMBER(18,0),
	"LOCAL_FD_FACILITY_KEY" NUMBER(18,0),
	"SCHEDULE_STOP_TIME_KEY" NUMBER(5,0),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	 CONSTRAINT "FK_FACILITY_79" FOREIGN KEY ("LOCAL_FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_80" FOREIGN KEY ("CENTRAL_FILL_FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_18" FOREIGN KEY ("SCHEDULE_DEPART_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_19" FOREIGN KEY ("SCHEDULE_STOP_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_DELIVERY_ROUTE_SCHEDULE" ON "TREXONE_DW_DATA"."DELIVERY_ROUTE_SCHEDULE" ("DELIVERY_ROUTE_SCHEDULE_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."DELIVERY_ROUTE_SCHEDULE" ADD CONSTRAINT "PK_DELIVERY_ROUTE_SCHEDULE" PRIMARY KEY ("DELIVERY_ROUTE_SCHEDULE_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_DELIVERY_ROUTE_SCHEDULE"  ENABLE;
-- ==========================================
