-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."DELIVERY_METHOD_TYPE"
   (	"DM_DELIVERY_METHOD_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"DM_DELIVERY_METHOD" NUMBER(18,0),
	"DM_DELIVERY_METHOD_DESC" VARCHAR2(45),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_DELIVERY_METHOD_TYPE" ON "TREXONE_DW_DATA"."DELIVERY_METHOD_TYPE" ("DM_DELIVERY_METHOD_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."DELIVERY_METHOD_TYPE" ADD CONSTRAINT "PK_DELIVERY_METHOD_TYPE" PRIMARY KEY ("DM_DELIVERY_METHOD_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_DELIVERY_METHOD_TYPE"  ENABLE;
-- ==========================================
