-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."DOC_VERSION"
   (	"DV_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"DOC_VERSION_NUM" NUMBER(18,0),
	"DV_VERSION" VARCHAR2(18),
	"DV_LAYOUT_STREAM" BLOB,
	"DV_MARSHALLING_TEMPLATE" CLOB,
	"DV_STYLESHEET" CLOB,
	"DV_CHECK_IN_DATE" DATE,
	"DV_CHECK_OUT_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_DOC_VERSION" ON "TREXONE_DW_DATA"."DOC_VERSION" ("DV_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."DOC_VERSION" ADD CONSTRAINT "PK_DOC_VERSION" PRIMARY KEY ("DV_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_DOC_VERSION"  ENABLE;
-- ==========================================
