-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."DUR_CONFLICT_FACT"
   (	"DATE_KEY" NUMBER(18,0),
	"FD_FACILITY_KEY" NUMBER(18,0),
	"PD_PATIENT_H_KEY" NUMBER(18,0),
	"PRS_PRESCRIBER_KEY" NUMBER(18,0),
	"PRD_PRODUCT_KEY" NUMBER(18,0),
	"SYS_USER_KEY" NUMBER(18,0),
	"TPLD_PLAN_KEY" NUMBER(18,0),
	"DUR_CONFLICT_CODE_KEY" NUMBER(18,0),
	"DUR_CONFLICT_TYPE_KEY" NUMBER(18,0),
	"DUR_SEVERITY_TYPE_KEY" NUMBER(18,0),
	"DUR_INDICATOR_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"RX_NUMBER" VARCHAR2(20),
	"FILL_SEQ_NUM" NUMBER(18,0),
	"REFILL_NUM" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PD_PATIENT_KEY" NUMBER(18,0),
	"H_LEVEL" NUMBER,
	"REASON_FOR_SERVICE_CODE" VARCHAR2(2),
	"RESULT_SERVICE_CODE" CHAR(2),
	"PROF_SERVICE_CODE" CHAR(2),
	"LEVEL_OF_EFFORT_NUM" NUMBER(9,0),
	"TP_MESSAGE_NUM" NUMBER(18,0),
	"PARTIAL_FILL_SEQ" NUMBER(2,0),
	"DUR_CONFLICT_NUM" NUMBER(18,0),
	 CONSTRAINT "FK_DATE_DIM_65" FOREIGN KEY ("DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DUR_CONFLICT_CODE_01" FOREIGN KEY ("DUR_CONFLICT_CODE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DUR_CONFLICT_CODE" ("DUR_CONFLICT_CODE_KEY") DISABLE,
	 CONSTRAINT "FK_DUR_CONFLICT_TYPE_01" FOREIGN KEY ("DUR_CONFLICT_TYPE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DUR_CONFLICT_TYPE" ("DUR_CONFLICT_TYPE_KEY") DISABLE,
	 CONSTRAINT "FK_DUR_INDICATOR_01" FOREIGN KEY ("DUR_INDICATOR_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DUR_INDICATOR" ("DUR_INDICATOR_KEY") DISABLE,
	 CONSTRAINT "FK_DUR_SEVERITY_TYPE_01" FOREIGN KEY ("DUR_SEVERITY_TYPE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DUR_SEVERITY_TYPE" ("DUR_SEVERITY_TYPE_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_62" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_H_32" FOREIGN KEY ("PD_PATIENT_H_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT_H" ("PD_PATIENT_H_KEY") DISABLE,
	 CONSTRAINT "FK_PRESCRIBER_13" FOREIGN KEY ("PRS_PRESCRIBER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRESCRIBER" ("PRS_PRESCRIBER_KEY") DISABLE,
	 CONSTRAINT "FK_PRODUCT_24" FOREIGN KEY ("PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE,
	 CONSTRAINT "FK_SYS_USER_67" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE,
	 CONSTRAINT "FK_TP_PLAN_05" FOREIGN KEY ("TPLD_PLAN_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TP_PLAN" ("TPLD_PLAN_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_32" FOREIGN KEY ("PD_PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") DISABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
