-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."DUR_CONFLICT_CODE"
   (	"DUR_CONFLICT_CODE_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"DUR_CONFLICT_CODE" VARCHAR2(10),
	"DUR_CONFLICT_CODE_DESC" VARCHAR2(255),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_DUR_CONFLICT_CODE" ON "TREXONE_DW_DATA"."DUR_CONFLICT_CODE" ("DUR_CONFLICT_CODE_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."DUR_CONFLICT_CODE" ADD CONSTRAINT "PK_DUR_CONFLICT_CODE" PRIMARY KEY ("DUR_CONFLICT_CODE_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_DUR_CONFLICT_CODE"  ENABLE;
-- ==========================================
