-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."DUR_FILL_SUMMARY"
   (	"DATE_KEY" NUMBER(18,0),
	"FD_FACILITY_KEY" NUMBER(18,0),
	"RX_NUMBER" VARCHAR2(20),
	"FILL_SEQ_NUM" NUMBER(18,0),
	"IS_NEW" CHAR(1),
	"CHAIN_CRITICAL_DUR_CNT" NUMBER(18,0),
	"CHAIN_INFORMATIONAL_DUR_CNT" NUMBER(18,0),
	"DUR_ELAPSED_SECS" NUMBER(10,0),
	"PARTITION_DATE" DATE,
	"CHAIN_HARD_STOP_DUR_CNT" NUMBER(18,0),
	"TP_CRITICAL_DUR_CNT" NUMBER(18,0),
	"TP_INFORMATIONAL_DUR_CNT" NUMBER(18,0),
	"TP_HARD_STOP_DUR_CNT" NUMBER(18,0),
	"CHAIN_FILTERED_DUR_CNT" NUMBER(18,0),
	"REFILL_NUM" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "FK_DATE_DIM_66" FOREIGN KEY ("DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_63" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
