-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."DUR_CONFLICT_TYPE"
   (	"DUR_CONFLICT_TYPE_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"DUR_CONFLICT_CODE" CHAR(10),
	"DUR_CONFLICT_DESC" VARCHAR2(100),
	"ERX_CLIENT_ID" VARCHAR2(100)
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_DUR_CONFLICT_TYPE" ON "TREXONE_DW_DATA"."DUR_CONFLICT_TYPE" ("DUR_CONFLICT_TYPE_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."DUR_CONFLICT_TYPE" ADD CONSTRAINT "PK_DUR_CONFLICT_TYPE" PRIMARY KEY ("DUR_CONFLICT_TYPE_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_DUR_CONFLICT_TYPE"  ENABLE;
-- ==========================================
