-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."DUR_SEVERITY_TYPE"
   (	"DUR_SEVERITY_TYPE_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"DUR_SEVERITY_CODE" VARCHAR2(10),
	"DUR_SEVERITY_DESC" VARCHAR2(100),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_DUR_SEVERITY_TYPE" ON "TREXONE_DW_DATA"."DUR_SEVERITY_TYPE" ("DUR_SEVERITY_TYPE_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."DUR_SEVERITY_TYPE" ADD CONSTRAINT "PK_DUR_SEVERITY_TYPE" PRIMARY KEY ("DUR_SEVERITY_TYPE_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_DUR_SEVERITY_TYPE"  ENABLE;
-- ==========================================
