-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."DW_LAST_LOAD_SEQ"
   (	"TABLE_NAME" VARCHAR2(50) NOT NULL ENABLE,
	"SEQ#" NUMBER,
	"FACILITY_NUM" NUMBER,
	"LAST_LOAD_DATE" DATE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_DW_LAST_LOAD_SEQ" ON "TREXONE_DW_DATA"."DW_LAST_LOAD_SEQ" ("TABLE_NAME", "FACILITY_NUM")
  ;
ALTER TABLE "TREXONE_DW_DATA"."DW_LAST_LOAD_SEQ" ADD CONSTRAINT "PK_DW_LAST_LOAD_SEQ" PRIMARY KEY ("TABLE_NAME", "FACILITY_NUM")
  USING INDEX "TREXONE_DW_DATA"."PK_DW_LAST_LOAD_SEQ"  ENABLE;
-- ==========================================
