-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."ELIGIBILITY_CLARIF"
   (	"EC_ELIGIBILITY_CLARIF_KEY" NUMBER(18,0),
	"EC_ELIGIBILITY_CLARIF_NUM" NUMBER(18,0),
	"EC_DESCRIPTION" VARCHAR2(30),
	"EC_SYS_USER_KEY" NUMBER(18,0),
	"EC_DATESTAMP" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	 CONSTRAINT "FK_SYS_USER_82" FOREIGN KEY ("EC_SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_ELIGIBILITY_CLARIF" ON "TREXONE_DW_DATA"."ELIGIBILITY_CLARIF" ("EC_ELIGIBILITY_CLARIF_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."ELIGIBILITY_CLARIF" ADD CONSTRAINT "PK_ELIGIBILITY_CLARIF" PRIMARY KEY ("EC_ELIGIBILITY_CLARIF_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_ELIGIBILITY_CLARIF"  ENABLE;
-- ==========================================
