-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."EPCS_TYPE"
   (	"EPCS_TYPE_KEY" NUMBER(18,0),
	"EPCS_TYPE_CODE" CHAR(1),
	"EPCS_TYPE_DESC" VARCHAR2(400),
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "PK_EPCS_TYPE" PRIMARY KEY ("EPCS_TYPE_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "UC_EPCS_TYPE_01" UNIQUE ("EPCS_TYPE_CODE")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
