-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."EPCS_SUB_CATEGORY"
   (	"EPCS_SUB_CATEGORY_KEY" NUMBER(18,0),
	"EPCS_CATEGORY_KEY" NUMBER(18,0),
	"EPCS_SUB_CATEGORY_CODE" VARCHAR2(255),
	"EPCS_SUB_CATEGORY_DESC" VARCHAR2(400),
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "PK_EPCS_SUB_CATEGORY" PRIMARY KEY ("EPCS_SUB_CATEGORY_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "UC_EPCS_SUB_CATEGORY_01" UNIQUE ("EPCS_SUB_CATEGORY_CODE")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_EPCS_CATEGORY_01" FOREIGN KEY ("EPCS_CATEGORY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."EPCS_CATEGORY" ("EPCS_CATEGORY_KEY") DISABLE
   ) ;
-- ==========================================
