-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."EPCS_PRIORITY"
   (	"EPCS_PRIORITY_KEY" NUMBER(18,0),
	"EPCS_PRIORITY_CODE" NUMBER(1,0),
	"EPCS_PRIORITY_DESC" VARCHAR2(400),
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "PK_EPCS_PRIORITY" PRIMARY KEY ("EPCS_PRIORITY_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "UC_EPCS_PRIORITY_01" UNIQUE ("EPCS_PRIORITY_CODE")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
