-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."FACILITY_PRESCRIBER"
   (	"FP_FACILITY_PRESCRIBER_KEY" NUMBER(18,0),
	"FP_FACILITY_PRESCRIBER_NUM" NUMBER(18,0),
	"FP_PRS_PRESCRIBER_KEY" NUMBER(18,0),
	"FP_FD_FACILITY_KEY" NUMBER(18,0),
	"FP_SYS_USER" NUMBER(18,0),
	"FP_CREATE_DT" DATE,
	"FP_UPDATE_DT" DATE,
	"FP_LAST_FILL_DATE" DATE,
	"FP_LOGIN_FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID'),
	 CONSTRAINT "PK_FACILITY_PRESCRIBER" PRIMARY KEY ("FP_FACILITY_PRESCRIBER_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_PRESCRIBER_15" FOREIGN KEY ("FP_PRS_PRESCRIBER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRESCRIBER" ("PRS_PRESCRIBER_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_94" FOREIGN KEY ("FP_FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE
   ) ;
-- ==========================================
