-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."FACILITY_SYSTEM_USER"
   (	"FACILITY_SYSTEM_USER_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"FD_FACILITY_KEY" NUMBER(18,0),
	"SYS_USER_KEY" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID'),
	"STATUS" CHAR(1),
	"FACILITY_SYSTEM_USER_NUM" NUMBER(18,0),
	 CONSTRAINT "PK_FACILITY_SYSTEM_USER" PRIMARY KEY ("FACILITY_SYSTEM_USER_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_FACILITY_91" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_SYS_USER_84" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE
   ) ;
-- ==========================================
