-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."FAX_ORDER_IN"
   (	"DATE_KEY" NUMBER(18,0),
	"FD_FACILITY_KEY" NUMBER(18,0),
	"SYS_USER_KEY" NUMBER(18,0),
	"UA_KEY" NUMBER(18,0),
	"FAX_ORDER_IN_NUM" NUMBER(18,0),
	"FOI_ELECTRONIC_ORDER_NUM" NUMBER(18,0),
	"FOI_FROM_FAX_NUM" VARCHAR2(12),
	"FOI_TO_FAX_NUM" VARCHAR2(12),
	"FOI_SENDER_NAME" VARCHAR2(30),
	"FOI_RECIPIENT_NAME" VARCHAR2(30),
	"FOI_IMAGE_NUM" NUMBER(18,0),
	"FOI_RX_RECORD_NUM" NUMBER(18,0),
	"FOI_RX_FILL_SEQ" NUMBER(18,0),
	"PRS_PRESCRIBER_KEY" NUMBER(18,0),
	"PD_PATIENT_H_KEY" NUMBER(18,0),
	"FOI_CREATE_DT" DATE,
	"FOI_RX_NUMBER" VARCHAR2(20),
	"FOI_REFILL_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PD_PATIENT_KEY" NUMBER(18,0),
	"H_LEVEL" NUMBER,
	 CONSTRAINT "FK_DATE_DIM_40" FOREIGN KEY ("DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_43" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_H_617" FOREIGN KEY ("PD_PATIENT_H_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT_H" ("PD_PATIENT_H_KEY") DISABLE,
	 CONSTRAINT "FK_PRESCRIBER_5" FOREIGN KEY ("PRS_PRESCRIBER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRESCRIBER" ("PRS_PRESCRIBER_KEY") DISABLE,
	 CONSTRAINT "FK_SYS_USER_46" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE,
	 CONSTRAINT "FK_USER_ACTION_TYPE_612" FOREIGN KEY ("UA_KEY")
	  REFERENCES "TREXONE_DW_DATA"."USER_ACTION_TYPE" ("UA_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_617" FOREIGN KEY ("PD_PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") DISABLE
   )
  PARTITION BY RANGE ("FOI_CREATE_DT") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
