-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."FILL_STATUS_TYPE"
   (	"FS_FILL_STATUS_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"FS_FILL_STATUS_NUM" NUMBER(18,0),
	"FS_FILL_STATUS_DESC" VARCHAR2(30),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_FILL_STATUS_TYPE" ON "TREXONE_DW_DATA"."FILL_STATUS_TYPE" ("FS_FILL_STATUS_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."FILL_STATUS_TYPE" ADD CONSTRAINT "PK_FILL_STATUS_TYPE" PRIMARY KEY ("FS_FILL_STATUS_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_FILL_STATUS_TYPE"  ENABLE;
-- ==========================================
