-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."FILL_PRICING_FACT"
   (	"ORDER_DATE_KEY" NUMBER(18,0),
	"PD_PATIENT_H_KEY" NUMBER(18,0),
	"AD_ACCOUNT_KEY" NUMBER(18,0),
	"PRS_PRESCRIBER_KEY" NUMBER(18,0),
	"TWED_KEY" NUMBER(18,0),
	"SYS_USER_KEY" NUMBER(18,0),
	"OVERRIDE_RPH_SYS_USER_KEY" NUMBER(18,0),
	"TPD_KEY" NUMBER(18,0),
	"TPLD_PLAN_KEY" NUMBER(18,0),
	"ATD_AGENCY_TYPE_KEY" NUMBER(18,0),
	"TRCD_KEY" NUMBER(18,0),
	"PADR_KEY" NUMBER(18,0),
	"PID_KEY" NUMBER(18,0),
	"NCPDP_KEY" NUMBER(18,0),
	"BS_BILLING_STATUS_KEY" NUMBER(18,0),
	"FS_FILL_STATUS_KEY" NUMBER(18,0),
	"LF_LATIN_FREQUENCY_KEY" NUMBER(18,0),
	"TSC_THERAPUETIC_SUB_CODE_KEY" NUMBER(18,0),
	"PRD_PRODUCT_KEY" NUMBER(18,0),
	"OS_ORDER_SOURCE_KEY" NUMBER(18,0),
	"FD_FACILITY_KEY" NUMBER(18,0),
	"DISPENSED_PRODUCT_KEY" NUMBER(18,0),
	"MC_MESSAGE_CATEGORY_KEY" NUMBER(18,0),
	"C_COUPON_TYPE_KEY" NUMBER(18,0),
	"DC_DAW_CODE_KEY" NUMBER(18,0),
	"RESPONSIBLE_PARTY_KEY" NUMBER(2,0),
	"FILL_CATEGORY_KEY" NUMBER(2,0),
	"OVERRIDE_DATE_KEY" NUMBER(18,0),
	"PRICING_OVERRIDE_CODE_KEY" NUMBER(18,0),
	"OVERRIDE_SYS_USER_KEY" NUMBER(18,0),
	"FILL_PRICING_IND_KEY" NUMBER(18,0),
	"RX_NUMBER" VARCHAR2(20),
	"BLLNG_COST_AMT" NUMBER(17,6),
	"BLLNG_FEE_AMT" NUMBER(17,6),
	"BLLNG_PRICING_DSCNT1_KEY" NUMBER(18,0),
	"BLLNG_PRICING_DSCNT2_KEY" NUMBER(18,0),
	"BLLNG_PRICING_DSCNT3_KEY" NUMBER(18,0),
	"BLLNG_DISCOUNT1_AMT" NUMBER(17,6),
	"BLLNG_DISCOUNT2_AMT" NUMBER(17,6),
	"BLLNG_DISCOUNT3_AMT" NUMBER(17,6),
	"BLLNG_ADJUSTMENT_AMT" NUMBER(17,6),
	"BLLNG_FINAL_PRICE_AMT" NUMBER(17,6),
	"BLLNG_PRE_OVERRIDE_PRC_AMT" NUMBER(17,6),
	"BLLNG_TAX_AMT" NUMBER(17,6),
	"CNTRCT_COST_AMT" NUMBER(17,6),
	"CNTRCT_FEE_AMT" NUMBER(17,6),
	"CNTRCT_PRICING_DSCNT1_KEY" NUMBER(18,0),
	"CNTRCT_PRICING_DSCNT2_KEY" NUMBER(18,0),
	"CNTRCT_PRICING_DSCNT3_KEY" NUMBER(18,0),
	"CNTRCT_DISCOUNT1_AMT" NUMBER(17,6),
	"CNTRCT_DISCOUNT2_AMT" NUMBER(17,6),
	"CNTRCT_DISCOUNT3_AMT" NUMBER(17,6),
	"CNTRCT_ADJUSTMENT_AMT" NUMBER(17,6),
	"CNTRCT_FINAL_PRICE_AMT" NUMBER(17,6),
	"CNTRCT_PRE_OVERRIDE_PRC_AMT" NUMBER(17,6),
	"CNTRCT_TAX_AMT" NUMBER(17,6),
	"POS_PRICE_AMT" NUMBER(17,6),
	"OVERRIDE_AMT" NUMBER(17,6),
	"COPAY_AMT" NUMBER(17,6),
	"ACTUAL_PAID_AMT" NUMBER(17,6),
	"DISPENSED_QTY_AWP_AMT" NUMBER(17,6),
	"DISPENSED_QTY" NUMBER(17,6),
	"PARTITION_DATE" DATE,
	"PRE_OVERRIDE_COPAY_AMOUNT" NUMBER(17,6),
	"USER_DEFINED_STEP_AMT" NUMBER(17,6),
	"ADJUDICATION_DATE_KEY" NUMBER(18,0),
	"ADJUDICATION_TIME_KEY" NUMBER(18,0),
	"DISPENSED_DRUG_KEY" NUMBER(18,0),
	"DRUG_KEY" NUMBER(18,0),
	"REFILL_NUM" NUMBER(18,0),
	"BILLING_ORDER" VARCHAR2(2),
	"FILL_COUNT" NUMBER(1,0),
	"NON_COVERED_AMT" NUMBER(17,6),
	"IS_LAST_COB_PAYER" CHAR(1),
	"FS_NUM" NUMBER,
	"TAX_PAID_AMT" NUMBER(17,6),
	"ADJUDICATION_GROUP_NUM" NUMBER,
	"RX_FILL_SEQ" NUMBER(18,0),
	"TRANSACTION_CODE" VARCHAR2(100),
	"BILLING_INDICATOR" CHAR(1),
	"DATE_OF_SERVICE_DATE_KEY" NUMBER(18,0),
	"DATE_OF_SERVICE_TIME_KEY" NUMBER(18,0),
	"IS_PRIMARY_PAYER" CHAR(1),
	"IS_COB" CHAR(1),
	"IS_BAR" CHAR(1),
	"DAYS_SUPPLY" NUMBER(18,0),
	"PRESCRIBED_DATE_KEY" NUMBER(18,0) DEFAULT 0,
	"TRIPLICATE_SERIAL_NUM" VARCHAR2(30),
	"PARTIAL_FILL_SEQ" NUMBER(3,0),
	"EC_ELIGIBILITY_CLARIF_KEY" NUMBER(18,0),
	"AUTH_TYPE_NUM" VARCHAR2(20),
	"BASIS_OF_COST" CHAR(2),
	"COUNSELING_ACCEPTED" CHAR(1),
	"IMAGE_KEY" NUMBER(18,0),
	"SOLD_DATE_KEY" NUMBER(18,0),
	"SOLD_TIME_KEY" NUMBER(18,0),
	"PARTIAL_FILL_IND" CHAR(1),
	"BIN_NUMBER" VARCHAR2(6),
	"TP_PROCESSOR_KEY" NUMBER(18,0),
	"CANCEL_DATE_KEY" NUMBER(18,0),
	"CANCEL_TIME_KEY" NUMBER(18,0),
	"RTP_DATE_KEY" NUMBER(18,0),
	"RTP_TIME_KEY" NUMBER(18,0),
	"RX_TYPE_NUM" NUMBER(2,0),
	"TOTAL_UANDC" NUMBER(17,6),
	"FINANCIAL_TRANSACTION_NUM" NUMBER(7,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PD_PATIENT_KEY" NUMBER(18,0),
	"CRF_NUM" NUMBER,
	"IS_340B" CHAR(1),
	"INFO_CLAIM_STATUS" CHAR(1),
	"INFO_CLAIM_OVERRIDE_COMMENT" VARCHAR2(255),
	"REFILLS_ALLOWED" NUMBER(9,0),
	"LAST_FILL_DATE_KEY" NUMBER(18,0),
	"LAST_FILL_TIME_KEY" NUMBER(18,0),
	"FIRST_FILL_DATE_KEY" NUMBER(18,0),
	"FIRST_FILL_TIME_KEY" NUMBER(18,0),
	"WRITTEN_DATE_KEY" NUMBER(18,0),
	"WRITTEN_TIME_KEY" NUMBER(18,0),
	"EXPIRY_DATE_KEY" NUMBER(18,0),
	"EXPIRY_TIME_KEY" NUMBER(18,0),
	"PROMISE_DATE_KEY" NUMBER(18,0),
	"PROMISE_TIME_KEY" NUMBER(18,0),
	"READY_DATE_KEY" NUMBER(18,0),
	"READY_TIME_KEY" NUMBER(18,0),
	"DISPENSE_DATE_KEY" NUMBER(18,0),
	"DISPENSE_TIME_KEY" NUMBER(18,0),
	"PROCESSOR_CONTROL_NUMBER" VARCHAR2(10),
	"SIG" VARCHAR2(2000),
	"REFILL_QTY" NUMBER(13,3),
	"WRITTEN_QTY" NUMBER(13,3),
	"INFO_CLAIM_SYS_USER_KEY" NUMBER(18,0),
	"TP_MESSAGE_NUM" NUMBER(18,0),
	"REASON_FOR_SERVICE_CODE" VARCHAR2(2),
	"PROFESSIONAL_SERVICE_CODE" VARCHAR2(2),
	"RESULT_OF_SERVICE" VARCHAR2(2),
	"LEVEL_OF_EFFORT" VARCHAR2(2),
	"BILLING_QTY" NUMBER(13,3),
	"ORDER_NUM" NUMBER(18,0),
	"FACILITY_ORDER_NUM" VARCHAR2(10),
	"DM_DELIVERY_METHOD_KEY" NUMBER(18,0),
	"LTC_FACILITY_KEY" NUMBER(18,0),
	"LTC_PATIENT_KEY" NUMBER(18,0),
	"LTC_BILL_STATUS" CHAR(1),
	"LTC_BILLING_QTY" NUMBER(13,3),
	"LTC_DAYS_SUPPLY" NUMBER(9,3),
	"LTC_BILLING_DAYS" NUMBER(5,0),
	"LTC_CARRY_OVER_QTY" NUMBER(13,3),
	"LTC_BILL_DATE_KEY" NUMBER(18,0),
	"LTC_BILLING_TYPE" CHAR(1),
	"LTC_FACILITY_NODE_KEY" NUMBER(18,0),
	"USER_DEF_1" VARCHAR2(100),
	"USER_DEF_2" VARCHAR2(100),
	"USER_DEF_3" VARCHAR2(100),
	"FACILITY_PLAN_NUM" VARCHAR2(20),
	"DISPENSED_ITEM_LOT_NUMBER" VARCHAR2(20),
	"DISPENSED_ITEM_EXPIRATION_DATE" DATE,
	"UNSOLD_DATE_KEY" NUMBER,
	"RX_ORIGIN_CODE" CHAR(1),
	"PRDC_CHAR_KEY" NUMBER(18,0),
	"IS_BAR_SOURCE" CHAR(1),
	"IS_EDIT_TP_SOURCE" CHAR(1),
	"IS_PARTIAL_AUTOBILLED" CHAR(1),
	"IS_PARTIAL_AUTOBILLED_SOURCE" CHAR(1),
	"IS_SAME_DAY_REVERSAL" CHAR(1) DEFAULT 'N' NOT NULL ENABLE,
	"LATIN_FREQUENCY_QTY" NUMBER(9,0),
	"PRESCRIBER_ORDER_NUMBER" VARCHAR2(35),
	"BAR_SYS_USER" NUMBER(18,0),
	"TP_CASH_MESSAGE_NUM" NUMBER(18,0),
	"RX_STATUS_KEY" NUMBER(18,0),
	 CONSTRAINT "FK_ACCOUNT_4" FOREIGN KEY ("AD_ACCOUNT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."ACCOUNT" ("AD_ACCOUNT_KEY") DISABLE,
	 CONSTRAINT "FK_AGENCY_TYPE_2" FOREIGN KEY ("ATD_AGENCY_TYPE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."AGENCY_TYPE" ("ATD_AGENCY_TYPE_KEY") DISABLE,
	 CONSTRAINT "FK_BILLING_STATUS_TYPE_1" FOREIGN KEY ("BS_BILLING_STATUS_KEY")
	  REFERENCES "TREXONE_DW_DATA"."BILLING_STATUS_TYPE" ("BS_BILLING_STATUS_KEY") DISABLE,
	 CONSTRAINT "FK_COUPON_TYPE_1" FOREIGN KEY ("C_COUPON_TYPE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."COUPON_TYPE" ("C_COUPON_TYPE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_3" FOREIGN KEY ("ORDER_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_59" FOREIGN KEY ("OVERRIDE_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_86" FOREIGN KEY ("ADJUDICATION_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_90" FOREIGN KEY ("PRESCRIBED_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DAW_CODE_TYPE_1" FOREIGN KEY ("DC_DAW_CODE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DAW_CODE_TYPE" ("DC_DAW_CODE_KEY") DISABLE,
	 CONSTRAINT "FK_DRUG_10" FOREIGN KEY ("DISPENSED_DRUG_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DRUG" ("DRUG_KEY") DISABLE,
	 CONSTRAINT "FK_DRUG_11" FOREIGN KEY ("DRUG_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DRUG" ("DRUG_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_1" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_FILL_CATEGORY_TYPE_1" FOREIGN KEY ("FILL_CATEGORY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FILL_CATEGORY_TYPE" ("FILL_CATEGORY_KEY") DISABLE,
	 CONSTRAINT "FK_FILL_PRICING_IND_1" FOREIGN KEY ("FILL_PRICING_IND_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FILL_PRICING_IND" ("FILL_PRICING_IND_KEY") DISABLE,
	 CONSTRAINT "FK_FILL_STATUS_TYPE_1" FOREIGN KEY ("FS_FILL_STATUS_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FILL_STATUS_TYPE" ("FS_FILL_STATUS_KEY") DISABLE,
	 CONSTRAINT "FK_LATIN_FREQUENCY_TYPE_1" FOREIGN KEY ("LF_LATIN_FREQUENCY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."LATIN_FREQUENCY_TYPE" ("LF_LATIN_FREQUENCY_KEY") DISABLE,
	 CONSTRAINT "FK_MESSAGE_CATEGORY_TYPE_1" FOREIGN KEY ("MC_MESSAGE_CATEGORY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."MESSAGE_CATEGORY_TYPE" ("MC_MESSAGE_CATEGORY_KEY") DISABLE,
	 CONSTRAINT "FK_NCPDP_REASON_TYPE_1" FOREIGN KEY ("NCPDP_KEY")
	  REFERENCES "TREXONE_DW_DATA"."NCPDP_REASON_TYPE" ("NCPDP_KEY") DISABLE,
	 CONSTRAINT "FK_ORDER_SOURCE_TYPE_1" FOREIGN KEY ("OS_ORDER_SOURCE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."ORDER_SOURCE_TYPE" ("OS_ORDER_SOURCE_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_H_7" FOREIGN KEY ("PD_PATIENT_H_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT_H" ("PD_PATIENT_H_KEY") DISABLE,
	 CONSTRAINT "FK_PRESCRIBER_7" FOREIGN KEY ("PRS_PRESCRIBER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRESCRIBER" ("PRS_PRESCRIBER_KEY") DISABLE,
	 CONSTRAINT "FK_PRESCRIBER_ADDRESS_4" FOREIGN KEY ("PADR_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRESCRIBER_ADDRESS" ("PADR_KEY") DISABLE,
	 CONSTRAINT "FK_PRESCRIBER_IDS_3" FOREIGN KEY ("PID_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRESCRIBER_IDS" ("PID_KEY") DISABLE,
	 CONSTRAINT "FK_PRICING_DISCOUNT_TYPE_1" FOREIGN KEY ("BLLNG_PRICING_DSCNT1_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRICING_DISCOUNT_TYPE" ("PRICING_DISCOUNT_KEY") DISABLE,
	 CONSTRAINT "FK_PRICING_DISCOUNT_TYPE_2" FOREIGN KEY ("BLLNG_PRICING_DSCNT2_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRICING_DISCOUNT_TYPE" ("PRICING_DISCOUNT_KEY") DISABLE,
	 CONSTRAINT "FK_PRICING_DISCOUNT_TYPE_3" FOREIGN KEY ("BLLNG_PRICING_DSCNT3_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRICING_DISCOUNT_TYPE" ("PRICING_DISCOUNT_KEY") DISABLE,
	 CONSTRAINT "FK_PRICING_DISCOUNT_TYPE_4" FOREIGN KEY ("CNTRCT_PRICING_DSCNT1_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRICING_DISCOUNT_TYPE" ("PRICING_DISCOUNT_KEY") DISABLE,
	 CONSTRAINT "FK_PRICING_DISCOUNT_TYPE_5" FOREIGN KEY ("CNTRCT_PRICING_DSCNT2_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRICING_DISCOUNT_TYPE" ("PRICING_DISCOUNT_KEY") DISABLE,
	 CONSTRAINT "FK_PRICING_DISCOUNT_TYPE_6" FOREIGN KEY ("CNTRCT_PRICING_DSCNT3_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRICING_DISCOUNT_TYPE" ("PRICING_DISCOUNT_KEY") DISABLE,
	 CONSTRAINT "FK_PRICING_OVERRIDE_CD_TYPE_1" FOREIGN KEY ("PRICING_OVERRIDE_CODE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRICING_OVERRIDE_CODE_TYPE" ("PRICING_OVERRIDE_CODE_KEY") DISABLE,
	 CONSTRAINT "FK_PRODUCT_6" FOREIGN KEY ("PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE,
	 CONSTRAINT "FK_PRODUCT_9" FOREIGN KEY ("DISPENSED_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE,
	 CONSTRAINT "FK_RESPONSIBLE_PARTY_TYPE_1" FOREIGN KEY ("RESPONSIBLE_PARTY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."RESPONSIBLE_PARTY_TYPE" ("RESPONSIBLE_PARTY_KEY") DISABLE,
	 CONSTRAINT "FK_SYS_USER_4" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE,
	 CONSTRAINT "FK_SYS_USER_65" FOREIGN KEY ("OVERRIDE_SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE,
	 CONSTRAINT "FK_SYS_USER_66" FOREIGN KEY ("OVERRIDE_RPH_SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE,
	 CONSTRAINT "FK_THERAPEUTIC_SUB_CODE_TYPE_1" FOREIGN KEY ("TSC_THERAPUETIC_SUB_CODE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."THERAPEUTIC_SUB_CODE_TYPE" ("TSC_THERAPUETIC_SUB_CODE_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_27" FOREIGN KEY ("ADJUDICATION_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_TP_PATIENT_2" FOREIGN KEY ("TPD_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TP_PATIENT" ("TPD_KEY") DISABLE,
	 CONSTRAINT "FK_TP_PLAN_2" FOREIGN KEY ("TPLD_PLAN_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TP_PLAN" ("TPLD_PLAN_KEY") DISABLE,
	 CONSTRAINT "FK_TP_WORKERS_COMP_2" FOREIGN KEY ("TWED_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TP_WORKERS_COMP" ("TWED_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_7" FOREIGN KEY ("PD_PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") DISABLE,
	 CONSTRAINT "FK_DELIVERY_METHOD_TYPE_02" FOREIGN KEY ("DM_DELIVERY_METHOD_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DELIVERY_METHOD_TYPE" ("DM_DELIVERY_METHOD_KEY") DISABLE,
	 CONSTRAINT "FK_LTC_FACILITY_05" FOREIGN KEY ("LTC_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."LTC_FACILITY" ("LTC_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_LTC_PATIENT_04" FOREIGN KEY ("LTC_PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."LTC_PATIENT" ("LTC_PATIENT_KEY") DISABLE,
	 CONSTRAINT "FK_TP_PROCESSOR_01" FOREIGN KEY ("TP_PROCESSOR_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TP_PROCESSOR" ("TP_PROCESSOR_KEY") DISABLE,
	 CONSTRAINT "FK_ELIGIBILITY_CLARIF_01" FOREIGN KEY ("EC_ELIGIBILITY_CLARIF_KEY")
	  REFERENCES "TREXONE_DW_DATA"."ELIGIBILITY_CLARIF" ("EC_ELIGIBILITY_CLARIF_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_113" FOREIGN KEY ("LTC_BILL_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_LTC_FACILITY_NODE_09" FOREIGN KEY ("LTC_FACILITY_NODE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."LTC_FACILITY_NODE" ("LTC_FACILITY_NODE_KEY") DISABLE,
	 CONSTRAINT "FK_SYS_USER_89" FOREIGN KEY ("INFO_CLAIM_SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_51" FOREIGN KEY ("CANCEL_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_52" FOREIGN KEY ("DATE_OF_SERVICE_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_53" FOREIGN KEY ("DISPENSE_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_54" FOREIGN KEY ("EXPIRY_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_55" FOREIGN KEY ("FIRST_FILL_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_56" FOREIGN KEY ("LAST_FILL_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_57" FOREIGN KEY ("PROMISE_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_58" FOREIGN KEY ("READY_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_59" FOREIGN KEY ("SOLD_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_60" FOREIGN KEY ("WRITTEN_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_61" FOREIGN KEY ("RTP_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_131" FOREIGN KEY ("CANCEL_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_132" FOREIGN KEY ("DATE_OF_SERVICE_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_133" FOREIGN KEY ("DISPENSE_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_134" FOREIGN KEY ("EXPIRY_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_135" FOREIGN KEY ("FIRST_FILL_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_136" FOREIGN KEY ("LAST_FILL_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_137" FOREIGN KEY ("PROMISE_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_138" FOREIGN KEY ("READY_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_139" FOREIGN KEY ("RTP_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_140" FOREIGN KEY ("SOLD_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_141" FOREIGN KEY ("UNSOLD_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_142" FOREIGN KEY ("WRITTEN_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_IMAGE_05" FOREIGN KEY ("IMAGE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."IMAGE" ("IMAGE_KEY") DISABLE,
	 CONSTRAINT "FK_PRODUCT_CHARACTERISTICS_03" FOREIGN KEY ("PRDC_CHAR_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT_CHARACTERISTICS" ("PRDC_CHAR_KEY") DISABLE,
	 CONSTRAINT "FK_RX_STATUS_02" FOREIGN KEY ("RX_STATUS_KEY")
	  REFERENCES "TREXONE_DW_DATA"."RX_STATUS" ("RX_STATUS_KEY") ENABLE NOVALIDATE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
