-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."FILL_PRICING_IND"
   (	"FILL_PRICING_IND_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PRICE_LINKING_OCCURRED_IND" CHAR(1),
	"WAS_OVERRIDDEN_IND" CHAR(1),
	"MINIMUM_WAS_APPLIED" CHAR(1),
	"POS_PRICE_WAS_USED" CHAR(1),
	"COPAY_WAS_OVERRIDDEN_IND" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100)
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_FILL_PRICING_IND" ON "TREXONE_DW_DATA"."FILL_PRICING_IND" ("FILL_PRICING_IND_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."FILL_PRICING_IND" ADD CONSTRAINT "PK_FILL_PRICING_IND" PRIMARY KEY ("FILL_PRICING_IND_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_FILL_PRICING_IND"  ENABLE;
-- ==========================================
