-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."FILL_WORKFLOW_FACT"
   (	"FWFS_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"WFSD_KEY" NUMBER(18,0),
	"PD_PATIENT_H_KEY" NUMBER(18,0),
	"FD_FACILITY_KEY" NUMBER(18,0),
	"PRD_PRODUCT_KEY" NUMBER(18,0),
	"DRUG_KEY" NUMBER(18,0),
	"PRS_PRESCRIBER_KEY" NUMBER(18,0),
	"FWFS_ORDER_DATE" DATE,
	"FWFS_TRAIL_INDICATOR" CHAR(1),
	"FWFS_PARTIAL_INDICATOR" CHAR(10),
	"FWFS_DT_IN" DATE,
	"FWFS_DT_OUT" DATE,
	"FWFS_DELIVERY_METHOD_NUM" NUMBER(18,0),
	"FWFS_PROC_INST_SEQ" NUMBER(18,0),
	"FWFS_NODE_SEQ" NUMBER(18,0),
	"FWFS_NODE_INSTANCE_SEQ" NUMBER(18,0),
	"FWFS_IS_DECLINED" VARCHAR2(1),
	"FWFS_INTERNAL_FILL_ID" NUMBER,
	"FWFS_ORDER_PRIORITY" NUMBER(1,0),
	"FWFS_PICKUP_TIME" DATE,
	"OS_ORDER_SOURCE_KEY" NUMBER(18,0),
	"DM_DELIVERY_METHOD_KEY" NUMBER(18,0),
	"FS_FILL_STATUS_KEY" NUMBER(18,0),
	"DR_DECLINE_REASON_KEY" NUMBER(18,0),
	"FWFS_RX_NUMBER" VARCHAR2(20),
	"SYS_USER_KEY" NUMBER(18,0),
	"FWFS_PROCESS_DEF_NUM" NUMBER(18,0),
	"FWFS_RX_TRANSACTION_CODE" VARCHAR2(255),
	"FWFS_REFILL_NUM" NUMBER(18,0),
	"FWFS_RX_RECORD_NUM" NUMBER(18,0),
	"FWFS_RX_FILL_SEQ" NUMBER(18,0),
	"IS_OUT_OF_STOCK" VARCHAR2(7),
	"READY_DATE" DATE,
	"FWFS_AUTO_RETRY_RELEASED" VARCHAR2(7),
	"CENTRAL_FILL_INDICATOR_KEY" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PD_PATIENT_KEY" NUMBER(18,0),
	"RX_TRANSACTION_CODE" VARCHAR2(255),
	"WORKFLOW_QUEUE_NUM" NUMBER,
	"FWFS_QTY_DISPENSED" NUMBER(13,3),
	"FWFS_IS_BAR" CHAR(1),
	"FWFS_COMPLETE_FACILITY_KEY" NUMBER(18,0),
	"FACILITY_ORDER_NUMBER" VARCHAR2(10),
	"OWNING_FACILITY_KEY" NUMBER(18,0),
	"PARTIAL_FILL_SEQ" NUMBER(2,0),
	"FWFS_DT_QUEUE" DATE,
	"NEXT_WFSD_KEY" NUMBER(18,0),
	"WRITTEN_QTY" NUMBER(17,6),
	"PADR_KEY" NUMBER(18,0),
	"FWFS_ELCTRNC_ORD_SBMT_DT" DATE,
	 CONSTRAINT "FK_CENTRAL_FILL_INDICATOR_2" FOREIGN KEY ("CENTRAL_FILL_INDICATOR_KEY")
	  REFERENCES "TREXONE_DW_DATA"."CENTRAL_FILL_INDICATOR" ("CENTRAL_FILL_INDICATOR_KEY") DISABLE,
	 CONSTRAINT "FK_DECLINE_REASON_TYPE_2" FOREIGN KEY ("DR_DECLINE_REASON_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DECLINE_REASON_TYPE" ("DR_DECLINE_REASON_KEY") DISABLE,
	 CONSTRAINT "FK_DELIVERY_METHOD_TYPE_2" FOREIGN KEY ("DM_DELIVERY_METHOD_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DELIVERY_METHOD_TYPE" ("DM_DELIVERY_METHOD_KEY") DISABLE,
	 CONSTRAINT "FK_DRUG_2" FOREIGN KEY ("DRUG_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DRUG" ("DRUG_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_6" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_FILL_STATUS_TYPE_6" FOREIGN KEY ("FS_FILL_STATUS_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FILL_STATUS_TYPE" ("FS_FILL_STATUS_KEY") DISABLE,
	 CONSTRAINT "FK_ORDER_SOURCE_TYPE_2" FOREIGN KEY ("OS_ORDER_SOURCE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."ORDER_SOURCE_TYPE" ("OS_ORDER_SOURCE_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_H_12" FOREIGN KEY ("PD_PATIENT_H_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT_H" ("PD_PATIENT_H_KEY") DISABLE,
	 CONSTRAINT "FK_PRESCRIBER_3" FOREIGN KEY ("PRS_PRESCRIBER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRESCRIBER" ("PRS_PRESCRIBER_KEY") DISABLE,
	 CONSTRAINT "FK_PRODUCT_5" FOREIGN KEY ("PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE,
	 CONSTRAINT "FK_SYS_USER_38" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE,
	 CONSTRAINT "FK_WF_STEP_2" FOREIGN KEY ("WFSD_KEY")
	  REFERENCES "TREXONE_DW_DATA"."WF_STEP" ("WFSD_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_12" FOREIGN KEY ("PD_PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_105" FOREIGN KEY ("FWFS_COMPLETE_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_109" FOREIGN KEY ("OWNING_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") ENABLE
   )
  PARTITION BY RANGE ("FWFS_ORDER_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PKFILL_WORKFLOW_FACT" ON "TREXONE_DW_DATA"."FILL_WORKFLOW_FACT" ("FWFS_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."FILL_WORKFLOW_FACT" ADD CONSTRAINT "PKFILL_WORKFLOW_FACT" PRIMARY KEY ("FWFS_KEY")
  USING INDEX "TREXONE_DW_DATA"."PKFILL_WORKFLOW_FACT"  ENABLE;
-- ==========================================
