-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."FILL_FACT"
   (	"FILL_FACT_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"ORDER_DATE_KEY" NUMBER(18,0),
	"ORDER_TIME_KEY" NUMBER(5,0),
	"PRESCRIBED_DATE_KEY" NUMBER(18,0),
	"READY_DATE_KEY" NUMBER(18,0),
	"READY_TIME_KEY" NUMBER(5,0),
	"PROMISE_DATE_KEY" NUMBER(18,0),
	"PROMISE_TIME_KEY" NUMBER(5,0),
	"EXPIRY_DATE_KEY" NUMBER(18,0),
	"PD_PATIENT_H_KEY" NUMBER(18,0),
	"PATIENT_DEMOGRAPHIC_KEY" NUMBER(18,0),
	"PATIENT_HEALTH_KEY" NUMBER(18,0),
	"PATIENT_OPTION_KEY" NUMBER(18,0),
	"PATIENT_PROFILE_KEY" NUMBER(18,0),
	"PATIENT_PRIVACY_RESTRICT_KEY" NUMBER(18,0),
	"PRS_PRESCRIBER_KEY" NUMBER(18,0),
	"PRSH_PRESCRIBER_KEY" NUMBER(18,0),
	"PADR_KEY" NUMBER(18,0),
	"FD_FACILITY_KEY" NUMBER(18,0),
	"PRD_PRODUCT_KEY" NUMBER(18,0),
	"MCD_KEY" NUMBER(18,0),
	"OS_ORDER_SOURCE_KEY" NUMBER(18,0),
	"LF_LATIN_FREQUENCY_KEY" NUMBER(18,0),
	"GS_GENERIC_SUB_KEY" NUMBER(18,0),
	"TSC_THERAPUETIC_SUB_CODE_KEY" NUMBER(18,0),
	"DC_DAW_CODE_KEY" NUMBER(18,0),
	"FILL_INDICATOR_KEY" NUMBER(18,0),
	"DM_DELIVERY_METHOD_KEY" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"RX_FILL_SEQ" NUMBER(18,0),
	"RX_NUMBER" VARCHAR2(20),
	"FACILITY_ORDER_NUMBER" VARCHAR2(10),
	"REFILL_NUM" NUMBER(18,0),
	"FIRST_FILL_QTY" NUMBER(18,6),
	"NEXT_FILL_QTY" NUMBER(13,3),
	"REFILL_QTY" NUMBER(21,3),
	"QTY_DISPENSED" NUMBER(13,3),
	"METRIC_QTY_DISPENSED" NUMBER(13,3),
	"INTENDED_QTY_DISPENSED" NUMBER(13,3),
	"INTENDED_DAYS_SUPPLY" NUMBER(9,3),
	"DAYS_SUPPLY" NUMBER(18,0),
	"ORDER_QUOTE_PRICE" NUMBER(18,6),
	"TP_PRICE_PAID" NUMBER(18,6),
	"PATIENT_PRICE_PAID" NUMBER(18,6),
	"TOTAL_PRICE_PAID" NUMBER(18,6),
	"DISPENSED_QTY_AWP" NUMBER(17,6),
	"FILL_DURATION_SECS" NUMBER(18,6),
	"PARTITION_DATE" DATE,
	"FS_FILL_STATUS_KEY" NUMBER(18,0),
	"VERIFY_RPH_SYS_USER_KEY" NUMBER(18,0),
	"DISPENSED_PRD_PRODUCT_KEY" NUMBER(18,0),
	"TRANSACTION_DATE" DATE,
	"CANCEL_DATE_KEY" NUMBER(18,0),
	"CANCEL_TIME_KEY" NUMBER(18,0),
	"CENTRAL_FILL_FD_FACILITY_KEY" NUMBER(18,0),
	"CF_LOCAL_PRD_PRODUCT_KEY" NUMBER(18,0),
	"USER_DEFINED_STEP_AMT" NUMBER,
	"PATIENT_TAX_AMT" NUMBER(17,6),
	"TP_TAX_AMT" NUMBER(17,6),
	"TRIPLICATE_SERIAL_NUM" VARCHAR2(30),
	"TOTAL_UNC" NUMBER(19,8),
	"FULL_PACKAGE_UNC" NUMBER(19,8),
	"NON_DISCOUNTED_UNC" NUMBER(19,8),
	"TRANSACTION_CODE" VARCHAR2(100),
	"WRITTEN_DATE_KEY" NUMBER(18,0),
	"WRITTEN_TIME_KEY" NUMBER(18,0),
	"FIRST_FILL_DATE_KEY" NUMBER(18,0),
	"FIRST_FILL_TIME_KEY" NUMBER(18,0),
	"WRITTEN_QTY" NUMBER,
	"TOTAL_REFILLS_ALLOWED" NUMBER,
	"TOTAL_REFILLS_REMAINING" NUMBER,
	"SOLD_DATE_KEY" NUMBER(18,0),
	"SOLD_TIME_KEY" NUMBER(18,0),
	"DISPENSED_DATE_KEY" NUMBER(18,0),
	"DISPENSED_TIME_KEY" NUMBER(18,0),
	"ADJUDICATION_GROUP_NUM" NUMBER,
	"WRITTEN_DRUG_KEY" NUMBER(18,0),
	"DISPENSED_DRUG_KEY" NUMBER(18,0),
	"LAST_FILL_DATE_KEY" NUMBER(18,0),
	"LAST_FILL_TIME_KEY" NUMBER(18,0),
	"PRIMARY_TPLD_PLAN_KEY" NUMBER(18,0),
	"IS_COB" CHAR(1),
	"COST_PRICING_FORMULA_NAME" VARCHAR2(30),
	"IS_BAR" CHAR(1),
	"OVERRIDE_AMOUNT" NUMBER(17,6),
	"OVERRIDE_CODE_KEY" NUMBER(18,0),
	"ERP_ENROLLMENT_CODE_NUM" NUMBER(18,0),
	"ERP_ENROLLMENT_STATUS_DATE" DATE,
	"ERP_ENROLLMENT_REASON_CODE_NUM" NUMBER(18,0),
	"ERP_TARGET_DATE" DATE,
	"ERP_EXCLUSION_REASON_CODE_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PD_PATIENT_KEY" NUMBER(18,0),
	"CRF_SEQ_NUM" NUMBER,
	"IS_340B" CHAR(1),
	"COUNSELING_ACCEPTED" CHAR(1),
	"COUNSELING_COMMENTS" VARCHAR2(100),
	"COUNSELING_NAME" VARCHAR2(100),
	"COUNSELING_INITIALS" VARCHAR2(3),
	"UNSOLD_DATE_KEY" NUMBER,
	"DATA_ENTRY_USER_INITIAL" VARCHAR2(30),
	"DISP_USER_INITIAL" VARCHAR2(30),
	"COUNSELING_SIGN_IMAGE_KEY" NUMBER(18,0),
	"IS_RETURNED_TO_STOCK" CHAR(1),
	"RET_TO_STCK_QTY" NUMBER(13,3),
	"RET_TO_STCK_DT_KEY" NUMBER(18,0),
	"SIG" VARCHAR2(2000),
	"ADJUDICATION_DATE_KEY" NUMBER,
	"ADJ_DATE_OF_SERVICE_KEY" NUMBER,
	"BILLED_AMOUNT" NUMBER,
	"RTP_DATE_KEY" NUMBER,
	"RTP_TIME_KEY" NUMBER,
	"TPD_KEY" NUMBER,
	"IS_ERP_OPPORTUNITY" CHAR(1),
	"PATIENT_ERP_ENROLLMENT_STATUS" NUMBER(18,0),
	"ORDER_NUM" NUMBER(18,0),
	"SHIPMENT_NUM" NUMBER(18,0),
	"MCKESSON_GENERIC_OPPORTUNITY" CHAR(1),
	"MCKESSON_GENERIC_STATUS" CHAR(1),
	"DISPENSING_FEE_AMOUNT" NUMBER(17,6),
	"INGREDIENT_COST" NUMBER(17,6),
	"MCKESSON_GENERIC_AVAIL" CHAR(1),
	"IS_SERVICE" CHAR(1),
	"IS_AUTO_DISPENSED" CHAR(1),
	"LTC_FACILITY_KEY" NUMBER(18,0),
	"LTC_PATIENT_KEY" NUMBER(18,0),
	"LTC_PACKAGING_METHOD_KEY" NUMBER(18,0),
	"LTC_RX_START_DATE_KEY" NUMBER(18,0),
	"LTC_RX_DUE_DATE_KEY" NUMBER(18,0),
	"LTC_RX_STOP_DATE_KEY" NUMBER(18,0),
	"LTC_RX_CYCLE_FILL_IND" CHAR(1),
	"LTC_BILLING_TYPE" CHAR(1),
	"LTC_MAINTENANCE_DRUG" CHAR(1),
	"LTC_DELIVERY_DATE_KEY" NUMBER(18,0),
	"LTC_FACILITY_NODE_KEY" NUMBER(18,0),
	"RX_EXPIRY_DATE_KEY" NUMBER(18,0),
	"RX_EXPIRY_TIME_KEY" NUMBER(5,0),
	"DATA_ENTRY_USER_KEY" NUMBER(18,0),
	"DISPENSING_USER_KEY" NUMBER(18,0),
	"LTC_HOA_KEY" NUMBER(18,0),
	"LOCAL_TRANSACTION_DATE" DATE,
	"FUTURE_FILL_DATE_KEY" NUMBER(18,0),
	"IS_PRN" CHAR(1),
	"PRIORITY" NUMBER(9,0),
	"IS_MAIL" CHAR(1),
	"IS_EDIT_TP" CHAR(1),
	"RX_ORIGIN_CODE" CHAR(1),
	"PARTIAL_FILL_SEQ" NUMBER(2,0),
	"IS_PARTIAL_FILL_BILLED" CHAR(1),
	"PRDC_CHAR_KEY" NUMBER(18,0),
	"IS_BAR_SOURCE" CHAR(1),
	"IS_EDIT_TP_SOURCE" CHAR(1),
	"IS_PARTIAL_AUTOBILLED" CHAR(1),
	"IS_PARTIAL_AUTOBILLED_SOURCE" CHAR(1),
	"IS_SPLIT_ORDER" CHAR(1),
	"SPLIT_ORDER_USER_KEY" NUMBER(18,0),
	"SPLIT_ORDER_DATE" DATE,
	"SYNC_DATE_KEY" NUMBER(18,0),
	"OS_ITEM_SOURCE_KEY" NUMBER(18,0),
	"IS_SAME_DAY_REVERSAL" CHAR(1) DEFAULT 'N' NOT NULL ENABLE,
	"LATIN_FREQUENCY_QTY" NUMBER(9,0),
	"INCENTIVE_FEE_AMOUNT" NUMBER(17,6),
	"TOTAL_TAX" NUMBER(17,6),
	"SKIP_PRE_VER_CODE" NUMBER(2,0),
	"BIN_NAME" VARCHAR2(30),
	"FOA_DATE" DATE,
	"DISPENSED_ITEM_LOT_NUMBER" VARCHAR2(20),
	"ACUTE_PROMISE_REASON_CODE" VARCHAR2(30),
	"H_LEVEL" NUMBER,
	"REQUIRE_CONSENT_TO_FILL" CHAR(1),
	"USER_CONSENTED_TO_FILL" VARCHAR2(255),
	"DATE_CONSENTED_TO_FILL" DATE,
	"IS_CONSENTED_TO_FILL" CHAR(1),
	"ERP_USER_MODIFIED_TARGET_DATE" DATE,
	"ERP_UM_DATE_BY" NUMBER(18,0),
	"ERP_UM_DATE_BY_TYPE" CHAR(1),
	"ERP_UM_DATE_MODIFIED_ON" DATE,
	"IS_FAST_TRACKED" CHAR(1),
	"HOA" VARCHAR2(4000),
	"DISPENSED_ITEM_GTIN_NUMBER" VARCHAR2(25),
	"DISPENSED_ITEM_SERIAL_NUMBER" VARCHAR2(20),
	"DISPENSED_ITEM_EXPIRATION_DATE" DATE,
	"TOTAL_QTY_REMAINING" NUMBER(14,3),
	"REFUSAL" CHAR(1),
	"MISSED_APT" CHAR(1),
	"ADMINISTERING_SITE" VARCHAR2(30),
	"ROUTE_OF_ADMINISTRATION" VARCHAR2(30),
	"DOSE_NUMBER" VARCHAR2(30),
	"SERIES_COMPLETE" VARCHAR2(30),
	"ADMINISTERING_PROVIDER_NAME" VARCHAR2(90),
	"ADMINISTERING_PROVIDER_SUFFIX" VARCHAR2(30),
	"LOCATION_TYPE" VARCHAR2(30),
	"LOCATION_NAME" VARCHAR2(255),
	"LOCATION_ADDRESS_1" VARCHAR2(100),
	"LOCATION_ADDRESS_2" VARCHAR2(50),
	"LOCATION_ZIPCODE" VARCHAR2(20),
	"LOCATION_CITY" VARCHAR2(40),
	"LOCATION_STATE" VARCHAR2(2),
	"LOCATION_COUNTY_CODE" VARCHAR2(5),
	"LOCATION_PHONE" VARCHAR2(10),
	"VTRCKS_PROVIDER_PIN" VARCHAR2(30),
	"COMORBIDITY_STATUS" VARCHAR2(30),
	"SEROLOGY_RESULTS" VARCHAR2(30),
	"ARE_FIELDS_REQUIRED" CHAR(1),
	"CRF_CREATED_SEQ_NUM" NUMBER,
	"PATIENT_PREFERRED_CONTACT" VARCHAR2(25),
	"PATIENT_PREFERRED_CONTACT_DESC" VARCHAR2(50),
	"THERAPY_TYPE_CODE" CHAR(1),
	"RX_START_DATE" DATE,
	"THERAPY_DAYS" NUMBER(9,3),
	"CONSENT_TO_REPORT" CHAR(1),
	"GUARDIAN_L_NAME" VARCHAR2(50),
	"GUARDIAN_F_NAME" VARCHAR2(30),
	"GUARDIAN_RELATION" VARCHAR2(50),
	"VACCINE_LOT_NUMBER" VARCHAR2(20),
	"VACCINE_EXPIRATION_DATE_KEY" NUMBER(18,0),
	"VACCINE_PROVIDER_L_NAME" VARCHAR2(50),
	"VACCINE_PROVIDER_F_NAME" VARCHAR2(30),
	"VACCINE_PROVIDER_ID" VARCHAR2(15),
	"FUNDING_SOURCE" VARCHAR2(30),
	"VFC_STATUS" VARCHAR2(20),
	"TARGET_POPULATION" VARCHAR2(30),
	"VACCINE_ADMIN_DATE_KEY" NUMBER(18,0),
	"VACCINE_LOCATION_ID" VARCHAR2(80),
	"RX_STATUS_KEY" NUMBER(18,0),
	"SPR_COMPLETION_DATE_KEY" NUMBER(18,0),
	"SPR_COMPLETION_TIME_KEY" NUMBER(18,0),
	"SPR_COMPLETION_USER_KEY" NUMBER(18,0),
	"SPR_USER_ACTION" CHAR(1),
	"IS_DISPENSE_LOCAL" CHAR(1),
	"MAPPED_SIG_RECEIVED" VARCHAR2(150),
	"FILL_AS_IS_SELECTED" CHAR(1),
	 CONSTRAINT "FD_FACILITY_85" FOREIGN KEY ("CENTRAL_FILL_FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_60" FOREIGN KEY ("ORDER_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_61" FOREIGN KEY ("PRESCRIBED_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_62" FOREIGN KEY ("READY_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_63" FOREIGN KEY ("PROMISE_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_64" FOREIGN KEY ("EXPIRY_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_77" FOREIGN KEY ("CANCEL_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_87" FOREIGN KEY ("SOLD_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_88" FOREIGN KEY ("DISPENSED_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_89" FOREIGN KEY ("LAST_FILL_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DAW_CODE_TYPE_2" FOREIGN KEY ("DC_DAW_CODE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DAW_CODE_TYPE" ("DC_DAW_CODE_KEY") DISABLE,
	 CONSTRAINT "FK_DELIVERY_METHOD_TYPE_03" FOREIGN KEY ("DM_DELIVERY_METHOD_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DELIVERY_METHOD_TYPE" ("DM_DELIVERY_METHOD_KEY") DISABLE,
	 CONSTRAINT "FK_DRUG_12" FOREIGN KEY ("WRITTEN_DRUG_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DRUG" ("DRUG_KEY") DISABLE,
	 CONSTRAINT "FK_DRUG_13" FOREIGN KEY ("DISPENSED_DRUG_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DRUG" ("DRUG_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_5" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_FILL_INDICATOR_01" FOREIGN KEY ("FILL_INDICATOR_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FILL_INDICATOR" ("FILL_INDICATOR_KEY") DISABLE,
	 CONSTRAINT "FK_FILL_STATUS_TYPE_7" FOREIGN KEY ("FS_FILL_STATUS_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FILL_STATUS_TYPE" ("FS_FILL_STATUS_KEY") DISABLE,
	 CONSTRAINT "FK_GENERIC_SUB_TYPE_1" FOREIGN KEY ("GS_GENERIC_SUB_KEY")
	  REFERENCES "TREXONE_DW_DATA"."GENERIC_SUB_TYPE" ("GS_GENERIC_SUB_KEY") DISABLE,
	 CONSTRAINT "FK_LATIN_FREQUENCY_TYPE_2" FOREIGN KEY ("LF_LATIN_FREQUENCY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."LATIN_FREQUENCY_TYPE" ("LF_LATIN_FREQUENCY_KEY") DISABLE,
	 CONSTRAINT "FK_MEDICAL_CONDITION_3" FOREIGN KEY ("MCD_KEY")
	  REFERENCES "TREXONE_DW_DATA"."MEDICAL_CONDITION" ("MCD_KEY") DISABLE,
	 CONSTRAINT "FK_ORDER_SOURCE_TYPE_4" FOREIGN KEY ("OS_ORDER_SOURCE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."ORDER_SOURCE_TYPE" ("OS_ORDER_SOURCE_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_H_9" FOREIGN KEY ("PD_PATIENT_H_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT_H" ("PD_PATIENT_H_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_DEMOGRAPHIC_02" FOREIGN KEY ("PATIENT_DEMOGRAPHIC_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT_DEMOGRAPHIC" ("PATIENT_DEMOGRAPHIC_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_HEALTH_02" FOREIGN KEY ("PATIENT_HEALTH_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT_HEALTH" ("PATIENT_HEALTH_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_OPTION_02" FOREIGN KEY ("PATIENT_OPTION_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT_OPTION" ("PATIENT_OPTION_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_PRIVACY_RESTRICT_02" FOREIGN KEY ("PATIENT_PRIVACY_RESTRICT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT_PRIVACY_RESTRICTION" ("PATIENT_PRIVACY_RESTRICT_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_PROFILE_02" FOREIGN KEY ("PATIENT_PROFILE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT_PROFILE" ("PATIENT_PROFILE_KEY") DISABLE,
	 CONSTRAINT "FK_PRESCRIBER_8" FOREIGN KEY ("PRS_PRESCRIBER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRESCRIBER" ("PRS_PRESCRIBER_KEY") DISABLE,
	 CONSTRAINT "FK_PRESCRIBER_ADDRESS_5" FOREIGN KEY ("PADR_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRESCRIBER_ADDRESS" ("PADR_KEY") DISABLE,
	 CONSTRAINT "FK_PRESCRIBER_H_2" FOREIGN KEY ("PRSH_PRESCRIBER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRESCRIBER_H" ("PRSH_PRESCRIBER_KEY") DISABLE,
	 CONSTRAINT "FK_PRODUCT_26" FOREIGN KEY ("DISPENSED_PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE,
	 CONSTRAINT "FK_PRODUCT_37" FOREIGN KEY ("CF_LOCAL_PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE,
	 CONSTRAINT "FK_PRODUCT_7" FOREIGN KEY ("PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE,
	 CONSTRAINT "FK_SYS_USER_69" FOREIGN KEY ("VERIFY_RPH_SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE,
	 CONSTRAINT "FK_THERAPEUTIC_SUB_CODE_TYPE_2" FOREIGN KEY ("TSC_THERAPUETIC_SUB_CODE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."THERAPEUTIC_SUB_CODE_TYPE" ("TSC_THERAPUETIC_SUB_CODE_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_01" FOREIGN KEY ("ORDER_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_02" FOREIGN KEY ("PROMISE_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_03" FOREIGN KEY ("READY_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_17" FOREIGN KEY ("CANCEL_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_28" FOREIGN KEY ("SOLD_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_29" FOREIGN KEY ("DISPENSED_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_30" FOREIGN KEY ("LAST_FILL_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_TP_PLAN_9" FOREIGN KEY ("PRIMARY_TPLD_PLAN_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TP_PLAN" ("TPLD_PLAN_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_9" FOREIGN KEY ("PD_PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") DISABLE,
	 CONSTRAINT "FK_LTC_FACILITY_03" FOREIGN KEY ("LTC_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."LTC_FACILITY" ("LTC_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_LTC_FACILITY_NODE_05" FOREIGN KEY ("LTC_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."LTC_FACILITY_NODE" ("LTC_FACILITY_NODE_KEY") DISABLE,
	 CONSTRAINT "FK_LTC_PATIENT_02" FOREIGN KEY ("LTC_PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."LTC_PATIENT" ("LTC_PATIENT_KEY") DISABLE,
	 CONSTRAINT "FK_LTC_FILL_FACT_4" FOREIGN KEY ("LTC_PACKAGING_METHOD_KEY")
	  REFERENCES "TREXONE_DW_DATA"."LTC_PACKAGING_METHOD_TYPE" ("LTC_PACKAGING_METHOD_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_107" FOREIGN KEY ("LTC_RX_START_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_108" FOREIGN KEY ("LTC_RX_DUE_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_109" FOREIGN KEY ("LTC_RX_STOP_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_110" FOREIGN KEY ("LTC_DELIVERY_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_LTC_HOA_04" FOREIGN KEY ("LTC_HOA_KEY")
	  REFERENCES "TREXONE_DW_DATA"."LTC_HOA" ("LTC_HOA_KEY") DISABLE,
	 CONSTRAINT "FK_SYS_USER_87" FOREIGN KEY ("DATA_ENTRY_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE,
	 CONSTRAINT "FK_SYS_USER_88" FOREIGN KEY ("DISPENSING_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE,
	 CONSTRAINT "FK_LTC_FACILITY_NODE_08" FOREIGN KEY ("LTC_FACILITY_NODE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."LTC_FACILITY_NODE" ("LTC_FACILITY_NODE_KEY") DISABLE,
	 CONSTRAINT "FK_PRICING_OVERRIDE_CD_TYPE_2" FOREIGN KEY ("OVERRIDE_CODE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRICING_OVERRIDE_CODE_TYPE" ("PRICING_OVERRIDE_CODE_KEY") DISABLE,
	 CONSTRAINT "FK_TP_PATIENT_04" FOREIGN KEY ("TPD_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TP_PATIENT" ("TPD_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_47" FOREIGN KEY ("FIRST_FILL_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_48" FOREIGN KEY ("RTP_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_49" FOREIGN KEY ("RX_EXPIRY_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_50" FOREIGN KEY ("WRITTEN_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_122" FOREIGN KEY ("ADJ_DATE_OF_SERVICE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_123" FOREIGN KEY ("ADJUDICATION_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_124" FOREIGN KEY ("FIRST_FILL_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_125" FOREIGN KEY ("FUTURE_FILL_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_126" FOREIGN KEY ("RET_TO_STCK_DT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_127" FOREIGN KEY ("RTP_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_128" FOREIGN KEY ("RX_EXPIRY_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_129" FOREIGN KEY ("UNSOLD_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_130" FOREIGN KEY ("WRITTEN_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_IMAGE_06" FOREIGN KEY ("COUNSELING_SIGN_IMAGE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."IMAGE" ("IMAGE_KEY") DISABLE,
	 CONSTRAINT "FK_PRODUCT_CHARACTERISTICS_02" FOREIGN KEY ("PRDC_CHAR_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT_CHARACTERISTICS" ("PRDC_CHAR_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_153" FOREIGN KEY ("SYNC_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_ORDER_SOURCE_TYPE_05" FOREIGN KEY ("OS_ITEM_SOURCE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."ORDER_SOURCE_TYPE" ("OS_ORDER_SOURCE_KEY") DISABLE,
	 CONSTRAINT "FK_RX_STATUS_01" FOREIGN KEY ("RX_STATUS_KEY")
	  REFERENCES "TREXONE_DW_DATA"."RX_STATUS" ("RX_STATUS_KEY") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_DATE_DIM_170" FOREIGN KEY ("SPR_COMPLETION_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_TIME_DIM_75" FOREIGN KEY ("SPR_COMPLETION_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_SYS_USER_130" FOREIGN KEY ("SPR_COMPLETION_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") ENABLE NOVALIDATE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_FILL_FACT" ON "TREXONE_DW_DATA"."FILL_FACT" ("FILL_FACT_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."FILL_FACT" ADD CONSTRAINT "PK_FILL_FACT" PRIMARY KEY ("FILL_FACT_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_FILL_FACT"  ENABLE;
-- ==========================================
