-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."GENERIC_SUB_GROUP_PRODUCT"
   (	"GENERIC_SUB_GROUP_PRODUCT_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"GENERIC_SUB_GROUP_PRODUCT_NUM" NUMBER(18,0),
	"PRD_PRODUCT_KEY" NUMBER(18,0),
	"PRD_SUBSTITUTED_PRODUCT_KEY" NUMBER(18,0),
	"RANK" NUMBER(3,0),
	"SYS_USER_KEY" NUMBER(18,0),
	"SUBSTITUTION_TYPE" VARCHAR2(1),
	"CREATED_DATE_KEY" NUMBER(18,0),
	"MODIFIED_DATE_KEY" NUMBER(18,0),
	"IS_ACTIVE" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID'),
	 CONSTRAINT "PK_GENERIC_SUB_GROUP_PRODUCT" PRIMARY KEY ("GENERIC_SUB_GROUP_PRODUCT_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_PRODUCT_48" FOREIGN KEY ("PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_143" FOREIGN KEY ("CREATED_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_144" FOREIGN KEY ("MODIFIED_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_PRODUCT_56" FOREIGN KEY ("PRD_SUBSTITUTED_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE,
	 CONSTRAINT "FK_SYS_USER_90" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE
   ) ;
-- ==========================================
