-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."GOOD_FAITH_EFFORT_REASON_TYPE"
   (	"GFE_GOOD_FAITH_EFFORT_RSN_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"GFE_GOOD_FAITH_EFFORT_RSN_NUM" NUMBER(18,0),
	"GFE_DESCRIPTION" VARCHAR2(100),
	"GFE_UPDATE_DT" DATE,
	"GFE_CREATE_DT" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_GOOD_FAITH_EFFORT_REASON" ON "TREXONE_DW_DATA"."GOOD_FAITH_EFFORT_REASON_TYPE" ("GFE_GOOD_FAITH_EFFORT_RSN_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."GOOD_FAITH_EFFORT_REASON_TYPE" ADD CONSTRAINT "PK_GOOD_FAITH_EFFORT_REASON" PRIMARY KEY ("GFE_GOOD_FAITH_EFFORT_RSN_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_GOOD_FAITH_EFFORT_REASON"  ENABLE;
-- ==========================================
