-- ==========================================

  CREATE GLOBAL TEMPORARY TABLE "TREXONE_DW_DATA"."GTT_PATIENT_ADDRESS_STG"
   (	"PD_PATIENT_KEY" NUMBER(18,0),
	"ADDRESS1" VARCHAR2(100),
	"ADDRESS2" VARCHAR2(50),
	"CITY" VARCHAR2(40),
	"STATE" VARCHAR2(2),
	"ZIP" VARCHAR2(20),
	"DATESTAMP" DATE,
	"ADDRESS_NUM" NUMBER(18,0),
	"COUNTY" VARCHAR2(30),
	"CTRY_CODE" VARCHAR2(8),
	"POST_OFFICE" VARCHAR2(40),
	"ADDRESS_USAGE" NUMBER(18,0),
	"USAGE" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"STATUS" CHAR(1),
	"EXT" VARCHAR2(6),
	"H_LEVEL" NUMBER,
	"H_TYPE" CHAR(1),
	"COUNTY_CODE" VARCHAR2(5)
   ) ON COMMIT DELETE ROWS ;
-- ==========================================
