-- ==========================================

  CREATE GLOBAL TEMPORARY TABLE "TREXONE_DW_DATA"."GTT_PATIENT_PRIMARY"
   (	"PRIMARY_PATIENT_NUM" NUMBER,
	"PATIENT_NUM" NUMBER,
	"DATESTAMP" DATE,
	"PATIENT_KEY" NUMBER,
	"STATUS" CHAR(1),
	"ADDRESS_USAGE" NUMBER,
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100)
   ) ON COMMIT DELETE ROWS ;
-- ==========================================
