-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."IMG_ANNOTATION_NOTE"
   (	"IMG_ANNOTATION_NOTE_KEY" NUMBER(18,0),
	"IMG_ANNOTATION_NOTE_SEQ" NUMBER(18,0),
	"RX_RECORD_NUM" NUMBER(18,0),
	"NOTE_TEXT" VARCHAR2(4000),
	"CREATE_USER_KEY" NUMBER(18,0),
	"CREATE_TIME_KEY" NUMBER(18,0),
	"CREATE_DATE_KEY" NUMBER(18,0),
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"NUM_UPDATES" NUMBER(9,0),
	"FACILITY_NUM" NUMBER(18,0),
	"IS_ACTIVE" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE,
	"PARTITION_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	"FONT_SIZE" NUMBER(3,0),
	"IMAGE_KEY" NUMBER(18,0),
	"ANNOTATION_UID" VARCHAR2(100),
	 CONSTRAINT "FK_SYS_USER_109" FOREIGN KEY ("CREATE_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_159" FOREIGN KEY ("CREATE_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_69" FOREIGN KEY ("CREATE_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_IMAGE_IMAGE_KEY" FOREIGN KEY ("IMAGE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."IMAGE" ("IMAGE_KEY") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("AUD_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
