-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."INV_ADJUSTMENT_REASON_TYPE"
   (	"IAR_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"CODE" VARCHAR2(3),
	"DESCRIPTION" VARCHAR2(50),
	"IS_ACTIVE" CHAR(1),
	"IS_USER_DEFINED" CHAR(1),
	"IS_DEFAULT" CHAR(1),
	"INV_ADJUST_REASON_NUM" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_INV_ADJUSTMENT_REASON_TYPE" ON "TREXONE_DW_DATA"."INV_ADJUSTMENT_REASON_TYPE" ("IAR_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."INV_ADJUSTMENT_REASON_TYPE" ADD CONSTRAINT "PK_INV_ADJUSTMENT_REASON_TYPE" PRIMARY KEY ("IAR_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_INV_ADJUSTMENT_REASON_TYPE"  ENABLE;
-- ==========================================
