-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."INVENTORY_ITEM_GROUP_SUMMARY"
   (	"INVENTORY_ITEM_GROUP_KEY" NUMBER(18,0),
	"FD_FACILITY_KEY" NUMBER(18,0),
	"PRD_PRODUCT_KEY" NUMBER(18,0),
	"DRUG_KEY" NUMBER(18,0),
	"INVENTORY_ITEM_NUM" NUMBER(18,0),
	"INVENTORY_LOCATION_KEY" NUMBER(18,0),
	"GROUP_KEY" NUMBER(18,0),
	"INV_ITEM_LAST_ACQ_COST_DATE" DATE,
	"INV_ITEM_LAST_ACQ_UNIT_COST" NUMBER(17,6),
	"STORAGE_LOC_CURRENT_QTY" NUMBER(17,6),
	"CURRENT_SUMMARY_DATESTAMP" DATE,
	"EXPECTED_COST" NUMBER(18,8),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"BIN_TYPE_KEY" NUMBER(18,0),
	"COMMITTED_QTY" NUMBER(17,6),
	"EXPECTED_UNIT_COST" NUMBER(18,8),
	"IS_AUTO_DISPENSED" CHAR(1),
	"INV_ITEM_LAST_ACQ_COST" NUMBER(17,6),
	"PRIMARY_VENDOR_NUM" NUMBER(18,0)
   ) ;
-- ==========================================
