-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."INVENTORY_ITEM_FACT_OLD"
   (	"IL_KEY" NUMBER(18,0),
	"INVENTORY_ITEM_NUM" NUMBER(18,0),
	"PRD_PRODUCT_KEY" NUMBER(18,0),
	"DRUG_KEY" NUMBER(18,0),
	"FD_FACILITY_KEY" NUMBER(18,0),
	"DATE_KEY" NUMBER(18,0),
	"BIN_TYPE_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"LAST_ACQ_COST" NUMBER(17,6),
	"LAST_ACQ_COST_DATE" DATE,
	"LAST_ACQ_UNIT_COST" NUMBER(17,6),
	"CURRENT_QTY" NUMBER(17,6),
	"COMMITTED_QTY" NUMBER(17,6),
	"EXPECTED_COST" NUMBER(18,8),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID'),
	"PRIMARY_VENDOR_NUM" NUMBER(18,0),
	"INVENTORY_GROUP_KEY" NUMBER(18,0) DEFAULT 0,
	"EXPECTED_UNIT_COST" NUMBER(18,8),
	"IS_AUTO_DISPENSED" CHAR(1),
	"H_LEVEL" NUMBER,
	"END_DATE_KEY" NUMBER(18,0),
	 CONSTRAINT "TK_INVENTORY_LOCATION_02" FOREIGN KEY ("IL_KEY")
	  REFERENCES "TREXONE_DW_DATA"."INVENTORY_LOCATION" ("IL_KEY") DISABLE,
	 CONSTRAINT "TK_FACILITY_90" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "TK_BIN_TYPE_01" FOREIGN KEY ("BIN_TYPE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."BIN_TYPE" ("BIN_TYPE_KEY") DISABLE,
	 CONSTRAINT "FK_INVENTORY_GROUP_02" FOREIGN KEY ("INVENTORY_GROUP_KEY")
	  REFERENCES "TREXONE_DW_DATA"."INVENTORY_GROUP" ("INVENTORY_GROUP_KEY") DISABLE,
	 CONSTRAINT "TK_DATE_DIM_93" FOREIGN KEY ("DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "TK_DRUG_19" FOREIGN KEY ("DRUG_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DRUG" ("DRUG_KEY") DISABLE,
	 CONSTRAINT "TK_PRODUCT_53" FOREIGN KEY ("PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE,
	 CONSTRAINT "TK_DATE_DIM_152" FOREIGN KEY ("END_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") ENABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
