-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."ITEM_LOT"
   (	"ITEM_LOT_KEY" NUMBER(18,0),
	"ITEM_LOT_NUM" NUMBER(18,0),
	"ITEM_SEQ" NUMBER(18,0),
	"ORDER_NUM" NUMBER(18,0),
	"RX_FILL_SEQ" NUMBER(18,0),
	"LOT_NUMBER" VARCHAR2(20),
	"SERIAL_NUMBER" VARCHAR2(20),
	"EXPIRATION_DATE" VARCHAR2(8),
	"SORT_ORDER" NUMBER(18,0),
	"FD_FACILITY_KEY" NUMBER(18,0),
	"RX_NUMBER" VARCHAR2(20),
	"REFILL_NUM" NUMBER(18,0),
	"DISPENSED_PRD_PRODUCT_KEY" NUMBER(18,0),
	"DISPENSED_DRUG_KEY" NUMBER(18,0),
	"WRITTEN_PRD_PRODUCT_KEY" NUMBER(18,0),
	"WRITTEN_DRUG_KEY" NUMBER(18,0),
	"SYS_USER_KEY" NUMBER(18,0),
	"H_TYPE" VARCHAR2(1),
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PARTITION_DATE" DATE,
	 CONSTRAINT "PK_ITEM_LOT" PRIMARY KEY ("ITEM_LOT_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SYS_USER_150" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_PRODUCT_70" FOREIGN KEY ("DISPENSED_PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_PRODUCT_71" FOREIGN KEY ("WRITTEN_PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_DRUG_30" FOREIGN KEY ("DISPENSED_DRUG_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DRUG" ("DRUG_KEY") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_DRUG_31" FOREIGN KEY ("WRITTEN_DRUG_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DRUG" ("DRUG_KEY") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_FACILITY_125" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") ENABLE NOVALIDATE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("DW_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
