-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."LANGUAGE"
   (	"LA_LANGUAGE_KEY" NUMBER NOT NULL ENABLE,
	"LA_LANGUAGE_NUM" NUMBER(18,0),
	"LA_NAME" VARCHAR2(30),
	"LA_LANG_ISO_ID" CHAR(2),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_LANGUAGE" ON "TREXONE_DW_DATA"."LANGUAGE" ("LA_LANGUAGE_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."LANGUAGE" ADD CONSTRAINT "PK_LANGUAGE" PRIMARY KEY ("LA_LANGUAGE_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_LANGUAGE"  ENABLE;
-- ==========================================
