-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."LTC_HOA_SIG"
   (	"LTC_HOA_KEY" NUMBER(18,0),
	"SIG_KEY" NUMBER(18,0),
	"LTC_HOA_NUM" NUMBER(18,0),
	"SIG_NUM" NUMBER(18,0),
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "PK_LTC_HOA_SIG" PRIMARY KEY ("LTC_HOA_KEY", "SIG_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_LTC_HOA_03" FOREIGN KEY ("LTC_HOA_KEY")
	  REFERENCES "TREXONE_DW_DATA"."LTC_HOA" ("LTC_HOA_KEY") DISABLE,
	 CONSTRAINT "FK_SIG_01" FOREIGN KEY ("SIG_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SIG" ("SIG_KEY") DISABLE
   ) ;
-- ==========================================
