-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."LTC_HOA_TIME"
   (	"LTC_HOA_TIME_KEY" NUMBER(18,0),
	"LTC_HOA_KEY" NUMBER(18,0),
	"LTC_HOA_NUM" NUMBER(18,0),
	"HOA_TIME_SEQ" NUMBER(18,0),
	"LTC_HOA_TIME" VARCHAR2(16),
	"PRINT_POSITION" NUMBER(9,0),
	"DOSAGE" NUMBER(18,3),
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "PK_LTC_HOA_TIME" PRIMARY KEY ("LTC_HOA_TIME_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_LTC_HOA_02" FOREIGN KEY ("LTC_HOA_KEY")
	  REFERENCES "TREXONE_DW_DATA"."LTC_HOA" ("LTC_HOA_KEY") DISABLE
   ) ;
-- ==========================================
