-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."LTC_PRESCRIBER_ORDER_TEXT"
   (	"LTC_PRESCRIBER_ORDER_TEXT_KEY" NUMBER(18,0),
	"LTC_PRESCRIBER_ORDER_NUM" NUMBER(18,0),
	"LTC_RX_PRESCRIBER_ORDER_NUM" NUMBER(18,0),
	"TEXT" VARCHAR2(1500),
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "PK_LTC_PRESCRIBER_ORDER_TEXT" PRIMARY KEY ("LTC_PRESCRIBER_ORDER_TEXT_KEY")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
