-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."LTC_FACILITY_NODE"
   (	"LTC_FACILITY_NODE_KEY" NUMBER(18,0),
	"LTC_FACILITY_NODE_NUM" NUMBER(18,0),
	"LTC_FACILITY_KEY" NUMBER(18,0),
	"LTC_FACILITY_NUM" NUMBER(18,0),
	"NAME" VARCHAR2(32),
	"ADDRESS1" VARCHAR2(100),
	"ADDRESS2" VARCHAR2(100),
	"CITY" VARCHAR2(60),
	"ZIPCODE" VARCHAR2(20),
	"STATE_CODE" VARCHAR2(2),
	"ZIP_EXT" VARCHAR2(6),
	"PHONE1" VARCHAR2(20),
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CONTEXT'),
	 CONSTRAINT "PK_LTC_FACILITY_NODE" PRIMARY KEY ("LTC_FACILITY_NODE_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_LTC_FACILITY_06" FOREIGN KEY ("LTC_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."LTC_FACILITY" ("LTC_FACILITY_KEY") DISABLE
   ) ;
-- ==========================================
