-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."LTC_PRESCRIBER_ORDER_TYPE"
   (	"LTC_PRESCRIBER_ORDER_TYPE_KEY" NUMBER(18,0),
	"PRESCRIBER_ORDER_TYPE" VARCHAR2(30),
	"PRESCRIBER_ORDER_DESC" VARCHAR2(255),
	"CODE_NUM" NUMBER(18,0),
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "PK_LTC_PRESCRIBER_ORDER_TYPE" PRIMARY KEY ("LTC_PRESCRIBER_ORDER_TYPE_KEY")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
