-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."LTC_PATIENT"
   (	"LTC_PATIENT_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"LTC_PATIENT_NUM" NUMBER(18,0),
	"LTC_FACILITY_NODE_KEY" NUMBER(18,0),
	"LTC_FACILITY_KEY" NUMBER(18,0),
	"PD_PATIENT_KEY" NUMBER(18,0),
	"STATUS" CHAR(1),
	"IS_FACILITY_LOCATION_INFO_USED" CHAR(1),
	"IS_ACTIVE" CHAR(1),
	"DISCHARGED_DATE_KEY" NUMBER(18,0),
	"STATUS_EFFECTIVE_DATE_KEY" NUMBER(18,0),
	"STATUS_TERMINATION_DATE_KEY" NUMBER(18,0),
	"ROOM" VARCHAR2(50),
	"BED" VARCHAR2(50),
	"ADMISSION_INFORMATION" VARCHAR2(255),
	"ADMITTED_DATE_KEY" NUMBER(18,0),
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CONTEXT'),
	"LTC_PATIENT_ID" VARCHAR2(20),
	"STATUS_CHANGE_DATE_KEY" NUMBER(18,0),
	 CONSTRAINT "PK_LTC_PATIENT" PRIMARY KEY ("LTC_PATIENT_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_LTC_FACILITY_01" FOREIGN KEY ("LTC_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."LTC_FACILITY" ("LTC_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_104" FOREIGN KEY ("STATUS_EFFECTIVE_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_105" FOREIGN KEY ("STATUS_TERMINATION_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_106" FOREIGN KEY ("ADMITTED_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_LTC_FACILITY_NODE_04" FOREIGN KEY ("LTC_FACILITY_NODE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."LTC_FACILITY_NODE" ("LTC_FACILITY_NODE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_103" FOREIGN KEY ("DISCHARGED_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_40" FOREIGN KEY ("PD_PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_145" FOREIGN KEY ("STATUS_CHANGE_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE
   ) ;
-- ==========================================
