-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."MANIFEST_ITEM_FACT"
   (	"SCHEDULED_DELIVERY_DATE_KEY" NUMBER(18,0),
	"DELIVERY_ROUTE_SCHEDULE_KEY" NUMBER(18,0),
	"CENTRAL_FILL_FD_FACILITY_KEY" NUMBER(18,0),
	"LOCAL_FD_FACILITY_KEY" NUMBER(18,0),
	"PRD_PRODUCT_KEY" NUMBER(18,0),
	"DRUG_KEY" NUMBER(18,0),
	"TOTE_KEY" NUMBER(18,0),
	"MANIFEST_CLOSE_DATE_KEY" NUMBER(18,0),
	"MANIFEST_CLOSE_TIME_KEY" NUMBER(5,0),
	"CHECK_OUT_DATE_KEY" NUMBER(18,0),
	"CHECK_OUT_TIME_KEY" NUMBER(5,0),
	"CHECK_OUT_SYS_USER_KEY" NUMBER(18,0),
	"CHECK_IN_DATE_KEY" NUMBER(18,0),
	"CHECK_IN_TIME_KEY" NUMBER(5,0),
	"CHECK_IN_SYS_USER_KEY" NUMBER(18,0),
	"RETURN_TIME_KEY" NUMBER(5,0),
	"RETURN_DATE_KEY" NUMBER(18,0),
	"RETURN_REASON_KEY" NUMBER(18,0),
	"PD_PATIENT_H_KEY" NUMBER(18,0),
	"PRS_PRESCRIBER_KEY" NUMBER(18,0),
	"PROMISE_DATE_KEY" NUMBER(18,0),
	"ORDER_DATE_KEY" NUMBER(18,0),
	"ORDER_TIME_KEY" NUMBER(5,0),
	"PROMISE_TIME_KEY" NUMBER(5,0),
	"PARTITION_DATE" DATE,
	"RX_NUMBER" VARCHAR2(20),
	"REFILL_NUM" NUMBER(10,0),
	"DISPENSED_QTY" NUMBER(13,3),
	"INTENDED_DISPENSE_QTY" NUMBER(13,3),
	"IS_PULLED_BACK" CHAR(1),
	"RX_RECORD_NUM" NUMBER(18,0),
	"RX_FILL_SEQ" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PD_PATIENT_KEY" NUMBER(18,0),
	"H_LEVEL" NUMBER,
	"MANIFEST_ITEM_NUM" NUMBER(18,0),
	"ITEM_QUANTITY" NUMBER(16,8),
	 CONSTRAINT "FK_DATE_DIM_78" FOREIGN KEY ("CHECK_OUT_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_79" FOREIGN KEY ("ORDER_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_81" FOREIGN KEY ("PROMISE_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_82" FOREIGN KEY ("MANIFEST_CLOSE_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_83" FOREIGN KEY ("CHECK_IN_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_84" FOREIGN KEY ("RETURN_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_85" FOREIGN KEY ("SCHEDULED_DELIVERY_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DELIVERY_ROUTE_SCHEDULE_1" FOREIGN KEY ("DELIVERY_ROUTE_SCHEDULE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DELIVERY_ROUTE_SCHEDULE" ("DELIVERY_ROUTE_SCHEDULE_KEY") DISABLE,
	 CONSTRAINT "FK_DRUG_9" FOREIGN KEY ("DRUG_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DRUG" ("DRUG_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_83" FOREIGN KEY ("CENTRAL_FILL_FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_84" FOREIGN KEY ("LOCAL_FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_H_36" FOREIGN KEY ("PD_PATIENT_H_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT_H" ("PD_PATIENT_H_KEY") DISABLE,
	 CONSTRAINT "FK_PRESCRIBER_14" FOREIGN KEY ("PRS_PRESCRIBER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRESCRIBER" ("PRS_PRESCRIBER_KEY") DISABLE,
	 CONSTRAINT "FK_PRODUCT_38" FOREIGN KEY ("PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE,
	 CONSTRAINT "FK_RETURN_REASON_TYPE_1" FOREIGN KEY ("RETURN_REASON_KEY")
	  REFERENCES "TREXONE_DW_DATA"."RETURN_REASON_TYPE" ("RETURN_REASON_KEY") DISABLE,
	 CONSTRAINT "FK_SYS_USER_79" FOREIGN KEY ("CHECK_IN_SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE,
	 CONSTRAINT "FK_SYS_USER_80" FOREIGN KEY ("CHECK_OUT_SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_21" FOREIGN KEY ("CHECK_IN_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_22" FOREIGN KEY ("PROMISE_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_23" FOREIGN KEY ("ORDER_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_24" FOREIGN KEY ("CHECK_OUT_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_25" FOREIGN KEY ("MANIFEST_CLOSE_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_26" FOREIGN KEY ("RETURN_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_TOTE_1" FOREIGN KEY ("TOTE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TOTE" ("TOTE_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_36" FOREIGN KEY ("PD_PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") DISABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
