-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."MEDICAL_CONDITION"
   (	"MCD_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"MCD_CONDITION_REF_NUM" VARCHAR2(20),
	"MCD_DESCRIPTION" VARCHAR2(255),
	"MCD_MED_CONDITION_NUM" NUMBER(18,0),
	"MCD_MED_COND_REF_TYPE" VARCHAR2(10),
	"MCD_COND_REF_NUM_PREFIX" CHAR(1),
	"MCD_COND_REF_NUM_SUFFIX" VARCHAR2(10),
	"MCD_FRMTTD_COND_REF_NUM" VARCHAR2(45),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_MEDICAL_CONDITION" ON "TREXONE_DW_DATA"."MEDICAL_CONDITION" ("MCD_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."MEDICAL_CONDITION" ADD CONSTRAINT "PK_MEDICAL_CONDITION" PRIMARY KEY ("MCD_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_MEDICAL_CONDITION"  ENABLE;
-- ==========================================
