-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."NCPDP_REASON_TYPE"
   (	"NCPDP_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"NCPDP_CATG_CODE" NUMBER(9,0),
	"NCPDP_CODE" VARCHAR2(4),
	"NCPDP_DESC" VARCHAR2(100),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_NCPDP_REASON_TYPE" ON "TREXONE_DW_DATA"."NCPDP_REASON_TYPE" ("NCPDP_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."NCPDP_REASON_TYPE" ADD CONSTRAINT "PK_NCPDP_REASON_TYPE" PRIMARY KEY ("NCPDP_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_NCPDP_REASON_TYPE"  ENABLE;
-- ==========================================
