-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PATIENT_PRIVACY_RESTRICTION"
   (	"PATIENT_PRIVACY_RESTRICT_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"ALLOW_CUSTOM_RPT_FLAG" VARCHAR2(7),
	"IS_LETTER_ON_FILE" VARCHAR2(7),
	"IS_EMANCIPATED_MINOR" VARCHAR2(7),
	"PRIVACY_LEVEL" VARCHAR2(7),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"RESTRICT_VACCINATION_REPORTING" CHAR(1)
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_PATIENT_PRIVACY_RESTRICTION" ON "TREXONE_DW_DATA"."PATIENT_PRIVACY_RESTRICTION" ("PATIENT_PRIVACY_RESTRICT_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."PATIENT_PRIVACY_RESTRICTION" ADD CONSTRAINT "PK_PATIENT_PRIVACY_RESTRICTION" PRIMARY KEY ("PATIENT_PRIVACY_RESTRICT_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_PATIENT_PRIVACY_RESTRICTION"  ENABLE;
-- ==========================================
