-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PATIENT_FACILITY"
   (	"PATIENT_FACILITY_NUM" NUMBER(18,0),
	"PATIENT_FACILITY_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PATIENT_KEY" NUMBER(18,0),
	"FACILITY_KEY" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID'),
	 CONSTRAINT "PK_PATIENT_FACILITY" PRIMARY KEY ("PATIENT_FACILITY_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_FACILITY_93" FOREIGN KEY ("FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_02" FOREIGN KEY ("PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") DISABLE
   ) ;
-- ==========================================
