-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PATIENT_EXTRA_TP_INFO"
   (	"PTPX_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PD_PATIENT_H_KEY" NUMBER(18,0),
	"PATIENT_EXTRA_TP_INFO_NUM" NUMBER(18,0),
	"PTPX_GUARANTOR_FNAME" VARCHAR2(30),
	"PTPX_GUARANTOR_MNAME" VARCHAR2(30),
	"PTPX_GUARANTOR_LNAME" VARCHAR2(30),
	"PTPX_GUARANTOR_SUFFIX" VARCHAR2(12),
	"PTPX_SERVICE_FACILITY_NAME" VARCHAR2(30),
	"PTPX_SERVICE_FACILITY_ID_QUAL1" VARCHAR2(10),
	"PTPX_SERVICE_FACILITY_ID1" VARCHAR2(30),
	"PTPX_SERVICE_FACILITY_ID_QUAL2" VARCHAR2(10),
	"PTPX_SERVICE_FACILITY_ID2" VARCHAR2(30),
	"PTPX_ARCHIVE_LEVEL" NUMBER(9,0),
	"PTPX_NUM_UPDATES" NUMBER(18,0),
	"ENT_BY" NUMBER(18,0),
	"ES_DT" DATE,
	"EE_DT" DATE,
	"EE_DT_SEQ" NUMBER(18,0),
	"PARTITION_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PD_PATIENT_KEY" NUMBER(18,0),
	 CONSTRAINT "FK_PATIENT_H_18" FOREIGN KEY ("PD_PATIENT_H_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT_H" ("PD_PATIENT_H_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_18" FOREIGN KEY ("PD_PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") DISABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_PATIENT_EXTRA_TP_INFO" ON "TREXONE_DW_DATA"."PATIENT_EXTRA_TP_INFO" ("PTPX_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."PATIENT_EXTRA_TP_INFO" ADD CONSTRAINT "PK_PATIENT_EXTRA_TP_INFO" PRIMARY KEY ("PTPX_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_PATIENT_EXTRA_TP_INFO"  ENABLE;
-- ==========================================
