-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PATIENT_PRIVACY"
   (	"PD_PATIENT_H_KEY" NUMBER(18,0),
	"FD_FACILITY_KEY" NUMBER(18,0),
	"PPF_PRIVACY_TYPE_CODE" CHAR(2),
	"DATE_KEY" NUMBER(18,0),
	"SYS_USER_KEY" NUMBER(18,0),
	"PPF_DOC_VERSION_NAME" VARCHAR2(18),
	"PPF_ACTION_CODE" CHAR(1),
	"PPF_ACK_TYPE_CODE" CHAR(1),
	"PPF_COMMENT_TEXT" VARCHAR2(1000),
	"PPF_ACK_REPRESENTATIVE_NAME" VARCHAR2(100),
	"PPF_AUTHORIZED_PARTY" VARCHAR2(255),
	"PPF_EFFECTIVE_DATE" DATE,
	"PPF_TERMINATION_DATE" DATE,
	"PPF_RESTRICTION_LEVEL_CODE" CHAR(1),
	"GFE_GOOD_FAITH_EFFORT_RSN_KEY" NUMBER(18,0),
	"SIGNATURE_IMAGE_KEY" NUMBER(18,0),
	"AUTH_FORM_IMAGE_KEY" NUMBER(18,0),
	"PPF_UPDATE_DT" DATE,
	"PPF_CREATE_DT" DATE,
	"TIME_KEY" NUMBER(5,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PD_PATIENT_KEY" NUMBER(18,0),
	"H_LEVEL" NUMBER,
	 CONSTRAINT "FK_DATE_DIM_31" FOREIGN KEY ("DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_33" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_GOOD_FAITH_EFFORT_REASON_1" FOREIGN KEY ("GFE_GOOD_FAITH_EFFORT_RSN_KEY")
	  REFERENCES "TREXONE_DW_DATA"."GOOD_FAITH_EFFORT_REASON_TYPE" ("GFE_GOOD_FAITH_EFFORT_RSN_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_H_17" FOREIGN KEY ("PD_PATIENT_H_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT_H" ("PD_PATIENT_H_KEY") DISABLE,
	 CONSTRAINT "FK_SYS_USER_35" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_12" FOREIGN KEY ("TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_17" FOREIGN KEY ("PD_PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") DISABLE,
	 CONSTRAINT "FK_IMAGE_4" FOREIGN KEY ("SIGNATURE_IMAGE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."IMAGE" ("IMAGE_KEY") DISABLE,
	 CONSTRAINT "FK_IMAGE_3" FOREIGN KEY ("AUTH_FORM_IMAGE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."IMAGE" ("IMAGE_KEY") DISABLE
   ) ;
-- ==========================================
