-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PATIENT_ADDRESS"
   (	"PAD_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PAD_ADDRESS1" VARCHAR2(100),
	"PAD_ADDRESS2" VARCHAR2(50),
	"PAD_CITY" VARCHAR2(50),
	"PAD_STATE" VARCHAR2(2),
	"PAD_ZIP" VARCHAR2(20),
	"PAD_PHONE1" VARCHAR2(20),
	"PAD_PHONE2" VARCHAR2(20),
	"PAD_PHONE3" VARCHAR2(20),
	"PAD_CREATE_DATE" DATE,
	"PAD_END_DATE" DATE,
	"PAD_ADDRESS_NUM" NUMBER(18,0),
	"PAD_COUNTY" VARCHAR2(30),
	"PAD_CNTRY_CD" VARCHAR2(8),
	"PAD_POST_OFFICE" VARCHAR2(40),
	"PAD_ADDRESS_USAGE" VARCHAR2(50),
	"PAD_USAGE" VARCHAR2(50),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"STATUS" CHAR(1),
	"PD_PATIENT_KEY" NUMBER(18,0),
	"PAD_EXT" VARCHAR2(6),
	"H_LEVEL" NUMBER,
	"PAD_COUNTY_CODE" VARCHAR2(5),
	 CONSTRAINT "FK_PATIENT_22" FOREIGN KEY ("PD_PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") DISABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_PATIENT_ADDRESS" ON "TREXONE_DW_DATA"."PATIENT_ADDRESS" ("PAD_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."PATIENT_ADDRESS" ADD CONSTRAINT "PK_PATIENT_ADDRESS" PRIMARY KEY ("PAD_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_PATIENT_ADDRESS"  ENABLE;
-- ==========================================
