-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PATIENT_ALLERGY_BRDG"
   (	"PAB_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PD_PATIENT_KEY" NUMBER(18,0),
	"ALD_ALLERGY_KEY" NUMBER(18,0),
	"PAB_EFFECTIVE_DATE" DATE,
	"PAB_SEVERITY" VARCHAR2(10),
	"PAB_REACTANT_ONSET_DATE" DATE,
	"PAB_UD_REACT_SYMPTOMS" VARCHAR2(60),
	"PAB_STATUS" CHAR(1),
	"PAB_DESCRIPTION" VARCHAR2(255),
	"PAB_SYS_USER" NUMBER(18,0),
	"PAB_DEACTIVATE_USER" NUMBER(18,0),
	"PAB_DEACTIVATE_DATE" DATE,
	"PAB_UPDATE_DT" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	 CONSTRAINT "FK_ALLERGY_3" FOREIGN KEY ("ALD_ALLERGY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."ALLERGY" ("ALD_ALLERGY_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_11" FOREIGN KEY ("PD_PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") DISABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_PATIENT_ALLERGY_BRDG" ON "TREXONE_DW_DATA"."PATIENT_ALLERGY_BRDG" ("PAB_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."PATIENT_ALLERGY_BRDG" ADD CONSTRAINT "PK_PATIENT_ALLERGY_BRDG" PRIMARY KEY ("PAB_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_PATIENT_ALLERGY_BRDG"  ENABLE;
-- ==========================================
