-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PATIENT_ALLERGY_SYMPTOM_BRDG"
   (	"PAB_KEY" NUMBER(18,0),
	"PASB_CREATE_DATE" DATE,
	"ASD_KEY" NUMBER(18,0),
	"PASB_STATUS" CHAR(1),
	"PASB_DESCRIPTION" VARCHAR2(255),
	"PASB_SEVERITY_NUM" NUMBER(9,0),
	"PASB_DELETE_DATE" DATE,
	"PASB_CREATE_USER" NUMBER(18,0),
	"PASB_UPDATE_DT" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	 CONSTRAINT "FK_ALLERGY_SYMPTOM_2" FOREIGN KEY ("ASD_KEY")
	  REFERENCES "TREXONE_DW_DATA"."ALLERGY_SYMPTOM" ("ASD_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_ALLERGY_BRDG_2" FOREIGN KEY ("PAB_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT_ALLERGY_BRDG" ("PAB_KEY") DISABLE
   ) ;
-- ==========================================
