-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PATIENT_HEALTH"
   (	"PATIENT_HEALTH_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"IS_SMOKER" VARCHAR2(7),
	"IS_TERMINALLY_ILL" VARCHAR2(7),
	"IS_VISUALLY_IMPAIRED" VARCHAR2(7),
	"IS_PREGNANT" VARCHAR2(7),
	"FAMILY_PLANNING" VARCHAR2(7),
	"IS_LACTATING" VARCHAR2(7),
	"IS_HEARING_IMPAIRED" VARCHAR2(7),
	"HAS_NO_ALLERGIES" VARCHAR2(7),
	"HAS_NO_MEDICAL_CONDITIONS" VARCHAR2(7),
	"HAS_CHRONIC_MED_CONDITION" VARCHAR2(7),
	"ERX_CLIENT_ID" VARCHAR2(100)
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_PATIENT_HEALTH" ON "TREXONE_DW_DATA"."PATIENT_HEALTH" ("PATIENT_HEALTH_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."PATIENT_HEALTH" ADD CONSTRAINT "PK_PATIENT_HEALTH" PRIMARY KEY ("PATIENT_HEALTH_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_PATIENT_HEALTH"  ENABLE;
-- ==========================================
