-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PATIENT_CREDIT_CARD"
   (	"PATIENT_CREDIT_CARD_KEY" NUMBER(18,0),
	"ACCOUNT_MEMBER_CREDIT_CARD_NUM" NUMBER(18,0),
	"PD_PATIENT_KEY" NUMBER(18,0),
	"CARD_TYPE_DESC" VARCHAR2(100),
	"EXPIRATION_DATE_KEY" NUMBER(18,0),
	"LAST4_PAN" CHAR(4),
	"FIRST_NAME" VARCHAR2(30),
	"MIDDLE_NAME" VARCHAR2(30),
	"LAST_NAME" VARCHAR2(30),
	"CARD_STATUS_DESC" VARCHAR2(100),
	"CARD_NOTE" VARCHAR2(100),
	"IS_ONE_TIME_CHARGE" CHAR(1),
	"FIRST6_PAN" CHAR(6),
	"HEALTH_CARD_DESIGNATION" VARCHAR2(20),
	"HEALTH_CARD_DESIGNATION_DATE" DATE,
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "PK_PATIENT_CREDIT_CARD" PRIMARY KEY ("PATIENT_CREDIT_CARD_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_PATIENT_43" FOREIGN KEY ("PD_PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_147" FOREIGN KEY ("EXPIRATION_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE
   ) ;
-- ==========================================
