-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PAYMENT_FACT"
   (	"FD_FACILITY_KEY" NUMBER(18,0),
	"DRUG_KEY" NUMBER(18,0),
	"PRD_PRODUCT_KEY" NUMBER(18,0),
	"PD_PATIENT_KEY" NUMBER(18,0),
	"PAYMENT_TYPE_KEY" NUMBER(18,0),
	"PAYMENT_DATE_KEY" NUMBER(18,0),
	"CANCELLED_DATE_KEY" NUMBER(18,0),
	"COMPLETION_DATE_KEY" NUMBER(18,0),
	"AUTHORIZED_DATE_KEY" NUMBER(18,0),
	"SETTLEMENT_DATE_KEY" NUMBER(18,0),
	"CANCELLED_TIME_KEY" NUMBER(5,0),
	"COMPLETION_TIME_KEY" NUMBER(5,0),
	"AUTHORIZED_TIME_KEY" NUMBER(5,0),
	"SETTLEMENT_TIME_KEY" NUMBER(5,0),
	"ORDER_NUM" NUMBER(18,0),
	"FACILITY_ORDER_NUMBER" VARCHAR2(10),
	"ITEM_SEQ" NUMBER(18,0),
	"RX_NUMBER" VARCHAR2(20),
	"REFILL_NUM" NUMBER(18,0),
	"QTY_DISPENSED" NUMBER(13,3),
	"PAYMENT_SOURCE" CHAR(2),
	"PAYMENT_AMOUNT" NUMBER(18,6),
	"ITEM_AMOUNT" NUMBER(18,6),
	"REVERSAL_PAYMENT_NUM" NUMBER(18,0),
	"PAYMENT_ID" VARCHAR2(100),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID'),
	"PARTITION_DATE" DATE,
	"IS_CENTRAL_FILL_MAIL" CHAR(1),
	"IS_STORE_MAIL" CHAR(1),
	"IS_EXPRESS_PAY" CHAR(1),
	"CARD_TYPE_DESC" VARCHAR2(100),
	"IS_ONE_TIME_CHARGE" CHAR(1),
	"LAST4_PAN" CHAR(4),
	"EXPIRATION_DATE_KEY" NUMBER(18,0),
	"HEALTH_CARD_DESIGNATION" VARCHAR2(20),
	"HEALTH_CARD_DESIGNATION_DT_KEY" NUMBER(18,0),
	"RX_FILL_SEQ" NUMBER(18,0),
	"IS_ITEM_REFUND" CHAR(1),
	"IS_ACTIVE" CHAR(1),
	"PAYMENT_NUM" NUMBER(18,0),
	"CC_PAYMENT_TYPE_NUM" NUMBER(18,0),
	 CONSTRAINT "FK_PAYMENT_TYPE_01" FOREIGN KEY ("PAYMENT_TYPE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PAYMENT_TYPE" ("PAYMENT_TYPE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_96" FOREIGN KEY ("COMPLETION_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_97" FOREIGN KEY ("CANCELLED_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_40" FOREIGN KEY ("SETTLEMENT_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_41" FOREIGN KEY ("COMPLETION_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_116" FOREIGN KEY ("PAYMENT_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_117" FOREIGN KEY ("SETTLEMENT_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_95" FOREIGN KEY ("AUTHORIZED_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DRUG_23" FOREIGN KEY ("DRUG_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DRUG" ("DRUG_KEY") DISABLE,
	 CONSTRAINT "FK_PRODUCT_54" FOREIGN KEY ("PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_101" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_41" FOREIGN KEY ("PD_PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_44" FOREIGN KEY ("CANCELLED_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_43" FOREIGN KEY ("AUTHORIZED_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
