-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PO_STATUS_TYPE"
   (	"PO_STATUS_TYPE_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(50),
	"STATUS_CODE" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100)
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_PO_STATUS_TYPE" ON "TREXONE_DW_DATA"."PO_STATUS_TYPE" ("PO_STATUS_TYPE_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."PO_STATUS_TYPE" ADD CONSTRAINT "PK_PO_STATUS_TYPE" PRIMARY KEY ("PO_STATUS_TYPE_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_PO_STATUS_TYPE"  ENABLE;
-- ==========================================
