-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."POS_FINALIZATION"
   (	"DATE_KEY" NUMBER(18,0),
	"POS_POS_FINALIZATION_NUM" NUMBER(18,0),
	"FD_FACILITY_KEY" NUMBER(18,0),
	"SYS_USER_KEY" NUMBER(18,0),
	"POS_RX_RECORD_NUM" NUMBER(18,0),
	"POS_REGISTER_TXN" NUMBER(9,0),
	"POS_REGISTER_TXN_SEQ" NUMBER(9,0),
	"POS_USERID" VARCHAR2(20),
	"POS_AMOUNT" NUMBER(17,6),
	"POS_PATIENT_PAY_SRC" CHAR(1),
	"POS_PRICE_OVERRIDE_RSN_CD" CHAR(2),
	"POS_POS_TAX_AMOUNT" NUMBER(17,6),
	"POS_REGISTER_NUM" NUMBER(9,0),
	"POS_RX_FILL_SEQ" NUMBER(18,0),
	"POS_TXN_TYPE" CHAR(1),
	"POS_DATESTAMP" DATE,
	"TIME_KEY" NUMBER(5,0),
	"POS_PARTIAL_FILL_NUM" NUMBER(2,0),
	"RX_NUMBER" VARCHAR2(20),
	"REFILL_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	 CONSTRAINT "FK_DATE_DIM_45" FOREIGN KEY ("DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_48" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_SYS_USER_53" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_13" FOREIGN KEY ("TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE
   )
  PARTITION BY RANGE ("POS_DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
