-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PPI_MESSAGE_AUDIT"
   (	"DATE_KEY" NUMBER(18,0),
	"FD_FACILITY_KEY" NUMBER(18,0),
	"PD_PATIENT_H_KEY" NUMBER(18,0),
	"PRS_PRESCRIBER_KEY" NUMBER(18,0),
	"PRD_PRODUCT_KEY" NUMBER(18,0),
	"SYS_USER_KEY" NUMBER(18,0),
	"PPIM_PPI_MESSAGE_NUM" NUMBER(18,0),
	"PPIM_SOURCE" VARCHAR2(120),
	"PPIM_DESTINATION" VARCHAR2(120),
	"PPIM_MESSAGE_ID" VARCHAR2(35),
	"PPIM_MESSAGE_TYPE" NUMBER(2,0),
	"PPIM_SENT_TIME" DATE,
	"PPIM_RELATED_MESSAGE_ID" VARCHAR2(35),
	"PPIM_RX_NUMBER" VARCHAR2(20),
	"PPIM_IS_MATCHED" CHAR(1),
	"PPIM_ERROR_CODE" NUMBER(3,0),
	"PPIM_STORE_NAME" VARCHAR2(70),
	"PPIM_PATIENT_LAST_NAME" VARCHAR2(35),
	"PPIM_PATIENT_FIRST_NAME" VARCHAR2(35),
	"PPIM_PATIENT_GENDER" CHAR(1),
	"PPIM_PATIENT_DATE_OF_BIRTH" DATE,
	"PPIM_MEDICATION_DESCRIPTION" VARCHAR2(105),
	"PPIM_RX_REFERENCE_NUMBER" VARCHAR2(35),
	"PPIM_PRESCRIBER_LAST_NAME" VARCHAR2(35),
	"PPIM_PRESCRIBER_FIRST_NAME" VARCHAR2(35),
	"PPIM_PRESCRIBER_CLINIC_NAME" VARCHAR2(70),
	"PPIM_PRESCRIBER_SPECIALTY_QUAL" CHAR(3),
	"PPIM_PRESCRIBER_SPECIALTY_CODE" CHAR(10),
	"PPIM_RESPONSE_TYPE" CHAR(1),
	"PPIM_RESPONSE_REFILL_QUALIFIER" CHAR(3),
	"PPIM_RESPONSE_REFILL_QTY" VARCHAR2(35),
	"PPIM_RESPONSE_DENIED_CODE" CHAR(3),
	"PPIM_RESPONSE_NOTE" VARCHAR2(70),
	"PPIM_CTL_MSG_CODE" CHAR(3),
	"PPIM_CTL_MSG_DESC_CODE" VARCHAR2(4),
	"PPIM_CTL_MSG_DESC" VARCHAR2(4000),
	"PPIM_UPDT_DT" DATE,
	"PPIM_CREATE_DT" DATE,
	"TIME_KEY" NUMBER(5,0),
	"PPIM_REFILL_NUM" NUMBER(18,0),
	"PPIM_RX_RECORD_NUM" NUMBER(18,0),
	"PPIM_RX_FILL_SEQ" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PD_PATIENT_KEY" NUMBER(18,0),
	"H_LEVEL" NUMBER,
	"PPI_MESSAGE_LEVEL" NUMBER,
	 CONSTRAINT "FK_DATE_DIM_46" FOREIGN KEY ("DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_49" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_H_23" FOREIGN KEY ("PD_PATIENT_H_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT_H" ("PD_PATIENT_H_KEY") DISABLE,
	 CONSTRAINT "FK_PRESCRIBER_9" FOREIGN KEY ("PRS_PRESCRIBER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRESCRIBER" ("PRS_PRESCRIBER_KEY") DISABLE,
	 CONSTRAINT "FK_PRODUCT_19" FOREIGN KEY ("PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE,
	 CONSTRAINT "FK_SYS_USER_54" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_14" FOREIGN KEY ("TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_23" FOREIGN KEY ("PD_PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") DISABLE
   )
  PARTITION BY RANGE ("PPIM_CREATE_DT") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
