-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PRESCRIBER_ADDRESS"
   (	"PADR_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PRS_PRESCRIBER_KEY" NUMBER(18,0),
	"PADR_ADDRESS_TYPE_CODE" VARCHAR2(10),
	"PADR_PRESCRIBER_ADDRESS_NUM" NUMBER(18,0),
	"PADR_ADDRESS1" VARCHAR2(100),
	"PADR_STATUS" CHAR(1),
	"PADR_ADDRESS2" VARCHAR2(50),
	"PADR_CITY" VARCHAR2(40),
	"PADR_EMAIL_ADDRESS" VARCHAR2(256),
	"PADR_WEB_ADDRESS" VARCHAR2(256),
	"PADR_STATE_CODE" VARCHAR2(2),
	"PADR_ZIPCODE" VARCHAR2(20),
	"PADR_PRIMARY_CONTACT_LNAME" VARCHAR2(30),
	"PADR_CTRY_CODE" VARCHAR2(8),
	"PADR_PRIMARY_CONTACT_MNAME" VARCHAR2(30),
	"PADR_COUNTY" VARCHAR2(30),
	"PADR_PRIMARY_CONTACT_FNAME" VARCHAR2(30),
	"PADR_POST_OFFICE" VARCHAR2(40),
	"PADR_IS_USER_DEFINED" CHAR(1),
	"PADR_IS_DEFAULT" CHAR(1),
	"PADR_SOURCE_CODE" CHAR(1),
	"PADR_PRESCRIBER_LOCATION" VARCHAR2(3),
	"PADR_DRUG_SCHEDULE" VARCHAR2(30),
	"PADR_PRACTICE_NAME" VARCHAR2(50),
	"PADR_PRIMARY_CONTACT_TITLE" VARCHAR2(30),
	"PADR_PRESCRIBER_ID_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PADR_EXT" VARCHAR2(6),
	"H_LEVEL" NUMBER,
	"IS_340B" CHAR(1),
	"PRESCRIBER_ADDR_CONTACT_KEY" NUMBER(18,0),
	 CONSTRAINT "FK_PRESCRIBER_ADDRESS" FOREIGN KEY ("PRS_PRESCRIBER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRESCRIBER" ("PRS_PRESCRIBER_KEY") DISABLE,
	 CONSTRAINT "FK_PRESCRIBER_ADDR_CONTACT_01" FOREIGN KEY ("PRESCRIBER_ADDR_CONTACT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRESCRIBER_ADDR_CONTACT" ("PRESCRIBER_ADDR_CONTACT_KEY") DISABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_PRESCRIBER_ADDRESS" ON "TREXONE_DW_DATA"."PRESCRIBER_ADDRESS" ("PADR_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."PRESCRIBER_ADDRESS" ADD CONSTRAINT "PK_PRESCRIBER_ADDRESS" PRIMARY KEY ("PADR_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_PRESCRIBER_ADDRESS"  ENABLE;
-- ==========================================
