-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PRESCRIBER_ADDR_CONTACT"
   (	"PRESCRIBER_ADDR_CONTACT_KEY" NUMBER(18,0),
	"CONTACT_METHOD_NUM" NUMBER(18,0),
	"DESCRIPTION" VARCHAR2(45),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	 CONSTRAINT "PK_PRESCRIBER_ADDR_CONTACT" PRIMARY KEY ("PRESCRIBER_ADDR_CONTACT_KEY")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
