-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PRICING_LIST_ITEM"
   (	"PRICING_LIST_ITEM_KEY" NUMBER(18,0),
	"PRICING_LIST_ITEM_NUM" NUMBER(18,0),
	"PRICING_LIST_NAME" VARCHAR2(30),
	"CASH_TP_IND" CHAR(1),
	"PRICING_HIERARCHY_KEY" NUMBER(18,0),
	"PRICING_FORMULA_NAME" VARCHAR2(30),
	"PRICING_FORMULA_NUM" NUMBER(18,0),
	"DEFAULT_PRICING_FORMULA_NUM" NUMBER(18,0),
	"DEFAULT_FORMULA_NAME" VARCHAR2(30),
	"CONFIG_EFFECTIVE_DATE" DATE,
	"CONFIG_TERM_DATE" DATE,
	"DATA_FILTER" CLOB,
	"PUBLISH_STATUS" CHAR(1),
	"PUBLISH_USER_LOGIN_NAME" VARCHAR2(255),
	"PUBLISH_DATE" DATE,
	"PROCESS_ORDER" NUMBER(9,0),
	"INCL_EXCL_IND" CHAR(1),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "FK_PRICING_HIERARCHY_1" FOREIGN KEY ("PRICING_HIERARCHY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRICING_HIERARCHY" ("PRICING_HIERARCHY_KEY") DISABLE
   ) ;
-- ==========================================
