-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PRICING_TABLE"
   (	"PRICING_TABLE_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PRICING_TABLE_DETAIL_NUM" NUMBER(18,0),
	"NAME" VARCHAR2(30),
	"CASH_TP_IND" CHAR(1),
	"PRICING_HIERARCHY_KEY" NUMBER(18,0),
	"PUBLISH_STATUS" CHAR(1),
	"PUBLISH_USER_LOGIN_NAME" VARCHAR2(255),
	"PUBLISH_DATE" DATE,
	"CONFIG_EFFECTIVE_DATE" DATE,
	"CONFIG_TERM_DATE" DATE,
	"INDEX_LOW_VALUE" NUMBER(17,6),
	"INDEX_HIGH_VALUE" NUMBER(17,6),
	"BASIS_OF_COST_CD" CHAR(2),
	"COST_BASIS_NAME" VARCHAR2(30),
	"COST_BASIS_DESC" VARCHAR2(255),
	"COST_BAS_PRICING_HIERARCHY_KEY" NUMBER(18,0),
	"TABLE_CALCULATION" VARCHAR2(4000),
	"LINKED_TABLE_NAME" VARCHAR2(30),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "FK_PRICING_HIERARCHY_4" FOREIGN KEY ("PRICING_HIERARCHY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRICING_HIERARCHY" ("PRICING_HIERARCHY_KEY") DISABLE,
	 CONSTRAINT "FK_PRICING_HIERARCHY_5" FOREIGN KEY ("COST_BAS_PRICING_HIERARCHY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRICING_HIERARCHY" ("PRICING_HIERARCHY_KEY") DISABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_PRICING_TABLE" ON "TREXONE_DW_DATA"."PRICING_TABLE" ("PRICING_TABLE_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."PRICING_TABLE" ADD CONSTRAINT "PK_PRICING_TABLE" PRIMARY KEY ("PRICING_TABLE_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_PRICING_TABLE"  ENABLE;
-- ==========================================
