-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PRICING_OVERRIDE_CODE_TYPE"
   (	"PRICING_OVERRIDE_CODE_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PRICING_OVERRIDE_CODE" VARCHAR2(10),
	"PRICING_OVERRIDE_NAME" VARCHAR2(30),
	"PRICING_OVERRIDE_DESC" VARCHAR2(255),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_PRICING_OVERRIDE_CODE_TYPE" ON "TREXONE_DW_DATA"."PRICING_OVERRIDE_CODE_TYPE" ("PRICING_OVERRIDE_CODE_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."PRICING_OVERRIDE_CODE_TYPE" ADD CONSTRAINT "PK_PRICING_OVERRIDE_CODE_TYPE" PRIMARY KEY ("PRICING_OVERRIDE_CODE_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_PRICING_OVERRIDE_CODE_TYPE"  ENABLE;
-- ==========================================
