-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PRICING_DISCOUNT_TYPE"
   (	"PRICING_DISCOUNT_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PRICING_DISCOUNT_CODE" VARCHAR2(10),
	"PRICING_DISCOUNT_NAME" VARCHAR2(30),
	"PRICING_DISCOUNT_DESC" VARCHAR2(255),
	"ERX_CLIENT_ID" VARCHAR2(100)
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_PRICING_DISCOUNT_TYPE" ON "TREXONE_DW_DATA"."PRICING_DISCOUNT_TYPE" ("PRICING_DISCOUNT_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."PRICING_DISCOUNT_TYPE" ADD CONSTRAINT "PK_PRICING_DISCOUNT_TYPE" PRIMARY KEY ("PRICING_DISCOUNT_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_PRICING_DISCOUNT_TYPE"  ENABLE;
-- ==========================================
