-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PRODUCT_IDENTIFIER"
   (	"PRODUCT_IDENTIFIER_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PRODUCT_IDENTIFIER_NUM" NUMBER(18,0),
	"PRD_PRODUCT_KEY" NUMBER(18,0),
	"SOURCE" VARCHAR2(30),
	"DATE_OF_ADD_KEY" NUMBER(18,0),
	"DESCRIPTION" VARCHAR2(255),
	"IDENTIFIER" VARCHAR2(50),
	"IS_ACTIVE" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID'),
	 CONSTRAINT "PK_PRODUCT_IDENTIFIER" PRIMARY KEY ("PRODUCT_IDENTIFIER_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_PRODUCT_46" FOREIGN KEY ("PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_146" FOREIGN KEY ("DATE_OF_ADD_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE
   ) ;
-- ==========================================
