-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PRODUCT_ORDERING_GROUP_MEMBER"
   (	"PRODUCT_ORDERING_GROUP_MEM_KEY" NUMBER(18,0),
	"PRODUCT_ORDERING_GROUP_NUM" NUMBER(18,0),
	"POG_MEMBERSHIP_RULE_NUM" NUMBER(18,0),
	"NAME" VARCHAR2(50),
	"PRD_PRODUCT_KEY" NUMBER(18,0),
	"INCLUDE_EXCLUDE_FLAG" CHAR(1),
	"IS_DIRECT_INCLUSION" CHAR(1),
	"IS_PRIMARY_PRODUCT" CHAR(1),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	"FACILITY_KEY" NUMBER(18,0),
	"IS_ORDERING_PRODUCT" CHAR(1),
	 CONSTRAINT "PK_PRODUCT_ORDERING_GROUP_MEMB" PRIMARY KEY ("PRODUCT_ORDERING_GROUP_MEM_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_PRODUCT_55" FOREIGN KEY ("PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_108" FOREIGN KEY ("FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE
   ) ;
-- ==========================================
