-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PRODUCT_INGREDIENT_BRDG"
   (	"PRD_PRODUCT_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PIB_PRODUCT_ING_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PIB_QUANTITY" NUMBER(26,8),
	"PIB_BILLING_QUANTITY" NUMBER(26,8),
	"PIB_COST" NUMBER(17,6),
	"PIB_DRUG_FORM_CODE" VARCHAR2(30),
	"PIB_NCPDP_CODE" CHAR(2),
	"PIB_FREE_FORM_NAME" VARCHAR2(50),
	"PRODUCT_INGREDIENT_NUM" NUMBER(18,0),
	"NOTE" VARCHAR2(4000),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	 CONSTRAINT "FK_PRODUCT_17" FOREIGN KEY ("PIB_PRODUCT_ING_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE,
	 CONSTRAINT "FK_PRODUCT_8" FOREIGN KEY ("PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_PRODUCT_INGREDIENT_BRDG" ON "TREXONE_DW_DATA"."PRODUCT_INGREDIENT_BRDG" ("PRD_PRODUCT_KEY", "PIB_PRODUCT_ING_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."PRODUCT_INGREDIENT_BRDG" ADD CONSTRAINT "PK_PRODUCT_INGREDIENT_BRDG" PRIMARY KEY ("PRD_PRODUCT_KEY", "PIB_PRODUCT_ING_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_PRODUCT_INGREDIENT_BRDG"  ENABLE;
-- ==========================================
