-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PRODUCT_COST_FACT"
   (	"COST_BASIS_SOURCE_VALUE_NUM" NUMBER(18,0),
	"PRD_PRODUCT_KEY" NUMBER(18,0),
	"DRUG_KEY" NUMBER(18,0),
	"COST_BASIS_SOURCE_KEY" NUMBER(18,0),
	"EFFECTIVE_DATE" DATE,
	"TERMINATION_DATE" DATE,
	"COST" NUMBER(17,6),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	"PARTITION_DATE" DATE,
	 CONSTRAINT "UC_PRODUCT_COST_FACT_01" UNIQUE ("COST_BASIS_SOURCE_KEY", "PRD_PRODUCT_KEY", "EFFECTIVE_DATE")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_PRODUCT_52" FOREIGN KEY ("PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE,
	 CONSTRAINT "FK_DRUG_22" FOREIGN KEY ("DRUG_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DRUG" ("DRUG_KEY") DISABLE,
	 CONSTRAINT "FK_COST_BASIS_SOURCE_02" FOREIGN KEY ("COST_BASIS_SOURCE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."COST_BASIS_SOURCE" ("COST_BASIS_SOURCE_KEY") DISABLE
   ) ;
-- ==========================================
