-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."PRODUCT_NOTE"
   (	"PRD_PRODUCT_KEY" NUMBER(18,0),
	"FD_FACILITY_KEY" NUMBER(18,0),
	"NOTE_NUM" NUMBER(18,0),
	"NOTE_TYPE" CHAR(1),
	"NOTE_TEXT" VARCHAR2(4000),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	 CONSTRAINT "PK_PRODUCT_NOTE" PRIMARY KEY ("PRD_PRODUCT_KEY", "FD_FACILITY_KEY", "NOTE_NUM")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_PRODUCT_NOTE_01" FOREIGN KEY ("PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE,
	 CONSTRAINT "FK_PRODUCT_NOTE_02" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE
   ) ;
-- ==========================================
