-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."RD_UNIVERSE_DATE_TYPE"
   (	"RD_UNIVERSE_ID" NUMBER(18,0) NOT NULL ENABLE,
	"RD_DATE_TYPE_ID" NUMBER(18,0) NOT NULL ENABLE,
	"STATUS_FLAG" CHAR(1),
	 CONSTRAINT "PK_RD_UNIVERSE_DATE_TYPE" PRIMARY KEY ("RD_UNIVERSE_ID", "RD_DATE_TYPE_ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_RD_UNIVERSE_DATE_TYPE_01" FOREIGN KEY ("RD_UNIVERSE_ID")
	  REFERENCES "TREXONE_DW_DATA"."RD_UNIVERSE" ("RD_UNIVERSE_ID") ENABLE,
	 CONSTRAINT "FK_RD_UNIVERSE_DATE_TYPE_02" FOREIGN KEY ("RD_DATE_TYPE_ID")
	  REFERENCES "TREXONE_DW_DATA"."RD_DATE_TYPE" ("RD_DATE_TYPE_ID") ENABLE
   ) ;
-- ==========================================
