-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."RETURN_REASON_TYPE"
   (	"RETURN_REASON_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"RETURN_REASON_TYPE" CHAR(1),
	"RETURN_REASON_NAME" VARCHAR2(30),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_RETURN_REASON_TYPE" ON "TREXONE_DW_DATA"."RETURN_REASON_TYPE" ("RETURN_REASON_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."RETURN_REASON_TYPE" ADD CONSTRAINT "PK_RETURN_REASON_TYPE" PRIMARY KEY ("RETURN_REASON_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_RETURN_REASON_TYPE"  ENABLE;
-- ==========================================
