-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."RX_FILL_INGREDIENT"
   (	"FILL_FACT_KEY" NUMBER(18,0),
	"PRD_PRODUCT_KEY" NUMBER(18,0),
	"PARTITION_DATE" DATE,
	"COST" NUMBER(17,6),
	"EXPIRATION_DATE" DATE,
	"LOT_NUMBER" VARCHAR2(20),
	"PRDC_CHAR_KEY" NUMBER(18,0),
	"NOTE" VARCHAR2(4000),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"QUANTITY" NUMBER(13,3),
	 CONSTRAINT "FK_FILL_FACT_1" FOREIGN KEY ("FILL_FACT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FILL_FACT" ("FILL_FACT_KEY") DISABLE,
	 CONSTRAINT "FK_PRODUCT_40" FOREIGN KEY ("PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE,
	 CONSTRAINT "FK_PRODUCT_CHARACTERISTICS_01" FOREIGN KEY ("PRDC_CHAR_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT_CHARACTERISTICS" ("PRDC_CHAR_KEY") DISABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
