-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."RX_REMS"
   (	"RX_REM_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"RX_REM_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"RX_RECORD_NUM" NUMBER(18,0),
	"RX_FILL_SEQ" NUMBER(18,0),
	"PRODUCT_KEY" NUMBER(18,0),
	"AUTHORIZATION_ID" VARCHAR2(20),
	"AUTHORIZATION_ID_DATE" DATE,
	"DISPENSING_ID" VARCHAR2(20),
	"DISPENSING_ID_DATE" DATE,
	"CANCEL_ID" VARCHAR2(20),
	"CANCEL_ID_DATE" DATE,
	"SYS_USER_KEY" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	 CONSTRAINT "PK_RX_REMS" PRIMARY KEY ("RX_REM_KEY")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
