-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."RX_TRANSFER_FACT"
   (	"RX_TRANSFER_FACT_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PD_PATIENT_H_KEY" NUMBER(18,0),
	"FD_FACILITY_KEY" NUMBER(18,0),
	"PRD_PRODUCT_KEY" NUMBER(18,0),
	"PRS_PRESCRIBER_KEY" NUMBER(18,0),
	"DC_DAW_CODE_KEY" NUMBER(18,0),
	"WRITTEN_DRUG_KEY" NUMBER(18,0),
	"RX_TRANSFER_TYPE_KEY" NUMBER(18,0),
	"RX_TRANSFER_METHOD_KEY" NUMBER(18,0),
	"TRANSFER_DATE_KEY" NUMBER(18,0),
	"TRANSFER_TIME_KEY" NUMBER(5,0),
	"PARTITION_DATE" DATE,
	"RX_FILL_SEQ" NUMBER(18,0),
	"PRS_FIRST_NAME" VARCHAR2(30),
	"PRS_MIDDLE_NAME" VARCHAR2(30),
	"PRS_LAST_NAME" VARCHAR2(30),
	"PATIENT_PRICE_PAID" NUMBER(18,6),
	"TOTAL_PRICE_PAID" NUMBER(18,6),
	"USER_DEFINED_STEP_AMT" NUMBER,
	"TOTAL_UNC" NUMBER(19,8),
	"OVERRIDE_AMOUNT" NUMBER(17,6),
	"TRANSFER_SEQ" NUMBER(18,0),
	"PRESCRIPTION_NUM" VARCHAR2(20),
	"HARDCOPY_RX_NUM" NUMBER(18,0),
	"HARDCOPY_LOCATION" VARCHAR2(50),
	"COMPETITOR_PRICE" NUMBER(17,6),
	"FIRST_FILL_DATE" DATE,
	"LAST_FILL_DATE" DATE,
	"NUM_REFILLS" NUMBER(9,0),
	"REFILLS_REMAINING" NUMBER(9,3),
	"RX_NUMBER" VARCHAR2(20),
	"RX_RECORD_NUM" NUMBER(18,0),
	"LOCAL_PHARMACIST_NAME" VARCHAR2(45),
	"REMOTE_PHARMACIST_NAME" VARCHAR2(45),
	"SENDING_PHARMACIST" VARCHAR2(45),
	"RECEIVING_PHARMACIST" VARCHAR2(45),
	"REFILL_NUM" NUMBER(18,0),
	"FACILITY_NAME" VARCHAR2(50),
	"THIRD_PARTY_IND" CHAR(1),
	"PARTIAL_IND" CHAR(1),
	"TRANSACTION_CODE" VARCHAR2(100),
	"QTY_DISPENSED" NUMBER(13,3),
	"SIG" VARCHAR2(2000),
	"READY_DATE_KEY" NUMBER(18,0),
	"SOLD_DATE_KEY" NUMBER(18,0),
	"REC_PHARMACY_ADDR1" VARCHAR2(100),
	"REC_PHARMACY_ADDR2" VARCHAR2(50),
	"REC_PHARMACY_CITY" VARCHAR2(40),
	"REC_PHARMACY_STATE" VARCHAR2(2),
	"REC_PHARMACY_ZIP" VARCHAR2(10),
	"REC_PHARMACY_PHONE" VARCHAR2(10),
	"REC_PHARMACY_FAX" VARCHAR2(10),
	"TOTAL_TP_PAID" NUMBER(18,6),
	"TOTAL_TAX" NUMBER(18,6),
	"CANCEL_DATE_KEY" NUMBER(18,0),
	"REC_PHARMACY_DEA" VARCHAR2(30),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PD_PATIENT_KEY" NUMBER(18,0),
	"CRF_SEQ_NUM" NUMBER,
	"PADR_KEY" NUMBER(18,0),
	"DISPENSED_PRD_PRODUCT_KEY" NUMBER(18,0),
	"TRANSFER_REASON" VARCHAR2(50),
	"TRANSFER_TO_RX_RECORD_NUM" VARCHAR2(20),
	"FACILITY_ID" VARCHAR2(10),
	"COMPETITOR_GROUP_CODE" VARCHAR2(15),
	"COMPETITOR_GROUP_NAME" VARCHAR2(30),
	"STORE_NUMBER" VARCHAR2(10),
	 CONSTRAINT "FK_DATE_DIM_91" FOREIGN KEY ("READY_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_92" FOREIGN KEY ("SOLD_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_RTF_DAW_CODE_TYPE" FOREIGN KEY ("DC_DAW_CODE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DAW_CODE_TYPE" ("DC_DAW_CODE_KEY") DISABLE,
	 CONSTRAINT "FK_RTF_DRUG" FOREIGN KEY ("WRITTEN_DRUG_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DRUG" ("DRUG_KEY") DISABLE,
	 CONSTRAINT "FK_RTF_FACILITY" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_RTF_PATIENT_H" FOREIGN KEY ("PD_PATIENT_H_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT_H" ("PD_PATIENT_H_KEY") DISABLE,
	 CONSTRAINT "FK_RTF_PRESCRIBER" FOREIGN KEY ("PRS_PRESCRIBER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRESCRIBER" ("PRS_PRESCRIBER_KEY") DISABLE,
	 CONSTRAINT "FK_RTF_PRODUCT" FOREIGN KEY ("PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE,
	 CONSTRAINT "FK_RTF_TRANSFER_DATE_KEY" FOREIGN KEY ("TRANSFER_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_RTF_TRANSFER_TIME_KEY" FOREIGN KEY ("TRANSFER_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE,
	 CONSTRAINT "FK_RX_TRANSFER_METHOD_KEY" FOREIGN KEY ("RX_TRANSFER_METHOD_KEY")
	  REFERENCES "TREXONE_DW_DATA"."RX_TRANSFER_METHOD_TYPE" ("RX_TRANSFER_METHOD_KEY") DISABLE,
	 CONSTRAINT "FK_RX_TRANSFER_TYPE_KEY" FOREIGN KEY ("RX_TRANSFER_TYPE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."RX_TRANSFER_TYPE" ("RX_TRANSFER_TYPE_KEY") DISABLE,
	 CONSTRAINT "FK_RTF_PATIENT" FOREIGN KEY ("PD_PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") DISABLE,
	 CONSTRAINT "FK_PRESCRIBER_ADDRESS_09" FOREIGN KEY ("PADR_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRESCRIBER_ADDRESS" ("PADR_KEY") DISABLE,
	 CONSTRAINT "FK_PRODUCT_49" FOREIGN KEY ("DISPENSED_PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_120" FOREIGN KEY ("CANCEL_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE
   )
  PARTITION BY RANGE ("PARTITION_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_RX_TRANSFER_FACT_KEY" ON "TREXONE_DW_DATA"."RX_TRANSFER_FACT" ("RX_TRANSFER_FACT_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."RX_TRANSFER_FACT" ADD CONSTRAINT "PK_RX_TRANSFER_FACT_KEY" PRIMARY KEY ("RX_TRANSFER_FACT_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_RX_TRANSFER_FACT_KEY"  ENABLE;
-- ==========================================
