-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."RX_TRANSFER_METHOD_TYPE"
   (	"RX_TRANSFER_METHOD_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"RX_TRANSFER_METHOD_IND" VARCHAR2(12),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_RX_TRANSFER_METHOD_KEY" ON "TREXONE_DW_DATA"."RX_TRANSFER_METHOD_TYPE" ("RX_TRANSFER_METHOD_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."RX_TRANSFER_METHOD_TYPE" ADD CONSTRAINT "PK_RX_TRANSFER_METHOD_KEY" PRIMARY KEY ("RX_TRANSFER_METHOD_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_RX_TRANSFER_METHOD_KEY"  ENABLE;
-- ==========================================
