-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."SCANNED_DOCUMENT_TYPE"
   (	"SCANNED_DOCUMENT_TYPE_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"SCANNED_DOCUMENT_TYPE_NUM" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(100),
	"ENABLED" CHAR(1),
	"DEFAULT_VALUE" CHAR(1),
	"SYS_USER_KEY" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "PK_SCANNED_DOCUMENT_TYPE" PRIMARY KEY ("SCANNED_DOCUMENT_TYPE_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SYS_USER_110" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") ENABLE
   ) ;
-- ==========================================
