-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."SCHEDULE_TIME"
   (	"SCHEDULE_TIME_KEY" NUMBER(2,0),
	"SCHEDULE_TIME_NUMBER" NUMBER(2,0),
	"SCHEDULE_TIME_DESC" VARCHAR2(20),
	"MINUTES_AFTER_MIDNIGHT" NUMBER(4,0),
	"TIME_OF_DAY" VARCHAR2(5),
	"IS_OPEN_ALL_DAY" CHAR(1),
	"IS_CLOSED_ALL_DAY" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "PK_SCHEDULE_TIME" PRIMARY KEY ("SCHEDULE_TIME_KEY")
  USING INDEX  ENABLE
   ) ;
-- ==========================================
