-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."SPECIALTY_PROGRAM_PRODUCT_LIST"
   (	"SPECIALTY_PROGRAM_TO_PRDCT_KEY" NUMBER(18,0),
	"SPECIALTY_PROGRAM_TO_PRDCT_NUM" NUMBER(18,0),
	"SPECIALTY_PROGRAM_KEY" NUMBER(18,0),
	"PRD_PRODUCT_KEY" NUMBER(18,0),
	"SYS_USER_KEY" NUMBER(18,0),
	"H_LEVEL" NUMBER(20,0),
	"H_TYPE" VARCHAR2(1),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	 CONSTRAINT "PK_SPECIALTY_PRGRAM_TO_PRODUCT" PRIMARY KEY ("SPECIALTY_PROGRAM_TO_PRDCT_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SYS_USER_120" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_SPECIALTY_PROGRAM_05" FOREIGN KEY ("SPECIALTY_PROGRAM_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SPECIALTY_PROGRAM" ("SPECIALTY_PROGRAM_KEY") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_PRODUCT_60" FOREIGN KEY ("PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") ENABLE NOVALIDATE
   ) ;
-- ==========================================
