-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."SPECIALTY_PROG_LOT_ITEM_LIST"
   (	"SPECIALTY_PROG_LOT_ITM_LST_KEY" NUMBER(18,0),
	"SPECIALTY_PROG_LOT_ITM_LST_NUM" NUMBER(18,0),
	"INVENTORY_LOT_KEY" NUMBER(18,0),
	"SPECIALTY_PROGRAM_KEY" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"DATESTAMP" DATE,
	"SYS_USER_KEY" NUMBER(18,0),
	"H_LEVEL" NUMBER,
	"H_TYPE" VARCHAR2(1),
	 CONSTRAINT "PK_SPECIALTY_PROG_LOT_ITM_LST" PRIMARY KEY ("SPECIALTY_PROG_LOT_ITM_LST_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_SYS_USER_145" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_INVENTORY_LOT_03" FOREIGN KEY ("INVENTORY_LOT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."INVENTORY_LOT" ("INVENTORY_LOT_KEY") ENABLE NOVALIDATE,
	 CONSTRAINT "FK_SPECIALTY_PROGRAM_04" FOREIGN KEY ("SPECIALTY_PROGRAM_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SPECIALTY_PROGRAM" ("SPECIALTY_PROGRAM_KEY") ENABLE NOVALIDATE
   ) ;
-- ==========================================
