-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."SYS_USER_LOGON_AUDIT"
   (	"FD_FACILITY_KEY" NUMBER(18,0),
	"SYS_USER_KEY" NUMBER(18,0),
	"DATE_KEY" NUMBER(18,0),
	"SULA_LOGON_ACTION_IND" CHAR(1),
	"SULA_SYS_USER_NUM" NUMBER(18,0),
	"SULA_DATESTAMP" DATE,
	"TIME_KEY" NUMBER(5,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	 CONSTRAINT "FK_DATE_DIM_30" FOREIGN KEY ("DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_32" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_SYS_USER_34" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_16" FOREIGN KEY ("TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE
   )
  PARTITION BY RANGE ("SULA_DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
