-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."TOTE"
   (	"TOTE_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"TOTE_ID" VARCHAR2(7),
	"TOTE_NUM" NUMBER(18,0),
	"FACILITY_NUM" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_TOTE" ON "TREXONE_DW_DATA"."TOTE" ("TOTE_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."TOTE" ADD CONSTRAINT "PK_TOTE" PRIMARY KEY ("TOTE_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_TOTE"  ENABLE;
-- ==========================================
