-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."TP_NETWORK_FACILITY"
   (	"TPLD_PLAN_KEY" NUMBER(18,0),
	"FD_FACILITY_KEY" NUMBER(18,0),
	"TP_NETWORK_NUM" NUMBER(18,0),
	"TP_NETWORK_NAME" VARCHAR2(45),
	"TP_NETWORK_DESC" VARCHAR2(255),
	"EFF_START_DATE" DATE,
	"EFF_END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100) DEFAULT sys_context('ERX_CONTEXT', 'ERX_CLIENT_ID'),
	 CONSTRAINT "FK_TP_PLAN_10" FOREIGN KEY ("TPLD_PLAN_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TP_PLAN" ("TPLD_PLAN_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_96" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE
   ) ;
-- ==========================================
