-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."TP_PROCESSOR"
   (	"TP_PROCESSOR_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"TP_PROCESSOR_NUM" NUMBER(18,0),
	"TP_PROCESSOR_GROUP_NUM" NUMBER(18,0),
	"NAME" VARCHAR2(45),
	"CONTACT_NAME" VARCHAR2(45),
	"EFFECTIVE_DATE" DATE,
	"TERMINATION_DATE" DATE,
	"ARCHIVE_LEVEL" NUMBER(9,0),
	"SYS_USER" NUMBER(18,0),
	"DATESTAMP" DATE,
	"NUM_UPDATES" NUMBER(9,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE INDEX "TREXONE_DW_DATA"."IN_TP_PROCESSOR_01" ON "TREXONE_DW_DATA"."TP_PROCESSOR" ("TP_PROCESSOR_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."TP_PROCESSOR" ADD CONSTRAINT "PK_TP_PROCESSOR" PRIMARY KEY ("TP_PROCESSOR_KEY")
  USING INDEX "TREXONE_DW_DATA"."IN_TP_PROCESSOR_01"  ENABLE;
-- ==========================================
