-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."TP_WORKERS_COMP"
   (	"TWED_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"TWED_EMPLOYER_NAME" VARCHAR2(30),
	"TWED_EMPLOYER_CONTACT_NAME" VARCHAR2(30),
	"TWED_EMPLOYER_ID" VARCHAR2(15),
	"TWED_EMPLOYER_TAX_ID" VARCHAR2(15),
	"TWED_CARRIER_ID" VARCHAR2(10),
	"TWED_CARRIER_NAME" VARCHAR2(25),
	"TWED_CARRIER_INSURANCE_ID" VARCHAR2(15),
	"TWED_CARRIER_CONTACT_NAME" VARCHAR2(30),
	"TWED_APPROVAL_NUMBER" VARCHAR2(30),
	"TWED_REFILLS_AUTHORIZED" NUMBER(9,0),
	"TWED_DIAGNOSIS_CODE_SUBMITTED" VARCHAR2(15),
	"TWED_CLAIM_EFFECTIVE_DATE" DATE,
	"TWED_TP_WRKRS_CMP_CLM_NUM" NUMBER(18,0),
	"TWED_ACTIVE_STATUS" CHAR(1),
	"TWED_CLAIM_REFERENCE_ID" VARCHAR2(30),
	"TWED_INJURY_DESCRIPTION" VARCHAR2(60),
	"TWED_DATE_OF_INJURY" DATE,
	"TWED_CLAIM_TERMINATION_DATE" DATE,
	"TWED_CLAIM_AUTHORIZED_BY" VARCHAR2(60),
	"PD_PATIENT_H_KEY" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PD_PATIENT_KEY" NUMBER(18,0),
	"H_LEVEL" NUMBER,
	"EMPLOYER_ADDRESS1" VARCHAR2(100),
	"EMPLOYER_ADDRESS2" VARCHAR2(50),
	"EMPLOYER_CITY" VARCHAR2(40),
	"EMPLOYER_STATE_CODE" VARCHAR2(2),
	"EMPLOYER_ZIP_CODE" VARCHAR2(20),
	"EMPLOYER_PHONE_NUMBER" VARCHAR2(30),
	"EMPLOYER_FAX_NUMBER" VARCHAR2(30),
	"CARRIER_ADDRESS1" VARCHAR2(100),
	"CARRIER_ADDRESS2" VARCHAR2(50),
	"CARRIER_CITY" VARCHAR2(40),
	"CARRIER_STATE_CODE" VARCHAR2(2),
	"CARRIER_ZIP_CODE" VARCHAR2(20),
	"CARRIER_PHONE_NUMBER" VARCHAR2(30),
	"CARRIER_FAX_NUMBER" VARCHAR2(30),
	"PAYEE_NAME" VARCHAR2(20),
	"PAYEE_ADDRESS1" VARCHAR2(100),
	"PAYEE_CITY" VARCHAR2(40),
	"PAYEE_STATE" VARCHAR2(2),
	"PAYEE_ZIP" VARCHAR2(20),
	 CONSTRAINT "FK_PATIENT_H_35" FOREIGN KEY ("PD_PATIENT_H_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT_H" ("PD_PATIENT_H_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_35" FOREIGN KEY ("PD_PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") DISABLE
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_TP_WORKERS_COMP" ON "TREXONE_DW_DATA"."TP_WORKERS_COMP" ("TWED_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."TP_WORKERS_COMP" ADD CONSTRAINT "PK_TP_WORKERS_COMP" PRIMARY KEY ("TWED_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_TP_WORKERS_COMP"  ENABLE;
-- ==========================================
