-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."USER_LICENSE"
   (	"UL_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"UL_USER_LICENSE_NUM" NUMBER(18,0),
	"UL_SYSTEM_USER_NUM" NUMBER(18,0),
	"UL_CTRY_CODE" VARCHAR2(8),
	"UL_STATE_CODE" VARCHAR2(2),
	"UL_LICENSE_NUMBER" VARCHAR2(15),
	"UL_LICENSE_TYPE" CHAR(1),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_USER_LICENSE" ON "TREXONE_DW_DATA"."USER_LICENSE" ("UL_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."USER_LICENSE" ADD CONSTRAINT "PK_USER_LICENSE" PRIMARY KEY ("UL_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_USER_LICENSE"  ENABLE;
-- ==========================================
