-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."USER_LOGIN"
   (	"USER_LOGIN_KEY" NUMBER(18,0),
	"FACILITY_KEY" NUMBER(18,0),
	"SYS_USER_KEY" NUMBER(18,0),
	"LOGIN_DATE_KEY" NUMBER(18,0),
	"LOGIN_TIME_KEY" NUMBER(6,0),
	"LOGIN_DATESTAMP" DATE,
	"DATESTAMP" DATE,
	"FACILITY_LOGIN_NUM" NUMBER(18,0),
	"H_LEVEL" NUMBER,
	"ERX_CLIENT_ID" VARCHAR2(100),
	 CONSTRAINT "PK_USER_LOGIN" PRIMARY KEY ("USER_LOGIN_KEY")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_FACILITY_112" FOREIGN KEY ("FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_SYS_USER_94" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE,
	 CONSTRAINT "FK_DATE_DIM_151" FOREIGN KEY ("LOGIN_DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_TIME_DIM_64" FOREIGN KEY ("LOGIN_TIME_KEY")
	  REFERENCES "TREXONE_DW_DATA"."TIME_DIM" ("TIME_KEY") DISABLE
   )
  PARTITION BY RANGE ("DATESTAMP") INTERVAL (NUMTODSINTERVAL(1,'DAY')) STORE IN ("DW_LARGE_DATA01")
 (PARTITION "P_MINVALUE"  VALUES LESS THAN (TO_DATE(' 2010-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
