-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."VENDOR"
   (	"VENDOR_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"VENDOR_NUM" NUMBER(18,0),
	"NAME" VARCHAR2(30),
	"ADDRESS1" VARCHAR2(100),
	"ADDRESS2" VARCHAR2(50),
	"CITY" VARCHAR2(50),
	"STATE" VARCHAR2(2),
	"ZIP_CODE" VARCHAR2(20),
	"COUNTRY_CODE" VARCHAR2(8),
	"PHONE_NUMBER" VARCHAR2(20),
	"FAX_NUMBER" VARCHAR2(20),
	"CONTACT_INFO" VARCHAR2(10),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_VENDOR" ON "TREXONE_DW_DATA"."VENDOR" ("VENDOR_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."VENDOR" ADD CONSTRAINT "PK_VENDOR" PRIMARY KEY ("VENDOR_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_VENDOR"  ENABLE;
-- ==========================================
