-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."VENDOR_PRICE_CATALOG"
   (	"VENDOR_PRICE_CATALOG_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"PRD_PRODUCT_KEY" NUMBER(18,0),
	"DRUG_KEY" NUMBER(18,0),
	"FD_FACILITY_KEY" NUMBER(18,0),
	"VENDOR_KEY" NUMBER(18,0),
	"VENDOR_ITEM_NUM" NUMBER(18,0),
	"VENDOR_PRODUCT_ID" VARCHAR2(48),
	"PKG_SIZE" NUMBER(16,8),
	"UNIT_PRICE" NUMBER(17,6),
	"UNIT_PRICE_DATE" DATE,
	"PURCHASE_INCREMENT" NUMBER(9,0),
	"STATUS" CHAR(1),
	"AVG_LEAD_TIME" NUMBER(9,0),
	"MIN_ORDER_QTY" NUMBER(16,8),
	"EFFECTIVE_START_DATE" DATE,
	"EFFECTIVE_END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER,
	"SYS_USER_KEY" NUMBER(18,0),
	 CONSTRAINT "FK_DRUG_16" FOREIGN KEY ("DRUG_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DRUG" ("DRUG_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_85" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_PRODUCT_42" FOREIGN KEY ("PRD_PRODUCT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRODUCT" ("PRD_PRODUCT_KEY") DISABLE,
	 CONSTRAINT "FK_VENDOR_04" FOREIGN KEY ("VENDOR_KEY")
	  REFERENCES "TREXONE_DW_DATA"."VENDOR" ("VENDOR_KEY") DISABLE
   )
  PARTITION BY RANGE ("EFFECTIVE_START_DATE") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_VENDOR_PRICE_CATALOG" ON "TREXONE_DW_DATA"."VENDOR_PRICE_CATALOG" ("VENDOR_PRICE_CATALOG_KEY")
  ;
ALTER TABLE "TREXONE_DW_DATA"."VENDOR_PRICE_CATALOG" ADD CONSTRAINT "PK_VENDOR_PRICE_CATALOG" PRIMARY KEY ("VENDOR_PRICE_CATALOG_KEY")
  USING INDEX "TREXONE_DW_DATA"."PK_VENDOR_PRICE_CATALOG"  ENABLE;
-- ==========================================
