-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."VENDOR_CONFIG_BCK"
   (	"VENDOR_CONFIG_KEY" NUMBER(18,0) NOT NULL ENABLE,
	"VENDOR_KEY" NUMBER(18,0),
	"ACCOUNT_NUMBER" VARCHAR2(16),
	"SENDER_ID" VARCHAR2(16),
	"RECEIVER_ID" VARCHAR2(16),
	"PURCHASE_ORDER_SORT_CODE" CHAR(1),
	"LEAD_TIME" NUMBER(9,0),
	"AUTO_TRANSMIT_PO_FLAG" CHAR(1),
	"DELIVERS_ON_SUNDAY" CHAR(1),
	"DELIVERS_ON_MONDAY" CHAR(1),
	"DELIVERS_ON_TUESDAY" CHAR(1),
	"DELIVERS_ON_WEDNESDAY" CHAR(1),
	"DELIVERS_ON_THURSDAY" CHAR(1),
	"DELIVERS_ON_FRIDAY" CHAR(1),
	"DELIVERS_ON_SATURDAY" CHAR(1),
	"C2_PO_STATUS" CHAR(1),
	"RANK" NUMBER(9,0),
	"IS_ACTIVE" CHAR(1),
	"FD_FACILITY_KEY" NUMBER(18,0),
	"EFFECTIVE_START_DATE" DATE,
	"EFFECTIVE_END_DATE" DATE,
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER(20,0),
	"DATESTAMP" DATE,
	"VENDOR_CONFIGURATION_NUM" NUMBER(18,0)
   ) ;
-- ==========================================
