-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."WEB_ORDER"
   (	"DATE_KEY" NUMBER(18,0),
	"FD_FACILITY_KEY" NUMBER(18,0),
	"SYS_USER_KEY" NUMBER(18,0),
	"UA_KEY" NUMBER(18,0),
	"WO_WEB_ORDER_NUM" NUMBER(18,0),
	"WO_ELECTRONIC_ORDER_NUM" NUMBER(18,0),
	"WO_CUST_WEB_ORDER" VARCHAR2(12),
	"WO_CUST_PHONE" VARCHAR2(12),
	"WO_PICKUP_DATE" DATE,
	"WO_COMMENTS" VARCHAR2(256),
	"WO_WEB_ORDER_ITEM_NUM" NUMBER(18,0),
	"WO_WEB_ORDER_SEQ" NUMBER(9,0),
	"WO_RX_NUMBER" VARCHAR2(20),
	"WO_IS_ERROR" CHAR(1),
	"WO_RX_COMMENT" VARCHAR2(256),
	"PRS_PRESCRIBER_KEY" NUMBER(18,0),
	"PD_PATIENT_H_KEY" NUMBER(18,0),
	"WO_CREATE_DT" DATE,
	"WO_REFILL_NUM" NUMBER(18,0),
	"WO_RX_RECORD_NUM" NUMBER(18,0),
	"WO_RX_FILL_SEQ" NUMBER(18,0),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"PD_PATIENT_KEY" NUMBER(18,0),
	"H_LEVEL" NUMBER,
	 CONSTRAINT "FK_DATE_DIM_56" FOREIGN KEY ("DATE_KEY")
	  REFERENCES "TREXONE_DW_DATA"."DATE_DIM" ("DATE_KEY") DISABLE,
	 CONSTRAINT "FK_FACILITY_59" FOREIGN KEY ("FD_FACILITY_KEY")
	  REFERENCES "TREXONE_DW_DATA"."FACILITY" ("FD_FACILITY_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_H_611" FOREIGN KEY ("PD_PATIENT_H_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT_H" ("PD_PATIENT_H_KEY") DISABLE,
	 CONSTRAINT "FK_PRESCRIBER_6" FOREIGN KEY ("PRS_PRESCRIBER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PRESCRIBER" ("PRS_PRESCRIBER_KEY") DISABLE,
	 CONSTRAINT "FK_SYS_USER_63" FOREIGN KEY ("SYS_USER_KEY")
	  REFERENCES "TREXONE_DW_DATA"."SYS_USER" ("SYS_USER_KEY") DISABLE,
	 CONSTRAINT "FK_USER_ACTION_TYPE_614" FOREIGN KEY ("UA_KEY")
	  REFERENCES "TREXONE_DW_DATA"."USER_ACTION_TYPE" ("UA_KEY") DISABLE,
	 CONSTRAINT "FK_PATIENT_611" FOREIGN KEY ("PD_PATIENT_KEY")
	  REFERENCES "TREXONE_DW_DATA"."PATIENT" ("PD_PATIENT_KEY") DISABLE
   )
  PARTITION BY RANGE ("WO_CREATE_DT") INTERVAL (NUMTODSINTERVAL(1,'DAY'))
 (PARTITION "P_20120308"  VALUES LESS THAN (TO_DATE(' 2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) ) ;
-- ==========================================
