-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."WF_STEP_XREF"
   (	"WF_BLOCK_DEFINITION_NUM" NUMBER,
	"WFSD_STEP_CODE" VARCHAR2(2),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;
  CREATE UNIQUE INDEX "TREXONE_DW_DATA"."PK_WF_STEP_XREF" ON "TREXONE_DW_DATA"."WF_STEP_XREF" ("WF_BLOCK_DEFINITION_NUM")
  ;
ALTER TABLE "TREXONE_DW_DATA"."WF_STEP_XREF" ADD CONSTRAINT "PK_WF_STEP_XREF" PRIMARY KEY ("WF_BLOCK_DEFINITION_NUM")
  USING INDEX "TREXONE_DW_DATA"."PK_WF_STEP_XREF"  ENABLE;
-- ==========================================
