-- ==========================================

  CREATE TABLE "TREXONE_DW_DATA"."ZIPCODE"
   (	"CSZ_NUM" NUMBER(18,0),
	"ZIPCODE" VARCHAR2(20),
	"CTRY_CODE" VARCHAR2(8),
	"STATE_CODE" VARCHAR2(2),
	"COUNTY" VARCHAR2(30),
	"CITY" VARCHAR2(40),
	"POST_OFFICE" VARCHAR2(40),
	"ERX_CLIENT_ID" VARCHAR2(100),
	"H_LEVEL" NUMBER
   ) ;

